### ISSUE TITLE
Allow building on Java 9+

### ISSUE THREAD

**Issue by efenderbosch** [localstack/localstack#1028] opened 2018-11-28 16:45 UTC
We've started using ``localstack-utils`` to perform some simple tests with the end goal of simulating standup-the-world situations.  Adding ``AWSSimpleSystemsManagement`` (and other missing services) to  ``TestUtils`` and ``DockerTestUtils`` as well as async versions of the service clients would be useful.

I tried forking the project and adding it myself with the intent of submitting a pull request, but I can't get it to build. I am using Java 10, though.

A couple quick fixes to get it to build under Java 10:

-  update ``lombok`` from 1.16.20 to 1.16.22. See this issue: https://github.com/rzwitserloot/lombok/issues/1651

- JAXB needs to be included:

```xml
        <!-- required to build on java 9+ -->
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
            <scope>provided</scope>
        </dependency>
```

Now I can build, but tests fail. It is having trouble finding ``virtualenv``.

When I run ``make install`` I get this:

```sh
make install
(test `which virtualenv` || pip install --user virtualenv) && \
		(test -e .venv || virtualenv  .venv) && \
		(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
		. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Requirement already satisfied: virtualenv in /Users/efenderbosch/Library/Python/2.7/lib/python/site-packages (16.1.0)
/bin/sh: virtualenv: command not found
```

I was able to fix that with ``chmod +x virtualenv.py`` and ``ln -s virtualenv.py virtualenv`` but that seems like a hack. I haven't investigated how to make this more seamless.

Now most of the tests will actually run and pass. Several throw ``java.lang.ClassNotFoundException`` and/or ``java.lang.LinkageError`` when looking for ``java.lang.UNIXProcess`` in ``org.ow2.proactive.process_tree_killer.ProcessTree`` but they still complete successfully. I'm running MacOS High Sierra 10.13.6.

3 tests fail, however:

``ContainerTest::createLocalstackContainerWithStaticPorts`` fails with ``java.lang.IllegalArgumentException: Port: 4567 does not exist`` 

``DockerOnlySQSFunctionalityTest::testSQSRunning`` fails twice, once for vintage and once for jupiter. Both throw ``com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 502; Error Code: 502 Bad Gateway; Request ID: null)``

At this point, I can't really invest more time trying to get this building. Hopefully this is a good starting point for someone else.

I'll open a separate issue to have SSM and async services added to ``TestUtils`` and ``DockerTestUtils``

**Comment by AndyMacDroo** [comment] 2019-01-12 19:37
Thanks for your notes thus far - I can see at least one of the causes of the test failures `ContainerTest::createLocalstackContainerWithStaticPorts`

When I switch the tests to run in JDK <= 1.8, as expected, all tests pass. When running in JDK higher than 1.8 it seems that the localstack docker containers are conflicting with the ports of localstack services already running (it seems from the prior tests installing and running localstack in `/tmp/` rather than the services running via the docker container) - which causes the docker container to fail to start (and obviously the ports to fail to register in the test).

```
INFO: Started container: 62bd6867df18c885111b69e94b3a42f6830a8973da2265832e3656ece487256e
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint sharp_hofstadter (6b5d95e6a210a48beb2f76e8b613f174f6ecc09687a0e0193ca8eeec700529bc): Error starting userland proxy: listen tcp 0.0.0.0:4583: bind: address already in use.
Jan 12, 2019 7:15:04 PM cloud.localstack.docker.Container stop
INFO: Stopped container: 62bd6867df18c885111b69e94b3a42f6830a8973da2265832e3656ece487256e
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint sharp_hofstadter (6b5d95e6a210a48beb2f76e8b613f174f6ecc09687a0e0193ca8eeec700529bc): Error starting userland proxy: listen tcp 0.0.0.0:4583: bind: address already in use.

java.lang.IllegalArgumentException: Port: 4567 does not exist
```
I suspect for this situation, it's either a change in test ordering given the newer JDK and the tests didn't clean up and stop the services very well after themselves - or it's a failure of the test cleanup routines which then leaves the localstack services running. 

I'm more inclined to the latter given that after the tests fail, I still see localstack running - but don't see the same with JDK <=1.8:
```
andy@andy-G3-3579:~$ sudo netstat -tulpn | grep 4583
tcp        0      0 0.0.0.0:4583            0.0.0.0:*               LISTEN      7730/python2
```

I'm new to the project so I'll invest some time to do some more digging and hopefully follow up with a PR for this and the other issues.

**Comment by AndyMacDroo** [comment] 2019-01-12 19:40
I think a better approach for the virtualenv issue is this:
```
install:           ## Install dependencies in virtualenv
	(test `which virtualenv` || $(PIP_CMD) install --user virtualenv) && \
		(test -e $(VENV_DIR) || python -m virtualenv $(VENV_OPTS) $(VENV_DIR)) && \
		(test ! -e requirements.txt || ($(VENV_RUN); $(PIP_CMD) -q install -r requirements.txt) && \
		$(VENV_RUN); PYTHONPATH=. exec python localstack/services/install.py testlibs)
```

Which is more resistent to discrepancies with whether virtualenv gets installed and added to the right part of the system PATH or not.

**Comment by AndyMacDroo** [comment] 2019-01-12 19:50
Actually I'm pretty certain it is a failure of the test cleanup routines. 

The `ClassNotFoundException` on the test referencing `java.lang.UNIXProcess` is probably the cause of the other test(s) failure in the docker container.

The `ProcessTree` class seems responsible for killing processes - if the processes can't be killed, they stay running and thus the ports conflict with any docker containers that try to use those ports that are already bound:

```java
        static {
            try {
                Class<?> clazz = Class.forName("java.lang.UNIXProcess");
                PID_FIELD = clazz.getDeclaredField("pid");
                PID_FIELD.setAccessible(true);

                if (isPreJava8()) {
                    DESTROY_PROCESS = clazz.getDeclaredMethod("destroyProcess", int.class);
                } else {
                    DESTROY_PROCESS = clazz.getDeclaredMethod("destroyProcess", int.class, boolean.class);
                }
                DESTROY_PROCESS.setAccessible(true);
            } catch (ClassNotFoundException e) {
                LinkageError x = new LinkageError();
                x.initCause(e);
                throw x;
            } catch (NoSuchFieldException e) {
                LinkageError x = new LinkageError();
                x.initCause(e);
                throw x;
            } catch (NoSuchMethodException e) {
                LinkageError x = new LinkageError();
                x.initCause(e);
                throw x;
            }
        }
```

I think this is relatively straightforward to solve so a PR should be forthcoming :smile:

**Comment by AndyMacDroo** [comment] 2019-01-12 21:35
Here we go:
https://github.com/localstack/localstack/pull/1087

**Comment by AndyMacDroo** [comment] 2019-01-29 21:06
Can we mark this as closed given the PR?

**Comment by whummer** [comment] 2019-03-17 23:02
Great, thanks for the PR @AndyMacDroo - closing this issue 👍

**Closed by whummer** 2019-03-17 23:02 UTC
