### ISSUE TITLE
Deploying lambda on Localstack docker - Permission Issue

### ISSUE THREAD

**Issue by jitesh-prajapati** [localstack/localstack#598] opened 2018-02-05 13:29 UTC
I have run localstack on docker. (localstack start --docker) - Works fine.

While creating lambda functions it gives me following error.
ERROR: 'mkdir -p /tmp/localstack/zipfile.d5e39381': mkdir: can't create directory '/tmp/localstack/zipfile.d5e39381': Permission denied

May be in container /tmp/localstack is not writable.

Can you please guide me on this?

- Jitesh

**Comment by whummer** [comment] 2018-02-05 13:40
Thanks for reporting @jitesh-prajapati . When you start `localstack` it prints the docker command like so: 
```
localstack start --docker
Starting local dev environment. CTRL-C to quit.
docker run -it -e LOCALSTACK_HOSTNAME="localhost" ...
```
Can you please post the exact command?

Please also post the output of these commands:
```
ls -la $TMPDIR
ls -la $TMPDIR/localstack
```

**Comment by jitesh-prajapati** [comment] 2018-02-06 05:23
Please find following output
-----------------------------------------
Starting local dev environment. CTRL-C to quit.
docker run -it -e HOSTNAME="icpl10379" -e LOCALSTACK_HOSTNAME="icpl10379" -p 8080:8080 -p 443:443 -p 4567-4583:4567-4583 -p 4590-4593:4590-4593 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
2018-02-06 05:21:43,844 CRIT Supervisor running as root (no user in config file)
2018-02-06 05:21:43,846 INFO supervisord started with pid 1
2018-02-06 05:21:44,848 INFO spawned: 'dashboard' with pid 9
2018-02-06 05:21:44,850 INFO spawned: 'infra' with pid 10
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
2018-02-06T05:21:45:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2018-02-06T05:21:45:INFO:werkzeug:  * Restarting with stat
Error starting infrastructure: [Errno 13] Permission denied: '/tmp/localstack/.localstack' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 450, in start_infra
event_publisher.fire_event(event_publisher.EVENT_START_INFRA)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 152, in fire_event
event = AnalyticsEvent(event_type=event_type, payload=payload)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 37, in __init__
self.m_id = kwargs.get('machine_id') or kwargs.get('m_id') or get_machine_id()
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 87, in get_machine_id
local_configs = load_file(config_file)
File "/opt/code/localstack/localstack/utils/common.py", line 424, in load_file
with open(file_path, mode) as f:
IOError: [Errno 13] Permission denied: '/tmp/localstack/.localstack'

ERROR: [Errno 13] Permission denied: '/tmp/localstack/.localstack'
2018-02-06 05:21:45,369 INFO exited: infra (exit status 0; not expected)
2018-02-06T05:21:45:WARNING:werkzeug:  * Debugger is active!
2018-02-06T05:21:45:INFO:werkzeug:  * Debugger PIN: 194-322-425
2018-02-06 05:21:46,729 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-06 05:21:46,731 INFO spawned: 'infra' with pid 31
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
Error starting infrastructure: [Errno 13] Permission denied: '/tmp/localstack/.localstack' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 450, in start_infra
event_publisher.fire_event(event_publisher.EVENT_START_INFRA)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 152, in fire_event
event = AnalyticsEvent(event_type=event_type, payload=payload)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 37, in __init__
self.m_id = kwargs.get('machine_id') or kwargs.get('m_id') or get_machine_id()
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 87, in get_machine_id
local_configs = load_file(config_file)
File "/opt/code/localstack/localstack/utils/common.py", line 424, in load_file
with open(file_path, mode) as f:
IOError: [Errno 13] Permission denied: '/tmp/localstack/.localstack'

ERROR: [Errno 13] Permission denied: '/tmp/localstack/.localstack'
2018-02-06 05:21:47,119 INFO exited: infra (exit status 0; not expected)
2018-02-06 05:21:49,123 INFO spawned: 'infra' with pid 39
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
Error starting infrastructure: [Errno 13] Permission denied: '/tmp/localstack/.localstack' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 450, in start_infra
event_publisher.fire_event(event_publisher.EVENT_START_INFRA)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 152, in fire_event
event = AnalyticsEvent(event_type=event_type, payload=payload)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 37, in __init__
self.m_id = kwargs.get('machine_id') or kwargs.get('m_id') or get_machine_id()
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 87, in get_machine_id
local_configs = load_file(config_file)
File "/opt/code/localstack/localstack/utils/common.py", line 424, in load_file
with open(file_path, mode) as f:
IOError: [Errno 13] Permission denied: '/tmp/localstack/.localstack'

ERROR: [Errno 13] Permission denied: '/tmp/localstack/.localstack'
2018-02-06 05:21:49,574 INFO exited: infra (exit status 0; not expected)
2018-02-06 05:21:52,579 INFO spawned: 'infra' with pid 47
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
Error starting infrastructure: [Errno 13] Permission denied: '/tmp/localstack/.localstack' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 450, in start_infra
event_publisher.fire_event(event_publisher.EVENT_START_INFRA)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 152, in fire_event
event = AnalyticsEvent(event_type=event_type, payload=payload)
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 37, in __init__
self.m_id = kwargs.get('machine_id') or kwargs.get('m_id') or get_machine_id()
File "/opt/code/localstack/localstack/utils/analytics/event_publisher.py", line 87, in get_machine_id
local_configs = load_file(config_file)
File "/opt/code/localstack/localstack/utils/common.py", line 424, in load_file
with open(file_path, mode) as f:
IOError: [Errno 13] Permission denied: '/tmp/localstack/.localstack'

ERROR: [Errno 13] Permission denied: '/tmp/localstack/.localstack'
2018-02-06 05:21:53,028 INFO exited: infra (exit status 0; not expected)
2018-02-06 05:21:54,029 INFO gave up: infra entered FATAL state, too many start retries too quickly

**Comment by whummer** [comment] 2018-02-12 01:44
@jitesh-prajapati 

> Please also post the output of these commands:
```
ls -la $TMPDIR
ls -la $TMPDIR/localstack
```

**Comment by whummer** [comment] 2018-02-25 21:42
Unable to reproduce this issue; it is likely caused by incorrect permission settings in the user's local environment. Closing this issue now, please re-open or comment here if the problem persists. Thanks

**Closed by whummer** 2018-02-25 21:42 UTC
Labels: bug, configuration
