### ISSUE TITLE
Add CloudWatch Events support

### ISSUE THREAD

**Issue by heycalmdown** [localstack/localstack#103] opened 2017-05-11 13:02 UTC
It would be great that if LocalStack include [CloudWatch Events](http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/WhatIsCloudWatchEvents.html) 

It is usually used for scheduling that replaces cronjob. Because of the environment on Lambda, there are no instances running for the whole day.

**Comment by whummer** [comment] 2017-05-16 12:24
Initial support for CloudWatch metrics is added in version `0.4.3`. Please note that currently only basic metrics for Lambda functions (`Invocations`, `Errors `, `Duration`) are available. CloudWatch alerts and metric statistics are not yet implemented, but you can retrieve the raw metrics data from the service. See here for an end-to-end integration test with Lambda invocation metrics: https://github.com/atlassian/localstack/blob/master/tests/integration/test_integration.py#L198-L214

The Docker image has been pushed with the new version tag. Can you please give this a try and report back if it works for you. Thanks

**Comment by heycalmdown** [comment] 2017-05-17 04:31
Happy to hear that you support CloudWatch already. Despite the name of CloudWatch Events, it is barely related CloudWatch itself. It works more like CronJob over metrics. Are you going to support it on to CloudWatch?

**Comment by rjjatson** [comment] 2018-09-17 11:32
hi @heycalmdown,  im seeing this issue is still open, have you able to utilize the CloudWatch events on local stack?

**Comment by heycalmdown** [comment] 2018-09-18 00:43
Currently, I'm out of this issue these days. So if no other needs out there, you can close this issue.

**Comment by aaronhayes** [comment] 2018-11-15 23:01
I haven't been able to use CloudWatch Events with localstack. 

CloudWatch and CloudWatch Events are two different [moto services](https://github.com/spulec/moto#moto---mock-aws-services). To use Moto to mock the API calls, we would need to add in another `start_moto_server` service in the [`infra.py`](https://github.com/localstack/localstack/blob/master/localstack/services/infra.py#L161) file:

Stack Trace for PutEvent on localstack CloudWatch. 
```
{ UnknownError: INTERNAL SERVER ERROR
    at Request.extractError (/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'INTERNAL SERVER ERROR',
  code: 'UnknownError',
  statusCode: 500,
  time: 2018-11-15T22:50:01.245Z,
  requestId: undefined,
  retryable: true }
```

**Comment by agonencl** [comment] 2018-12-13 10:07
+1

**Comment by whummer** [comment] 2019-03-02 19:28
Should be available in the latest version. Closing this issue - please reopen or comment here if the problem persists. Thanks

**Comment by whummer** [comment] 2019-03-02 19:32
Sorry, misread the question - CloudWatch Events currently not yet available. Reopening this issue.

**Comment by fionic** [comment] 2019-10-28 13:07
I noticed that @eoinsha has made a PR to support CloudWatch events and the put_rule works but I could be doing something wrong. When I make a call to put_rule I get `{ RuleArn: 'arn:aws:events:us-west-2:111111111111:rule/dev_test' }` (which I don't know why it's going to us-west-2 and account 11111111111 since I have my region set to us-east-1) but then when I try to call `aws --region=us-west-2 --endpoint-url=http://localhost:4587 events list-rules` the response shows `{
    "Rules": []
}`. Is that the expected behavior?

**Comment by whummer** [comment] 2019-10-28 21:37
Thanks for pointing that out - initial support for CW Events was indeed added in #1429.

> Is that the expected behavior?
I believe so, yes. You should be able to see the result if the region matches. Also, please make sure that the account ID is "000000000000", see: https://github.com/localstack/localstack/blob/master/localstack/constants.py#L41 

Please create a follow-up issue if the problem persists. Thanks

**Closed** 2020-04-25 11:05 UTC
Labels: api-request, integration-missing
