### ISSUE TITLE
bug: get-parameter and get-parameters on SSM does not work with ARNs (Localstack 3.5.0)

### ISSUE THREAD

**Issue by wbeardall** [localstack/localstack#11048] opened 2024-06-18 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Queries to Localstack SSM endpoints with the `get-parameter` or `get-parameters` commands do not work if parameter names are provided as ARNs. This appears to be due to the internal LocalStack parameter validation disallowing forward slashes in SSM parameter names. We observe the following:

```
$ awslocal ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter/myparam
An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

Removing the forward slash passes the input validation, but obviously fails to fetch a parameter:

```
$ awslocal ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parametermyparam
An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter arn:aws:service:us-east-1:0000000000:parametermyparam not found.
```

### Expected Behavior

`get-parameter` and `get-parameters` should allow ARNs in names, following the [official docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/get-parameters.html#options)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter/myparam

### Environment

```markdown
- OS: Sonoma 14.5
- LocalStack:
  LocalStack version: 3.5.1.dev20240618022512
  LocalStack Docker image sha: sha256:5cd0557de2fdfac98d8d26d2f861b8266dcfc07ed09dbdacad7dc21ee2560310
  LocalStack build date: 2024-06-18
  LocalStack build git hash: 666e239
```

**Comment by mikeshultz** [comment] 2024-06-21 23:14
The root cause of this may also be preventing the use of SSM secret string params in ECS task definitions.

[According to the docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-secret.html#aws-properties-ecs-taskdefinition-secret-properties), their values must be ARNs but when trying to run a task, the same prefix error occurs.

```
exception while calling ecs.RunTask: An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

**Comment by pinzon** [comment] 2024-08-23 21:04
The solution of this issue has been merged. Thank you for reporting it.

**Closed by pinzon** 2024-08-23 21:04 UTC
Labels: type: bug, aws:ssm, status: backlog

**Comment by GuddyTech** [comment] 2025-02-27 01:03
Yes! Using the ARN works instead of using the names and this will throw an error 
`aws ssm get-parameter --name "ec2-image-builder/devops/rhel8-stig-golden-image"`

`An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_`

Instead use: 
`$ aws ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter/myparam`

NOTE: If the parameter has a forward slash already do not add it
`$ aws ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter${myparam}`

**Comment by GuddyTech** [comment] 2025-02-27 02:28
Using the ARN of the **SSM Parameter** works pretty well even in **Cross-Accounts** where the SSM Parameter was shared via AWS RAM instead of using the name as this will throw an error. 

`aws ssm get-parameter --name "myparam"`

An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_

Instead use:

   ` $ aws ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter/myparam`

Output:
```
{
        "Parameter": {
            "Name": "/myparam",
            "Type": "String",
            "Value": "ami-06ad392018375648b",
            "Version": 3,
            "LastModifiedDate": "2025-02-26T02:29:26.198000+00:00",
            "ARN": "arn:aws:service:us-east-1:0000000000:parameter/myparam",
            "DataType": "aws:ec2:image"
        }
}
```


**NOTE:** If the parameter has a forward slash already do not add it

 `$ aws ssm get-parameter --name arn:aws:service:us-east-1:0000000000:parameter${myparam}`

If you are trying to access it in the **Cross-Account through the CLI or Lambda Function**:

   ```
    import boto3
    import os
    
    ssm = boto3.client('ssm')
    
    def lambda_handler(event, context):
        parameter_name = os.environ['PARAMETER_NAME']  # Read from environment variable
        
        try:
            response = ssm.get_parameter(
                Name=parameter_name,
                WithDecryption=True  # If it's a SecureString parameter
            )
            return {
                'statusCode': 200,
                'parameter_value': response['Parameter']['Value']
            }
        except Exception as e:
            return {
                'statusCode': 400,
                'error': str(e)
            }
```

Also make sure to have these in the SOURCE ACCOUNT(in RAM)

```
ssm:GetParameter
ssm:GetParameters
ssm:DescribeParameters
```

and the DESTINATION ACCOUNT(in the Lambda Role) create this inline policy

```
{
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "ssm:GetParameter",
                    "ssm:GetParameters",
                    "ssm:DescribeParameters"
                ],
                "Resource": "arn:aws:ssm:REGION:ACCOUNT_A_ID:parameter/myparam"
            }
        ]
}
```
Or Attach the **AmazonSSMFullAccess** to test, then restrict it later for security(So that the Role wont be too open to what is not needed by the system)

**Comment by pinzon** [comment] 2025-02-27 21:25
Hi @GuddyTech. I'm not able to reproduce the issue you're mentioning on the latest version. These commands run fine:
```bash
awslocal ssm put-parameter --name "/test2" --type String --value test
awslocal ssm get-parameter --name "/test2"
```
