### ISSUE TITLE
spark kinesis dynamodb state table

### ISSUE THREAD

**Issue by jney** [localstack/localstack#797] opened 2018-06-05 13:24 UTC
Hello, I'm using spark (pyspark) with kinesis but starting my container i've got the following message.

```log
that_app_1        | [DynamoDB][Connection on master side] Connect to DynamoDB... {'endpoint_url': 'http://localstack:4569', 'region_name': 'eu-west-1'}
that_app_1        | 2018-06-05 13:15:34 ERROR LeaseManager:114 - Failed to get table status for kinesis-staging-test
that_app_1        | com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The security token included in the request is invalid. (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: AB928UTFMV72B94D95GAJKGBJ7VV4KQNSO5AEMVJF66Q9ASUAAJG)
```

When configuring spark I give kinesis' `endpointUrl` but as far as i know, i can't give the related `endpointUrl` for its state in dynamodb.

Anyone experience on making `localstack` work with `dynamodb`, here?

Thank you

probably related to #677

**Comment by whummer** [comment] 2018-09-03 14:35
Thanks for reporting @jney . Seems like a duplicate of #677 - can we continue the discussion on that issue. Thanks

**Closed by whummer** 2018-09-03 14:35 UTC
