### ISSUE TITLE
Starting localstack fails - missing termios - Windows 10

### ISSUE THREAD

**Issue by billzichos** [localstack/localstack#1285] opened 2019-05-04 14:17 UTC
termios appears to be a Python module.  Installing on my Windows machine using pip fails.  Further research reveals this is only available on UNIX systems.  What is the Windows workaround?  I prefer to not go the Docker route - hyperthreading issues if I remember correctly. 

My current environment:

Windows 10 (64-bit)
make 3.79.1
python 3.6.1
pip 19.1
npm 5.6.0
java 1.8.0_211
javac 1.8.0_45
mvn 3.6.1

> python localstack start

Traceback (most recent call last):
  File "localstack", line 30, in <module>
    from localstack.utils import cli
  File "C:\Program Files\Python36\lib\site-packages\localstack\utils\cli.py", line 4, in <module>
    from localstack.services import infra
  File "C:\Program Files\Python36\lib\site-packages\localstack\services\infra.py", line 20, in <module>
    from localstack.utils import common, persistence
  File "C:\Program Files\Python36\lib\site-packages\localstack\utils\common.py", line 7, in <module>
    import pty
  File "C:\Program Files\Python36\lib\pty.py", line 11, in <module>
    import tty
  File "C:\Program Files\Python36\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'

**Comment by dr3x** [comment] 2019-06-18 20:16
Following - same issue; there is no termios on Windows:
https://docs.python.org/3/library/tty.html
The tty module defines functions for putting the tty into cbreak and raw modes.
Because it requires the termios module, it will work only on Unix.

Windows functionality may have been broken by this commit:
https://github.com/localstack/localstack/commit/6981a3d4181d1e7ce102486850979202b8258afc#diff-747ce9426d96c5759dfdf1ec62deea42

**Comment by arnagarjun** [comment] 2019-06-23 11:42
Facing the same issue

**Comment by jmb12686** [comment] 2019-06-24 18:51
same issue here as the original issue posted.

**Comment by vharigandhi** [comment] 2019-06-28 10:43
Same here

**Comment by whummer** [comment] 2019-08-03 19:06
@jmb12686 @vharigandhi @arnagarjun @dr3x @billzichos  Closing as duplicate of #563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

only install the bare minimum dependencies by default
start LocalStack in Docker by default, and
lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:06 UTC
