### ISSUE TITLE
MessageRetentionPeriod of SQS queue has no effect

### ISSUE THREAD

**Issue by ldrag** [localstack/localstack#3525] opened 2021-01-28 12:53 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

While creating an sqs queue I am passing _MessageRetentionPeriod_ attribute. Its value is set correctly and can be read with _get-queue-attributes_ command. Unfortunately it seems that this setting is ignored and messages stay longer in the queue.

## Expected behavior

Messages should be removed from the queue after time defined in _MessageRetentionPeriod_ has elapsed

## Actual behavior

Messages are still available for reading after time defined in _MessageRetentionPeriod_ has elapsed

# Steps to reproduce

## Command used to start LocalStack

```
aws sqs create-queue --queue-name test-queue --attributes MessageRetentionPeriod=60 --endpoint-url http://localhost:4566
aws sqs get-queue-attributes --endpoint-url http://localhost:4566 --queue-url http://localhost:4566/000000000000/test-queue
{
    "Attributes": {
        "ApproximateNumberOfMessagesNotVisible": "0",
        "VisibilityTimeout": "30",
        "ApproximateNumberOfMessagesDelayed": "0",
        "MaximumMessageSize": "262144",
        "CreatedTimestamp": "1611836084.188114",
        "ApproximateNumberOfMessages": "1",
        "ReceiveMessageWaitTimeSeconds": "0",
        "DelaySeconds": "0",
        "MessageRetentionPeriod": "60", <--- ATTRIBUTE IS SET TO THE CORRECT VALUE
        "LastModifiedTimestamp": "1611836084.188114",
        "QueueArn": "arn:aws:sqs:eu-west-1:000000000000:test-queue"
    }
}
aws sqs send-message --queue-url hhttp://localhost:4566/000000000000/test-queue --message-body "Hello world" --endpoint-url http://localhost:4566
```
Wait >60 sec.....

```
aws sqs receive-message --queue-url http://localhost:4566/000000000000/test-queue --endpoint-url http://localhost:4566
{
    "Messages": [
        {
            "Body": "Hello world",
            "Attributes": {
                "ApproximateFirstReceiveTimestamp": "1611836101843",
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "ApproximateReceiveCount": "2",
                "SentTimestamp": "1611836093589"
            },
            "ReceiptHandle": "naqtfpszzhrrampzkcqjvgqjwnnhiqkfbqjdepmzxauvhitapcwbgnyynbgwezgauabtqjrjuhhrcrgxetyaxdxujucaalzmwhqnofttkxkmrkuxalpljzcfptbqmnstpzjltzaepsunedbgbstccrobazzpmviaorfujkqixhxguzesmtvbkurjv",
            "MD5OfBody": "3e25960a79dbc69b674cd4ec67a72c62",
            "MessageId": "05188845-7b60-c721-2752-5c839a975b42"
        }
    ]
}
```

**Comment by whummer** [comment] 2021-02-22 08:19
Thanks for reporting @ldrag . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by ayeganyan-atl** [comment] 2023-07-24 09:50
Hi,
I am doing the same steps again in 1.4.0 and 2.2.0, and the issue is still there.
Might be regression here I guess...

**Comment by thrau** [comment] 2023-07-24 20:54
I can confirm that we don't have this implemented in our current SQS provider at the moment.

**Comment by thrau** [comment] 2023-12-28 15:05
i looked into this a little today and implementing message retention could prove trickier than it first appears. the biggest issue i ran into is persistence. suppose (conceptually) a message has an "is_expired" flag that is true if `time.time() > message.created_time + queue.message_retention_period`. when restoring localstack from a persisted state much later, all messages would automatically be considered expired and subsequently removed from the queue.

to fix this, we need some sort of mechanism to map the stored timestamps from the previous run to the current time of the restored run. we don't really have a pattern for this, nor has it come up in other services that i know of. sqs messages hold several time fields (created, last received, first received, visibility deadline, etc.). it seems we need to tackle this first before we can add message retention, otherwise pods and persistence users will have all of their messages removed. maybe a nice puzzle to solve for @giograno

in the meantime what we can do is hide it behind a feature flag and document the limitation when using it together with persistence.

**Comment by thrau** [comment] 2024-01-02 18:23
Hey everyone! We added this feature in #9956, docs https://github.com/localstack/docs/pull/997! You can enable it by starting localstack with `SQS_ENABLE_MESSAGE_RETENTION_PERIOD=1`. Note that, currently, updating the message retention period of a queue has no effect on existing messages.

**Comment by thrau** [comment] 2024-01-02 18:24
Hey everyone! We added this feature in #9956, docs https://github.com/localstack/docs/pull/997! You can enable it by starting localstack with `SQS_ENABLE_MESSAGE_RETENTION_PERIOD=1`. Note that, currently, updating the message retention period of a queue has no effect on existing messages.

**Closed by thrau** 2024-01-02 18:24 UTC
Labels: aws:sqs, status: backlog
