### ISSUE TITLE
Get Object after Put Object contains extra chunk-signature data

### ISSUE THREAD

**Issue by ulsa** [localstack/localstack#98] opened 2017-05-08 19:38 UTC
As a sanity check on startup, my system puts an object (containing the string `"test object"`) to S3, reads it back, and compares with the original data. This works fine with Amazon S3. However, when using Localstack S3, I get an exception from the AWS SDK:

    com.amazonaws.SdkClientException: Unable to verify integrity of data upload.
      Client calculated content hash (contentMD5: AVTp85hfPVsW2nDtDs/RLQ== in base 64)
      didn't match hash (etag: 6c390604627b1bcd5e7be501de28728f in hex) calculated by
      Amazon S3.  You may need to delete the data stored in Amazon S3.
      (metadata.contentMD5: null,
       md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@6bf19ed6,
       bucketName: mybucket,
       key: testing)

When I copy the object back, it contains two chunk-signature things:

    $ aws --endpoint-url http://localhost:4572/ s3 cp s3://mybucket/testing /tmp/t
    download: s3://mybucket/testing to ../../../../tmp/t
    
    $ cat /tmp/t
    b;chunk-signature=38f129967953ef81f03788f5d850eec889c21538db17259f0d1332755c304fb5
    test object
    0;chunk-signature=1a73198f3e9db9b74a292964bcb6fff9231c0c882624563d36526f75a3911d5c

**Comment by whummer** [comment] 2017-05-10 09:27
Thanks for the report. Can you please provide a minimal test case (including the Java SDK calls) to reproduce this issue?

Is this a possible duplicate of https://github.com/atlassian/localstack/issues/68?

**Comment by ulsa** [comment] 2017-05-10 12:01
Here is a [sample project](https://github.com/ulsa/localstack-s3) written in Clojure using the [Amazonica](https://github.com/mcohen01/amazonica) library, which uses the AWS Java SDK straight up. Maybe that's useful.

Don't know if this is related to #68.

**Comment by whummer** [comment] 2017-05-14 10:10
Thanks for providing a sample project. This should be fixed in ce2d37e227c1791f3c8d5dd7ccd26becba379f82 . Can you please try with the latest Docker image. Please re-open if the problem persists. Thanks

**Comment by ulsa** [comment] 2017-05-15 08:52
Works with image `atlassianlabs/localstack:265259a1a73a`.

**Comment by JeromeSimmonds** [comment] 2017-09-27 22:16
I am getting the same error with Docker image localstack/localstack:latest
My Java app uses aws-java-sdk 1.11.104 (I also tried 1.11.80).
Here is how I upload:
```
...
String dataString = "{}"; // Some JSON content
byte[] dataBytes = dataString.getBytes(StandardCharsets.UTF_8);

ObjectMetadata metaData = new ObjectMetadata();
metaData.setContentType(ContentType.APPLICATION_JSON.toString());
metaData.setContentEncoding(StandardCharsets.UTF_8.name());
metaData.setContentLength(dataBytes.length);

byte[] resultByte = DigestUtils.md5(dataBytes);
String streamMD5 = new String(Base64.encodeBase64(resultByte));
metaData.setContentMD5(streamMD5);

PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, keyName, new ByteArrayInputStream(dataBytes), metaData);
s3Client.putObject(putObjectRequest);

**Comment by xaviarias** [comment] 2017-09-29 14:51
Hi, 

I am having the same issue here with `aws-java-sdk 1.11.204`. The code:

    getClientS3().putObject(S3_BUCKET, key, new File("file.zip");

throws this exception:

```
com.amazonaws.SdkClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: lzQ7bxvNin+82bZ3oFUMhQ== in base 64) didn't match hash (etag: 11cabd475b9564456ed2e49300bbd3db in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: lzQ7bxvNin+82bZ3oFUMhQ==, md5DigestStream: null, bucketName: test-bucket, key: 54d2b376-c2a7-4029-960e-ab3873e246ce)
```

I am running Localstack on JUnit with `LocalstackTestRunner.class`, and I have other tests working so the environment is correctly spun up.

```
<dependency>
    <groupId>cloud.localstack</groupId>
    <artifactId>localstack-utils</artifactId>
    <version>0.1.4</version>
    <scope>test</scope>
</dependency>
```

**Comment by whummer** [comment] 2017-10-24 11:39
@JeromeSimmonds @xaviarias Can you please try again with the latest version. There has been a recent change which might have fixed that issue (https://github.com/localstack/localstack/pull/416). If not, please provide a link to the zip file you're trying to upload (content should not matter, but the size of the zip file may be relevant.) Thanks

**Comment by JeromeSimmonds** [comment] 2017-10-24 15:15
Ok I am going to try.
By the way as you can see in my code snippet I am not uploading a file but a byte array generated from a String (representing JSON data).

**Comment by JeromeSimmonds** [comment] 2017-10-25 18:08
Seems like it's working now :thumbsup:

Thanks!

**Closed** 2017-10-25 21:28 UTC
Labels: bug, priority-high

**Comment by te21wals** [comment] 2018-11-05 17:17
I was able to get this to work with my java s3 clients by passing the flag `-Dcom.amazonaws.services.s3.disableGetObjectMD5Validation`

**Comment by herrlegno** [comment] 2021-09-29 09:11
I'm getting a extra chunk-signature data in a file after restarting localstack. Everything work until I restart the stack, after that there is a json file that contains some extra signature data that breaks my application as I tried to parse it and it doesn't work.

```json
1e5;chunk-signature=83a45ce7e9db52171538036b946102068a9f2005c53049b23c63515f1c048fbc
{ "test": "this is a test json" }
0;chunk-signature=bd812928970799e2d5d16a86900629155d7d38aba42ed2dcbc7d6559c364671f
```

This is how I upload the file to S3:

```java
JSONObject currentContent;
currentContent = new JSONObject(IOUtils.toString(s3Client.getObject(bucketName, s3FilePath).objectContent));
s3Client.putObject(bucketName, s3FilePath, currentContent.toString());
```

I'm using the s3 java client v1.11.73. Is there any solution to this?

Thanks.

**Comment by herrlegno** [comment] 2021-09-30 11:58
I have created a test [repository](https://github.com/herrlegno/localstack-s3-signature-error) for reproducing this issue.

Requirements:
- Having a s3 bucket named: test

Steps to reproduce:
- Run test in order.
- After the test has successfully passed, restart the localstack container (i have a docker-compose file).
- Run only the "extendsS3Object" test or download the file from s3 through awscli. 

The file will look like something like this:
```json
19;chunk-signature=f64cba77c6523187a1448fd7bd9cd739ce9d953c951af6fe34ac787b8b8f60d6
{"bar":"baz","foo":"bar"}
0;chunk-signature=fcc672670aab469d7e23cd6eeea9cb5639feca2f065510bcfb77f057bb391c9b
```

**Comment by github-gregory-bougeard** [comment] 2022-05-17 09:23
Might be related to chunkEncoding enabled. cf https://stackoverflow.com/questions/55816844/aws-s3-get-after-put-includes-chunk-signature-data
