### ISSUE TITLE
Error creating infrastructure with terraform

### ISSUE THREAD

**Issue by jeznag** [localstack/localstack#1208] opened 2019-03-20 00:32 UTC
Hi,
When trying to deploy a terraform template to localstack, I get these errors:
```
* aws_iam_policy.lambda: Error creating IAM policy terraform-20190320002505900500000001: SerializationError: failed decoding Query response
	status code: 200, request id:
caused by: parsing time "2019-03-20T00:25:06.008558+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z"
* module.meter_data_export.aws_iam_policy.mde_chamber: 1 error(s) occurred:

* aws_iam_policy.mde_chamber: Error creating IAM policy MegadevmoMDEDevelopmentChamberAccess: SerializationError: failed decoding Query response
	status code: 200, request id:
caused by: parsing time "2019-03-20T00:25:07.111054+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z"
* module.meter_data_export.module.archive_storage.aws_sns_topic.main: 1 error(s) occurred:

* aws_sns_topic.main: Error creating SNS topic: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: cf5ece45-cafa-56aa-85b7-9b4e405221b1
* module.meter_data_export.aws_iam_policy.ses_send: 1 error(s) occurred:

* aws_iam_policy.ses_send: Error creating IAM policy MegadevmoMDEDevelopmentSendEmailNotificationsForMeterDataExporter: SerializationError: failed decoding Query response
	status code: 200, request id:
caused by: parsing time "2019-03-20T00:25:06.815180+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z"
* module.meter_data_export.module.list_lambda.aws_iam_role.lambda: 1 error(s) occurred:

* aws_iam_role.lambda: Error creating IAM Role MegadevmoMDEDevelopment-megatest-ListArchive: SerializationError: failed decoding Query response
	status code: 200, request id:
caused by: parsing time "2019-03-20 00:25:06.718828+00:00" as "2006-01-02T15:04:05Z": cannot parse " 00:25:06.718828+00:00" as "T"
* module.meter_data_export.aws_cloudwatch_event_rule.process: 1 error(s) occurred:

* aws_cloudwatch_event_rule.process: Creating CloudWatch Event Rule failed: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: 9f767d89-4aa6-11e9-9023-b1d43b6a9288
* module.meter_data_export.module.list_lambda.aws_iam_policy.dead_letter: 1 error(s) occurred:

* aws_iam_policy.dead_letter: Error creating IAM policy terraform-20190320002533842200000008: SerializationError: failed decoding Query response
	status code: 200, request id:
caused by: parsing time "2019-03-20T00:25:33.947961+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z"
```

**Comment by whummer** [comment] 2019-03-20 10:11
Thanks for reporting @jeznag . Any chance you can share a minimal working example with your terraform template?

**Comment by pall-valmundsson** [comment] 2019-04-24 23:55
I ran into this as well, seems to be an issue in moto. I just submitted a PR: https://github.com/spulec/moto/pull/2169

**Comment by christhomas** [comment] 2019-04-26 15:26
I've run into this issue today using IAM services

**Comment by christhomas** [comment] 2019-04-29 15:31
I added your git repository as a replacement in the requirements.txt and compiled an image with it. The issue is gone. Does anybody have any idea when this might get integrated into the mainline?

**Comment by danielptm** [comment] 2020-01-17 00:12
Im having this problem too with the CloudWatch Event Rule .... Are there any updates to this issue or suggested work arounds?

**Comment by duongpv7** [comment] 2020-03-10 18:04
I have a test with a terraform template as below, this issue already fixed in latest version
`provider "aws" {
  access_key    = ""
  secret_key    = ""
  region        = "ap-southeast-1"
  skip_credentials_validation   = true
  skip_metadata_api_check       = true
  skip_requesting_account_id    = true
  
  endpoints {
    iam                 = "http://localhost:4593"
    cloudwatchevents    = "http://localhost:4587"
  }
}

resource "aws_cloudwatch_event_rule" "NotificationEventRule" {
  event_pattern = <<PATTERN
{
    "source":[
        "aws.config"
    ],
    "detail-type":[
        "Config Configuration Item Change"
    ]
}
  PATTERN
}

data "aws_iam_policy_document" "DeliveryPolicyDocument" {
  statement {
    actions = [
        "firehose:PutRecord",
        "firehose:PutRecordBatch"
    ]

    resources = [
      "*"
    ]
  }
}

resource "aws_iam_policy" "DeliveryPolicy" {
  name      = "DeliveryPolicy"
  policy    = "${data.aws_iam_policy_document.DeliveryPolicyDocument.json}"
}`

**Comment by whummer** [comment] 2020-03-11 10:18
Great, thanks again for providing debug information and fixes @jeznag @pall-valmundsson @christhomas @danielptm @duongpv7 . Closing this one as fixed in the `latest` version - please reopen if the problem persists. Thanks!

**Closed by whummer** 2020-03-11 10:18 UTC
Labels: bug, diverges-from-aws

**Comment by Veetaha** [comment] 2021-09-01 12:48
@whummer We are seeing the same error for `awd_lambda_function_event_invoke_config`:
```
╷
│ Error: error putting Lambda Function Event Invoke Config (localstack-delete-provisioner): SerializationError: failed decoding JSON RPC response
│ 	status code: 200, request id: 
│ caused by: parsing time "2021-09-01T10:34:04.326198+00:00" as "2006-01-02T15:04:05.999999999Z": cannot parse "+00:00" as "Z"
│ 
│   with module.elastio_red_stack.module.provisioner.module.delete_provisioner.aws_lambda_function_event_invoke_config.this,
│   on ../../../modules/aws_lambda_rust/main.tf line 81, in resource "aws_lambda_function_event_invoke_config" "this":
│   81: resource "aws_lambda_function_event_invoke_config" "this" {
│ 
╵
```
We are using `localstack/localstack:0.12.13` docker image
