### ISSUE TITLE
SES 500 Internal Server Error

### ISSUE THREAD

**Issue by jbpratt78** [localstack/localstack#1765] opened 2019-11-14 20:38 UTC
I just cloned the project and started the containers, but whenever I go to make a call to the SES service, I receive a 500 response. Would appreciate it if anyone could help out.
```
localstack >docker-compose up
Starting localstack_main ... done
Attaching to localstack_main
localstack_main | Starting mock Kinesis (http port 4568)...
localstack_main | Starting mock Redshift (http port 4577)...
localstack_main | Starting mock Route53 (http port 4580)...
localstack_main | Starting mock CloudFormation (http port 4581)...
localstack_main | Starting mock CloudWatch (http port 4582)...
localstack_main | Starting mock CloudWatch Events (http port 4587)...
localstack_main | Starting mock CloudWatch Logs (http port 4586)...
localstack_main | Starting mock StepFunctions (http port 4585)...
localstack_main | Starting mock EC2 (http port 4597)...
localstack_main | Ready.
localstack_main | 2019-11-14T20:14:18:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_main | 2019-11-14 20:31:28,658 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_main | 2019-11-14 20:31:28,661 INFO supervisord started with pid 11
localstack_main | 2019-11-14 20:31:29,665 INFO spawned: 'dashboard' with pid 18
localstack_main | 2019-11-14 20:31:29,671 INFO spawned: 'infra' with pid 19
localstack_main | 2019-11-14 20:31:29,677 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_main | (. .venv/bin/activate; bin/localstack web)
localstack_main | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_main | 2019-11-14 20:31:30,679 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_main | cannot import name 'dns_server'
localstack_main |    WARNING: Do not use the development server in a production environment.
localstack_main |    Use a production WSGI server instead.
localstack_main | Starting local dev environment. CTRL-C to quit.
localstack_main | cannot import name 'dns_server'
localstack_main | Starting mock ES service (http port 4578)...
localstack_main | Starting local Elasticsearch (http port 4571)...
localstack_main | Starting mock S3 (http port 4572)...
localstack_main | Starting mock SNS (http port 4575)...
localstack_main | Starting mock SQS (http port 4576)...
localstack_main | Starting mock SES (http port 4579)...
localstack_main | Starting mock SSM (http port 4583)...
localstack_main | Starting mock STS (http port 4592)...
localstack_main | Starting mock IAM (http port 4593)...
localstack_main | Starting mock Secrets Manager (http port 4584)...
localstack_main | Starting mock API Gateway (http port 4567)...
localstack_main | Starting mock DynamoDB (http port 4569)...
localstack_main | Starting mock DynamoDB Streams service (http port 4570)...
localstack_main | Starting mock Firehose service (http port 4573)...
localstack_main | Starting mock Lambda service (http port 4574)...
localstack_main | Starting mock Kinesis (http port 4568)...
localstack_main | Starting mock Redshift (http port 4577)...
localstack_main | Starting mock Route53 (http port 4580)...
localstack_main | Starting mock CloudFormation (http port 4581)...
localstack_main | Starting mock CloudWatch (http port 4582)...
localstack_main | Starting mock CloudWatch Events (http port 4587)...
localstack_main | Starting mock CloudWatch Logs (http port 4586)...
localstack_main | Starting mock StepFunctions (http port 4585)...
localstack_main | Starting mock EC2 (http port 4597)...
localstack_main | 2019-11-14T20:31:33:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_main | Ready.

```

```
~ >aws --endpoint-url=http://localhost:4579 ses create-configuration-set --configuration-set Name=test --region us-east-2

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

~ >awslocal ses create-configuration-set --configuration-set Name=test

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by Bonemind** [comment] 2019-11-18 14:54
I'm having the same issue with EventGrid, wasn't sure whether to open a new issue:

`awslocal events list-event-buses`

```
An error occurred (500) when calling the ListEventBuses operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
startup output:
```
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 2019-11-18 14:49:50,377 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you
can set user=root in the config file to avoid this message.
localstack_main | 2019-11-18 14:49:50,381 INFO supervisord started with pid 12
localstack_main | 2019-11-18 14:49:51,384 INFO spawned: 'dashboard' with pid 20
localstack_main | 2019-11-18 14:49:51,387 INFO spawned: 'infra' with pid 21
localstack_main | 2019-11-18 14:49:51,402 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_main | (. .venv/bin/activate; bin/localstack web)
localstack_main | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_main | 2019-11-18 14:49:52,403 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_main | cannot import name 'dns_server'
localstack_main |    WARNING: Do not use the development server in a production environment.
localstack_main |    Use a production WSGI server instead.
localstack_main | Starting local dev environment. CTRL-C to quit.
localstack_main | cannot import name 'dns_server'
localstack_main | Starting mock ES service (http port 4578)...
localstack_main | Starting local Elasticsearch (http port 4571)...
localstack_main | Starting mock S3 (http port 4572)...
localstack_main | Starting mock SNS (http port 4575)...
localstack_main | 2019-11-18T14:49:55:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Starting mock SQS (http port 4576)...
localstack_main | Starting mock SES (http port 4579)...
localstack_main | Starting mock SSM (http port 4583)...
localstack_main | Starting mock STS (http port 4592)...
localstack_main | Starting mock IAM (http port 4593)...
localstack_main | Starting mock Secrets Manager (http port 4584)...
localstack_main | Starting mock API Gateway (http port 4567)...
localstack_main | Starting mock DynamoDB (http port 4569)...
localstack_main | Starting mock DynamoDB Streams service (http port 4570)...
localstack_main | Starting mock Firehose service (http port 4573)...
localstack_main | Starting mock Lambda service (http port 4574)...
localstack_main | Starting mock Kinesis (http port 4568)...
localstack_main | Starting mock Redshift (http port 4577)...
localstack_main | Starting mock Route53 (http port 4580)...
localstack_main | Starting mock CloudFormation (http port 4581)...
localstack_main | Starting mock CloudWatch (http port 4582)...
localstack_main | Starting mock CloudWatch Events (http port 4587)...
localstack_main | Starting mock CloudWatch Logs (http port 4586)...
localstack_main | Starting mock StepFunctions (http port 4585)...
localstack_main | Starting mock EC2 (http port 4597)...
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Ready.
```

**Comment by teroxik** [comment] 2019-11-18 21:21
@whummer I can confirm that the `events` service doesn't start at all on the latest image.
@Bonemind seems to be working with the latest `released` image 0.10.5, not the docker tag `latest`

**Comment by Bonemind** [comment] 2019-11-19 14:50
Ah, sorry I didn't specify, same output on both latest and 0.10.5

**Comment by whummer** [comment] 2020-03-02 00:44
Thanks for reporting @jbpratt78 - I've been able to reproduce this issue, and can confirm that certain SES APIs (e.g., `create_configuration_set`) are still missing. This is an upstream issue in `moto` - if you could create a pull request, that would be much appreciated. Thanks

@teroxik @Bonemind the issue you're describing seems to be different, and seems to be fixed in the meantime. Can you please give it a try with the `latest` version?

**Comment by teroxik** [comment] 2020-03-25 20:02
@whummer the issue seems to be resolved since localstack/localstack:0.10.6. Should have upated this!

**Comment by whummer** [comment] 2020-05-23 21:41
Thanks for confirming that this works in the latest version @teroxik 👍 . Please report here if the problem persists. Thanks

**Closed by whummer** 2020-05-23 21:41 UTC
Labels: feature-missing, upstream-issue

**Comment by arseniybanayev** [comment] 2020-06-05 01:51
I am getting 500s running docker image `localstack/localstack:0.11.2` with `SERVICES=ses` when I try to create a rule set

`awslocal ses create-receipt-rule-set --rule-set-name default-rule-set`

in a `.sh` script in `/docker-entrypoint-initaws.d`.

**Comment by harryurban** [comment] 2020-11-02 09:37
> I am getting 500s running docker image `localstack/localstack:0.11.2` with `SERVICES=ses` when I try to create a rule set
> 
> ```shell
> awslocal ses create-receipt-rule-set --rule-set-name default-rule-set
> ```
> 
> in a `.sh` script in `/docker-entrypoint-initaws.d`.
> 
> ```
> Unable to parse response (syntax error: line 1, column 54), invalid XML received:
> b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
> ```

Could you resolve your issue because I am facing a similar one.
