### ISSUE TITLE
Firehose default prefix in s3 not working

### ISSUE THREAD

**Issue by priteshwatch** [localstack/localstack#1812] opened 2019-11-27 20:17 UTC
May be I am doing something wrong, here is the basic setup

awslocal s3 mb s3://s3-firehose --region us-east-1
awslocal s3api put-bucket-acl --bucket s3-firehose --acl public-read
awslocal iam create-role --role-name super-role --assume-role-policy-document file://iam_policy.json
awslocal firehose create-delivery-stream --cli-input-json file://firehose_skeleton.json

Contents of iam_policy.json

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1572416334166",
      "Action": "*",
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}

```
Contents of firehose_skeleton.json

```
{
  "DeliveryStreamName": "s3-stream",
  "DeliveryStreamType": "DirectPut",
  "S3DestinationConfiguration": {
    "RoleARN": "arn:aws:iam::000000000000:role/super-role",
    "BucketARN": "arn:aws:s3:::s3-firehose",
    "ErrorOutputPrefix": "test-error-log",
    "BufferingHints": {
      "SizeInMBs": 1,
      "IntervalInSeconds": 60
    },
    "CompressionFormat": "UNCOMPRESSED",
    "CloudWatchLoggingOptions": {
      "Enabled": false,
      "LogGroupName": "",
      "LogStreamName": ""
    }
  },
  "Tags": [
    {
      "Key": "tagKey",
      "Value": "tagValue"
    }
  ]
}

```

When I ingest a record in firehose, the default YYYY/MM/dd/HH format is not created as a directory structure. 

Am I missing something?

**Comment by whummer** [comment] 2020-01-19 10:51
Thanks for reporting @priteshwatch . This seems to be a duplicate of #1554 - it should have been fixed in #1920 . Can you please give it a try with the latest version of the Docker image, and report here if the problem persists. Thanks

**Closed by whummer** 2020-01-19 10:51 UTC
