### ISSUE TITLE
aws java cloudformation sdk ListStackResourcesRequest causes 500 on the server

### ISSUE THREAD

**Issue by berardino** [localstack/localstack#1793] opened 2019-11-23 00:18 UTC
This is the localstack configuration for docker-compose:

```
localstack:
    image: localstack/localstack:0.10.5
    ports:
      - 4572:4572   #S3
      - 4576:4576   #SQS
      - 4581:4581   #CloudFormation
    environment:
      - START_WEB=0
      - SERVICES=s3,sqs,cloudformation
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-west-1
```
I am able to provision a stack :
> aws --endpoint-url=http://localhost:4581 cloudformation create-stack --stack-name mystack --template-body {"Resources":{}} --region us-west-1

and to query it:
> aws --endpoint-url=http://localhost:4581 cloudformation list-stack-resources --stack-name mystack --region us-west-1

```json
{
    "StackResourceSummaries": []
}
```

But when executing the same query via aws java jdk (version 1.11.679):

```kotlin
val client = AmazonCloudFormationClientBuilder.standard()
        .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration("http://localhost:4581", "eu-west-1"))
        .build()

client.listStackResources(ListStackResourcesRequest().withStackName("mystack"))
```

This generates a `500` response:

```
Exception in thread "main" com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: null (Service: AmazonCloudFormation; Status Code: 500; Error Code: 500 Internal Server Error; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:3885)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:3852)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:3841)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeListStackResources(AmazonCloudFormationClient.java:2701)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.listStackResources(AmazonCloudFormationClient.java:2672)
```

This is the http request generated from aws sdk:
```
POST / HTTP/1.1
Host: localhost:4581
amz-sdk-invocation-id: e59665e3-f1a6-de06-925e-16cd74fb2a5f
amz-sdk-retry: 3/11/485
Authorization: AWS4-HMAC-SHA256 Credential=local/20191123/eu-west-1/cloudformation/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;host;user-agent;x-amz-date, Signature=80a7180d1c13ecd74cd6f4fc93be61eeb052691983a9e2559c564a053492806b
User-Agent: aws-sdk-java/1.11.679 Linux/5.3.0-23-generic OpenJDK_64-Bit_Server_VM/12.0.2+10 java/12.0.2 kotlin/1.3.50 vendor/Oracle_Corporation
X-Amz-Date: 20191123T002046Z
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Content-Length: 63
Connection: Keep-Alive

Action=ListStackResources&Version=2010-05-15&StackName=documesh
```

And this is the one generated from the aws cli :
```
POST / HTTP/1.1
Host: localhost:4581
Accept-Encoding: identity
User-Agent: aws-cli/1.16.266 Python/3.5.2 Linux/5.3.0-23-generic botocore/1.13.2
X-Amz-Date: 20191123T002207Z
Authorization: AWS4-HMAC-SHA256 Credential=local/20191123/us-west-1/cloudformation/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=05c5650e91766a7490c2d41b637264b37dbd89e73a119cb44d80e3399361afbf
Content-Length: 63
Content-Type: application/x-www-form-urlencoded; charset=utf-8

Version=2010-05-15&Action=ListStackResources&StackName=documesh
```

I was able to narrow down the issue in the `Authorization` header: it looks like the aws-cli and the java sdk generate the header differently. And somehow this can crash the localstack cloudformation mock.

**Comment by whummer** [comment] 2020-01-18 15:53
Thanks for the detailed report @berardino . This seems to be caused by a region mismatch - please note that LocalStack is currently single-region and requires to configure the same region on the server side as well as on the client side.

You appear to be starting LocalStack with `DEFAULT_REGION` set to `us-west-1`, which explains why the CLI command with region `--region us-west-1` passes successfully. For Java, however, you seem to be using region `eu-west-1`, which is incompatible in this case.

Closing this issue - please report here if the problem persists after adjusting the region in the Java code. Thanks

**Closed by whummer** 2020-01-18 15:53 UTC
