### ISSUE TITLE
S3 Data persistence to volume

### ISSUE THREAD

**Issue by i-aggarwal** [localstack/localstack#1175] opened 2019-03-07 12:30 UTC
Hi Guys,

You have created an amazing tool, that we have started to use recently. It solves a lot of our problems, but one thing we are looking at is persistence of data (CSV, Parquet, etc.) on mounted volumes. I believe as of now the way persistence happens is through file - "s3_api_calls.json", which works sometimes, but as its size grows, we end up getting errors.

Are there any plans to persist data to volumes?

Thanks,
Ishan Aggarwal

**Comment by whummer** [comment] 2019-03-07 23:26
Hi @i-aggarwal , please refer to the `DATA_DIR` configuration, documented here: https://github.com/localstack/localstack#configurations

You can use this command to run LocalStack in Docker and persist data to your local `/tmp/localstack_data` folder, for example:
```
DATA_DIR=/tmp/localstack_data localstack infra start --docker
```

**Comment by i-aggarwal** [comment] 2019-03-08 14:16
Hi @whummer thanks for the reply. When I set the DATA_DIR to "/tmp/localstack/data" (/data not _data I believe) as per  DATA_DIR conf, all that gets saved to the location is s3_api_calls.json.

I am using docker image tagged 0.8.6. Could it be that the feature came in a later version?

**Comment by whummer** [comment] 2019-03-08 17:03
> I am using docker image tagged 0.8.6. Could it be that the feature came in a later version?

Hm, yes that could be an issue. Could you give it a try with the image tagged `0.9.0` or even `latest`? I'd like to understand the root cause for the time out error.

What happens if you run this:
```
docker pull localstack/localstack:latest
localstack infra start --docker
```

Wait until "`Ready.`" appears in the logs, and then in a separate terminal:
```
pip install awscli-local
awslocal s3 ls
```

**Comment by good-idea** [comment] 2019-03-09 00:13
I'm using docker-compose the data is persisting between container restarts. But, I don't see the files saving on my local HD.

**docker-compose.yml**

```
  localstack:
    image: localstack/localstack:latest
    container_name: mappslab-dev_localstack
    ports:
      - '4563-4584:4563-4584'
      - '8050:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

I'm on OS X, so i'm running docker-compose as:
`TMPDIR=/private$TMPDIR docker-compose up -d`

Like @i-aggarwal, all I have in `/tmp/localstack` is the `.localstack` config file and `s3_api_calls.json`. There's no `/data` directory.

The data is still there after a restart - accessible through the container - so that's all OK.. but I'd still like to be able to see the actual files.

**Comment by i-aggarwal** [comment] 2019-03-11 10:01
> > I am using docker image tagged 0.8.6. Could it be that the feature came in a later version?
> 
> Hm, yes that could be an issue. Could you give it a try with the image tagged `0.9.0` or even `latest`? I'd like to understand the root cause for the time out error.
> 
> What happens if you run this:
> 
> ```
> docker pull localstack/localstack:latest
> localstack infra start --docker
> ```
> Wait until "`Ready.`" appears in the logs (this may take a while), and then in a separate terminal:
> 
> ```
> pip install awscli-local
> awslocal s3 mb s3://test-bucket
> awslocal s3 ls
> ```
Hi @whummer, I tried run localstack on docker, but it never started on the command line. I got this error. I am attaching the complete log for your reference.
[localstack_logs.txt](https://github.com/localstack/localstack/files/2951627/localstack_logs.txt)



```
2019-03-11T09:40:19:ERROR:localstack.services.s3.s3_starter: S3 health check failed:  Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 14, in check_s3
wait_for_port_open(DEFAULT_PORT_S3_BACKEND)
File "/opt/code/localstack/localstack/utils/common.py", line 367, in wait_for_port_open
return retry(check, sleep=sleep_time, retries=retries)
File "/opt/code/localstack/localstack/utils/common.py", line 400, in retry
raise raise_error
Exception

2019-03-11T09:40:19:WARNING:infra.pyc: Service "s3" not yet available, retrying...
2019-03-11T09:40:19:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 380, in check_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 556, in start_infra
check_infra(apis=apis)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 389, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR: 'NoneType' object has no attribute '__getitem__'
```

**Comment by i-aggarwal** [comment] 2019-03-14 14:28
Hi @whummer,

I did manage to start the latest version of localstack image, but it still write the byte stream to "s3_api_calls.json" file and the actual files are not stored on the local machine.

I do understand you have a lot to work on this project. But is there going to a feature that will handle this use case if not soon, sometime in the future? Eagerly waiting for your reply.

Thanks,
Ishan Aggarwal

**Comment by motin** [comment] 2019-05-11 00:00
> I did manage to start the latest version of localstack image, but it still write the byte stream to "s3_api_calls.json" file and the actual files are not stored on the local machine.

You'll need to store the actual files on your local machine manually, like you would if you used S3. See https://stackoverflow.com/questions/31918960/boto3-to-download-all-files-from-a-s3-bucket/31929277#31929277 for an example in Python.

**Comment by whummer** [comment] 2019-11-29 11:12
Thanks all for chiming in and providing solutions and workarounds. Going to close this issue, as a solution is provided based on the `s3_api_calls.json` file. Let's please track the status of overall persistence support across services in this item: #164 

In the meantime, if some of you would be willing to work on a pull request to further improve persistence for S3, we'd be very happy to accept any improvements. Thanks

**Closed by whummer** 2019-11-29 11:12 UTC
Labels: question

**Comment by adams-family** [comment] 2021-07-09 13:37
I am running `LocalStack version: 0.12.15` and I confirm that the approach with the `s3_api_calls.json` file is working as long as the data directory is created before mounting.

This is my `docker-compose.yml` file:

```
version: "3.7"

services:
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - ./localstack:/tmp/localstack
```

I had to actually create the `./localstack/data` directory on my machine, the presence of `./localstack` which is created by docker/docker-compose automatically upon first run was not enough.

As a side note, the ever-growing .json file seems like an `event-sourcing` approach and probably will be super-intense during container start-up if one has large files - therefore I'd say one should delete this file and start from scratch occasionally.

**Comment by hlascelles** [comment] 2021-07-09 19:19
I will confess we gave up. The ever-growing json file just kept bringing our test services to their knees. We still use localstack for SQS and SNS, but have gone to [minio](https://docs.min.io/) for our S3 needs. Works perfectly for both docker-compose and Kubernetes.

**Comment by adams-family** [comment] 2021-07-09 20:16
@hlascelles I am impressed, minio is very well documented and worked like a charm, files are stored on the local drive, ready to browse as files!

Nonetheless, I am also impressed by localstack's extreme number of AWS compatible services, almost unbelievable, so I guess a combination of minio + localstack will work out well.

**Comment by korya** [comment] 2021-11-24 14:25
Hi guys, You have developed a great tool! But I could not make it to persist S3 data so we moved to `minio` as well. Thank you for your effort anyways! I know it is hard to please everyone.

**Comment by fuxiang-pki** [comment] 2022-02-07 11:47
It seems that LocalStack stores the S3 buckets info in `/tmp/localstack/recorded_api_calls.json`, which doesn't contain the S3 object data. So S3 objects will lost after restart a LocalStack docker container.

**Comment by developer992** [comment] 2024-05-21 11:31
It's probably a PRO only feature , since the example here https://docs.localstack.cloud/user-guide/state-management/persistence/ mentions `localstack-pro` but no word about community edition image ( or whatever it's called ) 

how could we confirm this?
