### ISSUE TITLE
put-method api-key-required does not seem to work 

### ISSUE THREAD

**Issue by satishkamat** [localstack/localstack#1916] opened 2020-01-03 13:06 UTC
Hello All,  

 I have created a method as below .. 
```
awslocal apigateway put-method --region us-east-1 --rest-api-id $REST_API_ID --resource-id '38ijyb6pxz'  --http-method GET --api-key-required  --authorization-type 'NONE' 
```

The above ran successfully but when i look up the details of this method using 
http://localhost:4567/restapis/xiqw6umv2e/resources 

The output is below  . Notice that the value of apiKeyRequired is **null** .    
Can someone please let me know whats the right way to make api key required to true.  
```
{"item": [{"path": "/", "id": "r893s5k2fz", "resourceMethods": {"GET": {}}}, {"path": "/dyn", "id": "wgi73lf00p",
"resourceMethods": {"GET": {"httpMethod": "GET", "authorizationType": "NONE", "authorizerId": null, **"apiKeyRequired":
nul**l, "requestParameters": null, "requestModels": null, "methodIntegration": {"type": "HTTP", "uri":
"http://host.docker.internal:8080/product-consumer/products/categories", "httpMethod": "GET", "requestTemplates": null,
"integrationResponses": {"200": {"responseTemplates": {"application/json": null}, "statusCode": 200}}}}}, "parentId":
"r893s5k2fz", "pathPart": "dyn"}]}
```

**Comment by whummer** [comment] 2020-05-23 23:02
Thanks for reporting @satishkamat . We haven't been able to reproduce this issue - seems to be fixed in the meantime. If I run the command you're describing, this is what I'm getting with the `latest` version:
```
$ awslocal apigateway get-resources --rest-api-id $apiId 
{
    "items": [
        ...
        {
            "id": "sp78m0cmwm",
            "parentId": "75dtgiz3ll",
            "pathPart": "parent1",
            "path": "/parent1",
            "resourceMethods": {
                "GET": {
                    "httpMethod": "GET",
                    "authorizationType": "NONE",
                    "apiKeyRequired": true
                }
            }
        },
...
```

Closing this issue - but please report here if the problem persists. Thanks!

**Closed by whummer** 2020-05-23 23:02 UTC
Labels: diverges-from-aws
