### ISSUE TITLE
DynamoDB does not start up properly in local installation on Linux

### ISSUE THREAD

**Issue by gregakespret** [localstack/localstack#241] opened 2017-08-14 05:27 UTC
I'm getting the following:

```bash
$ localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
ERROR:localstack.services.generic_proxy:Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe404c6c6d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/grega/miniconda2/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe404c6c6d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

```bash
$ uname -a
Linux grega-dev 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

$ node -v
v8.3.0

$ python --version
Python 2.7.13 :: Continuum Analytics, Inc.

$ localstack --version
0.7.4
```

Any hints? I've read a few threads about this problem, but nothing helps in my case. What should be running on 4564 ?

Thanks.

**Comment by whummer** [comment] 2017-08-14 13:36
Hi @gregakespret , thanks for reporting. Can you please enable detailed log output:
```
DEBUG=1 localstack start
```
It seems that DynamoDB cannot start up properly. Possibly the zip file has not been downloaded correctly, or one of the prerequisites (e.g., Java 8) is not installed properly.
Can you please post this output:
```
java -version
ls -la /home/grega/miniconda2/lib/python2.7/site-packages/localstack/infra/dynamodb/
java -jar /home/grega/miniconda2/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar -port 4564
```

**Comment by gregakespret** [comment] 2017-08-14 15:22
Sure thing, here's the output:

```bash
$ DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Error: Unable to access jarfile DynamoDBLocal.jar
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Listening at http://:::4565
Starting mock Lambda service (http port 4574)...
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
[2017-08-14T17:20:00,628][INFO ][o.e.n.Node               ] [] initializing ...
[2017-08-14T17:20:00,702][INFO ][o.e.e.NodeEnvironment    ] [_bWZGyo] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [11.9gb], net total_space [43.8gb], spins? [unknown], types [rootfs]
[2017-08-14T17:20:00,702][INFO ][o.e.e.NodeEnvironment    ] [_bWZGyo] heap size [483.3mb], compressed ordinary object pointers [true]
[2017-08-14T17:20:00,703][INFO ][o.e.n.Node               ] node name [_bWZGyo] derived from node ID [_bWZGyomS22c9oy9v_n2Vw]; set [node.name] to override
[2017-08-14T17:20:00,704][INFO ][o.e.n.Node               ] version[5.3.0], pid[8013], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/3.16.0-4-amd64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_05/25.5-b02]
[2017-08-14T17:20:01,310][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [aggs-matrix-stats]
[2017-08-14T17:20:01,310][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [ingest-common]
[2017-08-14T17:20:01,310][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [lang-expression]
[2017-08-14T17:20:01,310][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [lang-groovy]
[2017-08-14T17:20:01,311][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [lang-mustache]
[2017-08-14T17:20:01,311][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [lang-painless]
[2017-08-14T17:20:01,311][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [percolator]
[2017-08-14T17:20:01,311][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [reindex]
[2017-08-14T17:20:01,311][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [transport-netty3]
[2017-08-14T17:20:01,311][INFO ][o.e.p.PluginsService     ] [_bWZGyo] loaded module [transport-netty4]
[2017-08-14T17:20:01,312][INFO ][o.e.p.PluginsService     ] [_bWZGyo] no plugins loaded
[2017-08-14T17:20:03,184][INFO ][o.e.n.Node               ] initialized
[2017-08-14T17:20:03,184][INFO ][o.e.n.Node               ] [_bWZGyo] starting ...
[2017-08-14T17:20:03,314][INFO ][o.e.t.TransportService   ] [_bWZGyo] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2017-08-14T17:20:03,322][WARN ][o.e.b.BootstrapChecks    ] [_bWZGyo] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-08-14T17:20:03,322][WARN ][o.e.b.BootstrapChecks    ] [_bWZGyo] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-08-14T17:20:06,364][INFO ][o.e.c.s.ClusterService   ] [_bWZGyo] new_master {_bWZGyo}{_bWZGyomS22c9oy9v_n2Vw}{C_B9oiL4SCGFacmGXkclAA}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-08-14T17:20:06,402][INFO ][o.e.g.GatewayService     ] [_bWZGyo] recovered [0] indices into cluster_state
[2017-08-14T17:20:06,406][INFO ][o.e.h.n.Netty4HttpServerTransport] [_bWZGyo] publish_address {127.0.0.1:4560}, bound_addresses {[::1]:4560}, {127.0.0.1:4560}
[2017-08-14T17:20:06,409][INFO ][o.e.n.Node               ] [_bWZGyo] started
127.0.0.1 - - [14/Aug/2017 17:20:07] "GET / HTTP/1.1" 200 -
ERROR:localstack.services.generic_proxy:Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f293da16cd0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/grega/miniconda2/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f293da16cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

```bash
$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

$ ls -la /home/grega/miniconda2/lib/python2.7/site-packages/localstack/infra/dynamodb/
total 4888
drwxr-xr-x 2 grega grega    4096 Aug 14 05:36 .
drwxr-xr-x 5 grega grega    4096 Aug 14 05:39 ..
-rw-r--r-- 1 grega grega 4984832 Aug 14 05:36 ddb.zip

$ java -jar /home/grega/miniconda2/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar -port 4564
Error: Unable to access jarfile /home/grega/miniconda2/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar
```

**Comment by whummer** [comment] 2017-08-15 00:44
@gregakespret  Thanks for posting the details. This appears to be a duplicate of #213 . Can you please run the following commands:
```
mv $TMPDIR/localstack.ddb.zip $TMPDIR/localstack.ddb.old.zip
pip install --no-cache --upgrade localstack
localstack start
```

**Comment by gregakespret** [comment] 2017-08-18 00:32
@whummer Sorry for dropping the ball on this one for a few days. I do not have `localstack.ddb.zip` anywhere on the filesystem. I ran

```$ pip install --no-cache --upgrade localstack
Requirement already up-to-date: localstack in /home/grega/miniconda2/lib/python2.7/site-packages
Requirement already up-to-date: elasticsearch==5.3.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: python-coveralls==2.7.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: flask-swagger==0.2.12 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: moto-ext==1.0.1.7 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: coverage==4.0.3 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: docopt==0.6.2 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: flask-cors==3.0.3 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: jsonpath-rw==1.4.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: awscli==1.11.86 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: boto==2.46.1 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: airspeed==0.5.5.dev20160812 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: xmltodict==0.10.2 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: boto3==1.4.4 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: psutil==5.2.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: pyOpenSSL==17.0.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Collecting localstack-ext (from localstack)
  Downloading localstack-ext-0.7.0.7.tar.gz (50kB)
    100% |████████████████████████████████| 51kB 13.1MB/s
Requirement already up-to-date: nose==1.3.7 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: subprocess32-ext==3.2.8.2 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: six==1.10.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: flask==0.10.1 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: requests-aws4auth==0.9 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: pyYAML==3.12 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: pep8==1.7.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: requests==2.18.4 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack)
Requirement already up-to-date: urllib3<2.0,>=1.8 in /home/grega/miniconda2/lib/python2.7/site-packages (from elasticsearch==5.3.0->localstack)
Requirement already up-to-date: sh in /home/grega/miniconda2/lib/python2.7/site-packages (from python-coveralls==2.7.0->localstack)
Requirement already up-to-date: cookies in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: dicttoxml in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: mock in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: pytz in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: werkzeug in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: Jinja2>=2.8 in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Collecting pyaml (from moto-ext==1.0.1.7->localstack)
  Downloading pyaml-17.8.0-py2.py3-none-any.whl
Requirement already up-to-date: python-dateutil in /home/grega/miniconda2/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: ply in /home/grega/miniconda2/lib/python2.7/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already up-to-date: decorator in /home/grega/miniconda2/lib/python2.7/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already up-to-date: botocore==1.5.49 in /home/grega/miniconda2/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already up-to-date: rsa<=3.5.0,>=3.1.2 in /home/grega/miniconda2/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already up-to-date: docutils>=0.10 in /home/grega/miniconda2/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already up-to-date: s3transfer<0.2.0,>=0.1.9 in /home/grega/miniconda2/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already up-to-date: colorama<=0.3.7,>=0.2.5 in /home/grega/miniconda2/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already up-to-date: cachetools==0.8.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from airspeed==0.5.5.dev20160812->localstack)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in /home/grega/miniconda2/lib/python2.7/site-packages (from boto3==1.4.4->localstack)
Collecting cryptography>=1.7 (from pyOpenSSL==17.0.0->localstack)
  Downloading cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 11.3MB/s
Requirement already up-to-date: dnslib==0.9.7 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already up-to-date: pyaes==1.6.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already up-to-date: pyminifier==2.1 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already up-to-date: srp-ext==1.0.7.1 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already up-to-date: warrant-ext>=0.2.0.3 in /home/grega/miniconda2/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already up-to-date: itsdangerous>=0.21 in /home/grega/miniconda2/lib/python2.7/site-packages (from flask==0.10.1->localstack)
Collecting idna<2.7,>=2.5 (from requests==2.18.4->localstack)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 16.6MB/s
Requirement already up-to-date: certifi>=2017.4.17 in /home/grega/miniconda2/lib/python2.7/site-packages (from requests==2.18.4->localstack)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/grega/miniconda2/lib/python2.7/site-packages (from requests==2.18.4->localstack)
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in /home/grega/miniconda2/lib/python2.7/site-packages (from mock->moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: pbr>=0.11 in /home/grega/miniconda2/lib/python2.7/site-packages (from mock->moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: MarkupSafe>=0.23 in /home/grega/miniconda2/lib/python2.7/site-packages (from Jinja2>=2.8->moto-ext==1.0.1.7->localstack)
Requirement already up-to-date: pyasn1>=0.1.3 in /home/grega/miniconda2/lib/python2.7/site-packages (from rsa<=3.5.0,>=3.1.2->awscli==1.11.86->localstack)
Requirement already up-to-date: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /home/grega/miniconda2/lib/python2.7/site-packages (from s3transfer<0.2.0,>=0.1.9->awscli==1.11.86->localstack)
Requirement already up-to-date: ipaddress in /home/grega/miniconda2/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already up-to-date: asn1crypto>=0.21.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already up-to-date: enum34 in /home/grega/miniconda2/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already up-to-date: cffi>=1.7 in /home/grega/miniconda2/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already up-to-date: envs>=0.3.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already up-to-date: python-jose-ext>=1.3.2.2 in /home/grega/miniconda2/lib/python2.7/site-packages (from warrant-ext>=0.2.0.3->localstack-ext->localstack)
Collecting pycparser (from cffi>=1.7->cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 28.9MB/s
Requirement already up-to-date: click>=6.6 in /home/grega/miniconda2/lib/python2.7/site-packages (from envs>=0.3.0->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already up-to-date: terminaltables>=3.0.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from envs>=0.3.0->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already up-to-date: future<1.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already up-to-date: pycryptodome<3.4.0,>=3.3.1 in /home/grega/miniconda2/lib/python2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already up-to-date: ecdsa<1.0 in /home/grega/miniconda2/lib/python2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Installing collected packages: localstack-ext, pyaml, idna, cryptography, pycparser
  Found existing installation: localstack-ext 0.7.0.5
    Uninstalling localstack-ext-0.7.0.5:
      Successfully uninstalled localstack-ext-0.7.0.5
  Running setup.py install for localstack-ext ... done
  Found existing installation: pyaml 17.7.2
    Uninstalling pyaml-17.7.2:
      Successfully uninstalled pyaml-17.7.2
  Found existing installation: idna 2.5
    Uninstalling idna-2.5:
      Successfully uninstalled idna-2.5
  Found existing installation: cryptography 1.8.1
    Uninstalling cryptography-1.8.1:
      Successfully uninstalled cryptography-1.8.1
  Found existing installation: pycparser 2.17
    DEPRECATION: Uninstalling a distutils installed project (pycparser) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pycparser-2.17:
      Successfully uninstalled pycparser-2.17
  Running setup.py install for pycparser ... done
Successfully installed cryptography-2.0.3 idna-2.6 localstack-ext-0.7.0.7 pyaml-17.8.0 pycparser-2.18```

and ```$ localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2017-08-18T02:30:14:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a505dc350>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/grega/miniconda2/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/grega/miniconda2/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a505dc350>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Still the same result. Any ideas?

**Comment by gregakespret** [comment] 2017-08-18 00:42
Got it to work. Thanks for all the help.

Steps I needed to take:

```
$ rm -rf /home/grega/miniconda2/lib/python2.7/site-packages/localstack/infra/dynamodb/
```
(this is where previously I had `ddb.zip`)

```
$ pip uninstall localstack
$ pip install --no-cache --upgrade localstack
$ localstack start
Starting local dev environment. CTRL-C to quit.
2017-08-18T02:39:07:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Ready.
```

**Closed** 2017-08-18 00:44 UTC
Labels: installation, possible-duplicate, priority-high
