### ISSUE TITLE
Read timeout on endpoint URL: Lambda on update-function-code

### ISSUE THREAD

**Issue by tilakbhanu** [localstack/localstack#3177] opened 2020-10-27 09:01 UTC
# Type of request: This is a ...
[X ] bug report
[ ] feature request

# Detailed description
Running following command 
 aws lambda update-function-code --function-name lamdaforunsecureauthentication1 --s3-bucket mytestbucket --s3-key built.zip --endpoint-url=http://localhost:4566

...

## Expected behavior
Should update lambda with the latest built code.
...

## Actual behavior
Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/lamdaforunsecureauthentication1/code"

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-79) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-12-13 21:01
Thanks for reporting @tilakbhanu . Can you please share some details about your environment:
* What is the size of your Lambda archive zip file? Can you share a copy of the file?
* Are you able to access any other LocalStack API endpoints?
* What is the output of the health endpoint: `http://localhost:4566/health`

Would be great if you could provide some more details to help us reproduce this issue. Thanks.

**Comment by whummer** [comment] 2021-03-21 12:42
Closing this issue, as "cannot reproduce". Please reopen this issue with detailed instructions to reproduce if the problem persists @tilakbhanu . Thanks!

**Closed by whummer** 2021-03-21 12:42 UTC
Labels: awaiting reporter response, cannot-reproduce, evaluate-or-close, needs-triaging, networking

**Comment by macleanpinto** [comment] 2022-12-16 14:19
This issue is reproducible with files larger than 1 MB.
