### ISSUE TITLE
connectivity issue between local elasticsearch and mock aws es  

### ISSUE THREAD

**Issue by nilishas** [localstack/localstack#296] opened 2017-09-04 06:47 UTC
While it is possible to create, list , delete and describe domain on mock aws es  and index data to local elasticsearch, there seems to be a disconnect between the two when trying to index data to a particular domain created by mock aws es.

**Comment by whummer** [comment] 2017-09-04 07:21
Thanks for reporting @nilishas . That's correct, the integration between Elasticsearch and the ES service is currently still missing. Would you be able to start working on an initial version of that integration? I'd be happy to provide guidance and help out where needed. Would be great if we could start with a simple self-contained test case of what we're trying to achieve from an app perspective. Thanks!

**Comment by nilishas** [comment] 2017-09-04 08:57
On AWS ES , with creation of a domain, it's elasticsearch instances are created (based on requirement) . As I see it, the mock AWS ES currently allows for only one instance for a domain. If we start with that ( later on make the domain configuration flexible ) and try to do the integration for one domain and one instance, a possible way I see is to configure the local elasticsearch instance on creation of a domain, and point the cluster.name to the domain that is to be used.  Let me know if that's a possible workaround or if you have a better approach to go about it.

**Comment by Jitendraujn** [comment] 2019-07-15 07:17
@whummer Could you please update, whether this integration has been included in some version.
I am also facing the same issue.

Using localstack version: 0.9.0: 
1. able to create/update/delete domain using AWS SDK and AWS CLI
2. Able to index data into elasticsearch but without any domain.


Can you please point me the version where this is included.
Observation:
1. When I create domain using mock ES this provides me a endpoint
http:<someencodedtext>:4571 [Port 4571 is default port for local elasticsearch], so can I assume, that integration has been working between the two in version0.9.0.
If so then, why aren't I am given an option in index my data into created domain.

Could you please point me to some commands or SDK, which I can use and index my data into domain.

Please help, I am kind of stuck with this and need your help uregently

Thanks,
Jitendra

**Comment by Jitendraujn** [comment] 2019-07-15 07:30
@nilishas any comment on this issue , how you dealt with this ? It would be of great help, if you can provide some info.

**Comment by nilishas** [comment] 2019-07-15 07:46
@Jitendraujn in my case I modified the code to start an Elasticsearch instance in a docker container whenever I got a create domain request and configured it as per the request. You can fetch version based docker images for Elasticsearch from Dockerhub, or you can add code to run a local instance, but in that case, you must have the version installed on your system, that's not a very flexible and resourceful idea in my opinion.

**Comment by Jitendraujn** [comment] 2019-07-15 08:25
@nilishas Thanks for the response.

I am running docker image of localstack, and when I am starting the ES service:

> $ SERVICES=es docker-compose up
this automatically starts two services:
localstack_1  | Starting mock ES service (http port 4578)...
localstack_1  | Starting local Elasticsearch (http port 4571)...

When you say: 
"I got a create domain request and configured it as per the request"

What sort of configuration you did to interlink both service.

Just a few points:
1. When I create domain using aws cli on ES service port[4578], it gives me endpoint:host:4571.
aws es create-elasticsearch-domain --domain-name testdomain --endpoint-url http://myhost:4578

{
    "DomainStatus": {
        "DomainId": "000000000000/testdomain",
        "DomainName": "testdomain",
        "ARN": "arn:aws:es:us-east-1:000000000000:domain/testdomain",
        "Created": true,
        "Deleted": false,
        "Endpoint": "http://3ae2a9b7a675:4571",
        "Processing": false,
        "ElasticsearchVersion": "6.7",
        "ElasticsearchClusterConfig": {
            "InstanceType": "m3.medium.elasticsearch",
            "InstanceCount": 1,
            "DedicatedMasterEnabled": true,
            "ZoneAwarenessEnabled": false,
            "DedicatedMasterType": "m3.medium.elasticsearch",
            "DedicatedMasterCount": 1
        },
        "EBSOptions": {
            "EBSEnabled": true,
            "VolumeType": "gp2",
            "VolumeSize": 10,
            "Iops": 0
        }
    }
}

Thus can I assume that there is a connection between the two services.

2. After creating this domain, I can not use this anywhere [May be I dont know how to use it] to put index data into this domain: "testdomain".
3. Though I can use port 4571 along with host to create index and put data into it.
4. How did you configure this, can you please detail me here if possible.


Thanks,
Jitendra

**Comment by nilishas** [comment] 2019-07-15 08:40
The issue is still open and as per the code, I assume integration hasn't been done yet- the domain isn't actually created, you just get an aws like response. To make it work, "add some lines of code" to start up another docker container for elasticsearch. You can ignore the running elasticsearch instance in that case. Indexing should work conveniently once the instance is running.

**Comment by Jitendraujn** [comment] 2019-07-15 10:29
@nilishas domain is getting created, I can see domain using port: 4578

`http://host:4578/<default_index>/<default_type>/domain/<domain_name>
`
I checked using aws cli also using commands;

`aws es list-domains --endpoint-url http:<host>:4578`

But yeah you may be right, as this endpoint is just for name sack which I cant use to create index, through port[4571] only I could see there is some link between the two

now coming to creating index and pushing data.

I am able to use aws client:   to create index and push data using rest API.

Only thing which I am missing is "creating index under some domain"

Thanks,
Jitendra

**Comment by whummer** [comment] 2019-11-08 18:05
> Could you please update, whether this integration has been included in some version.

@Jitendraujn this is unfortunately still not supported. We'd be very happy to accept a pull request, though, if you manage to add this integration. Thanks!

**Comment by Aman-gupta19** [comment] 2020-02-12 10:45
> @nilishas domain is getting created, I can see domain using port: 4578
> 
> `http://host:4578/<default_index>/<default_type>/domain/<domain_name> `
> in my case: `default_index=2015-01-01 default_type=es`
> I checked using aws cli also using commands;
> 
> `aws es list-domains --endpoint-url http:<host>:4578`
> 
> But yeah you may be right, as this endpoint is just for name sack which I cant use to create index, through port[4571] only I could see there is some link between the two
> 
> now coming to creating index and pushing data.
> 
> I am able to use aws client: to create index and push data using rest API.
> 
> Only thing which I am missing is "creating index under some domain"
> 
> Thanks,
> Jitendra

hey, 

what to do after creating domain?

i have domain and aws s3 is also there, also files are present in aws s3.

how can i index and map the data and search with elasticsearch.

please reply ASAP it's very urgent.
regards,
Aman

**Comment by Jitendraujn** [comment] 2020-02-12 18:47
I haven't used this ES given as part of localstack....if you want to use this ...you need to go ahead with default index, which I mentioned above, you won't be able to create another index, use the default index and use the port I mentioned above to push data through some application reading from S3 and pushing it to ES .

**Comment by Aman-gupta19** [comment] 2020-02-13 05:42
> I haven't used this ES given as part of localstack....if you want to use this ...you need to go ahead with default index, which I mentioned above, you won't be able to create another index, use the default index and use the port I mentioned above to push data through some application reading from S3 and pushing it to ES .

hey, how am i supposed to index files present in s3, i am not able to find how to link ES and s3.
I'm sorry to disturb you but i'm really stuck at this and cannot find enough resources for the problem i'm facing.
regards,Aman

**Comment by Aman-gupta19** [comment] 2020-02-13 05:42
hey, how am i supposed to index files present in s3, i am not able to find
how to link ES and s3.

I'm sorry to disturb you but i'm really stuck at this and cannot find
enough resources for the problem i'm facing.

regards,
Aman

**Comment by Jitendraujn** [comment] 2020-02-21 14:13
In your case I could think of one approach:
Create an application let say Java Spring boot application of a AwS Lambda.
Application will have two factory to connect to S3 and ES.
These client you will have to use in same application, then write one service which will make use of aws-sdk for S3 to read files from S3, then in another service, make use of elastic search client and index the file read in S3 Service.

Java application:
---> ES client pointing to Localstack ES on Port I mentioned above
---> S3 client pointing to S3 bucket
---> S3Service: Use aws-sdk to read files by making Use of S3 client.
---->ES service: use aws-sdk to index content in default index of ES, make use of ESclient to preserve data.

**Comment by Aman-gupta19** [comment] 2020-03-06 06:42
my ES port 4578 is not responding in localstack how to fix that?

and also can anyone tell me how to delete domain on port 4578.

thank you in advance !

**Comment by Jitendraujn** [comment] 2020-03-07 02:56
without logs its difficult to predict what might have gone wrong. however try this once.
$ SERVICES=es docker-compose up --> use service name while bringing up docker compose.
this automatically starts two services:
localstack_1 | Starting mock ES service (http port 4578)...
localstack_1 | Starting local Elasticsearch (http port 4571)

**Comment by whummer** [comment] 2020-06-20 15:00
Thanks all for reporting, and thanks for providing a fix @Jitendraujn . The ES service and integration with Elasticsearch has been refactored in the meantime, and it seems that the issues reported here should already be addressed in the meantime. If there are any other remaining issues, please feel free to create follow-up tickets with detailed steps to reproduce @Aman-gupta19 . Thanks!

**Closed by whummer** 2020-06-20 15:00 UTC
Labels: enhancement, integration-missing

**Comment by ashameem123** [comment] 2021-01-06 22:10
@Jitendraujn - I am trying to read data from es index (ES is fed by lambda). 
I am creating a separate ES container mocking ES (6.8 version). I need your help in  understanding how to read data from the ES running in a separate container. I think this container won't be considered part of locatstack since it is running separately and is not spinning inside localstack port?

Is there a command to read index data in Localstack which i can run?

My docker-compose file looks like this-

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch6-8/data
    ports:
      - 9200:9200

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}"
    environment:
      - AWS_REGION=us-east-1
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=ecare-localstackdemoallservices_default
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by ashameem123** [comment] 2021-01-07 16:53
@Jitendraujn - Could you please provide details on how to achieve this step you mentioned above-

Able to index data into elasticsearch but without any domain.

i have a ES mock running in a diff container, how to add data in the index in this situation?
