### ISSUE TITLE
SQS bad request on sendMessage with AWS Node SDK (previously working)

### ISSUE THREAD

**Issue by madhuravius** [localstack/localstack#910] opened 2018-08-27 20:10 UTC
The version: 0.8.7 works fine for me, but currently latest throws this error (when using SQS.sendMessage()):

```
error: query.js:47:29: SEND SQS Error: {"message":"InvalidParameterValue; see the SQS docs.","code":"InvalidParameterValue","time":"2018-08-27T20:00:27.443Z","statusCode":400,"retryable":false,"retryDelay":99.07964982234161}, ERROR MESSAGE: InvalidParameterValue: InvalidParameterValue; see the SQS docs., ERROR TRACE: InvalidParameterValue: InvalidParameterValue; see the SQS docs.
```

Looking at the body of my sendMessage, I checked the SDK ([Link to SDK Docs for sendMessage()](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#sendMessage-property)).

An example object passed into sendMessage that functioned previously that does not function on latest:

```
{ MessageGroupId: 'Testing',
  MessageBody: '"{\\"randomNum\\":0.7610595996761194}"',
  QueueUrl: 'http://localhost:4576/queue/test_q.fifo' }
```

Examining the actual data it looks like it was pushing the correct object correctly. It looks like elasticMQ was updated in the last few weeks, was this a potential bug caused by that update?

**Comment by srouaix** [comment] 2018-09-03 14:34
I have the same issue using the latest docker image of localstack published today

**Comment by mberlanda** [comment] 2018-09-03 21:28
Hi, could you provide more details to reproduce the issue?
How did you create the fifo queue? Can you put the queue details?
I would be interesting to reproduce this case both on localstack and eventually on elasticmq to find a fix.

Would you get the same issue with the aws cli or Node SDK only?

**Comment by mberlanda** [comment] 2018-09-03 21:36
Btw it looks like an elasticmq issue which is appearing for .NET sdk as well: https://github.com/adamw/elasticmq/issues/150

**Comment by ZuluForce** [comment] 2018-10-29 16:50
I am experiencing this problem as well and have what I think is a minimally reproducible scenario.

Localstack version: `0.8.7`
AWS CLI version: `aws-cli/1.16.17 Python/2.7.10 Darwin/17.7.0 botocore/1.12.7`

Here's the steps to reproduce:
```
$ aws sqs create-queue --endpoint http://localstack:4576 --queue-name status.fifo --attributes '{"FifoQueue": "true"}'
{
    "QueueUrl": "http://localhost:4576/queue/status.fifo"
}

$ aws sqs list-queues --endpoint http://localstack:4576
{
    "QueueUrls": [
        "http://localhost:4576/queue/status.fifo"
    ]
}

$ aws sqs send-message --endpoint http://localstack:4576 --queue-url "http://localhost:4576/queue/status.fifo" --message-body '{"msg": "hello"}'

An error occurred (InvalidParameterValue) when calling the SendMessage operation: InvalidParameterValue; see the SQS docs.
```

This appears to be related to the version of AWS cli used to create the queue. A coworker used AWS cli version `aws-cli/1.14.63 Python/3.6.4 Darwin/17.7.0 botocore/1.9.16` and the queue name returned from `list-queues` returned the url `http://localhost:4576/queue/status_fifo`. For him he can then `send-message` using the `_` version of the url. For me I will get a queue not found error because the actual queue name has `.fifo`.

As the linked elasticmq issue indicates, it is most likely a validation issue on sending. It just happens that I think you can get around things if you have a sufficiently old enough version of the AWS cli since the queue url will be created with an underscore.

**Comment by samlindsaylevine** [comment] 2018-10-29 20:59
I am the coworker: I can confirm that when I run 

```
$ aws sqs create-queue --endpoint http://localstack:4576 --queue-name status.fifo --attributes '{"FifoQueue": "true"}'
```

I get

```
{
    "QueueUrl": "http://localhost:4576/queue/status_fifo"
}
```

and then I can send a message to the queue without error.

This is with aws-cli version `aws-cli/1.14.63 Python/3.6.4 Darwin/17.7.0 botocore/1.9.16` and using the same Localstack `0.8.7` as @ZuluForce (launched via Docker).

**Comment by samlindsaylevine** [comment] 2018-10-30 21:17
Thanks so much for the detailed explanation @mberlanda ! It seems that the difficulties that we encountered are unrelated to this issue. We were able to move forward as you described.

It might be nice, as an enhancement, if it were possible for the returned error message to be more descriptive than `An error occurred (InvalidParameterValue) when calling the SendMessage operation: InvalidParameterValue; see the SQS docs.` - if it had included anything along the lines of "you are missing a group ID" we wouldn't have bothered you!

It also was a little surprising that we had two different localstack `0.8.7` images, pulled at different times, that had meaningfully different behavior! This took us a while to diagnose.

I greatly appreciate your assistance. Thank you again!

**Comment by mberlanda** [comment] 2018-10-31 05:58
Hey @samlindsaylevine you are welcome.

I tried to implement more explicit error codea in elasticmq in this PR:

https://github.com/adamw/elasticmq/pull/148/files

I may try to have a look at why it is not returning the name of the missing attribute.

**Comment by kpollardsprypoint** [comment] 2019-02-19 17:36
> I am the coworker: I can confirm that when I run
> 
> ```
> $ aws sqs create-queue --endpoint http://localstack:4576 --queue-name status.fifo --attributes '{"FifoQueue": "true"}'
> ```
> I get
> 
> ```
> {
>     "QueueUrl": "http://localhost:4576/queue/status_fifo"
> }
> ```
> and then I can send a message to the queue without error.
> 
> This is with aws-cli version `aws-cli/1.14.63 Python/3.6.4 Darwin/17.7.0 botocore/1.9.16` and using the same Localstack `0.8.7` as @ZuluForce (launched via Docker).
> 
> It seems like the Localstack problem is that it is having trouble with this queue with a `.` in its URL, and this was exposed by the differing behaviours of our two AWS CLI versions in terms of what URL a FIFO queue (whose _name_ must end with `.fifo`) ends up with?
> 
> Edited to add: It turned out the differing AWS CLI versions was a complete red herring. Despite us both having launched Localstack `0.8.7` via Docker, my image had sha256 hash `044ca6975c74d1c68da26576f67482df45a8a56b454bb452529715244f5d5544` and his had sha256 hash `ac1af9b263a0e0a62a3316f585cf4804fabf0f97233e2c6d1cb4161ec192568c`.
> 
> When I removed my local version of the image with `docker rmi`, then launched it again, pulling `0.8.7` from the central public repository, I ended up with the version of `0.8.7` with the `ac1af` hash. Then creating this queue did end up for me having a URL ending with `status.fifo`, no longer `status_fifo`, and I also could not successfully send a message to it, seeing the same error as @ZuluForce .
> 
> Edited to further add: When using Localstack `0.8.6`, I found that the queue's URL had the `_` and not the `.` and I could send messages to it successfully. An actual AWS SQS FIFO queue _does_ have a `.` in its URL, so replicating this behavior in Localstack (as the most recent image of 0.8.7 does) is probably more correct... but only if the queue ends up actually able to receive messages, of course!

I had the same result with your test case, but then noticed that the test case is trying to post to endpoint http://localstack:4576 where it should be endpoint http://localhost:4576

**Comment by Adverbly** [comment] 2019-03-13 19:19
I had a similar problem which ended up being a user error. I wasn't creating a fifo queue properly. A couple things are needed to replicate the aws constraints: 

1) Fifo queues have to be named with a suffix .fifo
2) Fifo queues must be created with attributes
```json
{
   "FifoQueue": "true",
   "ContentBasedDeduplication": "true"
}
```
3) Fifo queues must have send-message called with a message-group-id, which is the mechanism that fifo queues use to scope the fifo-ness to things with the same message-group-id.

**Comment by kojoa** [comment] 2019-08-08 06:09
For anyone else struggling to get this work, this sentence is the key
> 2. Fifo queues must be created with attributes

Attributes needs to be added with `create-queue`. Setting them after queue creation with `set-queue-attributes` does not work.

**Comment by whummer** [comment] 2019-11-26 23:52
Thanks for reporting @madhuravius @srouaix @mberlanda @ZuluForce @samlindsaylevine @kpollardsprypoint @Adverbly @kojoa . From what I understand, this issue seems to be fixed in the latest version. Thanks all for posting your solutions. Closing this issue - please re-open if the problem persists. Thanks!

**Closed by whummer** 2019-11-26 23:52 UTC

**Comment by tarunsingh2789** [comment] 2020-12-30 20:29
> FifoQueue

How I can set these values in java policy object?
