### ISSUE TITLE
bug: downloading content at runtime results in API rate limits being hit?

### ISSUE THREAD

**Issue by nefilim** [localstack/localstack#7148] opened 2022-11-08 22:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
STDOUT: 2022-11-08 22:30:32,630 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
STDOUT: 2022-11-08 22:30:32,632 INFO supervisord started with pid 16
STDOUT: 2022-11-08 22:30:33,634 INFO spawned: 'infra' with pid 21
STDOUT: SERVICES variable is ignored if EAGER_SERVICE_LOADING=0.
STDOUT: LocalStack version: 1.2.0
STDOUT: 2022-11-08 22:30:34,840 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
STDOUT: LocalStack Docker container id: 909496f36c9b
STDOUT: LocalStack build date: 2022-10-07
STDOUT: LocalStack build git hash: 9be2a7aa
STDOUT: Error starting infrastructure: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
STDOUT: Traceback (most recent call last):
```

### Expected Behavior

Remote content should not be checked or downloaded at runtime 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

We are using testcontainers 

### Environment

```markdown
- OS: OS name: "Linux", version: 4.14.243-185.433.amzn2.x86_64, arch: amd64
- LocalStack: 1.2.0
```

**Comment by LuckySpb** [comment] 2022-11-09 01:52
I have similar issue, localstack doesn't start with on machine without internet connection, trying to call api.github.com

`requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/etspaceman/kinesis-mock/releases/tags/0.2.5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1dd934f280>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Comment by ihmabreu** [comment] 2022-11-17 16:57
@nefilim check https://github.com/localstack/localstack/issues/7103, the root cause was already identified. Try rollback to a previous version or use the latest one instead.

**Comment by otbe** [comment] 2022-11-28 13:54
@ihmabreu right now theres no newer version available right? Was looking for 1.2.x but couldnt find anything.

**Comment by otbe** [comment] 2022-11-28 14:20
Is there a known workaround besides downgrading? Seems to have a pretty big impact also from a security perspective 🤔

**Comment by weickmanna** [comment] 2022-12-30 16:49
Localstack is such an amazing product, but this remote downloading on startup really makes it very unstable and causes all sorts of problems. Builds not running at all because of rate limits. Builds sometimes failing because of timeouts.

**Comment by bskart** [comment] 2023-01-26 07:17
I downgraded to 1.1 some time ago as suggested in another issue, but now i see it happen with 1.1 aswell.

Our pipelines on Bitbucket Pipelines run into issues with failing/timeout.

Is there a technical reason to not include all of this into the image itself ? 

Is there a workaround with an ENV-variable for a GITHUB-token ?

```
ValueError: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Comment by DavidTanner** [comment] 2023-04-21 13:51
This is also an issue with the `2.0` release.  Some of the closed issues mentioned a lib folder `/var/lib/localstack/lib`, but that appears to be empty as of `1.4`.  I can't update any of my projects that rely on kinesis until this is fixed.

**Comment by isumaeru46** [comment] 2023-04-26 15:22
I have the same problem. 
I was using version `1.4.0` which already had kinesis_mock pre-installed in the `/usr/lib/localstack/kinesis-mock/0.3.4/kinesis-mock.jar` directory:
```
[   asgi_gw_6] plugin.manager             : instantiating plugin PluginSpec(localstack.aws.provider.kinesis:default = <function kinesis at 0xffff89b25900>)
[   asgi_gw_6] plugin.manager             : loading plugin localstack.aws.provider:kinesis:default
[   asgi_gw_6] l.services.plugins         : checking service health kinesis:4566
[   asgi_gw_6] localstack.packages.api    : Installation of kinesis-mock skipped (already installed).
[   asgi_gw_6] l.s.k.kinesis_mock_server  : starting kinesis process ['java', '-XX:+UseG1GC', '-jar', '/usr/lib/localstack/kinesis-mock/0.3.4/kinesis-mock.jar'] with env vars...
```



But now that I've updated to version `2.0.2` I'm getting the error `API rate limit exceeded`

**Comment by DavidZbarsky-at** [comment] 2023-06-01 15:26
See https://github.com/localstack/localstack/issues/7924#issuecomment-1572135824 for a workaround, you should be able to add an extra RUN directive to the Dockerfile if you are willing to build/host your own image

**Comment by alexrashed** [comment] 2023-06-02 07:33
Also, as mentioned in https://github.com/localstack/localstack/issues/7924#issuecomment-1572135824, you can set the `GITHUB_API_TOKEN` environment variable to a valid GitHub token. This will be picked up by LocalStack when downloading from GitHub, which increases the rate limit quite a lot (we also do this in our test pipelines).
I will close this issue for now.

**Closed by alexrashed** 2023-06-02 07:33 UTC
Labels: type: bug, area: infrastructure

**Comment by ShedPlant** [comment] 2023-07-11 15:53
I have just encountered this and will try setting `GITHUB_API_TOKEN` environment variable when starting `localstack`.

But I would rather DynamoDB/Kinesis on localstack 'just worked' without extra configuration. Even if I had to specify a different docker tag to download which already included kinesis.
