### ISSUE TITLE
PutError with PynamoDB ListAttribute

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#4187] opened 2021-06-22 12:59 UTC
[X] bug report
[ ] feature request

# Detailed description
I'm classifying this as a localstack bug because my code works properly against an AWS DynamoDB table, but NOT against localstack DynamoDB.

PynamoDB provides a DynamoDB API. Using PynamoDB 5.0.3, I've created a table definition that contains a ListAttribute, like so:

```
class MyModel(Model):
    class Meta:
        ...

    hash_key = UnicodeAttribute(hash_key=True)
    email_domains = ListAttribute(null=True)
    ....
```

I then try to instantiate a MyModel instance and save it. I can save it if I do NOT set the value of email_domains. When I try to 
set the value of the `email_domains` field and save the instance, like so:

```
my_model.email_domains = ['example.com']
my_model.save()
```

I receive `PutError: Failed to put item: An error occurred (ValidationException) on request (769be558-4532-489d-b793-88bbe14787aa) on table (my_table) when calling the PutItem operation: Invalid attribute value type`.

## Expected behavior
A ListAttribute receives an untyped List of arbitrary base types (str, int, etc.). The PutItem operation should succeed.

## Actual behavior
`PutError: Failed to put item: An error occurred (ValidationException) on request (769be558-4532-489d-b793-88bbe14787aa) on table (my_table) when calling the PutItem operation: Invalid attribute value type` received.

# Steps to reproduce
See above

## Command used to start LocalStack
docker compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
class MyModel(Model):
    class Meta:
        table_name = 'my_table'

    hash_key = UnicodeAttribute(hash_key=True)
    email_domains = ListAttribute(null=True)
    
MyModel.create_table()
my_model = MyModel(hash_key='1234abcd')
my_model.save() # succeeds
my_model.email_domains = ['example.com']
my_model.save() #throws error referenced above
```

**Comment by whummer** [comment] 2021-06-24 21:46
Thanks for reporting @holyoaks .

Looks like we haven't been able to reproduce this issue. Had to slightly adapt the script you've shared to the following:
```
from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, ListAttribute

class MyModel(Model):
    class Meta:
        table_name = 'my_table'
        host = 'http://localhost:4566'

    hash_key = UnicodeAttribute(hash_key=True)
    email_domains = ListAttribute(null=True)

MyModel.create_table(read_capacity_units=1, write_capacity_units=1, wait=True)
my_model = MyModel(hash_key='1234abcd')
my_model.save()
my_model.email_domains = ['example.com']
my_model.save()
```

Running the following commands with a fresh LocalStack instance yields the results below:
```
$ python test.py
$ awslocal dynamodb scan --table-name my_table
{
    "Items": [
        {
            "hash_key": {
                "S": "1234abcd"
            },
            "email_domains": {
                "L": [
                    {
                        "S": "example.com"
                    }
                ]
            }
        }
    ],
    "Count": 1,
    "ScannedCount": 1,
    "ConsumedCapacity": null
}
```
Are you able to replicate the results above? Can you please confirm if the problem still persists after pulling the `latest` Docker image? Thanks for your help!

**Comment by holyoaks** [comment] 2021-06-25 12:50
Thanks for your response. You asked if I can replicate after pulling the latest localstack image? I can't tell you. Rebuilding my entire Docker app with localstack:latest results in continuous errors, so I can't start up to test this for you. See error below:
  
​
  
​Traceback (most recent call last):
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
  
localstack_1          |          chunked=chunked,
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
  
localstack_1          |          conn.request(method, url, **httplib_request_kw)
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
  
localstack_1          |          super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  
localstack_1          |      File "/usr/lib/python3.7/http/client.py", line 1277, in request
  
localstack_1          |          self._send_request(method, url, body, headers, encode_chunked)
  
localstack_1          |      File "/usr/lib/python3.7/http/client.py", line 1323, in _send_request
  
localstack_1          |          self.endheaders(body, encode_chunked=encode_chunked)
  
localstack_1          |      File "/usr/lib/python3.7/http/client.py", line 1272, in endheaders
  
localstack_1          |          self._send_output(message_body, encode_chunked=encode_chunked)
  
localstack_1          |      File "/usr/lib/python3.7/http/client.py", line 1032, in _send_output
  
localstack_1          |          self.send(msg)
  
localstack_1          |      File "/usr/lib/python3.7/http/client.py", line 972, in send
  
localstack_1          |          self.connect()
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
  
localstack_1          |          conn = self._new_conn()
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
  
localstack_1          |          self, "Failed to establish a new connection: %s" % e
  
localstack_1          | urllib3.exceptions.NewConnectionError:  <urllib3.connection.HTTPConnection object at 0x7f6959721a10>: Failed to establish a new connection: [Errno 111] Connection refused
  
localstack_1          |
  
localstack_1          | During handling of the above exception, another exception occurred:
  
localstack_1          |
  
localstack_1          | Traceback (most recent call last):
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
  
localstack_1          |          timeout=timeout
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
  
localstack_1          |          method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  
localstack_1          |      File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
  
localstack_1          |          raise MaxRetryError(_pool, url, error or ResponseError(cause))
  
localstack_1          | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='localhost', port=58703): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6959721a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
  
​
  
  
  
Shawn

**Comment by whummer** [comment] 2021-06-26 13:04
Thanks for the update @holyoaks . As far as the startup issue with the `latest` image is concerned - it could potentially be related to a change in the Kinesis API provider we've recently introduced. Which hardware and OS are you using - we've seen some hiccups on particular hardwares/machines (e.g., on Macbook M1 laptops with ARM processors). Apologies for the inconvenience - if you can share some more details (e.g., full logs of your LocalStack container), we'll be happy to look into it.

There's a workaround in place, setting `KINESIS_PROVIDER=kinesalite`  in the container environment allows you to switch to the previous provider implementation.

Closing this issue, as the startup issue above seems unrelated to the original issue. If you are able to replicate the DynamoDB with `latest`, please feel free to re-open this issue. Thanks for your help!

**Closed by whummer** 2021-06-26 13:04 UTC
Labels: needs-triaging
