### ISSUE TITLE
S3 PutObjectResponse ParseError when using Rusoto

### ISSUE THREAD

**Issue by Steffey** [localstack/localstack#1647] opened 2019-10-13 17:21 UTC
Created a bucket using terraform:

```
resource "aws_s3_bucket" "bucket" {
  bucket = "my-tf-test-bucket"
  acl    = "public-read-write"
}


provider "aws" {
  access_key                  = "mock_access_key"
  region                      = "us-west-2"
  s3_force_path_style         = true
  secret_key                  = "mock_secret_key"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    s3             = "http://localhost:4572"
  }
}
```

Rust snippet:

```
let s3_client = S3Client::new(Region::Custom {
        name: "localstack".to_owned(),
        endpoint: "http://localhost:4572".to_owned(),
});

let result = s3_client.put_object(PutObjectRequest {
            bucket: "my-tf-test-bucket".to_owned(),
            key: "aaaaaaa".to_owned(),
            body: Some("Hello".to_owned().into_bytes().into()),
            ..Default::default()
}).sync();
println!("{:?}", result);
```

Results in:
`
Err(ParseError("Expected EndElement PutObjectResponse got Some(Ok(StartElement({http://s3.amazonaws.com/doc/2006-03-01}PutObjectResponse, {\"\": \"http://s3.amazonaws.com/doc/2006-03-01\", \"xml\": \"http://www.w3.org/XML/1998/namespace\", \"xmlns\": \"http://www.w3.org/2000/xmlns/\"})))"))
`

However the `put_object` call works:

```
awslocal s3 ls s3://my-tf-test-bucket
2019-10-13 13:04:23          5 aaaaaaa
```

Tested this same bit of code against my actual AWS account and it worked fine.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-127) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-05-31 21:13
Thanks for reporting @Steffey . Which version of Rusoto are you using? I was able to construct a simple example with rusoto version `0.43` that seems to be working:
```
$ AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=foo ./target/debug/my-test
Ok(PutObjectOutput { e_tag: Some("\"8b1a9953c4611296a827abf8c47804d7\""), expiration: None, request_charged: None, sse_customer_algorithm: None, sse_customer_key_md5: None, ssekms_encryption_context: None, ssekms_key_id: None, server_side_encryption: None, version_id: None })
```
One thing I noted: It seems that `sync()` has been removed from recent versions of the rusoto API - perhaps upgrading to the latest version helps?

If not, then can you please provide a small, isolated example that helps reproduce this issue? Thanks

**Comment by whummer** [comment] 2021-02-23 16:59
Closing as "cannot reproduce" - please report here if the problem persists. Thanks

**Closed by whummer** 2021-02-23 16:59 UTC
Labels: needs-triaging
