### ISSUE TITLE
Issue with using lambci/lambda as lambda executor

### ISSUE THREAD

**Issue by zodeus** [localstack/localstack#255] opened 2017-08-23 16:41 UTC
Hey there, just trying to get java lambdas to execute and I'm running into issues.
I've narrowed it down to the localstack containers /tmp/localstack/zipfile.x volume mount being empty in the lambda-docker container. I'm running localstack with privileged mode and mounted /var/run/docker to localstack, running docker images brings me back the correct list of images. Any suggestions? I think it has something to do with permissions, perhaps the lambda-docker container can't properly mount the other containers filesystem?

**Comment by bernljung** [comment] 2017-08-24 21:06
I ran in to this exact issue. I believe this issue only exists when one tries to run localstack the `docker-compose up` way. 

When we're passing in /var/run/docker to localstack we're effectively using our hosts docker inside the container, meaning that the volume mounts in any containers created inside localstack will be mounted from the host and not the container itself. 
A workaround is to create the directory /tmp/localstack on your host maching and mount it in the docker-compose.yml for localstack. You will then get the files inside the lambda container (and on your host...)

By then you're probably able to execute the lambda function, but you might have other issues depending on what you're trying to do. In my case I'd like to access the localstack S3 API and to do that I first have to figure out the internal IP address of the localstack container which can be accessed from within the lambda container. I can then set the s3 endpoint inside of the lambda function by doing: 

`const s3 = new aws.S3({
  apiVersion: '2007-03-01',
  endpoint: '172.21.0.2:4572'
});`

Problem is though that even though I'm able to access 172.21.0.2:4572 I do not have a host setup for  the full endpoint which is BUCKET.172.21.0.2:4572.

So here I'm getting this error:
`Error: getaddrinfo ENOTFOUND testbucket.172.21.0.2`

I tried to access /etc/hosts to add a row from within node.js but the user we get in the lambdaci/lambda:node6.10 image doesn't have the rights to edit that file. I also tried to setup 172.21.0.2:4572 as a [proxy](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html) but so far this is timing out every time.

While this might be entirely due to localstack running in docker, and lambda as a docker in docker container, installing the entire stack locally is not an option for me. Any suggestions are greatly appreciated.

**Comment by whummer** [comment] 2017-08-31 14:33
Hi @zodeus, can you please provide a few more details regarding your environment/configuration. Have you tried running LocalStack via `localstack start --docker`? Please post any relevant error messages and debug outputs. Thanks

**Comment by zodeus** [comment] 2017-08-31 22:53
Hey, guys, I'm not ignoring you just really busy. Once I get back to this I'll put together a proper report,

**Comment by bernljung** [comment] 2017-09-01 19:31
Steps to reproduce using nodejs:6.10 on Mac OS 10.12.6/Docker 17.06.1-ce-mac24

Put this in a file called index.js: 
```
  exports.handler = (event, context, callback) => {
      callback(null, 'hello');
  }; 
```
Zip it:
```
zip lambda.zip index.js
```
Upload to localstack:
```
aws --endpoint-url=http://$LOCALSTACK_HOSTNAME:4574 \
lambda create-function \
--function-name=lambda \
--runtime=nodejs6.10 \
--role=r1 \
--handler=index.handler \
--zip-file fileb://lambda.zip
```
Invoke:
```
aws lambda --endpoint-url=http://$LOCALSTACK_HOSTNAME:4574  \
invoke \
--function-name lambda \
result.log
```

Creating /tmp/localstack locally and changing the following in docker-compose.yml makes it work for me.

From:
```
- "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```
To:
```
- "/tmp/localstack:/tmp/localstack"
```

**Comment by zodeus** [comment] 2017-09-13 18:09
Ok, I have the latest localstack using docker. Here is a snippet from the compose file
```
  aws-localstack:
    image: localstack/localstack
    privileged: true
    ports:
      - "4566:8080"
      - "4567-4582:4567-4582"
    environment:
      - DEFAULT_REGION=us-west-2
      - USE_SSL=true
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - HOSTNAME=aws-localstack
      - HOSTNAME_EXTERNAL=aws-localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
```
Running the following series of commands 
```
#!/usr/bin/env bash
echo "CREATING"
aws --endpoint-url=https://localhost:4574 \
    lambda create-function \
    --function-name=lambda \
    --runtime=java8 \
    --role=r1 \
    --handler=com.exmaple::handler \
    --zip-file fileb://../target/lambda.zip \
    --no-verify-ssl
echo "INVOKING"
aws lambda --endpoint-url=https://localhost:4574  \
    invoke \
    --function-name lambda \
    --no-verify-ssl \
    result.log

cat result.log
```

 produces the following errors 
```
CREATING
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. 
An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script in Lambda archive.

INVOKING
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function does not exist: lambda
```

Looking inside of /tmp/localstack on the docker host 
```
-rw-r--r-- 1 root root  890 Sep 13 10:51 server.625d9c9b.test.pem.crt
-rw-r--r-- 1 root root  915 Sep 13 10:51 server.625d9c9b.test.pem.key
.....
.....
-rw-r--r-- 1 root root  305 Sep 13 10:51 sqs.be0d5bc2.conf
drwxr-xr-x 5 root root 4.0K Sep 13 10:51 zipfile.674390d2
drwxr-xr-x 5 root root 4.0K Sep 13 10:56 zipfile.f22bf830
````
Contents of one of the zip directories
```
✗ ll /tmp/localstack/zipfile.f22bf830/
total 78M
drwxr-xr-x 3 root root 4.0K Sep 13 11:07 com
drwxr-xr-x 3 root root 4.0K Sep 13 11:07 io
drwxr-xr-x 2 root root  16K Sep 13 11:07 lib
-rw-r--r-- 1 root root  671 Sep 13 11:07 log4j2.xml
-rw-r--r-- 1 root root  78M Sep 13 11:07 original_lambda_archive.zip
```

If I dig deeper, the class with the handler is inside the com directory.

Let me know if you want/need more info

**Comment by njcongtou** [comment] 2017-09-20 17:42
@bernljung have you resolved your issue ? I am having the same issue now.

**Comment by bernljung** [comment] 2017-09-21 09:14
@njcongtou Yes, the change in tmp dir worked for me. In your case the error message below indicate that there is something wrong with the lambda function itself, not the environment. 

`An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script in Lambda archive.`

I'm don't do Java, but I might be able to tell what's wrong if you show your code. (It's not as simple as a typo in the handler flag for create-function? com.exmaple::handler -> com.example::handler

**Comment by njcongtou** [comment] 2017-09-21 16:23
[hello.zip](https://github.com/localstack/localstack/files/1322000/hello.zip)

This is my hello world nodejs lambda. 

    environment:
      - SERVICES=${SERVICES-lambda, kinesis, s3}
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOSTNAME=${LOCALSTACK_HOSTNAME- }

**Comment by whummer** [comment] 2017-09-30 18:55
@zodeus @bernljung @njcongtou Have you been able to work around the problem with mounting the temporary directory (also mentioned in the [README](https://github.com/localstack/localstack#troubleshooting)) - Can we close this issue now?

**Comment by bernljung** [comment] 2017-10-01 08:10
@whummer Yes, this works as expected in my setup!

**Comment by zodeus** [comment] 2017-10-01 08:24
@whummer, yes that fixes the mounting issue, However I think there is a issues in how you expect the artifact to be package up. Right now you need to put a fat jar in a zip, which doesn't seem very intuitive. I had to read through the code to figure it out. Either just a fat jar or a zip (in the expect AWS format), which is not a fat jar. To use this now I need to produce 2 different artifacts one for docker and one for AWS. Not the end of the world but could be better.

**Comment by Surfoo** [comment] 2017-10-04 16:57
Hello,

I have the same issue with localstack 0.8.1 and this simple example of code : 

> exports.handler = (event, context, callback) => {
>    callback(null, 'hello');
> };

Here the init code : 
> zip indexer.zip /go/indexer/index.js
> aws --endpoint-url=http://fake-aws:4574 lambda create-function --function-name lambda --runtime nodejs6.10 --role r1 --handler index.handler --zip-file fileb://indexer.zip

And I get the same error : 

> An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script in Lambda archive.

I don't use macOS but Linux, and my volume isn't mounted in /tmp 

Do you need something more to help you?

**Comment by whummer** [comment] 2017-10-08 04:10
Good point @zodeus . Created a follow-up ticket here: https://github.com/localstack/localstack/issues/385 Thanks

**Closed by whummer** 2017-10-08 04:10 UTC
Labels: installation, needs-triaging, priority-high
