### ISSUE TITLE
"Unknown port mapping for service: s3"

### ISSUE THREAD

**Issue by Frantch** [localstack/localstack#2082] opened 2020-02-24 15:28 UTC
Hello,

I'm trying to use localstack using the maven dependency. I have followed the README but upon executing `TestUtils.getClientS3();` it says "Unknown port mapping for service: s3"

Looking into the source it tried to read a python file at
`/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_client/config.py`

I don't have that path at all. When does this file gets created?

Thanks!

**Comment by spanierm** [comment] 2020-02-28 10:19
The problem is the Python version. In the actual Docker base image, Python 3.8 is in use and therefore, the path is `/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_client/config.py`. Unfortunately, I do not see where this base image get built. Once I find it, I will provide a pull request.

**Comment by spanierm** [comment] 2020-02-28 10:24
Thanks to another issue, #1228, I found the Dockerfile. Indeed, Python 3.8.1 gets installed in https://github.com/localstack/localstack/blob/master/bin/Dockerfile.base#L8 and thus the path is wrong.

**Comment by spanierm** [comment] 2020-02-28 10:28
It has already been fixed on February 24: https://github.com/spanierm/localstack-java-utils/blob/master/src/main/java/cloud/localstack/Localstack.java#L27. So waiting for a new release...

**Comment by spanierm** [comment] 2020-02-28 11:46
As a workaround, you can locally modify the image by adding a symlink using `RUN ln -s /opt/code/localstack/.venv/lib/python3.8 /opt/code/localstack/.venv/lib/python3.7` at the end of the `Dockerfile` and build the image with `docker build . --tag localstack/localstack`.

**Comment by whummer** [comment] 2020-03-09 16:07
Thanks for reporting @Frantch @spanierm . A new version `0.2.1` of the Java libs has been released to Maven Central in the meantime - can you please give it another try? Please report here if the problem persists. Thanks

**Closed by whummer** 2020-03-09 16:07 UTC

**Comment by mickog** [comment] 2020-04-29 14:19
@whummer It seems the issue still exists in 0.2.1 for me. I have reported the issue but just updating here.

**Comment by gaetan224** [comment] 2021-06-08 15:20
same problem, localstack-utils:0.2.11, with the latest version of localstack

**Comment by jasonab** [comment] 2021-06-09 23:31
I see it too in the latest image (0.12.12)

**Comment by cabral-ricardo** [comment] 2021-06-14 20:40
same problem,
java.lang.IllegalArgumentException: Unknown port mapping for service: s3
	at cloud.localstack.Localstack.getServicePort(Localstack.java:232)
	at cloud.localstack.Localstack.endpointForService(Localstack.java:223)
	at cloud.localstack.Localstack.getEndpointS3(Localstack.java:122)
	at cloud.localstack.awssdkv1.TestUtils.getEndpointConfigurationS3(TestUtils.java:232)
	at cloud.localstack.awssdkv1.TestUtils.getClientS3(TestUtils.java:133)

**Comment by cabral-ricardo** [comment] 2021-06-15 18:29
great. I changed to findify.s3mock while I wait this deploy
https://stackoverflow.com/questions/6615988/how-to-mock-amazon-s3-in-an-integration-test
