### ISSUE TITLE
bug: SerializationException on Kinesis GetShardIterator and RegisterStreamConsumer actions

### ISSUE THREAD

**Issue by avandesa-fw** [localstack/localstack#6990] opened 2022-10-07 20:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to execute the `GetShardIterator` actions against a local Kinesis instance running in localstack, a `SerializationException` is thrown and an HTTP 400 response is returned saying the request body could not be decoded as JSON. Similarly, when trying to execute `SubscribeToShard`, the same exception is thrown, but a 500 error is returned.

This occurs regardless of which Kinesis backend provider is used (kinesis-mock or kinesalite) or client is used to perform the action (aws cli, awslocal, [rusoto](https://crates.io/crates/rusoto_kinesis), or [aws_sdk_kinesis](https://crates.io/crates/aws-sdk-kinesis)).

### Expected Behavior

The Kinesis backend should receive and perform the action, and return relevant valid data.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
awslocal kinesis create-stream --stream-name samplestream --shard-count 1
awslocal kinesis get-shard-iterator --stream-name samplestream --shard-id shardId-000000000000 --shard-iterator-type TRIMHORIZON
```
...returns the following:
```
An error occurred (SerializationException) when calling the GetShardIterator operation: Invalid message body: Could not decode JSON: {
  "StreamName" : "samplestream",
  "ShardId" : "shardId-000000000000",
  "ShardIteratorType" : "TRIMHORIZON"
}
```
...and prints in the localstack logs:
```
2022-10-07T20:14:28.051  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS kinesis.GetShardIterator => 400 (SerializationException)
```

Running the following Rust code using rusoto, tokio, and color-eyre (for neatly printing the error):
```rust
use color_eyre::eyre::{Result, WrapErr};
use rusoto_core::Region;
use rusoto_kinesis::{Kinesis, KinesisClient, StartingPosition, SubscribeToShardInput};

#[tokio::main]
async fn main() -> Result<()> {
    color_eyre::install()?;

    println!("Initializing client");
    let client = KinesisClient::new(Region::Custom {
        name: "localstack".to_string(),
        endpoint: "http://localhost:4566".to_string(),
    });
    let subscription = client
        .subscribe_to_shard(SubscribeToShardInput {
            consumer_arn: "arn:aws:kinesis:us-east-1:000000000000:stream/samplestream/consumer/sampleconsumer:1665174654".to_string(),
            shard_id: "shardId-000000000000".to_string(),
            starting_position: StartingPosition {
                type_: "TRIM_HORIZON".to_string(),
                sequence_number: None,
                timestamp: None,
            },
        })
        .await
        .wrap_err("Failed to subscribe to shard")?;
    dbg!(&subscription);

    Ok(())
}
```
...prints the following error:
```
Error: 
   0: Failed to subscribe to shard
   1: Request ID: Some("MCEG80Y9W4OFYQFBESL7VUZ67414J3GR6RQPLZYRHUR4YBOWQ2GW") Body: {"__type": "InternalError", "message": "exception while calling kinesis.SubscribeToShard: An error occurred (SerializationException) when calling the ListStreamConsumers operation: Invalid message body: Could not decode JSON: {\n  \"StreamARN\" : \"arn:aws:kinesis:localstack:000000000000:stream/samplestream\"\n}"}

Location:
   src/main.rs:25
```
...and prints the following in the localstack logs:
```
2022-10-07T20:36:21.234 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: An error occurred (SerializationException) when calling the ListStreamConsumers operation: Invalid message body: Could not decode JSON: {
"StreamARN" : "arn:aws:kinesis:localstack:000000000000:stream/samplestream"
}
2022-10-07T20:36:21.234  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS kinesis.SubscribeToShard => 500 (InternalError)
```

### Environment

```markdown
- OS: macOS Monterey 12.4
- LocalStack: latest
```

### Anything else?

Local stack startup logs, including the kinesis backend startup, just in case

```
 💻 LocalStack CLI 1.1.0

[16:03:32] starting LocalStack in Docker mode 🐳                                                                                                                             localstack.py:139
─────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ────────────────────────────────────────────────────────────────────────
Waiting for all LocalStack services to be ready
2022-10-07 20:03:33,386 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-10-07 20:03:33,387 INFO supervisord started with pid 16
2022-10-07 20:03:34,413 INFO spawned: 'infra' with pid 21
2022-10-07 20:03:35,603 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 1.2.0.dev
LocalStack Docker container id: 7bd9c8bd692a
LocalStack build date: 2022-10-07
LocalStack build git hash: 85d1973c

Ready.
2022-10-07T20:03:35.602  WARN --- [  Thread-110] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-10-07T20:03:35.602  WARN --- [  Thread-110] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-10-07T20:03:35.606  INFO --- [  Thread-110] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-10-07T20:03:35.606  INFO --- [  Thread-110] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)

2022-10-07T20:04:23.035  INFO --- [   asgi_gw_0] localstack.services.infra  : Starting mock Kinesis service on http port 4566 ...
2022-10-07T20:04:24.764  INFO --- [  Thread-121] l.s.k.kinesis_mock_server  : [io-compute-blocker-5] INFO  2022-10-07 20:04:24,761 k.m.KinesisMockService contextId=3d95ea08-467b-11ed-b3e4-3b840d53dd8a, cacheConfig={"awsAccountId":"000000000000","awsRegion":"us-east-1","createStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"initializeStreams":null,"mergeShardsDuration":{"length":500,"unit":"MILLISECONDS"},"persistConfig":{"fileName":"kinesis-data.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"/var/lib/localstack/tmp/state/kinesis","shouldPersist":true},"registerStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":500,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":500,"unit":"MILLISECONDS"}} - Logging Cache Config
2022-10-07T20:04:25.940  INFO --- [  Thread-121] l.s.k.kinesis_mock_server  : [io-compute-blocker-1] INFO  2022-10-07 20:04:25,939 k.m.KinesisMockService  - Starting Kinesis TLS Mock Service on port 4567
2022-10-07T20:04:25.940  INFO --- [  Thread-121] l.s.k.kinesis_mock_server  : [io-compute-blocker-1] INFO  2022-10-07 20:04:25,940 k.m.KinesisMockService  - Starting Kinesis Plain Mock Service on port 54839
2022-10-07T20:04:25.950  INFO --- [  Thread-121] l.s.k.kinesis_mock_server  : [io-compute-3] INFO  2022-10-07 20:04:25,949 k.m.KinesisMockService contextId=3e5ae7b9-467b-11ed-b3e4-3b840d53dd8a - Starting persist data loop
2022-10-07T20:04:27.027  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 4009.61ms
```

**Comment by ackdav** [comment] 2022-10-13 15:18
Hello @avandesa-fw - thank you for raising this issue. I'm having a bit of trouble consistently reproducing this.
I used the snipped you provided:
```
awslocal kinesis create-stream --stream-name samplestream --shard-count 1  
awslocal kinesis get-shard-iterator --stream-name samplestream --shard-id shardId-000000000000 --shard-iterator-type TRIMHORIZON
```

I can reproduce your issue using `TRIMHORIZON` - this seems to be a typo. With `TRIM_HORIZON` ([aws docs](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html#API_GetShardIterator_RequestSyntax)) everything works fine on my end. Can you please double-check this?
As far as I see it, the issue is that localstack should not allow the request to go through with the typo...

**Comment by avandesa-fw** [comment] 2022-10-14 14:34
Hi @ackdav, I can confirm that the TRIM_HORIZON typo seems to be the issue; using `TRIM_HORIZON` works. The error is quite confusing as the request is valid JSON, just with an invalid argument. Thanks for figuring that out!

**Comment by ackdav** [comment] 2022-10-14 14:57
Thanks for quickly confirming this @avandesa-fw. I'll close the issue for now, since it's not really a bug as described, but rather a usage issue. I'll make a note to add proper input sanitization soon to have a more usable error message. thanks again 👍

**Closed by ackdav** 2022-10-14 14:57 UTC
Labels: type: bug, status: triage needed, aws:kinesis
