### ISSUE TITLE
bug: Importing REST API from OpenAPI spec resulting in Invalid Rest API Id specified when hitting the endpoint

### ISSUE THREAD

**Issue by danw-mpl** [localstack/localstack#4619] opened 2021-09-20 16:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using the `awslocal` CLI to run `import-rest-api` with a provided OpenAPI spec.

The import and subsequent `create-deployment` seems to work without error.  However, when I hit the API, LocalStack's logs return:

```
localstack         | 2021-09-20T16:27:40:DEBUG:localstack_ext.services.apigateway.authorizers: Unable to find API entity for ID "8ad3loe9py" in region "None"
localstack         | 2021-09-20T16:27:40:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f7f255e1050>(None) failed: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified Traceback (most recent call last):
localstack         |   File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
localstack         |     result = self.func(self.params, **kwargs)
localstack         |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
localstack         |     return fn(*args, **kwargs)
localstack         |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 521, in handler
localstack         |     server_address=parsed_url.netloc,
localstack         |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 109, in modify_and_forward
localstack         |     method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
localstack         |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 306, in modify_and_forward
localstack         |     method=method, path=path, data=data, headers=headers
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/edge.py", line 195, in forward_request
localstack         |     return forward_request_orig(method,path,data,headers,*args,**kwargs)
localstack         |   File "/opt/code/localstack/localstack/services/edge.py", line 167, in forward_request
localstack         |     return do_forward_request(api, method, path, data, headers, port=port)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/edge.py", line 189, in do_forward_request
localstack         |     return do_forward_request_orig(api,method,path,data,headers,*args,**kwargs)
localstack         |   File "/opt/code/localstack/localstack/services/edge.py", line 195, in do_forward_request
localstack         |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack         |   File "/opt/code/localstack/localstack/services/edge.py", line 227, in do_forward_request_inmem
localstack         |     server_address=server_address,
localstack         |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 306, in modify_and_forward
localstack         |     method=method, path=path, data=data, headers=headers
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/apigateway_extended.py", line 102, in forward_request
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/invocations.py", line 115, in invoke_api
localstack         |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 305, in invoke_rest_api
localstack         |     path_map = helpers.get_rest_api_paths(rest_api_id=api_id)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/apigateway_extended.py", line 192, in get_rest_api_paths
localstack         |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 919, in get_rest_api_paths
localstack         |     resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
localstack         |     return self._make_api_call(operation_name, kwargs)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
localstack         |     raise error_class(parsed_response, operation_name)
localstack         | botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified
localstack         | 
localstack         | 2021-09-20T16:27:40:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://8ad3loe9py.execute-api.localhost.localstack.cloud:4566/Dev/: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified Traceback (most recent call last):
localstack         |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 130, in index
localstack         |     result = await run_sync(handler, request, data)
localstack         |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
localstack         |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack         |   File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
localstack         |     result = self.func(self.params, **kwargs)
localstack         |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
localstack         |     return fn(*args, **kwargs)
localstack         |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 521, in handler
localstack         |     server_address=parsed_url.netloc,
localstack         |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 109, in modify_and_forward
localstack         |     method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
localstack         |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 306, in modify_and_forward
localstack         |     method=method, path=path, data=data, headers=headers
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/edge.py", line 195, in forward_request
localstack         |     return forward_request_orig(method,path,data,headers,*args,**kwargs)
localstack         |   File "/opt/code/localstack/localstack/services/edge.py", line 167, in forward_request
localstack         |     return do_forward_request(api, method, path, data, headers, port=port)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/edge.py", line 189, in do_forward_request
localstack         |     return do_forward_request_orig(api,method,path,data,headers,*args,**kwargs)
localstack         |   File "/opt/code/localstack/localstack/services/edge.py", line 195, in do_forward_request
localstack         |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack         |   File "/opt/code/localstack/localstack/services/edge.py", line 227, in do_forward_request_inmem
localstack         |     server_address=server_address,
localstack         |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 306, in modify_and_forward
localstack         |     method=method, path=path, data=data, headers=headers
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/apigateway_extended.py", line 102, in forward_request
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/invocations.py", line 115, in invoke_api
localstack         |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 305, in invoke_rest_api
localstack         |     path_map = helpers.get_rest_api_paths(rest_api_id=api_id)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/apigateway_extended.py", line 192, in get_rest_api_paths
localstack         |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 919, in get_rest_api_paths
localstack         |     resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
localstack         |     return self._make_api_call(operation_name, kwargs)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
localstack         |     raise error_class(parsed_response, operation_name)
localstack         | botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified
localstack         | 
localstack         | 2021-09-20T16:27:40:ERROR:asyncio: Exception in callback _chain_future.<locals>._set_state(<Future finis...d specified')>, <Future at 0x...oundException>) at /usr/lib/python3.7/asyncio/futures.py:345
localstack         | handle: <Handle _chain_future.<locals>._set_state(<Future finis...d specified')>, <Future at 0x...oundException>) at /usr/lib/python3.7/asyncio/futures.py:345>
localstack         | Traceback (most recent call last):
localstack         |   File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
localstack         |     self._context.run(self._callback, *self._args)
localstack         |   File "/usr/lib/python3.7/asyncio/futures.py", line 347, in _set_state
localstack         |     _copy_future_state(other, future)
localstack         |   File "/usr/lib/python3.7/asyncio/futures.py", line 317, in _copy_future_state
localstack         |     assert not dest.done()
localstack         | AssertionError
```

And the curl command returns:

```shell
curl -v http://8ad3loe9py.execute-api.localhost.localstack.cloud:4566/Dev/*   Trying 127.0.0.1:4566...
* TCP_NODELAY set
* Connected to 8ad3loe9py.execute-api.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
> GET /Dev/ HTTP/1.1
> Host: 8ad3loe9py.execute-api.localhost.localstack.cloud:4566
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 
< Content-Type: text/html; charset=utf-8
< Content-Length: 2
< date: Mon, 20 Sep 2021 16:28:35 GMT
< server: hypercorn-h11
< 
* Connection #0 to host 8ad3loe9py.execute-api.localhost.localstack.cloud left intact
```

And `awslocal apigateway get-resources --rest-api-id *********` returns:

```json
{
    "items": [
        {
            "id": "fiojri5hdt",
            "path": "/",
            "resourceMethods": {
                "GET": {
                    "httpMethod": "GET",
                    "apiKeyRequired": false,
                    "methodIntegration": {
                        "type": "aws_proxy",
                        "httpMethod": "GET",
                        "uri": {
                            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:MyFunction/invocations"
                        },
                        "requestTemplates": {},
                        "passthroughBehavior": "when_no_match",
                        "cacheNamespace": "d76a5184",
                        "cacheKeyParameters": [],
                        "integrationResponses": {
                            "200": {
                                "statusCode": "200",
                                "responseTemplates": {}
                            }
                        }
                    }
                }
            }
        }
    ]
}
```

### Expected Behavior

Hitting / should run the Lambda function.

### How are you starting LocalStack?

With a docker-compose file

#### docker-compose.yml

```yaml
version: "3.8"

services:
  localstack:
    container_name: "localstack"
    build:
      dockerfile: dev-env/Dockerfile.localstack # Copies our CA cert
      context: .
    networks:
      - default
      - localstack
    ports:
      - "4566:4566" # Default LocalStack port
      - "4513:4513" # ECR Docker registry
    environment:
      - DEBUG=1
      - LOCALSTACK_API_KEY=************
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 # Required to prevent 403 from Commandeer
      - DISABLE_EVENTS=1 # Disable Localstack telemetry
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt # See Dockerfile.localstack
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp}/localstack
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### dev-env/Dockerfile.localstack

```Dockerfile
FROM localstack/localstack:latest@sha256:c7ac48be75cd010002cc743ab62bc8cd5a570c04ccbaa8ba6f44b35d6f6fcda4

COPY dev-env/********.crt /usr/local/share/ca-certificates/********.crt

RUN chmod 644 /usr/local/share/ca-certificates/********.crt && update-ca-certificates
```

#### repro/deploy.sh

```bash
export AWS_DEFAULT_REGION=eu-west-1

zip lambda.zip lambda.js

awslocal lambda create-function \
    --region eu-west-1 \
    --function-name MyFunction \
    --runtime nodejs8.10 \
    --handler lambda.apiHandler \
    --memory-size 128 \
    --zip-file fileb://lambda.zip \
    --role arn:aws:iam::123456:role/irrelevant

OUTPUT="$(awslocal apigateway import-rest-api \
    --parameters basepath=ignore \
    --body "file://openapi.json")"

API_ID="$(jq -r '.id' <<< "$OUTPUT")"

awslocal apigateway create-deployment \
    --rest-api-id "$API_ID" \
    --stage-name Dev \
    --stage-description 'MyDevStage' \
    --description 'First deploy'

echo "Endpoint: http://$API_ID.execute-api.localhost.localstack.cloud:4566/Dev/"
```

#### repro/lambda.js

```javascript
'use strict'

const apiHandler = (payload, context, callback) => {
    console.log(`Function apiHandler called with payload ${JSON.stringify(payload)}`);
    callback(null, {
        statusCode: 201,
        body: JSON.stringify({
            message: 'Hello World'
        }),
        headers: {
            'X-Custom-Header': 'ASDF'
        }
    }); 
}
    
module.exports = {
    apiHandler,
}
```

#### openapi.json

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "tasks-api",
    "version": "v1.0"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "List tasks",
        "description": "Returns list of tasks",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Task"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {}
          }
        },
        "x-amazon-apigateway-integration": {
          "uri": {
            "Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:MyFunction/invocations"
          },
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match",
          "httpMethod": "POST",
          "contentHandling": "CONVERT_TO_TEXT",
          "type": "aws_proxy"
        }
      }
    }
  }
}
```

### Environment

```markdown
- OS: WSL2 (Ubuntu 20.04) on Win 10
- LocalStack:


localstack         | LocalStack version: 0.12.17.5
localstack         | LocalStack Docker container id: d8eb0109b0af
localstack         | LocalStack build date: 2021-09-15
localstack         | LocalStack build git hash: e3877888
```
```


### Anything else?

_No response_

**Comment by whummer** [comment] 2021-12-28 20:02
Hi @danw-mpl , thanks for reporting this issue, and apologies for the delay. Looks like the Open API spec you've posted is not fully compliant with the format AWS requires (due to the `Fn::Sub` function contained in the template). 

When attempting to run the `import-rest-api` command against real AWS, this is what we're seeing:
```
An error occurred (BadRequestException) when calling the ImportRestApi operation: Unable to parse API definition because of a malformed integration at path /.
```
(After replacing `"Fn::Sub": "..."` with a raw string, the deployment works).

Regarding the error in the log output (`Unable to find API entity for ID ...`), we have recently fixed a couple of enhancements for API Gateway authorizers (for both, API GW v1 and v2), and we believe that this should (hopefully) be resolved in the meantime. Can you please pull the `latest` Docker image and give it another try? Hope that helps - please let us know if the problem persists, we'll be happy to dig more into this issue if it is still reproducible.. Thanks!

**Closed by whummer** 2021-12-28 20:02 UTC
Labels: bug, needs-triaging, aws:apigateway
