### ISSUE TITLE
Cannot enabled versioning on newly created S3 Bucket with Java SDK

### ISSUE THREAD

**Issue by MarkBramnik** [localstack/localstack#799] opened 2018-06-06 06:55 UTC
Applies to any version of Java SDK.

Environment: docker running the image: localstack/localstack on windows 10.

I've tried to create a bucket and enable versioning on it via Java SDK.

The used Code is:

      AmazonS3 s3Connector = new AmazonS3Client(<credentials>);
      s3Connector.setEndpoint(<endpoint>);
      s3Connector.setClientOptions(
                S3ClientOptions.builder().setPathStyleAccess(true).disableChunkedEncoding().build());

      s3Connector.createBucket("sample-bucket");
 
      BucketVersioningConfiguration configuration =
                new BucketVersioningConfiguration().withStatus(BucketVersioningConfiguration.ENABLED);

      SetBucketVersioningConfigurationRequest setBucketVersioningConfigurationRequest =
                new SetBucketVersioningConfigurationRequest(bucketName,configuration);

      s3Connector.setBucketVersioningConfiguration(setBucketVersioningConfigurationRequest);

The last line fails after retries, although the created bucket seems to be versioned after it fails.
The docker log shows the following exception in localstack: 

` 2018-06-05T20:27:37:ERROR:localstack.services.generic_proxy: Error forwarding request: string index out of range Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 194, in forward
    path=path, data=data, headers=forward_headers, response=response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 435, in return_response
    if parsed.query != 'notification':
IndexError: string index out of range`

I've investigated and run the same commands through aws cli:

`python awslocal s3api create-bucket --bucket sample-bucket`
`python awslocal s3api put-bucket-versioning --bucket sample-bucket --versioning-configuration
 Status=Enabled`

It worked correctly

So I've concluded  that there is a difference between the HTTP requests produced by aws cli and Java AWS client. 

I've run it via proxy (I've used burpsuite but I believe any proxy can do the job here) that is located between java application and localstack (so that it will intercept all the requests from java to localstack and then forward them to localstack) and observed that the difference that causes the exception in AWS is the construction of the actual path:

In Aws CLI the RAW HTTP Request is produced to the path:
`PUT /sample-bucket?versioning HTTP/1.1` 

In Java SDK the RAW HTTP request is produced to the path:
`PUT /sample-bucket/?versioning HTTP/1.1`

Note the _Trailing Slash_ after the bucket name in Java SDK Version
When I modify the request "manually" inside the proxy and remove the trailing slash it works.
So it looks like Amazon AWS servers can deal with this trailing slash, while localstack cannot process it correctly. 

So I've decided to open a bug about it.

A workaround that I've found in Java is to "wrap" the AmazonS3 client, override the "createRequest" method and remove the trailing slash in the path programmatically, but its not a good solution, and it could be great to fix it in localstack itself

In case other people got stuck with this, here is my workaround:

     import com.amazonaws.services.s3.AmazonS3Client;
     public class CustomS3Connector extends AmazonS3Client {
         protected <X extends AmazonWebServiceRequest> Request<X> createRequest(String bucketName, String key, X originalRequest, HttpMethodName httpMethod) {
             Request<X> request = super.createRequest(bucketName, key, originalRequest, httpMethod, endpoint);
             if(originalRequest instanceof SetBucketVersioningConfigurationRequest) {
                  String originalResourcePath = request.getResourcePath();
                  if(originalResourcePath.endsWith("/")) {
                     String modifiedResourcePath = originalResourcePath.substring(0, originalResourcePath.length() - 1);
                     request.setResourcePath(modifiedResourcePath);`
                 }
            }
            return request;
        }
    }

**Comment by whummer** [comment] 2018-09-03 14:41
Thanks for reporting @MarkBramnik. I was unable to reproduce this issue - looks like this issue has been fixed in the meantime.

Closing this issue now. Can you please try again with the latest version of the `localstack/localstack` image, and reopen this issue if the problem persists. Thanks

**Closed by whummer** 2018-09-03 14:41 UTC
