### ISSUE TITLE
error on ecr awslocal create repository using EDGE_PORT 

### ISSUE THREAD

**Issue by joseflexadaitan** [localstack/localstack#2324] opened 2020-04-20 16:53 UTC
# Type of request: This is a bug

[x] bug report
[ ] feature request

# Detailed description
Created a docker composer (here is the start of the file)
```
localstack:
    image: localstack/localstack:0.11.0
    container_name: localstack
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=cloudwatch,dynamodb,ecs,ecr,iam,s3,sqs,sns,sts
      - USE_SSL=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=10.0.0.20
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=${DEBUG}
    ports:
      - "4566:4566"
      - "4567:4567"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"

``` 
Run docker composer and after it was ready i tried the following:

And I saw the following stack trace on localstack logs:
```
localstack    | 2020-04-20T16:51:32:ERROR:localstack.services.generic_proxy: Error forwarding request: MyHTTPConnectionPool(host='e1adfc90e1b6', port=4610): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ba71c8ca0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
localstack    |     conn = connection.create_connection(
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack    |     raise err
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack    |     sock.connect(sa)
localstack    | ConnectionRefusedError: [Errno 111] Connection refused
localstack    | 
localstack    | During handling of the above exception, another exception occurred:
localstack    | 
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
localstack    |     httplib_response = self._make_request(
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
localstack    |     conn.request(method, url, **httplib_request_kw)
localstack    |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack    |     self._send_request(method, url, body, headers, encode_chunked)
localstack    |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack    |     self.endheaders(body, encode_chunked=encode_chunked)
localstack    |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack    |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack    |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack    |     self.send(msg)
localstack    |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack    |     self.connect()
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
localstack    |     conn = self._new_conn()
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
localstack    |     raise NewConnectionError(
localstack    | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6ba71c8ca0>: Failed to establish a new connection: [Errno 111] Connection refused
localstack    | 
localstack    | During handling of the above exception, another exception occurred:
localstack    | 
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack    |     resp = conn.urlopen(
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
localstack    |     retries = retries.increment(
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
localstack    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack    | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='e1adfc90e1b6', port=4610): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ba71c8ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack    | 
localstack    | During handling of the above exception, another exception occurred:
localstack    | 
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 247, in forward
localstack    |     listener_result = listener.forward_request(method=method,
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 59, in forward_request
localstack    |     response = function(url, data=data, headers=headers, verify=False)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 1065, in _wrapper
localstack    |     return method(*args, **kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack    |     return request('post', url, data=data, json=json, **kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack    |     return session.request(method=method, url=url, **kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack    |     resp = self.send(prep, **send_kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack    |     r = adapter.send(request, **kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack    |     raise ConnectionError(e, request=request)
localstack    | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='e1adfc90e1b6', port=4610): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ba71c8ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```
## Expected behavior

Create an ECR repository.

## Actual behavior

Failed creating an ECR repository.

# Steps to reproduce

## Command used to start LocalStack

`DEBUG=1 LOCALSTACK_API_KEY=GuessMe docker-compose up 
`
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ awslocal ecr create-repository --endpoint-url=http://10.0.0.20:4566 --repository-name mock-repo
An error occurred (502) when calling the CreateRepository operation (reached max retries: 4): Bad Gateway
```

**Comment by jacobisaliveandwell** [comment] 2020-05-02 21:14
In general, can we get some docks on how the Edge proxy is supposed to be used? It would be *amazing* if we could communicate with localstack without changing anything but the proxy settings in `~/.aws/config`.

**Comment by whummer** [comment] 2020-05-03 21:03
Thanks for reporting @joseflexadaitan . I just gave it a quick try with a ~1GB image on my machine, and it seems to upload fine on my machine (Mac OS, 3GB RAM allocated to Docker).

One thing that sticks out is that the code apparently cannot connect to port `4610` on host `e1adfc90e1b6`. Perhaps you could try adding the environment variable `HOSTNAME=localhost` to your docker-compose config? 
```
MyHTTPConnectionPool(host='e1adfc90e1b6', port=4610)
```

**Comment by alejandroandreu** [comment] 2020-05-10 13:50
Is the issue being worked on? Otherwise I can join the aforementioned Slack and provide input. In my case, I'm pointing Terraform to create an ECR repository with no success:

```
Error: error creating ECR repository: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: 095fb96b-f4d8-4bf8-a274-855a1394278a

  on ecr.tf line 1, in resource "aws_ecr_repository" "downloader":
   1: resource "aws_ecr_repository" "downloader" {
```

The rest of my resources can be created just fine, it's only ECR that is failing.

**Comment by alejandroandreu** [comment] 2020-06-05 07:07
As a workaround, using `awslocal` inside the LocalStack container works just fine. It's the proxying between the edge service and the ECR endpoint that is broken.

**Comment by whummer** [comment] 2020-06-22 22:21
Thanks for the update @alejandroandreu . Can you please help us debug this issue and give it another try with the `latest` version of the Docker image? Also, looking at the `UnrecognizedClientException` error, it seems that Terraform is trying to connect to the real AWS environment - please make sure that the `ecr` endpoint is configured to point to the `localhost` endpoint. We'll be happy to look into this issue if you could help us create a small, reproducible example. Thanks!

**Comment by whummer** [comment] 2020-06-27 21:34
Hi @alejandroandreu @joseflexadaitan - any updates on this issue? Have you been able to configure the `ecr` to point to the `localhost` endpoint? Would be great if you could give us a short update, or help us reproduce this issue using a small, isolated example. Thanks!

**Comment by alejandroandreu** [comment] 2020-06-30 06:46
Hi, I've been able to test this today with no success. Repository creation from Terraform hangs forever:
```
aws_ecr_repository.foo: Still creating... [10s elapsed]
aws_ecr_repository.foo: Still creating... [20s elapsed]
aws_ecr_repository.foo: Still creating... [30s elapsed]
aws_ecr_repository.foo: Still creating... [40s elapsed]
aws_ecr_repository.foo: Still creating... [50s elapsed]
aws_ecr_repository.foo: Still creating... [1m0s elapsed]
aws_ecr_repository.foo: Still creating... [1m10s elapsed]
aws_ecr_repository.foo: Still creating... [1m20s elapsed]
aws_ecr_repository.foo: Still creating... [1m30s elapsed]
aws_ecr_repository.foo: Still creating... [1m40s elapsed]
aws_ecr_repository.foo: Still creating... [1m50s elapsed]
aws_ecr_repository.foo: Still creating... [2m0s elapsed]
aws_ecr_repository.foo: Still creating... [2m10s elapsed]
aws_ecr_repository.foo: Still creating... [2m20s elapsed]
aws_ecr_repository.foo: Still creating... [2m30s elapsed]
aws_ecr_repository.foo: Still creating... [2m40s elapsed]
aws_ecr_repository.foo: Still creating... [2m50s elapsed]
aws_ecr_repository.foo: Still creating... [3m0s elapsed]
aws_ecr_repository.foo: Still creating... [3m10s elapsed]
aws_ecr_repository.foo: Still creating... [3m20s elapsed]
aws_ecr_repository.foo: Still creating... [3m30s elapsed]
aws_ecr_repository.foo: Still creating... [3m40s elapsed]
aws_ecr_repository.foo: Still creating... [3m50s elapsed]
aws_ecr_repository.foo: Still creating... [4m0s elapsed]
aws_ecr_repository.foo: Still creating... [4m10s elapsed]
```

And it doesn't seem to work using `awslocal` either, at least from my side:
```
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4610/".
```

**Comment by whummer** [comment] 2020-07-19 19:51
Thanks for the update @alejandroandreu - looks like Terraform is now connecting to the right endpoint, but apparently the API is still returning some response that makes TF hang forever. I just did a quick test (with some examples from [here](https://www.terraform.io/docs/providers/aws/r/ecr_repository.html)) and it seems to be working now with the `latest` version of the Docker image..?

Please note that Terraform is very strict when it comes to schema validation - it might be simply a matter of a missing parameter, or an incorrect data type in the response. Could you please help us and provide a small, isolated example so we can easily reproduce this issue? Many thanks for your help!

**Comment by whummer** [comment] 2020-08-23 19:01
Unable to reproduce this issue at this point, looks like it is fixed in the latest version. @alejandroandreu If the problem persists, can you please provide some more details on how to reproduce it - we'll be happy to look into it . Thanks!

**Closed by whummer** 2020-08-23 19:01 UTC
Labels: PRO, bug, enhancement, needs-triaging, priority-high, should-be-fixed
