### ISSUE TITLE
enhancement request: add support for alb listener rule condition type http_method

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#9432] opened 2023-10-22 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

To use the ALB as a replacement for API – GW this match condition is essential.

**Comment by robertlcx** [comment] 2023-12-21 16:17
Tested this using https://github.com/paulrobello/alb_routing_bug and I found this to not be reproducible. Re-ran:

```bash
make it-again
make exec-api-all
```

Many times and it has always given me the following output:

```bash
root@bc663c3d8345(alb) /workspace (main)
$ make exec-api-all
Expected: "HEALTHY"          Got: HEALTHY
Expected: "Route1"          Got: "Route1"
Expected: "Route2"          Got: "Route2"
Expected: "404 not found"   Got: "404 not found"
```

I wonder if https://github.com/localstack/localstack-ext/pull/2307 or https://github.com/localstack/localstack-ext/pull/2308 were the reason for this working now. @cabeaulac, what do you make of this?

**Comment by paulrobello** [comment] 2023-12-21 17:45
This enhancement request was not part of the bug reproducer, the bug that the reproducer had been targeting has already been fixed.
you can see on this line [https://github.com/paulrobello/alb_routing_bug/blob/main/iac/aws/alb/route/main.tf#L15](https://github.com/paulrobello/alb_routing_bug/blob/main/iac/aws/alb/route/main.tf#L15)
that the code that would test this enhancement request is commented out

**Comment by robertlcx** [comment] 2023-12-22 13:17
It was my understanding that https://github.com/paulrobello/alb_routing_bug was still the issue that had to be resolved and also the issue that I was supposed to fix. So this is still an unresolved issue, I see.

Re-opening then.

**Comment by bentsku** [comment] 2024-12-17 22:44
I believe the support for this feature has been added by @cabeaulac, therefore I'll be closing the issue. Please feel free to comment again if there's still an issue. Thanks!

**Closed by bentsku** 2024-12-17 22:44 UTC
Labels: type: feature, aws:elb, status: accepted
