### ISSUE TITLE
Error: localstack.services.generic_proxy:Error forwarding request: expected string or buffer

### ISSUE THREAD

**Issue by KamuelaFranco** [localstack/localstack#222] opened 2017-07-31 10:37 UTC
I seem to be getting this error now when trying to run the latest docker image from localstack/localstack:
```
WARNING:localstack.services.awslambda.lambda_api:Unable to run Lambda function on API Gateway message: working outside of application context Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 168, in process_apigateway_invocation
    return run_lambda(lambda_function, event=event, context={}, func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 108, in wrapped
    raise e
RuntimeError: working outside of application context

ERROR:localstack.services.generic_proxy:Error forwarding request: expected string or buffer Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 131, in forward
    data=data, headers=forward_headers, return_forward_info=True)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 116, in update_apigateway
    parsed_result = json.loads(result)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```
This was not happening with make infra on my local machine. What changed?

Steps to reproduce:

1. `docker run -it -p 4572:4572 -p 4569:4569 -p 4581:4581 -p 4574:4574 -p 4567:4567 -p 8080:8080 localstack/localstack`
2. Provision Lambda with `awscli`
3. Provision API Gateway
4. `curl -v http://localhost:4567/restapis/{REST_ID}/test/_user_request_/`
5. `curl` does not return and the output from the running docker image is as above.

**Comment by whummer** [comment] 2017-07-31 11:28
Thanks for reporting @KamuelaFranco . Can you please double-check if you are really using the latest image. That stack trace contains code that in fact shouldn't be in the image anymore.

In particular, generic_proxy.py, line 131 `... data=data, headers=forward_headers, return_forward_info=True)` does not exist anymore in https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py

Can you please try:
```
docker pull localstack/localstack
docker pull localstack/localstack:latest
docker pull localstack/localstack:0.7.3
```

Also, the recommended way of starting LocalStack is using the CLI. Can you please try:
```
pip install --upgrade localstack
localstack start --docker
```
Thanks

**Comment by KamuelaFranco** [comment] 2017-07-31 11:38
Is there some complication in starting it via docker directly? This is how we've gotten it working in our Bamboo VM.

**Comment by whummer** [comment] 2017-07-31 12:59
I am still unable to reproduce this.

On a fresh Docker installation I just pulled the image and `grep`ed for the code above, with empty result:
```
$ docker pull localstack/localstack
$ docker run --entrypoint /bin/bash -it localstack/localstack
# ls -la /opt/code/localstack/localstack/services/generic_proxy.py
-rw-rw-r--    1 root     root         12062 Jul 31 02:34 /opt/code/localstack/localstack/services/generic_proxy.py
# cat /opt/code/localstack/localstack/services/generic_proxy.py | grep return_forward_info
```

Note that I `grep`ed (searched) for `return_forward_info`, which is included in the stacktrace above, but it cannot be found. Something still makes me think that we are not using the same version of the Docker image.

Can you please post the output of `docker images`:
```
$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
localstack/localstack   latest              4563141d9736        10 hours ago        935.4 MB
```
Thanks

**Comment by KamuelaFranco** [comment] 2017-07-31 15:36
Thanks for getting back to me. I have the same output you do, e.g. no output regarding the `grep return_forward_info`.

```
$ docker images | grep localstack
localstack/localstack   latest              e1504f022630        13 hours ago        935MB
```
then
```
Last login: Mon Jul 31 16:22:16 on console
Kamuelas-MacBook-Pro:~ kamuela$ docker pull localstack/localstack
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Kamuelas-MacBook-Pro:~ kamuela$ docker pull localstack/localstack
Using default tag: latest
latest: Pulling from localstack/localstack
e4adc0eaaf1d: Pull complete 
711c3619bc40: Pull complete 
Digest: sha256:9c6d8597fecbc192332c5af69afe2a2d6e0af720b5a48b77390282290af4be6d
Status: Downloaded newer image for localstack/localstack:latest
Kamuelas-MacBook-Pro:~ kamuela$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack   latest              e1504f022630        13 hours ago        935MB
Kamuelas-MacBook-Pro:~ kamuela$ docker run -it -p 4572:4572 -p 4569:4569 -p 4581:4581 -p 4574:4574 -p 4567:4567 -p 8080:8080 -e SERVICES="s3,cloudformation,dynamodb,apigateway,lambda" -e LAMBDA_EXECUTOR=docker localstack/localstack:latest
2017-07-31 15:25:20,486 CRIT Supervisor running as root (no user in config file)
2017-07-31 15:25:20,488 INFO supervisord started with pid 1
2017-07-31 15:25:21,497 INFO spawned: 'dashboard' with pid 7
2017-07-31 15:25:21,500 INFO spawned: 'infra' with pid 8
(. .venv/bin/activate; bin/localstack web --port=8080)
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting mock API Gateway (http port 4567)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
 * Debugger is active!
Starting mock DynamoDB (http port 4569)...
 * Debugger PIN: 157-996-754
2017-07-31 15:25:22,990 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-07-31 15:25:22,990 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting mock Lambda service (http port 4574)...
Ready.
WARNING:localstack.services.awslambda.lambda_api:Error executing Lambda function: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 296, in run_lambda
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 292, in do_execute
    result = func(event, context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 370, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker

WARNING:localstack.services.awslambda.lambda_api:Unable to run Lambda function on API Gateway message: working outside of application context Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 167, in process_apigateway_invocation
    return run_lambda(lambda_function, event=event, context={}, func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 108, in wrapped
    raise e
RuntimeError: working outside of application context

ERROR:localstack.services.generic_proxy:Error forwarding request: expected string or buffer Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 166, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 119, in forward_request
    parsed_result = json.loads(result)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

^C2017-07-31 15:26:16,809 WARN received SIGINT indicating exit request
2017-07-31 15:26:16,810 INFO waiting for dashboard, infra to die
make: *** [Makefile:34: infra] Terminated
2017-07-31 15:26:16,811 INFO stopped: infra (terminated by SIGTERM)
make: *** [Makefile:75: web] Terminated
2017-07-31 15:26:16,812 INFO stopped: dashboard (terminated by SIGTERM)
Kamuelas-MacBook-Pro:~ kamuela$ cd Click/
Kamuelas-MacBook-Pro:Click kamuela$ ls
localstack		provision-my-handler
Kamuelas-MacBook-Pro:Click kamuela$ cd localstack/
Kamuelas-MacBook-Pro:localstack kamuela$ rm -rf *
Kamuelas-MacBook-Pro:localstack kamuela$ ls
Kamuelas-MacBook-Pro:localstack kamuela$ cd ..
Kamuelas-MacBook-Pro:Click kamuela$ cd provision-my-handler/
Kamuelas-MacBook-Pro:provision-my-handler kamuela$ ls
index.js	main.js		myHandler.zip	node_modules	package.json
Kamuelas-MacBook-Pro:provision-my-handler kamuela$ pip uninstall localstack
Cannot uninstall requirement localstack, not installed
Kamuelas-MacBook-Pro:provision-my-handler kamuela$ docker run --entrypoint /bin/bash -it localstack/localstack
bash-4.3# ls -la /opt/code/localstack/localstack/services/generic_proxy.py
-rw-rw-r--    1 root     root         12062 Jul 31 02:34 /opt/code/localstack/localstack/services/generic_proxy.py
bash-4.3# cat /opt/code/localstack/localstack/services/generic_proxy.py | grep return_forward_info
bash-4.3# exit
exit
Kamuelas-MacBook-Pro:provision-my-handler kamuela$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack   latest              e1504f022630        13 hours ago        935MB
Kamuelas-MacBook-Pro:provision-my-handler kamuela$ docker images | grep localstack
localstack/localstack   latest              e1504f022630        13 hours ago        935MB
Kamuelas-MacBook-Pro:provision-my-handler kamuela$ docker run -it -p 4572:4572 -p 4569:4569 -p 4581:4581 -p 4574:4574 -p 4567:4567 -p 8080:8080 -e SERVICES="s3,cloudformation,dynamodb,apigateway,lambda" -e LAMBDA_EXECUTOR=docker localstack/localstack:latest
```
receiving
```
2017-07-31 15:34:04,896 CRIT Supervisor running as root (no user in config file)
2017-07-31 15:34:04,898 INFO supervisord started with pid 1
2017-07-31 15:34:05,902 INFO spawned: 'dashboard' with pid 7
2017-07-31 15:34:05,904 INFO spawned: 'infra' with pid 8
(. .venv/bin/activate; bin/localstack web --port=8080)
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
Starting mock API Gateway (http port 4567)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
 * Debugger is active!
 * Debugger PIN: 157-996-754
2017-07-31 15:34:07,417 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-07-31 15:34:07,417 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting mock Lambda service (http port 4574)...
Ready.
```
Then I provision the API Gateway resources and the Lambda function, `curl` the endpoint, and this is immediately followed by:
```
WARNING:localstack.services.awslambda.lambda_api:Error executing Lambda function: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 296, in run_lambda
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 292, in do_execute
    result = func(event, context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 370, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker

WARNING:localstack.services.awslambda.lambda_api:Unable to run Lambda function on API Gateway message: working outside of application context Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 167, in process_apigateway_invocation
    return run_lambda(lambda_function, event=event, context={}, func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 108, in wrapped
    raise e
RuntimeError: working outside of application context

ERROR:localstack.services.generic_proxy:Error forwarding request: expected string or buffer Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 166, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 119, in forward_request
    parsed_result = json.loads(result)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by KamuelaFranco** [comment] 2017-07-31 16:18
As an update, I've skipped calling it through API Gateway and invoked the lambda itself to isolate this:
```
An error occurred (Exception) when calling the Invoke operation: Error executing Lambda function: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 296, in run_lambda
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 292, in do_execute
    result = func(event, context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 370, in generic_handler
    'Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "my-handler". Note that non-Python Lambdas require LAMBDA_EXECUTOR=docker
```

**Comment by whummer** [comment] 2017-08-03 00:23
Thanks for the update @KamuelaFranco . I'm closing this issue, as the `LAMBDA_EXECUTOR=docker` related question has been clarified in #226 . We will continue the discussion for adding a test case on this PR: https://github.com/localstack/localstack/pull/224

**Closed by whummer** 2017-08-03 00:23 UTC
