### ISSUE TITLE
With Step Functions v2 enabled:  No module named 'localstack.services.stepfunctions.asl.antlr'

### ISSUE THREAD

**Issue by Chad-Bailer-Regal** [localstack/localstack#8938] opened 2023-08-18 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After setting `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2` step functions appear to be broken. 

```
An error occurred (InternalError) when calling the CreateStateMachine operation (reached max retries: 4): exception while calling stepfunctions.CreateStateMachine: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service_plugin.py", line 36, in __call__
    return self.require_service(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service_plugin.py", line 50, in require_service
    service_plugin: Service = self.service_manager.require(service_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 73, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/plugins.py", line 294, in require
    container = self.get_service_container(name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/plugins.py", line 565, in get_service_container
    plugin = self._load_service_plugin(name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 73, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/plugins.py", line 614, in _load_service_plugin
    plugin = self.plugin_manager.load(plugin_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/plugin/manager.py", line 184, in load
    raise container.load_error
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/plugin/manager.py", line 283, in _load_plugin
    result = plugin.load(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/plugins.py", line 357, in load
    self.service = self.create_service()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/plugins.py", line 379, in create_service
    return self._create_service()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/providers.py", line 388, in stepfunctions_v2
    from localstack.services.stepfunctions.provider_v2 import StepFunctionsProvider
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/stepfunctions/provider_v2.py", line 68, in <module>
    from localstack.services.stepfunctions.asl.parse.asl_parser import AmazonStateLanguageParser
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/stepfunctions/asl/parse/asl_parser.py", line 6, in <module>
    from localstack.services.stepfunctions.asl.antlr.runtime.ASLLexer import ASLLexer
ModuleNotFoundError: No module named 'localstack.services.stepfunctions.asl.antlr
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using the example in the getting started doc:
```
awslocal stepfunctions create-state-machine \
        --name "WaitMachine" \
        --definition '{
        "StartAt": "WaitExecution",
        "States": {
            "WaitExecution": {
            "Type": "Wait",
            "Seconds": 10,
            "End": true
            }
        }
        }' \
        --role-arn "arn:aws:iam::000000000000:role/stepfunctions-role"

```

### Environment

```markdown
- LocalStack: latest
```

### Anything else?

This may be due to a missing `__init__.py` here https://github.com/localstack/localstack/tree/master/localstack/services/stepfunctions/asl/antlr

**Comment by dominikschubert** [comment] 2023-08-29 14:09
Unfortunately I can't reproduce the issue you're seeing when using your instructions.

Please make sure to do a fresh pull `docker pull localstack/localstack` before testing this again and ideally give us a sample of your docker-compose file. Maybe there's something else wrong with the startup.

**Comment by Chad-Bailer-Regal** [comment] 2023-08-29 16:15
So it seems like the issue only happens with the `localstack/localstack-pro` image.  The normal image `localstack/localstack` is working as intended. 

Here's my docker-compose file:
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - PROVIDER_OVERRIDE_STEPFUNCTIONS=v2
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }      
      - SNAPSHOT_FLUSH_INTERVAL=120
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by dominikschubert** [comment] 2023-08-30 06:38
Thanks @Chad-Bailer-Regal, I can verify that behavior now. Working on a fix :+1:

**Comment by dominikschubert** [comment] 2023-09-01 06:27
Fixed in https://github.com/localstack/localstack/pull/9018

Thanks again for reporting the issue. If you're experiencing any other issues with the v2 provider please let us know, we're very interested in improving it as fast as possible :+1:

**Closed by dominikschubert** 2023-09-01 06:27 UTC
Labels: type: bug, aws:stepfunctions, status: in progress
