### ISSUE TITLE
Has anyone tried localstack S3 with rclone ?

### ISSUE THREAD

**Issue by kforner** [localstack/localstack#4311] opened 2021-07-16 11:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Has anyone tried **localstack** S3 with **rclone** ?

cf this detailed post: https://forum.rclone.org/t/rclone-with-s3-localstack-copy-fails-with-forbidden-forbidden/25373
basically I can list, make a bucket but can not copy using rclone. 
Any hint ?

**Comment by mgagliardo** [comment] 2021-07-16 11:45
Hello @kforner I have been able to reproduce what I think you need, let me know if it works for you.

First of all not sure where are you running this from but I did from my local:

Run localstack:
```
$ docker run --rm -ti --name localstack -e DEBUG=1 -p 4566:4566 localstack/localstack:latest
```

Configure rclone:
```
$ rclone config create localstack s3 region us-east-1 endpoint http://localhost:4566
```

Create bucket:
```
$ rclone mkdir localstack:bucket
```

Copy sample file:
```
$ rclone sync -i 1.txt localstack:bucket
rclone: copy "1.txt"?
y) Yes, this is OK (default)
n) No, skip this
s) Skip all copy operations with no more questions
!) Do all copy operations with no more questions
q) Exit rclone now.
y/n/s/!/q> y
2021/07/16 13:42:37 NOTICE:
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         2.9s

# List
$ awslocal s3 ls s3://bucket/
2021-07-16 13:42:37          0 1.txt
```

Is there anything I'm doing different than you here?

**Comment by mgagliardo** [comment] 2021-07-16 11:49
One more thing, I was able to also sync a folder, but still not able to `ls` the bucket, doc is not quite clear for me though, maybe I'm doing something wrong here...


```
$ tree test/
test/
├── css
│   └── style.css
└── index.html

1 directory, 2 files

$ rclone sync -i test/ localstack:bucket
rclone: copy "index.html"?
y) Yes, this is OK (default)
n) No, skip this
s) Skip all copy operations with no more questions
!) Do all copy operations with no more questions
q) Exit rclone now.
y/n/s/!/q> y
rclone: copy "css/style.css"?
y) Yes, this is OK (default)
n) No, skip this
s) Skip all copy operations with no more questions
!) Do all copy operations with no more questions
q) Exit rclone now.
y/n/s/!/q> y
2021/07/16 13:47:19 NOTICE:
Transferred:   	       499 / 499 Bytes, 100%, 140 Bytes/s, ETA 0s
Transferred:            2 / 2, 100%
Elapsed time:         3.5s
```

```
$ awslocal s3 ls s3://bucket/
                           PRE css/
2021-07-16 13:42:37          0 1.txt
2021-07-16 13:47:18        448 index.html
```

**Comment by mgagliardo** [comment] 2021-07-16 11:52
Lastly, tried to reproduce your issue:

```
$ rclone -vv copy 2.txt localstack:bucket/
2021/07/16 13:50:53 DEBUG : Using config file from ""
2021/07/16 13:50:53 DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone" "-vv" "copy" "2.txt" "localstack:bucket/"]
2021/07/16 13:50:53 DEBUG : Creating backend with remote "2.txt"
2021/07/16 13:50:53 DEBUG : fs cache: adding new entry for parent of "2.txt", "/tmp"
2021/07/16 13:50:53 DEBUG : Creating backend with remote "localstack:bucket/"
2021/07/16 13:50:53 DEBUG : fs cache: renaming cache item "localstack:bucket/" to be canonical "localstack:bucket"
2021/07/16 13:50:53 DEBUG : 2.txt: Need to transfer - File not found at Destination
2021/07/16 13:50:53 INFO  : S3 bucket bucket: Bucket "bucket" created with ACL "private"
2021/07/16 13:50:53 DEBUG : 2.txt: MD5 = d41d8cd98f00b204e9800998ecf8427e OK
2021/07/16 13:50:53 INFO  : 2.txt: Copied (new)
2021/07/16 13:50:53 INFO  :
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.1s

2021/07/16 13:50:53 DEBUG : 4 go routines active
```

```
$ awslocal s3 ls s3://bucket/
                           PRE css/
2021-07-16 13:42:37          0 1.txt
2021-07-16 13:50:53          0 2.txt
2021-07-16 13:47:18        448 index.html
```

I'm closing this as rclone seems to work well with localstack, any issues seem to be coming either from configuration or from the tool (rclone) itself.

**Closed by mgagliardo** 2021-07-16 11:52 UTC
Labels: question

**Comment by kforner** [comment] 2021-07-16 14:22
I tried your example, but ls/lsd is not working on this remote

```
docker run --rm -ti --name localstack -e DEBUG=1 -p 4566:4566 localstack/localstack:latest

rclone config create localstack s3 region us-east-1 endpoint http://localhost:4566
rclone mkdir localstack:bucket

# but
rclone lsd localstack:
<3>ERROR : : error listing: NotFound: Not Found
	status code: 404, request id: , host id: 
Failed to lsd with 2 errors: last error was: NotFound: Not Found
	status code: 404, request id: , host id: 

# and 
rclone lsd localstack:bucket/
<3>ERROR : : error listing: directory not found
Failed to lsd with 2 errors: last error was: directory not found
```
I am not saying there's a bug in localstack, just if you have an idea why some rclone features do not work.
They have plenty of S3-related parameters, and support many S3-compatible providers (cf https://rclone.org/s3/).

Anyway thanks a lot for your quick and helpful support!!!

**Comment by mgagliardo** [comment] 2021-07-16 14:35
Ah my bad for implying that!
OTOH I don't see why those features wouldn't work on localstack, if you add `DEBUG=1` and/or `LS_LOG=trace` you can see some of those features are kind of buggy as they do not even reach localstack edge endpoint.

In any case, let me know if there's anything else I can help with.

Cheers

**Comment by kforner** [comment] 2021-07-16 14:43
Here's a detailed rclone log. seems like the problem is due to the HEAD call:
```
2021/07/16 14:40:25 DEBUG : Using config file from "/home/docker/.config/rclone/rclone.conf"
2021/07/16 14:40:25 DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone" "copy" "./world.txt" "localstack:toto" "--dump=bodies" "--retries=1" "--low-level-retries=1" "--log-level=DEBUG" "--log-file=rclone.log"]
2021/07/16 14:40:25 DEBUG : Creating backend with remote "./world.txt"
2021/07/16 14:40:25 DEBUG : fs cache: adding new entry for parent of "./world.txt", "/tmp"
2021/07/16 14:40:25 DEBUG : Creating backend with remote "localstack:toto"
2021/07/16 14:40:25 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2021/07/16 14:40:25 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/07/16 14:40:25 DEBUG : HTTP REQUEST (req 0xc0004a1000)
2021/07/16 14:40:25 DEBUG : HEAD /toto/world.txt HTTP/1.1
Host: localstack:5000
User-Agent: rclone/v1.55.1

2021/07/16 14:40:25 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/07/16 14:40:25 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/07/16 14:40:25 DEBUG : HTTP RESPONSE (req 0xc0004a1000)
2021/07/16 14:40:25 DEBUG : HTTP/1.1 403 Forbidden
Access-Control-Allow-Headers: authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Date: Fri, 16 Jul 2021 14:40:25 GMT
Server: BaseHTTP/0.3 Python/2.7.15
Content-Length: 0

2021/07/16 14:40:25 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/07/16 14:40:25 ERROR : Attempt 1/1 failed with 1 errors and: Forbidden: Forbidden
	status code: 403, request id: , host id: 
2021/07/16 14:40:25 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s

2021/07/16 14:40:25 DEBUG : 2 go routines active
2021/07/16 14:40:25 Failed to copy: Forbidden: Forbidden
	status code: 403, request id: , host id: 

```

**Comment by kforner** [comment] 2021-07-16 15:10
Is there a way to configure permission for the HEAD call in localstack ?

**Comment by mgagliardo** [comment] 2021-07-16 21:27
Do you know what is the exact call it is trying to make?

**Comment by kforner** [comment] 2021-07-20 17:07
> Do you know what is the exact call it is trying to make?

isn't it that this call ?
`2021/07/16 14:40:25 DEBUG : HEAD /toto/world.txt HTTP/1.1`

**Comment by mgagliardo** [comment] 2021-07-20 19:36
Are you sure it is?

```
$ curl --head http://localhost:4566/test/test.txt
HTTP/1.1 200 
content-type: text/plain
content-length: 0
etag: "d41d8cd98f00b204e9800998ecf8427e"
last-modified: Tue, 20 Jul 2021 19:24:18 GMT
access-control-allow-origin: *
x-amz-request-id: 0C303582FB05B10F
x-amz-id-2: MzRISOwyjmnup0C303582FB05B10F7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request
access-control-expose-headers: x-amz-version-id
connection: close
date: Tue, 20 Jul 2021 19:36:41 GMT
server: hypercorn-h11
```

```
2021-07-20 19:35:45,024:API: 127.0.0.1 - - [20/Jul/2021 19:35:45] "HEAD /test/test.txt HTTP/1.1" 200 -
```

**Comment by kforner** [comment] 2021-07-21 09:51
I restarted from scratch, using the latest localstack, with easier reproducibility.

Start localstack S3:
```
rclone mkdir localstack:bucket --dump=bodies --retries=1 --low-level-retries=1 --log-level=DEBUG
```
In another terminal:
## configure rclone remote
```
rclone config create localstack s3 region us-east-1 endpoint http://localhost:4566
```

## create bucket - OK
command:
```
rclone mkdir localstack:bucket 
```
local stack log:
```
2021-07-21 09:15:22,751:API: 127.0.0.1 - - [21/Jul/2021 09:15:22] "PUT /bucket HTTP/1.1" 200 -
```
## copy file into bucket - OK

command
```
echo hello > world.txt
rclone copy ./world.txt localstack:bucket/
```

local stack log:
```
2021-07-21 09:24:16,643:API: 127.0.0.1 - - [21/Jul/2021 09:24:16] "HEAD /bucket/world.txt HTTP/1.1" 404 -
2021-07-21 09:24:16,657:API: 127.0.0.1 - - [21/Jul/2021 09:24:16] "PUT /bucket HTTP/1.1" 200 -
2021-07-21 09:24:16,668:API: 127.0.0.1 - - [21/Jul/2021 09:24:16] "PUT /bucket/world.txt HTTP/1.1" 200 -
2021-07-21 09:24:16,678:API: 127.0.0.1 - - [21/Jul/2021 09:24:16] "HEAD /bucket/world.txt HTTP/1.1" 200 -
```

## list folders/buckets in remote - ERROR

command:
```
rclone ls localstack:bucket/ --dump=bodies --retries=1 --low-level-retries=1 --log-level=DEBUG
```

output:
```
rclone ls localstack:bucket/ --dump=bodies --retries=1 --low-level-retries=1 --log-level=DEBUG
<7>DEBUG : Using config file from "/home/karl/.config/rclone/rclone.conf"
<7>DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone" "ls" "localstack:bucket/" "--dump=bodies" "--retries=1" "--low-level-retries=1" "--log-level=DEBUG"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "localstack:bucket/"
<7>DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
<7>DEBUG : fs cache: renaming cache item "localstack:bucket/" to be canonical "localstack:bucket"
<7>DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<7>DEBUG : HTTP REQUEST (req 0xc00057be00)
<7>DEBUG : GET /bucket?delimiter=&max-keys=1000&prefix= HTTP/1.1
Host: localhost:4566
User-Agent: rclone/v1.55.1
Accept-Encoding: gzip

<7>DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<7>DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<7>DEBUG : HTTP RESPONSE (req 0xc00057be00)
<7>DEBUG : HTTP/1.1 404 
Connection: close
Access-Control-Allow-Headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-amz-version-id
Content-Type: text/html; charset=utf-8
Date: Wed, 21 Jul 2021 09:45:04 GMT
Server: hypercorn-h11

{"status": "running"}
<7>DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<7>DEBUG : 2 go routines active
Failed to ls: directory not found
```
local stack log:
```
2021-07-21T09:25:48:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /bucket?delimiter=&max-keys=1000&prefix=", target header "", auth header "", data ""
```


So it seems the issue is related to this `GET /bucket?delimiter=&max-keys=1000&prefix=`

To confirm that: 

curl --get "http://localhost:4566/bucket/" --> 
```
2021-07-21T09:49:31:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /bucket/", target header "", auth header "", data ""
```

**Comment by mgagliardo** [comment] 2021-07-21 12:23
The problem is a malformed GET request:

```
curl "http://localhost:4566/bucket/?delimiter=&max-keys=1000&prefix="

<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>bucket</Name><Prefix></Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>world.txt</Key><LastModified>2021-07-21T12:20:41.000Z</LastModified><ETag>&#34;b1946ac92492d2347c6235b4d2611184&#34;</ETag><Size>6</Size><StorageClass>STANDARD</StorageClass><Owner><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID><DisplayName>webfile</DisplayName></Owner></Contents></ListBucketResult>
```

You can see [the official API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html) the correct syntax is: `GET /?delimiter=Delimiter&encoding-type=EncodingType&marker=Marker&max-keys=MaxKeys&prefix=Prefix HTTP/1.1`

**Comment by kforner** [comment] 2021-07-22 13:12
Sorry cross-posting since this issue is with localstack and rclone:
from https://forum.rclone.org/t/rclone-with-s3-localstack-copy-fails-with-forbidden-forbidden/25373/17: 

> i think we are making progress by using --s3-force-path-style=false.
now it seems like a dns issue on the server, as rclone tries to lookup bucket.localhost.
have you searched the internet about this, as there seem to be other localstack and/or docker users with that problem.

What do you think ?

**Comment by mgagliardo** [comment] 2021-07-22 14:58
Again, this is not a problem with localstack, rclone seems to be looking for the `bucket.localhost`. You can do the following:

`echo "127.0.0.1 bucket.localhost" | sudo tee -a /etc/hosts`

And add it to the hostsfile, that would maskerade your request as the record would actually exist, but the problem is the request still fails:

```
2021-07-22T14:52:55:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /bucket?delimiter=%2F&max-keys=1000&prefix=", target header "", auth header "", data ""
```

You can see the bucket delimiter is still `/bucket?` when it should be `/bucket/?...`, even if you would use `rclone ls localstack:bucket/`

**Comment by kforner** [comment] 2021-08-24 08:15
I'm still surprised that you are not more eager to have localstack working with rclone.
The combination of rclone mount + localstack S3 enable to provide a networked filesystem to a docker stack, even in an offline setting which is nice for testing.

**Comment by mgagliardo** [comment] 2021-08-24 08:33
Hello @kforner, I am more than happy to help you troubleshoot in whatever you might need.

However when it comes to an external application there is not much we can do. I would be happy to contribute to rclone as well if I would have more time but (I personally think) as I said before this is not on localstack's side. Not only because the debug logs I showed you before, but because we did not receive any other requests like this.

Should you have any nice requests for expanding localstack's ecosystem like that don't hesitate on contacting us or get in touch with us [via any of our methods](https://localstack.cloud/contact/), thanks for understanding :)

**Comment by kforner** [comment] 2021-08-24 09:04
Hi @mgagliardo Thanks for your quick reply.

> However when it comes to an external application there is not much we can do.

I understand that, but for me it's even worse since I'm external to both localstack and rclone.
And in that topic I was stuck in-between, which was totally useless and counter-productive, since I gave some ways to reproduce the issue:

```
docker run --rm -ti --name localstack -e DEBUG=1 -p 4566:4566 localstack/localstack:latest

rclone config create localstack s3 region us-east-1 endpoint http://localhost:4566
rclone mkdir localstack:bucket
```

What I suggest, is that if you're willing to, to open your own rclone issue on that topic. It would be far more productive, and I suppose that localstack would benefit to be "rclone-compatible". 
The couple (localstack s3/rclone vfs) could become a kind of docker stack standard for sharing files between containers.
 
Best,

**Comment by ncw** [comment] 2021-08-25 11:46
The problem appears to in listing the bucket. This request works fine

```
$ curl "http://localhost:4566/potato/?delimiter=%2F&max-keys=1000&prefix="
<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>potato</Name><Prefix></Prefix><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>
```

Whereas leaving off the trailing `/` on the bucket name like rclone does causes it to fail.

```
$ curl "http://localhost:4566/potato?delimiter=%2F&max-keys=1000&prefix="
{"status": "running"}
```

Leaving off the trailing `/` works fine with AWS

```
2021/08/25 12:37:07 DEBUG : GET /rclone?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: s3.eu-west-2.amazonaws.com
User-Agent: rclone/v1.57.0-beta.5649.c751d93e9.fix-5545-box-cleanup
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210825T113707Z
Accept-Encoding: gzip

2021/08/25 12:37:07 DEBUG : HTTP RESPONSE (req 0xc00080c800)
2021/08/25 12:37:07 DEBUG : HTTP/1.1 200 OK
[snip]
```

Rclone uses the official [AWS SDK for Go](https://aws.amazon.com/sdk-for-go/) and it is this which generates the request, given a bucket name. This style also works with all the other 11  [S3 providers rclone supports](https://rclone.org/s3/).

So I think this is probably a bug in localstack!

**Comment by ncw** [comment] 2022-04-22 22:06
DNS problems probably mean that https://rclone.org/s3/#s3-force-path-style is set wrong @NickEm 

What we should do is make a provider for localstack with all the correct settings in. Which provider are you using? Other is probably the correct choice.

Perhaps make a post on forum.rclone.org and we can try to make a config that works then make a provider.

**Comment by whummer** [comment] 2022-04-23 09:53
Thanks for the update @NickEm @ncw . Looks like the issue previously posted is resolved with the latest version:
```
% curl "http://localhost:4566/potato?delimiter=%2F&max-keys=1000&prefix="

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>potato</BucketName><RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID></Error>
```
Just to confirm, have you been able to get rclone to work with the latest LocalStack version @ncw ? Thanks

**Comment by NickEm** [comment] 2022-04-27 09:39
Hey guys, thank you for the prompt replies.
Yeah, I tried only with the latest `localstack`(0.14.2).
The default hasn't worked. But as Nick mentioned the only combination that worked for me was:
```
--s3-provider=Other
--s3-force-path-style=true
```
So, kudos and thank you @ncw!

**Comment by kforner** [comment] 2022-05-10 08:03
Just for the record: what works for me:
docker-compose.yml
```
version: '3.4'
services:
  localstack:
    image: localstack/localstack:0.14.2
    environment:
      DEFAUT_REGION: us-east-1
      SERVICES: "s3"
      HOSTNAME: "localstack"
    ports:
      - 4566:4566
```

start with `docker-compose up`

then with rclone conf: 
```
[localstack]
type = s3
provider = Other
env_auth = true
region = us-east-1
endpoint = http://localhost:4566
```
it works fine: 
```
rclone mkdir localstack:titi
rclone copy docker-compose.yml localstack:titi/
rclone ls localstack:titi/
      205 docker-compose.yml
```
