### ISSUE TITLE
Unable start on windows 10

### ISSUE THREAD

**Issue by Lacan82** [localstack/localstack#851] opened 2018-07-16 00:06 UTC
did pip install localstack
doing localstack start doesn't work...Scripts folder is in my paths...If I do python localstack start within scripts...I can get it attempt to start but fails with this error:

Error starting infrastructure: environment can only contain strings Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\Python27\lib\site-packages\localstack\services\install.py", line 140, in install_components
    parallelize(install_component, names)
  File "C:\Python27\lib\site-packages\localstack\utils\common.py", line 751, in parallelize
    result = pool.map(func, list)
  File "C:\Python27\lib\multiprocessing\pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
TypeError: environment can only contain strings

ERROR: environment can only contain strings

following: 

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.4\bin\..
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_172\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

pip 10.0.1 from c:\python27\lib\site-packages\pip

**Comment by technoartista** [comment] 2018-07-19 12:29
Experiencing similar issue

**Comment by whummer** [comment] 2019-08-03 19:12
@technoartista @Lacan82  Closing as duplicate of #563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

* only install the bare minimum dependencies by default
* start LocalStack in Docker by default, and
* lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:12 UTC
