### ISSUE TITLE
error calling DynamoDB via javascript sdk (OS X 10.12.6)

### ISSUE THREAD

**Issue by noah10** [localstack/localstack#477] opened 2017-11-21 19:54 UTC
When I run DynamoDB (either in docker or locally) and call it using the regular aws cli, all is well (at least for creating and listing tables, which is all I've done via the cli so far). But when my angular app calls it using the aws javascript sdk I see the following error:

```
2017-11-21T19:20:28:ERROR:localstack.services.generic_proxy: Error forwarding request: expected string or buffer Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
path=path, data=data, headers=forward_headers)
File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 29, in forward_request
data = json.loads(to_str(data))
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

Version info:

```
$ localstack --version
0.8.2
$ node -v
v8.6.0
$ npm -v
5.5.1
```

**Comment by whummer** [comment] 2017-11-24 23:03
Thanks for reporting @noah10 . Which command and inputs are you using in your angular app, exactly? Can you please provide a small self-contained test case to reproduce this error. Thanks

**Comment by noah10** [comment] 2017-12-03 00:03
Here you go:

https://github.com/noah10/localstack477-repro.git

To use it, do your git clone, make sure that you have localstack dynamodb running on port 4569 and then:

```
npm install
ng s
```

Once it's up and running (you should see "webpack: Compiled successfully."), point your browser at localhost:4200 and take a look at the console output. You should see:

```
Calling listTables
core.es5.js:2925 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

...which notably does *not* include a list of your dynamodb tables. If you look at the terminal output of localstack dynamodb you'll see the error reported above. All of the relevant configuration parameters are in https://github.com/noah10/localstack477-repro/blob/master/src/environments/environment.ts and the code is in https://github.com/noah10/localstack477-repro/blob/master/src/app/app.component.ts . Other than those two files and including aws-sdk as a dependency this is a stock bare-bones angular app template generated by ng new. If I run it with Amazon's local dynamodb I get the list of tables as expected.

**Comment by zachschultz** [comment] 2018-06-21 18:36
same issue

**Comment by whummer** [comment] 2019-03-18 03:29
Closing this issue as fixed/outdated - should have been fixed in the meantime. Please re-open if the problem persists. Thanks

**Comment by noah10** [comment] 2019-03-18 18:47
Still exists, although the stack trace has changed somewhat:

```
2019-03-18T11:43:41:ERROR:localstack.services.generic_proxy:
 Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType Traceback (most recent call last):
  File "/Users/noah/.virtualenvs/localstack477-repro-VwqX_DKk/lib/python3.7/site-packages/localstack/services/generic_proxy.py", line 196, in forward
    path=path, data=data, headers=forward_headers)
  File "/Users/noah/.virtualenvs/localstack477-repro-VwqX_DKk/lib/python3.7/site-packages/localstack/services/dynamodb/dynamodb_listener.py", line 35, in forward_request
    data = json.loads(to_str(data))
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by AlexNeises** [comment] 2019-04-17 20:44
Any update on this? It seems like every issue dealing with this is closed without a real solution.

**Comment by jonb226** [comment] 2019-06-12 14:46
I had this issue as well. In my case I happen to have an nginx reverse proxy in place for development purposes, so I could resolve the error by reverse proxying to localstack dynamodb via nginx with a config like:
```server {
        listen 4560;

        location / {
            if ($request_method = OPTIONS ) {
                add_header Content-Length 0;
                add_header Content-Type text/plain;
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Headers *;
                return 200;
            }
            proxy_pass http://localstack:4569;
            proxy_hide_header Access-Control-Allow-Origin;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers *;
        }
    }```

The last error @noah10 posted was resolved with the OPTIONS response, and then the rest of the block is to deal with CORS. I wouldn't be surprised if there were some settings somewhere I had missed to make this easier, but the above has resolved the issue for me for the moment.

**Comment by whummer** [comment] 2019-11-18 20:23
Thanks @jonb226 @AlexNeises @noah10 . Just ran the original sample from https://github.com/noah10/localstack477-repro.git against the latest version of LocalStack - seems to be working. 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/2807888/69090687-51d49c80-0a49-11ea-9297-1537c83954f7.png">

I believe this has been fixed in a recent change that enables `OPTIONS` (CORS) requests without payload. Closing this issue - please reopen if the problem persists.

**Closed by whummer** 2019-11-18 20:23 UTC
Labels: bug, needs-triaging, priority-high
