### ISSUE TITLE
bug: SQS - messages only moved to dead letter queue on subsequent RecieveMessageRequest

### ISSUE THREAD

**Issue by zakhenry** [localstack/localstack#8234] opened 2023-05-01 20:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After pushing to an sqs queue that has a dlq configured, receiving that message and setting the visibility timeout to 0, the message should be moved to the dlq if the `maxReceiveCount` is `1`. Instead nothing actually happens, until the next call to `receiveMessage` is made which triggers the move of that message to the DLQ

### Expected Behavior

Moving a message to DQL should not wait for a subsequent `receiveMessage` call before initiating the change. 

The fix is likely to add the `self._dead_letter_check` call to the `change_message_visibility` handler, so that the visibility change causes the message to be immediately shifted to the DQL

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    testcontainers in kotlin

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Unit test in kotlin, assume a functioning connection to a configured queue with a dead letter queue. Note this test passes, see the comment for the superfluous receive message that is actually required to make the test pass

```kotlin

describe("dead letter queue") {

            it("has a configured dead letter queue that receives messages after first failed receipt") {

                val messageBody = "hello ${queue.queueName}"

                queue.client.sendMessage(
                    SendMessageRequest()
                        .withMessageBody(messageBody)
                        .withQueueUrl(queue.queueUrl)
                )

                queue.client.receiveMessage(
                    ReceiveMessageRequest().withQueueUrl(queue.deadLetterQueueUrl).withWaitTimeSeconds(1)
                ).messages.shouldBeEmpty()

                val message = queue.client.receiveMessage(
                    ReceiveMessageRequest().withQueueUrl(queue.queueUrl).withWaitTimeSeconds(1)
                ).messages.shouldNotBeEmpty().first()

                queue.client.changeMessageVisibility(
                    ChangeMessageVisibilityRequest()
                        .withReceiptHandle(message.receiptHandle)
                        .withQueueUrl(queue.queueUrl)
                        .withVisibilityTimeout(0)
                )

                // frustratingly this call is require to actually prompt localstack to move the message to the DLQ as it
                // is the receiveMessage handler that actually triggers the move, not time as it should be
                // @ref https://github.com/localstack/localstack/blob/66dd11858d5109154857cff94d5bb263b3a62e74/localstack/services/sqs/provider.py#L989-L996
                queue.client.receiveMessage(
                    ReceiveMessageRequest().withQueueUrl(queue.queueUrl).withWaitTimeSeconds(1)
                ).messages.shouldBeEmpty()

                queue.client.receiveMessage(
                    ReceiveMessageRequest().withQueueUrl(queue.deadLetterQueueUrl).withWaitTimeSeconds(1)
                ).messages.shouldNotBeEmpty().first().apply {
                    body.shouldBe(messageBody)
                }

            }

        }

```

### Environment

```markdown
- OS: MacOS 13.3.1 aarm
- LocalStack: 2.0.2
```

### Anything else?
relevant snippet where the only call to move messages to DQL is performed (this is inside the `def receive_message()` function)

https://github.com/localstack/localstack/blob/66dd11858d5109154857cff94d5bb263b3a62e74/localstack/services/sqs/provider.py#L989-L996

**Comment by thrau** [comment] 2023-05-02 11:34
hey @zakhenry, thanks for reporting. could you share the exact queue creation command including the queue attributes so we can try to reproduce this on AWS?

**Comment by thrau** [comment] 2023-05-03 23:46
Hey @zakhenry, another follow up: I tried to verify the intended behavior on AWS but can't. If I understood correctly, this test should pass when running against AWS, since you expect the message to be delivered to the DLQ when the visibility timeout expires. However AWS doesn't seem to behave this way either. The DLQ is empty in this scenario, so LocalStack seems to be doing things correctly here.

Happy to dig into it further though if you can point out something I may be missing.

```python
def test_dead_letter_queue_triggered_on_change_visibility_timeout(self, sqs_create_queue, aws_client):
    queue_name = f"queue-{short_uid()}"

    # set up the DLQ
    dead_letter_queue_name = f"dl-queue-{short_uid()}"
    dl_queue_url = sqs_create_queue(QueueName=dead_letter_queue_name)
    url_parts = dl_queue_url.split("/")
    dl_target_arn = arns.sqs_queue_arn(url_parts[-1], account_id=url_parts[len(url_parts) - 2])

    # create queue with redrive policy
    policy = {"deadLetterTargetArn": dl_target_arn, "maxReceiveCount": 1}
    queue_url = sqs_create_queue(
        QueueName=queue_name,
        Attributes={"RedrivePolicy": json.dumps(policy)},
    )

    # send a test message
    result_send = aws_client.sqs.send_message(QueueUrl=queue_url, MessageBody="test")

    # receive the message from the queue
    recv_result = aws_client.sqs.receive_message(QueueUrl=queue_url).get("Messages")
    assert len(recv_result) == 1

    # change the visibility timeout to 0
    aws_client.sqs.change_message_visibility(
        QueueUrl=queue_url,
        ReceiptHandle=recv_result[0]["ReceiptHandle"],
        VisibilityTimeout=0,
    )

    # actually raises a key error because there are no messages in the queue
    assert len(aws_client.sqs.receive_message(QueueUrl=dl_queue_url, WaitTimeSeconds=10)["Messages"]) == 1
```

**Comment by zakhenry** [comment] 2023-05-04 00:02
Hey @thrau thanks for looking in to this, I haven't been able to verify this behaviour in AWS (I don't have AWS access) but I do find it quite surprising.

Your unit test looks correct unless there is a delay on moving the item to the DLQ. if you insert a sleep before your final assertion is there any change in behavior?

If the behaviour matches AWS then all good I guess, localstack replicates what I would consider a bug in AWS. Might be worth putting your unit test into the code base as it's the kind of thing that might be inadvertently "fixed" in localstack

**Comment by thrau** [comment] 2023-05-06 13:32
i tested this also by adding 60 seconds delay before checking the DLQ, it's still not moved there. i'll close this for now. if we find some more evidence that localstack should behave differently, then i'm glad to look into it more.

**Closed by thrau** 2023-05-06 13:32 UTC
Labels: type: bug, status: response required, aws:sqs

**Comment by varunu28** [comment] 2023-08-13 19:41
Thanks a ton @thrau @zakhenry  for such wonderful discussion on Github and I am glad I ended up here after slamming my head for 2 days straight. 

I was facing the same issue and made a mistake of considering AWS documentation as source of truth which says.
```
 The maxReceiveCount is the number of times a consumer tries receiving a message from a queue without deleting it 

before being moved to the dead-letter queue. Setting the maxReceiveCount to a low value such as 1 would result in any 

failure to receive a message to cause the message to be moved to the dead-letter queue.
```
Essentially it doesn't do what it says and I ended up opening an issue. Thanks once again
https://github.com/localstack/localstack/issues/8903
