### ISSUE TITLE
Update/redeploy of Lambda (with serverless) don't update

### ISSUE THREAD

**Issue by sbv-trueenergy** [localstack/localstack#1248] opened 2019-04-11 08:51 UTC
When I use serverless (and serverless-localstack) to redeploy/update a lambda the changes don't go through.

For example if i change the name of the handler, add requirements to the zip etc.

Looking at the localstack logs I see:

```
2019-04-11T08:40:48:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:48] "GET /teems-local-ServerlessDeploymentBucket-2A-Z8349878893?list-type=2&prefix=serverless%2Fteems%2Flocal HTTP/1.1" 200 -
2019-04-11T08:40:48:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:48] "HEAD /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554971958412-2019-04-11T08%3A39%3A18.412Z/compiled-cloudformation-template.json HTTP/1.1" 200 -
2019-04-11T08:40:48:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:48] "HEAD /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554971958412-2019-04-11T08%3A39%3A18.412Z/teems.zip HTTP/1.1" 200 -
172.17.0.1 - - [11/Apr/2019 08:40:48] "POST / HTTP/1.1" 200 -
2019-04-11T08:40:48:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:48] "PUT /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/compiled-cloudformation-template.json HTTP/1.1" 200 -
2019-04-11T08:40:49:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (500) POST /: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

2019-04-11T08:40:48:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:48] "POST /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/teems.zip?uploads HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "PUT /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/teems.zip?partNumber=4&uploadId=eXYAj38pDQU8NVTB6aV2YBup%2FTjv6PyF8NoHYTszDaWArrUA4FMyNa5A HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "PUT /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/teems.zip?partNumber=2&uploadId=eXYAj38pDQU8NVTB6aV2YBup%2FTjv6PyF8NoHYTszDaWArrUA4FMyNa5A HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "PUT /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/teems.zip?partNumber=1&uploadId=eXYAj38pDQU8NVTB6aV2YBup%2FTjv6PyF8NoHYTszDaWArrUA4FMyNa5A HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "PUT /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/teems.zip?partNumber=3&uploadId=eXYAj38pDQU8NVTB6aV2YBup%2FTjv6PyF8NoHYTszDaWArrUA4FMyNa5A HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "POST /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/teems.zip?uploadId=eXYAj38pDQU8NVTB6aV2YBup%2FTjv6PyF8NoHYTszDaWArrUA4FMyNa5A HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "GET /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/compiled-cloudformation-template.json HTTP/1.1" 200 -
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "POST / HTTP/1.1" 500 -
2019-04-11T08:40:49:ERROR:werkzeug: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 302, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 290, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 117, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 200, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 274, in call_action
response = method()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 294, in update_stack
tags=tags,
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 330, in update_stack
stack.update(template, role_arn, parameters=parameters, tags=tags)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 112, in update
self.resource_map.update(self.template_dict, parameters)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 545, in update
raise last_exception
AttributeError: type object 'LambdaFunction' has no attribute 'update_from_cloudformation_json'
2019-04-11T08:40:49:INFO:werkzeug: 127.0.0.1 - - [11/Apr/2019 08:40:49] "GET /teems-local-ServerlessDeploymentBucket-2A-Z8349878893/serverless/teems/local/1554972048471-2019-04-11T08%3A40%3A48.471Z/compiled-cloudformation-template.json HTTP/1.1" 200 -
``` 

I start localstack with:
``` 

docker run --name $docker_name -d \
    -e LAMBDA_EXECUTOR=docker \
    -e DOCKER_HOST=unix:///var/run/docker.sock \
    -e SERVICES=cloudformation,s3,sts,lambda,cloudwatch \
    -e DEBUG=1 \
    -p 443:443 \
    -p 4567-4596:4567-4596 \
    -p 8080:8080 \
    -v $PWD:$PWD \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/localstack:/tmp/localstack \
    localstack/localstack:latest
``` 
and i've just pulled latest image 5 minutes ago.

**Comment by luke-grassroot** [comment] 2019-05-23 21:21
I am getting the same thing. Have pulled latest image recently and have similar config. Anyone have any updates on cause or suggestions for how to workaround?

**Comment by rsosnin** [comment] 2019-05-29 18:14
@sbv-trueenergy @luke-grassroot before you deploy/re-deploy your lambda function, delete the existing function. That's what I do as a workaround. Should be quite easy.

**Comment by gavinvangent** [comment] 2019-08-14 12:22
For those going through the pain I'm enduring:

Using `sis remove` to delete your stack before attempting a new deploy will also not work due to this issue: https://github.com/localstack/localstack/issues/999

You will have to delete each resource manually if you want to drop a stack entirely.

**Comment by chrisandrews7** [comment] 2019-09-02 10:37
Its open as a feature request in [moto](https://github.com/spulec/moto) https://github.com/spulec/moto/issues/2317

**Comment by whummer** [comment] 2019-12-08 10:39
Thanks for reporting @sbv-trueenergy @luke-grassroot @rsosnin @gavinvangent @chrisandrews7 

> AttributeError: type object 'LambdaFunction' has no attribute 'update_from_cloudformation_json'

This issue should be fixed in the latest version. You should now be able to run multiple `sls deploy` commands in sequence, and the Lambda functions (code and configuration) should get updated.

> Using `sls remove` to delete your stack before attempting a new deploy will also not work due to this issue: #999

Correct, this still appears to be a problem. Closing this issue, as the "update" part seems to be fixed. Let's track the progress of the "remove" part in #999.

**Closed by whummer** 2019-12-08 10:39 UTC

**Comment by zhenwenc** [comment] 2020-06-07 03:41
Hi @whummer , I am getting a similar error for S3 buckets:
```
AttributeError: type object 'FakeBucket' has no attribute 'update_from_cloudformation_json'
```

Are they somehow related (similar root cause)? Thanks!

**Comment by yonahforst** [comment] 2020-07-21 15:29
I'm having a similar one as well.
` type object 'LambdaPermission' has no attribute 'delete_from_cloudformation_json'`
