### ISSUE TITLE
Events being sent to incorrect source mappings

### ISSUE THREAD

**Issue by a88zach** [localstack/localstack#1441] opened 2019-07-26 13:11 UTC
I am currently setting up several event source mappings between kinesis streams and down stream lambda processors.  However, the kinesis streams are sending the events to multiple downstream lambda processors even though there is no event source mapping tied to the lambda.

From a brief overview of the code, it looks like you are getting the event source mappings based on a starts with check as seen here:

https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L280

This means that if I have 2 streams, `myFancyStream1` and `myFancyStream2` and I hook up each stream to different lambdas.  Both lambdas will be sent the events when either stream has records

This check should be a strict compare to uniquely identify event source mappings

**Comment by whummer** [comment] 2019-12-21 12:51
Thanks for reporting @a88zach . Looks like a potential duplicate of #1705 . This should be fixed in #1764 - please report here if the problem persists. Thanks

**Closed by whummer** 2019-12-21 12:51 UTC
