### ISSUE TITLE
Creating a queue through the API gives a successful response when queue is not created 

### ISSUE THREAD

**Issue by jonathanroby** [localstack/localstack#2751] opened 2020-07-20 19:54 UTC
# Type of request: This is a
[X] bug report
[ ] feature request

# Detailed description
This problem applies to version `0.11.3` (isn't present with `0.11.2`); the issue may be related to a [change in the queue url format](https://github.com/localstack/localstack/issues/2612#issuecomment-653520084), which introduces an `/<accountId>/` in the path, in place of `/queue/`.

Creating a queue through the API gives a successful response, but it does not appear the queue is actually created. Two observations suggest this conclusion.

First, when listing queues through the AWS CLI, the queue name is not present. (Though this response diverges from the API response, which does list the queue name.)

Second, it isn't possible to send messages to the queue.

## Expected behavior
When creating a queue through the API:
  1) the queue name should be listed by the AWS CLI
  2) it should be possible to send messages to it

## Actual behavior
When creating a queue through the API:
1) the queue name is NOT listed by the AWS CLI
2) it is NOT possible to send messages to it

# Steps to reproduce
Create a queue through the API

Request

```
POST  HTTP/1.1
Host: localhost:4576
Content-Type: application/x-www-form-urlencoded
Content-Encoding: identity

Action=CreateQueue&QueueName=api-created-queue
```

Response

```
<CreateQueueResponse>
	<CreateQueueResult>
		<QueueUrl>http://localhost:4576/000000000000/api-created-queue</QueueUrl>
	</CreateQueueResult>
	<ResponseMetadata>
		<RequestId><request-id-hash></RequestId>
	</ResponseMetadata>
</CreateQueueResponse>
```

**1) The queue name is NOT present when checking through the AWS CLI**

```
$ aws --endpoint-url=http://localhost:4576 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4576/000000000000/cli-created-queue"
    ]
}
```

Note: Queues are still successfully created through the CLI.

Contrast this response with the one provided by the API:

```
$ curl http://localhost:4576/?Action=ListQueues
<ListQueuesResponse>
	<ListQueuesResult>
		<QueueUrl>http://localhost:4576/000000000000/api-created-queue</QueueUrl>
	</ListQueuesResult>
	<ResponseMetadata>
		<RequestId><request-id-hash></RequestId>
	</ResponseMetadata>
</ListQueuesResponse>
```

**2) It is NOT possible to send messages to the queue**

Request

```
$ aws --endpoint-url=http://localhost:4576 sqs send-message --queue-url=http://localhost:4576/queue/api-created-queue --message-body=[...]

An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist for this wsdl version.
```

## Command used to start LocalStack
Created through a default configuration.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-221) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment] 2020-07-21 19:09
@jonathanroby Using which API are you trying to create the queue? we tried to reproduce the issue by creating the Queue from POSTMAN and then listed queues in the CLI but in this case we are able to see the queue in the list.

Can you give us a bit more detail or  a sample example on using which API are you creating the queue ? This would help us identify and resolve the issue a bit sooner.Thanks


![image](https://user-images.githubusercontent.com/29707592/88096087-bf763100-cbb3-11ea-833c-edc69666c04d.png)

awslocal sqs list-queues 

{
    "QueueUrls": [
        "http://localhost:4576/000000000000/api-created-queue"
    ]
}

**Comment by usmangani1** [comment] 2020-07-25 17:06
@jonathanroby Can you help us here to identify from which source you are trying to create the API ?

**Comment by chris-crowther** [comment] 2020-08-04 15:08
I'm experiencing the same problem in `0.11.3`. My queue is created with `awslocal` from a shell script mounted at `/docker-entrypoint-initaws.d/`. Rolling back to `0.11.2` has fixed it.

**Comment by sahurgithub** [comment] 2020-08-31 19:58
I've encountered this issue yesterday as well. To me it seems related to the hostname & port mapping. I have the localstack running with docker-compose with docker on Windows (using WSL 2). Another container in the docker-compose connects to localstack using "http://localstack:4566" and can create and use the queues but if I try to do `aws --endpoint-url=http://localhost:4567 sqs list-queues` from the host machine (notice localhost vs localstack) then I get an empty response.

Rolling back to 0.11.2 has fixed it for me too.

**Comment by whummer** [comment] 2020-09-15 19:18
Thanks for the update @sahurgithub .

> I've encountered this issue yesterday as well. To me it seems related to the hostname & port mapping. I have the localstack running with docker-compose with docker on Windows (using WSL 2). Another container in the docker-compose connects to localstack using "http://localstack:4566" and can create and use the queues but if I try to do aws --endpoint-url=http://localhost:4567 sqs list-queues from the host machine (notice localhost vs localstack) then I get an empty response.

That sounds like the port may not be exposed in your container..? Can you please share your docker-compose configuration, and also try using the edge port 4566 rather than the deprecated port 4567. Thanks!

**Comment by sahurgithub** [comment] 2020-09-24 23:42
@whummer port 4567 is mapped to 4566. Here's the docker-compose configuration:

```
localstack:
    image: localstack/localstack:0.11.2
    environment:
      - SERVICES=dynamodb,sqs
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4567:4566"
      - "53285:8080"
```

**Comment by whummer** [comment] 2020-09-25 15:53
Thanks @sahurgithub - looks like this could be a region mismatch issue. Can you please share the AWS CLI configuration on your terminal - which value is assigned to `AWS_DEFAULT_REGION` or `AWS_REGION` (or perhaps the region is configured via a local profile)? Please note that the region on the client needs to match the region configured on the server (`DEFAULT_REGION` config value, or `us-east-1` by default). Thanks

**Comment by sahurgithub** [comment] 2020-09-28 00:31
I'm on `eu-west-1` and have tried specifying region in the docker-config but it didn't make any difference. Let me know if you want me to try any specific config values.

**Comment by whummer** [comment] 2021-02-07 18:00
Hi @jonathanroby @chris-crowther @sahurgithub thanks for the update. We have pushed a couple of improvements for SQS and the request routing logic in general, can you please pull the `latest` Docker image and verify whether this problem persists? Thanks for your help.

**Closed** 2021-02-22 20:04 UTC
Labels: evaluate-or-close, needs-triaging, region-issue, should-be-fixed
