### ISSUE TITLE
No logs when using "docker-reuse" as LAMBDA_EXECUTOR

### ISSUE THREAD

**Issue by cabdesigns** [localstack/localstack#826] opened 2018-07-02 20:13 UTC
Firstly, great job on localstack! 👌

Using this product for first time, and making use of "docker-reuse" as the LAMBDA_EXECUTOR, for performance reasons. It's proving difficult to debug the lambda when things go wrong, as seemingly there has been no output.

This [thread](https://github.com/localstack/localstack/issues/117) suggested using plain old `docker logs`, however every time I've done that - the logs appear empty.

Then I realised, the command ran in the above example was nodejs, where as my output displays "/bin/bash". I assume this is a key difference between running with "docker-reuse" and just "docker".

```
CONTAINER ID        IMAGE                           COMMAND                  CREATED                  STATUS                  PORTS                                                                             NAMES
eeee99282d09        lambci/lambda:nodejs8.10        "/bin/bash"              Less than a second ago   Up Less than a second                                                                                     localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_my-test-lambda
```

Changing our setup back to using "docker" as the LAMBDA_EXECUTOR allows us to use `docker logs`.

Is this a bug? If not, should a workaround (if known) be documented?

**Comment by jamespedid** [comment] 2018-12-23 17:49
Is there any known workarounds for this (other than switching the lambda executor back to docker)?

**Comment by foxmulder900** [comment] 2019-01-31 19:19
It looks like if you set `DEBUG=1` on the localstack container itself, and then run `docker logs` on that container, you will see logs from the lambda executors as well.

**Comment by whummer** [comment] 2019-11-24 16:51
Thanks for reporting @cabdesigns @jamespedid @foxmulder900 , this should be fixed in the meantime. Steps to reproduce below.

Terminal 1:
```
LAMBDA_EXECUTOR=docker-reuse DEBUG=1 SERVICES=lambda localstack start
```

Terminal 2:
```
$ echo 'def handler(*args, **kwargs): print("Debug output from Lambda function")' > /tmp/testlambda.py
$ (cd /tmp; zip testlambda.zip testlambda.py)
$ awslocal lambda create-function --function-name func1 --runtime python3.6 --role r1 --handler testlambda.handler --zip-file fileb:///tmp/testlambda.zip
$ awslocal lambda create-event-source-mapping --event-source-arn arn:aws:sqs:us-east-1:000000000000:queue1 --function-name func1
$ awslocal lambda invoke --function-name func1 /tmp/tmp.out

$ stream=$(AWS_DEFAULT_REGION=eu-central-1 awslocal logs describe-log-streams --log-group-name /aws/lambda/func1 | jq -r '.logStreams[0].logStreamName')
$ AWS_DEFAULT_REGION=eu-central-1 awslocal logs get-log-events --log-group-name /aws/lambda/func1 --log-stream-name $stream
{
    "events": [
        {
            "timestamp": 1574613754760,
            "message": "START RequestId: d57ad60e-c525-4b7c-9fa9-f1eefd6b74be Version: $LATEST",
            "ingestionTime": 1574613758384.971
        },
        {
            "timestamp": 1574613755665,
            "message": "Debug output from Lambda function",
            "ingestionTime": 1574613758384.971
        },
        {
            "timestamp": 1574613756570,
            "message": "END RequestId: d57ad60e-c525-4b7c-9fa9-f1eefd6b74be",
            "ingestionTime": 1574613758384.971
        },
        {
            "timestamp": 1574613757475,
            "message": "REPORT RequestId: d57ad60e-c525-4b7c-9fa9-f1eefd6b74be Duration: 52 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 19 MB",
            "ingestionTime": 1574613758384.971
        }
    ],
    "nextForwardToken": "f/00000000000000000000000000000000000000000000000000000000",
    "nextBackwardToken": "b/00000000000000000000000000000000000000000000000000000000"
}
```

Please report here if the problem persists. Thanks

**Closed by whummer** 2019-11-24 16:51 UTC
