### ISSUE TITLE
Lambda invoked subsequent times if it has errors

### ISSUE THREAD

**Issue by cammanderson** [localstack/localstack#817] opened 2018-06-23 00:26 UTC
Hi Guys,

I have an issue that when I invoke a lambda function and it doesn't execute correctly that it is retried 3 additional times. 

I'd expect that if I am writing a lambda function, and for instance throw an error (or use the callback passing it an error) that it would no retry calling the function many times. 

Using docker for running localstack, with the env config; SERVICES: 'lambda,sqs', LAMBDA_EXECUTOR: docker. 

I've had to switch to gadgetjunkie/localstack to be able to use our lambda nodejs environment correctly. Is it possibly related to that fork? I guess I just want to understand - Is it the default behaviour/intention of localstack to call failed lambdas multiple times?

Thanks!
Cam

**Comment by whummer** [comment] 2018-09-03 14:07
Thanks for reporting @cammanderson . How exactly are you calling the Lambda? Is it an asynchronous or synchronous execution? If you're using an SDK like `boto3`, then my assumption would be that the retries are caused by the client itself (`boto3` and other SDKs add retries for most API calls by default). Can you verify whether that's the case?

**Comment by whummer** [comment] 2019-11-18 21:50
Unable to reproduce, closing. Please report here if the problem persists and more details are available. Thanks

**Comment by whummer** [comment] 2019-11-18 21:50
Unable to reproduce, closing. Please report here if the problem persists and more details are available. Thanks

**Closed by whummer** 2019-11-18 21:50 UTC
Labels: question
