### ISSUE TITLE
bug: Array properties aren't handled correctly when Filter Policy Scope is set to MessageBody for SNS subscription

### ISSUE THREAD

**Issue by ABAG603** [localstack/localstack#10567] opened 2024-03-28 13:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Messages are not not being routed to the queues based on the Filter Policy (see steps to reproduce for more details)

### Expected Behavior

Messages are being correctly routed. This is the behaviour when tested against "real" SQS/SNS.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Setup
- SNS topic: topic1
- SQS queues: queue1, queue2

Both queues are being subscribed to the topic1 with **Filter Policy Scope** set to **MessageBody**

Filter policy for **queue1** topic subscription:
```json
{
    "headers": {
      "route-to": ["queue1"]  
    }
}
```
Filter policy for **queue2** topic subscription:
```json
{
    "headers": {
      "route-to": ["queue2"]  
    }
}
``` 

**Scenario 1**
Send message below to the **topic1**
```json
{
    "headers": {
      "route-to": ["queue1"]  
    }
}
```
Expected: message to appear in the **queue1** (this is exactly what is happening in AWS SNS\SQS)
Actual: no messages in the **queue1**

**Scenario 2**
Send message below to the **topic1**
```json
{
    "headers": {
      "route-to": ["queue2"]  
    }
}
```
Expected: message to appear in the **queue2** (this is exactly what is happening in AWS SNS\SQS)
Actual: no messages in the **queue2**

**Scenario 3**
Send message below to the **topic1**
```json
{
    "headers": {
      "route-to": ["queue1", "queue2"]  
    }
}
```
Expected: message to appear in both **queue1** and **queue2** (this is exactly what is happening in AWS SNS\SQS)
Actual: message is neither in **queue1** nor **queue2**

### Environment

```markdown
- OS: Mac OS Sonoma 14.4.1
- LocalStack: 3.2.0
```

**Comment by ABAG603** [comment] 2024-05-03 13:19
Hi @bentsku . It looks like this fix introduced a regression. Now filter policy works only when header is an array. So,

this works - message will be delivered to queue1
```
{
    "headers": {
      "route-to": ["queue1"]  
    }
}
```

this doesn't
```
{
    "headers": {
      "route-to": "queue1"
    }
}
```

I'm testing with LocalStack 3.4.0. I've also tested in AWS and it works in both cases above.

**Comment by bentsku** [comment] 2024-05-03 13:24
Interesting, in the AWS documentation, I don't think I can find any example of a policy setting its value in something else than an array. The example you shared above is the filter policy, did I understood that right?

**Comment by ABAG603** [comment] 2024-05-03 13:34
@bentsku  sorry, now I realize that it was not clear.

So, filter policy is:

```
{
    "headers": {
      "route-to": ["queue1"]  
    }
}
```

If we send this message it **won't** be delivered to queue1 with LocalStack 3.4.0
```
{
    "messageProp1": "value1",
    "messageProp2": "value2",
    "headers": {
      "route-to": **"queue1"**
    }
}
```

this message will be delivered:
```
{
    "messageProp1": "value1",
    "messageProp2": "value2",
    "headers": {
      "route-to": **["queue1"]**
    }
}
```

When tested against AWS both messages are being delivered.

**Comment by bentsku** [comment] 2024-05-03 14:20
Hi @ABAG603, I've just gave it a try with the example you've given and I'm currently unable to reproduce, it works both on AWS and LocalStack. 

This what I'm using, this is a test based on this issue scenario:

```python
filter_policy_1 = {"headers": {"route-to": ["queue1"]}}
sns_create_sqs_subscription_with_filter_policy(
    topic_arn=topic_arn,
    queue_url=queue_url_1,
    filter_scope="MessageBody",
    filter_policy=filter_policy_1,
)

filter_policy_2 = {"headers": {"route-to": ["queue2"]}}
sns_create_sqs_subscription_with_filter_policy(
    topic_arn=topic_arn,
    queue_url=queue_url_2,
    filter_scope="MessageBody",
    filter_policy=filter_policy_2,
)

# publish messages that satisfies the filter policy, assert that messages are received
messages = [
    {"headers": {"route-to": ["queue3"]}},
    {"headers": {"route-to": ["queue1"]}},
    {"headers": {"route-to": "queue1"}},
    {"headers": {"route-to": ["queue2"]}},
    {"headers": {"route-to": "queue2"}},
    {"headers": {"route-to": ["queue1", "queue2"]}},
]
for message in messages:
    aws_client.sns.publish(
        TopicArn=topic_arn,
        Message=json.dumps(message),
    )
```

For Queue 1, I got the following message bodies:
```json
{
  "headers": {
    "route-to": "queue1"
  }
}

{
  "headers": {
    "route-to": [
      "queue1",
      "queue2"
    ]
  }
}

{
  "headers": {
    "route-to": [
      "queue1"
    ]
  }
}
```

And for Queue2:
```json
{
  "headers": {
    "route-to": "queue2"
  }
}

{
  "headers": {
    "route-to": [
      "queue1",
      "queue2"
    ]
  }
}

{
  "headers": {
    "route-to": [
      "queue2"
    ]
  }
}
```

Could you please share a sample which is currently failing against LocalStack? Maybe we do not have the same setup and something is different, but with what is currently provided, I'm not able to reproduce.

**Comment by bentsku** [comment] 2024-05-15 16:23
Hello @ABAG603 and thanks again for the report! #10691 will finally supported the use-case reported here. Once merged, it will close this issue and should be available in the next hour or so after this issue being closed.

**Closed** 2024-05-16 18:18 UTC
Labels: type: bug, aws:sns, status: confirmed
