### ISSUE TITLE
Can't queue multiple messages on SQS

### ISSUE THREAD

**Issue by wcalebgray** [localstack/localstack#1320] opened 2019-05-17 20:23 UTC
First off, I love that something like this exists, so thank you for contributing and making it!

I'm having issues with SQS. I'd like to test that multiple messages are queued successfully by reading the queue after a certain process runs. When I read the queue though, I only see the first message. It seems that localstack is only saving the first message.

Is this supposed to be supported? What else can I provide to help narrow down the issue?

**Comment by ImFlog** [comment] 2019-06-06 17:26
I'm a user of Localstack and I use to push messages from SNS to SQS in localstack.
I've never experienced this issue, could you please provide a code sample with your issue to let me try to reproduce this ?

**Comment by whummer** [comment] 2019-06-19 20:57
After starting LocalStack, the following sequence works for me (assumes you have `awslocal` installed):
```
# create queue
awslocal sqs create-queue --queue-name q1

# put 3 messages
awslocal sqs send-message-batch --queue-url http://localhost:4576/queue/q1 --entries MessageBody=e1,Id=e1 MessageBody=e2,Id=e2
awslocal sqs send-message --queue-url http://localhost:4576/queue/q1 --message-body e3

# retrieve the 3 messages
awslocal sqs receive-message --queue-url http://localhost:4576/queue/q1
awslocal sqs receive-message --queue-url http://localhost:4576/queue/q1
awslocal sqs receive-message --queue-url http://localhost:4576/queue/q1
```

**Comment by duongpv7** [comment] 2020-04-02 02:55
This be fixed in the latest version - an integration test has been added in #2227 to cover this functionality.

**Closed by duongpv7** 2020-04-02 02:55 UTC
Labels: cannot-reproduce, needs-triaging, question
