### ISSUE TITLE
Illegal base64 character - KCL 2.3.4 - Localstack 0.12.8

### ISSUE THREAD

**Issue by HC-gcampelo** [localstack/localstack#3753] opened 2021-03-19 08:48 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
The [Process Real-Time Stock Data Using KPL and KCL Tutorial](https://docs.aws.amazon.com/streams/latest/dev/tutorial-stock-data-kplkcl2.html) was implemented using localstack.

## Expected behavior
Records properly deserialized, consumed and stats printed on the console
...

## Actual behavior
Consumer is failing to get the records:

```
09:36:21.310 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.k.l.d.DynamoDBLeaseCoordinator - With failover time 10000 ms and epsilon 25 ms, LeaseCoordinator will renew leases every 3308 ms, takeleases every 20050 ms, process maximum of 2147483647 leases and steal 1 lease(s) at a time. - MDC[]
09:36:21.321 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.kinesis.coordinator.Scheduler - Initialization attempt 1 - MDC[]
09:36:21.321 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.kinesis.coordinator.Scheduler - Initializing LeaseCoordinator - MDC[]
09:36:22.940 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.k.l.d.DynamoDBLeaseCoordinator - Created new lease table for coordinator with initial read capacity of 10 and write capacity of 10. - MDC[]
09:36:22.982 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.kinesis.coordinator.Scheduler - Syncing Kinesis shard info - MDC[]
09:36:23.248 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.kinesis.coordinator.Scheduler - Starting LeaseCoordinator - MDC[]
09:36:23.289 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.kinesis.coordinator.Scheduler - Initialization complete. Starting worker loop. - MDC[]
09:36:23.334 [] [LeaseCoordinator-0000] INFO  s.a.k.l.dynamodb.DynamoDBLeaseTaker - Worker d2bc1d1b-a45f-4fc7-9805-53291dfc82a6 saw 1 total leases, 1 available leases, 1 workers. Target is 1 leases, I have 0 leases, I will take 1 leases - MDC[]
09:36:23.416 [] [LeaseCoordinator-0000] INFO  s.a.k.l.dynamodb.DynamoDBLeaseTaker - Worker d2bc1d1b-a45f-4fc7-9805-53291dfc82a6 successfully took 1 leases: shardId-000000000000 - MDC[]
09:36:24.338 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.k.r.f.FanOutConsumerRegistration - StreamConsumer not found, need to create it. - MDC[]
09:36:24.370 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.k.r.f.FanOutConsumerRegistration - Waiting for StreamConsumer StockTradesProcessor to have ACTIVE status... - MDC[]
09:36:25.385 [] [com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor.main()] INFO  s.a.kinesis.coordinator.Scheduler - Created new shardConsumer for : ShardInfo(shardId=shardId-000000000000, concurrencyToken=01e0c7cf-77fd-4a9a-8b46-2fc1c76d80cf, parentShardIds=[], checkpoint={SequenceNumber: LATEST,SubsequenceNumber: 0}) - MDC[]
09:36:25.389 [] [ShardRecordProcessor-0000] INFO  s.a.k.l.BlockOnParentShardTask - No need to block on parents [] of shard shardId-000000000000 - MDC[]
09:36:29.524 [] [aws-java-sdk-NettyEventLoop-1-4] WARN  s.a.k.r.f.FanOutRecordsPublisher - shardId-000000000000: [SubscriptionLifetime] - (FanOutRecordsPublisher#errorOccurred) @ 2021-03-19T08:36:28.431088Z id: shardId-000000000000-1 -- CompletionException/SdkClientException/java.lang.IllegalArgumentException: Illegal base64 character 7b. Last successful request details -- request id - UNKNOWN, timestamp - 2021-03-19T08:36:28.431088Z - MDC[]
java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Illegal base64 character 7b
        at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:60)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:85)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:144)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:125)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:104)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$WrappedErrorForwardingResponseHandler.onError(MakeAsyncHttpRequestStage.java:158)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.lambda$notifyError$5(ResponseHandler.java:309)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:181)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:71)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.notifyError(ResponseHandler.java:307)
        at software.amazon.awssdk.http.nio.netty.internal.utils.ExceptionHandlingUtils.tryCatch(ExceptionHandlingUtils.java:42)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:270)
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onNext(ResponseHandler.java:221)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:407)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.channelRead(HandlerPublisher.java:383)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:228)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:199)
        at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:173)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at software.amazon.awssdk.http.nio.netty.internal.LastHttpContentHandler.channelRead(LastHttpContentHandler.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.onDataRead(Http2ToHttpInboundAdapter.java:84)
        at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:49)
        at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:42)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:901)
        at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.fireChildRead(AbstractHttp2StreamChannel.java:555)
        at io.netty.handler.codec.http2.Http2MultiplexHandler.channelRead(Http2MultiplexHandler.java:181)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.http2.Http2FrameCodec.onHttp2Frame(Http2FrameCodec.java:707)
        at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onDataRead(Http2FrameCodec.java:646)
        at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
        at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:318)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:181)
        at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

It looks like a double *decoding from base64* issue.
The records on the stream where checked using awscli, and they seem to be correct (*data* is only encoded once).

# Steps to reproduce
* Checkout the code at https://github.com/HC-gcampelo/KCL2.3-integration, and follow the README or:
* Start localstack: `./start-containers.sh`
* Start the producer: `AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar ENDPOINT_OVERRIDE=http://localhost:4566 CBOR_ENABLED=false ./mvnw exec:java -Dexec.mainClass="com.amazonaws.services.kinesis.samples.stocktrades.writer.StockTradesWriter" -Dexec.args="stocks eu-central-1" &`
* Start the consumer: `AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar ENDPOINT_OVERRIDE=http://localhost:4566 CBOR_ENABLED=false ./mvnw exec:java -Dexec.mainClass="com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor" -Dexec.args="StockTradesProcessor stocks eu-central-1"`

## Command used to start LocalStack
Used localstack docker image with the following configuration:
- SERVICES=kinesis,dynamodb,cloudwatch
- KINESIS_LATENCY=0

**Comment by mgagliardo** [comment] 2021-03-19 09:47
Related to https://github.com/localstack/localstack/pull/3605, I'm going to put a PR to fix this today or reverse it (and take some more time to fix it).

**Comment by HC-gcampelo** [comment] 2021-03-19 10:08
Quick response, thanks @mgagliardo !

**Comment by mgagliardo** [comment] 2021-03-22 01:17
@HC-gcampelo would you please mind in sharing the full code as well as which commands are you running? I was unable to reproduce this and I need to confirm where this is happening. Thanks.

**Comment by HC-gcampelo** [comment] 2021-03-22 08:12
Hi @mgagliardo , it is in the readme of the repository in the ticket description:

full code: https://github.com/HC-gcampelo/KCL2.3-integration

commands: 
* Start localstack:

`./start-containers.sh`

* Run the producer in the background (it logs, so you might want to open a new shell):

`AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar ENDPOINT_OVERRIDE=http://localhost:4566 CBOR_ENABLED=false ./mvnw exec:java -Dexec.mainClass="com.amazonaws.services.kinesis.samples.stocktrades.writer.StockTradesWriter" -Dexec.args="stocks eu-central-1" &`

* Run the consumer:

`AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar ENDPOINT_OVERRIDE=http://localhost:4566 CBOR_ENABLED=false ./mvnw exec:java -Dexec.mainClass="com.amazonaws.services.kinesis.samples.stocktrades.processor.StockTradesProcessor" -Dexec.args="StockTradesProcessor stocks eu-central-1"`

**Comment by HC-gcampelo** [comment] 2021-03-23 07:30
@mgagliardo I just tried it with latest image (`49ad28cafd39`) and getting the same error

**Comment by whummer** [comment] 2021-12-14 22:03
Thanks for providing the detailed example @HC-gcampelo . This appears to be fixed in the meantime - applying the small patch below (to avoid `java.nio.ReadOnlyBufferException`) in your sample we've been able to get this working end-to-end:
```
     private void processRecord(KinesisClientRecord record) {
-        StockTrade trade = StockTrade.fromJsonAsBytes(record.data().array());
+        java.nio.ByteBuffer bb = record.data();
+        byte[] bytes = new byte[bb.remaining()];
+        bb.get(bytes);
+        StockTrade trade = StockTrade.fromJsonAsBytes(bytes);
         if (trade == null) {
```

Are you able to replicate these results with the `latest` Docker image? Please let us know if the problem persists.. Thanks!

**Closed by whummer** 2021-12-14 22:03 UTC
Labels: bug, priority-high, aws:kinesis

**Comment by HC-gcampelo** [comment] 2021-12-20 09:37
Thanks for the update @whummer and sorry for the late response! I'll give it a try!
