### ISSUE TITLE
Using __local__ to create Lambda function does not work.

### ISSUE THREAD

**Issue by seanstaley** [localstack/localstack#3698] opened 2021-03-09 23:45 UTC
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
When attempting to source the source code for a function from a JAR on the file system, I'm running into the following error:
```
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: Unable to extract Java Lambda handler - file is not a valid zip/jar file
```

After adding some log lines to the LocalStack source code, it looks like the LocalStack code in `lambda_api.py` is setting the file name to a temp file instead:
```
/tmp/localstack/app/indexer/latest.jar/original_lambda_archive.zip
```

Here is my Docker Compose configuration:
```
version: '3.8'

services:
  localstack:
    container_name: "localstack_main"
    image: "localstack/localstack:0.12.7"
    networks:
      - localstack_network
    ports:
      - "4566:4566"
    environment:
      SERVICES: "apigateway, dynamodb, dynamodbstreams, iam, lambda, logs, cloudwatch, firehose, s3, sqs, sts"
      DEBUG: "1"
      LAMBDA_EXECUTOR: "docker-reuse"
      LAMBDA_REMOTE_DOCKER: "false"
      DOCKER_HOST: "unix:///var/run/docker.sock"
      HOST_TMP_FOLDER: "/tmp/localstack"
      DEFAULT_REGION: "us-east-1"
      AWS_CBOR_DISABLE: "true"
      USE_SSL: "false"
      AWS_ACCESS_KEY_ID: "accesskey"
      AWS_SECRET_ACCESS_KEY: "secretkey"
      HOSTNAME_EXTERNAL: "localstack"
      LAMBDA_JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:_debug_port_"
      LAMBDA_DOCKER_NETWORK: "localstack_network"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Here are the additional logs I added in:
```
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: code (718)
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: {'S3Bucket': '__local__', 'S3Key': '/tmp/localstack/app/indexer/latest.jar'}
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: lambda_cwd (768)
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: <function set_archive_code at 0x7f9f2f298160>
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: tmp_file (780)
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: /tmp/localstack/app/indexer/latest.jar/original_lambda_archive.zip
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: Going to try and load zip file.
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: None
2021-03-09T23:28:47:INFO:localstack.services.awslambda.lambda_api: Unable to extract Java Lambda handler - file is not a valid zip/jar file
```
...

## Expected behavior
The Lambda function to be created using the path provided in the AWS CLI call, specifically:
```
/tmp/localstack/app/indexer/latest.jar
```

...

## Actual behavior
The application tries to load the JAR file from:
```
/tmp/localstack/app/indexer/latest.jar/original_lambda_archive.zip
```

...

# Steps to reproduce

## Command used to start LocalStack
This is in a docker compose environment, so when the application starts up I simple execute `docker-compose up`.

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
 aws --endpoint-url http://localhost:4566 lambda create-function --function-name myLambda --code S3Bucket="__local__",S3Key="/tmp/localstack/app/indexer/latest.jar" --handler com.app.Handler  --runtime java11 --role 'doesNotMatter'
```
...

**Comment by whummer** [comment] 2021-12-16 22:18
Thanks for reporting @seanstaley , and apologies for the long delay on this one. In the meantime we have added a number of enhancements for the Lambda API, in particular also around local code mounting for Java Lambdas. Closing this as "cannot reproduce" for now - please do keep us posted if the problem persists.. Thanks for your help!

**Closed by whummer** 2021-12-16 22:18 UTC
Labels: bug, java, lambda-execution, docker, aws:lambda
