### ISSUE TITLE
Bootstrapping fails fetching test certs when running behind isolated proxy

### ISSUE THREAD

**Issue by LykinsN** [localstack/localstack#2424] opened 2020-05-13 18:09 UTC
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

We've begun using the latest version of localstack within a Docker container, as part of our CI/CD pipeline, to validate one of our services and its upload/download capabilities from S3, and we're using localstack to mock out that functionality. However, our platform sits behind a proxy that blocks all external traffic, both in and out. This is a problem, as there's a step in the bootstrapping for localstack, where it tries to fetch a set of test SSL certificates from GitHub.com and, as a result, this step always fails.

```
2020-05-13T17:35:25:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
```

We're able to cache those files locally and mount them as a volume in our Docker container, to get past the issue but, even when doing that, the download is still attempted and fails.

I've dug through the documentation and the source but I haven't found an effective workaround or solution, here. Is there an existing configuration item in place to disable this step? And if not, can someone direct me to where this step is initiated? I'd be happy to write up a change myself, to make this step an optional toggle and have it be included as another configuration value. It also seems like a possibility, to have the download step be skipped if an existing set of certificates are already found at that path, and this is also something I could address.

...

## Expected behavior
When starting up localstack, the bootstrapping should complete successfully, including managing any test SSL certificates. I'd expect it to either skip the download step if the files are already there, in `/tmp/localstack` or at least to fail gracefully.

...

## Actual behavior
When run behind our proxy, the test SSL certificate download step fails, as our platform is unable to access GitHub.com.

...

# Steps to reproduce
Start the localstack Docker container when running in an isolated environment that is unable to access the internet.

## Command used to start LocalStack
docker-compose:

```
image: ***..../localstack:0.11.1
volumes:
  - "${PWD}/test:/tmp/localstack"
  - "/var/run/docker.sock:/var/run/docker.sock"
container_name: localstack-s3
ports:
  - 4567-4580:4567-4580
  - 8080:8080
restart: always
environment:
  - SERVICES=s3
  - DEBUG=1
  - AWS_ACCESS_KEY_ID=foobar
  - AWS_SECRET_ACCESS_KEY=foobar
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by paul-ivanassociates** [comment] 2020-06-09 08:17
I have this problem too.  Did you figure out a workaround?  Thanks.

**Comment by loudwinston** [comment] 2020-07-03 00:40
I am also encountering this.  I've tried running with `USE_SSL=0` set explicitly, but still receive the error.

**Comment by LykinsN** [comment] 2020-07-03 00:48
I was able to figure out a solution but this part really caused me some confusion. The dependency featuring the download logic is housed in the `localstack_ext` PyPi package, and the source code for it doesn't seem to be anywhere on GitHub. I had to do a search in the image itself for the error string, and commented out the line responsible for the download. It looks the image already has test SSL scripts cached in place, so it didn't cause any negative impact. 

Once the download step was no longer executing, the image came up as expected. It's been a while since I worked on this so I don't remember the exact path, but a `grep -R` with the above error message should produce the package in question. You'll specifically need to check the PyPi dependencies, though, since it's not featured in the localstack code set. I hope this helps!

**Comment by c-desmarais** [comment] 2020-07-24 14:31
Just another me too. 

**Docker-compose.yml**
`
  localstack:
    image: localstack/localstack:0.11.3
    container_name: awsmock
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
    - ./scripts/local/localstack-config-fixtures:/opt/code/localstack/localstack-config-fixtures
    - ./scripts/local/localstack-init:/docker-entrypoint-initaws.d
    tmpfs:
      - /tmp/localstack:exec,mode=600
`

**Comment by kishaningithub** [comment] 2020-07-26 16:51
the important thing about this problem, localstack waits for like 2 minutes(can be observed from the log timestamps below) because of the timeouts with github. Is there anyway this can be disabled?

**Logs**
```
2020-07-26T16:03:48.973232233Z 2020-07-26 16:03:48,973 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-07-26T16:03:50.923587145Z Running on 0.0.0.0:8081 over https (CTRL + C to quit)
2020-07-26T16:03:52.791404733Z Waiting for all LocalStack services to be ready
2020-07-26T16:03:59.792532991Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:06.793664975Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:13.794810039Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:20.795983995Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:27.797139708Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:34.798253456Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:41.799349266Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:48.800678364Z Waiting for all LocalStack services to be ready
2020-07-26T16:04:55.804514221Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:02.806600880Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:09.809250747Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:16.810530749Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:23.811648127Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:30.812835358Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:37.813989778Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:44.815076895Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:51.816371310Z Waiting for all LocalStack services to be ready
2020-07-26T16:05:58.802974553Z 2020-07-26T16:05:58:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate to /tmp/localstack/server.test.pem: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2180eb00a0>: Failed to establish a new connection: [Errno 110] Operation timed out')) Traceback (most recent call last):
2020-07-26T16:05:58.803015501Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
2020-07-26T16:05:58.803021070Z     conn = connection.create_connection(
2020-07-26T16:05:58.803026737Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
2020-07-26T16:05:58.803031493Z     raise err
2020-07-26T16:05:58.803035557Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
2020-07-26T16:05:58.803040083Z     sock.connect(sa)
2020-07-26T16:05:58.803044177Z TimeoutError: [Errno 110] Operation timed out
2020-07-26T16:05:58.803048233Z 
2020-07-26T16:05:58.803118017Z During handling of the above exception, another exception occurred:
2020-07-26T16:05:58.803124405Z 
2020-07-26T16:05:58.803128341Z Traceback (most recent call last):
2020-07-26T16:05:58.803141882Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
2020-07-26T16:05:58.803147465Z     httplib_response = self._make_request(
2020-07-26T16:05:58.803151680Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
2020-07-26T16:05:58.803156260Z     self._validate_conn(conn)
2020-07-26T16:05:58.803160269Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
2020-07-26T16:05:58.803164889Z     conn.connect()
2020-07-26T16:05:58.803178825Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
2020-07-26T16:05:58.803183185Z     conn = self._new_conn()
2020-07-26T16:05:58.803186930Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
2020-07-26T16:05:58.803191169Z     raise NewConnectionError(
2020-07-26T16:05:58.803194958Z urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2180eb00a0>: Failed to establish a new connection: [Errno 110] Operation timed out
2020-07-26T16:05:58.803199617Z 
2020-07-26T16:05:58.803203225Z During handling of the above exception, another exception occurred:
2020-07-26T16:05:58.803207211Z 
2020-07-26T16:05:58.803264527Z Traceback (most recent call last):
2020-07-26T16:05:58.803270287Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
2020-07-26T16:05:58.803274521Z     resp = conn.urlopen(
2020-07-26T16:05:58.803278159Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
2020-07-26T16:05:58.803282568Z     retries = retries.increment(
2020-07-26T16:05:58.803286571Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
2020-07-26T16:05:58.803290777Z     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2020-07-26T16:05:58.803294791Z urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2180eb00a0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
2020-07-26T16:05:58.803300053Z 
2020-07-26T16:05:58.803303666Z During handling of the above exception, another exception occurred:
2020-07-26T16:05:58.803307535Z 
2020-07-26T16:05:58.803311531Z Traceback (most recent call last):
2020-07-26T16:05:58.803367012Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/install.py", line 66, in setup_ssl_cert
2020-07-26T16:05:58.803372965Z     download(SSL_CERT_URL,target_file)
2020-07-26T16:05:58.803376842Z   File "/opt/code/localstack/localstack/utils/common.py", line 632, in download
2020-07-26T16:05:58.803380921Z     r = s.get(url, stream=True, verify=verify_ssl)
2020-07-26T16:05:58.803384777Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
2020-07-26T16:05:58.803389045Z     return self.request('GET', url, **kwargs)
2020-07-26T16:05:58.803393960Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
2020-07-26T16:05:58.803406323Z     resp = self.send(prep, **send_kwargs)
2020-07-26T16:05:58.803410466Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
2020-07-26T16:05:58.803418894Z     r = adapter.send(request, **kwargs)
2020-07-26T16:05:58.803422821Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
2020-07-26T16:05:58.803427026Z     raise ConnectionError(e, request=request)
2020-07-26T16:05:58.803480792Z requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2180eb00a0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
2020-07-26T16:05:58.803488899Z 
2020-07-26T16:05:58.803492627Z 2020-07-26T16:05:58:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f2181af8d30>
2020-07-26T16:05:58.820509392Z Waiting for all LocalStack services to be ready
2020-07-26T16:06:02.804054725Z 2020-07-26T16:06:02:DEBUG:bootstrap.py: Plugin loading took 134.71786785125732 sec
2020-07-26T16:06:04.804388242Z Starting edge router (https port 80)...
2020-07-26T16:06:05.804551946Z Starting mock KMS service in http ports 80 (recommended) and 4599 (deprecated)...
2020-07-26T16:06:05.804573513Z Starting mock SSM service on http ports 80 (recommended) and 4583 (deprecated)...
2020-07-26T16:06:05.804578398Z [36mINFO[0m[2020-07-26 16:06:04.890] No file found at path /init/seed.yaml; skipping seeding.
2020-07-26T16:06:05.804582924Z [36mINFO[0m[2020-07-26 16:06:04.890] Data will be stored in /tmp/local-kms
2020-07-26T16:06:05.804586093Z [36mINFO[0m[2020-07-26 16:06:04.890] Local KMS started on 0.0.0.0:55685
2020-07-26T16:06:05.804589033Z Running on 0.0.0.0:80 over https (CTRL + C to quit)
2020-07-26T16:06:05.804591903Z Running on 0.0.0.0:4599 over http (CTRL + C to quit)
2020-07-26T16:06:05.804594709Z 2020-07-26T16:06:04:INFO:localstack.multiserver: Starting multi API server process on port 41705
2020-07-26T16:06:05.804597553Z Running on 0.0.0.0:4583 over http (CTRL + C to quit)
2020-07-26T16:06:05.804600205Z Running on 0.0.0.0:41705 over http (CTRL + C to quit)
2020-07-26T16:06:05.821706083Z Waiting for all LocalStack services to be ready
2020-07-26T16:06:06.804751574Z 2020-07-26 16:06:05,886:API:  * Running on http://0.0.0.0:45383/ (Press CTRL+C to quit)
2020-07-26T16:06:06.804777787Z 2020-07-26 16:06:05,886:API:  * Running on http://0.0.0.0:45383/ (Press CTRL+C to quit)
2020-07-26T16:06:06.804783348Z 2020-07-26 16:06:05,886:API:  * Running on http://0.0.0.0:45383/ (Press CTRL+C to quit)
2020-07-26T16:06:11.805180274Z Ready.
```

**compose file**
```
  localstack:
    image: localstack/localstack:0.11.3
    environment:
      - SERVICES=kms,ssm
      - EDGE_PORT=80
      - DEBUG=1
    tmpfs:
      - /tmp/localstack:exec,mode=600
```

**Comment by whummer** [comment] 2020-08-16 08:42
Thanks all for the updates. Please note that the `Unable to download local test SSL certificate` message is an INFO log message - it should not hold up the container startup. (As soon as you see `Ready.` in the output, that should indicate that the services are properly started up and available.)

We have now pushed a change, and in the latest version the certificate download issue should be fixed. @c-desmarais @kishaningithub @LykinsN @loudwinston @paul-ivanassociates  can you please give it a try with the `latest` version of the Docker image and let us know if the problem persists? Thanks!

---
@kishaningithub Based on your logs, I don't think that the failed certificate loading is necessarily the issue in your case. One thing that is a bit concerning is the long time it takes to load the plugins:
```
2020-07-26T16:06:02.804054725Z 2020-07-26T16:06:02:DEBUG:bootstrap.py: Plugin loading took 134.71786785125732 sec
```
Can you please ensure that sufficient resources (CPU/RAM) are allocated to the Docker environment? Thanks

**Closed by whummer** 2020-08-16 08:42 UTC

**Comment by kishaningithub** [comment] 2020-08-20 01:18
@whummer After the 0.11.4 upgrade the problem is solved for me. Attaching my current logs here for closure.

**Logs**
```
2020-08-19T13:30:35.975920468Z Waiting for all LocalStack services to be ready
2020-08-19T13:30:36.375251429Z 2020-08-19 13:30:36,375 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-08-19T13:30:36.378132108Z 2020-08-19 13:30:36,378 INFO supervisord started with pid 13
2020-08-19T13:30:37.381772939Z 2020-08-19 13:30:37,381 INFO spawned: 'dashboard' with pid 19
2020-08-19T13:30:37.383808104Z 2020-08-19 13:30:37,383 INFO spawned: 'infra' with pid 20
2020-08-19T13:30:37.390076166Z 2020-08-19 13:30:37,389 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-08-19T13:30:37.390094810Z 2020-08-19 13:30:37,389 INFO exited: dashboard (exit status 0; expected)
2020-08-19T13:30:37.973900501Z (. .venv/bin/activate; exec bin/localstack start --host)
2020-08-19T13:30:38.974060599Z LocalStack version: 0.11.4
2020-08-19T13:30:38.974084117Z Starting local dev environment. CTRL-C to quit.
2020-08-19T13:30:38.974089531Z !WARNING! - Looks like you have configured $LAMBDA_REMOTE_DOCKER=1 - please make sure to configure $HOST_TMP_FOLDER to point to your host's $TMPDIR
2020-08-19T13:30:38.974094527Z 2020-08-19T13:30:38:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f96a231cc10>
2020-08-19T13:30:38.974100644Z 2020-08-19T13:30:38:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f96a2f3d3a0>
2020-08-19T13:30:38.974106335Z 2020-08-19T13:30:38:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f96a2f3d0d0>
2020-08-19T13:30:39.364465700Z 2020-08-19 13:30:39,364 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-19T13:30:41.974394096Z Starting edge router (https port 80)...
2020-08-19T13:30:41.974425854Z Starting mock DynamoDB service in http ports 80 (recommended) and 4569 (deprecated)...
2020-08-19T13:30:41.974431380Z Starting mock Firehose service on http ports 80 (recommended) and 4573 (deprecated)...
2020-08-19T13:30:41.974435896Z Starting mock KMS service in http ports 80 (recommended) and 4599 (deprecated)...
2020-08-19T13:30:41.974440858Z Starting mock S3 service on http ports 80 (recommended) and 4572 (deprecated)...
2020-08-19T13:30:41.974445324Z [36mINFO[0m[2020-08-19 13:30:41.625] No file found at path /init/seed.yaml; skipping seeding.
2020-08-19T13:30:41.974452740Z [36mINFO[0m[2020-08-19 13:30:41.625] Data will be stored in /tmp/local-kms
2020-08-19T13:30:41.974457232Z [36mINFO[0m[2020-08-19 13:30:41.625] Local KMS started on 0.0.0.0:45825
2020-08-19T13:30:41.974461907Z Initializing DynamoDB Local with the following configuration:
2020-08-19T13:30:41.974466147Z Port:	49865
2020-08-19T13:30:41.974470294Z InMemory:	true
2020-08-19T13:30:41.974485277Z DbPath:	null
2020-08-19T13:30:41.974489507Z SharedDb:	true
2020-08-19T13:30:41.974493517Z shouldDelayTransientStatuses:	false
2020-08-19T13:30:41.974497620Z CorsParams:	*
2020-08-19T13:30:41.974501596Z 
2020-08-19T13:30:41.974595659Z 2020-08-19T13:30:41:INFO:botocore.credentials: Found credentials in environment variables.
2020-08-19T13:30:41.974602570Z 2020-08-19T13:30:41:INFO:botocore.credentials: Found credentials in environment variables.
2020-08-19T13:30:41.974607276Z Running on 0.0.0.0:80 over https (CTRL + C to quit)
2020-08-19T13:30:41.974611381Z Running on 0.0.0.0:4569 over http (CTRL + C to quit)
2020-08-19T13:30:41.974615302Z Running on 0.0.0.0:4599 over http (CTRL + C to quit)
2020-08-19T13:30:41.974619379Z Running on 0.0.0.0:4572 over http (CTRL + C to quit)
2020-08-19T13:30:41.974623682Z 2020-08-19T13:30:41:INFO:localstack.multiserver: Starting multi API server process on port 44235
2020-08-19T13:30:41.974627943Z Running on 0.0.0.0:44235 over http (CTRL + C to quit)
2020-08-19T13:30:42.974882199Z [36mINFO[0m[2020-08-19 13:30:42.589] New key created: arn:aws:kms:us-east-1:000000000000:key/4275c5a6-3ec9-489a-9da5-181a067e6b81
2020-08-19T13:30:42.974912311Z Starting mock SSM service on http ports 80 (recommended) and 4583 (deprecated)...
2020-08-19T13:30:42.974916441Z Running on 0.0.0.0:4583 over http (CTRL + C to quit)
2020-08-19T13:30:42.977300135Z Waiting for all LocalStack services to be ready
2020-08-19T13:30:47.975372968Z 2020-08-19T13:30:47:INFO:botocore.credentials: Found credentials in environment variables.
2020-08-19T13:30:48.975483402Z Ready.
```

**Compose file**
```
  localstack:
    image: localstack/localstack:0.11.4
    environment:
      - SERVICES=kms,ssm,firehose,s3,dynamodb
      - EDGE_PORT=80
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=someAccessKey
      - AWS_SECRET_ACCESS_KEY=someAccessKey
    tmpfs:
      - /tmp/localstack:exec,mode=600
```
