### ISSUE TITLE
cloudwatch list-metrics is broken

### ISSUE THREAD

**Issue by jk2l** [localstack/localstack#606] opened 2018-02-09 01:38 UTC
run "awslocal cloudwatch list-metrics" and the following results returned

Error during pagination: The same next token was received twice: {'NextToken': '\n            96e88479-4662-450b-8a13-239ded6ce9fe\n        '}

**Comment by igor-dmitriev** [comment] 2018-05-16 16:34
got the same error, any updates on this?

**Comment by igor-dmitriev** [comment] 2018-05-20 08:14
I looked under the hood and found a workaround:
```
   @Bean
    public IMetricsFactory metricsFactory() {
        return new CWMetricsFactory(
                cloudWatch(),
                streamName,
                Integer.MAX_VALUE, // this bufferTimeMillis disables logging metrics
                100
        );
    }

 @Bean(initMethod = "run", destroyMethod = "shutdown")
    public Worker worker() {
        return new Worker.Builder()
                .config(kinesisClientLibConfiguration())
                .recordProcessorFactory(iRecordProcessorFactory())
                .kinesisClient(kinesis())
                .dynamoDBClient(dynamoDb())
                .cloudWatchClient(cloudWatch())
                .metricsFactory(metricsFactory())
                .build();
    }
```
so, when I set `bufferTimeMillis` Integer.MAX_VALUE it disables publishing metrics to cloudwatch, cause:
`com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.runOnce:113`:
```
            if (timeSinceFlush >= bufferTimeMillis || queue.size() >= flushSize || shuttingDown) {
                dataToPublish = queue.drain(flushSize);

}

if (dataToPublish != null) {
...
  metricsPublisher.publishMetrics(dataToPublish);
...
}
```

**Comment by whummer** [comment] 2019-11-08 20:13
Thanks for posting the workaround @igor-dmitriev - leaving this issue open for now until this is fixed upstream.

Has anyone been able to raise an upstream issue with `moto`, or ideally contributed a pull request?

**Comment by whummer** [comment] 2020-03-15 11:14
Looks like this has been fixed in the meantime.

```
$ for i in {1..200}; do awslocal cloudwatch put-metric-data --namespace n1 --metric-data 'MetricName=test,Value=123'; done
$ awslocal cloudwatch list-metrics | grep Namespace  | wc -l
      200
```

Please report here if the problem persists. Thanks

**Comment by theomarkkuspaul** [comment] 2020-05-25 04:56
Can confirm the problem is still happening

**Comment by whummer** [comment] 2020-05-25 17:10
Thanks for confirming @theomarkkuspaul . Can you please provide a small, isolated example to help us reproduce this issue? Thanks

**Comment by theomarkkuspaul** [comment] 2020-05-27 02:53
Pretty straightforward to reproduce:

`$ localstack start`

**in a new shell**

`$ awslocal cloudwatch list-metrics`
`=> Error during pagination: The same next token was received twice: {'NextToken': '\n            96e88479-4662-450b-8a13-239ded6ce9fe\n        '}`

Running `$ awslocal --version`
`=> aws-cli/1.18.66 Python/3.5.6 Darwin/18.7.0 botocore/1.16.16`

OS: macOS 10.14.6

**Comment by whummer** [comment] 2020-05-27 17:01
Thanks @theomarkkuspaul . Can you please share the version/age of the Docker image you're using?
```
$ docker images | grep localstack
localstack/localstack                     latest                                           2c48a64937e5        2 days ago          680MB
```
Still unable to reproduce this issue, unfortunately. Does this issue occur on a fresh instance, i.e., if no metrics have been added to CloudWatch yet? Does this issue also persist if you pull the `latest` version of the Docker image?

**Closed** 2020-08-06 21:07 UTC
Labels: bug, upstream-issue
