### ISSUE TITLE
docker-compose up | Exception running proxy on port 8081

### ISSUE THREAD

**Issue by bounteous** [localstack/localstack#1607] opened 2019-09-30 09:13 UTC
```
docker -v
```
root@manjaro Docker version 19.03.1-ce, build 74b1e89e8a
```
docker-compose -v
```
root@manjaro docker-compose version 1.24.1, build unknown
```
uname -r
```
root@manjaro 5.2.11-1-MANJARO
```bash
aa-enabled
```
root@manjaro No - disabled at boot.
```bash
cat docker-compose.yml
```
```bash
version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=./data
    volumes:
      - './.localstack:/tmp/localstack'
```
```bash
docker-compose up
```

![image](https://user-images.githubusercontent.com/16175933/65864425-251dd600-e372-11e9-96eb-97100840bba1.png)

**Comment by whummer** [comment] 2019-10-05 19:03
Thanks for reporting this issue @bounteous . This issue should be fixed in #1626 - can you please give it a try with the latest version of the Docker image?

**Comment by bounteous** [comment] 2019-10-16 14:27
```
docker-compose pull localstack
```
```
docker-compose up --force-recreate 
```

Still the same error.

**Comment by whummer** [comment] 2020-01-18 13:39
Following up on this issue one more time @bounteous . I was able to reproduce this issue by running this:
```
sudo chown -R root .localstack/
sudo chmod -R 600 .localstack/
```
However, the `latest` version of the Docker image seems to be able to deal with file permission issues:
```
localstack_demo | 2020-01-18T13:35:06:INFO:localstack.utils.common: Unable to store certificate file under /tmp/localstack/server.test.pem, using tmp file instead: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'
```
Closing this issue - please report here with more details if the problem persists. Thanks!

**Closed by whummer** 2020-01-18 13:39 UTC
Labels: bug, installation
