### ISSUE TITLE
bug: AppSync InternalError (Unable to find operation for request to service appsync)

### ISSUE THREAD

**Issue by sc0ttdav3y** [localstack/localstack#8655] opened 2023-07-08 03:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm new to LocalStack and am on the latest version. I have a basic serverless config with AppSync and a basic query and HTTP resolver.  It deploys okay, but when I hit the endpoint I get an internal error response as follows.

```json
{
  "__type": "InternalError",
  "message": "exception while calling appsync with unknown operation: Traceback...*snipped, see below*"
}
```

I can manually connect to the resolver via `wget` from the `localstack-main` docker container.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

### Anything else?

In the debug logs I see the following (includes the traceback from the above message):

```
2023-07-08T03:08:02.951 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py", line 557, in parse
operation, uri_params = self._operation_router.match(request)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/op_router.py", line 317, in match
rule, args = matcher.match(path, method=method, return_rule=True)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 655, in match
raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
handler(self, self.context, response)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 64, in __call__
return self.parse_and_enrich(context)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
operation, instance = parser.parse(context.request)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py", line 172, in wrapper
return func(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py", line 559, in parse
raise OperationNotFoundParserError(
localstack.aws.protocol.parser.OperationNotFoundParserError: Unable to find operation for request to service appsync: POST /graphql
2023-07-08T03:08:02.952  INFO --- [   asgi_gw_0] localstack.request.http    : POST /graphql => 500

```

It seems to

**Comment by bentsku** [comment] 2023-07-08 21:45
Closing as it's a duplicate of #8656

**Closed by bentsku** 2023-07-08 21:45 UTC
Labels: type: bug, status: triage needed
