### ISSUE TITLE
Bad Gateway error after many S3 requests

### ISSUE THREAD

**Issue by indiejames** [localstack/localstack#994] opened 2018-10-31 15:31 UTC
I am running a suite of tests that read from and write to S3 and I find that after a few test cases I get a 502 Bad Gateway error from localstack. It's not any particular test cases as a I can change the cases that are run and it still happens. It seems to be the number of tests that matter. 

I'm running localstack (latest) via docker-compose and I have debug logging enabled. The output is as follows:

> localstack_1  | Killed
localstack_1  | 2018-10-31T15:23:55:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection broken: IncompleteRead(152616960 bytes read, 55322560 more expected)', IncompleteRead(152616960 bytes read, 55322560 more expected)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 204, in forward
localstack_1  |     response._content = response.raw.read()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/urllib3/response.py", line 401, in read
localstack_1  |     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
localstack_1  |   File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
localstack_1  |     self.gen.throw(type, value, traceback)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/urllib3/response.py", line 320, in _error_catcher
localstack_1  |     raise ProtocolError('Connection broken: %r' % e, e)
localstack_1  | ProtocolError: ('Connection broken: IncompleteRead(152616960 bytes read, 55322560 more expected)', IncompleteRead(152616960 bytes read, 55322560 more expected))
localstack_1  |
localstack_1  | 2018-10-31T15:23:55:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /gitc-test-bucket/file-staging/mystack/Landsat_WELD/WELD_CR321_GA_LL2010335.tif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fe7f34310>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
localstack_1  |     return request('get', url, params=params, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /gitc-test-bucket/file-staging/mystack/Landsat_WELD/WELD_CR321_GA_LL2010335.tif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fe7f34310>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  |
localstack_1  | 2018-10-31T15:23:55:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /gitc-test-bucket/file-staging/mystack/Landsat_WELD/WELD_CR321_GA_LL2010335.tif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fe7f64890>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
localstack_1  |     return request('get', url, params=params, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /gitc-test-bucket/file-staging/mystack/Landsat_WELD/WELD_CR321_GA_LL2010335.tif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fe7f64890>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  |
localstack_1  | 2018-10-31T15:23:55:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /gitc-test-bucket/file-staging/mystack/Landsat_WELD/WELD_CR321_GA_LL2010335.tif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fe7f646d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
localstack_1  |     return request('get', url, params=params, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /gitc-test-bucket/file-staging/mystack/Landsat_WELD/WELD_CR321_GA_LL2010335.tif (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9fe7f646d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by palidanx** [comment] 2018-11-09 21:35
I get similar behavior when doing

```
aws --endpoint-url=http://localhost:4572 s3 sync . s3://mybucket --acl public-read
```

In a folder of CSV files about 300 megs each (about 2 gigs total).

It starts failing with:
Part operation (reached max retries: 4): Bad Gateway
upload failed: file.csv to s3://mybucket/file.csv An error occurred (502) when calling the CreateMultipartUpload operation (reached max retries: 4): Bad Gateway
Completed 1.5 GiB/2.3 GiB (4.9 MiB/s) with 13 file(s) remaining

**Comment by palidanx** [comment] 2018-11-11 22:48
Actually I was able to solve it by increasing the memory allocation of the docker image.

**Comment by whummer** [comment] 2019-11-30 19:46
Thanks for reporting @indiejames , and thanks for providing a solution/workaround @palidanx. Closing this issue - please report here if the problem persists. Thanks

**Closed by whummer** 2019-11-30 19:46 UTC

**Comment by hakanilter** [comment] 2020-02-18 16:51
I'm having the same problem. First I tried to upload 1.7G file, then I split it into 100 files (17mb each). It never works even I increase the memory limit for the container.

**Comment by delijati** [comment] 2020-03-04 23:01
> Actually I was able to solve it by increasing the memory allocation of the docker image.

can you give me here an example ?

**Comment by etwillbefine** [comment] 2020-03-12 14:44
In my case it was related to a different S3 port being used as default then the one mentioned in the README of localstack. Related to https://gitlab.com/gitlab-org/gitlab-runner/issues/16946

<details>
<summary>localstack error during S3 request</summary>

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /a-real-test-state-bucket (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c1d62a850>: Failed to establish a new connection: [Errno 111] Connection refused'))
</details>

**Comment by delijati** [comment] 2020-03-16 11:00
ohh boy i also had to remove setting the port to get it working ... @etwillbefine thanks a lot
