### ISSUE TITLE
Multipart upload stram faling, "Your proposed upload is smaller than the minimum allowed size happeining for S3 service"

### ISSUE THREAD

**Issue by medimohammadise** [localstack/localstack#1404] opened 2019-06-28 15:45 UTC
I am uploading a inputfilestream  more than 5MB. It is working well with Amazon S3 service but it is failing with localStack. Any suggestion?

**Comment by whummer** [comment] 2020-04-27 23:26
Thanks for reporting @medimohammadise . We weren't able to reproduce this issue, due to a lack of specific steps or a concrete example to reproduce it. Closing this issue, but please report here if the problem persists - if you can help us create a small example we'll be happy to look into this. Thanks!

**Closed by whummer** 2020-04-27 23:26 UTC
