### ISSUE TITLE
bug: API Gateway V1 (targeted to Lambda) gives 500 error with // in path

### ISSUE THREAD

**Issue by northvankiwiguy** [localstack/localstack#11253] opened 2024-07-23 18:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With API Gateway V1, I have a `/orders` path that targets a Lambda function. When accessing the URL using the syntax:

`curl -v https://45szzn0od7.execute-api.localhost.localstack.cloud:4566/prod/orders` I see the correct response.
    
However, if there's an extra `/` in the path after `/prod` I see a 500 response:

`curl -v https://45szzn0od7.execute-api.localhost.localstack.cloud:4566/prod//orders`

I see the response message:

```
"__type": "InternalError", "message": "exception while calling apigateway with unknown operation: 308 Permanent Redirect: http://45szzn0od7.execute-api.localhost.localstack.cloud:4566/prod/orders"
```

I keep on hitting this bug because I have `API_URL` set to the base URL, and then call `$API_URL/orders`. If the `API_URL` contains a trailing `/`, it crashes.

I'm not sure if the Lambda integration is relevant or not (or whether other integrations will also see the problem). I can confirm that my Lambda function is _not_ invoked when `/prod//orders` is used.

### Expected Behavior

In the AWS service, both of these work correctly, regardless of whether the path is `/prod/orders` or `/prod//orders`.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-composed up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

API Gateway V1 created with CDK

```
const api = new apigateway.RestApi(this, 'example-api')
const ordersApi = api.root.addResource('orders')
const ordersLambdaInt = new apigateway.LambdaIntegration(orderLambda, { proxy: true })
ordersApi.addMethod('GET', ordersLambdaInt)
```    

I don't have the `awslocal` commands on hand, but I can figure them out if necessary.

### Environment

```markdown
- OS: MacOS Sonoma 4.5
- LocalStack: 
  LocalStack version: 3.5.1.dev
  LocalStack Docker image sha: (built from latest source)
  LocalStack build date: 2024-07-23
  LocalStack build git hash: a0a1ba090
```

**Comment by northvankiwiguy** [comment] 2024-08-02 18:25
Thanks for looking into this. Unfortunately, it's still failing, but with a different error:

```
% curl https://fhqrncbobi.execute-api.localhost.localstack.cloud:4566/prod//orders 
{"Type": "User", "message": "Unable to find path /prod//orders", "__type": "NotFoundException"}
```

and on the LocalStack log I see:

```
2024-08-02T11:22:49.052 DEBUG --- [et.reactor-5] l.s.apigateway.helpers     : No match found for path: '//orders' and method: 'GET'
2024-08-02T11:22:49.052  INFO --- [et.reactor-5] localstack.request.http    : GET /prod//orders => 404
``` 

Likely failing in a different place now?

**Comment by northvankiwiguy** [comment] 2024-08-02 20:35
@bentsku, I can't find a way to re-open this issue, but hopefully you'll see my comment anyway.

**Comment by bentsku** [comment] 2024-08-02 23:12
Thanks @northvankiwiguy, I'll open a PR fixing the issue shortly. It seems the fixed issue is only working when the only resource path is `{proxy+}` and not a hardcoded value. I'll link the PR again to the issue, thanks a lot for the report!

**Comment by bentsku** [comment] 2024-08-02 23:39
In the meantime, it seems the issue is already fixed with our newest implementation of the invocation logic for API Gateway REST APIs. If you're not a Pro user, could you give it a try by starting LocalStack with `PROVIDER_OVERRIDE_APIGATEWAY=next_gen`? It should fix your issue and bring a lot more parity to AWS. 
This new implementation will become default before the next major release of LocalStack, as we're putting a lot of effort to make LocalStack API Gateway much closer to AWS. 

I'll still work on a fix, but you should be able to already use it now. 
Feel free if you have any feedback about the new implementation!

**Comment by northvankiwiguy** [comment] 2024-08-03 03:36
Hi there... I gave it a try, and I see this error:

```
API for service 'apigateway' not yet implemented or pro feature
```

Your message said "If you're _not_ a Pro user", and I'm _not_ a Pro user, so should I expect this to work? If necessary, I'm happy to debug this more, since I'd prefer to use the newer version if it's going to become the default.

**Comment by bentsku** [comment] 2024-08-03 17:53
Yes, it is supposed to work. It also works for Pro users, but currently they would lose features as not everything as been implemented. But for the regular `localstack/localstack` image, all features have been rewritten so it is ready for use.

This error message indicates an issue with loading the new implementation: either the image used does not have the new implementation as it would be too old, or a typo in the configuration.

I've just gave it a try with the following `docker-compose.yml` file after running `docker pull localstack/localstack:latest`:
```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PROVIDER_OVERRIDE_APIGATEWAY=next_gen
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

And with the `DEBUG` flag set to `1`, I could see the following lines after running the following command: `awslocal apigateway get-rest-apis`
```
localstack-main  | 2024-08-03T17:49:25.921 DEBUG --- [et.reactor-0] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.aws.provider.apigateway:next_gen = <function apigateway_next_gen at 0xffff7a5931a0>)
localstack-main  | 2024-08-03T17:49:25.921 DEBUG --- [et.reactor-0] plux.runtime.manager       : loading plugin localstack.aws.provider:apigateway:next_gen
localstack-main  | 2024-08-03T17:49:25.980 DEBUG --- [et.reactor-0] l.s.a.n.execute_api.router : Registering API Gateway routes.
localstack-main  | 2024-08-03T17:49:28.139  INFO --- [et.reactor-0] localstack.request.aws     : AWS apigateway.GetRestApis => 200
```

**Closed** 2024-08-05 09:32 UTC
Labels: type: bug, aws:apigateway, status: in progress

**Comment by bentsku** [comment] 2024-08-05 12:45
Hello @northvankiwiguy, the issue has been closed automatically as the fix for the current version has been merged, but we can continue discussing here to make the `next_gen` version work for you

**Comment by northvankiwiguy** [comment] 2024-08-06 13:31
Thanks, I've tried it again and the bug is now fixed in the current version.

I also tried the `next_gen` solution, and it also works now. I'm not sure if I simply typed the wrong thing, or if my source tree was slightly out of date (I updated it in the middle of last week), but now it works fine with the latest updates.

One observation is that my X-Ray trace ID isn't getting passed correctly from my test client -> API Gateway -> Lambda. Does the Next Gen API Gateway support this? (the current version definitely doesn't). I also know that Lambda doesn't support this properly (it overwrites it), so there might be a problem in two places.

Thanks!

**Comment by bentsku** [comment] 2024-08-06 13:48
Awesome, I'm glad to hear it's correctly working! 

Regarding the trace ID and X-Ray, both versions currently do not support it. It is currently only mocked, sorry.

There are plans to improve X-Ray integration over multiple services in LocalStack,  but X-Ray is part of our Pro offering. Still, this should improve the traceID being passed around. I can't really commit to a date, but it is part of our roadmap.

**Comment by northvankiwiguy** [comment] 2024-08-06 14:01
Thanks. Will there be any concern if I added X-Ray support to the community version by myself, and submit the changes? I need it for a project I'm working on, and it doesn't seem too hard to add.

**Comment by northvankiwiguy** [comment] 2024-08-06 16:35
Just to clarify, I'm only interested in Passive X-Ray Tracing (where the `X-Amzn-Trace-Id` header is provided, and passed along), and I'm not planning to add Active Tracing. I certainly don't want to implement the X-Ray console ;-)

**Comment by bentsku** [comment] 2024-08-07 13:19
Sorry for the delay! 

No, feel free to contribute, hopefully the new implementation is simpler to understand and get started with! I believe currently we don't keep the trace id from the beginning, so some changes are required, but it should be doable 😄 

Feel free to ping me if you need any help! I could quickly have a look today at it if you'd like, I could try to add it too.
