### ISSUE TITLE
[Bug Report] Cannot get Cognito service to start

### ISSUE THREAD

**Issue by Vaunorage** [localstack/localstack#2677] opened 2020-07-05 19:49 UTC
#  Detailed description
When trying to run cognito service, it does not  want to start along with the other services. 

## Actual behavior
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e SERVICES="edge,cognito,dynamodb" -p 4566:4566 --rm --privileged --name localstack_main -p 4569:4569 -p 4590-4591:4590-4591 -p 8080-8081:8080-8081  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
Waiting for all LocalStack services to be ready
2020-07-05 19:43:09,129 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-07-05 19:43:09,134 INFO supervisord started with pid 14
2020-07-05 19:43:10,143 INFO spawned: 'dashboard' with pid 20
2020-07-05 19:43:10,147 INFO spawned: 'infra' with pid 21
2020-07-05 19:43:10,174 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.3
2020-07-05 19:43:11,192 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
2020-07-05T19:43:16:INFO:localstack.utils.common: Error storing key/cert SSL files (falling back to random tmp file names): [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
Running on 0.0.0.0:8081 over https (CTRL + C to quit)
Starting edge router (https port 4566)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready

![image](https://user-images.githubusercontent.com/10731763/86540984-0b985480-bed7-11ea-9650-9d62dfa33ed9.png)

# Steps to reproduce

## Command used to start LocalStack

docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e SERVICES="edge,cognito,dynamodb" -p 4566:4566 --rm --privileged --name localstack_main -p 4569:4569 -p 4590-4591:4590-4591 -p 8080-8081:8080-8081  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"

**Comment by Vaunorage** [comment] 2020-07-05 20:16
When I set my localstack key for the pro version, I get an interface setting error 

> export LOCALSTACK_API_KEY=...
> export SERVICES=edge,cognito,dynamodb
> localstack start

LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
2020-07-05T15:54:19:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Found network interface br-18b44471095f with address 172.18.0.1
Running command: sudo ifconfig br-18b44471095f:0 0.0.0.0 netmask 255.255.255.0 up
Unable to create forward proxy on interface br-18b44471095f, address 0.0.0.0: Command 'sudo ifconfig br-18b44471095f:0 0.0.0.0 netmask 255.255.255.0 up' returned non-zero exit status 1.
Found network interface docker0 with address 172.17.0.1
Running command: sudo ifconfig docker0:0 0.0.0.0 netmask 255.255.255.0 up
Unable to create forward proxy on interface docker0, address 0.0.0.0: Command 'sudo ifconfig docker0:0 0.0.0.0 netmask 255.255.255.0 up' returned non-zero exit status 255.
Found network interface ens33 with address 192.168.32.111
Running command: sudo ifconfig ens33:0 0.0.0.0 netmask 255.255.255.0 up
Unable to create forward proxy on interface ens33, address 0.0.0.0: Command 'sudo ifconfig ens33:0 0.0.0.0 netmask 255.255.255.0 up' returned non-zero exit status 255.
Found network interface lo with address 127.0.0.1
Unable to create forward proxy on interface lo, address 0.0.0.0: 
docker run -it -e SERVICES="edge,cognito,dynamodb" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_API_KEY="srcx3NA47Y" -p 0.0.0.0:53:53 -p 0.0.0.0:53:53/udp -p 443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 4569:4569 -p 4590-4591:4590-4591 -p 8080-8081:8080-8081  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
docker: Error response from daemon: driver failed programming external connectivity on endpoint localstack_main (d9243912b85b164014b1c01e5ee930c8107b5a01f470bad47be771b68a387970): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.

**Comment by whummer** [comment] 2020-07-05 22:58
Thanks for reporting @Vaunorage . Looks like port 53 is already occupied (which is used to start a DNS server in LocalStack Pro) - can you please try setting the `DNS_ADDRESS=0` environment variable in your Docker configuration? Hope that helps - please keep us posted. Thanks!

**Comment by Vaunorage** [comment] 2020-07-06 02:52
Hi !

It did not help a lot ...

> docker run -it -e SERVICES="edge,cognito,dynamodb" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_API_KEY="srcx3NA47Y" -p 0.0.0.0:53:53 -p 0.0.0.0:53:53/udp -p 443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 4569:4569 -p 4590-4591:4590-4591 -p 8080-8081:8080-8081 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" -e DNS_ADDRESS=0

result : 
docker: Error response from daemon: driver failed programming external connectivity on endpoint localstack_main (5935b364a8e5b03d067474f4a0f4e8b66aec7b119eec81447e07df5c987a2087): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.

**Comment by whummer** [comment] 2020-07-06 05:52
Thanks for the update. Sorry, should have made myself more clear. The environment variable should be set in the terminal session that is running `localstack start` (which should then adapt the port configuration accordingly). If you are running the `docker run ...` command directly, you could try removing the `-p 0.0.0.0:53:53 -p 0.0.0.0:53:53/udp` flags (or change them to `-p 168.0.x.x:53:53 -p 168.0.x.x:53:53/udp` where `168.0.x.x` is some exemplary local IP address that allows to bind to port 53). Thanks

**Comment by Vaunorage** [comment] 2020-07-06 06:40
Hi ! 

Thanks for the response. I am sorry for the misunderstanding. It actually kinda worked but I got a new networking error

> export LOCALSTACK_API_KEY=...
> export SERVICES=edge,cognito,dynamodb
> export DNS_ADDRESS=0
> localstack start

LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
2020-07-06T02:32:38:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="000000000000" -e DNS_ADDRESS="0" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_API_KEY="..." -e SERVICES="edge,cognito,dynamodb"  -p 443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 4569:4569 -p 4590-4591:4590-4591 -p 8080-8081:8080-8081  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
Waiting for all LocalStack services to be ready
2020-07-06 06:32:47,839 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-07-06 06:32:47,866 INFO supervisord started with pid 13
2020-07-06 06:32:48,878 INFO spawned: 'dashboard' with pid 19
2020-07-06 06:32:48,889 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-07-06 06:32:49,064 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-07-06 06:32:50,073 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
LocalStack version: 0.11.3
LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
2020-07-06T06:33:12:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate to /tmp/localstack/server.test.pem: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f215948d100>: Failed to establish a new connection: [Errno -3] Try again')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f215948d100>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f215948d100>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/install.py", line 66, in setup_ssl_cert
    download(SSL_CERT_URL,target_file)
  File "/opt/code/localstack/localstack/utils/common.py", line 636, in download
    r = s.get(url, stream=True, verify=verify_ssl)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f215948d100>: Failed to establish a new connection: [Errno -3] Try again'))

2020-07-06T06:33:18:INFO:localstack.utils.common: Unable to store certificate file under /tmp/localstack/server.test.pem, using tmp file instead: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'
Running on 0.0.0.0:8081 over https (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready.

**Comment by whummer** [comment] 2020-07-07 23:05
Thanks for the update @Vaunorage . The `ConnectionError` you're seeing looks like a duplicate of #2424 . This is only an `INFO` log message, though, which should not have an impact on the functionality per se (as we're using a fallback to use a self-signed certificate if the cert file cannot be downloaded). Looks like this could potentially be an issue with your API key - would you mind getting touch with us via email (or Slack) directly? Many thanks!

**Closed** 2020-07-25 00:20 UTC
Labels: PRO, installation, priority-high, usage
