### ISSUE TITLE
Localstack and AWS SQS receive message with boto3 returns different message formats

### ISSUE THREAD

**Issue by Kyrrui** [localstack/localstack#1786] opened 2019-11-21 21:00 UTC
I'm having an issue (using boto3, python, and localstack) where the message format is different between localstack and AWS's message format. I was wondering if I'm overlooking something, I really would prefer to avoid having two different sets of message parsing logic for my SQS consumer.

Here is how I am publishing to my SNS topic, which then pushes the message into an SQS Queue
https://i.stack.imgur.com/6kbec.png

Here is how the message is being received differently from the sqs queue
https://i.stack.imgur.com/BeRPE.jpg

**Comment by whummer** [comment] 2019-11-24 13:55
Thanks for reporting @Kyrrui . Can you please provide some details about your SQS consumer - specifically, the SNS `subscribe` API call done to your code?

Following [this AWS document](https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html), it seems that the entire JSON message is sent as payload:
```
The Amazon SQS message will look similar to the following JSON document. 
...
```

Is your client by any chance using `RawMessageDelivery`? Quoting from [this AWS document](https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html):
```
When you enable raw message delivery for an Amazon SQS endpoint, any Amazon SNS metadata is stripped from the published message and the message is sent as is.
```
... Which seems to be what you're expecting to see in your case, right?

**Comment by Kyrrui** [comment] 2019-11-25 16:04
@whummer Thanks for getting back to me! So RawMesssageDelivery is enabled on my AWS console, this is the message type I'm expecting to see when using localstack. The RawMessageDelivery option seems to be enabled by default when I created the subscription on AWS.

I created a quick small contained example using localstack to test vs my AWS services:

Localstack commands:
`localstack start`
`aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name reggora-events`
`aws --endpoint-url=http://localhost:4575 sns create-topic --name reggora-topic`
`aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:reggora-topic --protocol sqs --notification-endpoint arn:aws:sns:us-east-1:000000000000:reggora-events`
`aws --endpoint-url=http://localhost:4575 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:reggora-topic --message tacoPurchased`
`aws --endpoint-url=http://localhost:4576 sqs receive-message --queue-url http://localhost:4576/queue/reggora-events`

Response:

> {
    "Messages": [
        {
            "Body": "{\"MessageId\": \"5a59a4a0-b092-413a-b2ac-9838d3662cb4\", \"Type\": \"Notification\", \"Timestamp\": \"2019-11-25T15:39:20.758172Z\", \"Message\": \"tacoPurchased\", \"TopicArn\": \"arn:aws:sns:us-east-1:000000000000:reggora-topic\"}", 
            "ReceiptHandle": "5ea0290f-54cc-4184-9e07-d3b961ebf09a#4b7d6509-9cfb-482a-830d-49193fa0ef16", 
            "MD5OfBody": "bf4a1cba61323167a663463dd4b9af38", 
            "MessageId": "5ea0290f-54cc-4184-9e07-d3b961ebf09a"
        }
    ]
}


Using my AWS servicews:
`aws --region us-east-1  sns publish --topic-arn MY-AWS-ARN --message tacoPurchased`
`aws --region us-east-1 sqs receive-message --queue-url MY-SQS-URL`

Response:

> {
    "Messages": [
        {
            "Body": "tacoPurchased", 
            "ReceiptHandle": "AQEB0D0zJELRT/0pOLQLpGGBAxTkqEy7RjLVuP3XDT0khP3cBcj3ASj9wLeZJyW614mVVqCA0VUo8lsKbEFe5B9h5XH1c4OXpSVTlt6HNlruI3a8g5doY3uhUx+qMbwJkPjUuZeauff2WB2kW/RsA3KFR1Xmjy9mt73v/lkMpaaLhGW0YX+NvD4J0W7dPC08bf24HUBgqgBP5/GmD7EOEbzpuOgBw7yrfb4Ojt5NZJRW0cRwF5b4PvVFHQKGGTNWEXMLBbSUuoPHASYTF9SXluh34In3Q+qffytKWR8/HhNuHXBvbmCLikJH7j2YeAT3wUbSjnN33sjwqFpT72gvcpwLHvK9WyzSzkaF6KZb/gXX4aJlfcnRXocmR8ByRJInuUaI1Etihu82yQVNpiwGrOzJWQ==", 
            "MD5OfBody": "73c55f302c823ea1e6ec824b3b95eb7b", 
            "MessageId": "29295347-0be1-4170-a246-859e2fab4ce8"
        }
    ]
}

**Comment by whummer** [comment] 2020-01-18 16:19
Thanks for providing the detailed example @Kyrrui . 

I was able to get the expected output by slightly modifying your subscribe command (appending `RawMessageDelivery=true`):
```
aws --endpoint-url=http://localhost:4575 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:reggora-topic --protocol sqs --notification-endpoint arn:aws:sns:us-east-1:000000000000:reggora-events --attributes RawMessageDelivery=true 
```
The `receive-message` command then yields this output for me:
```
{
    "Messages": [
        {
            "MessageId": "1dcd34e9-06ff-42e8-b6a5-aea06e8a83a0",
            "ReceiptHandle": "1dcd34e9-06ff-42e8-b6a5-aea06e8a83a0#46fad183-8bb6-47c4-a54c-aa49b98af841",
            "MD5OfBody": "73c55f302c823ea1e6ec824b3b95eb7b",
            "Body": "tacoPurchased"
        }
    ]
}
```

Raw message delivery seems to be disabled by default, so it makes sense that it has to be specified explicitly with the subscription. My assumption would be that you've created your subscription with raw message delivery enabled.

From the AWS CLI:
```
$ awslocal sns subscribe help
...
          o RawMessageDelivery  When set to true , enables raw message  deliv-
            ery  to  Amazon  SQS or HTTP/S endpoints. This eliminates the need
            for the endpoints to process JSON formatting, which  is  otherwise
            created for Amazon SNS metadata.
```

Closing this issue, as it seems that the behavior of LocalStack is correct in this case. If you still believe that the behavior is inconsistent with AWS, please follow up here with more details to reproduce. Thanks!

**Closed by whummer** 2020-01-18 16:19 UTC
Labels: diverges-from-aws, needs-triaging
