### ISSUE TITLE
bug: get-object-attributes does not return requested -object-attributes

### ISSUE THREAD

**Issue by teimatinimarin** [localstack/localstack#6217] opened 2022-06-06 16:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

awslocal s3api get-object-attributes --bucket localbucket --key raw/localbucket/2022/06/04/141730/object2.txt --object-attributes "StorageClass" "ETag" "ObjectSize"
{
    "LastModified": "2022-06-04T19:49:09+00:00",
    "VersionId": "null"
}

### Expected Behavior

aws --profile xx s3api get-object-attributes --bucket xxxxx-bucket --key raw/localbucket/2022/06/04/141730/object1.txt --object-attributes "StorageClass" "ETag" "ObjectSize"
{
    "LastModified": "2022-06-04T19:29:58+00:00",
    "ETag": "fa6d82afd1ba8116fd66ceeec0b0f6b9",
    "StorageClass": "STANDARD",
    "ObjectSize": 45
}

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

SERVICES="s3" localstack start

### Environment

```markdown
- OS: MacIS Monterey
- LocalStack: 0.14.4.dev
- LocalStack CLI: LocalStack CLI 0.14.3.2
```

**Comment by bentsku** [comment] 2022-12-08 15:32
Hello and thanks for your report.

  We have been working on a new implementation of S3, and it is now available under a feature flag. Could you try pulling the latest Docker image (`localstack/localstack:1.3` or `latest`) and set the environment variable `PROVIDER_OVERRIDE_S3=“asf”`? It should normally be fixed and we have tests covering your use case. 
  
  In case you have not upgraded to a version above v1 yet, here the migration guide to help: https://discuss.localstack.cloud/t/migrating-to-localstack-v1-0/58

Thanks a lot for your feedback! 

_Note: if you are a Pro user, you should set the flag to `“asf_pro”` instead of `“asf”`._

**Comment by bentsku** [comment] 2022-12-30 14:45
Hello! As it's been 3 weeks and the issue is not reproducible anymore with the solution above and is covered by an integration test, I'll close the issue. If you still encounter this issue, don't hesitate to comment again and I'll reopen!

Thanks again for your report!

**Closed by bentsku** 2022-12-30 14:45 UTC
Labels: type: bug, status: resolved/fixed, status: response required, aws:s3
