### ISSUE TITLE
ERROR: java.util.LinkedHashMap cannot be cast to APIGatewayProxyRequestEvent

### ISSUE THREAD

**Issue by fuzzy28** [localstack/localstack#4799] opened 2021-10-27 15:16 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Unfortunately, the issue exists in the current docker build

```
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: . Output:
Exception in thread "main" java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent is in unnamed module of loader 'app')
        at com.fitness.society.users.handlers.UserRegistrationAPIGatewayHandler.handleRequest(UserRegistrationAPIGatewayHandler.java:26)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:119)

```

### Expected Behavior

Should work with the below dependency as it was closed and verified in the original ticket https://github.com/localstack/localstack/issues/1634

```
   <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-lambda-java-events</artifactId>
        <version>2.0.2</version>
    </dependency>
```

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    curl -X POST http://192.168.1.1:4566/restapis/mvy1yew0wa/prod/_user_request_/users

### Environment

```markdown
- OS: Amazon Linux2
- LocalStack: localstack/localstack   latest    087de49bf85a
```

**Comment by dfangl** [comment] 2022-12-21 16:43
Hi!
Will close this as duplicate of #1634 .
This behavior does only effect the local executor mode. Please use one of the docker executor modes (by mounting a docker socket into you container) to fix this, or use the new provider using `PROVIDER_OVERRIDE_LAMBDA=asf` in addition to the docker socket being mounted into the container. (please also verify you are running on the latest image).

**Closed by dfangl** 2022-12-21 16:43 UTC
Labels: type: bug, aws:lambda, area: integration/aws-sdk
