### ISSUE TITLE
Kinesis create stream giving 502 Bad gateway

### ISSUE THREAD

**Issue by mudim** [localstack/localstack#329] opened 2017-09-18 16:26 UTC
Hi,
Trying to use localstack and noticed that while trying to create a stream using `createStream` of kinesis client, am getting a 502. This seems to be tied to the following error am seeing in logs of localstack
`2017-09-18T17:19:31:ERROR:localstack.services.generic_proxy: Error forwarding request: 'str' object has no attribute 'get' Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 189, in forward
    path=path, data=data, headers=forward_headers, response=response)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/kinesis/kinesis_listener.py", line 33, in return_response
    event_publisher.fire_event(event_type, payload={'n': event_publisher.get_hash(data.get('StreamName'))})
AttributeError: 'str' object has no attribute 'get'`

Above indicates that `data` is expected to be a dict object. However, when calling `createStream` it's just stream name and shard count that can be passed. Is there any config am missing for the proxy to work properly?

Appreciate help on above.

Cheers.

**Comment by whummer** [comment] 2017-09-21 23:51
Hi @mudim , thanks for reporting. Which Kinesis client are you using? One possible issue could be that the client does not send the correct `Content-Type` header along with the request. Can you please provide a minimal test case to reproduce the error? Thanks

**Comment by whummer** [comment] 2019-11-08 17:20
Closing as outdated - looks like this issue should be fixed in the meantime.

**Closed by whummer** 2019-11-08 17:20 UTC
Labels: needs-triaging
