### ISSUE TITLE
bug: AttributeError: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name'

### ISSUE THREAD

**Issue by esetnik** [localstack/localstack#5160] opened 2021-12-21 14:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
```
AttributeError: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/run.py", line 155, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 912, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 162, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 219, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for sqs: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name'
```

### Expected Behavior

SQS service starts normally as it did in 0.13.0

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```dockerfile
FROM localstack/localstack:0.13.2


RUN apt-get update && \
  apt-get install -y software-properties-common && \
  curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
  apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  terraform

RUN mkdir -p /terraform
COPY terraform.tf /terraform
COPY entrypoint.sh /docker-entrypoint-initaws.d/

RUN terraform -chdir=/terraform init
```

```yml
  localstack:
    build: ./localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs,sns,dynamodb,apigateway,ssm,lambda,s3,cloudformation,sts,iam,cloudwatch,logs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack/terraform.tf:/terraform/terraform.tf
      - localstack:/terraform
```

### Environment

```markdown
- OS: macOS 12.1
- LocalStack: 0.13.2
```

### Anything else?

Working fine in 0.13.0 and broken in 0.13.1 and 0.13.2

**Comment by esetnik** [comment] 2021-12-21 14:52
Possibly related to https://github.com/localstack/localstack/pull/5024

**Comment by adamdavis40208** [comment] 2021-12-23 01:20
I'm also hitting this (in 0.13.2), but oddly enough half of my other sqs tests are passing fine.

**Comment by esetnik** [comment] 2021-12-23 13:51
I was able to work around the issue by setting `EAGER_SERVICE_LOADING=1`

**Comment by viacheslav-shvets** [comment] 2021-12-23 15:44
Same happened to my colleague on his laptop, but for me it works fine. Pretty strange.

**Comment by alexandre-guidin-dafiti** [comment] 2021-12-23 16:20
> I was able to work around the issue by setting `EAGER_SERVICE_LOADING=1`

It work here. I'm having the same issue only in my CI.

**Comment by adamdavis40208** [comment] 2021-12-23 17:48
`EAGER_SERVICE_LOADING=1` fixes my failing tests as well. It's too much of a breaking bug for me to introduce this version into the company, though

**Comment by adamdavis40208** [comment] 2021-12-23 17:56
And in case this helps y'all debug the issue (all of this is without EAGER_SERVICE_LOADING):

```
      # pretty simple ruby code after making a queue
      log "queues #{client.list_queues}"
      log "queue urls #{client.list_queues.queue_urls}"


      ### 1 queue
      Listing SQS queues:
      queues {:queue_urls=>["http://janus-localstack:4566/000000000000/local-sqs-stack-pew-pew"], :next_token=>nil}
      queue urls ["http://janus-localstack:4566/000000000000/local-sqs-stack-pew-pew"]
        1. http://janus-localstack:4566/000000000000/local-sqs-stack-pew-pew


        ### 2 queues

        AttributeError: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name'
```

I have other tests with more than one queue passing, not sure what trips this.

**Comment by dfangl** [comment] 2021-12-27 15:24
Hi all!
This issue is a result of a race condition where service startups can happen multiple times if two queues are created simultaneously.
This only just surfaced with the introduction of a new method to patch dependencies.
The PR which should fix this issue is linked, thank you all for reporting and providing valuable information to reproduce this issue! This one is quite tricky since the timing has to be quite good to trigger this behavior, so difference of machines, environment etc can all factor into it surfacing.

**Comment by dfangl** [comment] 2021-12-27 18:42
A fix for this behavior should now be available in `localstack/localstack:latest`. Please see if this fixes your error!

**Comment by adamdavis40208** [comment] 2021-12-27 19:14
Confirmed, we have green happy checks

![image](https://user-images.githubusercontent.com/19850646/147500713-1777a42a-77fa-410e-a1c8-dc02f189ca3b.png)

Can you let us know when this is pushed to a version?

**Comment by dfangl** [comment] 2021-12-28 11:10
Will let you know!

**Closed by dfangl** 2021-12-28 11:10 UTC
Labels: bug, needs-triaging, aws:sqs
