### ISSUE TITLE
Issues running java AWS lambda

### ISSUE THREAD

**Issue by soasathish** [localstack/localstack#911] opened 2018-08-28 13:22 UTC
I am running a docker images of the localstack

docker run --privileged -d -p 4576:4576 -p 4572:4572 -p 4574:4574 -p 8080:8080 -e SERVICES=s3,sqs,lambda --name localstack localstack/localstack

I have written n java lambda function when i try to invokde i get  using below command
 

> aws --endpoint-url=http://localhost:4574 lambda create-function --function-name=f2 --runtime=java8 --role=r1 --handler=com.atlassian.localstack.sample.LambdaHandlers --zip-file 
 fileb://LambdaHandler.zip

An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script in Lambda archive.

Java functions
===========
`package com.atlassian.localstack.sample;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;

/**
 * Test Lambda handler class
 */
public class LambdaHandler implements RequestHandler<Object, Object> {

    @Override
    public Object handleRequest(Object event, Context context) {
        System.err.println(event);
        return "{}";
    }

}`

**Comment by whummer** [comment] 2019-11-30 19:58
Closing this one as outdated / cannot reproduce. If the problem persists, please open a follow-up ticket with a small self-contained example that allows to reproduce this issue (including the commands for packaging/deploying the Lambda). Thanks

**Closed by whummer** 2019-11-30 19:58 UTC
