### ISSUE TITLE
SQS Support for ContentBasedDeduplication

### ISSUE THREAD

**Issue by JoaoRXFernandesJG** [localstack/localstack#590] opened 2018-01-29 08:27 UTC
Hi,

Any chance we could update to allow FifoQueue attributes?

```
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name "test-queue.fifo" --attributes "FifoQueue=true,ContentBasedDeduplication=true"
```

An error occurred (InvalidParameterValue) when calling the CreateQueue operation: InvalidParameterValue; see the SQS docs.

Thanks,

Joao

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-304) by [Unito](https://www.unito.io/learn-more)

**Comment by tollmanz** [comment] 2018-02-14 22:17
When I use `awslocal` with your command, it works fine:

```
awslocal --endpoint-url=http://localhost:4576 sqs create-queue --queue-name "test-queue.fifo" --attributes "FifoQueue=true,ContentBasedDeduplication=true"
```

I'm also running FIFO SQS queues in Localstack, added via the Node SDK and they seem to be working just fine.

**Comment by sp-daniel-pinyol** [comment] 2018-04-04 08:03
In my case I don't get an error, but ContentBasedDeduplication does not seem to work
```
aws --endpoint-url=http://192.168.99.100:4576 sqs create-queue --queue-name "test-queue.fifo" --attributes "FifoQueue=true,ContentBasedDeduplication=true"
{
    "QueueUrl": "http://localstack:4576/queue/test-queue_fifo"
}
```

**Comment by sp-daniel-pinyol** [comment] 2018-09-04 13:48
@mberlanda thanks for the info! Unfortunately I'm currently working on a different project. I'll take it into account for future ones

best

**Comment by austinbutler** [comment] 2020-07-01 16:44
I'm using boto3 to create the queue like this and still getting duplicate messages with v0.11.3.

```
sqs.create_queue(
    QueueName=queue_name,
    Attributes={
        "FifoQueue": "true",
        "ContentBasedDeduplication": "true",
    },
)
```

If I inspect the queue attributes after creation I see the queue name ends in `.fifo`, `FifoQueue` is `'true'`, and `ContentBasedDeduplication` is `'true'`.

**Comment by badmintonkid** [comment] 2020-07-21 10:55
I have tests depending on fifo dedup and they are passing when using version 0.11.2. Using a localstack image past that results in the tests failing because of duplicate messages.

**Comment by mberlanda** [comment] 2020-09-20 18:58
Hello, my two cents here would be to try debugging the functionality in service used by localstack to mock SQS: https://github.com/softwaremill/elasticmq

You can start having a look at this file: https://github.com/softwaremill/elasticmq/blob/master/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/QueueAttributesDirectives.scala

I would add unit tests reproducing your issue and validate that this is actually an issue on elasticmq side

**Comment by whummer** [comment] 2021-02-07 18:40
Thanks for the update @austinbutler @badmintonkid @mberlanda @sp-daniel-pinyol , and apologies for the delay on this one. We believe that this should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Closed** 2021-02-21 17:24 UTC
Labels: evaluate-or-close, feature-missing, needs-triaging, should-be-fixed, upstream-issue
