### ISSUE TITLE
bug: kinesis.mock.ExpiredIteratorException when using AmazonDynamoDBStreamsAdapterClient

### ISSUE THREAD

**Issue by saravanan1986** [localstack/localstack#5182] opened 2021-12-23 21:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I’m using KCL 1.x version and dynamodb-streams-kinesis-adapter 1.5.3 version for consuming data from Kinesis Streams. Consumer is able to consume data from Kinesis stream from localstack. I could see AmazonDynamoDBStreamsAdapterClient is constantly calling getRecords() to look for new records. But when consumer is idle for more than 5 minutes, because there was no data from Kinesis Stream, I start seeing ShardIterator Expired exception on localstack. After encountering the exception, consumer is no longer able to stream the data even when data is posted to the stream. Debugging I could see AmazonDynamoDBStreamsAdapterClient is calling getRecords() and erroring out with 500 error response.

I see following error on **localstack**:
```
kinesis.mock.ExpiredIteratorException: The shard iterator has expired. Shard iterators are only valid for 300 seconds
at kinesis.mock.models.ShardIterator.parse(ShardIterator.scala:58)
at kinesis.mock.api.GetRecordsRequest.$anonfun$getRecords$1(GetRecordsRequest.scala:24)
at cats.effect.IOFiber.runLoop(IOFiber.scala:319)
at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1175)
at cats.effect.IOFiber.run(IOFiber.scala:129)
at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:435)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
2021-12-23T21:26:07.777:DEBUG:localstack.services.edge: IN(dynamodbstreams): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost:4566', 'Amz-Sdk-Invocation-Id': '643b0e52-0d9e-3b0c-bc85-60512e3d8ec9', 'Amz-Sdk-Request': 'ttl=20211223T212657Z;attempt=1;max=4', 'Amz-Sdk-Retry': '0/0/0', 'Authorization': 'AWS4-HMAC-SHA256 Credential=dummy/20211223/us-west-2/dynamodb/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=6c8302247ff69b0d0ffe0c5907ccd47da4e5f8f12c1af588ec6d878293e68492', 'Content-Type': 'application/x-amz-json-1.0', 'User-Agent': 'aws-sdk-java/1.11.1016 Mac_OS_X/10.16 OpenJDK_64-Bit_Server_VM/11.0.2+9 java/11.0.2 kotlin/1.5.30 vendor/Oracle_Corporation cfg/retry-mode/legacy', 'X-Amz-Date': '20211223T212607Z', 'X-Amz-Target': 'DynamoDBStreams_20120810.GetRecords', 'Content-Length': '301', 'Connection': 'Keep-Alive', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b'{"ShardIterator":"AAAAAAAAAAG4wzT5ZbQJXrwEBiDjq71Wduk3LUajYTOEo0Az8uCuKY8JeqQgIyqUoRbyYcvRqH9EEmcKW0yT/iym0Vrl4GFS+/SR7pt0/NWr9zPgbvmgr824218Cms46JN2FsbZOvESlJv3h8VP7H7DIKIrzqVMWjMvct8PMydm0JNMWa9IM101nELIOZ7mt1kQQIUu1pWONjWuuMvwutGXjhmm6DeGuNUqUUW5YaUKMDXOsEFnP8naxRjaFR/w9NGqIbZCbe1o=","Limit":1000}'
```

`2021-12-23T21:16:35.965:DEBUG:localstack.services.edge: OUT(dynamodbstreams): "POST /" - status: 500 - response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '290', 'Access-Control-Allow-Origin': '*', 'Server': 'Werkzeug/2.0.2 Python/3.8.12', 'Date': 'Thu, 23 Dec 2021 21:16:35 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'`

### Expected Behavior

Consumer should be able to stream data even when there is no data on the Kinesis for longer period of time should not return 500 error code.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    DEBUG=1 LS_LOG=true localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

**AmazonDynamoLocalStackConfig.kt**
```
import com.amazonaws.auth.AWSCredentialsProvider
import com.amazonaws.auth.AWSStaticCredentialsProvider
import com.amazonaws.auth.BasicAWSCredentials
import com.amazonaws.client.builder.AwsClientBuilder
import com.amazonaws.services.cloudwatch.AmazonCloudWatch
import com.amazonaws.services.cloudwatch.AmazonCloudWatchClientBuilder
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder
import com.amazonaws.services.dynamodbv2.streamsadapter.AmazonDynamoDBStreamsAdapterClient
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Profile
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider
import software.amazon.awssdk.core.client.config.ClientOverrideConfiguration
import software.amazon.awssdk.core.retry.RetryPolicy
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient
import software.amazon.awssdk.services.dynamodb.DynamoDbClient
import software.amazon.awssdk.services.dynamodb.streams.DynamoDbStreamsClient
import java.net.URI

@Configuration
@Profile("dev")
class AmazonDynamoLocalStackConfig {

    @Bean
    fun awsCredentialsProvider(): AWSCredentialsProvider {
        val awsCreds = BasicAWSCredentials("dummy", "dummy")
        return AWSStaticCredentialsProvider(awsCreds)
    }

    @Bean
    fun awsCredentialsProviderV2(): AwsCredentialsProvider {
        return StaticCredentialsProvider.create(AwsBasicCredentials.create("dummy", "dummy"))
    }

    @Bean
    fun dynamoDbClient(awsCredentialsProvider: AwsCredentialsProvider, amazonDynamoProperties: AmazonDynamoProperties): DynamoDbClient {
        return DynamoDbClient.builder()
            .endpointOverride(URI("http://localhost:4566"))
            .credentialsProvider(awsCredentialsProvider)
            .overrideConfiguration(
                ClientOverrideConfiguration.builder()
                    .retryPolicy(
                        RetryPolicy.builder()
                            .numRetries(
                                5
                            )
                            .build()
                    )
                    .build()
            )
            .build()
    }

    @Bean
    fun dynamoDbStreamsClient(awsCredentialsProvider: AwsCredentialsProvider, amazonDynamoProperties: AmazonDynamoProperties): DynamoDbStreamsClient {
        
        return DynamoDbStreamsClient.builder()
            .endpointOverride(URI("http://localhost:4566"))
            .credentialsProvider(awsCredentialsProvider)
            .build()
    }

    @Bean
    fun dynamoDbEnhancedClient(dynamoDbClient: DynamoDbClient): DynamoDbEnhancedClient {

        return DynamoDbEnhancedClient.builder()
            .dynamoDbClient(dynamoDbClient)
            .build()
    }

    @Bean
    fun adapterClient(awsCredentialsProvider: AwsCredentialsProvider, amazonDynamoProperties: AmazonDynamoProperties): AmazonDynamoDBStreamsAdapterClient {
        val data = AmazonDynamoDBStreamsClientBuilder.standard()
            .withCredentials(awsCredentialsProvider1)
            .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration(amazonDynamoProperties.endpoint, amazonDynamoProperties.region))
            .build()

        val adapter = AmazonDynamoDBStreamsAdapterClient(data)

        return adapter
    }

    @Bean
    fun dynamoDbClientV2(awsCredentialsProvider: AWSCredentialsProvider, amazonDynamoProperties: AmazonDynamoProperties): AmazonDynamoDB {
        val client: AmazonDynamoDB = AmazonDynamoDBClientBuilder.standard()
            .withCredentials(awsCredentialsProvider)
            .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration("http://localhost:4566","us-west-2"))
            .build()

        return client
    }

    @Bean
    fun dynamoDbEnhancedClientV2(dynamoDbClient: DynamoDbClient): DynamoDbEnhancedClient {
        return DynamoDbEnhancedClient.builder().dynamoDbClient(dynamoDbClient).build()
    }

    @Bean
    fun cloudWatchClient(awsCredentialsProvider: AWSCredentialsProvider, amazonDynamoProperties: AmazonDynamoProperties): AmazonCloudWatch {

        return AmazonCloudWatchClientBuilder.standard()
            .withCredentials(awsCredentialsProvider)
            .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration("http://localhost:4566","us-west-2"))
            .build()
    }

    @Bean("kinesisUtilName")
    fun kinesisUtil(
        dynamoDb: AmazonDynamoDB,
        cloudWatch: AmazonCloudWatch,
        dynamoProperties: AmazonDynamoProperties,
        adapterClient: AmazonDynamoDBStreamsAdapterClient,
        awsCredentialsProvider: AWSCredentialsProvider
    ): KinesisUtil {
        dynamoProperties.kinesisEndpoint = "http://localhost:4566"

        // set the param value here?
        return KinesisUtil(dynamoDb, cloudWatch, adapterClient, awsCredentialsProvider)
    }
}
```

**KinesisUtil.kt**
```
import com.amazonaws.ClientConfiguration
import com.amazonaws.auth.AWSCredentialsProvider
import com.amazonaws.services.cloudwatch.AmazonCloudWatch
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB
import com.amazonaws.services.dynamodbv2.streamsadapter.AmazonDynamoDBStreamsAdapterClient
import com.amazonaws.services.dynamodbv2.streamsadapter.StreamsWorkerFactory
import com.amazonaws.services.kinesis.clientlibrary.interfaces.v2.IRecordProcessorFactory
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitialPositionInStream
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibConfiguration
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker
import com.amazonaws.services.kinesis.metrics.interfaces.MetricsLevel
import org.springframework.stereotype.Component

@Component
class KinesisUtil(
    private val dynamoDb: AmazonDynamoDB,
    private val cloudWatch: AmazonCloudWatch,
    private val adapterClient: AmazonDynamoDBStreamsAdapterClient,
    private val awsCredentialsProvider: AWSCredentialsProvider
) {

    fun buildWorker(dynamoTable: String, workerId: String, processorFactory: IRecordProcessorFactory): Worker {
        
        val streamARN = dynamoDb.describeTable(dynamoTable).table.latestStreamArn

        var workerConfig = KinesisClientLibConfiguration(
            workerId,
            streamARN,
            null,
            null,
            KinesisClientLibConfiguration.DEFAULT_INITIAL_POSITION_IN_STREAM,
            awsCredentialsProvider,
            awsCredentialsProvider,
            awsCredentialsProvider,
            KinesisClientLibConfiguration.DEFAULT_FAILOVER_TIME_MILLIS,
            workerId,
            5000,
            KinesisClientLibConfiguration.DEFAULT_IDLETIME_BETWEEN_READS_MILLIS,
            KinesisClientLibConfiguration.DEFAULT_DONT_CALL_PROCESS_RECORDS_FOR_EMPTY_RECORD_LIST,
            KinesisClientLibConfiguration.DEFAULT_PARENT_SHARD_POLL_INTERVAL_MILLIS,
            KinesisClientLibConfiguration.DEFAULT_SHARD_SYNC_INTERVAL_MILLIS,
            KinesisClientLibConfiguration.DEFAULT_CLEANUP_LEASES_UPON_SHARDS_COMPLETION,
            ClientConfiguration(),
            ClientConfiguration(),
            ClientConfiguration(),
            KinesisClientLibConfiguration.DEFAULT_TASK_BACKOFF_TIME_MILLIS,
            KinesisClientLibConfiguration.DEFAULT_METRICS_BUFFER_TIME_MILLIS,
            KinesisClientLibConfiguration.DEFAULT_METRICS_MAX_QUEUE_SIZE,
            KinesisClientLibConfiguration.DEFAULT_VALIDATE_SEQUENCE_NUMBER_BEFORE_CHECKPOINTING,
            null,
            KinesisClientLibConfiguration.DEFAULT_SHUTDOWN_GRACE_MILLIS,
            KinesisClientLibConfiguration.DEFAULT_DDB_BILLING_MODE
        )

        workerConfig = workerConfig.withKinesisEndpoint("http://localhost:4566")
        
        workerConfig = workerConfig.withInitialPositionInStream(InitialPositionInStream.TRIM_HORIZON)
                                    .withMetricsLevel(MetricsLevel.NONE)
                                    .withMaxLeasesForWorker(100) 

        return StreamsWorkerFactory.createDynamoDbStreamsWorker(
            processorFactory,
            workerConfig,
            adapterClient,
            dynamoDb,
            cloudWatch
        )
    }
}
```

**MyTableStreamConsumer.kt**

```
import org.springframework.boot.ApplicationArguments
import org.springframework.boot.ApplicationRunner
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.context.ApplicationContext
import org.springframework.context.annotation.Profile
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor
import org.springframework.stereotype.Component

@Component
class MyTableStreamConsumer(
    private val threadPoolTaskExecutor: ThreadPoolTaskExecutor,
    private val kinesisUtil: KinesisUtil,
    private val recordProcessorUtils: RecordProcessorUtils
) : ApplicationRunner {

    override fun run(args: ApplicationArguments?) {
        val worker = kinesisUtil.buildWorker(
            "mytable", "mytable-stream-worker",
            MyTableRecordProcessorFactory("mytable", "mytable-stream-consumer", recordProcessorUtils)
        )

        threadPoolTaskExecutor.execute(worker)

    }
}

```
**MyTableRecordProcessorFactory.kt**
```
import com.amazonaws.services.kinesis.clientlibrary.interfaces.v2.IRecordProcessor
import com.amazonaws.services.kinesis.clientlibrary.interfaces.v2.IRecordProcessorFactory
import org.slf4j.LoggerFactory

class MyTableRecordProcessorFactory(
    private val tableName: String,
    private val metricName: String
) : IRecordProcessorFactory {

    override fun createProcessor(): IRecordProcessor {
        return GenericDynamoStreamConsumer()
    }
}
```

**GenericDynamoStreamConsumer.kt**
```
import com.amazonaws.services.kinesis.clientlibrary.interfaces.v2.IRecordProcessor
import com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownReason
import com.amazonaws.services.kinesis.clientlibrary.types.InitializationInput
import com.amazonaws.services.kinesis.clientlibrary.types.ProcessRecordsInput
import com.amazonaws.services.kinesis.clientlibrary.types.ShutdownInput

class GenericDynamoStreamConsumer() : IRecordProcessor {
    private var checkpointCounter: Int = 0

    override fun initialize(initializationInput: InitializationInput?) {
        checkpointCounter = 0
    }

    override fun processRecords(processRecordsInput: ProcessRecordsInput?) {
       //do Something
    }

    override fun shutdown(shutdownInput: ShutdownInput?) {
        if (shutdownInput?.shutdownReason === ShutdownReason.TERMINATE) {
            try {
                shutdownInput?.checkpointer.checkpoint()
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }
}

```

**gradle dependency**

```
 implementation(platform("software.amazon.awssdk:bom:2.15.67"))
 implementation("software.amazon.awssdk", "dynamodb-enhanced")
 implementation("com.amazonaws", "dynamodb-streams-kinesis-adapter", 1.5.3)
```

### Environment

```markdown
- OS: macOS Big Sur 11.6.1
- LocalStack: 0.13.1
```

**Comment by thrau** [comment] 2021-12-27 14:22
Hey Eric @etspaceman, might this be an issue in kinesis-mock?

**Comment by etspaceman** [comment] 2021-12-27 15:02
Shard Iterators expire after 5 minutes. This tells me that a new shard iterator is not being requested, which is odd

**Comment by thrau** [comment] 2021-12-27 15:30
thanks, that's already helpful! will open an issue in kinesis-mock when we now more, if needed.

**Comment by saravanan1986** [comment] 2022-01-05 18:42
@etspaceman @thrau Were able to replicate this issue.

**Comment by dfangl** [comment] 2022-01-13 18:10
@etspaceman It seems like kinesis mock will return the same shard iterator over and over as NextShardIterator when calling get-records. Reproduced it by starting kinesis-mock as docker container and running `aws --endpoint-url http://127.0.0.1:4568 kinesis get-records --shard-iterator <shard-iterator>` over and over, the `NextShardIterator` is always the same instead of a new one (with a new validity period). This is why dynamodbstreams does not get any new iterators.
AWS provides a new shard iterator for every get-records request, as well for kinesis as for dynamodbstreams.

The other part of the problem is the missing mapping between the boto3 exception and the correct error response in dynamodbstreams if a shard iterator is expired, thats fixed with #5270.

**Comment by etspaceman** [comment] 2022-01-13 19:07
@dfangl I have confirmed that is the behavior in the kinesis-mock. I can look into that in the near future for a fix. Thanks for the bug report!

**Comment by etspaceman** [comment] 2022-01-14 01:28
I have a version 0.2.2 with a fix for this. The artifacts should be available shortly.

**Comment by dfangl** [comment] 2022-01-14 11:28
Great, thanks! Preparing a version bump right now.

**Comment by dfangl** [comment] 2022-01-16 20:44
Fix is in place in `:latest`.
Thanks for reporting this!

**Closed by dfangl** 2022-01-16 20:44 UTC
Labels: bug, needs-triaging, aws:kinesis, aws:dynamodbstreams

**Comment by cabeaulac** [comment] 2023-05-25 23:40
I'm still getting this error in LS version 2.0.2. When this happens, my Lambda bound to the DDB stream never fires again, and I have to stop LS and restart/redeploy everything.
```
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : [io-compute-0] WARN  2023-05-25 23:16:13,566 k.m.cache.Cache x-amzn-RequestId=24712ec9-fb52-11ed-9059-a1348e548173, action=GetRecords, contextId=24712ec8-fb52-11ed-9059-a1348e548173, x-amz-id-2=gCk38Ej75iKetNtekgWoJKOXgy1hNl0QORkRWkRFormlRtxfRgS6M9km7F3B++qE1gzPHS+vpE5mlpqc6vOPduzbLS9+vJSP, contentType=application/x-amz-json-1.1 - Getting records was unuccessful
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : kinesis.mock.ExpiredIteratorException: The shard iterator has expired. Shard iterators are only valid for 300 seconds
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : at kinesis.mock.models.ShardIterator.parse(ShardIterator.scala:58)
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : at kinesis.mock.api.GetRecordsRequest.$anonfun$getRecords$1(GetRecordsRequest.scala:25)
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : at cats.effect.IOFiber.runLoop(IOFiber.scala:337)
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1330)
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : at cats.effect.IOFiber.run(IOFiber.scala:119)
2023-05-25 16:16:13 2023-05-25T23:16:13.574  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:585)
2023-05-25 16:16:13 2023-05-25T23:16:13.606 ERROR --- [uncthread611] l.s.a.e.stream_event_sourc : Error while listening to shard / executing lambda with params {'function_arn': 'arn:aws:lambda:us-west-2:000000000000:function:lsgdc-user-ddb-stream-handler-lambda-local-0efb963', 'stream_arn': 'arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-05-25T21:40:40.343', 'batch_size': 100, 'parallelization_factor': 1, 'lock_discriminator': '0e5db798-170c-403c-8cba-86840304a2f0/arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-05-25T21:40:40.343/shardId-00000001685000000000-000000000000', 'shard_id': 'shardId-00000001685000000000-000000000000', 'stream_client': <botocore.client.DynamoDBStreams object at 0xfffee250c6d0>, 'shard_iterator': 'AAAAAAAAAAEBQ+frqxeZe5fx4eBUGnSTjxD96OEI6nklIdiPixZ0NW7xH5L9Xq+0E1mmyqHSO9CIRUIrzGZKfBBQW9BvS0bDqXIOF49lNTv7xf1CIgSeFiL6+HDSbMtYXVyicgQD8JbztYZuedxf9yRuqE4RfWNhzsy/p979D4MGxmqlGjYgZBUXiqm255M8pl0eBd6CyVW5HKzdDhwyC3pwP6zkDUGoKfD6KlWYsyLXH+NXj3JPCA==', 'failure_destination': None, 'max_num_retries': inf}: An error occurred (ExpiredIteratorException) when calling the GetRecords operation: Shard iterator has expired
2023-05-25 16:16:13 2023-05-25T23:16:13.615  INFO --- [uncthread611] localstack.utils.threads   : Thread run method <bound method StreamEventSourceListener._listen_to_shard_and_invoke_lambda of <localstack.services.awslambda.event_source_listeners.dynamodb_event_source_listener.DynamoDBEventSourceListener object at 0xfffee2576380>>({'function_arn': 'arn:aws:lambda:us-west-2:000000000000:function:lsgdc-user-ddb-stream-handler-lambda-local-0efb963', 'stream_arn': 'arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-05-25T21:40:40.343', 'batch_size': 100, 'parallelization_factor': 1, 'lock_discriminator': '0e5db798-170c-403c-8cba-86840304a2f0/arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-05-25T21:40:40.343/shardId-00000001685000000000-000000000000', 'shard_id': 'shardId-00000001685000000000-000000000000', 'stream_client': <botocore.client.DynamoDBStreams object at 0xfffee250c6d0>, 'shard_iterator': 'AAAAAAAAAAEBQ+frqxeZe5fx4eBUGnSTjxD96OEI6nklIdiPixZ0NW7xH5L9Xq+0E1mmyqHSO9CIRUIrzGZKfBBQW9BvS0bDqXIOF49lNTv7xf1CIgSeFiL6+HDSbMtYXVyicgQD8JbztYZuedxf9yRuqE4RfWNhzsy/p979D4MGxmqlGjYgZBUXiqm255M8pl0eBd6CyVW5HKzdDhwyC3pwP6zkDUGoKfD6KlWYsyLXH+NXj3JPCA==', 'failure_destination': None, 'max_num_retries': inf}) failed: An error occurred (ExpiredIteratorException) when calling the GetRecords operation: Shard iterator has expired Traceback (most recent call last):
2023-05-25 16:16:13   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/threads.py", line 58, in run
2023-05-25 16:16:13     result = self.func(self.params, **kwargs)
2023-05-25 16:16:13   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/event_source_listeners/stream_event_source_listener.py", line 201, in _listen_to_shard_and_invoke_lambda
2023-05-25 16:16:13     records_response = stream_client.get_records(
2023-05-25 16:16:13   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
2023-05-25 16:16:13     return self._make_api_call(operation_name, kwargs)
2023-05-25 16:16:13   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
2023-05-25 16:16:13     raise error_class(parsed_response, operation_name)
2023-05-25 16:16:13 botocore.errorfactory.ExpiredIteratorException: An error occurred (ExpiredIteratorException) when calling the GetRecords operation: Shard iterator has expired
2023-05-25 16:16:13 
2023-05-25 16:16:59 2023-05-25T23:16:59.028  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : 2023-05-25T23:16:59.024Z [WARNING] Your app's responsiveness to a new asynchronous
2023-05-25 16:16:59 2023-05-25T23:16:59.028  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : event (such as a new connection, an upstream response, or a timer) was in excess
2023-05-25 16:16:59 2023-05-25T23:16:59.028  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : of 100 milliseconds. Your CPU is probably starving. Consider increasing the
2023-05-25 16:16:59 2023-05-25T23:16:59.028  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : granularity of your delays or adding more cedes. This may also be a sign that you
2023-05-25 16:16:59 2023-05-25T23:16:59.029  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : are unintentionally running blocking I/O operations (such as File or InetAddress)
2023-05-25 16:16:59 2023-05-25T23:16:59.029  INFO --- [uncthread223] l.s.k.kinesis_mock_server  : without the blocking combinator.
```
