### ISSUE TITLE
AWS SDKv2 kinesis throws exception when using `getRecords`

### ISSUE THREAD

**Issue by lukecollier** [localstack/localstack#3243] opened 2020-11-13 16:57 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Currently when using [software.amazon.awssdk:kinesis:2.15.27](https://search.maven.org/artifact/software.amazon.awssdk/kinesis/2.15.27/jar) and attempting to use [getRecords](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/kinesis/KinesisAsyncClient.html#getRecords-java.util.function.Consumer-) we end up getting a general aws client exception `software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 1.605283809962E9`. This doesn't happen when using a live kinesis stream.

## Expected behavior
Should be able to get a response from localstack with the correct data.

## Actual behavior
An exception is thrown from inside aws sdk v2 with the message `software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 1.605283809962E9`.

# Steps to reproduce
## Command used to start LocalStack
`docker run -d -p 4566:4566 -e "SERVICES=kinesis" localstack/localstack:0.12.2`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
https://github.com/lukecollier/localstack-jvm-aws-sdk-v2

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-53) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-11-16 20:23
Potential duplicate of #3134

**Comment by jalkjaer** [comment] 2020-11-24 11:47
This is also a problem for the java kinesis client v1 (at least 1.11.718) 
The Kinesis API spec states that the Record.Data field is Base64 encoded 
https://docs.aws.amazon.com/kinesis/latest/APIReference/API_Record.html (version 2013-12-02??)
And that is how Kinesis responses look (checked using aws cli)

LocalStack returns an object ` "Data": { "type": "Buffer", "data": [ <ints> ] }`
Which can also be seen using the aws cli

**Comment by pinzon** [comment] 2020-12-02 13:23
This should be fix with the PR #3278

**Closed by pinzon** 2020-12-02 13:23 UTC
Labels: bug, java, possible-duplicate
