### ISSUE TITLE
S3 VersionId not persistent

### ISSUE THREAD

**Issue by geoynomous** [localstack/localstack#1507] opened 2019-08-27 08:06 UTC
I am enabling persistence with -e DATA_DIR="/tmp/localstack/data" - then S3 Objects survive restarts of the docker container. However, with enabled Versioning on the Bucket, the restarts assigns new VersionIds in each restart - this renders the persistence feature useless.

I assume it's because of the replay of the s3 API calls .... maybe there is a way to recreate the VersionIds.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-113) by [Unito](https://www.unito.io/learn-more)

**Comment by zserge** [comment] 2021-01-19 15:40
So persistance is broken because the S3 implementation moved from incremental IDs to UUIDs. Inside Localstack there seems to be no easy way to persist those returned UUIDs in the JSON file, and more importantly - to replay them properly.

There is a possible workaround of mocking the random generator to use a reproducible seed, but oh my that's a hack:

```
import os
import random

random.seed(0)
def mock_urandom(n):
    return bytes([random.getrandbits(8) for i in range(n)])

# Now the UUIDs depend only on the order of their generator, which remains the same during the replay
os.urandom = mock_urandom
```

**Comment by whummer** [comment] 2021-08-31 22:20
Closing as outdated/`won't fix` for now - the replay-based persistence mechanism will likely be changed / partially disabled in the future, to avoid error situations like the one described above. Thanks!

**Closed by whummer** 2021-08-31 22:20 UTC
Labels: bug, enhancement, persistence, available-in-pro
