### ISSUE TITLE
bug: S3 simulation doesn't check conditions for CopyObject

### ISSUE THREAD

**Issue by Cyberax** [localstack/localstack#5274] opened 2022-01-14 06:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

S3 emulation of `CopyObject` doesn't check that `CopySource` is different from the copy target. It succeeds on Localstack and returns an error on production S3.

### Expected Behavior

The following error is expected:

```
Bad Request: operation error S3: CopyObject, https response error StatusCode: 400, RequestID: ..., api error InvalidRequest: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.  ReqId: 65d0a11a2751a836
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
docker run localstack/localstack
awslocal s3 mb s3://mybucket
echo Hello > testfile.txt
awslocal s3 cp testfile.txt s3://mybucket/testfile.txt
awslocal s3api copy-object --bucket mybucket --key testfile.txt --copy-source mybucket/testfile.txt
{
    "CopyObjectResult": {
        "ETag": "\"09f7e02f1290be211da707a266f153b3\"",
        "LastModified": "2022-01-14T06:41:13.000Z"
    }
}
```

### Environment

```markdown
- OS: macOS 12.1
- LocalStack: `latest` tag
```

**Comment by SwatsonCodes** [comment] 2022-02-07 18:35
Thank you for raising this issue. The root cause appears to be a bug within `moto`. I am currently working on an upstream PR to address it there.

**Comment by SwatsonCodes** [comment] 2022-02-11 16:49
My moto PR has been merged and I expect that this issue will be resolved as the updated moto code makes its way into our repo. Closing this issue for now.

**Closed by SwatsonCodes** 2022-02-11 16:49 UTC
Labels: bug, needs-triaging, aws:s3
