### ISSUE TITLE
Default example of Getting Started not working

### ISSUE THREAD

**Issue by zopyx** [localstack/localstack#6448] opened 2022-07-13 13:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The example

```
mkdir -p /tmp/python/
echo 'def util():' > /tmp/python/testlayer.py
echo '  print("Output from Lambda layer util function")' >> /tmp/python/testlayer.py
(cd /tmp; zip -r testlayer.zip python)
awslocal lambda publish-layer-version --layer-name layer1 --zip-file fileb:///tmp/testlayer.zip

```

does not work (tested on Linux and Mac):

```
(localstack) ajung@dev2.zopyx.com ➜  localstack git:(master) ✗  bash test.sh
updating: python/ (stored 0%)
updating: python/testlayer.py (deflated 2%)

An error occurred (404) when calling the PublishLayerVersion operation: <!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>

```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

See above

### Environment

```markdown
- OS: Linux/MacoSX
- LocalStack: 0.14.5
```

**Comment by bentsku** [comment] 2022-07-13 14:57
Hello and thank you for your report!
I've started a PR to fix the issue you mentioned. In the meantime, you can replace the file path given in the example `fileb:///tmp/testlayer.zip` by `file:///tmp/testlayer.zip`, this should fix your issue. Sorry for the inconvenience!

**Comment by zopyx** [comment] 2022-07-13 15:24
Next error:

```
+ awslocal lambda publish-layer-version --layer-name layer1 --zip-file file:///tmp/testlayer.zip

Error parsing parameter '--zip-file': Unable to load paramfile (/tmp/testlayer.zip), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.

```

**Comment by bentsku** [comment] 2022-07-13 16:52
After retrying the updated example from the docs that you mentioned in your issue, I cannot reproduce the issue.
Please note that Lambda layers are a LocalStack Pro-only feature, you can find the list of supported services and operation for Community and Pro here: https://docs.localstack.cloud/aws/feature-coverage/

The 404 error will change after this PR #6449 is merged.

For more informations about our different plans, you can see: https://localstack.cloud/pricing/

**Comment by bentsku** [comment] 2022-07-29 10:38
Issue marked as resolved in Discuss:
https://discuss.localstack.cloud/t/default-example-of-getting-started-not-working/56/2

**Closed by bentsku** 2022-07-29 10:38 UTC
Labels: type: bug, status: response required
