### ISSUE TITLE
bug: aws_cloudwatch_log_group resource cannot be implemented

### ISSUE THREAD

**Issue by 1141558** [localstack/localstack#5895] opened 2022-04-20 09:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to create an aws_cloudwatch_log_group resource it takes a long time and is not implemented. The first time this happens I had some features to implement. But then I just tried with the aws_cloudwatch_log_group resource.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26725670/164197867-50374530-78cc-479b-9b43-747ad3d9ff8f.png)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

- docker-compose up -d    
- docker container start localstack_main (**after each reboot**)

[docker-compose.txt](https://github.com/localstack/localstack/files/8520161/docker-compose.txt)

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

**I didn't change the endpoint_url, I just changed the DNS.**
1. resolvectl dns docker0 172.17.0.2
2. resolvectl domain docker0 ~amazonaws.com ~aws.amazon.com ~cloudfront.net ~localhost.localstack.cloud
3. terraform apply

[main_tf.txt](https://github.com/localstack/localstack/files/8520255/main_tf.txt)
[main.tf.json.txt](https://github.com/localstack/localstack/files/8520263/main.tf.json.txt)

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.2.1
```

### Anything else?

**brashrc**

export LOCALSTACK_API_KEY=...
export DNS_ADDRESS=127.0.0.1
export LOCALSTACK_HOSTNAME=localhost.localstack.cloud
export EDGE_PORT=4566
export AWS_REGION=eu-west-1

**Comment by whummer** [comment] 2022-05-09 18:22
Thanks for reporting @1141558 . Can you please share some details about your environment, as well as a minimal working example to reproduce this issue?

Just gave it a quick try with the sample resource in the Terraform docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

With this `main.tf` file:
```
resource "aws_cloudwatch_log_group" "yada" {
  name = "Yada"

  tags = {
    Environment = "production"
    Application = "serviceA"
  }
}
```

... then using `tflocal` to deploy the resource (https://github.com/localstack/terraform-local):
```
tflocal apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_cloudwatch_log_group.yada will be created
  + resource "aws_cloudwatch_log_group" "yada" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "Yada"
      + retention_in_days = 0
      + tags              = {
          + "Application" = "serviceA"
          + "Environment" = "production"
        }
      + tags_all          = {
          + "Application" = "serviceA"
          + "Environment" = "production"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_cloudwatch_log_group.yada: Creating...
aws_cloudwatch_log_group.yada: Creation complete after 0s [id=Yada]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by 1141558** [comment] 2022-05-11 13:24
Hi, can you try with my files (main_tf.txt, main.tf.json.txt)?  You just need to rename the files

**Comment by whummer** [comment] 2022-05-14 14:09
Hi @1141558 . Your example seems to be missing the - can you include that as well please? Thanks

Seeing this in your `main_tf.txt` file:
```
module "CDAF" {
  source = "./cdaf"
}
```

Btw, quick hint - we have recently released a `tflocal` script you can use to deploy TF templates locally. With this script you no longer need to configure the AWS `provider` section in your main.tf. 👍 Maybe you want to give it a try! https://github.com/localstack/terraform-local

**Comment by 1141558** [comment] 2022-05-20 09:09
Hello @whummer , the hierarchy files is:
> main.tf
> cdaf
    > main.tf.json

Where should I put the module?

**Comment by 1141558** [comment] 2022-05-20 13:10
I tried with tflocal, but I got a lot of erros
`
Error: Unsupported argument

  on localstack_providers_override.tf line 11, in provider "aws":
  11: apigatewayv2 = "http://localhost.localstack.cloud:4566"

An argument named "apigatewayv2" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 12, in provider "aws":
  12: appconfig = "http://localhost.localstack.cloud:4566"

An argument named "appconfig" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 28, in provider "aws":
  28: config = "http://localhost.localstack.cloud:4566"

An argument named "config" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 30, in provider "aws":
  30: costexplorer = "http://localhost.localstack.cloud:4566"

An argument named "costexplorer" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 33, in provider "aws":
  33: dynamodbstreams = "http://localhost.localstack.cloud:4566"

An argument named "dynamodbstreams" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 41, in provider "aws":
  41: elasticsearch = "http://localhost.localstack.cloud:4566"

An argument named "elasticsearch" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 43, in provider "aws":
  43: elbv2 = "http://localhost.localstack.cloud:4566"

An argument named "elbv2" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 46, in provider "aws":
  46: events = "http://localhost.localstack.cloud:4566"

An argument named "events" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 54, in provider "aws":
  54: ioteventsdata = "http://localhost.localstack.cloud:4566"

An argument named "ioteventsdata" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 55, in provider "aws":
  55: iotwireless = "http://localhost.localstack.cloud:4566"

An argument named "iotwireless" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 69, in provider "aws":
  69: qldbsession = "http://localhost.localstack.cloud:4566"

An argument named "qldbsession" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 71, in provider "aws":
  71: rdsdata = "http://localhost.localstack.cloud:4566"

An argument named "rdsdata" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 73, in provider "aws":
  73: redshiftdata = "http://localhost.localstack.cloud:4566"

An argument named "redshiftdata" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 81, in provider "aws":
  81: sagemakerruntime = "http://localhost.localstack.cloud:4566"

An argument named "sagemakerruntime" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 86, in provider "aws":
  86: sesv2 = "http://localhost.localstack.cloud:4566"

An argument named "sesv2" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 92, in provider "aws":
  92: support = "http://localhost.localstack.cloud:4566"

An argument named "support" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 94, in provider "aws":
  94: timestreamquery = "http://localhost.localstack.cloud:4566"

An argument named "timestreamquery" is not expected here.

(localsatck) masilva@PF1MZMK1:~/repos/ctw/localstack/uc-one-gpm$ tflocal init

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 3.37"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
(localsatck) masilva@PF1MZMK1:~/repos/ctw/localstack/uc-one-gpm$ tflocal plan

Error: Unsupported argument

  on localstack_providers_override.tf line 11, in provider "aws":
  11: apigatewayv2 = "http://localhost.localstack.cloud:4566"

An argument named "apigatewayv2" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 12, in provider "aws":
  12: appconfig = "http://localhost.localstack.cloud:4566"

An argument named "appconfig" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 28, in provider "aws":
  28: config = "http://localhost.localstack.cloud:4566"

An argument named "config" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 30, in provider "aws":
  30: costexplorer = "http://localhost.localstack.cloud:4566"

An argument named "costexplorer" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 33, in provider "aws":
  33: dynamodbstreams = "http://localhost.localstack.cloud:4566"

An argument named "dynamodbstreams" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 41, in provider "aws":
  41: elasticsearch = "http://localhost.localstack.cloud:4566"

An argument named "elasticsearch" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 43, in provider "aws":
  43: elbv2 = "http://localhost.localstack.cloud:4566"

An argument named "elbv2" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 46, in provider "aws":
  46: events = "http://localhost.localstack.cloud:4566"

An argument named "events" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 54, in provider "aws":
  54: ioteventsdata = "http://localhost.localstack.cloud:4566"

An argument named "ioteventsdata" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 55, in provider "aws":
  55: iotwireless = "http://localhost.localstack.cloud:4566"

An argument named "iotwireless" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 69, in provider "aws":
  69: qldbsession = "http://localhost.localstack.cloud:4566"

An argument named "qldbsession" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 71, in provider "aws":
  71: rdsdata = "http://localhost.localstack.cloud:4566"

An argument named "rdsdata" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 73, in provider "aws":
  73: redshiftdata = "http://localhost.localstack.cloud:4566"

An argument named "redshiftdata" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 81, in provider "aws":
  81: sagemakerruntime = "http://localhost.localstack.cloud:4566"

An argument named "sagemakerruntime" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 86, in provider "aws":
  86: sesv2 = "http://localhost.localstack.cloud:4566"

An argument named "sesv2" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 92, in provider "aws":
  92: support = "http://localhost.localstack.cloud:4566"

An argument named "support" is not expected here.


Error: Unsupported argument

  on localstack_providers_override.tf line 94, in provider "aws":
  94: timestreamquery = "http://localhost.localstack.cloud:4566"

An argument named "timestreamquery" is not expected here.`

**Comment by steffyP** [comment] 2022-06-02 14:07
Hi @1141558,

do you also get this errors, when you run the example we provided?

> With this `main.tf` file:
> 
> ```
> resource "aws_cloudwatch_log_group" "yada" {
>   name = "Yada"
> 
>   tags = {
>     Environment = "production"
>     Application = "serviceA"
>   }
> }
> ```
> 
> ... then using `tflocal` to deploy the resource (https://github.com/localstack/terraform-local):
> 
> ```
> $ tflocal apply
> 

Could you please let us know, if this minimal example works for you?

If it does, we can go on with analyzing the modules you are using - please provide a minimal example so we can try to reproduce the issue on our side. We would either need the content of the `cdaf` module, or another example where you experience this issue.
Thank you.

**Comment by steffyP** [comment] 2022-07-01 07:37
Hi @1141558,

you can find the [recommended docker-compose file here](https://github.com/localstack/localstack/blob/master/docker-compose.yml). Could you clarify what you mean by "SO environment variables"?

You can pull the latest localstack image with `docker pull localstack/localstack:latest`. You will see the version when the image started (at time of writing, the latest version is `0.14.5.dev`).

I tested the minimal example above with terraform versions `v1.1.5` and `v1.2.4`, with the `tflocal` wrapper.

**Comment by 1141558** [comment] 2022-07-04 16:33
SO environment variables can be defined in **bashrc** file. 
I have these:
```
export LOCALSTACK_API_KEY=...
export DNS_ADDRESS=127.0.0.1
export DEBUG=1
export LOCALSTACK_HOSTNAME=localhost.localstack.cloud
export AWS_REGION=eu-west-1
export DOCKER_BRIDGE_IP=172.17.0.1
```
My **main.tf**
```
provider "aws" {
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
  region                      = "eu-west-1"

  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway        = "http://localhost:4566"
    athena            = "http://localhost:4566"
    cloudwatchevents  = "http://localhost:4566"
    cloudformation    = "http://localhost:4566"
    cloudwatch        = "http://localhost:4566"
    dynamodb          = "http://localhost:4566"
    ec2               = "http://localhost:4566"
    es                = "http://localhost:4566"
    elasticache       = "http://localhost:4566"
    firehose          = "http://localhost:4566"
    glue              = "http://localhost:4566"
    iam               = "http://localhost:4566"
    kafka             = "http://localhost:4566"
    kinesis           = "http://localhost:4566"
    kms               = "http://localhost:4566"
    lambda            = "http://localhost:4566"
    rds               = "http://localhost:4566"
    redshift          = "http://localhost:4566"
    route53           = "http://localhost:4566"
    s3                = "http://s3.localhost.localstack.cloud:4566"
    secretsmanager    = "http://localhost:4566"
    ses               = "http://localhost:4566"
    sns               = "http://localhost:4566"
    sqs               = "http://localhost:4566"
    ssm               = "http://localhost:4566"
    stepfunctions     = "http://localhost:4566"
    sts               = "http://localhost:4566"
  }
}

resource "aws_cloudwatch_log_group" "yada" {
  name = "Yada"

  tags = {
    Environment = "production"
    Application = "serviceA"
  }
}
  
```
I tested with terraform version v1.1.5 and tflocal, and localstack 0.14.4 and I got this error:
```
╷
│ Error: error configuring Terraform AWS Provider: loading configuration: credential type source_profile requires role_arn, profile default
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵
```

**Comment by steffyP** [comment] 2022-07-04 16:58
Hi @1141558,

thanks for providing the example. 
When I run this script, I get a different error - but it might have the same root:
In your "endpoints" you are not re-defining the endpoint for `logs`, and from the error message I would assume you run it with `terraform`? It seems like it's trying to connect to AWS, as this is the default endpoint.

If you want to try `tflocal` you do not need to specify any endpoint - everything is already handled by the wrapper.


For me, your script works, if I add this line to the `endpoints`:
```
    logs               = "http://localhost:4566"
```

I haven't tested with your specific SO envs yet. Please let us know if defining the endpoint works for you, or if you encounter another issue.

**Comment by steffyP** [comment] 2022-08-05 12:09
Hi @1141558, 

we haven't heard back from you - did adding the logs endpoint resolve your issue?
If it did, please close the issue. 🙏 

Else we would ask to provide more detailed information as we are not able to reproduce your issue. 
Thank you.

**Comment by whummer** [comment] 2022-08-09 11:49
Hi @1141558, please note that when using the `tflocal` command line, you do **not** need to (in fact you _should_ not) include the `provider` section in your Terraform script.

Simply add the resource definition to your `main.tf`:
```
resource "aws_cloudwatch_log_group" "yada" {
  name = "Yada"

  tags = {
    Environment = "production"
    Application = "serviceA"
  }
}
```
... and then deploy the script via `tflocal`: 
```
$ tflocal apply
```

Hope that helps - please let us know if this works, so we can close the issue.. Thanks!

**Comment by fabio-blanco** [comment] 2022-09-03 16:31
> please note that when using the `tflocal` command line, you do **not** need to (in fact you _should_ not) include the `provider` section in your Terraform script.

That's really bad because you are not able to test a real Terraform script with localstack in development environment since you have to adapt the real script to the localstack needs.

**Comment by whummer** [comment] 2022-10-16 20:56
@fabio-blanco Can you please elaborate on this point. Did you have a chance to give `tflocal` try? https://github.com/localstack/terraform-local In fact, `tflocal` is a tool that should enable you to deploy your real (production) Terraform scripts against without any modification required.

As a simple example - let's assume this minimal Terraform example that defines an S3 bucket:
```
resource "aws_s3_bucket" "test-bucket" {
  bucket = "my-bucket-123"
}
```
... You can then deploy this example against real AWS via `terraform`:
```
$ terraform deploy
...
```
... and you can deploy the exact same Terraform script against LocalStack using `tflocal` - without any modification:
```
$ tflocal apply
...
```

Closing this issue as resolved. Please keep us posted on how it goes. If you can share a few more details about your use case, we'll be happy to look into it in more details (feel free to re-open this issue, or create a new one).. Thanks!

**Closed by whummer** 2022-10-16 20:56 UTC
Labels: type: bug, area: integration/terraform, status: response required, aws:cloudwatch

**Comment by fabio-blanco** [comment] 2022-10-16 22:06
> Can you please elaborate on this point. 

Yes I can.

> Did you have a chance to give `tflocal` a try?

Yes I did. In fact that's the reason I've came to read this issue. Because I was facing some related error messages by using this tool.

> In fact, `tflocal` is a tool that should enable you to deploy your real (production) Terraform scripts against without any modification required.

If you're trying to test some real (production) Terraform scripts for building AWS infrastructure, then you **must** in fact have an AWS provider section in your production scripts. And that's the opposite of what you've told to Andre Silva in a previous comment:

>  you do not need to (in fact you should not) include the `provider` section in your Terraform script.

I was referring specifically to that comment since if you have to remove the `provider` section of the production scripts in order to be able to test it with `tflocal` then you're not testing the real thing. 

I don't know if I misunderstood what you've said before but it seems to me that your are now stating the exact opposite of what you've said before when you say "*without any modification required*".
