### ISSUE TITLE
[PRO] Neptune service getting NotImplementedError: websocket protocol is not implemented error 

### ISSUE THREAD

**Issue by ccarladev** [localstack/localstack#7810] opened 2023-03-06 15:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logs from inside the localstack container

2023-03-06T15:20:41.860 ERROR --- [-functhread5] hypercorn.error            : Error in ASGI Framework
2023-03-06T15:20:41.865791000Z Traceback (most recent call last):
2023-03-06T15:20:41.865813000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 22, in _handle
2023-03-06T15:20:41.865834000Z     await app(scope, receive, send, sync_spawn)
2023-03-06T15:20:41.865854000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 31, in __call__
2023-03-06T15:20:41.865874000Z     await self.app(scope, receive, send)
2023-03-06T15:20:41.865894000Z   File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 59, in __call__
2023-03-06T15:20:41.865914000Z     raise NotImplementedError(f"{scope['type']} protocol is not implemented")
2023-03-06T15:20:41.865933000Z NotImplementedError: websocket protocol is not implemented
2023-03-06T15:20:41.865953000Z 2023-03-06T15:20:41.860 ERROR --- [-functhread5] hypercorn.error            : Error in ASGI Framework
2023-03-06T15:20:41.865974000Z Traceback (most recent call last):
2023-03-06T15:20:41.865995000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 22, in _handle
2023-03-06T15:20:41.866014000Z     await app(scope, receive, send, sync_spawn)
2023-03-06T15:20:41.866034000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 31, in __call__
2023-03-06T15:20:41.866055000Z     await self.app(scope, receive, send)
2023-03-06T15:20:41.866075000Z   File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 59, in __call__
2023-03-06T15:20:41.866094000Z     raise NotImplementedError(f"{scope['type']} protocol is not implemented")
2023-03-06T15:20:41.866114000Z NotImplementedError: websocket protocol is not implemented
2023-03-06T15:20:41.917188000Z 2023-03-06T15:20:41.883 ERROR --- [-functhread5] hypercorn.error            : Error in ASGI Framework
2023-03-06T15:20:41.917226000Z Traceback (most recent call last):
2023-03-06T15:20:41.917248000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 22, in _handle
2023-03-06T15:20:41.917269000Z     await app(scope, receive, send, sync_spawn)
2023-03-06T15:20:41.917290000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 31, in __call__
2023-03-06T15:20:41.917312000Z     await self.app(scope, receive, send)
2023-03-06T15:20:41.917337000Z   File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 59, in __call__
2023-03-06T15:20:41.917357000Z     raise NotImplementedError(f"{scope['type']} protocol is not implemented")
2023-03-06T15:20:41.917383000Z NotImplementedError: websocket protocol is not implemented
2023-03-06T15:20:41.917417000Z 2023-03-06T15:20:41.883 ERROR --- [-functhread5] hypercorn.error            : Error in ASGI Framework
2023-03-06T15:20:41.917443000Z Traceback (most recent call last):
2023-03-06T15:20:41.917468000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/asyncio/task_group.py", line 22, in _handle
2023-03-06T15:20:41.917493000Z     await app(scope, receive, send, sync_spawn)
2023-03-06T15:20:41.917518000Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 31, in __call__
2023-03-06T15:20:41.917543000Z     await self.app(scope, receive, send)
2023-03-06T15:20:41.917568000Z   File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 59, in __call__
2023-03-06T15:20:41.917593000Z     raise NotImplementedError(f"{scope['type']} protocol is not implemented")
2023-03-06T15:20:41.917617000Z NotImplementedError: websocket protocol is not implemented

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I am using testcontainers to get the localstack/localstack-pro:latest image then start the container.
In the configuration of the container, I am adding the environment variables for LOCALSTACK_API_KEY and SERVICE for neptune.
Language used is golang.
Neptune Client is communicating with Amazon Neptune using a Websocket connection

### Environment

```markdown
- OS: macOS 13.1 (22C65)
- LocalStack: latest
```

**Comment by steffyP** [comment] 2023-03-14 09:24
Hi @ccarladev,

thanks for reporting. Can you please provide a code snippet, so that we have a reproducible sample of what you are trying to achieve?

In general, Neptune is available in LocalStack Pro. The Neptune database will accept websocket connection on its dedicated port. 
However, to get the correct port using testcontainers, there are some additional steps required. We have added an [example for RDS in our docs,](https://docs.localstack.cloud/user-guide/integrations/testcontainers/#special-setup-for-using-rds) for Neptune the setup would be similar.

**Comment by ccarladev** [comment] 2023-03-20 07:55
Hi! @steffyP! Thank you for the answer.

**Comment by steffyP** [comment] 2023-03-20 13:47
Hey @ccarladev,

thanks for the snippet. As I tried to explain before: LocalStack does only accept the wss connection on the port the Neptune Database is running. 
Your function `getEndpointForNeptune` seems to return the LocalStack endpoint though. This endpoint should be used to actually create the Neptune Cluster or Instance, using the `aws-sdk`. You will have to set the correct endpoint for the aws-sdk like [outlined in our docs](https://docs.localstack.cloud/user-guide/integrations/sdks/go/#examples). 

Then you create the Neptune Cluster (please also check the aws-sdk docs for details):
```
        neptuneSvc := neptune.New(sess)
	createDBClusterInput := &neptune.CreateDBClusterInput{
		DBClusterIdentifier: aws.String("test-neptune-cluster"),
		Engine:              aws.String("neptune"),
	}
	createDBClusterOutput, err := neptuneSvc.CreateDBCluster(createDBClusterInput)
```

You will have to wait until the status of the DB is `available`. Then you will retrieve the port when running `DescribeDBCluster`, which will look similar to `"Endpoint": "localhost:4510"`
This port (in my example `4510`) is where Neptune will be available within the container. 

Now to access this port from your test, you will have to tell Testcontainers to expose it first, and then retrieve the mapped port. 
Meaning you will have to add the to the list of `ExposedPorts` **beforehand**. Normally, when you only run one service in your test, you can assume that Neptune DB will allocate port `4510`. However, depending on your setup it could take any port in the range `4510-4559`. So you will have to adapt the `ExposedPorts` accordingly.

To find the mapped port, you would then need to run:
```
mappedPort, err := container.MappedPort(ctx, nat.Port(neptunePort))
```
where `neptunePort` would be the one you retrieved from `DescribeDBCluster` (4510 in my example). 
This is also where you want to connect to using `wss` protocol. 


Could you please to try your example accordingly and let us know if your are able to connect to Neptune DB? 🙏

**Comment by alexrashed** [comment] 2023-07-06 07:00
Hi @ccarladev!
Since it seems like this issue was caused by using the wrong endpoint in the SDK.
I'll close this issue for now, please feel free to create a new issue if you are still experiencing any issues.
Thanks!

**Closed by alexrashed** 2023-07-06 07:00 UTC
Labels: type: bug, status: response required, aws:neptune
