### ISSUE TITLE
Dockerhub run documentation gone

### ISSUE THREAD

**Issue by max-wittig** [localstack/localstack#149] opened 2017-07-10 06:42 UTC
A while ago, there was a guide to run localstack with one command 
<pre>docker run -it -p 4567-4578:4567-4578 -p 8080:8080 atlassianlabs/localstack</pre>
Now you have to install localstack/localstack first, before you can use the docker container
with `localstack start --docker`

Bringing back the docker run command would be easier, especially for user who just want to test localstack without installing it

**Comment by whummer** [comment] 2017-07-10 07:41
Thanks for the suggestion. The problem is that LocalStack meanwhile has quite a few configuration parameters, and some of these parameters are sensitive in the sense that it is critical to pass the right configuration based on the environment you are running (otherwise things might break).

After we've received a lot of requests related to which parameters to pass to `docker run`, the decision has been made to make the *CLI the (only) preferred way to start LocalStack*. Since then, the number of installation-/configuration-related requests has decreased drastically, because we can now abstract the complexity of different configuration parameters away from the user.

Note that we also try to keep the `docker-compose.yml` up to date, although long-term we may not be able to support all features (because configuration features in docker compose are inherently limited).

That said, the "default" `docker run` command is printed when you run the CLI command. On my machine it looks like this:
```
$ localstack start --docker
Starting local dev environment. CTRL-C to quit.
docker run -it  -p 8080:8080 -p 4567-4582:4567-4582 -v "/private/var/folders/lj/2rlhxf6d1xg96zwc_qjqtlr4f4b2f3/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/lj/2rlhxf6d1xg96zwc_qjqtlr4f4b2f3/T/localstack" "atlassianlabs/localstack" 
...
```

Also, we can consider moving the `localstack` CLI to a separate light-weight project which only installs the bare minimum of dependencies/libraries. We already created an `awslocal` CLI in a separate project (https://github.com/localstack/awscli-local), and we could follow the same pattern for the `localstack` CLI.

**Comment by whummer** [comment] 2017-08-06 06:59
The installation has recently been significantly improved, libraries are lazy-loaded and only downloaded when first used, and the dependencies for only installing the `localstack` CLI have been reduced to a minimum.

That said, we'll continue to improve the user experience to make LocalStack as light-weight, working out-of-the-box (zero-configuration), and cross-platform compatible as possible.

I'm closing this issue for now, but please feel free to share your experiences and suggestions for further improvement. Appreciated!

**Closed by whummer** 2017-08-06 06:59 UTC
Labels: documentation, installation
