### ISSUE TITLE
Issue creating local FIFO queue

### ISSUE THREAD

**Issue by monsieurBoutte** [localstack/localstack#1063] opened 2018-12-19 14:37 UTC
AWS expects your fifo queue to end with `.fifo`. 

When trying to spin up a local fifo queue w/ the following command:
```
awslocal sqs create-queue --queue-name chrono-queue.fifo --attributes "FifoQueue=true"
```
the output of the queue url becomes
```
{
    "QueueUrl": "http://localhost:4576/queue/chrono-queue_fifo"
}
```
also tried the following:
```
awslocal --endpoint-url=http://localhost:4576 sqs create-queue --queue-name "chrono-queue.fifo" --attributes "FifoQueue=true"
```
the output of the queue url, again,  becomes
```
{
    "QueueUrl": "http://localhost:4576/queue/chrono-queue_fifo"
}
```

this is problematic, as it's not being registered as a true `fifo` queue so when developing against it locally, it becomes an issue where I'm seeing the same messages getting read twice in the queue.

**Comment by whummer** [comment] 2018-12-30 13:14
Thanks for reporting @MrBoutte101 . I was unable to reproduce this issue.
```
$ awslocal sqs create-queue --queue-name chrono-queue.fifo --attributes "FifoQueue=true"
{
    "QueueUrl": "http://localhost:4576/queue/chrono-queue.fifo"
}
$ awslocal --version
aws-cli/1.15.26 Python/2.7.15 Darwin/17.7.0 botocore/1.10.84
```

Can you provide some more details about your environment / setup?

We also have an integration test which verifies that the FIFO is created and the name gets preserved properly: https://github.com/localstack/localstack/blob/master/tests/integration/test_sqs.py#L26-L27

**Comment by zaheershaik** [comment] 2019-06-26 05:05
I've noticed similar problem. Tested on localstack:0.9.5.

```
$ aws sqs create-queue --endpoint-url=http://localhost:4576 --queue-name chrono-queue.fifo --attributes "FifoQueue=true"
{
    "QueueUrl": "http://localhost:4576/queue/chrono-queue_fifo"
}
```

**Comment by whummer** [comment] 2019-11-26 23:58
Thanks for reporting @monsieurBoutte @zaheershaik . This appears to be fixed in the latest version:
```
$ awslocal sqs create-queue --queue-name chrono-queue.fifo --attributes "FifoQueue=true"
{
    "QueueUrl": "http://localhost:4576/queue/chrono-queue.fifo"
}
```

**Closed by whummer** 2019-11-26 23:58 UTC
Labels: needs-triaging
