### ISSUE TITLE
Expected hash not equal to calculated hash when uploading a stream to S3 using .net aws sdk

### ISSUE THREAD

**Issue by matthall88** [localstack/localstack#1562] opened 2019-09-13 13:43 UTC
using localstack in docker, latest version

The code has been tested in a fully deployed AWS environment and works as expected, error only occurs locally against localstack

When attempting to upload a memory stream of an image to S3 using the following code:

`
var request = new PutObjectRequest
{
    InputStream = stream,
    Key = key,
    BucketName = bucketName,
    ContentType = "image/png",
};

await _s3.PutObjectAsync(request);
`

OR

`
var fileTransferUtility = new TransferUtility(_s3)
await fileTransferUtility.UploadAsync(stream, bucketName, key);
`

(in both cases "_s3" is an injected AmazonS3Client)

The underlying AWSSDK throws an exception:

`
Amazon.Runtime.AmazonClientException: Expected hash not equal to calculated hash
at Amazon.S3.Internal.AmazonS3ResponseHandler.CompareHashes(String etag, Byte[] hash)
at Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers(IExecutionContext executionContext)
at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)

`

**Comment by whummer** [comment] 2019-10-05 10:46
Thanks for reporting @matthall88  . Looks like this was an issue with HTTP chunked encoding, which should be fixed in the latest version, as also confirmed in #1571 . Please re-open this issue if this problem persists. Thanks

**Comment by trevor-thoele** [comment] 2020-02-04 17:14
We just hit this same problem with the latest image, but it does not exist in 0.10.7. Our code is effectively equivalent to the initial post. Has there been a regression here?

**Comment by whummer** [comment] 2020-02-05 19:29
Thanks for the update @trevor-thoele . This issue could be related to #2015 , and is potentially fixed in #2021 . Can you please give it another try with the `latest` version? Please report here if the problem persists. Thanks

**Comment by jsk95** [comment] 2020-06-17 06:31
I'm still having this issue in 0.11.2 @whummer

**Comment by jomonkl** [comment] 2020-08-07 09:30
Still getting the error of hash not equal to calculated hash.
But if i use the "CORE 3.1" framework, it works without issue. 
When the target ,net framework is "4.7.2", it hits the error.  And unfortunately, I need to use this target framework.

I tried latest version and older version of the package as well. (3.3.111.31 and 3.3.111.38)

/************/
using (FileStream fs = new FileStream(localFolderPath + "\\" + fileName, FileMode.Create, FileAccess.Write))
                {
                    byte[] data = new byte[32768];
                    int bytesRead = 0;
                    do
                    {
                        bytesRead = responseStream.Read(data, 0, data.Length);
                        fs.Write(data, 0, bytesRead);
                    }
                    while (bytesRead > 0);
                    fs.Flush();
                }
/********************/

**Comment by jomonkl** [comment] 2020-08-07 13:24
Got it resolved after the GetObjectResponse was removed from "using" format.

Error Code :
using (GetObjectResponse objResponse = await client.GetObjectAsync(objRequest))
{
*********
}

No Error Code after removing "using" structure as below.
GetObjectResponse objResponse = await client.GetObjectAsync(objRequest);

**Comment by whummer** [comment] 2020-08-07 13:29
Thanks for the update @jomonkl . Glad you were able to get it working. Wondering if that is a general .Net framework error (I'm not too familiar with it) - is the issue on LocalStack side resolved now? Thanks

**Comment by jomonkl** [comment] 2020-08-07 13:36
@whummer Yes, as of now, no error after i changed the way i wrote the code.
I'm also not sure if anything to do with the .Net framework. Because in .net CORE, the same code worked without error. The issue happened only in the non-CORE framework.

Thank you for your prompt response on this. 👍

**Closed** 2020-08-07 14:42 UTC
