### ISSUE TITLE
Cognito - non-existing user is added to the user pool when trying to authenticate with a failing migration trigger

### ISSUE THREAD

**Issue by yonatandbinahai** [localstack/localstack#3945] opened 2021-04-29 14:16 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When trying to authenticate with a **non-existing** user, and a migration lambda trigger is defined and returns an error, the user is still added to the user pool, and the authentication succeeds (tokens are returned to the client).

## Expected behavior

User should not be added to the user pool, and an authentication error should be returned to the client.

## Actual behavior

User is added to the user pool, and a successful response with tokens is returned to the client.

# Steps to reproduce

1) Define a user pool with a migration lambda trigger, which always returns an error (e.g. status code 401).
2) Call InitiateAuth with any (non-existent) username
--> User is added to the user pool and a successful response with tokens is returned

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Client code:
```
      res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'missing_user@example.com',
          PASSWORD: 'pass',
        }
      }).promise();

    // res contains response with tokens
```

Migration lambda (python):

```
def handler(event, context):
    raise Exception('Incorrect username or password')
```
...

**Comment by whummer** [comment] 2021-04-29 21:18
Thanks for reporting @John-D8 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted if the problem persists. Thanks for your help!

**Comment by John-D8** [comment] 2021-05-01 10:13
@whummer still reproduces

**Comment by whummer** [comment] 2021-05-08 08:45
Thanks for the update @John-D8 - just to confirm, does this issue still persist with the `latest` Docker image (we haven't been able to reproduce it anymore..). Thanks

**Comment by John-D8** [comment] 2021-05-08 09:03
@whummer it seems it's still reproduced when the migration lambda throw an exception:
```
raise Exception("User not authenticated")
```

**Comment by whummer** [comment] 2022-04-01 15:22
Hi @yonatandbinahai, it's been a while since this was raised - in the meantime we have pushed a couple of enhancements for the Cognito user migration logic. Assuming that this is resolved in the meantime, but please do let us know if the problem persists - we'll be happy to look into it in more detail with a reproducible sample. Thanks!

**Closed by whummer** 2022-04-01 15:22 UTC
Labels: bug, priority-high, needs-triaging, aws:cognito
