### ISSUE TITLE
Unable to restore from recorded_api_calls.json

### ISSUE THREAD

**Issue by theiviaxx** [localstack/localstack#2527] opened 2020-06-08 04:52 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Unable to restore (s3) data when running localstack via docker-compose.  Everything works fine the first time, but after stopping and restarting the service it fails.  Enabling the DEBUG=1 env var showed that this actually fails.  Without this, the service reports that it successfully restored the commands.

## Expected behavior
To be able to run and stop localstack via docker-compose and persist the uploaded files to s3

## Actual behavior
Unhandled exceptions are thrown when trying to restore

# Steps to reproduce
1. Run localstack via docker-compose
1. Add a bucket
1. add a file to bucket
1. stop localstack
1. Run localstack via docker-compose
1. Exception when trying to restore commands from `recorded_api_calls.json`

## Command used to start LocalStack
```
C:\github\localstack> set DATA_DIR=/tmp/localstack/data
C:\github\localstack> set TMPDIR=c:\tmp
C:\github\localstack> set DEBUG=1
C:\github\localstack> docker-compose up
```

I get unhandled exceptions like this when trying to restore:

```
localstack_main | 2020-06-08 04:40:03,139:API: 127.0.0.1 - - [08/Jun/2020 04:40:03] "PUT /test-bucket/0c/fc/da403ee84d6f366506efd65d6cdc2b9cc705?uploadId=f8loNGp9dH3oGyf0hyDF7GkuHQO7iAFb3s7Kh8Fj9h86LWjHlVdTLMRw&partNumber=1 HTTP/1.1" 500 -
localstack_main | 2020-06-08 04:40:03,139:API: 127.0.0.1 - - [08/Jun/2020 04:40:03] "PUT /test-bucket/0c/fc/da403ee84d6f366506efd65d6cdc2b9cc705?uploadId=f8loNGp9dH3oGyf0hyDF7GkuHQO7iAFb3s7Kh8Fj9h86LWjHlVdTLMRw&partNumber=1 HTTP/1.1" 500 -
localstack_main | 2020-06-08 04:40:03,139:API: 127.0.0.1 - - [08/Jun/2020 04:40:03] "PUT /test-bucket/0c/fc/da403ee84d6f366506efd65d6cdc2b9cc705?uploadId=f8loNGp9dH3oGyf0hyDF7GkuHQO7iAFb3s7Kh8Fj9h86LWjHlVdTLMRw&partNumber=1 HTTP/1.1" 500 -
localstack_main | 2020-06-08 04:40:03,153:API: Error on request:
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_main |     execute(self.server.app)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_main |     application_iter = app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 163, in __call__
localstack_main |     return backend_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_main |     return self.wsgi_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_main |     response = self.handle_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
localstack_main |     result = self.callback(request, request.url, {})
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 936, in key_or_control_response
localstack_main |     response = self._key_response(request, full_url, headers)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1081, in _key_response
localstack_main |     return self._key_response_put(
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 131, in s3_key_response_put
localstack_main |     result = s3_key_response_put_orig(request, body, bucket_name, query, key_name, headers, *args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1184, in _key_response_put
localstack_main |     key = self.backend.set_part(bucket_name, upload_id, part_number, body)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1507, in set_part
localstack_main |     multipart = bucket.multiparts[multipart_id]
localstack_main | KeyError: 'f8loNGp9dH3oGyf0hyDF7GkuHQO7iAFb3s7Kh8Fj9h86LWjHlVdTLMRw'
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-197) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-06-28 12:02
Thanks for reporting @theiviaxx . A small fix for S3 persistence has been pushed recently - can you please do a `docker pull localstack/localstack` and give it a try with the `latest` version of the Docker image? If the problem persists, can you please provide a small, isolated example with the full sequence of actions, to make it easier to reproduce this issue. Thanks!

**Comment by theiviaxx** [comment] 2020-06-28 20:28
Pulled and tested this on 598200c7ea153287a92052d6038534b277e56e2d but still get the same error:

```
localstack_main | 2020-06-28 20:24:50,533:API: 127.0.0.1 - - [28/Jun/2020 20:24:50] "POST /test-bucket/ab/23/b2b5d8c312a5fd2acdc6eed15605ebfaa477?uploadId=hLLnzlixKHEmUQPcjjcpkc2PXhRjCvT1ImX2YhCaglo02czVNVjSNfbTw HTTP/1.1" 500 -
localstack_main | 2020-06-28 20:24:50,533:API: 127.0.0.1 - - [28/Jun/2020 20:24:50] "POST /test-bucket/ab/23/b2b5d8c312a5fd2acdc6eed15605ebfaa477?uploadId=hLLnzlixKHEmUQPcjjcpkc2PXhRjCvT1ImX2YhCaglo02czVNVjSNfbTw HTTP/1.1" 500 -
localstack_main | 2020-06-28 20:24:50,533:API: 127.0.0.1 - - [28/Jun/2020 20:24:50] "POST /test-bucket/ab/23/b2b5d8c312a5fd2acdc6eed15605ebfaa477?uploadId=hLLnzlixKHEmUQPcjjcpkc2PXhRjCvT1ImX2YhCaglo02czVNVjSNfbTw HTTP/1.1" 500 -
localstack_main | 2020-06-28T20:24:50:INFO:localstack.utils.persistence: Restored 43 API calls from persistent file: /tmp/localstack/data/recorded_api_calls.json
localstack_main | 2020-06-28 20:24:50,540:API: Error on request:
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_main |     execute(self.server.app)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_main |     application_iter = app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 163, in __call__
localstack_main |     return backend_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_main |     return self.wsgi_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_main |     response = self.handle_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
localstack_main |     result = self.callback(request, request.url, {})
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 936, in key_or_control_response
localstack_main |     response = self._key_response(request, full_url, headers)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1091, in _key_response
localstack_main |     return self._key_response_post(request, body, bucket_name, query, key_name)
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 121, in s3_key_response_post
localstack_main |     result = s3_key_response_post_orig(request, body, bucket_name, query, key_name, *args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1628, in _key_response_post
localstack_main |     key = self.backend.complete_multipart(bucket_name, upload_id, body)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1478, in complete_multipart
localstack_main |     multipart = bucket.multiparts[multipart_id]
localstack_main | KeyError: 'hLLnzlixKHEmUQPcjjcpkc2PXhRjCvT1ImX2YhCaglo02czVNVjSNfbTw'```

**Comment by whummer** [comment] 2020-06-28 20:33
Thanks for confirming @theiviaxx . What are the characteristics of the file (size, content), or is it reproducible with any kind of file? Since S3 supports different flavors of uploading files, it would be great if you could share a small code snippet with us that contains the actual code you're using to run this test. Thanks!

**Comment by theiviaxx** [comment] 2020-06-28 23:35
unfortunately I don't have an isolated test as I'm using other libraries to manage it [(django-storages and boto3)](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) and 
the images are small PNGs see attached.  I could be missing a setting somewhere with the above libs that could cause issues with localstack.  Still new to all this.

![addthis](https://user-images.githubusercontent.com/173465/85961145-44777d00-b95d-11ea-8ded-90268205d703.png)

**Comment by szdrasiak** [comment] 2020-07-03 09:24
I can confirm issue, I'm getting same errors after I upload any kind of file using 
`aws --region=eu-west-1 --endpoint-url=http://localhost:4566 s3 cp ...`  or after I deploy lambda using `serverless-localstack`

os: linux
localstack_version: 0.11.3

```
  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=serverless,events,cloudformation,ses,secretsmanager
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - HOST_TMP_FOLDER=${TMPDIR}
 volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/tmp/localstack
```
localstack_data - is external volume

**Comment by theiviaxx** [comment] 2020-07-09 03:05
I only have the s3 service enabled, does that have dependencies on anything else that might contribute to this error?

**Comment by timothymugayi** [comment] 2020-07-14 06:24
Getting the same error only occurs when having DATA_DIR set 

```
localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    networks:
      - localstack-net
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=iam,lambda,s3,sqs,sts
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${HOME:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
```



```
localstack       |     multipart = bucket.multiparts[multipart_id]
localstack       | KeyError: 'GVpYnFiWQYKKhL2ADsk2ddW7YhxOrsujttgSN3JNbGmewh7PZU6lmPuxpw'
localstack       | 2020-07-14 06:15:12,865:API: Error on request:
localstack       | Traceback (most recent call last):
localstack       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack       |     execute(self.server.app)
localstack       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack       |     application_iter = app(environ, start_response)
localstack       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 163, in __call__
localstack       |     return backend_app(environ, start_response)
localstack       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack       |     return self.wsgi_app(environ, start_response)

```

**Comment by theiviaxx** [comment] 2020-07-14 16:13
@timothymugayi  does it actually restore files though?

**Comment by lalec** [comment] 2020-10-01 13:56
@whummer any update on this?

**Comment by DouglasPuppioPereira** [comment] 2020-11-11 16:45
@whummer I am also facing the same issue related to S3 data not being persisted across restarts of Localstack. Any updates on that would be helpful. Thanks!

**Comment by ShadabShariff** [comment] 2021-02-07 08:05
Hi @theiviaxx  @DouglasPuppioPereira, I have tried to reproduce the persistence of the files uploaded on S3 on restart of LocalStack and it currently working as expected with the DATA_DIR env. variable. It would be helpful, if you could share the LocalStack version and the snippet of code that could help in reproducing the issue at our end. Thanks.

**Comment by theiviaxx** [comment] 2021-02-07 16:13
@ShadabShariff ok let me pull latest and try again, will report back soon

**Comment by theiviaxx** [comment] 2021-02-07 16:25
@ShadabShariff still getting this with latest code on master.  My startup env is as above and here are my steps:

1. aws --endpoint-url http://127.0.0.1:4566 s3 mb s3://storage-test
2. upload to endpoint with boto3 python lib
3. Verify images are found and served correctly
4. shutdown docker-compose
5. restart docker compose as above
6. In the debug log, you can see it try each line in the `recorded_api_calls.json` and error with:

```
localstack_main | 2021-02-07 16:19:22,145:API: 127.0.0.1 - - [07/Feb/2021 16:19:22] "POST /storage-test/d7/ac/646f23b32394a69ff6570a3fcd691eaef6a2?uploadId=ICNBGyUp9PdvieepH3z2dQgoVrkVUdHyazgfaUbrLSO0TINa0x39eEXLXQ HTTP/1.1" 500 -
localstack_main | 2021-02-07T16:19:22:INFO:localstack.utils.persistence: Restored 19 API calls from persistent file: /tmp/localstack/data/recorded_api_calls.json
localstack_main | 2021-02-07T16:19:22:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 9508.853912353516ms
localstack_main | 2021-02-07 16:19:22,155:API: Error on request:
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_main |     execute(self.server.app)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_main |     application_iter = app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 173, in __call__
localstack_main |     return backend_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_main |     return self.wsgi_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_main |     response = self.handle_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 151, in __call__
localstack_main |     result = self.callback(request, request.url, {})
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 975, in key_or_control_response
localstack_main |     response = self._key_response(request, full_url, headers)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1146, in _key_response
localstack_main |     return self._key_response_post(request, body, bucket_name, query, key_name)
localstack_main |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 130, in s3_key_response_post
localstack_main |     result = s3_key_response_post_orig(request, body, bucket_name, query, key_name, *args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1741, in _key_response_post
localstack_main |     multipart = bucket.multiparts[multipart_id]
localstack_main | KeyError: 'ICNBGyUp9PdvieepH3z2dQgoVrkVUdHyazgfaUbrLSO0TINa0x39eEXLXQ'
```

And the images are not found.

I'll try to debug this and see if there is something i am missing on my end

**Comment by ShadabShariff** [comment] 2021-02-07 21:29
Hi @theiviaxx, thanks for your time and the confirmation, could you please confirm the **LocalStack version** which would be printed in the logs shared above, it would help as i was unable to find the same from the above logs. Also an isolated code snippet for the boto3 upload that is used for the upload of images would be helpful as well (Just ensuring the steps to reproduce the issue). Thanks.

**Comment by suitap** [comment] 2021-03-19 13:47
Hi there, I find a simple repro using docker.

```shell
docker run -d -e DEBUG=1 -e DATA_DIR=/tmp/localstack/data localstack/localstack:0.12.7
docker exec -it <container_id> bash

cd `mktemp -d`

dd if=/dev/zero of=largefile_1.dat bs=900  count=1
dd if=/dev/zero of=largefile_2.dat bs=2000 count=1

aws configure set default.s3.multipart_threshold 1KB

awslocal s3api create-bucket --bucket s3bucket
awslocal s3 cp largefile_1.dat s3://s3bucket/
awslocal s3 cp largefile_2.dat s3://s3bucket/

awslocal s3 ls s3bucket                                 ## shows largefile_1.dat and largefile_2.dat
exit

docker restart <container_id>                           ## replays api calls
docker exec -it <container_id> bash

awslocal s3 ls s3bucket                                 ## shows only largefile_1.dat, where is largefile_2.dat ?

less /tmp/localstack_infra.err                          ## shows stacktrace similar to reported one
```

**Comment by latkins** [comment] 2021-04-07 16:31
I have this issue, using `LocalStack version: 0.12.9.1`.

**Comment by DJanyavula** [comment] 2021-04-19 07:35
Still have this issue with latest version. I observed that smaller files are restored properly, I have issue with restoring larger files. I tested with file of < 1 MB and another file with size 1.6 GB. All multipart uploads for 1.6 GB sized file requests failed
` 2021-04-19 07:22:15,910:API: 127.0.0.1 - - [19/Apr/2021 07:22:15] "PUT /test/test.csv?uploadId=m5tZebYm451AEkNHoH6Mn9VCJ8Z89mkAZoHfum8Z6DXGr86dzdD4NLg&partNumber=143 HTTP/1.1" 500 -
 2021-04-19 07:22:15,934:API: Error on request:
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
     execute(self.server.app)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
     application_iter = app(environ, start_response)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 177, in __call__
     return backend_app(environ, start_response)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
     return self.wsgi_app(environ, start_response)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
     response = self.handle_exception(e)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
     response = self.full_dispatch_request()
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
     rv = self.dispatch_request()
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
     result = self.callback(request, request.url, {})
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1001, in key_or_control_response
     response = self._key_response(request, full_url, headers)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1162, in _key_response
     return self._key_response_put(
   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 141, in s3_key_response_put
     result = s3_key_response_put_orig(request, body, bucket_name, query, key_name, headers, *args, **kwargs)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1284, in _key_response_put
     key = self.backend.set_part(bucket_name, upload_id, part_number, body)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1622, in set_part
     multipart = bucket.multiparts[multipart_id]
 KeyError: 'm5tZebYm451AEkNHoH6Mn9VCJ8Z89mkAZoHfum8Z6DXGr86dzdD4NLg'`

**Comment by oronkastel** [comment] 2021-05-31 09:29
Hi,
Is there any update on this issue?

Thanks.

**Comment by dolevhadad** [comment] 2021-05-31 12:28
Hi, 
you can see more details about this issue in case #4087 
To workaround this problem you need to change the threshold to be larger then the file that you want to upload.

> s3 =
   multipart_threshold = 64MB

**Comment by ppatidar-conga** [comment] 2021-11-19 15:06
I am running that on windows and i could see that operations and request are being saved in recorded_api_calls.json
however once container is stopped and again restarted , it doesn't reload and restore the data.It doesnt show any error specific to restore like shown above still it doesnt work out.

**Comment by whummer** [comment] 2021-12-13 11:58
Thanks for reporting @latkins @szdrasiak @oronkastel @ppatidar-conga @dolevhadad @DJanyavula @suitap @ShadabShariff @theiviaxx @DouglasPuppioPereira .

Unfortunately, the "record&replay" based persistence mechanism (storing API calls to `recorded_api_calls.json` and re-running them on restart) has many conceptual flaws which cannot be easily addressed in a robust and generic way. In fact, this persistence mechanism has created more problems and headaches than benefits for most users recently (as indicated by the various bug reports in this thread). 

Due to these fundamental issues, we have decided to discontinue support for the record&replay based legacy persistence. Please find more details in the release notes for version 0.13.1: https://github.com/localstack/localstack/releases/tag/v0.13.1 . We have introduced an environment variable `LEGACY_PERSISTENCE` which can be used to continue using the legacy persistence; currently the default setting is still `LEGACY_PERSISTENCE=1` (i.e., no changes required on your end), but this option may default to `LEGACY_PERSISTENCE=0` in an upcoming release.

The recommended solution/workaround for now is to disable the `DATA_DIR` configuration, and instead use init scripts to pre-populate your LocalStack instance with the required state at startup (see documentation around `INIT_SCRIPTS_PATH`/`/docker-entrypoint-initaws.d` in the README). We hope that helps reduce the headaches around `KeyError`, slow startups, and other issues introduced by the legacy persistence.. Thanks!

**Closed** 2022-01-03 10:52 UTC
Labels: bug, needs-triaging, won't fix, persistence, workaround-in-place

**Comment by mistriel** [comment] 2023-04-24 09:25
I think it was a very important feature of localstack as it allowed to persist "AWS snapshots" of a certain state.
removing it - is taking a very important core feature from this gem.
