### ISSUE TITLE
bug: ARN of log group not fetched correctly when granting role, resulting in MalformedPolicyDocumentException

### ISSUE THREAD

**Issue by philipholtseeland** [localstack/localstack#6968] opened 2022-10-03 14:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running CDK with Kotlin against LocalStack Pro.

When creating a role and log group, LocalStack fails when trying to grant the role to the log group, with the error message 

> An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource my-stack-myloggroup... must be in ARN format or "*".

This seems to happen when creating the role first as a variable, but not when creating it directly as a parameter. 

The CloudFormation template looks correct, but the error also happens when using `cloudformation deploy` instead of `cdklocal deploy`.

Logs from LocalStack:
```
localstack    | 2022-10-03T14:22:50.389 DEBUG --- [   asgi_gw_2] l.s.c.provider             : Executing change set "cdk-deploy-change-set" for stack "my-stack" with 4 resources ...
localstack    | 2022-10-03T14:22:50.400  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.ExecuteChangeSet => 200
localstack    | 2022-10-03T14:22:50.415  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack    | 2022-10-03T14:22:50.466 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Handling "Add" for resource "myrole97476C1B" (1/4) type "AWS::IAM::Role" in loop iteration 1 (should_deploy=True)
localstack    | 2022-10-03T14:22:50.470 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Running action "create" for resource type "IAM::Role" id "myrole97476C1B"
localstack    | 2022-10-03T14:22:50.473 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Request for resource type "IAM::Role" in region eu-north-1: create_role {'AssumeRolePolicyDocument': '{"Statement": [{"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"Service": ""}}], "Version": "2012-10-17"}', 'RoleName': 'my-stack-myrole97476C1B-7004125b'}
localstack    | 2022-10-03T14:22:50.738 DEBUG --- [   asgi_gw_1] l.services.plugins         : checking service health logs:4566
localstack    | 2022-10-03T14:22:50.833 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Handling "Add" for resource "myroleDefaultPolicyFEF25ABF" (1/3) type "AWS::IAM::Policy" in loop iteration 1 (should_deploy=True)
localstack    | 2022-10-03T14:22:50.860 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Dependency for resource {'Type': 'AWS::IAM::Policy', 'Metadata': {'aws:cdk:path': 'my-stack/my-role/DefaultPolicy/Resource'}, 'LogicalResourceId': 'myroleDefaultPolicyFEF25ABF', 'Properties': {'PolicyDocument': {'Statement': [{'Action': ['logs:CreateLogStream', 'logs:PutLogEvents'], 'Effect': 'Allow', 'Resource': 'my-stack-myloggroupB3C64303-4d092b27'}], 'Version': '2012-10-17'}, 'PolicyName': 'myroleDefaultPolicyFEF25ABF', 'Roles': ['my-stack-myrole97476C1B-7004125b']}, '_state_': {}} not yet deployed: myloggroupB3C64303 {'Type': 'AWS::Logs::LogGroup', 'Properties': {'RetentionInDays': 731}, 'UpdateReplacePolicy': 'Retain', 'DeletionPolicy': 'Retain', 'Metadata': {'aws:cdk:path': 'my-stack/my-log-group/Resource'}, 'LogicalResourceId': 'myloggroupB3C64303'}
localstack    | 2022-10-03T14:22:50.883 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Handling "Add" for resource "myloggroupB3C64303" (2/3) type "AWS::Logs::LogGroup" in loop iteration 1 (should_deploy=True)
localstack    | 2022-10-03T14:22:50.883 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Running action "create" for resource type "Logs::LogGroup" id "myloggroupB3C64303"
localstack    | 2022-10-03T14:22:50.885 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Request for resource type "Logs::LogGroup" in region eu-north-1: create_log_group {'logGroupName': 'my-stack-myloggroupB3C64303-4d092b27'}
localstack    | 2022-10-03T14:22:51.275 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Extract resource attribute: Parameter Ref
localstack    | 2022-10-03T14:22:51.602  WARN --- [  Thread-556] l.u.c.template_deployer    : Unable to deploy resource type "CDK::Metadata": {"Type": "AWS::CDK::Metadata", "Metadata": {"aws:cdk:path": "my-stack/CDKMetadata/Default"}, "Condition": "CDKMetadataAvailable", "LogicalResourceId": "CDKMetadata", "Properties": {"Analytics": "v2:deflate64:H4sIAAAAAAAA/zVOSwrCMBQ8i/vkabXgAboQxEWpB5BnGsuzaZ7ko0jI3W1TXM2PGWYP9QGqDX68VP0oDd0hXQOqUczWLRFOkDo2WjQPW7BlQ+q7yJVlYXjwkC48nBzH15L8ec6lpj1Hp8pEw7anQGyzOOMbt9URdlDPB56eSLpoA00auhV/ma8+RZwAAAA=", "PhysicalResourceId": "cdk-meta-adcdb2e5"}}
localstack    | 2022-10-03T14:22:51.602 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Handling "Add" for resource "CDKMetadata" (2/2) type "AWS::CDK::Metadata" in loop iteration 1 (should_deploy=False)
localstack    | 2022-10-03T14:22:51.647 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Handling "Add" for resource "myroleDefaultPolicyFEF25ABF" (1/1) type "AWS::IAM::Policy" in loop iteration 2 (should_deploy=True)
localstack    | 2022-10-03T14:22:51.669 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Running action "create" for resource type "IAM::Policy" id "myroleDefaultPolicyFEF25ABF"
localstack    | 2022-10-03T14:22:51.704 DEBUG --- [  Thread-556] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "my-stack": An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource my-stack-myloggroupB3C64303-4d092b27 must be in ARN format or "*". Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1570, in _run
localstack    |     self.do_apply_changes_in_loop(changes, stack)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1647, in do_apply_changes_in_loop
localstack    |     self.apply_change(change, stack=stack)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1724, in apply_change
localstack    |     result = deploy_resource(self, resource_id)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 853, in deploy_resource
localstack    |     result = execute_resource_action(resource_id, stack, ACTION_CREATE)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 891, in execute_resource_action
localstack    |     result = func["function"](resource_id, resources, resource_type, func, stack_name)
localstack    |   File "/opt/code/localstack/localstack/services/cloudformation/models/iam.py", line 400, in _create
localstack    |     iam.put_role_policy(
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
localstack    |     return self._make_api_call(operation_name, kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 934, in _make_api_call
localstack    |     raise error_class(parsed_response, operation_name)
localstack    | botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource my-stack-myloggroupB3C64303-4d092b27 must be in ARN format or "*".
localstack    |
```

### Expected Behavior

Deploy should work without error. This works fine when deploying to an AWS environment.

When the deploy has been tried, the log group exists and has an ARN:
``` 
$ aws --endpoint-url http://localhost:4566 logs describe-log-groups
{
    "logGroups": [
        {
            "logGroupName": "my-stack-myloggroupB3C64303-4d092b27",
            "creationTime": 1664806970890,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:eu-north-1:000000000000:log-group:my-stack-myloggroupB3C64303-4d092b27",
            "storedBytes": 0
        }
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```
docker-compose up
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
cdklocal deploy my-stack
```
or 
```
cdklocal synth
aws cloudformation deploy --endpoint-url http://localhost:4566 --stack-name my-stack --template cdk.out/my-stack.template.json 
```   

#### Stack code
Initialized in App:
```
MyStack(this, "my-stack")
```

MyStack.kt:
```
import software.amazon.awscdk.Stack
import software.amazon.awscdk.services.iam.Role
import software.amazon.awscdk.services.iam.ServicePrincipal
import software.amazon.awscdk.services.logs.LogGroup
import software.constructs.Construct

class MyStack(scope: Construct, id: String) : Stack(scope, id) {
    init {
        val role = Role.Builder
            .create(this, "my-role")
            .assumedBy(ServicePrincipal(""))
            .build()

        LogGroup.Builder.create(this, "my-log-group")
            .build()
            .apply {
                grant(role, "logs:CreateLogStream", "logs:PutLogEvents")
            }
    }
}
```

### Environment

```markdown
- OS: macOS 12.6
- LocalStack: 1.1.0
- aws-cdk: 2.43.1
- aws-cdk-local: 2.15.0
- aws-cli: 2.7.25
```

### Anything else?

This issue seems related to the issue in #6726, though the resources are different.

---

Using the following code instead does not result in this error:
MyStack.kt:
```
import software.amazon.awscdk.Stack
import software.amazon.awscdk.services.iam.Role
import software.amazon.awscdk.services.iam.ServicePrincipal
import software.amazon.awscdk.services.logs.LogGroup
import software.constructs.Construct

class MyStack(scope: Construct, id: String) : Stack(scope, id) {
    init {
        LogGroup.Builder.create(this, "my-log-group")
            .build()
            .apply {
                grant(
                    Role.Builder
                        .create(this, "my-role")
                        .assumedBy(ServicePrincipal(""))
                        .build(),
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                )
            }
    }
}
```

**Comment by philipholtseeland** [comment] 2024-01-08 13:13
I don't have a way to test this anymore, but I would assume it is still an issue if it hasn't been assessed, so should probably still be checked.

**Comment by dfangl** [comment] 2024-01-31 15:53
I tried to reproduce this issue, both with a typescript based and a java based cdk stack, neither fails.
Typescript:
```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';

export class LocalstackIssues6968Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here
    const role = new iam.Role(this, 'Role', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
    });
    const logGroup = new logs.LogGroup(this, 'Log Group');
    logGroup.grant(role, "logs:CreateLogStream", "logs:PutLogEvents")
  }
}
```

Java:

```java
import software.constructs.Construct;
import software.amazon.awscdk.Stack;
import software.amazon.awscdk.StackProps;
import software.amazon.awscdk.services.iam.Role;
import software.amazon.awscdk.services.iam.ServicePrincipal;
import software.amazon.awscdk.services.logs.LogGroup;
// import software.amazon.awscdk.Duration;
// import software.amazon.awscdk.services.sqs.Queue;

public class KotlinCdkStack extends Stack {
    public KotlinCdkStack(final Construct scope, final String id) {
        this(scope, id, null);
    }

    public KotlinCdkStack(final Construct scope, final String id, final StackProps props) {
        super(scope, id, props);

        // The code that defines your stack goes here
        Role role = Role.Builder
            .create(this, "my-role")
            .assumedBy(new ServicePrincipal(""))
            .build();

        LogGroup.Builder.create(this, "my-log-group")
            .build()
                .grant(role, "logs:CreateLogStream", "logs:PutLogEvents");


        // example resource
        // final Queue queue = Queue.Builder.create(this, "KotlinCdkQueue")
        //         .visibilityTimeout(Duration.seconds(300))
        //         .build();
    }
}
```
I also cannot see a logical difference between your two provided cdk files, except for inlining the role. Without seeing what that would change in the cloudformation template back then, I sadly cannot even guess why it would make a difference.

For now, I would close this, should anyone else encounter this issue, please open another issue and we will take a look again. I would however guess that it has been resolved in the meantime, due to the massive code changes since the original issue report.

Thank you for reporting this nevertheless, and sorry for the long wait!

**Closed by dfangl** 2024-01-31 15:53 UTC
Labels: type: bug, aws:iam, area: integration/aws-cdk, aws:logs, status: backlog
