### ISSUE TITLE
bug: Different error response when missing API Gateway auth header

### ISSUE THREAD

**Issue by lukeprv** [localstack/localstack#10636] opened 2024-04-10 16:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create an API Gateway REST API with an authorizer function and deploy into LocalStack:

```
Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: "Api"
      StageName: Example
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: Auth
        ApiKeyRequired: true
        Authorizers:
          Auth:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 5

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AuthorizerFunction"
      PackageType: Image
      ImageUri: !Sub "${ImageRepositoryUri}:${ImageTag}"
      ImageConfig:
        Command:
          - example.authorizer_handler

  MethodFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "MethodFunction"
      PackageType: Image
      ImageUri: !Sub "${ImageRepositoryUri}:${ImageTag}"
      ImageConfig:
        Command:
          - example.method_function
      Events:
        Generic:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: Api
```

Make a request to the API Gateway endpoint without the auth header:

```
$ curl -i -X POST http://example.localstack.address:4566/endpoint/
HTTP/1.1 403 
Content-Type: text/html; charset=utf-8
x-amzn-errortype: MissingAuthenticationTokenException
Content-Length: 108
Connection: close
date: Tue, 09 Apr 2024 15:32:17 GMT
server: hypercorn-h11

{"Type": "User", "message": "Missing Authentication Token", "__type": "MissingAuthenticationTokenException"}
```

### Expected Behavior

* The status code should be 401 (not 403) 
* Different `x-amzn-errortype` header
* Different body

```
$ curl -i -X POST https://actual.deployed.app/endpoint/
HTTP/2 401 
content-type: application/json
content-length: 26
date: Tue, 09 Apr 2024 15:33:35 GMT
x-amzn-requestid: ...
x-amzn-errortype: UnauthorizedException
x-amz-apigw-id: ...
x-cache: Error from cloudfront
via: ...
x-amz-cf-pop: ...
x-amz-cf-id: ...

{"message":"Unauthorized"}                                                                                            
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose with `image: localstack/localstack-pro`

### Environment

```markdown
- OS: macOS 13.0
- LocalStack: latest (3.3)
```

**Comment by lukeprv** [comment] 2024-04-15 18:54
Another way of looking at this: API Gateway shouldn't consider the "Missing Authentication Token" as an error; it should invoke the authorizer Lambda function regardless and let the function return the "Unauthorized" response. When we send the example curl command above in our AWS environment, the function is invoked.

**Comment by cloutierMat** [comment] 2024-04-16 16:32
Thanks for reporting this and helping to improve LocalStack!

I was able to reproduce the first issue and I am currently working on a fix.

However, regarding apigw invoking the lambda even if the header is missing, I am not able to reproduce this behaviour on AWS.

Please make a working test case and publish it here.

It would be appreciated if you could avoid external dependencies in the test. The LocalStack team is small and generally doesn't have enough resources to thoroughly evaluate third-party code. Furthermore, standalone tests are easier to incorporate into regression tests.

Thank you in advance. Your assistance is appreciated.

**Comment by cloutierMat** [comment] 2024-04-17 02:30
Hi @lukeprv ,

A quick update on this issue, I was able to recreate the condition for a Lambda Authorizer to be invoked.

According to the [documentation](https://docs.aws.amazon.com/apigateway/latest/api/API_CreateAuthorizer.html#API_CreateAuthorizer_RequestSyntax), the `identitySource` is optional only for `REQUEST` authorizers and only when caching is disabled. 

I have implemented the fix and I will keep you up to date when it gets merged and pushed to the `latest` image.

The changes will be the following:

- For `TOKEN` authorizer, the source is required and the lambda is not invoked if absent or empty.
- For `REQUEST` authorizer, the source is required when caching is enabled and if the authorizer was configured to require a source. If caching is disabled the function will be called if no source was configured.

**Comment by rajveerappan** [comment] 2024-04-17 15:20
> For TOKEN authorizer, the source is required and the lambda is not invoked if absent or empty.

Hi @cloutierMat,

Just to clarify, the issue is not when _creating_ the authorizer. In that case, yes, specifying the source is required. The issue is when _invoking_ the authorizer APIGW should pass the request to the authorizer lambda even if the header is not present or if the header does not have a value specified.

You can see this for example when clicking "Test Authorizer" in the AWS Console without providing a a token value, it invokes the lambda and then it's up to the lambda to decide how to handle that case. In the example below the lambda returns 401 when the token value is not present.

<img width="1319" alt="image" src="https://github.com/localstack/localstack/assets/29206449/eea0681b-d9c1-45d6-99ba-42ca873a4728">

**Comment by cloutierMat** [comment] 2024-04-17 17:37
Thank you for the clarification and extra context, we are indeed both talking about the invocation.

In you example above, the Lambda has not been invoked. This message is returned by apigateway without actually calling your Lambda Authorizer.

When apigateway invokes your Lambda, it will be written explicitly in the logs also. And a full stack trace will be available.

```
Execution log for request 93a74a70-7264-4b98-961a-6ce65c50ff3d *** : 
Starting authorizer: z4nj0a for request: 93a74a70-7264-4b98-961a-6ce65c50ff3d *** : 
Incoming identity: ***ow *** : 
Endpoint request URI: *** : 
Endpoint request headers: {Authorization=***} : 
Endpoint request body after transformations: {"***}
*** : Using valid authorizer policy for principal: **er
```

I hope that helps clarifying, please let me know if you have any further questions.

**Closed** 2024-04-18 11:35 UTC
Labels: type: bug, aws:apigateway, status: in progress

**Comment by cloutierMat** [comment] 2024-04-18 22:11
Thank you for bringing this to our attention.
This issue has been resolved. It will is now part of the `latest` image.

Please let us know if there are still some issues with the feature!
