### ISSUE TITLE
LocalstackDocker incompatible with python3 change

### ISSUE THREAD

**Issue by dysmento** [localstack/localstack#1293] opened 2019-05-08 15:59 UTC
As of https://github.com/localstack/localstack/commit/0886a249ab8bbfea47b68597045a061ef5c55ece, `LocalstackDocker` can't get port configuration, because of this:

```
private static final String PORT_CONFIG_FILENAME = "/opt/code/localstack/" +
            ".venv/lib/python2.7/site-packages/localstack_client/config.py";
```

**Comment by whummer** [comment] 2019-05-08 16:05
Good catch @dysmento - any chance you can create a quick PR to fix this issue? thx

**Comment by dysmento** [comment] 2019-05-08 16:06
Yeah, I'll go ahead.

**Comment by blakeney** [comment] 2019-05-08 18:00
I came here to file a ticket about this same issue, and saw this one was already created.  In case it helps anyone who needs to work around the problem temporarily while the PR is in progress, here's what I just did:

1. Added `pullNewImage=false` to the `@LocalstackDockerProperties` annotation on my JUnit test class
2. Manually pulled and tagged `localstack/localstack:0.9.1` as `localstack/localstack:latest`

**Comment by markcuk** [comment] 2019-05-08 20:04
Can 0.9.2 be removed from the dockerhub repo and 0.9.1 be set back to latest? This is breaking all of our builds that use localstack.

**Comment by mukundans91** [comment] 2019-05-08 21:10
Can the new version with the fix be released to dockerhub https://hub.docker.com/r/localstack/localstack/tags? This is breaking builds that use localstack.

**Comment by yinghong** [comment] 2019-05-08 22:12
> I came here to file a ticket about this same issue, and saw this one was already created. In case it helps anyone who needs to work around the problem temporarily while the PR is in progress, here's what I just did:
> 
> 1. Added `pullNewImage=false` to the `@LocalstackDockerProperties` annotation on my JUnit test class
> 2. Manually pulled and tagged `localstack/localstack:0.9.1` as `localstack/localstack:latest`

I tried this workaround but didn't work.  pullNewImage=false didn't prevent it download the latest image. :-(

**Comment by blakeney** [comment] 2019-05-09 14:26
@yinghong: Earlier in my troubleshooting, I also had deleted all of my local copies of the localstack docker image, as well as all of my stopped localstack containers, so I started with a clean slate in that regard.  I didn't think it would be necessary, but maybe it was.

After that, I did `docker pull localstack/localstack:0.9.1` and then `docker tag localstack/localstack:0.9.1 localstack/localstack:latest`.  I'm not sure why `pullNewImage=false` wouldn't prevent a pull, unless there wasn't already a `latest` tag for the image on the machine.

Also, I'm using version 0.1.15 of localstack-utils in my project, for whatever that might be worth.

**Comment by markcuk** [comment] 2019-05-09 14:47
@yinghong also make sure you have changed all of your instances of @LocalstackDockerProperties to use pullNewImage=false, if you miss any then latest will get overwritten and everything that runs after that will break again. This workaround worked for me, I also created #1301 to add an imageTag attribute to @LocalstackDockerProperties so that you can force it to use a specific image version

**Comment by whummer** [comment] 2019-05-10 13:07
@blakeney @yinghong @mukundans91 Can you confirm that it works for you with the latest version of the Java libs and Docker image?

**Comment by markcuk** [comment] 2019-05-10 14:04
@whummer everything is working for me now with the latest version of the Java libs and Docker image. Can you tag the new docker image with a version so that I can pin it in my code?

**Comment by blakeney** [comment] 2019-05-10 15:35
@whummer, @markcuk :  I haven't tested the updated docker image yet (I guess I would have to build it locally?), but I think I've run into some problems with the latest Java libs:

1. If I specify an image tag that doesn't exist locally on my machine using the new `imageTag` parameter in the `@LocalstackDockerProperties` annotation, the image doesn't seem to get automatically pulled, and I get a TimeoutException (stacktrace below).  If I manually pull the image version first, the container at least starts.  For example, this happens if I use Java lib version 0.1.21 and annotation `@LocalstackDockerProperties(imageTag = "0.9.2", randomizePorts = true, services = [ "s3" ])`.  In case you're wondering, I tried this because I initially misunderstood and thought that I should test with image version 0.9.2, and incidentally discovered this problem.
2. Somehow, I still run into the original port mapping problem for which this ticket was opened if I use version 0.1.21 of the Java libs and specify imageTag 0.9.1.  Annotation: `@LocalstackDockerProperties(imageTag = "0.9.1", randomizePorts = true, services = [ "s3" ])`.  I find this especially strange because the container is using version 0.9.1 of the image according to the output of `docker ps`.  See partial stacktrace below.
3. The workaround that I was using before (see my previous messages on this issue) does not work with version 0.1.20 or 0.1.21 of the Java libs.  Specifically, f I manually pull and tag image version 0.9.1 as latest, then run my test with annotation `@LocalstackDockerProperties(pullNewImage=false, randomizePorts = true, services = [ "s3" ])`, I encounter the same port mapping issue for which this issue was originally opened.  It works using Java lib version 0.1.19 and earlier.

Stacktrace for 1:
```
cloud.localstack.docker.exception.LocalstackDockerException: Could not start the localstack docker container.
	at cloud.localstack.docker.LocalstackDocker.startup(LocalstackDocker.java:78)
	at cloud.localstack.docker.LocalstackDockerTestRunner.run(LocalstackDockerTestRunner.java:42)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to execute command
	at cloud.localstack.docker.DockerExe.execute(DockerExe.java:74)
	at cloud.localstack.docker.DockerExe.execute(DockerExe.java:51)
	at cloud.localstack.docker.command.RunCommand.execute(RunCommand.java:30)
	at cloud.localstack.docker.Container.createLocalstackContainer(Container.java:60)
	at cloud.localstack.docker.LocalstackDocker.startup(LocalstackDocker.java:65)
	... 31 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at cloud.localstack.docker.DockerExe.execute(DockerExe.java:68)
	... 35 more
```

Stacktrace for 2 and 3:
```
java.lang.IllegalArgumentException: Unknown port mapping for service
	at cloud.localstack.docker.LocalstackDocker.endpointForService(LocalstackDocker.java:187)
	at cloud.localstack.docker.LocalstackDocker.getEndpointS3(LocalstackDocker.java:100)
	at cloud.localstack.DockerTestUtils.createEndpointConfiguration(DockerTestUtils.java:114)
	at cloud.localstack.DockerTestUtils.getClientS3(DockerTestUtils.java:59)
```

**Comment by markcuk** [comment] 2019-05-10 16:08
@blakeney I believe both the image and java libs were updated to fix the issue and aren't backwards compatible, so 0.1.19 of the java lib will work with 0.9.1 of the image but not with the latest version (which was updated this morning but only for the latest tag, there was no version tag created for it). The opposite is also true (in my testing), 0.1.21 of the java lib works with the latest image but not with older versions of the image like 0.9.1.

I'm using 0.1.21 of the java lib without my imageTag attribute currently until the latest version of the image is tagged with it's version (I'm assuming it will be 0.9.3), then I'll add imageTag="0.9.3" to pin it for repeatability. This is working successfully.

**Comment by rotoclone** [comment] 2019-05-10 16:55
After updating to version 0.1.21 of localstack-utils, the "Unknown port mapping for service" error goes away, but now I'm seeing a new error:
```
com.amazonaws.SdkClientException: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: HlK8+pUmMRtnBY0EDEAa3g== in base 64) didn't match hash (etag: 7299f19de657a7d4f462ba41680178a8 in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@290c8999, bucketName: a-bucket, key: base/path/channel/channel123/bundle/bundle123/faketable1/part2)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1812)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1746)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1687)
```

This code works fine with real AWS, and worked fine with localstack before the unknown port mapping error appeared. I'm having trouble creating a minimal example to reproduce the new error though.

**Comment by gavingolden** [comment] 2019-05-13 19:37
when will tag `0.9.3` be pushed?

**Comment by yinghong** [comment] 2019-05-14 21:25
I upgraded library version `cloud.localstack:localstack-utils:0.1.21` and with properties: imageTag = "0.9.3"  but running into error ` manifest for localstack/localstack:0.9.3 not found`

**Comment by gavingolden** [comment] 2019-05-14 21:27
@yinghong `0.9.3` [doesn't exist yet](https://hub.docker.com/r/localstack/localstack/tags)

**Comment by whummer** [comment] 2019-05-17 21:50
Seems that this issues should be fixed in the latest release. Please open a follow-up ticket for any issues that still exist or come up. Thanks

**Closed by whummer** 2019-05-17 21:50 UTC
Labels: bug, priority-high, regression

**Comment by bigunyak** [comment] 2021-06-09 13:30
The issue seems to re-occurred in the latest localstack image. Maybe Python got upgraded again?

**Comment by whummer** [comment] 2021-06-09 13:35
Thanks for reporting @bigunyak . Can you please share some details about the exact issue/error you're seeing, as well as steps to reproduce? Thanks!

**Comment by bigunyak** [comment] 2021-06-09 16:09
Hi @whummer,
I've just pulled localstack/localstack:latest from dockerhub and it looks like it's coming with Python3.7 not 3.8.
```
/opt/code/localstack # ls /opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_client/config.py
ls: /opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_client/config.py: No such file or directory
/opt/code/localstack # ls /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_client/config.py
/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_client/config.py
/opt/code/localstack # python --version
Python 3.7.10
/opt/code/localstack #
```

Isn't it supposed to be 3.8? Some regression?

**Comment by bigunyak** [comment] 2021-06-10 11:22
Notice that same is reported in https://github.com/localstack/localstack/issues/2082
