### ISSUE TITLE
bug: Localstack version 1.4 Inaccessible host: '127.0.0.1' at port '4566'.

### ISSUE THREAD

**Issue by lkoida-boohoo** [localstack/localstack#7720] opened 2023-02-20 14:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running localstack as docker-compose service permanently have this error when try to call `sqs` form nodejs application.
`UnknownEndpoint: Inaccessible host: '127.0.0.1' at port '4566'. This service may not be available in the eu-west-1' region.`

 Tried to change `127.0.0.1`  to `localhost` but without any success.
Tried to use latest aws-sdk, and the same - message - conection refused.

running request using curl do the job perfectly.

This is my docker-compose settings for nodejs and localstack:
```yaml
version: "3.5"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.local
    depends_on:
      - localstack
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SDK_LOAD_CONFIG=1
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.4
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/localstack:/etc/localstack/init/ready.d/
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

```

### Expected Behavior

Expect to have successful comunication between localstack and node

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   in init scripts I have a couple of queues created on localstack start.
   And later I have to call them through nodejs api to send/receive messages

### Environment

```markdown
- OS:WSL Ubuntu 20.04
- LocalStack:1.4
```

**Comment by steffyP** [comment] 2023-02-21 14:03
Hi @lkoida-boohoo,

thanks your reaching out. I have some follow-up questions to clarify your issue.

1.  > running request using curl do the job perfectly.

    Do you run `curl` from your host machine, or from within one of the containers?

2. > UnknownEndpoint: Inaccessible host: '127.0.0.1' at port '4566'

    From your description, I understood that you are using nodejs, and this nodejs-app is part of the docker-compose deployment? So, do you get this error when running the command inside the `api` container?

    If yes, have you tried using `localstack` (e.g. the service-name) as hostname to connect to the localstack instance? It seems like you are sharing the network. And while I am no expert on [docker networks](https://docs.docker.com/compose/networking/), I think the service-name should be used to connect to the services that share the network.

**Comment by lkoida-boohoo** [comment] 2023-02-23 07:25
Hi @steffyP, so 
* yes, I'm used curl on my host machine
* yes, we have several containers, one of them is nodejs application, and through it we run the commands
Thanks for idea, I didn't tried yet to change the host to service-name in settings for nodejs app. As soon I'll have any results I provide more info.

**Comment by lkoida-boohoo** [comment] 2023-03-01 08:42
So, after some time I found that using `localstack` in host partially fix the problem, but then I found that if I specify any other region in SQS configuration than "us-east-1" it return me the next error
`AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.`

Should I in local development use only this region? @steffyP

**Comment by steffyP** [comment] 2023-03-01 12:21
Hi @lkoida-boohoo, 

thanks for getting back. As the error you reported initially with `Inaccessible host` seems to be resolved, I will close this ticket.

Regarding your issue with SQS: it depends on your use case, there are some known limitations with multi-accounts as outlined in #7041, which might cause your issue as well.
If it is not related to multi-accounts, please open a new ticket including a reproducible sample, so we can further look into it. Thanks.

**Closed by steffyP** 2023-03-01 12:21 UTC
Labels: type: bug

**Comment by rdeavila94** [comment] 2023-03-08 21:05
@lkoida-boohoo I had the exact same experience using the aws-sdk for node version 2.1331

This would be a bug in the aws-sdk, and not localstack. It appears that when using anything but the default/"global" region of us-east-1, the aws-sdk SQS object will attempt to use the region when making the outbound request to the service.

**Comment by kazazor** [comment] 2023-12-02 23:05
@rdeavila94 , I believe I'm facing the same issue as I get an error with a queue in `us-west-2` while a queue in `us-east-1` works (specifically using [ssut/nestjs-sqs](https://github.com/ssut/nestjs-sqs) version 1.3.0 which has `peerDependencies` of `"aws-sdk": "^2"`.

And I have `aws-sdk` version `2.1329.0` installed. Tried updating to the latest version of `aws-sdk` and it still seems broken.
And indeed using `awslocal` works as expected.

Can you elaborate on that and how you solved it?
