### ISSUE TITLE
DynamoDB health check is broken

### ISSUE THREAD

**Issue by jchanam** [localstack/localstack#2534] opened 2020-06-09 11:32 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When checking the health of dynamodb, errors are raised and a 500 is returned. This makes it impossible to really know If the service is running.

I got these two error traces:
```
2020-06-09T11:04:42:ERROR:localstack.services.dynamodb.dynamodb_starter: DynamoDB health check failed: an integer is required (got type NoneType) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 23, in check_dynamodb
    wait_for_port_open(PORT_DYNAMODB_BACKEND, http_path='/', expect_success=False, sleep_time=1)
  File "/opt/code/localstack/localstack/utils/common.py", line 412, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 460, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 456, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 409, in check
    if not is_port_open(port, http_path=http_path, expect_success=expect_success):
  File "/opt/code/localstack/localstack/utils/common.py", line 392, in is_port_open
    result = sock.connect_ex((host, port))
TypeError: an integer is required (got type NoneType)
```

```
2020-06-09T11:04:42:ERROR:localstack.services.plugins: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/plugins.py", line 94, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 113, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 109, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 32, in check_dynamodb
    assert isinstance(out['TableNames'], list)
TypeError: 'NoneType' object is not subscriptable
```

I've been reading the code, and it seems that the variable `PORT_DYNAMODB_BACKEND` is not updated properly, even though it's supposedly changed in:
https://github.com/localstack/localstack/blob/59bf9ec61d2bdad919b7117f961f561a2c499980/localstack/services/dynamodb/dynamodb_starter.py#L35-L37
But I see the port is correctly used (checking the java running on the pod):
![image](https://user-images.githubusercontent.com/6512096/84142063-70859980-aa54-11ea-8ced-b48e63469fc9.png)

That generates the first exception when calling to `wait_for_port_open(PORT_DYNAMODB_BACKEND, ...)`, and because the code after the exception catch is run, it gets to the assert with a None value of `out`:
https://github.com/localstack/localstack/blob/59bf9ec61d2bdad919b7117f961f561a2c499980/localstack/services/dynamodb/dynamodb_starter.py#L32

## Expected behavior
When calling to `/health?reload` it should return a `200 OK`.

## Actual behavior
When calling to `/health?reload` it returns a `500 INTERNAL SERVER ERROR` and exceptions are raised.

# Steps to reproduce

## Command used to start LocalStack
It's deployed on Kubernetes with this configuration:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: localstack
  name: localstack
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:0.11.2
        imagePullPolicy: IfNotPresent
        env:
        - name: HOSTNAME_EXTERNAL
          value: localstack
        - name: FORCE_NONINTERACTIVE
          value: "true"
        - name: SERVICES
          value: kinesis,dynamodb,s3,sqs
        ports:
        - containerPort: 4566
          name: edge
          protocol: TCP
        - containerPort: 8080
          name: web-ui
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health?reload
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health?reload
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 800Mi
      restartPolicy: Always
```

The pod is constantly restarted as the health checks are not returning that the application is running properly.

**Comment by vculanathan** [comment] 2020-06-09 17:46
Seeing this same issue,.

running OS: ubuntu 18.04.4 LTS
localstack version: 0.11.2

**Comment by vculanathan** [comment] 2020-06-09 17:53
Seeing this same issue when I am trying to run localstack in a docker container.

docker container config: 
```
  image: localstack/localstack:0.11.2
  ports:
    - "4566:4566"
    - "4580:8080"
  environment:
    - SERVICES=kinesis,dynamodb,sqs,s3
    - USE_SSL=true
    - HOSTNAME_EXTERNAL=mockaws
```

running OS: ubuntu 18.04.4 LTS
localstack version: 0.11.2

**Comment by whummer** [comment] 2020-06-19 12:50
Thanks for reporting this issue @jchanam @vculanathan . This is indeed a bit unexpected - as you mentioned, the `PORT_DYNAMODB_BACKEND` variable should get updated, if things are happening in the right sequence of events.

Can you please pull the `latest` version of the Docker image, and post the full logs with `DEBUG=1` enabled for your container. Thanks

I would expect to see this line from `start_dynamodb(..)` in the logs, before the process errors out in the `check_dynamodb(..)` function, as you posted above. 
```
Starting mock DynamoDB service in http ports 443 (recommended) and 4569 (deprecated)...
```

**Comment by whummer** [comment] 2020-06-22 20:50
Looks like this could be a duplicate of #2294

**Comment by jchanam** [comment] 2020-06-23 10:38
Hi,

I've just tested with the image tag `latest`. When calling to `/health` I get no answer (but a connection refused) until the services are running. After that, I get this:

```json
{
  "services": {
    "dynamodb": "running",
    "kinesis": "running",
    "s3": "running",
    "sqs": "running"
  }
}
```

Before any call to the health endpoint, this are the logs being shown:

```
Waiting for all LocalStack services to be ready
2020-06-23 10:32:09,144 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-06-23 10:32:09,146 INFO supervisord started with pid 16
2020-06-23 10:32:10,148 INFO spawned: 'dashboard' with pid 22
2020-06-23 10:32:10,150 INFO spawned: 'infra' with pid 23
2020-06-23 10:32:10,232 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-06-23 10:32:11,235 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 0.11.2
LocalStack version: 0.11.2
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-06-23T10:32:41:INFO:localstack.utils.common: Error storing key/cert SSL files (falling back to random tmp file names): [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
Running on 0.0.0.0:8081 over https (CTRL + C to quit)
Starting edge router (https port 4566)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
Starting mock S3 service on http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock SQS service on http ports 4566 (recommended) and 4576 (deprecated)...
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Running on 0.0.0.0:4568 over http (CTRL + C to quit)
Running on 0.0.0.0:4572 over http (CTRL + C to quit)
2020-06-23T10:32:41:INFO:localstack.multiserver: Starting multi API server process on port 43299
Running on 0.0.0.0:43299 over http (CTRL + C to quit)
Running on 0.0.0.0:4576 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Ready.
```

Then, if I call to `/health?reload` I get a 500 error and I see this on the logs:

```
2020-06-23T10:33:11:ERROR:localstack.services.dynamodb.dynamodb_starter: DynamoDB health check failed: an integer is required (got type NoneType) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 23, in check_dynamodb
    wait_for_port_open(PORT_DYNAMODB_BACKEND, http_path='/', expect_success=False, sleep_time=1)
  File "/opt/code/localstack/localstack/utils/common.py", line 422, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 470, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 466, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 419, in check
    if not is_port_open(port, http_path=http_path, expect_success=expect_success):
  File "/opt/code/localstack/localstack/utils/common.py", line 402, in is_port_open
    result = sock.connect_ex((host, port))
TypeError: an integer is required (got type NoneType)

2020-06-23T10:33:11:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
2020-06-23T10:33:11:ERROR:localstack.services.plugins: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/plugins.py", line 96, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 115, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 111, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 32, in check_dynamodb
    assert isinstance(out['TableNames'], list)
TypeError: 'NoneType' object is not subscriptable

2020-06-23T10:33:11:ERROR:app: Exception on /health [GET]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/dashboard/api.py", line 106, in get_health
    result = plugins.get_services_health(reload=reload)
  File "/opt/code/localstack/localstack/services/plugins.py", line 72, in get_services_health
    reload_services_health()
  File "/opt/code/localstack/localstack/services/plugins.py", line 119, in reload_services_health
    check_infra(retries=0)
  File "/opt/code/localstack/localstack/services/plugins.py", line 103, in check_infra
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 96, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 115, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 111, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 32, in check_dynamodb
    assert isinstance(out['TableNames'], list)
TypeError: 'NoneType' object is not subscriptable

...
...
```

And the logs keep showing the error (note that I have the liveness/readiness probes).

Hope this helps.

**Comment by whummer** [comment] 2020-06-26 19:13
Thanks for the update @jchanam @vculanathan . I was now able to reproduce this issue. With the change in #2627 , the `/health` endpoint has moved to the edge port (4566) and should now (hopefully) be fixed. Please update your clients to use this endpoint from now on: http://localhost:4566/health . Thanks

**Closed by whummer** 2020-06-26 19:13 UTC
Labels: bug, docker, installation, needs-triaging

**Comment by jchanam** [comment] 2020-07-03 16:46
I've tested and it's working now, thanks!

The requests for the healthcheck take between 35 and 75 seconds, is that normal?
