### ISSUE TITLE
bug: CORS issue listing cloudformation stack resources from app.localstack.cloud

### ISSUE THREAD

**Issue by joshbalfour** [localstack/localstack#7770] opened 2023-03-01 11:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Preflight request fails when listing cloudformation stack resources on app.localstack.cloud, resulting in an empty list.

### Expected Behavior

For the resources to be listed on the page.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```yml
networks:
  localstack:
    name: localstack
services:
  localstack:
    image: localstack/localstack-pro:1.4
    privileged: true # required to access the docker socket
    container_name: localstack_main
    env_file:
      .env
    networks:
      - localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      DOCKER_HOST: unix://var/run/docker.sock
      LOCALSTACK_PERSISTENCE: 0
      PROVIDER_OVERRIDE_LAMBDA: asf
      BUCKET_MARKER_LOCAL: hot-reload
      LAMBDA_DOCKER_NETWORK: localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

### Environment

```markdown
- OS: docker on macOS 13.2.1 (22D68)
- LocalStack: 1.4
```

**Comment by MarcelStranak** [comment] 2023-03-02 09:05
We would like to let you know that we were able to reproduce the problem, and that a fix is currently in progress. The fix will be released in the upcoming days. We'll let you know when a new version is available. Please do not hesitate to ask further questions!

**Comment by MarcelStranak** [comment] 2023-03-03 11:36
@joshbalfour the issue is now resolved.

![image](https://user-images.githubusercontent.com/97876429/222710565-c45b8de4-51cd-4d3d-babb-a11602cf1080.png)

**Closed by MarcelStranak** 2023-03-03 11:36 UTC
Labels: type: bug, area: web

**Comment by joshbalfour** [comment] 2023-03-03 15:05
@MarcelStranak awesome - thank you so much for the quick fix!
