### ISSUE TITLE
localstack fails to start

### ISSUE THREAD

**Issue by vamshisiddarth** [localstack/localstack#3939] opened 2021-04-28 12:59 UTC
# Type of request: 

- [x] bug report

# Detailed description

Localstack fails to start when running on kubernetes. The same configuration was working fine previously.

## Expected behavior

Start localstack without any errors.

## Actual behavior

Localstack service s doesn't start and gives below error.

```sh
$ kubectl logs -f localstack-7c8477b467-w7258
Waiting for all LocalStack services to be ready
2021-04-28 12:54:47,289 INFO supervisord started with pid 14
2021-04-28 12:54:48,292 INFO spawned: 'dashboard' with pid 20
2021-04-28 12:54:48,295 INFO spawned: 'infra' with pid 21
2021-04-28 12:54:48,301 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-04-28 12:54:48,301 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2021-04-28 12:54:49,306 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.

LocalStack version: 0.12.10
LocalStack build date: 2021-04-24
LocalStack build git hash: 9b57e6a9

Starting edge router (https port 4566)...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock Kinesis service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
2021-04-28T12:54:53:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 3883.8179111480713ms
2021-04-28T12:54:53:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 3884.4351768493652ms
[2021-04-28 12:54:53 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-04-28T12:54:53:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-04-28T12:54:53:INFO:localstack.multiserver: Starting multi API server process on port 52865
[2021-04-28 12:54:53 +0000] [22] [INFO] Running on http://0.0.0.0:52865 (CTRL + C to quit)
2021-04-28T12:54:53:INFO:hypercorn.error: Running on http://0.0.0.0:52865 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Error starting infrastructure: Port 55671 (path: None) was not open Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 374, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 451, in do_start_infra
    thread = start_api_services()
  File "/opt/code/localstack/localstack/utils/analytics/profiler.py", line 156, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 435, in start_api_services
    t1 = plugin.start(asynchronous=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 40, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/localstack/services/kms/kms_starter.py", line 27, in start_kms
    wait_for_port_open(backend_port)
  File "/opt/code/localstack/localstack/utils/common.py", line 525, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 598, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 594, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 523, in check
    raise Exception('Port %s (path: %s) was not open' % (port, http_path))
Exception: Port 55671 (path: None) was not open
```

**Comment by vamshisiddarth** [comment] 2021-04-28 14:02
seems like issue with my local configuration. I'm yet to identify what exactly caused this.

**Comment by vamshisiddarth** [comment] 2021-04-29 07:51
Confirming the root cause of the issue. It fails when kms is enabled. I tried just enabling kms and nothing else and still fails.

```sh
$ kubectl logs -f localstack-86bc478867-jrdxf                          
Waiting for all LocalStack services to be ready
2021-04-29 07:36:58,565 INFO supervisord started with pid 14
2021-04-29 07:36:59,569 INFO spawned: 'dashboard' with pid 20
2021-04-29 07:36:59,571 INFO spawned: 'infra' with pid 21
2021-04-29 07:36:59,576 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-04-29 07:36:59,576 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2021-04-29 07:37:00,579 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.

LocalStack version: 0.12.9.1
LocalStack build date: 2021-03-31
LocalStack build git hash: 165beed

2021-04-29T07:37:04:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 3605.4139137268066ms
2021-04-29T07:37:04:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 3606.0378551483154ms
Starting edge router (https port 4566)...
Starting mock KMS service on http port 4566 ...
[2021-04-29 07:37:04 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-04-29T07:37:04:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Error starting infrastructure: Port 48475 (path: None) was not open Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 373, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 450, in do_start_infra
    thread = start_api_services()
  File "/opt/code/localstack/localstack/utils/analytics/profiler.py", line 156, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 434, in start_api_services
    t1 = plugin.start(asynchronous=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 40, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/localstack/services/kms/kms_starter.py", line 27, in start_kms
    wait_for_port_open(backend_port)
  File "/opt/code/localstack/localstack/utils/common.py", line 521, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 594, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 590, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 519, in check
    raise Exception('Port %s (path: %s) was not open' % (port, http_path))
Exception: Port 48475 (path: None) was not open

2021-04-29T07:37:10:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 5583.481073379517ms
ERROR: Port 48475 (path: None) was not open
```

**Comment by szEvEz** [comment] 2021-04-29 14:18
We are also having issues with LocalStack version: 0.12.10. We went back to 0.12.5 and most of our issues were solved.

**Comment by vamshisiddarth** [comment] 2021-05-07 15:27
KMS isn't working on any version from 0.11.0 and higher. I'm using 0.10.7 for the kms and the latest image for the rest of the services.

**Comment by dmarkey** [comment] 2021-05-12 21:38
Seems to happen to me with data persistence turned on and after a restart. Have stripped out KMS functionality from my terraform and inserted fake KMS arns for now.

**Comment by pinzon** [comment] 2021-06-10 22:08
Hi @vamshisiddarth I tested you issue deploying several versions of Localstack with kubernetes but I don't have any issue with the kms service or with Localstack in general. Maybe you could provide more info into your problem.

I'll close this issue for now but feel free to comment with more info in how to reproduce the issue. Also I leave here my kubernetes file so you can tell me if something is wrong.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: localstack
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: localstack
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: localstack
    spec:
      containers:
        - env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
            - name: SERVICES
              value: 'kms'
          image: localstack/localstack:0.12.10
          name: localstack-main
          ports:
            - containerPort: 4566
            - containerPort: 4571
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

```

**Closed by pinzon** 2021-06-10 22:08 UTC

**Comment by alfonzjanfrithz** [comment] 2021-11-22 04:05
> We are also having issues with LocalStack version: 0.12.10. We went back to 0.12.5 and most of our issues were solved.

I am not sure what is the exact reason, because the debug does not tell much of the problem, but this solution works.
I ended up using 0.12.5
