### ISSUE TITLE
Latest master branch issue: 'localstack' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by maheshn99** [localstack/localstack#717] opened 2018-04-15 06:27 UTC
I am on Windows 7. I downloaded the latest master branch. Followed the steps to install localstack still get the following error upon doing localstack start.

'localstack' is not recognized as an internal or external command, operable program or batch file.

Python and pip are correctly added to the path already.
D:\LocalStack\localstack-master>python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

D:\LocalStack\localstack-master>pip freeze
airspeed==0.5.5.dev20160812
asn1crypto==0.24.0
aws-xray-sdk==0.95
awscli==1.15.4
boto==2.46.1
boto3==1.7.4
botocore==1.10.4
cachetools==0.8.0
...
...

Please advise. Thanks!

**Comment by whummer** [comment] 2018-05-01 13:48
Thanks for reporting @maheshn99 . I'm assuming you installed LocalStack via `pip install localstack`. Looks like pip's `bin` folder (the one which should contain the `localstack` command) is not in your path?

Not exactly sure where this folder is located in WIndows 7, it really depends on your local python installation. Have you been able to install any other pip packages and run a command that they provide?

**Comment by aw230012** [comment] 2018-08-17 18:14
I'm having this issue and my PATH is setup properly.  Any ideas?

**Comment by preetampatil3d** [comment] 2018-10-26 15:47
Same issue for me also. I have installed LocalStack via pip install localstack.
i can see localstack file at location 'D:\Python27\Scripts'.

**Comment by milk9111** [comment] 2018-11-21 03:37
Does anyone have a fix for this yet? Mine is located in the same directory "C:\Python36\Scripts" and other pip installed packages are working.

**Comment by arnagarjun** [comment] 2019-01-24 19:05
Same problem here.
Installed successfully.
Can see the localstack file.
Have added the path to environment variables.
But still nothing working.

**Comment by exp-oliviazhan** [comment] 2019-04-03 07:14
I have the same issue. is anyone looking into this?

**Comment by praveenvelampudi7** [comment] 2019-07-09 17:05
Same issue with me as well. 
Does anyone have a fix for this problem?

**Comment by jnewton3edinburgh** [comment] 2019-07-15 12:00
I also have the same issue. localstack is not recognised after pip install.
Python is in my PATH environment variable and other pip packages can be run.

**Comment by ElvenMonky** [comment] 2019-09-08 21:21
@praveenvelampudi7 you can create localstack.bat file in the same "Scripts" folder with following content `python "%~dp0localstack" %*`.
May still cause issues from #563 (at least for me termios still fails)

**Comment by bpringe** [comment] 2019-09-20 21:33
This is still an issue. I have the same issue on Windows 10. Path is set correctly.

**Comment by whummer** [comment] 2019-11-08 21:38
Thanks for reporting @bpringe @ElvenMonky @jnewton3edinburgh @praveenvelampudi7 @exp-oliviazhan @arnagarjun @milk9111 @preetampatil3d @aw230012 @maheshn99 

There should now be a `localstack.bat` script included in the latest release of the pip package. This script should allow you to run the `localstack` command under Windows, provided the PATH is set up properly on your machine. 

Please give it a try with the latest version (`0.10.5`) and report back if the problem persists. Thanks

**Closed by whummer** 2019-11-08 21:38 UTC
Labels: installation, python-env-issue

**Comment by whighsmith** [comment] 2023-02-15 11:33
Just ran into this problem following steps here: https://docs.localstack.cloud/getting-started/installation/
It's 2023.  If you can't get the simple parts right, how can one think you'll get the hard parts right.

**Comment by tinabhowal** [comment] 2023-10-27 11:36
I had the same problem. I added the path but still the problem persisted. So I started afresh.
(I am on Windows 10)

Following is what I did 
1. Downloaded the respective binary for my architecture directly from https://docs.localstack.cloud/getting-started/installation/

2. Extracted the file

3. After extraction, moved to the directory. 
The problem is, If I just run **localstack --version** from the directory, I got an error saying 
**"localstack : The term 'localstack' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again."**

this was because localstack command is not found in my system's PATH, and I was running it from a directory where it is not recognized as an executable. 

So instead , I ran the command **.\localstack --version** and this worked!

I am not sure how much this will help you.

I am just a beginner and sharing whatever has helped me to go around the problem.
