### ISSUE TITLE
bug: API Gateway V1 REST requests breaks when path parameter validation is enabled in serverless

### ISSUE THREAD

**Issue by mickfold** [localstack/localstack#7842] opened 2023-03-12 23:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When performing any requests with path parameters with validation enabled the following error message is returned

`GET http://localhost:4566/restapis/<apigw_id>/local/_user_request_/test/world`

returns

`{"Type": "User", "message": "Invalid request body", "__type": "InvalidRequest"}`

### Expected Behavior

Path parameter validation works like AWS, i.e. validation is performed, lambda is invoked and response returned to caller.

`GET http://localhost:4566/restapis/<apigw_id>/local/_user_request_/test/world`

returns

`"hello world"`

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   See project in zip archive - [localstack-path-parameter-test.zip](https://github.com/localstack/localstack/files/10952340/localstack-path-parameter-test.zip). Also included below.

To deploy to localstack:

1. `yarn install`
2. `npx sls deploy --stage local --region eu-west-2`

This has two endpoints. The first, test, works but the second endpoint, broken-test, fails with the error `Invalid request body`.

It looks like the error is caused by localstack not being able to handle `AWS::ApiGateway::RequestValidator` correctly.

Also if you try to fix an endpoint by removing the validation, i.e. change the broken-test endpoint to:

```
  broken-test:
    handler: handler.test
    events:
      - http:
          path: broken-test/{value}
          method: get
```

Then after deploying and hitting this endpoint you get an error like

```
{
"__type": "InternalError",
"message": "exception while calling apigateway with unknown operation: An error occurred (NotFoundException) when calling the GetRequestValidator operation: Validator 06ce6f for API Gateway 5ajrq316ln not found"
}
```

**serverless.yml**
```
service: locastack-test
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    NODE_ENV: dev
plugins:
  - serverless-localstack
custom:
  localstack:
    stages: [local]
    host: http://127.0.0.1
    debug: true
functions:
  test:
    handler: handler.test
    events:
      - http:
          path: test/{value}
          method: get
  broken-test:
    handler: handler.test
    events:
      - http:
          path: broken-test/{value}
          method: get
          request:
            parameters:
              paths:
                issuer: true
```

**handler.js**
```
exports.test = async function (event, context) {
  return {
    body: `hello ${event.pathParameters.value}`,
    headers: {},
    statusCode: 200,
  };
}
```

**package.json**
```
{
  "name": "localstack-test",
  "devDependencies": {    
    "serverless": "^3.28.1",
    "serverless-localstack": "^1.0.4"
  }
}
```

### Environment

```markdown
- OS: AWS Linux Workspace
- LocalStack: latest
```

### Anything else?

[localstack_logs.txt](https://github.com/localstack/localstack/files/10952376/localstack_logs.txt)

**Comment by bentsku** [comment] 2023-03-16 18:49
Hi @mickfold and thank you for the very detailed report!

We indeed have an issue on our side that will be fixed by #7846: if a `RequestValidator` is created with `validateRequestBody=true` like Serverless does, and no model was attached to the `Method`, we would reject the request (instead of using the default `Empty` schema like AWS). This has now be fixed.

However, while trying the sample against AWS, it doesn't work either because your path is `test/{value}` but the path parameter is named `issuer`, which is then missing when validating the request.
At the moment, LocalStack won't validate the path parameter (we only validate the request body), but at some point we will have the same behaviour than AWS. 

I'll comment back once the fix is merged and available. Thanks again!

**Comment by mickfold** [comment] 2023-03-16 22:57
Hi @bentsku, sorry that's a mistake on my part. I extracted the failing scenario from our codebase and missed updating the path parameter, which should have been "value". Apologies for any confusion this caused. The yaml should have been written as:

```
  broken-test:
    handler: handler.test
    events:
      - http:
          path: broken-test/{value}
          method: get
          request:
            parameters:
              paths:
                **value: true**
```

**Comment by bentsku** [comment] 2023-03-16 22:58
No problem, I'm really glad you gave us a good sample to reproduce the issue in the first place, and it raised a real issue. Thanks!

**Comment by bentsku** [comment] 2023-03-17 16:04
Hi again @mickfold,

The fix is now released and part of the `latest` docker image, can you run `docker pull localstack/localstack:latest` (or `localstack/localstack-pro:latest` if you're a Pro user) and give it a try? Thanks!

**Comment by mickfold** [comment] 2023-03-20 11:37
@bentsku Unfortunately it's still returning the same error about "Invalid request body". 

This is the version info we get from the docker container:

LocalStack version: [1.4.1.dev](http://1.4.1.dev/)
LocalStack Docker container id: 4c7909e80fdb
LocalStack build date: 2023-03-17
LocalStack build git hash: e8580459

**Comment by bentsku** [comment] 2023-03-20 15:54
@mickfold Okay, well, it seems we've missed maybe one case. Could you please give us the command you're executing against the API route? It seems we might be missing something while validating or not the body. Sorry for that.

**Comment by bentsku** [comment] 2023-03-20 22:00
@mickfold the second fix is now released as well, could you give it a try again? Sorry again for the inconvenience.

**Comment by mickfold** [comment] 2023-03-21 01:24
@bentsku Sorry but I'm still getting the same error with my test case. I've included a tweaked test project and screenshots to show the failing scenario

LocalStack version: 1.4.1.dev
LocalStack Docker container id: a8959a5c9401
LocalStack build date: 2023-03-20
LocalStack build git hash: 77bd2c2c

[localstack-path-parameter-test.zip](https://github.com/localstack/localstack/files/11024169/localstack-path-parameter-test.zip)

**Failing endpoint - with required path parameter defined**
`2023-03-21T01:16:01.258  WARN --- [   asgi_gw_2] l.s.apigateway.invocations : failed to validate request body, request data is not valid JSON Expecting value: line 1 column 1 (char 0)
2023-03-21T01:16:01.258  INFO --- [   asgi_gw_2] localstack.request.http    : GET /restapis/mn6c1jeqyb/local/_user_request_/required-param-test/world => 400`

![image](https://user-images.githubusercontent.com/1315895/226497845-8721d1cd-8c6b-4ac5-ad4d-965dea67193f.png)

**Working endpoint - with no path parameter except in the path definition**
`2023-03-21T01:15:16.398  INFO --- [   asgi_gw_0] localstack.request.http    : GET /restapis/mn6c1jeqyb/local/_user_request_/test/world => 200`

![image](https://user-images.githubusercontent.com/1315895/226497781-ee9ace49-9b1f-4c2e-9af9-e12f648f8401.png)

**Working endpoint - with optional parameter defined**
`2023-03-21T01:13:01.741  INFO --- [   asgi_gw_0] localstack.request.http    : GET /restapis/mn6c1jeqyb/local/_user_request_/optional-param-test/world => 200
2023-03-21T01:15:15.844  INFO --- [   asgi_gw_0] l.s.apigateway.templates   : Method request body before transformations:
2023-03-21T01:15:15.848  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:us-east-1:000000000000:function:locastack-test-local-test`

![image](https://user-images.githubusercontent.com/1315895/226497724-a4243930-2a17-4512-bf1f-f37bfff2fc62.png)

**Comment by bentsku** [comment] 2023-03-21 01:55
@mickfold, yes, apparently from the git hash, the fix is not in the image, looking at the history on `master`: https://github.com/localstack/localstack/commits/master

It seems we got a hiccup in our pipeline and the latest docker image was overwritten by a previous commit, thus not getting the fix in your image. I re-launched our pipeline and the fix should be in the `latest` docker image again in around one hour. Really sorry for the inconvenience again.

**Comment by mickfold** [comment] 2023-03-21 18:26
@bentsku It's working now. Thanks!

**Comment by bentsku** [comment] 2023-03-21 21:45
Awesome, thanks a lot for the feedback and the sample to reproduce the issue. Apologies for the inconveniences along the way, glad to see it resolved!

**Closed by bentsku** 2023-03-21 21:45 UTC
Labels: type: bug, aws:apigateway, status: confirmed
