### ISSUE TITLE
Shell scripts in docker-entrypoint-initaws.d does't work at all

### ISSUE THREAD

**Issue by hrytskivr** [localstack/localstack#2814] opened 2020-08-05 18:42 UTC
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

I'm trying to verify couple of emails for SES service, using sh script in /docker-entrypoint-initaws.d directory, but when the script launches I receive an error. At first I thought there is no bash in localstack container, so I removed shebang, but then it said that there is no aws command and this is completely wrong, because when I execute the command that is inside the scrip by hand via cli in container it works just fine.

_ses.sh_
```
#!/bin/bash

aws ses verify-email-identity --email-address email@gmail.com --region eu-central-1 --endpoint-url=http://localhost:4579

```

_docker-compose.yml_
```
version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=cloudwatch,ses,s3
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "../storage:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/docker-entrypoint-initaws.d"
```

_localstack container log_
```
Waiting for all LocalStack services to be ready
2020-08-05 18:33:34,316 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-08-05 18:33:34,319 INFO supervisord started with pid 13
2020-08-05 18:33:35,322 INFO spawned: 'dashboard' with pid 19
2020-08-05 18:33:35,323 INFO spawned: 'infra' with pid 20
2020-08-05 18:33:35,327 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-08-05 18:33:35,328 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
!WARNING! - Looks like you have configured $LAMBDA_REMOTE_DOCKER=1 - please make sure to configure $HOST_TMP_FOLDER to point to your host's $TMPDIR
2020-08-05 18:33:37,253 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting edge router (https port 4566)...
Starting mock CloudWatch service on http ports 4566 (recommended) and 4582 (deprecated)...
Starting mock S3 service on http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock SES service on http ports 4566 (recommended) and 4579 (deprecated)...
2020-08-05T18:33:39:INFO:localstack.multiserver: Starting multi API server process on port 36469
Running on 0.0.0.0:36469 over http (CTRL + C to quit)
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Running on 0.0.0.0:4572 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready.

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/ses.sh
: No such file or directoryd/ses.sh: line 1: ﻿#!/bin/bash
```

## Expected behavior

There should't be any errors, and email should be confirmed.

## Actual behavior

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/ses.sh
: No such file or directoryd/ses.sh: line 1: ﻿#!/bin/bash
```

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up -d`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`aws ses verify-email-identity --email-address email@gmail.com --region eu-central-1 --endpoint-url=http://localhost:4579`

**Comment by hrytskivr** [comment] 2020-08-05 18:43
I've tried this on latest tag and on 0.11.0. I've also tried this on WSL2 backend and Hyper-V backend (Docker for Windows).

**Comment by whummer** [comment] 2020-08-05 21:03
Thanks for reporting this issue @hrytskivr . Please note that the init scripts are getting sourced, so the shebang should not be required - see here: https://github.com/localstack/localstack/blob/master/bin/docker-entrypoint.sh#L27

Haven't been able to reproduce this issue (under MacOS) - this is the output I'm seeing:
```
Ready.
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/foo.sh
Unable to locate credentials. You can configure credentials by running "aws configure".
```
(Which indicates that the `aws` command is getting executed correctly.)

Can you please share the actual `ses.sh` file here - is there any chance that there are some special, non-ASCII/non-printable characters in the file? Thanks

**Comment by hrytskivr** [comment] 2020-08-06 07:37
@whummer thanks for your help. I tried on macOS now and it worked, then I've committed the files and pulled changes on Windows, and it didn't work, now showing this error: 

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/ses.sh
/docker-entrypoint-initaws.d/ses.sh: line 2: $'\r': command not found
```

Here's a link to ses.sh -> https://drive.google.com/file/d/1HyfhQZFwsXg0YDr48xlqsqHyNv0unpk7/view?usp=sharing

**Comment by mdaniel** [comment] 2020-08-12 05:18
> I tried on macOS now and it worked, then I've committed the files and pulled changes on Windows, and it didn't work, now showing this error:

    /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/ses.sh
    /docker-entrypoint-initaws.d/ses.sh: line 2: $'\r': command not found

Yes, it's because that `ses.sh` file has Windows line endings (`\r\n`), but `bash` does not tolerate that. You'll find [any number of ways of converting them](https://stackoverflow.com/search?q=convert+windows+to+unix+line+endings) as that's a very, very common problem when trying to interoperate between Windows and Linux

**Comment by whummer** [comment] 2020-08-12 18:20
@mdaniel  Thanks a lot for providing clarity on the root cause, and for pointing out possible ways to fix the line endings!

@hrytskivr Closing this issue as resolved (or, unrelated to LocalStack) - please do report here if the problem persists. Thanks!

**Closed by whummer** 2020-08-12 18:20 UTC

**Comment by MarcioVRED** [comment] 2024-04-02 14:46
Im running with docker-compose.yaml , and iam not receive error, but its not execute nothing:

version: "3"
networks:
  openfire:

services:

  localstack:
    image:  localstack/localstack:latest
    networks:
      - openfire
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - ./init-scripts/startup.sh:/docker-entrypoint-initaws.d/docker-entrypoint.sh
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range

return:

localstack-1  | 
localstack-1  | LocalStack version: 3.3.1.dev
localstack-1  | LocalStack build date: 2024-04-02
localstack-1  | LocalStack build git hash: a38de240a
localstack-1  |
localstack-1  | 2024-04-02T14:34:10.651  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack-1  | 2024-04-02T14:34:10.651  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack-1  | 2024-04-02T14:34:10.805  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 602.97ms
localstack-1  | Ready.

the script startup.sh is not running:

![image](https://github.com/localstack/localstack/assets/31067526/8401d9e4-242d-464a-8ce9-9d0db1ca73de)

my startup.sh 

![image](https://github.com/localstack/localstack/assets/31067526/a850c3ac-0a02-4813-94df-1e8b1564b1b7)
