### ISSUE TITLE
bug: list-metrics returns only first record

### ISSUE THREAD

**Issue by ondrejkouril** [localstack/localstack#5000] opened 2021-11-24 14:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

list-metrics doesn't list multiple metrics within the same instance

### Expected Behavior

`aws --endpoint-url=http://localhost:4566 cloudwatch list-metrics` should list all metrics from all instances

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create ec2 instance `aws --endpoint-url=http://localhost:4566 ec2 run-instances --region us-east-1`
Create 2 metrics
`aws --endpoint-url=http://localhost:4566 cloudwatch put-metric-data --namespace "AWS/EC2" --metric-name "CPUUtilization" --dimensions InstanceId=i-46cdcd06a11207ab3 --value 15`
`aws --endpoint-url=http://localhost:4566 cloudwatch put-metric-data --namespace "AWS/EC2" --metric-name "Memory" --dimensions InstanceId=i-46cdcd06a11207ab3 --value 30`
List metrics `aws --endpoint-url=http://localhost:4566 cloudwatch list-metrics`

docker-compose.yml
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=ec2,cloudwatch,lambda,s3
      - AWS_DEFAULT_REGION=us-east-1
      - PORT_WEB_UI=9080
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

### Environment

```markdown
- OS: Windows 20H2 19042.1237
- LocalStack: 0.12.20
```

**Comment by KrishnanRanjithkumar** [comment] 2022-01-19 19:54
Thanks @ondrejkouril for reporting this issue, this should fixed be fixed in spulec/moto#4732. Could you please pull the latest docker image and give it another try ? Please let us know if the problem still persists.

**Comment by steffyP** [comment] 2022-06-03 10:53
@ondrejkouril,
can you confirm that the issue you reported was resolved?

**Comment by steffyP** [comment] 2022-08-02 10:49
Hi @ondrejkouril,

we haven't heard back from you and were are not able to reproduce this issue anymore with the latest image. I will close the ticket therefore.

**Closed by steffyP** 2022-08-02 10:49 UTC
Labels: type: bug, status: response required, aws:cloudwatch
