### ISSUE TITLE
Secrets Manager returns all secrets in despite of the value of MaxResults

### ISSUE THREAD

**Issue by abarisuzuner** [localstack/localstack#3196] opened 2020-10-29 08:23 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I am using `listSecrets` in `SecretsManager` in `aws-sdk`. I have created 10 secrets and passing `{MaxResults: 3}` as params. 

## Expected behavior
I expect it to return only 3 secrets and `NextToken`.

## Actual behavior
It returns all secrets with `null` as `NextToken`

# Steps to reproduce
## Command used to start LocalStack
localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
    this.secretsManager = new SecretsManager({
      endpoint : process.env.AWS_ENDPOINT,
      region : process.env.AWS_REGION,
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
    });

      this.secretsManager.listSecrets({ MaxResults: 3 }, (err, data) => {
        ...
      })

```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-74) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment] 2020-10-31 19:40
@abarisuzuner 
Thanks for reporting the issue.Can you please let us know which version of localstack are you using?

I am not able to reproduce this using aws cli commands on latest version of localstack,may be the issue is specific to java sdk.Can you please confirm which version of localstack you are using ?

**Comment by abarisuzuner** [comment] 2020-11-02 07:14
@usmangani1 
I used localstack version 0.12.1 and for javascript, aws-sdk version 2.718.0.

The main reason I suspect localstack is that when I run my code against actual AWS it works as I expected. But localstack somehow ignores the params I think.

**Comment by miho120** [comment] 2020-11-09 18:58
Hi @abarisuzuner 
I was able to reproduce your issue and made a fix for this in localstack/moto lib.
https://github.com/localstack/moto/pull/9

After merge and updating `requirements.txt` here, the secretsmanager pagination should work.

**Comment by abarisuzuner** [comment] 2020-11-10 07:08
> Hi @abarisuzuner
> I was able to reproduce your issue and made a fix for this in localstack/moto lib.
> [localstack/moto#9](https://github.com/localstack/moto/pull/9)
> 
> After merge and updating `requirements.txt` here, the secretsmanager pagination should work.

Thank you!

**Comment by whummer** [comment] 2021-01-02 19:18
Thanks for reporting @abarisuzuner - this should be fixed in the meantime, can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Closed by whummer** 2021-01-02 19:18 UTC
