### ISSUE TITLE
Dashboard does not work 

### ISSUE THREAD

**Issue by FighterNan** [localstack/localstack#1392] opened 2019-06-22 23:04 UTC
Run localstack through docker. 
```bash
sudo docker run -it -p 4567-4578:4567-4578 -p 8080:8080 localstack/localstack
```
I have put some objects into s3. 
```bash
$ aws s3 ls foo.bucket
2019-06-22 15:15:02         11 bar.key
```
But the dashboard is still empty.  The dashboard keeps empty even if I add lambda functions and more objects.

**Comment by whummer** [comment] 2019-06-23 10:28
Thanks for reporting @FighterNan . I wasn't able to reproduce this issue. Are you sure you're creating the S3 bucket against LocalStack, and not against the real AWS account?

Note that the dashboard is currently configured to display only resources in your local instance, but it does *not* by default show the resources from your AWS account (in order to do that, it would have to be configured with your access credentials, etc)

**Comment by FighterNan** [comment] 2019-06-23 17:05
Thanks for your reply @whummer . 
I'm quite sure I'm creating buckets, objects, and functions in the LocalStack since I have specified the endpoint. I use `boto3` to create a function. 
```python
lambda_client = boto3.client(service_name='lambda',
                              use_ssl=False,
                              aws_access_key_id='fake',
                              aws_secret_access_key='fake',
                              endpoint_url='http://x.x.x.x:4574'
                             )
lambda_client.create_function(FunctionName="foo.function",
                                  Runtime='python2.7',
                                  Role='foo.role',
                                  Handler='lambda.handler',
                                  Code={'ZipFile': zipped_code}
                                   )
 ```
Then I can verify the function has been created using `awscmd`.
```bash
$ aws lambda list-functions  --endpoint-url http://x.x.x.x:4574
{
    "Functions": [
        {
            "FunctionName": "foo.function",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:foo.function",
            "Runtime": "python2.7",
            "Role": "foo.role",
            "Handler": "lambda.handler",
            "CodeSize": 238,
            "Description": "",
            "Timeout": 3,
            "LastModified": "2019-06-23T00:12:44.453+0000",
            "CodeSha256": "j9nL122uJlgeEOzVXEtnv/WglSFwIoqRYOpCWLHzWKs=",
            "Version": "$LATEST",
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "f168efbe-a506-414a-a460-4dc353deb5df"
        }
    ]
}
```
But the web ui is still empty. As far as my understanding, if I check `Local AWS Endpoints` and use the Name Filter `.*`, there should be some instances in the web UI.

**Comment by RAAJNarducci** [comment] 2019-07-10 00:34
I Have i same problem. web ui is still empty:
Log:
 aws --endpoint-url="http://21ad0c748654:4578" es list-domain-names [Errno 1] Operation not permitted: '/tmp/cache.603fe2759e3fd86a1a62d33a4bf3652a.json'

**Comment by saurabh73** [comment] 2019-07-11 14:23
Adding this to my `docker-compose.yaml` fix the error log,
```
volumes:
      - ...
      - "${TMPDIR:-/tmp/localstack}:/tmp"
      -  ...
```

Web UI is empty till resource is created, eg.
```
aws --endpoint-url="http://localhost:4578" --region us-east-1 s3api create-bucket --bucket my-bucket
```

**Comment by ronaldpetty** [comment] 2019-07-16 00:59
I am hunting this down myself (noob here).  I suspect it is due to `/tmp/cache.*.json` being owned by root yet `web` process is running a `localstack` user.  I am not fully sure who launches what, but getting close.

Started via Docker:

```
$ TMPDIR=/private$TMPDIR localstack start --docker
Starting local dev environment. CTRL-C to quit.
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e LOCALSTACK_HOSTNAME="localhost" --rm --privileged --name localstack_main -p 8080:8080 -p 443:443 -p 4567-4597:4567-4597 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
...
ready
```

Debugging via Docker:

```
$ docker container exec --user=localstack -it -e LOCALSTACK_HOSTNAME="localhost" -e LOCALSTACK_HOSTNAME="localhost" --privileged -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/Users/ronald.petty/tmp/localstack" localstack_main sh
/opt/code/localstack $ ps wuxa | grep web
   20 localsta  0:00 bash -c if [ "$START_WEB" = "0" ]; then exit 0; fi; make web
   22 localsta  0:00 make web
   24 localsta  0:02 python bin/localstack web
  714 localsta  0:13 python /opt/code/localstack/bin/localstack web
  786 localsta  0:00 grep web
/opt/code/localstack $ touch /tmp/cache.37d6ac786ae207c150c5e38876067e69.json
touch: /tmp/cache.37d6ac786ae207c150c5e38876067e69.json: Permission denied
/opt/code/localstack $ whoami
localstack
```

**Comment by zarr12steven** [comment] 2019-07-25 06:39
> I Have i same problem. web ui is still empty:
> Log:
> aws --endpoint-url="http://21ad0c748654:4578" es list-domain-names [Errno 1] Operation not permitted: '/tmp/cache.603fe2759e3fd86a1a62d33a4bf3652a.json'

I have the same issue

### OS information

```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

### docker-compose.yml

```
version: '3.2'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
      - SERVICES=iam,s3,ec2,rotue53,cloudwatch,cloudwatchlogs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      #- KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - './.localstack:/tmp/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
```

When I run `TMPDIR=/private$TMPDIR docker-compose up` 

### Container Logs

```
localstack    | 2019-07-25T06:27:42:WARNING:localstack.dashboard.infra: Error running command: { test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localstack:4572" s3api get-bucket-notification-configuration --bucket demo_bucket [Errno 1] Operation not permitted: '/tmp/cache.8a3017c2ef4733fe265d0f8b15ebda06.json'
```

**Comment by wzowee** [comment] 2019-07-26 02:06
Hitting this as well, can successfuly run aws cli commands against the localstack instance but the UI can't display any of the s3 resources

docker-compose.yml

```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_s3
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
     # - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      aws_local:
        ipv4_address: 192.168.10.2
        aliases:
          - localstack-s3
networks:
  aws_local:
    external:
      name: aws-local
```

log messagine indicating failure to list-buckets

```
2019-07-26T02:03:24:WARNING:localstack.dashboard.infra: Error running command: { test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://fcba5ecdc4f1:4572" s3api list-buckets [Errno 1] Operation not permitted: '/tmp/cache.59b17a619639bbfe8aea9e201259d92b.json'
```

**Comment by unleashit** [comment] 2019-07-27 00:44
Having the same issue and same errors as the others. Tried downgrading to the 0.8.10 image, and the problem went away for me...

**Comment by LEscobar-Driver** [comment] 2019-07-29 22:02
Can confirm, getting the same error as everyone else right now


    localstack    | Ready.
    localstack    | 2019-07-29T21:54:43:INFO:localstack.utils.persistence: Restored 2 API calls from persistent file: /tmp/localstack/data/s3_api_calls.json
    localstack    | 2019-07-29T21:54:55:WARNING:localstack.dashboard.infra: Error running command: { test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4578" es list-domain-names [Errno 1] Operation not permitted: '/tmp/cache.c08081ce4cb73d03925a460cdbf70ce8.json' 
    localstack    | 2019-07-29T21:54:56:WARNING:localstack.dashboard.infra: Error running command: { test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4572" s3api list-buckets [Errno 1] Operation not permitted: '/tmp/cache.c08081ce4cb73d03925a460cdbf70ce8.json' 
    localstack    | 2019-07-29T21:54:57:WARNING:localstack.dashboard.infra: Error running command: { test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4574" lambda list-functions [Errno 1] Operation not permitted: '/tmp/cache.c08081ce4cb73d03925a460cdbf70ce8.json' 


**docker-compose file**

    version: "2.1"
    services:
      localstack:
        image: localstack/localstack
        container_name: localstack
        ports:
          # - "4567-4584:4567-4584"
          - '4563-4584:4563-4584'
          - '8055:8080'
         environment:
          - SERVICES=s3,lambda,es
          - DEBUG=0
          - DEFAULT_REGION=us-west-2
          - DATA_DIR=/tmp/localstack/data
          - HOSTNAME=localhost
          - LAMBDA_EXECUTOR=local
          - DOCKER_HOST=unix:///var/run/docker.sock
         volumes:
          - ./.localstack:/tmp/localstack
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:4571"]
    #     interval: 15s
    #     timeout: 20s
    #     retries: 5

**Comment by kink80** [comment] 2019-07-30 08:08
The warning goes away for me with the following docker compose file, note the **user:localstack** entry in it. 

However, there's another error in the `graphCtrl` JS controller where the `$http` directive uses deprecated `success` handler instead of `then`.

```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    user: localstack
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.tmp:/tmp'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

**Comment by LEscobar-Driver** [comment] 2019-07-30 20:07
@kink80 

When I put `user:localstack` I get this error 

      PermissionError: [Errno 1] Operation not permitted: '/opt/code/localstack/localstack/infra/elasticsearch/tmp'


If I put `user:root` it starts up correctly but still getting the error

    2019-07-30T20:04:53:WARNING:localstack.dashboard.infra: Error running command: { test `which aws` || . .venv/bin/activate; }; aws --endpoint-url="http://localhost:4578" es list-domain-names [Errno 1] Operation not permitted: '/tmp/cache.a743de848abda9c36cceb4392861a8f6.json'

**Comment by kink80** [comment] 2019-07-31 11:31
Did you also set the `DATA_DIR` and `volumes` in the same way as shown above?

**Comment by alexhafner** [comment] 2019-07-31 23:17
Experiencing the same issues. 

The files causing the initial errors are actually on the docker image (tests?) e.g. 
/tmp/cache.a743de848abda9c36cceb4392861a8f6.json

chowning them to localstack:localstack gets rid of the error in the log and the cache gets subsequently cleared when refreshing the UI, however still no data is being displayed e.g. for s3 buckets/files working fine on the command line.

There is also a javascript error in Chrome

> angular.js:15567 Error: transition superseded
    at $StateProvider.$get (angular-ui-router.js:2827)
    at Object.invoke (angular.js:5141)
    at angular.js:4930
    at getService (angular.js:5084)
    at injectionArgs (angular.js:5109)
    at Object.invoke (angular.js:5133)
    at angular.js:8778
    at forEach (angular.js:387)
    at Object.<anonymous> (angular.js:8776)
    at Object.invoke (angular.js:5141) "Possibly unhandled rejection: {}"
(anonymous) @ angular.js:15567
(anonymous) @ angular.js:11846
processChecks @ angular.js:17975
$digest @ angular.js:19112
$apply @ angular.js:19500
bootstrapApply @ angular.js:1963
invoke @ angular.js:5141
doBootstrap @ angular.js:1961
bootstrap @ angular.js:1981
angularInit @ angular.js:1866
(anonymous) @ angular.js:36430
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
angular.js:15567 Error: transition prevented
    at $StateProvider.$get (angular-ui-router.js:2828)
    at Object.invoke (angular.js:5141)
    at angular.js:4930
    at getService (angular.js:5084)
    at injectionArgs (angular.js:5109)
    at Object.invoke (angular.js:5133)
    at angular.js:8778
    at forEach (angular.js:387)
    at Object.<anonymous> (angular.js:8776)
    at Object.invoke (angular.js:5141) "Possibly unhandled rejection: {}"
(anonymous) @ angular.js:15567
(anonymous) @ angular.js:11846
processChecks @ angular.js:17975
$digest @ angular.js:19112
$apply @ angular.js:19500
bootstrapApply @ angular.js:1963
invoke @ angular.js:5141
doBootstrap @ angular.js:1961
bootstrap @ angular.js:1981
angularInit @ angular.js:1866
(anonymous) @ angular.js:36430
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
angular.js:15567 Error: transition aborted
    at $StateProvider.$get (angular-ui-router.js:2829)
    at Object.invoke (angular.js:5141)
    at angular.js:4930
    at getService (angular.js:5084)
    at injectionArgs (angular.js:5109)
    at Object.invoke (angular.js:5133)
    at angular.js:8778
    at forEach (angular.js:387)
    at Object.<anonymous> (angular.js:8776)
    at Object.invoke (angular.js:5141) "Possibly unhandled rejection: {}"
(anonymous) @ angular.js:15567
(anonymous) @ angular.js:11846
processChecks @ angular.js:17975
$digest @ angular.js:19112
$apply @ angular.js:19500
bootstrapApply @ angular.js:1963
invoke @ angular.js:5141
doBootstrap @ angular.js:1961
bootstrap @ angular.js:1981
angularInit @ angular.js:1866
(anonymous) @ angular.js:36430
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
B @ jquery.min.js:2
angular.js:15567 Error: transition failed
    at $StateProvider.$get (angular-ui-router.js:2830)
    at Object.invoke (angular.js:5141)
    at angular.js:4930
    at getService (angular.js:5084)
    at injectionArgs (angular.js:5109)
    at Object.invoke (angular.js:5133)
    at angular.js:8778
    at forEach (angular.js:387)
    at Object.<anonymous> (angular.js:8776)
    at Object.invoke (angular.js:5141) "Possibly unhandled rejection: {}"`

**Comment by jkinred** [comment] 2019-08-05 10:07
There seem to be some files in the Docker image which are owned by `root` and therefore causing issues with the processes running inside the container as `localstack`.

```
$ docker run --name localstack -it -e SERVICES=s3 localstack/localstack:0.10.0
$ docker exec -it localstack sh
/opt/code/localstack # ls -l /tmp/
total 168
-rw-r--r--    1 root     root          1299 Aug  3 18:48 cache.04f3aeb71d4a992f80548e35ec919bf1.json
-rw-r--r--    1 root     root             0 Aug  3 18:48 cache.132d9d5d939f0096c790df8777b439d8.json
<snip>
```

You can get it running while waiting for an upstream fix by fixing the permissions and committing to a new image:
```
$ docker run -d --name localstack -it -e SERVICES=s3 localstack/localstack
$ docker exec -it localstack sh -c 'chown -R localstack:localstack /tmp/cache.*'
$ docker stop localstack
$ docker commit localstack mylocalstack
$ docker rm localstack
```

Now reference `mylocalstack`:
```
version: '2.1'
services:
  localstack:
    image: mylocalstack
```

**Comment by ashleshsortee** [comment] 2019-08-05 18:52
after changing permissions, error is not showing but still dashboard is empty.

**Comment by geekyme** [comment] 2019-08-07 09:43
<img width="885" alt="Screenshot 2019-08-07 at 5 42 29 PM" src="https://user-images.githubusercontent.com/977460/62612802-cb34fd00-b93a-11e9-9e83-c3ea02bf640e.png">

Same issue here

**Comment by dknepprath** [comment] 2019-08-12 04:03
I've noticed the dashboard behaving very inconsistently in Safari (sometimes loading no, some, or all of the resources), but it is more consistent in Chrome.

In Chrome, as long as I load `http://localhost:8282` then everything works well. But this url redirects to `http://localhost:8282/#/infra` and if I hit refresh then no resources will display.

**Comment by Deblob12** [comment] 2019-08-12 17:30
Hi all, managed to fix it by changing the docker compose file. The default tmpdir in the docker-compose file template appears to be incorrect and needs to be changed to `"${TMPDIR:-/tmp/localstack}:/tmp"`
Furthermore, LocalStack appears to check if the environment is an AWS environment, so to pass the ```test `which aws` || . .venv/bin/activate``` command, you must set an environment variable `AWS_EXECUTION_ENV=True`

Please reference my docker-compose file below for a working template
```
version: "3"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4568-4597:4568-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,s3,lambda,cloudwatchlogs,iam,sqs,kinesis
      - DEFAULT_REGION=us-west-2
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_EXECUTION_ENV=True
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp"
```

**Comment by unleashit** [comment] 2019-08-14 02:22
Have tried most of the suggestions here (including your exact docker-compose @Deblob12) and it's still not working for me. It appears to be a front end JS issue introduced some time after the 0.8.x release. I don't have any problems getting the right response back from the graph endpoint, it's just not printing to the screen. Not sure why it works for some and not others, but for me it consistently doesn't work unless I downgrade to the older Localstack. I'm also having issues with the IAM service being only partially implemented, but that's a separate problem.

**Comment by dknepprath** [comment] 2019-08-14 05:00
@unleashit, a front end JS issue might explain the difference I'm seeing between Chrome and Safari. What browser are you using?

**Comment by unleashit** [comment] 2019-08-14 06:12
Mainly the latest Chrome in Ubuntu 18, but have occasional tried Firefox (no difference).

**Comment by whummer** [comment] 2019-08-14 13:30
@FighterNan @unleashit @dknepprath @Deblob12 @ashleshsortee @geekyme Should be fixed in #1483 - please report here if the problem persists. Thanks

**Comment by unleashit** [comment] 2019-08-18 20:44
Still not working for me using the latest image from 2 days ago. Can't get anything to display in the dashboard, but when I keep the same settings and downgrade it works.

**Comment by FighterNan** [comment] 2019-08-18 21:46
Pulled the latest image on Aug 18, 2019. The dashboard is still empty after putting objects.

**Comment by bahrmichael** [comment] 2019-08-21 08:56
I just installed localstack for the first time and am getting the same issues.

```
Mac: macOS 10.14.6 (18G87)
Chrome 76.0.3809.100 (Official Build) (64-bit)
```

**Comment by mcintyre94** [comment] 2019-08-30 14:51
Same issue here, note that this is UI only - the call to `/graph` returns data:

```
{
  "edges": [], 
  "nodes": [
    {
      "arn": "arn:aws:s3:::hello-bucket", 
      "id": "f05b7d8a", 
      "name": "hello-bucket", 
      "type": "s3"
    }, 
    {
      "arn": "arn:aws:sqs:us-east-1:queue:hello-queue", 
      "id": "d6780a65", 
      "name": "hello-queue", 
      "type": "sqs"
    }
  ]
}
```

**Comment by whummer** [comment] 2019-09-01 20:18
Thanks @mcintyre94 . Should be fixed in #1521

**Closed** 2019-09-01 20:18 UTC
Labels: cannot-reproduce, needs-triaging, priority-high, question

**Comment by FighterNan** [comment] 2019-09-01 23:19
Pulled the latest image on September 1st, 2019. The dashboard works correctly.
<img width="461" alt="Screen Shot 2019-09-01 at 4 18 25 PM" src="https://user-images.githubusercontent.com/26795118/64083396-3ffa1d80-ccd4-11e9-8830-4b6615759456.png">

**Comment by markomitranic** [comment] 2020-03-05 18:57
Does not work again. Just returns as empty from the API. No errors or anything.

**Comment by geekyme** [comment] 2020-06-25 09:29
This issue is happening again on the frontend (localstack:latest): 

```
angular.js:15570 Error: transition superseded
    at $StateProvider.$get (angular-ui-router.js:2827)
    at Object.invoke (angular.js:5143)
    at angular.js:4932
    at getService (angular.js:5086)
    at injectionArgs (angular.js:5111)
    at Object.invoke (angular.js:5135)
    at angular.js:8781
    at forEach (angular.js:387)
    at Object.<anonymous> (angular.js:8779)
    at Object.invoke (angular.js:5143) "Possibly unhandled rejection: {}"

```

**Comment by T0D0-FIXME** [comment] 2020-09-23 00:08
Do we know if this issue ever got fixed? I just pulled the latest localstack and it has the same issue as well. I am able to access the s3 bucket from command line but the UI doesn't work

**Comment by whummer** [comment] 2020-09-23 19:36
Thanks for the update @geekyme @T0D0-FIXME . Please note that the UI is not actively maintained any longer, and is also excluded from the default `localstack/localstack` Docker image. Can you please try using the `localstack/localstack-full` image instead? If you manage to fix the issue, then a pull request would be much appreciated! Thanks

**Comment by edwardofclt** [comment] 2021-08-11 22:39
> Can you please try using the `localstack/localstack-full` image instead?

@whummer that doesn't work either... I've tried all of the above recommendations too.

**Comment by whummer** [comment] 2021-08-12 13:57
@edwardofclt . Please note that the old legacy dashboard has been removed from the image - this was an old Angular.js app that was full of bugs :) and hasn't been actively maintained since 2018, essentially. If you'd like to use a visual resource browser for your local resources, we'd recommend signing up in our online app here: http://app.localstack.cloud . Hope that helps - please keep us posted how it goes.. Thanks!

**Comment by ypicard** [comment] 2022-03-17 22:16
To me, the new dashboard still does not display data from my bucket even if the CLI does say it exists...
