### ISSUE TITLE
creating/configuring API gateway

### ISSUE THREAD

**Issue by nodejs1** [localstack/localstack#129] opened 2017-06-14 14:21 UTC
I was able to setup localstack on my machine and also create a lambda function using the create-function ... command. However, i was not able to create an API gateway for it so that I can call/trigger it.
How can we create an APIGateway in localstack, so as using the lambda function can be called.

**Comment by whummer** [comment] 2017-06-14 23:35
One option would be to use the serverless framework (https://github.com/serverless/serverless). Otherwise, you can call the LocalStack services directly (via the CLI or an SDK) to create an API Gateway resource+method+integration, and connect them to your Lambda function.

Here are a few pointers that might be helpful:
https://ig.nore.me/2016/03/setting-up-lambda-and-a-gateway-through-the-cli/ (the "Creating a role" part can be skipped)
https://github.com/atlassian/localstack/issues/101
https://github.com/temyers/serverless-localstack

**Comment by nodejs1** [comment] 2017-06-15 07:36
Thanks. The above link is helpful. 
When I try the very basic command "aws --endpoint-url=http://localhost:4567/ apigateway create-rest-api --name "MyFirstAPI"" (specified in the above link), I get an error - "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application."

**Comment by whummer** [comment] 2017-06-18 02:48
@nodejs1 I was unable to reproduce your problem. This is what it looks like for me:
```
$ aws --endpoint-url=http://localhost:4567/ apigateway create-rest-api --name "MyFirstAPI"
{
    "name": "MyFirstAPI", 
    "id": "A-Z19A-Z0A-Z0329", 
    "createdDate": "2017-06-18T02:45:24.132Z"
}
```
It works both when starting LocalStack via Docker (`make docker-run`) and starting it locally (`make infra`). Which command did you use to start up LocalStack?

Can you please try to enable debug output by setting the `DEBUG=1` environment variable. It works for both Docker and local execution (choose either):
```
DEBUG=1 make docker-run 
DEBUG=1 make infra 
```
The `DEBUG` flag should cause LocalStack to print the details of the internal server error. Please post the output here. Thanks

**Comment by whummer** [comment] 2017-07-20 14:41
Is there any update on this issue @nodejs1 ? The root cause for this issue may have been fixed in the meantime, could you please give it a try with the latest version of the code. Thanks

**Comment by whummer** [comment] 2017-08-06 23:14
Closing this issue as there hasn't been an update in a while. Please feel free to re-open if the problem persists. Thanks.

**Closed by whummer** 2017-08-06 23:14 UTC
Labels: bug, needs-triaging

**Comment by GeoffreyBooth** [comment] 2017-12-05 02:01
I’m having this issue too. Can anyone please share an example of how to get an API Gateway endpoint that calls a Lambda function, and returns the response? I followed the examples of http://docs.aws.amazon.com/apigateway/latest/developerguide/create-api-using-awssdk.html and https://ig.nore.me/2016/03/setting-up-lambda-and-a-gateway-through-the-cli/, but whenever I hit the new endpoint I get a 404.

**Comment by westonplatter** [comment] 2019-02-28 16:21
@GeoffreyBooth thanks for posting this. Working off of master today, I wasn't able to get your example url `http://localhost:4567/restapis/9697256665/prod/_user_request_/app/photo/` to work.

Anyone know where this is documented?

**Comment by whummer** [comment] 2019-03-08 03:50
@westonplatter - can you please provide more details, which status code is returned? Can you try starting localstack with `DEBUG=1` and share any error logs or stack traces.

**Comment by Ben168-stack** [comment] 2023-06-27 14:59
@westonplatter I believe url on the api gateway is documented here
https://docs.localstack.cloud/user-guide/aws/apigateway/
