### ISSUE TITLE
bug: aws_sqs_queue_redrive_allow_policy after 2 minutes of 'still creating' errors out with the message 'timeout while waiting for state to become 'equal' ('last state: 'notequal', timeout: 2m0s)

### ISSUE THREAD

**Issue by soheil-salimian1-NHSD** [localstack/localstack#7958] opened 2023-03-24 14:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

aws_sqs_queue_redrive_allow_policy after 2 minutes of 'still creating' errors out with the message 'timeout while waiting for state to become 'equal' ('last state: 'notequal', timeout: 2m0s)

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    run via make-file calls localstack-restart

### Environment

```markdown
- OS: 20.04
- LocalStack: 1.4.0
```

**Comment by thrau** [comment] 2023-03-27 08:52
hi @soheil-salimian1-NHSD, could you please provide instructions on how to reproduce the issue?

**Comment by craigzour** [comment] 2023-06-08 13:06
Hello,

I am also having the same issue. I just found this ticket and I figured I could try to give some more details on how to reproduce it. I happens 100% of the time on my side.

Here is the Terraform resources I am trying to apply to my LocalStack environment:

```
resource "aws_sqs_queue" "audit_log_queue" {
  name                       = "audit_log_queue"
  delay_seconds              = 0
  max_message_size           = 2048
  message_retention_seconds  = 172800 // 2 days
  visibility_timeout_seconds = 1960

  kms_master_key_id                 = "alias/aws/sqs"
  kms_data_key_reuse_period_seconds = 300

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.audit_log_deadletter_queue.arn
    maxReceiveCount     = 5
  })

  redrive_allow_policy = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = [aws_sqs_queue.audit_log_deadletter_queue.arn]
  })

  tags = {
    (var.billing_tag_key) = var.billing_tag_value
    Terraform             = true
  }
}

resource "aws_sqs_queue" "audit_log_deadletter_queue" {
  name                      = "audit_log_deadletter_queue"
  delay_seconds             = 60
  max_message_size          = 262144
  message_retention_seconds = 1209600
  receive_wait_time_seconds = 5

  kms_master_key_id                 = "alias/aws/sqs"
  kms_data_key_reuse_period_seconds = 300

  tags = {
    (var.billing_tag_key) = var.billing_tag_value
    Terraform             = true
  }
}
```

Using `terragrunt apply`, here is the error I get `aws_sqs_queue_redrive_allow_policy after 2 minutes of 'still creating' errors out with the message 'timeout while waiting for state to become 'equal' ('last state: 'notequal', timeout: 2m0s)`

**Comment by awkaplan** [comment] 2023-11-07 23:29
I am able to reliably reproduce this issue.  The response from localstack seems to be missing the RedriveAllowPolicy entirely:

```
localstack  | 2023-11-07T23:26:40.956  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS sqs.GetQueueAttributes => 200; 000000000000/us-east-1; GetQueueAttributesRequest({'QueueUrl': 'http://localstack:4566/000000000000/redacted', 'AttributeNames': ['All']}, headers={'Host': 'localstack:4566', 'User-Agent': 'APN/1.0 HashiCorp/1.0 Terraform/1.5.7 (+https://www.terraform.io) terraform-provider-aws/5.23.1 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.46.3 (go1.20.10; linux; amd64)', 'Content-Length': '151', 'Authorization': 'AWS4-HMAC-SHA256 Credential=cp/20231107/us-east-1/sqs/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=2078cdd6fd39043161fe79cbe0010c1c18fe4f12459858edafcf55244a9cf9c1', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'X-Amz-Date': '20231107T232640Z', 'Accept-Encoding': 'gzip', 'x-localstack-tgt-api': 'sqs', 'x-moto-account-id': '000000000000'}); GetQueueAttributesResult({'Attributes': {'ApproximateNumberOfMessages': 0, 'ApproximateNumberOfMessagesNotVisible': 0, 'ApproximateNumberOfMessagesDelayed': 0, 'CreatedTimestamp': '1699399470', 'DelaySeconds': '0', 'LastModifiedTimestamp': '1699399470', 'MaximumMessageSize': '262144', 'MessageRetentionPeriod': '345600', 'QueueArn': 'arn:aws:sqs:us-east-1:000000000000:redacted, 'ReceiveMessageWaitTimeSeconds': '0', 'VisibilityTimeout': '33', 'SqsManagedSseEnabled': 'true', 'KmsMasterKeyId': 'alias/redacted', 'RedriveAllowPolicy': ''}}, headers={'Content-Type': 'text/xml', 'Content-Length': '1431', 'Connection': 'close', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
```

**Comment by thrau** [comment] 2024-01-04 18:07
I'm no longer able to reproduce the issue with the latest version of localstack, or any version past 3.0.1. i believe this PR is responsible for the fix: https://github.com/localstack/localstack/pull/8268

using this tf file and using `tflocal apply`

```hcl
resource "aws_sqs_queue" "audit_log_queue" {
  name                       = "audit_log_queue"
  delay_seconds              = 0
  max_message_size           = 2048
  message_retention_seconds  = 172800 // 2 days
  visibility_timeout_seconds = 1960

  kms_master_key_id                 = "alias/aws/sqs"
  kms_data_key_reuse_period_seconds = 300

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.audit_log_deadletter_queue.arn
    maxReceiveCount     = 5
  })

  redrive_allow_policy = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = [aws_sqs_queue.audit_log_deadletter_queue.arn]
  })

  tags = {
    billing_tag_key       = "billing_tag_value"
    Terraform             = true
  }
}

resource "aws_sqs_queue" "audit_log_deadletter_queue" {
  name                      = "audit_log_deadletter_queue"
  delay_seconds             = 60
  max_message_size          = 262144
  message_retention_seconds = 1209600
  receive_wait_time_seconds = 5

  kms_master_key_id                 = "alias/aws/sqs"
  kms_data_key_reuse_period_seconds = 300

  tags = {
    billing_tag_key       = "billing_tag_value"
    Terraform             = true
  }
}
```

getting the following output:

```
 % tflocal apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_sqs_queue.audit_log_deadletter_queue will be created
  + resource "aws_sqs_queue" "audit_log_deadletter_queue" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 60
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = 300
      + kms_master_key_id                 = "alias/aws/sqs"
      + max_message_size                  = 262144
      + message_retention_seconds         = 1209600
      + name                              = "audit_log_deadletter_queue"
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 5
      + redrive_allow_policy              = (known after apply)
      + redrive_policy                    = (known after apply)
      + sqs_managed_sse_enabled           = (known after apply)
      + tags                              = {
          + "Terraform"       = "true"
          + "billing_tag_key" = "billing_tag_value"
        }
      + tags_all                          = {
          + "Terraform"       = "true"
          + "billing_tag_key" = "billing_tag_value"
        }
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

  # aws_sqs_queue.audit_log_queue will be created
  + resource "aws_sqs_queue" "audit_log_queue" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = 300
      + kms_master_key_id                 = "alias/aws/sqs"
      + max_message_size                  = 2048
      + message_retention_seconds         = 172800
      + name                              = "audit_log_queue"
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 0
      + redrive_allow_policy              = (known after apply)
      + redrive_policy                    = (known after apply)
      + sqs_managed_sse_enabled           = (known after apply)
      + tags                              = {
          + "Terraform"       = "true"
          + "billing_tag_key" = "billing_tag_value"
        }
      + tags_all                          = {
          + "Terraform"       = "true"
          + "billing_tag_key" = "billing_tag_value"
        }
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 1960
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_sqs_queue.audit_log_deadletter_queue: Creating...
aws_sqs_queue.audit_log_deadletter_queue: Still creating... [10s elapsed]
aws_sqs_queue.audit_log_deadletter_queue: Still creating... [20s elapsed]
aws_sqs_queue.audit_log_deadletter_queue: Creation complete after 25s [id=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/audit_log_deadletter_queue]
aws_sqs_queue.audit_log_queue: Creating...
aws_sqs_queue.audit_log_queue: Still creating... [10s elapsed]
aws_sqs_queue.audit_log_queue: Still creating... [20s elapsed]
aws_sqs_queue.audit_log_queue: Creation complete after 25s [id=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/audit_log_queue]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

getting the queue attributes returns the `RedriveAllowPolicy` correctly:
```console
 % awslocal sqs get-queue-attributes --queue-url http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/audit_log_queue --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "CreatedTimestamp": "1704391469",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1704391469",
        "MaximumMessageSize": "2048",
        "MessageRetentionPeriod": "172800",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:audit_log_queue",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "1960",
        "SqsManagedSseEnabled": "true",
        "KmsDataKeyReusePeriodSeconds": "300",
        "RedriveAllowPolicy": "{\"redrivePermission\":\"byQueue\",\"sourceQueueArns\":[\"arn:aws:sqs:us-east-1:000000000000:audit_log_deadletter_queue\"]}",
        "RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:audit_log_deadletter_queue\",\"maxReceiveCount\":5}",
        "KmsMasterKeyId": "alias/aws/sqs"
    }
}
```

closing as complete. if the issue persists in version >=3.0.1, please open a new issue with the concrete localstack version you are using and how to reproduce the issue. thanks!

**Closed by thrau** 2024-01-04 18:07 UTC
Labels: type: bug, area: integration/terraform, aws:sqs, status: backlog
