### ISSUE TITLE
CreateFunction returns "413 Request Entity Too Large" for 23MB Lambda Zipfile

### ISSUE THREAD

**Issue by shawnrusaw-wf** [localstack/localstack#2727] opened 2020-07-15 14:57 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

## Expected behavior

The Lambda function should be created since the real limit is 50MB as per https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

## Actual behavior

`CreateFunction` command returns 

```
An error occurred (413) when calling the CreateFunction operation:
<!doctype html>
<title>413 Request Entity Too Large</title>
<h1>Request Entity Too Large</h1>
Entity is too large
```

for a python Zip file that is only 23MB in size (approx)

```
%> ls -la /var/folders/.../lambda.zip
-rw-------  1 me  group  22620820 Jul 15 06:47 /var/folders/.../lambda.zip
```

# Steps to reproduce

## Command used to start LocalStack

docker-compose entry like:

```
  localstack:
    image: localstack/localstack:0.11.3
    environment:
      SERVICES: sqs,kinesis,dynamodb,lambda
      HOSTNAME: localstack
      DOCKER_HOST: unix:///var/run/docker.sock
      USE_SSL: 'true'
      DEFAULT_REGION: us-east-1
      LAMBDA_EXECUTOR: local
      LAMBDA_JAVA_OPTS: -Xmx512M
      # AWS_ACCOUNT_ID: anything - is not supported yet on kinesis, do not use
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
%> aws --endpoint-url="https://localhost:4566" lambda create-function ...
```

**Comment by phillip-haydon** [comment] 2020-07-16 15:08
Strange, I have a 31mb .net core lambda works totally fine.

**Comment by shawnrusaw-wf** [comment] 2020-07-17 01:47
@phillip-haydon it only seems to happen when going through the gateway port 4566, and works fine on the deprecated port 4574.

**Comment by phillip-haydon** [comment] 2020-07-17 03:27
@shawnrusaw-wf I just tested with `aws` and `http://localhost:4566` (non ssl cos that doesn't work for me) and it worked. 

My docker compose file looks like this:


```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      #- SERVICES=${SERVICES- }
      - SERVICES=s3,events,sqs,lambda,cloudwatch,iam
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

```
> aws --endpoint-url=http://localhost:4566 lambda create-function --function-name workflow-begin-qc4 --runtime dotnetcore3.1 --memory-size 256 --timeout 60 --zip-file fileb://output/QCWorkflowBeginQCHandler.zip --handler TestLocalStack.Workflows.MediaServices::TestLocalStack.Workflows.MediaServices.QCWorkflowHandler::BeginQCHandler --role arn:aws:iam::000000000000:role/lambda-role
{
    "FunctionName": "workflow-begin-qc4",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:workflow-begin-qc4",
    "Runtime": "dotnetcore3.1",
    "Role": "arn:aws:iam::000000000000:role/lambda-role",
    "Handler": "TestLocalStack.Workflows.MediaServices::TestLocalStack.Workflows.MediaServices.QCWorkflowHandler::BeginQCHandler",
    "CodeSize": 31832094,
    "Description": "",
    "Timeout": 60,
    "MemorySize": 256,
    "LastModified": "2020-07-17T03:20:59.881+0000",
    "CodeSha256": "h5W5LL2tqkYune7h9A4kJ7jutcPmkEyZnpJc+0S3NS4=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "052222ca-29c9-4493-9b44-7a98a8858c47",
    "State": "Active",
    "LastUpdateStatus": "Successful"
}
```

I'll re-test with `0.11.3`

**Comment by whummer** [comment] 2020-07-18 09:14
Thanks for digging into this issue @shawnrusaw-wf @phillip-haydon . I haven't been able to reproduce - tested with both `latest` and `0.11.3`, and both `USE_SSL=0` and `USE_SSL=1`. Can you please provide the full server-side error logs with `DEBUG=1` enabled - ideally we should be able to extract a stack trace from there..? Thanks

**Comment by whummer** [comment] 2020-07-25 12:59
Quick follow-up @shawnrusaw-wf @phillip-haydon - any chance we can get a stack trace from the server logs to better understand the root case here? Or is this perhaps already fixed in the `latest` version, by any chance? Thanks for your help.

**Comment by phillip-haydon** [comment] 2020-07-25 13:22
I’m not sure how to allow the ssl certificate so that I can run it with https. That’s why I’ve only run with http.

**Comment by whummer** [comment] 2020-09-15 19:13
Thanks for the update. This is likely already fixed with some performance enhancements in the HTTP server/middleware layer that have merged recently. Closing this issue - but please feel free to re-open with instructions to reproduce if the problem persists. Thanks!

**Closed by whummer** 2020-09-15 19:13 UTC
Labels: bug, evaluate-or-close, needs-triaging, performance, should-be-fixed

**Comment by bhargavpanth** [comment] 2023-07-05 15:11
I am using the latest Localstack-pro Docker image and still running into this issue when trying to create a lambda function.
