### ISSUE TITLE
bug: S3 Select on gzipped csv is erroring

### ISSUE THREAD

**Issue by hemachandran-kalaimani** [localstack/localstack#10888] opened 2024-05-24 11:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do a S3 select query `SELECT COUNT(*) AS recordCount FROM s3Object` on a gzipped CSV file in S3, getting the following error:

```
exception while calling s3.SelectObjectContent: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/s3/v3/provider.py.enc", line 28, in select_object_content
    A=SpooledTemporaryFile(max_size=S3_SELECT_MAX_SPOOLED_SIZE,newline='',mode='w+');C=run_s3_select_query(bucket,key,expression,input_serialization=input_serialization,scan_range=scan_range);dump_s3_select_result(C,output_serialization,file_obj=A);A.seek(0)
                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/s3/s3_select_utils.py.enc", line 108, in run_s3_select_query
    elif _H in C:extract_scan_range(A,E,get_serialization_config(B,_C));F=query_csv(D,A,input_serialization=B)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/s3/s3_select_utils.py.enc", line 46, in query_csv
    def query_csv(query,csv_file,db_name=_A,input_serialization=_A):return run_query(query,csv_file,_H,db_name=db_name,input_serialization=input_serialization)
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/s3/s3_select_utils.py.enc", line 94, in run_query
    if F==_H:E=get_serialization_config(G,_C,{}).get(_J,'NONE');E=E.upper();csvquerytool.create_table_from_csv(I,C,D,header_info=E)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/utils/csvquerytool.py.enc", line 29, in create_table_from_csv
    F=count_columns(A);A.seek(0);G=csv.reader(A,skipinitialspace=_A)
      ^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/utils/csvquerytool.py.enc", line 25, in count_columns
    def count_columns(fh):A=csv.reader(fh,skipinitialspace=_A);return max(len(A)for A in A)
                                                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/utils/csvquerytool.py.enc", line 25, in <genexpr>
    def count_columns(fh):A=csv.reader(fh,skipinitialspace=_A);return max(len(A)for A in A)
                                                                         ^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

```

### Expected Behavior

It should return the number of records and not error out.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Tried using docker-compose on `localstack-pro` version.

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version: 3.1.1.dev20240126193412
  LocalStack Docker image sha: 349a7e64c77d
  LocalStack build date: 2024-01-27
  LocalStack build git hash: bc34f91
```

**Comment by bentsku** [comment] 2024-06-05 22:01
Please also feel free to close the issue if the new image fixes the issue, or give feedback if there's still anything wrong. Thanks! 🙏

**Comment by bentsku** [comment] 2024-06-11 10:26
I'll close the issue, please feel free to comment again if the issue is still here. Thanks!

**Closed by bentsku** 2024-06-11 10:26 UTC
Labels: type: bug, status: response required, aws:s3
