### ISSUE TITLE
bug: Inernal server error in get-object with Range header

### ISSUE THREAD

**Issue by ma91n** [localstack/localstack#6988] opened 2022-10-07 03:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

## s3 get-object with `--range` option result is invalid

$ aws --profile local --endpoint-url http://localhost:4566 s3api get-object --bucket local-bucket --key local-test.csv --range bytes=0-10 out.csv        
An error occurred (InternalError) when calling the GetObject operation (reached max retries: 2): exception while calling s3.GetObject: Traceback (most recent call last):

### Expected Behavior

no error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
-- docker-compose.yaml
localstack:
container_name: localstack
image: localstack/localstack:1.1.0
ports:
  - "4566:4566"
environment:
  - SERVICES=s3
  - DEFAULT_REGION=ap-northeast-1
  - AWS_DEFAULT_REGION=ap-northeast-1
  - AWS_DEFAULT_OUTPUT=json
  - AWS_ACCESS_KEY_ID=test
  - AWS_SECRET_ACCESS_KEY=test
  - DEBUG=1
  - LS_LOG=debug
```

$ docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
$ echo "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" > local-test.txt

$ aws --profile local --endpoint-url http://localhost:4566 s3api create-bucket --bucket local-bucket --create-bucket-configuration LocationConstraint=ap-northeast-1
$ aws --profile local --endpoint-url http://localhost:4566 s3 cp local-test.txt s3://local-bucket/local-test.csv
$ aws --profile local --endpoint-url http://localhost:4566 s3api get-object --bucket local-bucket --key local-test.csv --range bytes=0-10 out.csv        
An error occurred (InternalError) when calling the GetObject operation (reached max retries: 2): exception while calling s3.GetObject: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
    result = self.forward_request(
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
    return do_forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 602, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 775, in modify_and_forward
    updated_response = listener.return_response(
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1697, in return_response
    fix_range_content_type(bucket_name, path, headers, response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 790, in fix_range_content_type
    result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 934, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (503) when calling the HeadObject operation (reached max retries: 4): Service Unavailable
```

### Localstack log

$ docker-compose logs -f localstack

```log
localstack    | 2022-10-07T03:45:17.862  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
localstack    | 2022-10-07T03:45:29.991 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
localstack    |     handler(self, self.context, response)
localstack    |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
localstack    |     handler(chain, context, response)
localstack    |   File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
localstack    |     result = self.forward_request(
localstack    |   File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
localstack    |     return do_forward_request(
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
localstack    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
localstack    |     response = modify_and_forward(
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 602, in wrapper
localstack    |     value = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 775, in modify_and_forward
localstack    |     updated_response = listener.return_response(
localstack    |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1697, in return_response
localstack    | 2022-10-07T03:45:40.929 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
localstack    |     handler(self, self.context, response)
localstack    |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
localstack    |     handler(chain, context, response)
localstack    |   File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
localstack    |     result = self.forward_request(
localstack    |   File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
localstack    |     return do_forward_request(
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
localstack    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
localstack    |     response = modify_and_forward(
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 602, in wrapper
localstack    |     value = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 775, in modify_and_forward
localstack    |     updated_response = listener.return_response(
localstack    |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1697, in return_response
localstack    |     fix_range_content_type(bucket_name, path, headers, response)
localstack    |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 790, in fix_range_content_type
localstack    |     result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
localstack    |     return self._make_api_call(operation_name, kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 934, in _make_api_call
localstack    |     raise error_class(parsed_response, operation_name)
localstack    | botocore.exceptions.ClientError: An error occurred (503) when calling the HeadObject operation (reached max retries: 4): Service Unavailable
localstack    | 2022-10-07T03:45:40.931  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
```

### Environment

```markdown
- OS: Windows10
- LocalStack: 1.1.0
```

**Comment by bentsku** [comment] 2022-12-08 15:58
Hello and thanks for your report.

I'm currently unable to reproduce your issue locally.

Would it be possible to try it with a feature flag on? We have been working on a new implementation of S3. Could you try pulling the latest Docker image (`localstack/localstack:1.3` or `latest`) and set the environment variable `PROVIDER_OVERRIDE_S3=“asf”`? It might fix your issue.

If it does not, could please try to set the environment variable `LS_LOG=trace`? We might get more information about what is going on.  

Thanks a lot for your feedback!

**Comment by bentsku** [comment] 2022-12-30 14:51
Hello! As it's been 3 weeks and the issue is not currently reproducible and we have tests covering the `--range` parameter with the new S3 provider, I'll close the issue.
Using `PROVIDER_OVERRIDE_S3=asf` should fix your issue. In case it does not, please don't hesitate to comment and I'll reopen this issue. 

Thanks for your report!

**Closed by bentsku** 2022-12-30 14:51 UTC
Labels: type: bug, status: response required, aws:s3
