### ISSUE TITLE
using serverless-localstack and having problems with authentication. 

### ISSUE THREAD

**Issue by st33v** [localstack/localstack#649] opened 2018-03-08 20:43 UTC
hello... I'm trying to use 'serverless-localstack' to deploy a lambda function. It seems to work, despite throwing an error:
```
Serverless Error ---------------------------------------

Attribute without value
Line: 13
Column: 70
Char: a
```

I'm also having trouble using `sls invoke` to run my lambda function. I have to use real security tokens because SLS will give me grief:

```

  Serverless Error ---------------------------------------

  The security token included in the request is invalid.
```

if I do that, sls, miscalculates the ARN of my function:
```
  Serverless Error ---------------------------------------

  Function not found: arn:aws:lambda:us-east-1:94195FOO6246:function:aws-nodejs-dev-hello
```

where the functions are more like:
```son
{
    "Functions": [
        {
            "FunctionName": "aws-nodejs-dev-hello",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:aws-nodejs-dev-hello",
            "Runtime": "nodejs6.10",
            "Handler": "handler.hello",
            "CodeSize": 50,
            "Version": "$LATEST",
            "Environment": {}
        },
        {
            "FunctionName": "aws-nodejs-local-hello",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:aws-nodejs-local-hello",
            "Runtime": "nodejs6.10",
            "Handler": "handler.hello",
            "CodeSize": 50,
            "Version": "$LATEST",
            "Environment": {}
        }
    ]
}
```

**Comment by juancho088** [comment] 2018-03-14 12:29
+1

**Comment by suryacaprice** [comment] 2018-03-24 06:45
+1

**Comment by actsasgeek** [comment] 2018-05-04 18:18
I have the same issue which has been reported here as well:

https://github.com/temyers/serverless-localstack/issues/32

I gave up on localstack + serverless for a while and started using serverless + AWS lab account and...boom...I'm getting the same security token error (although I can confirm that when I get the first error, I can invoke the function using `aws` just not `sls`)

While this might not be the case for everyone, for me, It's not clear that this isn't at least potentially a problem with serverless: https://github.com/serverless/serverless/issues/4592 and not localstack or the serverless plugin.

I seem to be able to use both aws and Python scripts with both AWS and localstack but adding serverless into the mix causes problems.

**Comment by bargenson** [comment] 2018-05-05 00:38
It's related to a bad XML returned by CloudFormation containing an object reference. This ticket seems to be source cause : https://github.com/spulec/moto/issues/1588

**Comment by whummer** [comment] 2019-11-08 21:03
Should have been fixed in the meantime - thanks @st33v @bargenson @actsasgeek . Please re-open this issue if the problem persists.

**Closed by whummer** 2019-11-08 21:03 UTC
Labels: bug
