### ISSUE TITLE
S3 object metadata behavior is inconsistent with AWS behavior

### ISSUE THREAD

**Issue by dparrella** [localstack/localstack#1790] opened 2019-11-22 18:53 UTC
When PUTting an S3 object to Localstack with attached Metadata, if a key contains an underscore it is replaced with a dash.

However, when the same request is performed against the real S3, the key is not modified.

Example Input:
key_with_underscores => test

Localstack Result:
key-with-underscores => test

S3 Result:
key_with_underscores => test

Localstack Version: 0.10.5

Tested using AWS v2 S3 client

**Comment by whummer** [comment] 2020-01-18 21:38
Thanks for reporting @dparrella . This looks like a duplicate of #459, which has been closed as "won't fix". Please refer to the description in this issue comment as to why this is something that is currently not easy to fix in LocalStack: https://github.com/localstack/localstack/issues/459#issuecomment-346756560 Going to close this issue as well - the recommended workaround is to avoid using metadata keys with underscores at this point. Thanks

**Closed by whummer** 2020-01-18 21:38 UTC

**Comment by whummer** [comment] 2020-01-18 22:59
The previous comment is obsolete. A workaround has been applied in #1965 which should fix this issue. The limitation from now on is that metadata keys must not contain three dashes in a row (which should be a reasonable assumption for most cases) as they would get transformed to an underscore.
