### ISSUE TITLE
IAM Attached Policies Issues 

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2660] opened 2020-07-02 11:45 UTC
This is with reference to ticket https://github.com/localstack/localstack/issues/2649
The IAM policies do show on Assume roles on the I have created the policies and attached to it. Moreover the policies are not working. The restrict permission are not working for definite bucket define.

**Comment by usmangani1** [comment] 2020-07-02 11:52
Hey @RSHUKL01  could you please provide us the contents of assume-role-policy-document which you are using to create the given role ? This would help us to dig a bit more into this issue.

**Comment by rpattcorner** [comment] 2020-07-02 14:47
This issue is very likely a duplicate of #2647 -- if so, the first comment has an example policy document and some quick Python code to illustrate the problem.

**Comment by usmangani1** [comment] 2020-07-02 19:49
@rpattcorner  it just works as expected with the assume-role-policy-document mentioned in the #2647.We are actually trying to reproduce this issue using AWS and it works absolutely fine.

 ```
aws iam create-role --role-name trust-role-2 --assume-role-policy-document file://trust-policy.json

{
    "Role": {
        "Path": "/",
        "RoleName": "trust-role-2",
        "RoleId": "AROARCSPW2WNTCIK7DPCB",
        "Arn": "arn:aws:iam::074255357339:role/trust-role-2",
        "CreateDate": "2020-07-02T19:41:29Z",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "AWS": [
                            "arn:aws:iam::074255357339:user/ls-dev-1"
                        ]
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        }
    }
}

aws iam list-attached-role-policies --role-name trust-role-2 
{
    "AttachedPolicies": []
}

```

**Comment by RSHUKL01** [comment] 2020-07-20 04:44
@usmangani1 @rpattcorner I have used the similar case in actual AWS and I am not getting the below output.
The policy name which is attached to role is visible when listing the policies of role. We have tried the same scenario with java SDK in localstack and it is working fine there. There is some issue with aws cli. Your help is appreciated here.
{
   "AttachedPolicies": []
}

**Comment by usmangani1** [comment] 2020-07-20 18:13
@RSHUKL01 As we are not able to reproduce with the issue with other policy documents mentioned above.Can you please help us with the policy document with which you are using ?

**Comment by RSHUKL01** [comment] 2020-07-21 12:31
@usmangani1 You can try with any policy document. Below are the things we tried with java sdk and it is working fine but when we are trying with aws cli it is not working,
1.	Create policy (Policy document attached)- java code

                     IamClient iamClient = awsClientBuilderUtil.getIamClient(awsStaticCredentialsProvider);
                     
                     String policyDocument = new String(multipartFile.getBytes());
                     
                     CreatePolicyRequest createPolicyRequest = CreatePolicyRequest.builder()
                       .policyName(policyName)
                       .policyDocument(policyDocument).build();

                     CreatePolicyResponse createPolicyResponse = iamClient.createPolicy(createPolicyRequest);

2.	Policy created             
 
![policy created](https://user-images.githubusercontent.com/65276850/88054835-a18cda00-cb7b-11ea-8bfe-c7358b767ff2.png)

3.	Create role – java code
                                IamClient iamClient = awsClientBuilderUtil.getIamClient(awsStaticCredentialsProvider);
                                                
                                CreateRoleRequest createRoleRequest = CreateRoleRequest.builder()
                                                                .roleName(roleName)
                                                                .build();
                                                
                                CreateRoleResponse createRoleResponse = iamClient.createRole(createRoleRequest);
4.	Role created
![role created](https://user-images.githubusercontent.com/65276850/88054892-bb2e2180-cb7b-11ea-8a71-aa676c0023b3.png)
5.	Attach policy to role – java code
                                IamClient iamClient = awsClientBuilderUtil.getIamClient(awsStaticCredentialsProvider);
                                                
                                AttachRolePolicyRequest attachRolePolicyRequest = AttachRolePolicyRequest.builder()
                                                                .roleName(“test-role”)
                                                                .policyArn(“arn:aws:iam::000000000000:policy/test-policy")
                                                                .build();
                                                                                
                                iamClient.attachRolePolicy(attachRolePolicyRequest);

6.	Policy attached to role
![policy attc](https://user-images.githubusercontent.com/65276850/88055024-ef094700-cb7b-11ea-92e2-a85c649a5c78.png)

7.	List attached policies of user – java code
IamClient iamClient = awsClientBuilderUtil.getIamClient(awsStaticCredentialsProvider);
                                                
                                ListAttachedRolePoliciesRequest listAttachedRolePoliciesRequest = ListAttachedRolePoliciesRequest.builder()
                                                                .roleName(roleName)
                                                                .build();
                                                                                
                                ListAttachedRolePoliciesResponse listAttachedRolePoliciesResponse = iamClient.listAttachedRolePolicies(listAttachedRolePoliciesRequest);
                                                
                                List<AttachedPolicy> policies = listAttachedRolePoliciesResponse.attachedPolicies(); 
                                                
                                                List<String> policyNames = new ArrayList<>();
                                                
                                policies.forEach(policy -> {
                                               policyNames.add(policy.policyName());
                                });
8.	Attached policies of role
![attached policy](https://user-images.githubusercontent.com/65276850/88055107-0ea06f80-cb7c-11ea-93c5-11483558d81b.png)

Policy used
[Allowing_an_IAM_User_Access_to_One_of_Your_Buckets.txt](https://github.com/localstack/localstack/files/4953454/Allowing_an_IAM_User_Access_to_One_of_Your_Buckets.txt)

**Comment by whummer** [comment] 2020-09-22 23:28
Unable to reproduce with the provided details - please reopen this issue with a clear, self-contained, textual (!) example code snippet (please no screenshots) - clearly showing the discrepancy between AWS and LocalStack behavior - if the problem persists. Thanks!

**Closed by whummer** 2020-09-22 23:28 UTC
