### ISSUE TITLE
command not found: localstack

### ISSUE THREAD

**Issue by orr-levinger** [localstack/localstack#404] opened 2017-10-15 14:46 UTC
**after successfully installing localstack:**
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 airspeed-0.5.5.dev20160812 asn1crypto-0.23.0 awscli-1.11.86 boto-2.46.1 boto3-1.4.4 botocore-1.5.49 cachetools-0.8.0 certifi-2017.7.27.1 cffi-1.11.2 chardet-3.0.4 colorama-0.3.7 configparser-3.5.0 cookies-2.2.1 coverage-4.0.3 cryptography-2.1.1 decorator-4.1.2 dicttoxml-1.7.4 dnslib-0.9.7 docopt-0.6.2 docutils-0.14 ecdsa-0.13 elasticsearch-5.3.0 enum34-1.1.6 envs-1.2.3 flake8-3.4.1 flake8-quotes-0.11.0 flask-0.10.1 flask-cors-3.0.3 flask-swagger-0.2.12 funcsigs-1.0.2 future-0.16.0 futures-3.1.1 idna-2.6 ipaddress-1.0.18 itsdangerous-0.24 jmespath-0.9.3 jsonpath-rw-1.4.0 localstack-0.8.1 localstack-ext-0.7.0.7 mccabe-0.6.1 mock-2.0.0 moto-ext-1.1.5 nose-1.3.7 pbr-3.1.1 ply-3.10 psutil-5.2.0 pyOpenSSL-17.0.0 pyYAML-3.12 pyaes-1.6.0 pyaml-17.10.0 pyasn1-0.3.7 pycodestyle-2.3.1 pycparser-2.18 pycryptodome-3.3.1 pyflakes-1.5.0 pyminifier-2.1 python-coveralls-2.7.0 python-dateutil-2.6.1 python-jose-ext-1.3.2.2 pytz-2017.2 requests-2.18.4 requests-aws4auth-0.9 rsa-3.4.2 s3transfer-0.1.11 sh-1.12.14 six-1.11.0 srp-ext-1.0.7.1 subprocess32-ext-3.2.8.2 urllib3-1.22 warrant-ext-0.2.0.3 xmltodict-0.10.2
 

than when i try to 
localstack start                 
i get : zsh: command not found: localstack

**Comment by whummer** [comment] 2017-10-15 15:58
Thanks for reporting @orr-levinger . This looks like a duplicate of #366. Can you please follow the instructions posted there. Thanks

**Comment by webmake** [comment] 2018-01-18 22:18
I had same issue, and after long time of installation/uninstallation eventually I decided to read output log, and in my case uninstall info shown me where localstack actually was installed
```
$ pip uninstall localstack
Uninstalling localstack-0.8.4:
  /home/vagrant/.local/bin/localstack
  /home/vagrant/.local/lib/python2.7/site-packages/localstack-0.8.4.dist-info/DESCRIPTION.rst
...
```
so running `/home/vagrant/.local/bin/localstack start` works, as mentioned in #366 you can add path that command would work

**Comment by whummer** [comment] 2018-01-21 19:52
Thanks for confirming the fix @webmake . Closing this issue now, please re-open or comment here if the problem persists.

**Closed by whummer** 2018-01-21 19:52 UTC
Labels: installation, possible-duplicate
