### ISSUE TITLE
LocalStack: Cloudformation- Issue

### ISSUE THREAD

**Issue by RSHUKL01** [localstack/localstack#2698] opened 2020-07-08 09:18 UTC
I am trying to list the stack with filter condition.
Command Used:  aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE --endpoint-url=http://localhost:443

Error: It is showing all the stack which are in progress state. The filter condition is not working fine.
Please find the screenshot attached.
![Error](https://user-images.githubusercontent.com/65276850/86901295-0bdc5e00-c12a-11ea-9a28-eb776e1da118.PNG)

@whummer  Can you please look into this.

**Comment by whummer** [comment] 2020-07-14 18:50
Thanks for reporting @RSHUKL01 - this should be fixed in the latest version. Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by RSHUKL01** [comment] 2020-07-20 04:46
@whummer we have tried with the latest version of localstack and the issue is not yet fixed. Your help is appreciated here and let me know if you need any other detail on this.

**Comment by whummer** [comment] 2020-07-28 22:39
Thanks for the update @RSHUKL01 . Can you please try running `docker pull localstack/localstack` to ensure the `latest` image is pulled from Docker Hub?

Please report your image version and age here, for example:
```
$ docker images | grep localstack/localstack
localstack/localstack                latest                                           bf271bf883cb        9 days ago          677MB
```
Thanks

**Comment by usmangani1** [comment] 2020-08-05 19:34
@RSHUKL01 
We are not able to reproduce this issue with the latest docker image.Please find the aws cli commands and the responses attached below.

Also In the dynamo.json you had attached in the Issue #2700 there seems to be some issue. The values of ReadCapacityUnits and WriteCapacityUnits should be in of type int where as string type is specified as below.
**"ReadCapacityUnits" : "5",
"WriteCapacityUnits" : "5"** 
We would suggest to please correct this and give it a try.

$ docker images |  grep localstack/localstack
localstack/localstack   latest                   **6110f7cf464f**        8 hours ago         664MB

$ awslocal cloudformation create-stack --stack-name examplestack1 --template-body file://dynamo.json
{
    "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/examplestack1/f0b4d201-440f-4f24-9184-ca8e7ffe8360"
}

$ awslocal cloudformation list-stacks --stack-status-filter CREATE_COMPLETE
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/examplestack1/f0b4d201-440f-4f24-9184-ca8e7ffe8360",
            "StackName": "examplestack1",
            "TemplateDescription": "None",
            "CreationTime": "2020-08-05T19:27:21Z",
            "StackStatus": "CREATE_COMPLETE"
        }
    ]
}
Please let us know in case if you have any issues with the same.

**Comment by whummer** [comment] 2020-08-12 20:56
Thanks for the update @usmangani1 . @RSHUKL01 if this problem persists with the `latest` version of the Docker image (after pulling it from Docker Hub), then please provide exact steps to reproduce, similar to the `awslocal` commands above. Many thanks for your help.

**Closed by whummer** 2020-08-12 20:56 UTC
Labels: bug, cloudformation, diverges-from-aws, needs-triaging
