### ISSUE TITLE
Create Lambda function using SAM template

### ISSUE THREAD

**Issue by emeraldBazaar** [localstack/localstack#632] opened 2018-03-01 22:56 UTC
Is it possible to create a lambda function using SAM template? For example:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
     TestLambda:
            Type: 'AWS::Serverless::Function'
             Properties:
                    CodeUri: ./testLambda.zip
                     Handler: testLambda.handler
                      .......
```

When I try to package to s3 in localstack using the following command:

aws --endpoint-url=http://localhost:4581 cloudformation package --template-file test.yaml --output-template-file output.yaml --s3-bucket test-bucket

I get an error as follows:
Unable to upload artifact ./testLambda.zip referenced by CodeUri parameter of TestLambda resource. An error occurred (AccessDenied) when calling the PutObject operation: Access Denied.

Any help will be appreciated.

**Comment by 0rangeMan** [comment] 2018-03-14 13:41
+1
Having the same issue

**Comment by Guy-Incognito** [comment] 2018-03-14 15:47
+1

**Comment by tamanjoku** [comment] 2018-04-18 07:09
+1
Having the same issue.

**Comment by byumark** [comment] 2018-05-14 14:58
I think I got around this issue by packaging my code and uploading it myself, but then I started getting this error when running deploy.

https://github.com/localstack/localstack/issues/760

The deploy command eventually returns this:
`HTTPConnectionPool(host='localhost', port=4581): Read timed out.`

**Comment by whummer** [comment] 2019-11-16 12:10
Thanks for reporting @emeraldBazaar @0rangeMan @Guy-Incognito @tamanjoku @baronswindle @byumark - this should be fixed in #1766 . Can you please give it a try with the latest version. Please re-open if the problem persists. Thanks

**Comment by ben-eb** [comment] 2019-11-20 13:31
Same issue for me, with the following template:

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello, world

Resources:
    HelloWorld:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./helloWorld/
            Handler: index.handler
            Runtime: nodejs10.x

```

and `index.js`:

```js
const handler = () => `Hello, world`;

exports.handler = handler;
```

After doing [`awslocal s3 mb s3://test-bucket`](https://github.com/localstack/awscli-local), I try `awslocal cloudformation package --template-file template.yaml --output-template-file output.yaml --s3-bucket test-bucket` and get the following error:

>Unable to upload artifact ./helloWorld/ referenced by CodeUri parameter of HelloWorld resource.
>
>An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

For now I'm working around this by creating resources via the JS SDK, but it's not ideal. I am using the latest docker image if that helps. 😃

**Comment by miron4dev** [comment] 2019-12-02 12:12
@whummer the issue is not solved. I'm still getting the same error.

**Comment by whummer** [comment] 2019-12-02 23:56
@ben-eb @miron4dev Turns out this is not an issue with LocalStack, but with the AWS command line interface which does not support specifying an S3 endpoint for the `cloudformation package` command. Tracking the progress of this issue here: #1783 Thanks

**Closed by whummer** 2019-12-02 23:56 UTC
Labels: bug, feature-missing, priority-high
