### ISSUE TITLE
cross acount

### ISSUE THREAD

**Issue by synajen** [localstack/localstack#2218] opened 2020-03-29 12:45 UTC
# Type of request:
This is a feature request

# Detailed description

As far as I see there is no support for services that connect from different accounts.
Example: lambda in account X reading from dynamo db in account Y

Could you add it? Is there any way now to simulate this?

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment] 2020-03-29 17:04
Thanks for reporting @synajen . Closing this as duplicate of #1498 , which contains a very similar feature request. Please follow the discussion there and feel free to chime in. Thanks

**Closed by whummer** 2020-03-29 17:04 UTC
