### ISSUE TITLE
Localstack SNS Notification message format is wrong

### ISSUE THREAD

**Issue by troygould** [localstack/localstack#2165] opened 2020-03-17 22:45 UTC
According to AWS docs: [http-notification-json](https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html#http-notification-json)
the message should look something like this:
```
POST / HTTP/1.1
x-amz-sns-message-type: Notification
x-amz-sns-message-id: 22b80b92-fdea-4c2c-8f9d-bdfb0c7bf324
x-amz-sns-topic-arn: arn:aws:sns:us-west-2:123456789012:MyTopic
x-amz-sns-subscription-arn: arn:aws:sns:us-west-2:123456789012:MyTopic:c9135db0-26c4-47ec-8998-413945fb5a96
Content-Length: 773
Content-Type: text/plain; charset=UTF-8
Host: myhost.example.com
Connection: Keep-Alive
User-Agent: Amazon Simple Notification Service Agent
{
  "Type" : "Notification",
  "MessageId" : "22b80b92-fdea-4c2c-8f9d-bdfb0c7bf324",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Subject" : "My First Message",
  "Message" : "Hello world!",
  "Timestamp" : "2012-05-02T00:54:06.655Z",
  "SignatureVersion" : "1",
  "Signature" : "EXAMPLEw6JRN...",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem",
  "UnsubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-2:123456789012:MyTopic:c9135db0-26c4-47ec-8998-413945fb5a96"
}
```

However, the message created by localstack for Notifications looks more like this:
```
{
	"Type": "Notification",
	"MessageId": "2f097989-310c-46db-a510-c735cf52a5c5",
	"Token": null,
	"TopicArn": "arn:aws:sns:us-west-2:000000000000:my-topic",
	"Message": "{\"Records\": [{\"eventVersion\": \"2.0\", \"eventSource\": \"aws:s3\", \"awsRegion\": \"us-west-2\", \"eventTime\": \"2020-03-17T05:48:19.212324Z\", \"eventName\": \"ObjectCreated:Put\", \"userIdentity\": {\"principalId\": \"AIDAJDPLRKLG7UEXAMPLE\"}, \"requestParameters\": {\"sourceIPAddress\": \"127.0.0.1\"}, \"responseElements\": {\"x-amz-request-id\": \"867e6137\", \"x-amz-id-2\": \"eftixk72aD6Ap51TnqcoF8eFidJG9Z/2\"}, \"s3\": {\"s3SchemaVersion\": \"1.0\", \"configurationId\": \"testConfigRule\", \"bucket\": {\"name\": \"xxxx-qual-edi-123456789012-us-west-2\", \"ownerIdentity\": {\"principalId\": \"A3NL1KOZZKExample\"}, \"arn\": \"arn:aws:s3:::xxxx-qual-edi-123456789012-us-west-2\"}, \"object\": {\"key\": \"test2.txt\", \"size\": 46, \"eTag\": \"d41d8cd98f00b204e9800998ecf8427e\", \"versionId\": null, \"sequencer\": \"0055AED6DCD90281E5\"}}}]}",
	"SubscribeURL": null,
	"Timestamp": "2020-03-17T05:48:19.215537Z",
	"SignatureVersion": "1",
	"Signature": "EXAMPLEpH+..",
	"SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem",
	"Subject": "Amazon S3 Notification"
}
```

When I use the AWS .NET SDK's Message.ParseMessage(string), it's failing for a message from localstack. The message should not have Token and SubscribeURL. It is also missing the UnsubscribeURL which is part of the Notification message, but not the ConfirmSubscription message.

It looks like sns_listener.py, line: 420 where data object is created is wrong for Notification messages.  

I'd love to help fix this as it's a simple fix. Unfortunately, this is my first experience with python and docker. I've attempted to fix locally, run make and regenerate the docker image, but I just keep hitting landmines - a combination of my inexperience with both and possibly because I'm running on Windows.

**Comment by whummer** [comment] 2020-03-20 00:28
Thanks for reporting @troygould .

> When I use the AWS .NET SDK's Message.ParseMessage(string), it's failing for a message from localstack. The message should not have Token and SubscribeURL

This should indeed be a relatively simple fix. Can you please try making these two small changes, and create a pull request against this repository. The integration tests will then be automatically executed in our CI system (Travis CI), so you don't need to fiddle with the test locally.

Another option is to run `make docker-build` locally, which runs the tests in Docker; that usually produces relatively reproducible results. Thanks

**Comment by whummer** [comment] 2020-05-28 20:36
This should be fixed in #2467 - thanks @andrei-gypaetus . Please report here if the problem persists in the `latest` version. Thanks!

**Closed by whummer** 2020-05-28 20:36 UTC
Labels: diverges-from-aws, pr-requested

**Comment by KarlKl** [comment] 2020-12-23 16:14
I still have the problem that the Message.ParseMessage(string) is failing with the AWS .NET SDK. The problem is that nothing in the JSON is allowed to be `null`.
So in my case `Token` and `SubscribeURL` needs to be String. Empty string would be OK.

Another problem is the signature, but that could be worked around.

**Comment by danielloader** [comment] 2022-02-10 12:44
Just to say still getting this problem now:

```
localstack_main | localstack.services.awslambda.lambda_executors.InvocationException: Lambda runtime error. Result: {'errorMessage': "'UnsubscribeURL'", 'errorType': 'KeyError', 'requestId': 'ecc5a796', 'stackTrace': ['  File "/var/task/src/handler.py", line 105, in debug_handler\n    ret = parse(event=event, model=S3Model, envelope=SnsSqsEnvelope)\n', '  File "/var/lang/lib/python3.9/site-packages/aws_lambda_powertools/utilities/parser/parser.py", line 154, in parse\n    return envelope().parse(data=event, model=model)\n', '  File "/var/lang/lib/python3.9/site-packages/aws_lambda_powertools/utilities/parser/envelopes/sns.py", line 72, in parse\n    sns_notification = SnsNotificationModel.parse_raw(record.body)\n', '  File "pydantic/main.py", line 534, in pydantic.main.BaseModel.parse_raw\n', '  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj\n', '  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__\n', '  File "pydantic/main.py", line 996, in pydantic.main.validate_model\n', '  File "/var/lang/lib/python3.9/site-packages/aws_lambda_powertools/utilities/parser/models/sns.py", line 32, in check_sqs_protocol\n    values["UnsubscribeUrl"] = values.pop("UnsubscribeURL")\n']}
```

Context: Trying to use https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#built-in-envelopes to validate the event sources, using a `SnsSqsEnvelope` envelop on a `S3Model` PUT event, being passed to SNS, to SQS to lambda.

Might be worth dogfooding the services with these up to date model validators for the JSON events.
