### ISSUE TITLE
Getting dependecny error while using Localstack during Junit test 

### ISSUE THREAD

**Issue by atanupanda** [localstack/localstack#974] opened 2018-10-23 06:15 UTC
Dear Team,

We have integrated localstack in Junit, and also we have given proxy while building the maven build. as 

clean install -Dhttp.proxyHost=xyx -Dhttp.proxyPort=abc -Dhttps.proxyHost=xyz -Dhttps.proxyPort=abc
(please note this proxy works when i run pip install --user localstack)
but while running we get below error as 

<pre>
`
build	22-Oct-2018 13:24:46	-------------------------------------------------------
build	22-Oct-2018 13:24:46	 T E S T S
build	22-Oct-2018 13:24:46	-------------------------------------------------------
build	22-Oct-2018 13:24:48	Running com.telstra.accessdm.avc.test.AVCInitiationServiceLocalStackTest
error	22-Oct-2018 13:24:48	Oct 22, 2018 1:24:48 PM cloud.localstack.docker.annotation.LocalstackDockerAnnotationProcessor getExternalHostName
error	22-Oct-2018 13:24:48	INFO: External host name is set to: localhost
error	22-Oct-2018 13:24:48	Oct 22, 2018 1:24:48 PM cloud.localstack.docker.Container createLocalstackContainer
error	22-Oct-2018 13:24:48	INFO: Pulling latest image...
error	22-Oct-2018 13:27:09	Oct 22, 2018 1:27:09 PM cloud.localstack.docker.Container createLocalstackContainer
error	22-Oct-2018 13:27:09	INFO: Started container: 2dcf5f8aa833d23215971f8cd16958553ec13aaf8b30c57a9374cf72f9e7694b
error	22-Oct-2018 13:27:10	Oct 22, 2018 1:27:10 PM cloud.localstack.docker.LocalstackDocker startup
error	22-Oct-2018 13:27:10	INFO: Waiting for localstack container to be ready...
build	22-Oct-2018 13:27:20	AVCInitiationServiceLocalStackTest 1
error	22-Oct-2018 13:27:23	Oct 22, 2018 1:27:23 PM cloud.localstack.Localstack ensureInstallation
error	22-Oct-2018 13:27:23	INFO: Installing LocalStack to temporary directory (this may take a while): /tmp/AVC-AVCINITIATION-JOB1/localstack_install_dir
error	22-Oct-2018 13:29:00	Oct 22, 2018 1:29:00 PM cloud.localstack.docker.Container stop
error	22-Oct-2018 13:29:00	INFO: Stopped container: 2dcf5f8aa833d23215971f8cd16958553ec13aaf8b30c57a9374cf72f9e7694b
build	22-Oct-2018 13:29:00	Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 252.516 sec <<< FAILURE! - in com.telstra.accessdm.avc.test.AVCInitiationServiceLocalStackTest
build	22-Oct-2018 13:29:00	com.telstra.accessdm.avc.test.AVCInitiationServiceLocalStackTest  Time elapsed: 250.387 sec  <<< ERROR!
build	22-Oct-2018 13:29:00	java.lang.RuntimeException: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/tmp/AVC-AVCINITIATION-JOB1/localstack_install_dir"; make install', return code 2.
build	22-Oct-2018 13:29:00	STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
build	22-Oct-2018 13:29:00		(test -e .venv || virtualenv  .venv) && \
build	22-Oct-2018 13:29:00		(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
build	22-Oct-2018 13:29:00		. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
build	22-Oct-2018 13:29:00	New python executable in /tmp/AVC-AVCINITIATION-JOB1/localstack_install_dir/.venv/bin/python2
build	22-Oct-2018 13:29:00	Also creating executable in /tmp/AVC-AVCINITIATION-JOB1/localstack_install_dir/.venv/bin/python
build	22-Oct-2018 13:29:00	Installing setuptools, pip, wheel...done.
build	22-Oct-2018 13:29:00	
build	22-Oct-2018 13:29:00	STDERR:   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7a321e390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/airspeed/
build	22-Oct-2018 13:29:00	  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7a321ec50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/airspeed/
build	22-Oct-2018 13:29:00	  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7a321e990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/airspeed/
build	22-Oct-2018 13:29:00	  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7a321ed90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/airspeed/
build	22-Oct-2018 13:29:00	  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb7a321eed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/airspeed/
build	22-Oct-2018 13:29:00	  Could not find a version that satisfies the requirement airspeed==0.5.5.dev20160812 (from -r requirements.txt (line 4)) (from versions: )
build	22-Oct-2018 13:29:00	No matching distribution found for airspeed==0.5.5.dev20160812 (from -r requirements.txt (line 4))
build	22-Oct-2018 13:29:00	Traceback (most recent call last):
build	22-Oct-2018 13:29:00	  File "localstack/services/install.py", line 9, in <module>
build	22-Oct-2018 13:29:00	    from localstack.constants import (DEFAULT_SERVICE_PORTS, ELASTICMQ_JAR_URL, STS_JAR_URL,
build	22-Oct-2018 13:29:00	  File "/tmp/AVC-AVCINITIATION-JOB1/localstack_install_dir/localstack/constants.py", line 2, in <module>
build	22-Oct-2018 13:29:00	    import localstack_client.config
build	22-Oct-2018 13:29:00	ImportError: No module named localstack_client.config
build	22-Oct-2018 13:29:00	make: *** [install] Error 1
build	22-Oct-2018 13:29:00	
build	22-Oct-2018 13:29:00		at cloud.localstack.Localstack.exec(Localstack.java:233)
build	22-Oct-2018 13:29:00		at cloud.localstack.Localstack.exec(Localstack.java:215)
build	22-Oct-2018 13:29:00		at cloud.localstack.Localstack.ensureInstallation(Localstack.java:155)
build	22-Oct-2018 13:29:00		at cloud.localstack.Localstack.ensureInstallationAndGetEndpoint(Localstack.java:187)
build	22-Oct-2018 13:29:00		at cloud.localstack.Localstack.getEndpointSQS(Localstack.java:106)
build	22-Oct-2018 13:29:00		at cloud.localstack.TestUtils.getEndpointConfigurationSQS(TestUtils.java:87)
build	22-Oct-2018 13:29:00		at cloud.localstack.TestUtils.getClientSQS(TestUtils.java:44)
build	22-Oct-2018 13:29:00		at com.telstra.accessdm.avc.test.AVCInitiationServiceLocalStackTest.setup(AVCInitiationServiceLocalStackTest.java:65)
build	22-Oct-2018 13:29:00	
build	22-Oct-2018 13:29:00	
build	22-Oct-2018 13:29:00	Results :`

</pre>
So could you please suggest how to provide proxy ? please let me know if you need any other information about our configuration.

**Comment by raz-viber** [comment] 2019-05-13 13:04
same here


java.lang.RuntimeException: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/var/folders/dg/mjhfvfxs7c7547n6tbmb3k7w0000gp/T//localstack_install_dir"; make install', return code 2.
STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
		(test -e .venv || virtualenv  .venv) && \
		(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
		. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Requirement already satisfied: virtualenv in /Users/raz/Library/Python/2.7/lib/python/site-packages (16.5.0)

STDERR: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
/bin/sh: virtualenv: command not found
make: *** [install] Error 127


	at cloud.localstack.Localstack.exec(Localstack.java:346)
	at cloud.localstack.Localstack.exec(Localstack.java:314)
	at cloud.localstack.Localstack.ensureInstallation(Localstack.java:247)
	at cloud.localstack.Localstack.setupInfrastructure(Localstack.java:353)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:24)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/var/folders/dg/mjhfvfxs7c7547n6tbmb3k7w0000gp/T//localstack_install_dir"; make install', return code 2.
STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
		(test -e .venv || virtualenv  .venv) && \
		(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
		. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Requirement already satisfied: virtualenv in /Users/raz/Library/Python/2.7/lib/python/site-packages (16.5.0)

STDERR: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
/bin/sh: virtualenv: command not found
make: *** [install] Error 127

	at cloud.localstack.Localstack.exec(Localstack.java:332)
	... 17 more

**Comment by whummer** [comment] 2019-11-26 22:31
Thanks for reporting @raz-viber @atanupanda .

From the logs:
```
STDERR: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
/bin/sh: virtualenv: command not found
```

Please make sure that your system is upgraded to Python 3, and that `virtualenv` is installed and accessible in your `PATH`. Closing this issue - please report here or create follow-up items if there are any other issues. Thanks

**Closed by whummer** 2019-11-26 22:31 UTC
