### ISSUE TITLE
Error when deployment cloud formation stack

### ISSUE THREAD

**Issue by hongyunlim** [localstack/localstack#1787] opened 2019-11-22 08:55 UTC
Hi, I got this error when i trying to deploy a cloud formation to localstack.
2019-11-22T08:33:40: WARNING:moto: No Moto CloudFormation support for AWS::CloudFormation::Stack

What's the cause of this, and how can i solve this?

Thank in advance..

**Comment by whummer** [comment] 2020-01-18 15:55
Thanks for reporting @hongyunlim . This looks like a duplicate of #1566 - should be fixed in #1921 . Please report here if the problem persists with the latest version of the Docker image. Thanks

**Closed by whummer** 2020-01-18 15:55 UTC
