### ISSUE TITLE
bug: Create SQS queue fails on latest build

### ISSUE THREAD

**Issue by jackterm** [localstack/localstack#4466] opened 2021-08-18 21:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On code that has always worked previously, on the latest docker build, when creating a SQS queue, I receive this error message:

```
Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

I just tested on `localstack/localstack:0.12.15`, and it works normally.

For reference, this is the API call I'm making:
```
AWS_REGION="${TEST_AWS_REGION}" \
AWS_ACCESS_KEY_ID="${TEST_AWS_ACCESS_KEY_ID}" \
AWS_SECRET_ACCESS_KEY="${TEST_AWS_SECRET_ACCESS_KEY}" aws --endpoint="${TEST_AWS_ENDPOINT}" \
sqs create-queue --queue-name="$1"
```

Nothing about the test setup or code has changed... the only change is the docker image

### Expected Behavior

It should create the SQS queue without error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

From docker-compose.yml:
```
localstack:
    image: localstack/localstack:0.12.15
    ports:
      - "4566:4566"
    networks:
      - db
    environment:
      - HOSTNAME=localhost
      - EDGE_PORT=4566 # main entry point for all mock services
      - SERVICES=sqs,s3 # comma-separated list of services
      - DEBUG=1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
AWS_REGION="${TEST_AWS_REGION}" \
AWS_ACCESS_KEY_ID="${TEST_AWS_ACCESS_KEY_ID}" \
AWS_SECRET_ACCESS_KEY="${TEST_AWS_SECRET_ACCESS_KEY}" aws --endpoint="${TEST_AWS_ENDPOINT}" \
sqs create-queue --queue-name="$1"
```

### Environment

```markdown
- OS: Mac OS
- LocalStack: versions explained in bug report
```

**Comment by mgagliardo** [comment] 2021-08-18 21:51
Hello @jackterm, is it possible there's a typo on your command? The right one should be `--endpoint-url` instead of `--endpoint`.

docker-compose.yml:
```
localstack:
    image: localstack/localstack:0.12.15
    ports:
      - "4566:4566"
    environment:
      - EDGE_PORT=4566
      - SERVICES=sqs,s3
      - DEBUG=1
```

output:
```
$ AWS_REGION=us-east-1 \
> AWS_ACCESS_KEY_ID=test \
> AWS_SECRET_ACCESS_KEY=test \
> aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}

$ AWS_REGION=us-east-1 AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/test"
    ]
}
```

**Comment by jackterm** [comment] 2021-08-18 21:52
If so, that means it changed out from under us... as mentioned this has been working for ~6 mo, and it continues to work with this image `localstack/localstack:0.12.15`

**Comment by mgagliardo** [comment] 2021-08-18 21:53
> If so, that means it changed out from under us... as mentioned this has been working for ~6 mo, and it continues to work with this image `localstack/localstack:0.12.15`

I could not tell that, the AWS CLI is not managed by us. But I have always used `--endpoint-url`.

**Comment by jackterm** [comment] 2021-08-18 21:55
It seems to be a change in the localstack docker image... if you test the one I reference (`0.12.15`) it works, and the `latest` fails... that cannot be attributable to AWS

**Comment by jackterm** [comment] 2021-08-18 21:56
`0.12.15` is from July, so the change must have been recent... `0.12.16` is the breaking image

**Comment by mgagliardo** [comment] 2021-08-18 22:25
Tried with `latest` and `0.12.16` and still could not reproduce this issue.

**Comment by mgagliardo** [comment] 2021-08-18 22:38
I have tested this on both mac and linux (ubuntu) now, images `0.12.15`, `0.12.16` and `latest` as well, tried with all commands below and all of them worked as expected:

```
$ AWS_REGION=us-east-1 AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}
(base) ✔ ~
00:36 $ AWS_REGION=us-east-1 AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws --endpoint=http://localhost:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}
```

I'm closing this as could not reproduce the issue.

**Closed by mgagliardo** 2021-08-18 22:38 UTC
Labels: bug, needs-triaging

**Comment by whummer** [comment] 2021-08-19 00:37
Thanks for digging into this @jackterm @mgagliardo . Out of curiosity - can you please share the logs of your LocalStack container (with `DEBUG=1` enabled) - since you're getting a 500 internal error message, I'd assume that we should be able to see an error message in the server process. 

Also, please make sure to run the `aws` command with the `--debug` flag enabled, and please share the detailed log output here as well. Thanks!

**Comment by jackterm** [comment] 2021-08-19 01:39
@whummer - here is the log output:

(I just ran it several times locally, and it only failed intermittently, which is weird)
```
2021-08-19 01:37:30,936:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 181, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 250, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 282, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/sqs/responses.py", line 78, in call_action
    status_code, headers, body = super(SQSResponse, self).call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/sqs/responses.py", line 101, in create_queue
    queue = self.sqs_backend.create_queue(queue_name, tags, **self.attribute)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/sqs/responses.py", line 36, in sqs_backend
    return sqs_backends[self.region]
KeyError: 'local-test'
```

**Comment by jackterm** [comment] 2021-08-19 01:43
We're setting local nonsense env vars, and we set `AWS_REGION="local-test"`

It looks like this code is calling `moto` and the fake region name is not being found in this dict:
https://github.com/spulec/moto/blob/master/moto/sqs/models.py#L1047

So maybe the `moto` code was updated as part of this latest release?

**Comment by jackterm** [comment] 2021-08-19 01:45
It looks like `moto` is calling `Boto3` under the hood, which leads me here:
https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3/session.html#Session.get_available_regions

So this code must have changed, thereby no longer allowing fake region names?

**Comment by jackterm** [comment] 2021-08-23 15:40
@whummer - this looks like a bug to me. I think @mgagliardo was a little quick to close the issue.

**Comment by mgagliardo** [comment] 2021-08-23 17:39
I could not tell if I was a little quick to close the issue as I did not see you were using `local-test` values, I think I showed you all my outputs and you did not tell me until recently what the issue was.
Anyways, it would be great to know the usecase for this as the AWS CLI will fail as well if you use a fake endpoint.

**Comment by spendo-atl** [comment] 2021-09-20 23:48
@mgagliardo we're still experiencing the problem with latest release and as mentioned above we were using the region name `us-east-1`. We're unfortunately stuck on `0.12.15`. Can you consider re-opening this issue?

**Comment by spendo-atl** [comment] 2021-09-21 01:44
@mgagliardo my apologies 🤦 it was also due to configuration in our case where region had a typo in one instance: `us-east1` fixing this solved the issue for us. Although would be awesome if we could clarify through a different error message if possible
