### ISSUE TITLE
bug: In 1.1.0, the S3 GetObject returns boolean with uppercase first character in header x-amz-server-side-encryption-bucket-key-enabled 

### ISSUE THREAD

**Issue by alfreddatakillen** [localstack/localstack#6840] opened 2022-09-08 14:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When doing a S3 GetObject, the x-amz-server-side-encryption-bucket-key-enabled header in the response is `False`.

### Expected Behavior

The AWS SDK v3 for Nodejs expects the string to be `false` with all lower case letters. Otherwise, it throws an exception.

### How are you starting LocalStack?

With a docker-compose file

#### Start localstack

    docker-compose up
    
with docker compose file:

```
version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.1.0
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - HOST_TMP_FOLDER="/tmp/localstack"
```

#### Code snippet using AWS SDK for Nodejs

```
const { S3Client, GetObjectCommand } = require("@aws-sdk/client-s3");
const s3 = new S3Client({ endpoint: "http://127.0.0.1:4566/", region: "eu-west-1", forcePathStyle: true });
const command = new GetObjectCommand({
  Bucket: "testbucket",
  Key: "data.json",
});
s3.send(command);
```

I'm using the latest `@aws-sdk/client-s3` package from npmjs, i.e. version 3.165.0.

The AWS SDK v3 for Nodejs throws an exception with this error:

```
/home/user/dev/testproj/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:11
            throw new Error(`Unable to parse boolean value "${value}"`);
                  ^

Error: Unable to parse boolean value "False"
    at parseBoolean (/home/user/dev/testproj/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:11:19)
    at map.BucketKeyEnabled (/home/user/dev/testproj/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4307:52)
    at map (/home/user/dev/testproj/node_modules/@aws-sdk/smithy-client/dist-cjs/object-mapping.js:37:31)
    at deserializeAws_restXmlGetObjectCommand (/home/user/dev/testproj/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4263:22)
    at deserialize (/home/user/dev/testproj/node_modules/@aws-sdk/client-s3/dist-cjs/commands/GetObjectCommand.js:44:73)
    at /home/user/dev/testproj/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/user/dev/testproj/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/home/user/dev/testproj/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /home/user/dev/testproj/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 1.1.0 (latest)
```

### Code in AWS SDK v3 that throws the error

The AWS SDK v3 for Nodejs only allows lower case string representing booleans, in `node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js`:

```
const parseBoolean = (value) => {
    switch (value) {
        case "true":
            return true;
        case "false":
            return false;
        default:
            throw new Error(`Unable to parse boolean value "${value}"`);
    }
};
```

### Similar issues

There are other issues regarding similar problems with upper/lower case booleans, like #6495, #4890, #4887, #3064, but those seem to be about other localstack/aws services.

**Comment by ChandanChainani** [comment] 2022-09-22 12:37
Can i work on the issue?

**Comment by ChandanChainani** [comment] 2022-09-24 05:48
Is anyone working on the issue if not can I work on the issue?

**Comment by bentsku** [comment] 2022-12-14 17:20
Hello @alfreddatakillen and thanks for your report. 

We have been working on a new implementation of S3, and it is now available under a feature flag. Could you try starting LocalStack with `PROVIDER_OVERRIDE_S3=asf` (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)) and see if that would fix your problem? I've tested locally and it seems solved.

```bash
$ curl -v http://localhost:4566/mybucket/testkey
*   Trying 127.0.0.1:4566...
* Connected to localhost (127.0.0.1) port 4566 (#0)
> GET /mybucket/testkey HTTP/1.1
> Host: localhost:4566
> User-Agent: curl/7.84.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< Content-Type: binary/octet-stream
< accept-ranges: bytes
< Last-Modified: Wed, 14 Dec 2022 17:17:29 GMT
< Content-Length: 6
< ETag: "8feb211fef744a43469cf07400094c70"
< x-amz-server-side-encryption: aws:kms
< x-amz-server-side-encryption-aws-kms-key-id: test
< x-amz-server-side-encryption-bucket-key-enabled: true
< x-amz-request-id: P8HC67P0Q74UPXTLW51KI3KUE0DXMP9E1J1T3NP03GUCTC0HP9C5
< x-amz-id-2: MzRISOwyjmnupP8HC67P0Q74UPXTLW51KI3KUE0DXMP9E1J1T3NP03GUCTC0HP9C57/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
< Connection: close
< date: Wed, 14 Dec 2022 17:18:33 GMT
< server: hypercorn-h11
< 
test

```

In the case it's not, don't hesitate to provide us any logs where the exception can be seen. Thanks a lot for your feedback! 

Note: if you are a Pro user, you should use the flag value `asf_pro` instead of `asf`.

**Comment by bentsku** [comment] 2022-12-30 14:47
Hi again! As it's been 2 weeks and the issue is not reproducible anymore with the solution above, I'll close the issue.
If you still encounter the issue, don't hesitate to comment again and I'll reopen. 

Thanks again for your report!

**Closed by bentsku** 2022-12-30 14:47 UTC
Labels: type: bug, status: response required, aws:s3
