### ISSUE TITLE
Keep-alive header mandatory on API Gateway to hold connection

### ISSUE THREAD

**Issue by wem** [localstack/localstack#1570] opened 2019-09-17 18:03 UTC
Localstack image version: 0.10.2

As Http 1.1 the connection: keep-alive header should be optional, but the API gateway closes the connection without an explicit declaration of this header.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-119) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-01-03 17:25
Thanks for reporting @wem . My understanding that the LocalStack behavior (requires the keep-alive header) diverges from AWS (does not require the header).

Can you please provide some more details (or a small example) where this leads to problems? Shouldn't be hard to change this behavior, but would be good to understand the impact. Thanks!

**Comment by whummer** [comment] 2021-02-23 17:46
Closing this issue as "cannot reproduce" - there have been various changes in our API/networking setup (with the new `edge` service acting as the central entry point). Please report here if the problem persists. Thanks!

**Closed by whummer** 2021-02-23 17:46 UTC
Labels: diverges-from-aws, needs-triaging
