### ISSUE TITLE
bug: [SNS] wrong keys on message attributes passed to SQS

### ISSUE THREAD

**Issue by decima** [localstack/localstack#8441] opened 2023-06-05 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When passed to SQS, keys of the messages attributes on SNS are renamed from StringValue to Value and DataType to Type.

### Expected Behavior

The keys should not be renamed

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Flow
 - Create a SQS Queue
 - Create a SNS Topic
 - Configure a Subscription of the new Topic that sends to the SQS queue (specify a raw delivery at true)
 - Publish a message to SNS Topic with attribute { DataType: "string", StringValue: "anything"}
 - Attributes are no more StringValue but just value. 

(can't provide more, I have issues with my awslocal, I got this issue with the PHP client initially)

### Environment

```markdown
- OS: Docker Desktop for mac
- LocalStack: 1.4
```

### Anything else?

The AWS SNS official documentation : https://docs.aws.amazon.com/sns/latest/api/API_MessageAttributeValue.html

MR for fix is coming

**Comment by bentsku** [comment] 2023-06-05 16:08
Thanks for the issue raised, I've answered in your PR: https://github.com/localstack/localstack/pull/8442#issuecomment-1577081915

I'm not sure this is really an issue without a reproducer that can run against AWS to show the difference between LocalStack and AWS. Thanks!

**Comment by decima** [comment] 2023-06-07 07:42
Thanks for your reply. With my team, we spotted what's going on (but could not test it on localstack 2.x), you were right, my fix is not fixing the problem.
The problem seems to come from attaching the RawMessageDelivery Attribute on subscription creation.

```
# awslocal sns list-topics
{
    "Topics": [
        {
            "TopicArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint"
        }
    ]
}

```

Then we try to create a subscription with RawMessageDelivery set to "true" : 

```
# Raw Message Delivery enabled within subscription creation like :
subscription = client.subscribe(
          TopicArn=topic_arn,
          Protocol=protocol,
          Endpoint=endpoint,
          Attributes={
              "RawMessageDelivery": "true",
          },
          ReturnSubscriptionArn=True
      )
```
When we retrieve the subscription we can see the RawMessageDelivery is not set. 
```
# awslocal sns list-subscriptions-by-topic --topic-arn arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint:19a7d05c-2bce-46e8-a5da-5471e8560464",
            "Owner": "000000000000",
            "Protocol": "sqs",
            "Endpoint": "arn:aws:sqs:eu-west-3:000000000000/sqs_dev_fr",
            "TopicArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint"
        }
    ]
}

# awslocal sns get-subscription-attributes --subscription-arn arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint:19a7d05c-2bce-46e8-a5da-5471e8560464
{
    "Attributes": {
        "TopicArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint",
        "Endpoint": "arn:aws:sqs:eu-west-3:000000000000/sqs_dev_fr",
        "Protocol": "sqs",
        "SubscriptionArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint:19a7d05c-2bce-46e8-a5da-5471e8560464",
        "PendingConfirmation": "false"
    }
}
```

We have to manually set the subscription-attribute afterward to make it available : 

```
# Set attribute RawMessageDelivery after subscription :
client.set_subscription_attributes(
            SubscriptionArn=subscription["SubscriptionArn"],
            AttributeName="RawMessageDelivery",
            AttributeValue="true"
        )

# awslocal sns set-subscription-attributes --subscription-arn arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint:19a7d05c-2bce-46e8-a5da-5471e8560464 --attribute-name RawMessageDelivery --attribute-value true

# awslocal sns get-subscription-attributes --subscription-arn arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint:19a7d05c-2bce-46e8-a5da-5471e8560464
{
    "Attributes": {
        "TopicArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint",
        "Endpoint": "arn:aws:sqs:eu-west-3:000000000000/sqs_dev_fr",
        "Protocol": "sqs",
        "SubscriptionArn": "arn:aws:sns:eu-west-3:000000000000:dev_StartingPoint:19a7d05c-2bce-46e8-a5da-5471e8560464",
        "PendingConfirmation": "false",
        "RawMessageDelivery": "true"
    }
}
```

we tried the same script on aws and don't need to set-subscription-attributes to make it work. I'm closing my fix, let me know if the problem is the same on 2.x

**Comment by bentsku** [comment] 2023-06-07 16:29
Interesting, thanks for the feedback! I just gave it a try with `latest`, and it doesn't seem I can reproduce the issue. I'm however opening a PR adding tests to validate this behaviour, so what we would catch any regression in this sense. Thanks a lot for raising this issue!

**Comment by bentsku** [comment] 2023-06-16 11:35
Hi @decima! As the issue is now covered with an integration test and seems to be fixed in the latest version, I'll close the issue. Feel free to reopen if there's still anything linked to that. Thanks again for the report!

**Closed by bentsku** 2023-06-16 11:35 UTC
Labels: type: bug, aws:sns
