### ISSUE TITLE
SNS hangs under load, shows error: urllib3.connectionpool: Connection pool is full, discarding connection

### ISSUE THREAD

**Issue by stevepryde** [localstack/localstack#2665] opened 2020-07-03 07:24 UTC
Localstack version: 0.11.3 (I have not tested earlier versions yet)

SNS seems to hang when I publish to a topic concurrently using multiple threads (> 30 threads for python, > 15 threads for rust).

We were seeing issues with SNS/SQS under load in our application, so I've written a small python test that demonstrates the issue. The test reproduces the issue almost immediately every time.

I have attached the python code used to test it. I also have a rust version that can reproduce the issue with less threads (exactly half, which is potentially interesting) - let me know if you are interested in that. The python one works fine with 29 publish threads but fails almost immediately with 30. That seems strange to me. Hopefully it's not my code doing something weird. The fact that once in that state I cannot even create a topic afterwards (that also hangs) tells me that SNS is stuck.

## Expected behavior
There are two parts to this (I only care about the second one for this ticket):

1. It should not hang once it reaches capacity (but I'm not sure what it should do - return errors? wait with timeout?)
1. The actual capacity / throughput should surely be much higher ? (I'm seeing this issue with slightly over 15-20 messages per second)

## Actual behavior
Attempting to publish to SNS using 30+ threads (python) or 15+ threads (rust) causes SNS to hang, and after that no requests will go through. Cannot even create a new topic once it is in that state. Have to restart localstack.

The `Connection pool is full, discarding connection` message shows up in the logs even at lower load (less threads). But the hang only happens at 30 threads, and it happens almost as soon as the publish threads start.

# Steps to reproduce
## Command used to start LocalStack
```
DEBUG=1 SERVICES=sqs,sns docker-compose up
```

## Client code
```
pip install localstack-client 
```

Test code:

```
#!/usr/bin/env python3

import json
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import localstack_client.session


AWS_ACCESS_KEY = "dummyaccess"
AWS_SECRET_KEY = "dummysecret"
REGION_NAME = "us-east-1"
ENDPOINT_URL = "http://localhost:4566"
TEST_BUCKET = "test-bucket"
TOPIC_NAME = "mytopic"
QUEUE_NAME = "myqueue"
MSG_PER_THREAD = 100
SEND_THREADS = 30
RECV_THREADS = 1


def sqs_receive(q_url):
    response = sqs.receive_message(
        QueueUrl=q_url,
        AttributeNames=["All"],
        MaxNumberOfMessages=1,
        MessageAttributeNames=["All"],
        VisibilityTimeout=0,
        WaitTimeSeconds=0,
    )
    recv_list = []
    try:
        for message in response["Messages"]:
            receipt_handle = message["ReceiptHandle"]
            sqs_message = json.loads(message["Body"])["Message"]
            recv_list.append((sqs_message, receipt_handle))
    except KeyError:
        pass
    return recv_list


def sqs_delete(q_url, receipt_handle):
    """Delete received message from sqs."""
    sqs.delete_message(QueueUrl=q_url, ReceiptHandle=receipt_handle)


def sqs_publish(q_url, msg):
    sqs.send_message(QueueUrl=q_url, MessageBody=msg)


def sns_publish(topic_arn, msg):
    sns.publish(TargetArn=topic_arn, Message=msg)


def sns_send_thread(topic_arn, id, send_count):
    sent = []
    for count in range(send_count):
        msg = f"{id}_{count}"
        sns_publish(topic_arn, msg)
        sent.append(msg)
        print(f"Sent {msg}")
    return sent


def sqs_recv_thread(q_url):
    recv_count = 0
    received = []
    timeout = 10
    while True:
        recv_list = sqs_receive(q_url)
        if not recv_list:
            timeout -= 1
            if timeout <= 0:
                return received
            time.sleep(1)
            continue

        for sqs_message, receipt_handle in recv_list:
            received.append(sqs_message)
            recv_count += 1
            print(f"Recv {sqs_message}")
            try:
                sqs_delete(q_url, receipt_handle)
            except Exception:
                # If using multiple threads, they can race and then attempt
                # to delete the same message twice, which will fail.
                pass
            print(f"Del {sqs_message}")


def run_test():

    print("Create topic")
    topic = sns.create_topic(Name=TOPIC_NAME)
    topic_arn = topic["TopicArn"]
    print(f"Topic = {topic_arn}")

    print("Create queue")
    queue_url = sqs.create_queue(QueueName=QUEUE_NAME,)["QueueUrl"]
    print(f"Queue = {queue_url}")
    r = sqs.get_queue_attributes(QueueUrl=queue_url, AttributeNames=["QueueArn"])
    queue_arn = r["Attributes"]["QueueArn"]
    print(f"ARN = {queue_arn}")

    time.sleep(2)
    # queue_url = queue_url.replace("aws-local_sns-sqs", "localhost")

    print("Subscribe to SNS topic")

    response = sns.subscribe(TopicArn=topic_arn, Protocol="sqs", Endpoint=queue_arn)
    sub_arn = response["SubscriptionArn"]
    print(f"Subscription ARN = {sub_arn}")

    print("Start thread pool")
    with ThreadPoolExecutor(max_workers=SEND_THREADS + RECV_THREADS) as executor:
        start_send = time.monotonic()
        futures_recv = []
        for i in range(RECV_THREADS):
            future = executor.submit(sqs_recv_thread, queue_url)
            futures_recv.append(future)

        start_recv = time.monotonic()
        futures_send = []
        for i in range(SEND_THREADS):
            future = executor.submit(sns_send_thread, topic_arn, i, MSG_PER_THREAD)
            futures_send.append(future)

        sent_messages = []
        for future in as_completed(futures_send, timeout=600):
            r = future.result()
            sent_messages.extend(r)

        duration_send = time.monotonic() - start_send
        sent_per_sec = len(sent_messages) / duration_send

        recv_messages = []
        for future in as_completed(futures_recv, timeout=600):
            r = future.result()
            recv_messages.extend(r)

        duration_recv = time.monotonic() - start_recv
        recv_per_sec = len(recv_messages) / duration_recv

        print(f"Sent {sent_per_sec:.3f} messages per second")
        print(f"Recv {recv_per_sec:.3f} messages per second")

        # Verify that all sent messages were received.
        for msg in sent_messages:
            assert msg in recv_messages, f"Message '{msg}' not found in recv_messages"

            # If using multiple recv threads there can be double-ups.
            while msg in recv_messages:
                recv_messages.remove(msg)

        assert not recv_messages, f"Messages were received but not sent??\n{recv_messages}"

        print("Test successful.")


if __name__ == "__main__":
    try:
        print("Connecting")
        session = localstack_client.session.Session()
        sqs = session.client(
            "sqs",
            aws_access_key_id=AWS_ACCESS_KEY,
            aws_secret_access_key=AWS_SECRET_KEY,
            region_name=REGION_NAME,
        )

        sns = session.client(
            "sns",
            aws_access_key_id=AWS_ACCESS_KEY,
            aws_secret_access_key=AWS_SECRET_KEY,
            region_name=REGION_NAME,
            endpoint_url=ENDPOINT_URL,
        )

        run_test()
    except KeyboardInterrupt:
        print("Cancelled.")
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-207) by [Unito](https://www.unito.io/learn-more)

**Comment by stevepryde** [comment] 2020-07-03 07:35
I also tried the same test with just SQS (sending messages directly to the queue rather than to the SNS topic) and that seemed to work fine without hanging. Similar performance IIRC

**Comment by stevepryde** [comment] 2020-07-03 07:56
Tested on 0.11.2 as well - still hangs but does publish more messages before the hang

**Comment by AdallomRoy** [comment] 2020-08-31 21:04
Experiencing this as well, all the time. Any idea if there is any workaround for this?

**Comment by macnev2013** [comment] 2020-10-28 19:21
Thanks for reporting @stevepryde @AdallomRoy . We have added significant improvements in the latest version.
Can you please give it a try with `latest `version of localstack using `docker pull localstack/localstack`?
Thanks.

**Comment by whummer** [comment] 2020-12-06 11:01
Thanks @stevepryde @AdallomRoy @macnev2013 - looks like this issue is already fixed in the `latest` version (the script runs to completion and outputs `Test successful.`). Please let us know if the issue is still consistently reproducible on your end. Thanks!

**Closed by whummer** 2020-12-06 11:01 UTC
Labels: performance, should-be-fixed
