### ISSUE TITLE
package lambdas using aws cloudformation package

### ISSUE THREAD

**Issue by mihirshirali** [localstack/localstack#3170] opened 2020-10-26 06:25 UTC
# Type of request: This is a ...
[ ] bug report

# Detailed description
Running into an error, when running aws cloudformation package command
```
root@sj-vm20-18:~/certificate_attributes# aws cloudformation package --template ${TEMPLATE_FILE} --s3-bucket ${S3_BUCKET_NAME} --region ${REGION} --output-template-file ${TEMPLATE_OUT_FILE} --endpoint-url=http://localhost:4566

Unable to upload artifact /root/certificate_attributes/output/lambda_certificates_authorization_manager.zip referenced by CodeUri parameter of CertificateAuthFunction resource.
Connect timeout on endpoint URL: "https://us-east-1-certificates-installable.s3.us-east-1.amazonaws.com/06c0ac6e2da4546bea39f22dd26f1492"
```
It looks like there is an issue accessing S3. Is this a known issue?

S3 bucket does exist:
```
root@sj-vm20-18:~/certificate_attributes# aws s3api list-buckets --endpoint-url=http://localhost:4566 
{
    "Buckets": [
        {
            "Name": "us-east-1-certificates-installable",
            "CreationDate": "2020-10-25T18:41:59.156959+00:00"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```
...

## Expected behavior
lambdas should uploaded into s3

## Actual behavior
Error, when uploading since S3 is not accessible
...

# Steps to reproduce
## Command used to start LocalStack
```
localstack start
...
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
S3_BUCKET_NAME="us-east-1-certificates-installable" 
ACCOUNT=000000000000
REGION="us-east-1"
TEMPLATE_FILE="cloudformation/certificates_v2.yaml"
TEMPLATE_OUT_FILE=${TEMPLATE_OUT_FILE:-certificates-pkg.yml}

aws s3 mb s3://${S3_BUCKET_NAME} --region ${REGION} --endpoint-url=http://localhost:4566

aws cloudformation validate-template --template-body file://${TEMPLATE_FILE} --region ${REGION} --endpoint-url=http://localhost:4566

aws cloudformation package --template ${TEMPLATE_FILE} --s3-bucket ${S3_BUCKET_NAME} --region ${REGION} --output-template-file ${TEMPLATE_OUT_FILE} --endpoint-url=http://localhost:4566
...
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-82) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-12-17 21:59
Thanks for reporting @mihirshirali . This should be fixed in the `awslocal` command in https://github.com/localstack/awscli-local/pull/29 - the root cause is that the `--s3-endpoint-url` parameter is missing in the `aws` commands above. 

Can you please install the latest version of `awslocal` and give it a try:
```
$ pip install --upgrade awslocal
$ awslocal cloudformation package ...
```

Hope that helps - please let us know if the problem persists. Thanks

**Closed by whummer** 2020-12-17 21:59 UTC
