### ISSUE TITLE
bug: S3Exception 403 null when using AWS SDK Java V2 with localstack

### ISSUE THREAD

**Issue by phatthinh123** [localstack/localstack#8956] opened 2023-08-22 11:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm facing a strange behavior with localstack together with S3ASyncClient using AWS crt client
`Received failed response: 403, Request ID: not available, Extended Request ID: not available
2023-08-22 12:51:22,223 DEBUG [     Thread-144] [          software.amazon.awssdk.request] Received failed response: 403, Request ID: not available, Extended Request ID: not available
2023-08-22 12:51:22,223 DEBUG [sdk-async-respo] [software.amazon.awssdk.core.retry.ClockS] Reported service date: Tue, 22 Aug 2023 10:51:22 GMT
2023-08-22 12:51:22,224 DEBUG [sdk-async-respo] [software.amazon.awssdk.core.retry.ClockS] Reported service date: Tue, 22 Aug 2023 10:51:22 GMT
2023-08-22 12:51:22,249 ERROR [ default task-2] Something is going on: java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 403, Request ID: null)

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

I'm running S3Container through testcontainer, which I have no issue on my centos 7
            s3Container = new LocalStackContainer(localstackImage)
                    .withNetwork(network).withNetworkAliases("s3")
                    .withExposedPorts(4566)
                    .withEnv("DEBUG", "1")
                    .withServices(S3);
            s3Container.start();
                        AwsBasicCredentials credentials = AwsBasicCredentials.create(s3Container.getAccessKey(), s3Container.getSecretKey());

         S3AsyncClient s3AsyncClient = S3AsyncClient.crtBuilder()
                    .credentialsProvider(StaticCredentialsProvider.create(credentials))
                    .region(Region.of(s3Container.getRegion()))
                    .endpointOverride(s3Container.getEndpoint())
                    .build();
### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 2.2.0
Inside docker-dind environment which is deployed by jenkins
```

### Anything else?

This issue only happened when using S3ASyncClient used AWS CRT HTTP client, if I use S3Client then no problem occurred

**Comment by bentsku** [comment] 2023-08-22 12:10
Hello @phatthinh123 and thanks for your report.

Could you give us a little bit more information concerning the operation failing? What are you trying to do when receiving this error? This Java trace log is not giving any informations. Could you share LocalStack logs when this happens? You can have more verbose logs by setting `LS_LOG=trace` when starting LocalStack. 

Maybe you need to set the `forcePathStyle` when configuring your client? Maybe the CRT client is not exactly configured the same way. 

We had another report regarding the CRT client, and it links to the documentation on how to configure it:
https://github.com/localstack/localstack/issues/8736#issuecomment-1651737821
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-crt.html

**Comment by phatthinh123** [comment] 2023-08-22 12:20
Hi @bentsku,
I create a new bucket and process to upload it by using AWS CRT client, then it's working OK on my centos 7, but for some reason inside a docker-dind environment that I used for testing pipelines, it's not working.
I didn't face this issue with S3Client, and there is no problem with the real AWS S3
I also have no more details from my side, it looks like localstack hasn't received any requests, also tried the settings you mentioned they also not working.
I just tried to use AwsCrtAsyncHttpClient but that didn't seem to work either
![image](https://github.com/localstack/localstack/assets/23252545/656d7ae3-e355-4bab-b744-f2f76fe05f89)

**Comment by phatthinh123** [comment] 2023-08-22 12:38
Hi @bentsku,
Sorry for the confusion, look like it works after changing to use the AwsCrtAsyncHttpClient, looks like a bug in software.amazon.awssdk:s3 libraries I guess

**Comment by bentsku** [comment] 2023-08-22 14:22
Hi @phatthinh123, okay interesting to see. Also, it is a bit weird because a 403 error would indicate some authorisation error, but with no other indication, which is weird. If you can reproduce with the old client and see if the request hits LocalStack, maybe we could have more informations, but maybe the request doesn't even go there?

**Comment by phatthinh123** [comment] 2023-08-22 15:10
Hi @bentsku, 
In this picture, there is no log introduced by LocalStack after the request failed, I wonder if there is some difference in authorization between crtBuilder and the standard libraries for AWS crt client
As far I as I see, there is no different (at least what visible in the TRACE log) 
This is from S3Client
`2023-08-22 09:19:59,479 DEBUG [ default task-2] [          software.amazon.awssdk.request] Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=172.17.0.1, port=49153, encodedPath=/lsv-bucket/00000000-0000-0000-1212-000000000001/test.pdf, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent], queryParameters=[])`
S3AsyncClient using crtBuilder
`2023-08-22 09:20:02,498 DEBUG [ default task-2] [          software.amazon.awssdk.request] Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=localhost, port=49153, encodedPath=/lsv-bucket/test2, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent], queryParameters=[])
`
![image](https://github.com/localstack/localstack/assets/23252545/6e919143-f957-467a-97db-4c9ea52116a0)

**Comment by phatthinh123** [comment] 2023-08-25 08:18
Hi @bentsku ,
Yes, it does look like to me the request not even hitting LocalStack when using CRT.
All of the S3Client and S3AsyncClient.crtBuidler and S3AsyncClient.builder they are used credentials from s3 container as well as the endpoint
`AwsBasicCredentials credentials = AwsBasicCredentials.create(s3Container.getAccessKey(), s3Container.getSecretKey());`
Only S3AsyncClient.crtBuidler facing this issue

**Comment by bentsku** [comment] 2023-09-08 02:18
I'll close the issue as it is more related to an SDK bug than LocalStack, as it does not even receive the request, but feel free to reopen if there's anything else for this. Thanks!

**Closed by bentsku** 2023-09-08 02:18 UTC
Labels: type: bug, aws:s3, area: integration/aws-sdk-java, status: in progress
