### ISSUE TITLE
An internal server on port 4560 becomes unresponsive and SQS stops working

### ISSUE THREAD

**Issue by sineqa** [localstack/localstack#2465] opened 2020-05-28 08:51 UTC
# bug report

# Detailed description

An internal server on port 4560 (not sure which server/service this is) randomly becomes unresponsive and when it does, SQS stops working. Once in this state it does not recover automatically and needs to be manually restarted.

## Expected behavior

1. SQS should remain stable and keep working
2. If this internal server becomes unresponsive, it should terminate the container to allow it to restart
3. There should be some kind of health check on this
4. What is running on port 4560? I can't find any documentation on this

## Actual behavior

The logs contain a lot of the following:
```
2020-05-28T08:07:35:ERROR:localstack.services.generic_proxy: Error forwarding request: MyHTTPConnectionPool(host='127.0.0.1', port=4560): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f00961377f0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f00961377f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='127.0.0.1', port=4560): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f00961377f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 287, in forward
    response = self.method(request_url, data=data_to_send,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
```

# Steps to reproduce

## Command used to start LocalStack

Started from docker container

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Still not sure if this is caused by load or just randomly happens on its own. It is not under very heavy load during my testing. Running on a core i7 laptop and not using a lot of CPU/mem.

I have a worker that pulls jobs from the queue and an app that pushes onto the queue. Runs on AWS just fine in a production setting. On my laptop it doesn't seem to handle much at all.
Just 10 events per second seems to be enough to bring it down. I want to be able to do several times that.

Queue created as follows:
```
awslocal sqs create-queue --queue-name worker-queue
awslocal sns create-topic --name worker-topic
awslocal sns subscribe --topic-arn arn:aws:sns:ap-southeast-2:000000000000:worker-topic --protocol sqs --notification-endpoint arn:aws:sqs:ap-southeast-2:000000000000:worker-queue
```

**Comment by sineqa** [comment] 2020-05-28 09:17
Actually this looks like a duplicate of #1653

**Comment by whummer** [comment] 2020-06-21 22:41
Thanks for reporting @sineqa . Indeed, this looks like a possible duplicate of #1653 . Also, a change has just been pushed in #2595 which significantly reworks the SQS implementation. Can you please do a `docker pull localstack/localstack` and let us know if the issue is reproducible with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!

**Closed by whummer** 2020-06-21 22:41 UTC

**Comment by sineqa** [comment] 2020-06-23 07:44
I'm not seeing the original errors but I am still seeing a lot of this:
```
WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: 8bda2c6cdb22
```

It seems once that happens it's game over. Everything stops sending/receiving
