### ISSUE TITLE
Error when an HTTP subscription to SNS is not valid anymore

### ISSUE THREAD

**Issue by ricardovf** [localstack/localstack#2125] opened 2020-03-04 21:48 UTC
Thanks for this great project.

I have this subscriptions to a topic:

```
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:lambda-test-dev-realtime-ws:e3d62eb0-ac7d-412b-87cf-02f7961df1b3",
            "Owner": "",
            "Protocol": "http",
            "Endpoint": "http://192.168.0.107:4003/lambda-test-chat-example-dev-snsChat",
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:lambda-test-dev-realtime-ws"
        },
        {
            "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:lambda-test-dev-realtime-ws:eb712c40-d7f5-4919-813f-0f05a2c74162",
            "Owner": "",
            "Protocol": "http",
            "Endpoint": "http://192.168.0.107:4002/lambda-test-dev-snsChat",
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:payface-lambda-pushpin-test-dev-realtime-ws"
        }
    ]
}
```

The first one (http://192.168.0.107:4003/lambda-test-chat-example-dev-snsChat) is not valid anymore cause the process is not listening on this ip/port. But the second one is. So when i publish an SNS message, localstack throws an error 502...

I think would be better to remove the subscription in this case, automaticlly, if possible... Or it could at least delivery the sns message to the other subscribers.

(im using with serverless-offline-sns)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-163) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-03-06 16:49
Thanks for reporting @ricardovf . Can you please provide a small, self-contained example that helps reproduce this issue? If you can post a minimal serverless.yml config, that would be great.

> (im using with serverless-offline-sns)

I'm not too familiar with this plugin, but out of curiosity - is there an advantage of using this plugin over native SNS in LocalStack?

Thanks

**Comment by ricardovf** [comment] 2020-03-07 22:50
> Thanks for reporting @ricardovf . 

Thanks for the quick reply.

> Can you please provide a small, self-contained example that helps reproduce this issue? If you can post a minimal serverless.yml config, that would be great.

Broker serverless.yaml
```
service: broker

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:AWS_REGION, 'us-east-1'}
  timeout: 30
  memorySize: 512
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  environment:
    SLS_OPTIMIZE_PREFIX: ${self:custom.prefix}
    AWS_SNS_ENDPOINT: ${self:custom.snsEndpointUrl.${self:provider.stage}}
    AWS_SNS_TOPIC_ARN: ${self:custom.snsTopicArn.${self:provider.stage}}
    AWS_SNS_REGION: ${self:provider.region}
    AWS_WEBSOCKET_API_ENDPOINT: ${self:custom.websocketsApiUrl.${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:${self:provider.region}:*:**/@connections/*'
    - Effect: Allow
      Action:
        - SNS:Publish
        - SNS:Subscribe
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:sns:${self:provider.region}:'
            - Ref: 'AWS::AccountId'
            - ':${self:custom.snsTopic}'

functions:
  websocket:
    handler: src/main.handlerWebsocketEvents
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  snsAuth:
    handler: src/main.handlerSnsAuthActions
    events:
      - sns:
        topicName: ${self:custom.snsTopic}
        filterPolicy:
          action:
            - auth_authorize
            - auth_reject
  sns:
    handler: src/main.handlerSnsActions
    events:
      - sns:
        topicName: ${self:custom.snsTopic}
        filterPolicy:
          action:
            - send_message
            - send_message_to_channel
            - join_channel
            - leave_channel
            - drop_connection

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-dynamodb-local
  - serverless-offline-sns
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

resources:
  Resources:
    SnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.snsTopic}

custom:
  serverless-offline-sns:
    host: 0.0.0.0 # Enable plugin to listen on every local address
    sns-subscribe-endpoint: ${env:DEV_LOCAL_IP} # Host ip address
    sns-endpoint: http://127.0.0.1:4575 # Default localstack sns endpoint
    debug: true
    region: ${self:provider.region}
  snsTopic: '${self:service}-${self:provider.stage}-realtime-ws'
  snsTopicArn:
    dev: 'arn:aws:sns:${self:provider.region}:000000000000:${self:custom.snsTopic}'
    production:
      Fn::Join:
        - ''
        - - 'arn:aws:sns:${self:provider.region}:'
          - Ref: 'AWS::AccountId'
          - ':${self:custom.snsTopic}'
  snsEndpointUrl:
    dev: 'http://127.0.0.1:4575'
  websocketsApiUrl:
    dev: 'http://127.0.0.1:3001'
    production:
      Fn::Join:
        - ''
        - - 'https://'
          - Ref: 'WebsocketsApi'
          - '.execute-api.'
          - ${self:provider.region}.
          - Ref: 'AWS::URLSuffix'
          - '/'
          - ${self:provider.stage}

```

> I'm not too familiar with this plugin, but out of curiosity - is there an advantage of using this plugin over native SNS in LocalStack?

Actually im using native SNS of LocalStack, but this plugin works with serverless-offline which allow me to quickly develop. I will also try the alternative (https://github.com/localstack/serverless-localstack)

**Comment by bentsku** [comment] 2022-08-05 09:54
Hello! Since this issue was created, substantial improvement has been made to the SNS service.
The issue with the subscription should now be resolved in the latest releases of Localstack. We handle http/https subscriptions not being available, and deliver the message to a Dead Letter Queue if one was configured.
Should this issue still be encountered, I encourage you to open a new issue with a reproducible example.

Thanks a lot again for your bug report!

**Closed by bentsku** 2022-08-05 09:54 UTC
Labels: status: triage needed, area: integration/serverless, aws:sns
