### ISSUE TITLE
Cannot invoke lambda function from SQS

### ISSUE THREAD

**Issue by pinboro** [localstack/localstack#967] opened 2018-10-18 05:42 UTC
## What I want to do

- Send a message to SQS
- Get Lambda to be invoked when SQS receives the message (using an EventSourceMapping).

Using a sample localstack structure available here: https://gitlab.com/jvasseur/webapp-with-localstack

## How I do

* Start Localstack

```
cd submodules/localstack
export TMPDIR=/private$TMPDIR
export SERVICES="lambda,sqs,dynamodb"
export LAMBDA_EXECUTOR=docker-reuse
export DEBUG=1
docker-compose up
```

* Create services

```
> aws --endpoint-url=http://localhost:4574 lambda create-function --cli-input-json file://serverless/lambda/my_lambda.json --zip-file fileb://tmp/lambda_function.my_lambda.zip

	arn:aws:lambda:us-east-1:000000000000:function:my_lambda	my_lambda	index.handler	128		nodejs8.10	3
SECURITYGROUPIDS	None
SUBNETIDS	None
```

```
> aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name my_sqs

http://localhost:4576/queue/my_sqs
```

```
> aws --endpoint-url=http://localhost:4574 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:us-east-1:queue:my_sqs --function-name my_lambda

100	arn:aws:sqs:us-east-1:queue:my_sqs	arn:aws:lambda:us-east-1:000000000000:function:my_lambda	1539840635.0	OK	Enabled	User action	5ee6d136-46ec-4056-aa73-086e9be1a3e0
```

* Call Lambda manually

```
> aws --endpoint-url http://localhost:4574 lambda invoke --function-name my_lambda outfile.txt
{
    "StatusCode": 200
}
```

* Send message to SQS

```
> aws --endpoint-url=http://localhost:4576 sqs send-message --queue-url "http://localhost:4576/queue/my_sqs" --message-body '{}'
{
    "MD5OfMessageBody": "99914b932bd37a50b983c5e7c90ae93b",
    "MD5OfMessageAttributes": "d41d8cd98f00b204e9800998ecf8427e",
    "MessageId": "67f356cc-92c9-4b97-9a28-9c8aeb93281b"
}
```

## Expecting

Lambda function to run after sending a message to SQS.

## Actual

Nothing happens after message is successfully sent (observing the logs with `docker-compose logs -f`).

**Comment by dknepprath** [comment] 2018-12-05 05:00
This is a much more thorough issue, but is essentially a dupe of https://github.com/localstack/localstack/issues/850

**Comment by jbaileyashe** [comment] 2019-03-12 18:45
Fixed by  #1144?

**Comment by whummer** [comment] 2019-03-17 22:36
Thanks for reporting @pinboro - this should be fixed by #1144 , as @jbaileyashe mentioned

**Comment by MathiasBojda** [comment] 2019-03-26 11:49
@whummer Have you confirmed that it works in practice? I cannot for the life of me get SQS to trigger a lambda function.

**Comment by MathiasBojda** [comment] 2019-03-26 12:37
@whummer I made this simple example here: https://github.com/MathiasBojda/sqs-localstack-lambda
Confirming that SQS does not trigger the event, or you can check if i am doing something wrong

**Comment by MathiasBojda** [comment] 2019-03-26 14:44
OK, it's solved. To anyone who might else be struggling with this.
For me the issue was the event-source-arn, specified in the create-event-source-mapping. 
You cannot rely on the event-source-arn you get from the dashboard /infra.
It's actually:
`arn:aws:sqs:elasticmq:000000000000:queue_name` 
not 
`arn:aws:sqs:us-east-1:queue:my_sqs`

You can get the true event-source-arn with 
`awslocal sqs get-queue-attributes --queue-url http://localhost:4576/queue/test_queue --attribute-name QueueArn`

or without awslocal

`aws sqs get-queue-attributes --queue-url http://localhost:4576/queue/test_queue --attribute-name QueueArn  --endpoint-url http://localhost:4576`

**Comment by cdowey-r7** [comment] 2019-05-29 08:21
That was super helpful @MathiasBojda, the dashboard shows the SQS -> Lambda relationship when the QueueUrl is wrong but when corrected per your comment the dashboard no longer shows the relationship. Ah well, at least it works now. Cheers!

**Comment by linux2647** [comment] 2019-11-30 22:57
For anyone arriving here at or after the time of this writing, the issue with the queue ARN needing to be `arn:aws:sqs:elasticmq:000000000000:queue_name` instead of `arn:aws:sqs:us-east-1:000000000000:queue_name` appears to have been fixed.  In other words, the region should not be `elasticmq` anymore, but should be a standard AWS region, like `us-east-1`.

**Comment by mayank-kapoor** [comment] 2020-02-03 04:25
@linux2647 @MathiasBojda its not working with  standard AWS region or even with arn:aws:sqs:elasticmq:000000000000 ?

**Comment by BR0kEN-** [comment] 2020-03-16 16:31
Neither https://github.com/localstack/localstack/issues/967#issuecomment-560027971 nor https://github.com/localstack/localstack/issues/967#issuecomment-476679444 works anymore.

```
export AWS_ACCESS_KEY_ID=irrelevant
export AWS_SECRET_ACCESS_KEY=irrelevant
export AWS_DEFAULT_REGION=eu-west-1

aws --endpoint-url=http://localhost.loc:4593 iam create-role \
    --role-name crawler-trigger \
    --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["lambda:InvokeFunction"]}, {"Effect": "Allow", "Action": ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"]}]}'

aws --endpoint-url=http://localhost.loc:4574 lambda create-function \
    --function-name crawler-trigger \
    --runtime python3.8 \
    --handler run.crawler \
    --role arn:aws:iam::000000000000:role/crawler-trigger \
    --zip-file fileb:///var/www/crawler-trigger/local/latest.zip

aws --endpoint-url=http://localhost.loc:4576 sqs create-queue \
    --queue-name urls_regular_out

aws --endpoint-url=http://localhost.loc:4574 lambda create-event-source-mapping \
    --batch-size 1 \
    --event-source-arn arn:aws:sqs:$AWS_DEFAULT_REGION:000000000000:urls_regular_out \
    --function-name crawler-trigger
```

Does anyone have a solution?

**Comment by BR0kEN-** [comment] 2020-03-16 16:44
And the reason - changed `AWS_DEFAULT_REGION`. Once it is set to `us-east-1` the SQS message triggers lambda.

I decided to blindly try this after reading https://github.com/localstack/localstack/issues/1290#issuecomment-531595250.

**Closed** 2020-03-16 16:47 UTC
Labels: bug, needs-triaging, regression

**Comment by BR0kEN-** [comment] 2020-03-16 16:52
I'd say it's a good idea to disallow changing the `AWS_DEFAULT_REGION` (or ensure a change doesn't affect stack operability). This simple parameter change could cost someone a couple of hours.

**Comment by ambreenshameem** [comment] 2020-08-31 19:41
@whummer   --> So when i am trying to trigger Lambda  thru SQS, and  running below commands for event mapping,  Lambda isn't triggering-
aws --endpoint-url=http://localhost:4574 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:us-east-1:queue:my_sqs --function-name my_lambda
OR 
aws --endpoint-url=http://localhost:4574 lambda create-event-source-mapping --event-source-arn arn arn:aws:sqs:elasticmq:000000000000: my_sqs --function-name my_lambda

but passing $AWS_DEFAULT_REGION worked and successfully triggered Lambda 
aws --endpoint-url=http://localhost:4574 lambda create-event-source-mapping --event-source-arn arn:aws:sqs:$AWS_DEFAULT_REGION:000000000000:my_sqs --function-name SQSdemo

So for mapping SNS/SQS are we suppose to use  $AWS_DEFAULT_REGION instead of “elasticmq” Or “us-east-1”.

**Comment by codan84** [comment] 2021-03-17 17:13
Same problem here, but I am using CloudFormation generated by serverless to deploy the code. None of my lambdas are being triggered off SQS messages.
