### ISSUE TITLE
Starting localstack on Windows

### ISSUE THREAD

**Issue by rol4400** [localstack/localstack#822] opened 2018-07-01 05:32 UTC
Hi all. I recently installed localstack on Windows and have had some issues running it. Because the localstack file in Python's Scripts folder requires bash, I've been running it using conemu. I originally had to modify this localstack file to change the first line from "#!C:/Program Files (x86)/Python36-32/python.exe" to "#!python.exe" as the spaces were causing a syntax error. Running the web interface, there were additional errors. In the "C:\Program Files (x86)\Python36-32\Lib\site-packages\localstack\dashboard\api.py" file, I had to change "cd "%s"; npm install" to "cd "%s" && npm install" on line 96 to get it to run. When I run  "DEBUG=1 localstack start" in the terminal; however, I receive a number of errors that look to be from similar Windows syntax issues. Looking through the changelog and other issues it appears localstack does support Windows so I'm wondering if there's something I've done wrong in installation. (just ran the pip command from the readme). The errors I get from running localstack start are shown below and I'm currently using localstack version 0.8.7.

λ DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock ES service (http port 4578)...
Starting local Elasticsearch (http port 4571)...
'ES_JAVA_OPTS' is not recognized as an internal or external command,
operable program or batch file.
Starting mock S3 (http port 4572)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Error: Unable to access jarfile C:\Program
Starting mock SES (http port 4579)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock SSM (http port 4583)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock API Gateway (http port 4567)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock DynamoDB (http port 4569)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Lambda service (http port 4574)...
Starting mock Kinesis (http port 4568)...
The system cannot find the path specified.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Starting mock Redshift (http port 4577)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock Route53 (http port 4580)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock CloudFormation (http port 4581)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
Starting mock CloudWatch (http port 4582)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,
operable program or batch file.
2018-07-01T15:18:12:WARNING:infra.py: Service "elasticsearch" not yet available, retrying...

**Comment by pfouilloux** [comment] 2018-07-05 12:08
Running in windows seems to be a bit broken at the moment. I've been seeing things like:
`chown : The term 'chown' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
in my own (limited) experimentation.

Until windows support improves the workaround I'm using is to spin up a docker container using 
`docker run localstack/localstack` instead. Is that an option for you too?

**Comment by jopincar** [comment] 2018-07-11 16:36
PS C:\Users\John\AppData\Local\Programs\Python\Python36-32\Scripts> py localstack start
Starting local dev environment. CTRL-C to quit.
ERROR: 'cd "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true': b"'zip' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n'true' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
Error starting infrastructure: Command 'cd "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1. Traceback (most recent call last):
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\services\install.py", line 140, in install_components
    parallelize(install_component, names)
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\utils\common.py", line 751, in parallelize
    result = pool.map(func, list)
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\services\install.py", line 132, in install_component
    install_dynamodb_local()
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\services\install.py", line 102, in install_dynamodb_local
    run('cd "%s" && zip -u DynamoDBLocal.jar log4j2.xml || true' % INSTALL_DIR_DDB)
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\utils\common.py", line 653, in run
    return do_run(cmd)
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\utils\common.py", line 650, in do_run
    raise e
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack\utils\common.py", line 635, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\users\john\appdata\local\programs\python\python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1.

ERROR: Command 'cd "c:\users\john\appdata\local\programs\python\python36-32\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1.
PS C:\Users\John\AppData\Local\Programs\Python\Python36-32\Scripts>

**Comment by Vignesh40** [comment] 2018-07-26 05:00
+1 Similar issue

**Comment by ss207210** [comment] 2018-09-07 07:06
Getting similar issue while starting the localstack service on windows:   


Starting local dev environment. CTRL-C to quit.
Starting mock ES service (http port 4578)...
Starting local Elasticsearch (http port 4571)...
'ES_JAVA_OPTS' is not recognized as an internal or external command,

operable program or batch file.

Starting mock S3 (http port 4572)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,

operable program or batch file.

Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,

operable program or batch file.

12:31:38.594 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.10) ...

12:31:39.396 [elasticmq-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started

12:31:40.711 [elasticmq-akka.actor.default-dispatcher-2] ERROR akka.io.TcpListener - Bind failed for TCP channel on endpoint [/0.0.0.0:4561]

java.net.BindException: Address already in use: bind

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)

at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)

at akka.io.TcpListener.<init>(TcpListener.scala:53)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at akka.util.Reflect$.instantiate(Reflect.scala:65)

at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)

at akka.actor.Props.newActor(Props.scala:213)

at akka.actor.ActorCell.newActor(ActorCell.scala:626)

at akka.actor.ActorCell.create(ActorCell.scala:652)

at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)

at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)

at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)

at akka.dispatch.Mailbox.run(Mailbox.scala:223)

at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

12:31:40.711 [elasticmq-akka.actor.default-dispatcher-5] ERROR o.e.rest.sqs.TheSQSRestServerBuilder - Cannot start SQS rest server, bind address 0.0.0.0:4561

akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of Address already in use: bind

Caused by: java.net.BindException: Address already in use: bind

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)

at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)

at akka.io.TcpListener.<init>(TcpListener.scala:53)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at akka.util.Reflect$.instantiate(Reflect.scala:65)

at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)

at akka.actor.Props.newActor(Props.scala:213)

at akka.actor.ActorCell.newActor(ActorCell.scala:626)

at akka.actor.ActorCell.create(ActorCell.scala:652)

at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)

at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)

at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)

at akka.dispatch.Mailbox.run(Mailbox.scala:223)

at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

12:31:40.710 [main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main

akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of Address already in use: bind

Caused by: java.net.BindException: Address already in use: bind

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)

at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)

at akka.io.TcpListener.<init>(TcpListener.scala:53)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at akka.util.Reflect$.instantiate(Reflect.scala:65)

at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)

at akka.actor.Props.newActor(Props.scala:213)

at akka.actor.ActorCell.newActor(ActorCell.scala:626)

at akka.actor.ActorCell.create(ActorCell.scala:652)

at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)

at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)

at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)

at akka.dispatch.Mailbox.run(Mailbox.scala:223)

at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by whummer** [comment] 2019-08-03 19:10
@jopincar @Vignesh40 @rol4400 @pfouilloux @jopincar  Closing as duplicate of #563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

* only install the bare minimum dependencies by default
* start LocalStack in Docker by default, and
* lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:10 UTC
