### ISSUE TITLE
bug: boto3 uploading file to s3 failing

### ISSUE THREAD

**Issue by shubhammapara** [localstack/localstack#4700] opened 2021-10-05 06:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a block of code that first gets pre-signed URL for the s3 object and then it calls upload to the s3 bucket using the following code:

`resource.meta.client.put_object(Body=file_obj, Bucket=AWS_S3_BUCKET_NAME, Key=file_name,ContentType=content_type)`

FYI, `resource` is an s3 client object which is created as follows:

`session = boto3.Session()`
`resource = session.client('s3', endpoint_url='http://localhost:4566')`

Currently, I am getting the following error in localstack console

` 2021-10-05T05:59:20:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /collections-asset", target header "", auth header "", data ""`

### Expected Behavior

The object should get uploaded to the s3 bucket and it should return the location.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

docker-compose-yml file:
`version: "3.8"`

`services:`
`  localstack:`
  `  container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"`
`    image: localstack/localstack`
  `  ports:`
`      - "127.0.0.1:53:53"`
`      - "127.0.0.1:443:443"`
`      - "4566:4566"`
`      - "4571:4571"`
 `   environment:`
 `     - SERVICES=s3,sqs`
`      - DATA_DIR=/tmp/localstack/data`
`      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:8080`
`      - DISABLE_CORS_CHECKS=1`
`    volumes:`
`      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"`
`      - "/var/run/docker.sock:/var/run/docker.sock"`

After this I simply call the above code to upload file

### Environment

```markdown
- OS: macOS Big Sur
- LocalStack: latest
```

### Anything else?

<img width="1435" alt="Screenshot 2021-10-05 at 11 50 49 AM" src="https://user-images.githubusercontent.com/68106104/135970791-75090c6c-a618-4fb8-bb86-e39c8f8ab3c3.png">

**Comment by pinzon** [comment] 2021-11-02 18:12
Hi @shubhammapara could you provide more code to reproduce your issue? I'm trying to reproduce it but both uploading a file directly and from a presigned url  work without a problem.

Here is the code I used:
```python3
import requests
import boto3
from botocore.client import ClientError

session = boto3.session.Session()
s3 = session.client('s3',  endpoint_url='http://localhost:4566')

AWS_S3_BUCKET_NAME='test'
KEY='testFile'
KEY2='2testFile'
PATH='./example'

#create bucket 
try:
   s3.head_bucket(Bucket=AWS_S3_BUCKET_NAME)
except ClientError:
   s3.create_bucket(Bucket=AWS_S3_BUCKET_NAME)

#upload file directly
s3.put_object(Body=PATH, Bucket=AWS_S3_BUCKET_NAME, Key=KEY)


#upload using a presigned URL
presigned_url= s3.generate_presigned_url(
	'put_object',
	Params={'Bucket': AWS_S3_BUCKET_NAME,'Key': KEY2},
	ExpiresIn=3600)

requests.put(url=presigned_url,data=open(PATH,'rb'))

print(s3.list_objects(Bucket=AWS_S3_BUCKET_NAME)['Contents'])
```

I'll close this issue for now since it seems like an usage problem but I'll open it again once I get more info about your problem.

**Closed by pinzon** 2021-11-02 18:12 UTC
Labels: bug, needs-triaging, aws:s3
