### ISSUE TITLE
Not able to SSH the created EC2 instance

### ISSUE THREAD

**Issue by uyadavv** [localstack/localstack#2692] opened 2020-07-07 14:23 UTC
# Type of request: This is a bug

# Detailed description
I am trying to ssh using this command:
ssh -i "MyKeyPair.pem" ec2-user@54.214.9.166 --endpoint-url=http://localhost:4597 get this error
"ssh: connect to host 54.214.9.166 port 22: Connection timed out"

--

I 

## Expected behavior
Must be able to ssh the created EC2 Instance
...

## Actual behavior
Getting Error while SSH
"ssh: connect to host 54.214.9.166 port 22: Connection timed out"
...

# Steps to reproduce

1. Created EC2 Instance using this command:
aws --endpoint-url=http://localhost:4597 ec2 run-instances --image-id ami-09d95fab7fff3776c --count 1 --instance-type t2.micro --key-name C:/Users/Desktop/testing.pem --security-group-ids sg-2d25eb0w

2. Now try to ssh using this command:
ssh -i "MyKeyPair.pem" ec2-user@54.214.9.166 --endpoint-url=http://localhost:4597

## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment] 2020-08-02 20:40
Thanks for reporting @uyadavv . Please note that launching EC2 instances (i.e., creating actual virtual machines that you can connect to via EC2) is not (yet) fully supported in LocalStack. Closing this issue as a duplicate of #1996 - let's please continue the discussion on the other issue... Thanks!

**Closed by whummer** 2020-08-02 20:40 UTC
