### ISSUE TITLE
Multiple secrets in secrets manager

### ISSUE THREAD

**Issue by jgunn987** [localstack/localstack#1079] opened 2019-01-09 14:40 UTC
It seems that the secrets manager can only store one secret, is there scope to increase this limit?

**Comment by gerbenmeyer** [comment] 2019-01-15 20:31
Running into the same issue. Seems like every secret created gets the same `VersionId`, despite of what `ClientRequestToken` provided when creating it. Hopefully this can be fixed!

**Comment by MichaelDSalzman** [comment] 2019-01-17 17:06
The issue is with the moto python library. This (and other issues) have been fixed and merged to master. It _should_ be included in the next release of moto and then it should be added to the subsequent release of localstack. No idea when that will happen.

Here's a link to another issue that was raised. It includes a link to the moto PR that was merged: https://github.com/localstack/localstack/issues/981

**Comment by whummer** [comment] 2020-03-31 19:58
Thanks for reporting @jgunn987 @gerbenmeyer @MichaelDSalzman @jgunn987 . This should be fixed in the latest version - an integration test has been added in #2223 . Please report here if the problem persists. Thanks

**Closed by whummer** 2020-03-31 19:58 UTC
