### ISSUE TITLE
API Gateway: 500 error on update Rest API with Swagger spec

### ISSUE THREAD

**Issue by jamespamplin** [localstack/localstack#1957] opened 2020-01-17 08:51 UTC
Hi guys, consistently getting 500 error responses when trying to update a new API Gateway Rest API with a Swagger spec.

I'm orchestrating with Pulumi, using the `@pulumi/awsx` package to build out a test API gateway with no routes. The package constructs an API Gateway with a Swagger spec, and performs aws api calls via terraform providers underneath.

Here's the call sequence to replicate the issue, captured via proxying with mitmproxy:

1. Create a RestAPI:

```
curl -H 'User-Agent:aws-sdk-go/1.27.0 (go1.13.6; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.11+compatible (+https://www.terraform.io)' -H 'Content-Length:73' -H 'Accept:application/json' -H 'Authorization:AWS4-HMAC-SHA256 Credential=mockAccessKey/20200117/us-east-1/apigateway/aws4_request, SignedHeaders=accept;content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=0ee091e679dc60847871c4b3ccc1eb7cefe8064285a5d9d82229b41dd2b72d1c' -H 'Content-Type:application/json' -H 'X-Amz-Date:20200117T080847Z' -H 'X-Amz-Security-Token:nothing' -H 'Accept-Encoding:gzip' -H 'Connection:close' -X POST 'http://localhost:4567/restapis' --data-binary '{"apiKeySource":"HEADER","binaryMediaTypes":["*/*"],"name":"hello-world"}'

```

2. Update API with Swagger definition body:

```
# note: replace the rest api id `bmtiorrlv3` below with the id of the api created in first call (1)
curl -i -H 'User-Agent:aws-sdk-go/1.27.0 (go1.13.6; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.11+compatible (+https://www.terraform.io)' -H 'Content-Length:451' -H 'Accept:application/json' -H 'Authorization:AWS4-HMAC-SHA256 Credential=mockAccessKey/20200117/us-east-1/apigateway/aws4_request, SignedHeaders=accept;content-length;host;x-amz-date;x-amz-security-token, Signature=e976099157b754cf1555592075737b3c4e2dde70931a02d53a8009e5cee6ac25' -H 'X-Amz-Date:20200117T080847Z' -H 'X-Amz-Security-Token:nothing' -H 'Accept-Encoding:gzip' -H 'Connection:close' -X PUT 'http://localhost:4567/restapis/bmtiorrlv3?mode=overwrite' --data-binary '{"swagger":"2.0","info":{"title":"hello-world","version":"1.0"},"paths":{},"x-amazon-apigateway-binary-media-types":["*/*"],"x-amazon-apigateway-gateway-responses":{"MISSING_AUTHENTICATION_TOKEN":{"statusCode":404,"responseTemplates":{"application/json":"{\\"message\\": \\"404 Not found\\" }"}},"ACCESS_DENIED":{"statusCode":404,"responseTemplates":{"application/json":"{\\"message\\": \\"404 Not found\\" }"}}},"x-amazon-apigateway-api-key-source":"HEADER"}'
```

Response:
```
HTTP/1.1 500 Internal Server Error
Server: BaseHTTP/0.6 Python/3.7.5
Date: Fri, 17 Jan 2020 08:40:48 GMT
Content-Type: text/html
Content-Length: 290
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging
Access-Control-Expose-Headers: x-amz-version-id

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Localstack container logs (started via docker-compose):

```
localstack_main | 2020-01-17 08:43:22,967:API: Error on request:
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
localstack_main |     execute(self.server.app)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
localstack_main |     application_iter = app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 135, in __call__
localstack_main |     return backend_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
localstack_main |     return self.wsgi_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
localstack_main |     response = self.handle_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 150, in __call__
localstack_main |     if len(result) == 3:
localstack_main | TypeError: object of type 'NoneType' has no len()
localstack_main | 2020-01-17 08:43:22,967:API: Error on request:
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
localstack_main |     execute(self.server.app)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
localstack_main |     application_iter = app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 135, in __call__
localstack_main |     return backend_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
localstack_main |     return self.wsgi_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
localstack_main |     response = self.handle_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 150, in __call__
localstack_main |     if len(result) == 3:
localstack_main | TypeError: object of type 'NoneType' has no len()
localstack_main | 2020-01-17 08:43:22,967:API: Error on request:
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
localstack_main |     execute(self.server.app)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
localstack_main |     application_iter = app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 135, in __call__
localstack_main |     return backend_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
localstack_main |     return self.wsgi_app(environ, start_response)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
localstack_main |     response = self.handle_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 150, in __call__
localstack_main |     if len(result) == 3:
localstack_main | TypeError: object of type 'NoneType' has no len()
```

Localstack docker image `latest` (2020-01-17):
Digest: `sha256:15cece3343cd14df99b4637962536c51191134c47ffb5198694bb9a8140e2840`

`docker-compose.yml`:
```
version: "2.1"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4567-4597:4567-4597"
    environment:
      - START_WEB=0
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker}
      - LAMBDA_REMOTE_DOCKER=${LAMBDA_REMOTE_DOCKER- 0}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Thanks guys! Let me know if you need any more info on anything.

**Comment by ChocPanda** [comment] 2020-02-06 14:09
This is not supported behaviour. Please see https://github.com/localstack/localstack/issues/171

**Comment by whummer** [comment] 2020-02-26 12:34
Thanks for reporting @jamespamplin , and thanks for referencing the issue @ChocPanda . Closing as duplicate of #171 - please follow the discussion there. If anyone would be willing to add this functionality, a pull request would be highly appreciated! Thanks

**Closed by whummer** 2020-02-26 12:34 UTC

**Comment by jamespamplin** [comment] 2020-02-28 10:04
Thanks both, will do!
