### ISSUE TITLE
Mistaken customized Codes

### ISSUE THREAD

**Issue by anirudh-hegde** [localstack/localstack#11611] opened 2024-10-01 04:42 UTC
![Screenshot from 2024-10-01 09-47-42](https://github.com/user-attachments/assets/dcc3a2b0-789f-4ef0-8459-f6c6024ad1fd)
![p2](https://github.com/user-attachments/assets/79b64d2f-d36f-4626-9c74-c348a147f017)

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses
File Path: https://github.com/localstack/localstack/blob/master/scripts/capture_notimplemented_responses.py

**Comment by alexrashed** [comment] 2024-10-02 14:12
The script you linked is not part of LocalStack, it is a utility script for us to track the coverage of API operations by AWS.
Could you please describe your issue with a minimal reproducible exampe to help us resolve your actual issue?

**Comment by alexrashed** [comment] 2024-10-10 09:25
Since we didn't get a response yet and I really don't think this is a script that is used by any of our users, I'll close this issue for now.

**Closed by alexrashed** 2024-10-10 09:25 UTC
Labels: status: response required
