### ISSUE TITLE
bug: `localstack:latest` doesn't start with S3 and SQS via Testcontainers in GH Actions

### ISSUE THREAD

**Issue by peshrus** [localstack/localstack#8125] opened 2023-04-12 14:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`localstack:latest` doesn't start with S3 and SQS in GH Actions. 
See https://github.com/peshrus/localstack-latest-issue/pull/1
```
> Task :test

LocalstackTest > Localstack > LocalstackTest.cannot start S3 & SQS with the latest version FAILED
    org.testcontainers.containers.ContainerLaunchException at LocalstackTest.kt:15
        Caused by: org.testcontainers.containers.ContainerLaunchException at LocalstackTest.kt:15
            Caused by: org.rnorth.ducttape.RetryCountExceededException at LocalstackTest.kt:15
                Caused by: org.testcontainers.containers.ContainerLaunchException at LocalstackTest.kt:15
                    Caused by: org.testcontainers.containers.ContainerLaunchException at LocalstackTest.kt:15

2 tests completed, 1 failed

> Task :test FAILED
```

`localstack:1.4` works well.

### Expected Behavior

`localstack:latest` should be able to start with S3 and SQS in GH Actions similar to `localstack:1.4`

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Via Testcontainers, see https://github.com/peshrus/localstack-latest-issue/pull/1/files#diff-9922c24a8f5ee38762aa49ae00af4590113bb6c732c64871b0ab2cc825dadba4R21

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
```

**Comment by bentsku** [comment] 2023-04-13 03:47
Hi @peshrus and thanks for your report! From a quick glance to the repo, could it be that this issue is a duplicate of #8127, see with this resolution: https://github.com/localstack/localstack/issues/8127#issuecomment-1505615761 ?

It seems you are still using `"/docker-entrypoint-initaws.d/init.sh",`, which has been deprecated in LocalStack 1.4 and removed with 2.0. From the other issue:

> The new equivalent would be /etc/localstack/init/ready.d. Please give that a try, and you can find more information on our docs: https://docs.localstack.cloud/references/init-hooks/

**Comment by peshrus** [comment] 2023-04-13 07:53
Hi @bentsku. 
Thanks a lot for the hint. It works (see https://github.com/peshrus/localstack-latest-issue/pull/1/commits/f087a1b8e8d3e5666267f4816b7fc6ecba73aa72).

**Closed** 2023-04-13 10:18 UTC
Labels: type: bug, status: triage needed
