### ISSUE TITLE
Timestamp parse error when GetMetricData is called from aws-sdk for ec2 instance

### ISSUE THREAD

**Issue by sahajavidya** [localstack/localstack#3494] opened 2021-01-20 09:24 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Timestamp parse error when GetMetricData is called from aws-sdk for ec2 instance.

$ ./main.exe
**Error: SerializationError: failed decoding Query response
        status code: 200, request id: BOQA1T4EYEUIWMJKJKJKV1RCKIVNMD54YM1A
caused by: parsing time "2021-01-20 09:02:29.571913" as "2006-01-02T15:04:05.999999999Z": cannot parse " 09:02:29.571913" as "T"**

...

## Expected behavior

Should not fail with timestamp parse error.
...

## Actual behavior

...

# Steps to reproduce

1)  put metric data for metric : CPUUtilization
aws --endpoint-url=http://localhost:5000 cloudwatch put-metric-data --namespace AWS/EC2 --metric-data '[{ "MetricName": "CPUUtilization", "Dimensions": [ { "Name": "InstanceId", "Value": "i-7355f4f0eb49f4686" } ], "Value": 28, "Unit": "Percent" }]'

2) Run the go code to fetch metric data. code is as below - 

//===================================================================================
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/cloudwatch"
)

func main() {
	sess := session.Must(session.NewSessionWithOptions(
		session.Options{
			SharedConfigState: session.SharedConfigEnable,
			Config: aws.Config{
				Region:     aws.String("us-east-1"),
				Endpoint:   aws.String("http://localhost:5000"),
				DisableSSL: aws.Bool(true),
			},
		}))

	svc := cloudwatch.New(sess)

	currentTime := time.Now()
	metric := []*cloudwatch.MetricDataQuery{{
		Id: aws.String("m_localstackReq"),
		MetricStat: &cloudwatch.MetricStat{
			Metric: &cloudwatch.Metric{
				Dimensions: []*cloudwatch.Dimension{{
					Name:  aws.String("InstanceId"),
					Value: aws.String("i-7355f4f0eb49f4686"),
				}},
				MetricName: aws.String("CPUUtilization"),
				Namespace:  aws.String("AWS/EC2"),
			},
			Period: aws.Int64(600),
			Stat:   aws.String("Average"),
		},
		Period:     aws.Int64(600),
		ReturnData: aws.Bool(true),
	}}

	dataResult, err := svc.GetMetricDataWithContext(context.Background(),
		&cloudwatch.GetMetricDataInput{
			EndTime:           aws.Time(currentTime),
			StartTime:         aws.Time(currentTime.Add((-time.Duration(600)) * time.Second)),
			MetricDataQueries: metric,
			ScanBy:            aws.String("TimestampAscending"),
			NextToken:         nil,
		})

	if err != nil {
		fmt.Printf("Error: %v", err.Error())
	} else {
		fmt.Printf("Result: %v", dataResult)
	}

}
//===================================================================================
Copy the above code in main.go and run the code with below command.
$ go run main.go

3) you should see the Error printed as below:-
$ ./main.exe
Error: SerializationError: failed decoding Query response
        status code: 200, request id: BOQA1T4EYEUIWMJKJKJKV1RCKIVNMD54YM1A
caused by: parsing time "2021-01-20 09:02:29.571913" as "2006-01-02T15:04:05.999999999Z": cannot parse " 09:02:29.571913" as "T"

As timestamp is not coming in proper format from local stack, it is failing.

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by irahulranjan** [comment] 2021-01-20 21:43
Hi @sahajavidya, thanks for reporting the issue. It seems to be duplicate of the issue that you raised https://github.com/localstack/localstack/issues/3492.

**Comment by irahulranjan** [comment] 2021-01-23 20:14
@sahajavidya, can you please pull the latest localstack image and try it out. The issue should be fixed.
Please reopen, if the issue persists

**Closed by irahulranjan** 2021-01-23 20:14 UTC

**Comment by sahajavidya** [comment] 2021-01-25 05:21
Thanks working as expected
