### ISSUE TITLE
Elasticsearch domain health never turns green 

### ISSUE THREAD

**Issue by MakarandPundlik** [localstack/localstack#7337] opened 2022-12-15 10:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am creating elasticsearch domain using command line 
This is my ```docker-compose.yml```
``` 
version: "2.1"
services:
  localstack:
    image: "localstack/localstack"
    container_name: "localstack"
    ports:
      - "4566-4620:4566-4620"
      - "127.0.0.1:8055:8080"
    environment:
      - SERVICES=s3,es,dynamodb,apigateway,lambda,sns,sqs,sloudformation
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - DYNAMODB_SHARE_DB=1
      - DISABLE_CORS_CHECKS=1
      - AWS_DDB_ENDPOINT=http://localhost:4566

    volumes:
      - "${TMPDIR:-/var/lib/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "local"

networks:
  local:
    driver: "bridge"
```
My domain gets created, after some time even ```processing``` flag becomes ```false```
But when i check my cluster health using ```curl mydomain.us-east-1.es.localhost.localstack.cloud:4566/_cluster/health``` 
```status``` remains **yellow** instead of green.
Is this in any sense related to my previously created [issue](https://github.com/localstack/localstack/issues/7326) 

Even when i create new index using ```curl -X PUT http://mydomain.us-east-1.es.localhost.localstack.cloud:4566/my-index```  it gets created but individual index ```health``` remains **yellow**

### Expected Behavior

indices and domains should have **green** health and status values 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Windows 11
- LocalStack: latest
```

### Anything else?

this is my previously created issue for the same 
https://github.com/localstack/localstack/issues/7326

**Comment by thrau** [comment] 2022-12-15 12:02
@MakarandPundlik, could you please share the commands you use to create the elasticsearch domain?

If you could also share the localstack container logs, or take a look yourself whether they reveal something, that would be great!

**Comment by MakarandPundlik** [comment] 2022-12-16 05:59
> @MakarandPundlik, could you please share the commands you use to create the elasticsearch domain?
> 
> If you could also share the localstack container logs, or take a look yourself whether they reveal something, that would be great!

Hi @thrau, i'm using cli to create the domain with this command ```awslocal es create-elasticsearch-domain --cli-input-json file://elasticsearch/file.json ```

Here ```file``` refers to the file which contains parameters to create ES domain 
file.json looks like this 

```
 {
            "DomainName":"my-domain",
            "ElasticsearchVersion": "6.8",
            "ElasticsearchClusterConfig": {
              "DedicatedMasterEnabled": true,
              "DedicatedMasterCount": 5,
              "ZoneAwarenessEnabled": true,
              "ZoneAwarenessConfig":{
              "AvailabilityZoneCount":2
              },
              "InstanceCount": 5,
              "InstanceType":"m3.medium.elasticsearch",
              "DedicatedMasterType": "m3.medium.elasticsearch",
              "WarmEnabled":false,
              "WarmType":"ultrawarm1.medium.search"
            },
            "EBSOptions" : {
                "EBSEnabled" : true,
                "VolumeSize" : 20,
                "VolumeType" : "gp2"
            }
     }       
```
Hope this helps.

**Comment by alexrashed** [comment] 2023-07-05 13:47
Hi @MakarandPundlik!
Sorry that it took quite a while for the response. We changed a lot in the meantime, and I tried to reproduce your issue with the given CLI input (thanks!):
```
$ awslocal es create-elasticsearch-domain --cli-input-json file://~/Downloads/test-es.json
$ awslocal es describe-elasticsearch-domain --domain-name my-domain
{
    "DomainStatus": {
        "DomainId": "000000000000/my-domain",
        "DomainName": "my-domain",
        "ARN": "arn:aws:es:us-east-1:000000000000:domain/my-domain",
        "Created": true,
        "Deleted": false,
        "Endpoint": "my-domain.us-east-1.es.localhost.localstack.cloud:443",
        "Processing": false,
        "UpgradeProcessing": false,
        "ElasticsearchVersion": "6.8",
        ...
}
$ curl my-domain.us-east-1.es.localhost.localstack.cloud:443/_cluster/health | jq...
{
  "cluster_name": "elasticsearch",
  "status": "green",
  ...
}
```
So for me, your issue does not seem to be reproducible anymore.
Could you please try to test this again with the latest version of LocalStack (pull `latest` from DockerHub before running the test).
Thanks!

**Comment by alexrashed** [comment] 2023-07-11 06:32
I will close this issue for now, since I can't reproduce it anymore. Please feel free to open a new issue if you are still experiencing any issues. Thanks!

**Closed by alexrashed** 2023-07-11 06:32 UTC
Labels: type: bug, status: response required, aws:elasticsearch
