### ISSUE TITLE
Impossible to do request from lambda to another container

### ISSUE THREAD

**Issue by Aornn** [localstack/localstack#3836] opened 2021-04-06 17:20 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Hi here is my probleme i want to call an api on another container so i had set LAMBDA_DOCKER_NETWORK on host to be sure I can. but every time i run my lambda I get 
```
localstack_main    | 2021-04-06T17:11:14:DEBUG:localstack.services.awslambda.lambda_api: Running Lambda function arn:aws:lambda:eu-west-3:000000000000:function:sign from API Gateway invocation: GET /sign
localstack_main    | 2021-04-06T17:11:14:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.21.0.4
localstack_main    | 2021-04-06T17:11:14:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e AWS_REGION="$AWS_REGION" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e DOCKER_LAMBDA_API_PORT="$DOCKER_LAMBDA_API_PORT" -e DOCKER_LAMBDA_RUNTIME_PORT="$DOCKER_LAMBDA_RUNTIME_PORT" --network="host"  --rm "lambci/lambda:go1.x" "sign")";docker cp "/tmp/localstack/zipfile.214d5edb/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
localstack_main    | 2021-04-06T17:11:15:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:eu-west-3:000000000000:function:sign result / log output:
localstack_main    | 
localstack_main    | > 2021/04/06 17:11:15 Mock server did not start in time
localstack_main    | 2021-04-06T17:11:16:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-3:000000000000:function:sign: Lambda process returned error status code: 1. Result: . Output:
localstack_main    | 2021/04/06 17:11:15 Mock server did not start in time Traceback (most recent call last):
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 581, in run_lambda
localstack_main    |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 176, in execute
localstack_main    |     return do_execute()
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 168, in do_execute
localstack_main    |     return _run(func_arn=func_arn)
localstack_main    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack_main    |     raise e
localstack_main    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack_main    |     result = func(*args, **kwargs)
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in _run
localstack_main    |     raise e
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 147, in _run
localstack_main    |     result = self._execute(func_arn, func_details, event, context, version)
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 325, in _execute
localstack_main    |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack_main    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 231, in run_lambda_executor
localstack_main    |     raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_main    | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: . Output:
localstack_main    | 2021/04/06 17:11:15 Mock server did not start in time
localstack_main    | 

```
...

## Expected behavior
I expect to get an response like this from my lambda : 
```
{"token" : "thistoken"}
```

# Steps to reproduce
here is my dockerfile : 
```
version: '3'

services:
  myapi:
    container_name: myapi
    build: ./myapi
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICES=lambda,apigateway
      - DEBUG=1
      - DEFAULT_REGION=eu-west-3
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=host


```

my server  : 
```
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/cred", func(w http.ResponseWriter, r *http.Request) {
		log.Println("Request incoming")
		payload := []byte(`{"token" : "thistoken"}`)
		w.Header().Set("Content-Type", "application/json")
		w.Write(payload)
	}).Methods("POST")
	r.HandleFunc("/ping", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "pong")
	}).Methods("GET")
	srv := &http.Server{
		Handler:      r,
		Addr:         "0.0.0.0:8000",
		WriteTimeout: 5 * time.Minute,
		ReadTimeout:  5 * time.Minute,
	}

	log.Fatal(srv.ListenAndServe())
}

```
In my dockerfile server my port 8000 is exposed

my lambda 
```
package main

import (
	"context"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)
func HandleRequest(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	resp, err := http.Post("myapi:8000/cred", "application/json", nil)
	if err != nil {
		log.Println("ERROR NUL : ", err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Println("Error while read body : ", err)
	}
	log.Println(string(body))
	return events.APIGatewayProxyResponse{
		StatusCode: http.StatusOK,
		Body:       "SALUT",
	}, nil
}

func main() {
	lambda.Start(HandleRequest)
}

```

I'm sure that everything works because when I make a curl inside another container i can get a proper response.

Tanks for all.

**Comment by mgagliardo** [comment] 2021-04-06 21:06
Hello @Aornn, have you tried running everything inside the same docker network? Can you also run a `docker inspect $container_name` on both the lambda function and your own API container to see if both are on the same network/IP segment? 

This sounds to me like a network issue, but I might be wrong.

Example:
```
services:
  myapi:
    container_name: myapi
    build: ./myapi
    networks:
      - internal
  localstack:
  ...
    environment:
      - LAMBDA_DOCKER_NETWORK=internal
    networks:
      - internal
  ...

networks:
  internal:
    name: internal
```

**Comment by mgagliardo** [comment] 2021-04-06 21:44
Hello again, I have just confirmed this works with the following setup, indeed you need to use the same network (and also add `http://` to your POST request).

docker-compose.yml:
```
version: '3'

services:
  myapi:
    container_name: myapi
    build: ./myapi
    ports:
      - 8000:8000
    networks:
      - internal
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICES=lambda,apigateway
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=internal
    networks:
      - internal

networks:
  internal:
    name: internal
```

lambda:
```
package main

import (
	"context"
	"io/ioutil"
	"log"
	"net/http"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)
func HandleRequest(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	resp, err := http.Post("http://myapi:8000/cred", "application/json", nil)
	if err != nil {
		log.Println("ERROR NUL : ", err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Println("Error while read body : ", err)
	}
	log.Println(string(body))
	return events.APIGatewayProxyResponse{
		StatusCode: http.StatusOK,
		Body:       "SALUT",
	}, nil
}

func main() {
	lambda.Start(HandleRequest)
}
```

myapi Dockerfile:
```
$ cat Dockerfile 
FROM busybox:stable

WORKDIR /app

COPY . .

EXPOSE 8000

ENTRYPOINT ["./main"]
```

myapi:
```
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()
	r.HandleFunc("/cred", func(w http.ResponseWriter, r *http.Request) {
		log.Println("Request incoming")
		payload := []byte(`{"token" : "thistoken"}`)
		w.Header().Set("Content-Type", "application/json")
		w.Write(payload)
	}).Methods("POST")
	r.HandleFunc("/ping", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, "pong")
	}).Methods("GET")
	srv := &http.Server{
		Handler:      r,
		Addr:         "0.0.0.0:8000",
		WriteTimeout: 5 * time.Minute,
		ReadTimeout:  5 * time.Minute,
	}

	log.Fatal(srv.ListenAndServe())
}
```

create-function:
```
$ awslocal lambda create-function --function-name test --runtime go1.x --zip-file fileb://main.zip --handler main --role test
```

Invoke output:
```
$ awslocal lambda invoke --function-name test test.txt
myapi         | 2021/04/06 21:41:12 Request incoming
localstack_main | 2021-04-06T21:41:13:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test result / log output:
localstack_main | {"statusCode":200,"headers":null,"multiValueHeaders":null,"body":"SALUT"}
localstack_main | > START RequestId: 6310ccb7-cf53-1033-3e7e-b995760f8670 Version: $LATEST
localstack_main | > 2021/04/06 21:41:12 {"token" : "thistoken"}
localstack_main | > END RequestId: 6310ccb7-cf53-1033-3e7e-b995760f8670
localstack_main | > REPORT RequestId: 6310ccb7-cf53-1033-3e7e-b995760f8670	Init Duration: 147.86 ms	Duration: 5.86 ms	Billed Duration: 6 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB	

$ cat test.txt 
{"body":"SALUT","headers":null,"multiValueHeaders":null,"statusCode":200}
```

**Comment by mgagliardo** [comment] 2021-04-06 21:45
I am closing this as it looks like it could be solved with the proposed solution. Add any further comments if needed. Thanks

**Closed by mgagliardo** 2021-04-06 21:45 UTC

**Comment by Aornn** [comment] 2021-04-07 07:16
Tanks for all, I feel a little silly. Because I did not think that I had to create the network. Now it's obvious.

**Comment by mgagliardo** [comment] 2021-04-07 07:26
Don't be, nothing is ever `obvious` in IT, glad I could help. Cheers mate.
