### ISSUE TITLE
Lambda event invocation doesn't trigger the function

### ISSUE THREAD

**Issue by sahas-** [localstack/localstack#946] opened 2018-09-29 01:20 UTC
Docker version : Docker version 18.06.1-ce, build e68fc7a
Localstack: 66d1868122bc943ef122e4fc78625fa0fc6cecaab4216dee4b926c454698c8c0

Here is my lambda function
```
module.exports.KinesisStreamHandler = function (event, context, callback) { 

       console.log("...executing function...");

       console.log(JSON.stringify(event, null, 2));

       callback(null, "...executing lambda function..."); 

};
```

I created the function.

- When invoked with default invocation type "RequestResponse"  - I see console.log statements on docker logs
- When invoked with --invocation-type Event and without --payload - I see the logs and its complaining about not providing payload (Empty event body specified for invocation of Lambda)

However, when I invoke it with proper payload and --invocation-type Event, function doesn't get triggered. I get 202 immediately and don't see any logs in the container logs.

Am I missing something silly?

**Comment by sahas-** [comment] 2018-10-14 01:40
I'm running docker on mac too. I waited several minutes and no change in behavior.

**Comment by whummer** [comment] 2019-03-08 05:28
Thanks for reporting @sahas- @dleclere . Can you confirm that this problem still exists with the latest version? 

> The function will eventually execute, but it can take several minutes.

Could this be related to Docker downloading the image we're using to execute the Lambda functions (images `lambci/lambda:*`)? This can take in the order of several minutes. Once the image has been downloaded, though, the startup should be much faster.

**Comment by whummer** [comment] 2019-11-26 22:54
Closing this issue as "cannot reproduce" - please report here with more details if the problem persists. Thanks!

**Closed by whummer** 2019-11-26 22:54 UTC
