### ISSUE TITLE
Lambda is not triggering with SNS event and throwing exception

### ISSUE THREAD

**Issue by ambreenshameem** [localstack/localstack#2885] opened 2020-08-26 18:39 UTC
This is a ...

[ ] bug report
Description ->  Trying to trigger Lambda  thru SNS. Publish message is displaying  but lambda is not triggering and throwing exception(screen shot attached)

...

## Expected behavior
The lambda should be triggered successfully after publishing the SNS topic
...

## Actual behavior
Getting exception, though message is successfully published but lambda doesn't trigger.
...

# Steps to reproduce
Steps: 
docker-compose up -d

1. Create Function
aws lambda create-function --endpoint-url=http://localhost:4574 --function-name snsreceiverfunction --runtime java11 --handler com.aws.lamda.SNSReceiverFunction --zip-file fileb://C:\AWS\Localstack\target\localstack-1.0-SNAPSHOT.jar --role arn:aws:iam::1234567:role/anything --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"
1. Create SNS topic-
aws sns create-topic --name lambdafeeder --endpoint-url=http://localhost:4575
1. Subscribe Lambda to topic-
aws sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:lambdafeeder --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:000000000000:function:snsreceiverfunction --endpoint-url=http://localhost:4575

1. Publish SNS topic:
aws --endpoint-url=http://localhost:4575 sns publish  --topic-arn arn:aws:sns:us-east-1:000000000000:lambdafeeder --message "TESTSNS"
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
provided above
Attached is the screen shot of the exception.

Note: On using LAMBDA_EXECUTOR=docker, and LAMBDA_DOCKER_NETWORK=projectname_default, localstack is throwing exception --> default network not found hence i changed the setting to LAMBDA_EXECUTOR=local.)
![LS!UNITO-UNDERSCORE!Exception](https://user-images.githubusercontent.com/68869037/91343233-d525da00-e7a1-11ea-916c-d443bccf775e.JPG)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-239) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment] 2020-08-27 18:44
@ambreenshameem  Thanks for reporting the issue.
Can you please help us with a bit more details here to reproduce the issue as we are not able to reproduce the issue with Python run times.
Can you share us the complete docker-compose.yml as well as java client code example zip using which we can reproduce the issue.
This will help us reproduce and fix the issue a bit sooner.Thanks.

**Comment by ambreenshameem** [comment] 2020-08-28 02:33
@usmangani1 -Thanks for looking into it. Code zip is attached. And below is the docker file content:


version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      ##- DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


[aws-labmda-example-1.0-SNAPSHOT.jar.zip](https://github.com/localstack/localstack/files/5139699/aws-labmda-example-1.0-SNAPSHOT.jar.zip)


please let me know if additional details needed.

**Comment by ambreenshameem** [comment] 2020-09-02 17:54
@whummer  - A response is greatly appreciated. I am stuck here and unable to test my services due to this issue.

**Comment by ashameem123** [comment] 2020-09-08 16:29
@whummer -- am i missing any data to debug this issue?

**Comment by whummer** [comment] 2021-02-02 07:18
@ambreenshameem @ashameem123 Thanks for the update - this issue should be fixed in the meantime, as we have switched from our custom Java Lambda executor to the [Lambci](https://github.com/lambci/docker-lambda) executor for Java lambdas. Please let us know in case the problem persists with the `latest` version of the Docker image. Thanks

**Closed by whummer** 2021-02-02 07:18 UTC
