### ISSUE TITLE
LocalStack Pro Support_Need steps to read data from redis

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#5681] opened 2022-03-15 18:48 UTC
I have a lambda feeding redis. I got the cluster created but I don't see anything flowing into Redis once my lambda is invoked.
Steps:

```
docker-compose up -d
```

```
#!/bin/bash

aws lambda create-function --endpoint-url=http://localhost:4566 --function-name sync-function--runtime java11 --role arn:aws:iam::000000000000:role/delegator.function --handler abc.function.syncFunction --zip-file fileb://syncFunction.zip --environment file://environmentvariables.json
sleep 5

aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name sync-trigger
sleep 5


aws --endpoint-url=http://localhost:4566 elasticache create-cache-cluster --cache-cluster-id i1

#aws --endpoint-url=http://localhost:4566 elasticache --debug create-cache-cluster --engine redis --cache-cluster-id c1 --num-cache-nodes 3 --replication-group-id rg1

aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/sync-trigger --message-body file://test-event.json
```

Am i missing anything here. Also please guide how to read data from redis?

My redis is running on port-4510

**Comment by whummer** [comment] 2022-03-30 09:19
Hi @ashameem123 , thanks for reporting. Can you please share the relevant code snippets of your Java Lambda handler, what is the intended logic of the Lambda?

You can use the `redis-cli` command line interface to read data from Redis - more details can be found here: https://docs.localstack.cloud/aws/elasticache

If you can share a few more details, ideally a small reproducible sample project of your use case, we'd be able to provide more detailed support and guidance.. Thanks!

**Comment by whummer** [comment] 2022-04-18 10:48
Hi @ashameem123 , quick follow-up - have you been able to get it working and connect to your Redis instance in the meantime? Please let us know, so we can close this issue. Thanks!

**Comment by ashameem123** [comment] 2022-04-18 15:54
@whummer - Tried so many times to reach out via slack but no success  :(
I don't have steps to write data to redis (my lambda looks for some info in redis and keeps failing) hence my lambda is not giving me the expected result. 
Would be very helpful if i could get some more details on how to read/write from redis

**Comment by whummer** [comment] 2022-05-14 18:35
Hi again @ashameem123 - looking at the latest Slack conversation, it seems that this issue has been resolved (i.e., you've been able to test your Lambda with Redis and can also see data written to it), can you confirm that? Please do let us know if the problem persists - happy to provide more guidance in that case.. Thanks!

**Closed by whummer** 2022-05-14 18:35 UTC
Labels: question, evaluate-or-close, aws:elasticache

**Comment by ashameem123** [comment] 2022-05-14 19:33
Yes. Thanks for the support. Issue can be closed now.
