### ISSUE TITLE
bug: exception while calling s3.CopyObject: S3 object is not in write mode

### ISSUE THREAD

**Issue by dowben** [localstack/localstack#10407] opened 2024-03-06 17:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

copy failed: s3://test/testfile.txt to s3://test/testfile1.txt An error occurred (InternalError) when calling the CopyObject operation (reached max retries: 4): exception while calling s3.CopyObject: S3 object is not in write mode

### Expected Behavior

Copy to succeed

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

echo 123 > test.txt
awslocal s3api create-bucket --bucket test
awslocal s3 cp test.txt s3:/test/testfile.txt
awslocal s3 cp s3://test/testfile.txt s3://test/testfile1.txt

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack version: 3.2.1.dev20240306101601
- LocalStack Docker container id: fee559b5f664
- LocalStack build date: 2024-03-06
- LocalStack build git hash: e75ccf4
```

### Anything else?

Using Image: localstack/localstack-pro:latest

**Comment by bentsku** [comment] 2024-03-06 19:40
Hello @dowben! Thanks a lot for the report, this regression slipped through. The fix for the issue has been merged, and will be available in the next `latest` image, in around an hour or 2. Thanks a lot again for the report!

**Comment by bentsku** [comment] 2024-03-07 00:07
Hi again, the image should now be available. Could you give it a try and see if it fixes your issue? Thanks!

**Comment by dowben** [comment] 2024-03-07 16:05
Hey, @bentsku, Just ran my tests with the latest image with no issues. Thanks for getting on this so quickly

**Comment by bentsku** [comment] 2024-03-07 16:07
Awesome, thanks a lot for the quick feedback. Sorry this regression went through, we also fixed the root cause of this not being caught. I'll close the issue! Thank you again for the quick report on the issue.

**Closed by bentsku** 2024-03-07 16:07 UTC
Labels: type: bug, status: response required, aws:s3
