### ISSUE TITLE
Can't create a SQS queue using AWS CLI

### ISSUE THREAD

**Issue by kirillt** [localstack/localstack#2936] opened 2020-09-04 11:47 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Can't create a topic in Localstack SQS using AWS CLI.
Both versions 1 and 2 of AWS CLI tested.

## Expected behavior
200 OK returned and the topic created

## Actual behavior
500 Internal Error returned

# Steps to reproduce
## Command used to start LocalStack
```bash
docker run -it --rm --env SERVICES=sqs:4568 -p 4568:4568 localstack/localstack:latest
```

```bash
aws --endpoint-url http://localhost:4568/ sqs create-queue --queue-name my-queue
```

## Error returned
```
Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-251) by [Unito](https://www.unito.io/learn-more)

**Comment by kirillt** [comment] 2020-09-04 11:55
Accessing via edge router doesn't work as well:
```bash
docker run -it --rm --env SERVICES=sqs -p 4566:4566 localstack/localstack
```

Boot log:
```
Waiting for all LocalStack services to be ready
2020-09-04 11:52:07,298 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-09-04 11:52:07,303 INFO supervisord started with pid 9
2020-09-04 11:52:08,306 INFO spawned: 'dashboard' with pid 15
2020-09-04 11:52:08,309 INFO spawned: 'infra' with pid 16
2020-09-04 11:52:08,317 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-09-04 11:52:08,317 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-09-04 11:52:09,322 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 0.11.4
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock SQS service on http ports 4566 (recommended) and 4 (deprecated)...
2020-09-04T11:52:16:INFO:botocore.credentials: Found credentials in environment variables.
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
2020-09-04T11:52:17:INFO:localstack.multiserver: Starting multi API server process on port 50257
Running on 0.0.0.0:4 over http (CTRL + C to quit)
Running on 0.0.0.0:50257 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready.
2020-09-04T11:52:23:INFO:botocore.credentials: Found credentials in environment variables.
```

Request over HTTPS:
```
aws --no-verify-ssl --endpoint-url https://localhost:4566/ sqs create-queue --queue-name integration-brig-events-internal
```

Error message:
```
/usr/local/aws-cli/v2/2.0.46/dist/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

**Comment by kirillt** [comment] 2020-09-04 12:01
But creating a queue with `docker exec $localstack_container awslocal sqs ...` works.
Is AWS CLI from outside of the container supported?

**Comment by usmangani1** [comment] 2020-09-04 20:54
@kirillt Thanks for reporting the issue here.

Can you please tell us what version of localstack are you actually using? You can use this command below

 $ docker images | grep localstack/localstack | grep latest
localstack/localstack   latest               238e3fbf3771        9 days ago          664MB

```

**Comment by kirillt** [comment] 2020-09-06 11:20
Hi @usmangani1. The image version:
```
docker.io/localstack/localstack   latest   ba01985df205   2 days ago     702 MB
```

**Comment by katsanva** [comment] 2020-09-08 07:56
This happens for me both on `latest`, `0.11.4` and `0.11.3`. `0.11.2` is just fine.

**Comment by usmangani1** [comment] 2020-09-12 19:20
@kirillt 

The same aws cli command is working on my system on version 0.11.4.

Can you please run the same command and --debug in the end and add the output here ? It will be easy for us to identify and resolve the issue sooner.Thanks.

`aws --endpoint-url http://localhost:4568/ sqs create-queue --queue-name my-queue --debug
`

**Comment by kirillt** [comment] 2020-09-15 14:23
@usmangani1 here is the log of this command.
[sqs.log](https://github.com/localstack/localstack/files/5225561/sqs.log)

**Comment by usmangani1** [comment] 2020-12-01 17:35
@kirillt We are not able to reproduce the issue on the latest version.Can you please pull the latest image and and give this a try? Please let us know if the issue persists.Thanks

**Comment by kirillt** [comment] 2020-12-04 11:41
Hmm, now it is something a bit different.
```
# LocalStack version: 0.12.2
# docker.io/localstack/localstack        latest                 e61e66be92bf   18 hours ago
docker run -it --rm --env SERVICES=sqs:4568 -p 4568:4568 localstack/localstack:latest

sudo netstat -tlpn | grep 4568
# tcp6       0      0 :::4568                 :::*                    LISTEN      66039/containers-ro
aws --version
# aws-cli/2.1.7 Python/3.7.3 Linux/5.6.11-300.fc32.x86_64 exe/x86_64.fedora.32 prompt/off

aws --endpoint-url http://localhost:4568/ sqs create-queue --queue-name my-queue

# Connection was closed before we received a valid response from endpoint URL: "http://localhost:4568/".
```

[localstack.log](https://github.com/localstack/localstack/files/5642464/localstack.log)

**Comment by whummer** [comment] 2021-02-07 17:51
Thanks for the update @kirillt . Please note that we've recently pushed a fix that unifies all APIs under a single entry point on port `4566`. Can you please try again with the `latest` Docker image and try like this:
```
aws --endpoint-url http://localhost:4566 sqs create-queue --queue-name my-queue
```

Hope that helps - please let us know if the problem persists. Thanks

**Closed by whummer** 2021-02-07 17:51 UTC
Labels: needs-triaging
