### ISSUE TITLE
EventBridge target of SQS does not find queue

### ISSUE THREAD

**Issue by tiaanl** [localstack/localstack#2843] opened 2020-08-14 09:47 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When trying to send event bridge events to sqs, it says the queue does not exist.

## Expected behavior
I expect the event to be put onto the sqs queue.

## Actual behavior
I get the following error: `An error occurred (400) when calling the PutEvents operation: The specified queue does not exist for this wsdl version.`

# Steps to reproduce
## Command used to start LocalStack
`docker run --rm -it -e SERVICES=events,sqs -p 4587:4587 -p 4576:4576 localstack/localstack`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
    #!/bin/bash
    
    export AWS_PAGER=
    AWS_EVENTS="aws --endpoint-url http://localhost:4587 --region eu-west-1 events"
    AWS_SQS="aws --endpoint-url http://localhost:4576 --region eu-west-1 sqs"
    
    echo "Creating SQS queue..."
    QUEUE_URL=`${AWS_SQS} create-queue --queue-name domain-events | jq --raw-output ".QueueUrl"`
    QUEUE_ARN=`${AWS_SQS} get-queue-attributes --queue-url $QUEUE_URL | jq --raw-output ".Attributes.QueueArn"`
    echo " - Queue URL: ${QUEUE_URL}"
    echo " - Queue ARN: ${QUEUE_ARN}"
    
    echo "Creating event bridge rule..."
    RULE_ARN=`${AWS_EVENTS} put-rule --name domain-events | jq --raw-output ".RuleArn"`
    
    echo "Putting targets on rule..."
    ${AWS_EVENTS} put-targets --rule domain-events --targets "Id"="1","Arn"="$QUEUE_ARN" > /dev/null
    
    echo "Putting events on event bus..."
    ${AWS_EVENTS} put-events --entries file://entries.json`entires.json`:

```
[
  {
    "Source": "com.mycompany.myapp",
    "Detail": "{ \"key1\": \"value1\", \"key2\": \"value2\" }",
    "Resources": [],
    "DetailType": "myDetailType"
  }
]
```

and the output:

```
Creating SQS queue...
 - Queue URL: http://localhost:4576/000000000000/domain-events
 - Queue ARN: arn:aws:sqs:eu-west-1:000000000000:domain-events
Creating event bridge rule...
Putting targets on rule...
Putting events on event bus...

An error occurred (400) when calling the PutEvents operation: The specified queue does not exist for this wsdl version.
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-236) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment] 2020-08-14 20:39
@tiaanl 
Thanks for reporting the issue.
We have tried to reproduce the issue issue using aws cli commands attached below with the same entries.json and we are not able to reproduce the issue.Can you please help us understand in case if we are missing something ? 


```
 $ awslocal sqs create-queue --queue-name domain-events --region eu-west-1
{
    "QueueUrl": "http://localhost:4576/000000000000/domain-events"
}

$ awslocal sqs get-queue-attributes --queue-url http://localhost:4576/000000000000/domain-events --region eu-west-1
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1597436862.419952",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1597436862.419952",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:eu-west-1:000000000000:domain-events",
        "Policy": "None",
        "RedrivePolicy": "None",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
$ awslocal events  put-rule --name domain-events  --region eu-west-1
{
    "RuleArn": "arn:aws:events:eu-west-1:000000000000:rule/domain-events"
}
$ awslocal events put-targets --rule domain-events --targets "Id"="1","Arn"="arn:aws:events:eu-west-1:000000000000:rule/domain-events" --region eu-west-1
{
    "FailedEntryCount": 0,
    "FailedEntries": []
}
$ awslocal events put-events --entries file://entries.json --region eu-west-1
{
    "Entries": [
        {
            "EventId": "393be491-0b84-421c-a537-3a0f8f717391"
        }
    ]
}

```

**Comment by manymikes** [comment] 2020-08-24 22:10
A Google search landed me on this same issue because I am receiving the exact same error:
`The specified queue does not exist for this wsdl version.`

It appears to have started fairly recently with no changes to the codebase. I'm not sure if it is helpful but I am using this package to connect to the queue:

```typescript
const consumer = Consumer.create({
  queueUrl: P0_SQS_URL
}
```

I am creating the queues using the following:
```bash
awslocal sqs create-queue --queue-name p0-fuse-queue-dev
```

**Comment by mcshiz** [comment] 2021-05-27 18:51
If you are trying to delete a message using a ReceiptHandle of a non existent message, you will receive this error too. Very Confusing

**Comment by WtfJoke** [comment] 2021-06-07 09:56
I experience a similar issue, for us it works on 0.12.10 and doesnt on 0.12.11+

**Comment by chopstik** [comment] 2021-08-20 01:08
Definetly a region mismatch. I use different region `--region=eu-west-2` in staging/production and `--region=eu-west-1` in local/development and locally I get the same 404 error when working with nthe AWS::sqs client. I thought i read in the docs that localstack/sqs was now region agnostic? Perhaps I misread. I solved by specifying the region which I didn't have to do previously:

`awslocal sqs create-queue --queue-name XYZ --region=eu-west-1`

**Comment by nickzoic** [comment] 2021-08-25 05:06
It seems like if I run `aws s3 cp $file s3://$bucketname` with the right bucket name but the wrong region, the copy succeeds but the sqs notification for the new file then fails with:

```
Unable to send notification for S3 bucket "my-bucket" to SQS queue "arn:aws:sqs:ap-southeast-1:000000000000:my-queue": An error occurred (QueueDoesNotExist) when calling the SendMessage operation: The specified queue does not exist for this wsdl version.
```

The names in the error message are correct, and both the bucket and the queue were created in ap-southeast-1, but in this case I pushed the file in with `aws s3 cp --region ap-southeast-2` ... should this matter? The file successfully gets added to the bucket, but the notification logs the error.

**Comment by whummer** [comment] 2021-10-03 21:36
Thanks for the update @nickzoic @chopstik @WtfJoke @mcshiz @mikehroth . From what I understand from the last comments in this thread, this appears to have been a region mismatch issue. 

Please note that we've recently added multi-region support - in the past, all resources were created in a single region (configured in the LocalStack instance), whereas now the region is determined from the client which initiates the API call.

Hope that helps - please let us know if there are any other issues or if this particular problem persists. Thanks for your help!

**Closed by whummer** 2021-10-03 21:37 UTC
Labels: evaluate-or-close

**Comment by nickzoic** [comment] 2021-10-03 21:46
I'm not sure that localstack's multi-region behaviour correctly emulates real AWS behaviour in this case.
I think `aws s3 cp ...` works the same regardless of which `--region` it is given, and the notification is generated *in the region in which the bucket was defined*.
I'll check this and let you know.
