### ISSUE TITLE
Can't start Kinesis using localstack on docker with latest version

### ISSUE THREAD

**Issue by ajgrayson** [localstack/localstack#1678] opened 2019-10-23 15:13 UTC
I started to get this issue on the latest version of localstack from the docker registry. Forcing back to the 0.10.3 version resolved the issue.

```
$ docker-compose up --build --force-recreate localstack
Recreating rae_localstack_1 ... done
Attaching to rae_localstack_1
localstack_1           | Waiting for all LocalStack services to be ready
localstack_1           | 2019-10-23 14:52:28,362 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can
set user=root in the config file to avoid this message.
localstack_1           | 2019-10-23 14:52:28,365 INFO supervisord started with pid 13
localstack_1           | 2019-10-23 14:52:29,367 INFO spawned: 'dashboard' with pid 19
localstack_1           | 2019-10-23 14:52:29,369 INFO spawned: 'infra' with pid 20
localstack_1           | 2019-10-23 14:52:29,373 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1           | (. .venv/bin/activate; bin/localstack web)
localstack_1           | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1           | 2019-10-23 14:52:30,375 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1           | 2019-10-23T14:52:32:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.6/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
localstack_1           | Starting local dev environment. CTRL-C to quit.
localstack_1           | Starting mock Lambda service (http port 4574)...
localstack_1           | Starting mock Kinesis (http port 4568)...
localstack_1           | Starting mock CloudWatch Logs (http port 4586)...
localstack_1           | internal/modules/cjs/loader.js:797
localstack_1           | throw err;
localstack_1           | ^
localstack_1           |
localstack_1           | Error: Cannot find module 'leveldown'
localstack_1           | Require stack:
localstack_1           | - /opt/code/localstack/localstack/node_modules/kinesalite/db/index.js
localstack_1           | - /opt/code/localstack/localstack/node_modules/kinesalite/index.js
localstack_1           | - /opt/code/localstack/localstack/node_modules/kinesalite/cli.js
localstack_1           | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
localstack_1           | at Function.Module._load (internal/modules/cjs/loader.js:687:27)
localstack_1           | at Module.require (internal/modules/cjs/loader.js:849:19)
localstack_1           | at require (internal/modules/cjs/helpers.js:74:18)
localstack_1           | at Object.create (/opt/code/localstack/localstack/node_modules/kinesalite/db/index.js:31:35)
localstack_1           | at kinesalite (/opt/code/localstack/localstack/node_modules/kinesalite/index.js:24:26)
localstack_1           | at Object.<anonymous> (/opt/code/localstack/localstack/node_modules/kinesalite/cli.js:29:35)
localstack_1           | at Module._compile (internal/modules/cjs/loader.js:956:30)
localstack_1           | at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
localstack_1           | at Module.load (internal/modules/cjs/loader.js:812:32) {
localstack_1           | code: 'MODULE_NOT_FOUND',
localstack_1           | requireStack: [
localstack_1           | '/opt/code/localstack/localstack/node_modules/kinesalite/db/index.js',
localstack_1           | '/opt/code/localstack/localstack/node_modules/kinesalite/index.js',
localstack_1           | '/opt/code/localstack/localstack/node_modules/kinesalite/cli.js'
localstack_1           | ]
localstack_1           | }
localstack_1           | 2019-10-23T14:52:32:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_1           | Waiting for all LocalStack services to be ready
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-131) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2019-10-24 21:01
Thanks for reporting @ajgrayson . I haven't been able to reproduce this issue - looks like a transient issue where one of the dependencies couldn't be installed correctly.

Can you please give it a try with the latest version? If the problem persists, please post your docker-compose file for easier reproducibility. Thanks!

**Comment by whummer** [comment] 2021-02-23 17:01
Closing as "cannot reproduce" - please report here with steps to reproduce if the problem persists. Thanks!

**Closed by whummer** 2021-02-23 17:01 UTC
Labels: bug, cannot-reproduce, installation
