### ISSUE TITLE
Go and Python Lambda Support

### ISSUE THREAD

**Issue by HoneyryderChuck** [localstack/localstack#602] opened 2018-02-07 15:54 UTC
I've installed the docker image of localstack, and been trying with deploying a lambda function. Both of my tries failed: a Go lambda function, and a Python. I think they failed for different reasons, as Go seems not to be supported.

Is support for Go on the works? And why are Python lambdas not deployable?

**Comment by whummer** [comment] 2018-02-11 17:47
Thanks for reporting @HoneyryderChuck . Regarding Go support, this is a duplicate of #561. Let's continue the discussion on that ticket.

> And why are Python lambdas not deployable?

Can you provide more details, how exactly are you starting localstack, what is your environment setup, which error message are you getting? Please provide a fully reproducible, minimal example.

**Comment by whummer** [comment] 2019-08-25 20:13
Closing this issue as outdated/fixed. Please open a follow-up issue if the problem persists. Thanks

**Closed by whummer** 2019-08-25 20:13 UTC
Labels: bug, duplicate, needs-triaging
