### ISSUE TITLE
Localstack appears to non-deterministically persist data

### ISSUE THREAD

**Issue by b3ross** [localstack/localstack#378] opened 2017-10-06 20:49 UTC
I'm running localstack as part of our python tests.  I follow the pattern of starting the infrastructure, async, on start, and tearing it down at the end.

On occasion, the infrastructure will persist state and not clean up on `infra_stop()`.  The symptom that I'm experiencing is that creating a bucket in s3 will fail on a subsequent run because the bucket already exists.

This is happening on a Mac OS laptop - restarting the computer solves this problem, but I have yet to be able to find the location of the data files.  `DATA_DIR` is not set, and I cannot find any trace of the data on my drive.

This problem has been reproduced on a colleague's computer.

**Comment by whummer** [comment] 2017-10-08 04:29
Thanks for reporting @mellocello2003 . This appears to be a duplicate of and/or related to #166.

When we talk about "persistent" data in LocalStack, we are referring to data that is persisted to *disk*. The purpose of `DATA_DIR` is to have persistent data that survives restarts of LocalStack (or even restarts of your machine).

What you're experiencing appears to be state that is kept in *memory*, rather than on disk. Actually, `stop_infra()` should cause the underlying mock services to be terminated. Specifically, the mock services are started as separate processes, and `stop_infra()` kills those processes, which should also clear their state. I'd be surprised if the behavior is really non-deterministic, but we will need some more details about your use case to debug this further. Can you please provide a self-contained test case which exhibits this behavior? Thanks

**Comment by mellocello2003** [comment] 2017-10-10 14:01
@whummer, all I'm doing is something very simple - just spinning up localstack within a test via `infra.start_infra(async=True)`, creating a bucket via `s3client` against `localhost`, and then stopping localstack via `infra.stop_infra()`.

The behavior basically is as follows:
- I run the test a number of times, successfully.
- Eventually the test starts failing because the bucket already exists.
- I restart my computer, and things start working again.

So if it starts up separate processes, it's possible that the processes are not actually dying?  What are the processes called?

It almost seems like the smarter thing to do here is to just start localstack in docker up as part of your entire test run (as opposed to inside each test) and stop it at the end.  That way it's probably cleaner given that we're dealing with actual processes - though it unfortunately is a little less convenient.

**Comment by mellocello2003** [comment] 2017-10-11 01:04
As far as I can tell, the problem is that if I SIGINT the running test, then restart it, the problem occurs.  There are definitely zombie processes - stuff like `moto server`.  The bug is that running `stop_infra()` doesn't indiscriminately kill the running processes after a SIGINT.  Ideally I would be able to call `stop_infra()` and it would kill leftover zombie processes.

**Comment by n8sty** [comment] 2018-06-18 15:46
I'm having a similar/same problem with an almost identical workflow. A demonstration:

```
In [5]: infra.start_s3(port=port, async=True)
Starting mock S3 (http port 4567)...
Out[5]: <ShellCommandThread(Thread-416, started daemon 139849349900032)>

In [6]: infra.stop_infra()

In [7]: infra.start_s3(port=port, async=True)
Starting mock S3 (http port 4567)...
Out[7]: <ShellCommandThread(Thread-483, started daemon 139849349900032)>

Exception running proxy on port 4567: [Errno 98] Address already in use Traceback (most recent call last):
  File "/home/nate/.local/share/virtualenvs/eventable-Oy9s0l8M/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 284, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/home/nate/.pyenv/versions/3.6.5/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/home/nate/.pyenv/versions/3.6.5/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/nate/.pyenv/versions/3.6.5/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by whummer** [comment] 2019-08-25 18:59
Closing as outdated / obsolete. Please create a follow-up issue if the problem persists.

**Closed by whummer** 2019-08-25 18:59 UTC
Labels: needs-triaging, question
