### ISSUE TITLE
bug: secretsmanager get-secret-value can't find value for existing secret

### ISSUE THREAD

**Issue by afbarbaro** [localstack/localstack#4669] opened 2021-09-29 20:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't retrieve value for any secret stored in `Secrets Manager`.  A `ResourceNotFoundException` is thrown.

### Expected Behavior

Should be able to retrieve secret values

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ aws --endpoint-url=http://localhost:4566 secretsmanager create-secret --name testSecret

$ aws --endpoint-url=http://localhost:4566 secretsmanager describe-secret --secret-id testSecret

$ aws --endpoint-url=http://localhost:4566 secretsmanager get-secret-value --secret-id testSecret
```

![image](https://user-images.githubusercontent.com/18277423/135340094-090025ce-01e8-479b-acb1-dd5135a6accc.png)

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

### Anything else?

Another user reported this problem in this (related but not the same, and closed) issue.
https://github.com/localstack/localstack/issues/1002#issuecomment-906285490

**Comment by mgagliardo** [comment] 2021-09-29 22:20
I can see you already closed the issue but just in case, this is the expected behaviour for an actual secret in AWS as well. Response from an actual command ran against AWS:

```
$ aws --profile test --region us-east-1  secretsmanager get-secret-value --secret-id testSecret

An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret value for staging label: AWSCURRENT
```

**Comment by afbarbaro** [comment] 2021-09-29 22:34
Thanks @mgagliardo.  I can confirm that the error is not happening if the secret is created with a value:

```
$ aws --endpoint-url=http://localhost:4566 secretsmanager create-secret --name testSecret --secret-string 'secret'
```

I'm going to dig in a bit more because I'm having an issue with a secret created via `cdklocal`, which should have a value, but it's yielding this error.

**Comment by mgagliardo** [comment] 2021-09-29 23:35
Ok, once you have reproduced the issue please let us know, I'll close the issue for now as the reported bug is actually not a bug but an expected response. Same happens on AWS if the secret is created with no value.

**Closed by mgagliardo** 2021-09-29 23:35 UTC
Labels: bug, needs-triaging

**Comment by brfrugis** [comment] 2022-09-30 17:41
Having that same error here ....
by checking the secret with aws-cli I can see the tag AWSCURRENT but even though I'm facing that error iwth Java en Python apps .....
Any idea ?

**Comment by endrig0** [comment] 2022-11-30 18:27
> Having that same error here .... by checking the secret with aws-cli I can see the tag AWSCURRENT but even though I'm facing that error iwth Java en Python apps ..... Any idea ?

same error here still. Any workarond?

**Comment by Octtavius** [comment] 2023-04-14 09:11
Any updates on this issue ? I am facing the same

**Comment by eyal-solomon1** [comment] 2023-09-27 13:01
@endrig0 @Octtavius 
Had the same issue - for me it was the secret was empty ..
