### ISSUE TITLE
Simple ECS task runs to completion under AWS but container gets aborted under Localstack

### ISSUE THREAD

**Issue by jim-meyer** [localstack/localstack#9893] opened 2023-12-16 21:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I deployed a simple ECS task that simple logs a line ever 1/2 second and it runs for 25 seconds. I can deploy the ECS task to AWS and it works fine. Deploying the same SAM template using localstack results in the container running for a few seconds then being terminated; most of the lines that should have got logged do not appear.

### Expected Behavior

Deploying an ECS task that works in AWS should work in localstack (pro) too

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Fully reproducible example including SAM templates, python code is (here)[https://github.com/jim-meyer/minimal-ecs-task/tree/main]. The `README.md` contains the following information to reproduce the problem but it included here as well:

# minimal-ecs-task

A project containing a bare minimum ECS task that demonstrates unexpected termination of ECS task under Localstack.

This repo's ECS task simply logs some messages periodically for ~25 seconds then exits. The following ECS task code is from [here](./src/task.py):

```python
import logging
import time

logger = logging.getLogger()


if __name__ == '__main__':
    try:
        logger.warning('*** Entering ECS container entrypoint src/task.py')

        # Simulate something happening for a while
        for i in range(50):
            logger.warning(f'*** sleep loop {i}')
            time.sleep(0.5)

        logger.warning('*** Exiting ECS container entrypoint src/task.py')
    except:     # noqa
        logger.exception('*** Exception raised in src/task.py')
        raise
    finally:
        # Now make sure logs get flushed
        logging.shutdown()
```

When this ECS task is run in **AWS it works** as expected.
When it is run under **Localstack Pro it fails**.

# Repo Setup

Create a python virtual environment then run this to install python packages needed by this repo:

```bash
python -m venv ~/envs/minimal-ecs-task
make one_time_setup
source ~/envs/minimal-ecs-task/bin/activate
```

# Deploy to AWS and Test

```bash
AWS_ACCOUNT_ID=<<<fill this this in>>>
AWS_REGION=us-east-2
make deploy_aws
make run_task_aws
```

Look at the ECS Task logs in the AWS console (https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/minimal-ecs-task-cluster/tasks/).
The logs will show something like this:

```
December 16, 2023, 14:22 (UTC-6:00)	*** Exiting ECS container entrypoint src/task.py	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 49	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 48	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 47	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 46	ecs_task_container
... some lines removed for brevity
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 4	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 3	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 2	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 1	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** Entering ECS container entrypoint src/task.py	ecs_task_container
December 16, 2023, 14:22 (UTC-6:00)	*** sleep loop 0	ecs_task_container
```

The key is the `*** Entering ECS container entrypoint` and `*** Exiting ECS container entrypoint` log lines.
This shows that the ECS task runs to completion when run in AWS.

# Deploy to Localstack and Test

In one terminal window:

```bash
make deploy_local
```

This allows one to see the Localstack logs while the test gets run in another terminal window.

In another terminal window run the test against Localstack:

```bash
make run_task_local
```

Notice that this last command fails after only a few seconds:

```
(minimal-ecs-task) jmp:minimal-ecs-task bash$ make run_task_local
python src/run_task.py --localstack
Error detected while polling task on cluster minimal-ecs-task-cluster: MISSING
Traceback (most recent call last):
  File "/Users/jimmeyer/projects/minimal-ecs-task/src/run_task.py", line 48, in <module>
    run_ecs_task('ecs_task_container', args.localstack)
  File "/Users/jimmeyer/projects/minimal-ecs-task/src/run_task.py", line 34, in run_ecs_task
    runner.start_container(task_name,
  File "/Users/jimmeyer/projects/minimal-ecs-task/src/ecs_container_runner.py", line 85, in start_container
    while not self.task_completed(ecs_cluster_name, task_id):
  File "/Users/jimmeyer/projects/minimal-ecs-task/src/ecs_container_runner.py", line 35, in task_completed
    raise ContainerStartFailedException(error_msg)
ecs_container_runner.ContainerStartFailedException: Error detected while polling task on cluster minimal-ecs-task-cluster: MISSING
make: *** [run_task_local] Error 1
```

Doing `docker ps -a` will show the ECS task container that was just run since `localstack start` was done with `ECS_REMOVE_CONTAINERS=0`:

```
(minimal-ecs-task) jmp:minimal-ecs-task bash$ docker ps -a
CONTAINER ID   IMAGE                                                       COMMAND                  CREATED              STATUS                          PORTS                                                                                                    NAMES
d21b2edc0f04   localhost.localstack.cloud:4511/ecs_task_container:latest   "python3 /var/task/m…"   About a minute ago   Exited (0) About a minute ago                                                                                                            ls_ecs_minimal-ecs-task-cluster_c36c2f2c-8eba-4d20-809b-aae84742cad4_0_45bba564
7f21dc35ce3b   localstack/localstack-pro:latest                            "docker-entrypoint.sh"   28 minutes ago       Up 28 minutes (healthy)         127.0.0.1:443->443/tcp, 127.0.0.1:4510-4560->4510-4560/tcp, 53/tcp, 5678/tcp, 127.0.0.1:4566->4566/tcp   localstack-main
4dc73884d66e   localstack/localstack                                       "sh -c 'echo test123'"   28 minutes ago       Created                                                                                                                                  elated_bohr
```

Finally, look at the logs for that ECS task's container:

```
docker logs d21b2edc0f04
```

You'll see something like:

```
*** Entering ECS container entrypoint src/task.py
*** sleep loop 0
*** sleep loop 1
*** sleep loop 2
*** sleep loop 3
*** sleep loop 4
*** sleep loop 5
*** sleep loop 6
*** sleep loop 7
*** sleep loop 8
*** sleep loop 9
*** sleep loop 10
*** sleep loop 11
*** sleep loop 12
*** sleep loop 13
*** sleep loop 14
*** sleep loop 15
*** sleep loop 16
*** sleep loop 17
*** sleep loop 18
*** sleep loop 19
*** sleep loop 20
*** sleep loop 21
*** sleep loop 22
*** sleep loop 23
*** sleep loop 24
*** sleep loop 25
*** sleep loop 26
(minimal-ecs-task) jmp:minimal-ecs-task bash$ 
```

Notice that there is no `*** Exiting ECS container entrypoint` log line. For some reason the container was terminated after
about 13 seconds which is the 26th time through the "sleep for 1/2 second" loop in `./src/task.py`.

So this simple ECS task runs fine in AWS. But fails under Localstack.

# Environment

## Localstack Version Info

```
(minimal-ecs-task) jmp:minimal-ecs-task jimmeyer$ localstack --version
3.0.2
```

## Python Package Version Info

Python version:

```
(minimal-ecs-task) Jims-MacBook-Pro:minimal-ecs-task jimmeyer$ python -V
Python 3.9.2
```

AWS related pip packages in use:

```
pip list | grep aws

aws-lambda-builders       1.43.0
aws-sam-cli               1.105.0
aws-sam-cli-local         1.68.0
aws-sam-translator        1.82.0
awscli                    1.32.2
awscli-local              0.21.1
awscliv2                  2.2.0
```

Localstack related pip packages in use:

```
pip list | grep local


localstack                3.0.2
localstack-client         2.5
localstack-core           3.0.2
localstack-ext            3.0.2
```

## Docker Version Info

```
docker version

Client:
Cloud integration: v1.0.35+desktop.5
Version:           24.0.6
API version:       1.43
Go version:        go1.20.7
Git commit:        ed223bc
Built:             Mon Sep  4 12:28:49 2023
OS/Arch:           darwin/amd64
Context:           desktop-linux

Server: Docker Desktop 4.25.2 (129061)
Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     true
containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Environment

```markdown
- OS: MacOS 12.7.1
- LocalStack:3.0.2
- Localstack Pro docker image: localstack/localstack-pro@sha256:3e6163adcba5994155326cabde8a21c135b6ec95f54bb4421597ecf232359720
```

### Anything else?

Fully reproducible example is at https://github.com/jim-meyer/minimal-ecs-task/tree/main.

**Comment by simonrw** [comment] 2024-04-17 14:12
Hi @jim-meyer could you pull the latest docker image and try again please? We have made numerous improvements to ECS since you submitted this issue. 

I cannot reproduce this error on my side. The container runs to completion.

**Comment by simonrw** [comment] 2024-04-26 09:50
As I cannot reproduce this problem, I am going to close this issue. Please feel free to re-open and comment again if you are still experiencing problems.

**Closed by simonrw** 2024-04-26 09:50 UTC
Labels: type: bug, area: integration/sam, aws:ecs, status: backlog
