### ISSUE TITLE
Unable to find forwarding rule for host - SQS

### ISSUE THREAD

**Issue by MatthewEdge** [localstack/localstack#2478] opened 2020-05-30 01:11 UTC
# Type of request: This is a ...
[x ] bug report
[ ] feature request

# Detailed description
When attempting to run in a Docker environment with Spring Cloud AWS Messaging - getting a 404 on the application side and `INFO:localstack.services.edge: Unable to find forwarding rule for host "awslocal:4566", path "/", target header "", auth header ""` on Localstack container. 

Using the following docker-compose entry:

```
localstack:
    image: localstack/localstack:0.11.2
    container_name: awslocal
    hostname: awslocal
    environment:
      SERVICES: "sqs,sns"
      HOST_TMP_FOLDER: /tmp/localstack
      HOSTNAME_EXTERNAL: awslocal
    ports:
      - "4566:4566"
      - "8055:8080"
    volumes:
      - "./.localstack:/tmp/localstack"
```

## Expected behavior
Application can listen to SQS messages on the `test` queue created externally with AWS CLI:

```
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/queue/test"
}

aws --endpoint-url=http://localhost:4566 sns create-topic --name test
{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:test"
}

aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:000000000000:test
{
    "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:test:de195743-b616-4c13-8539-fe17d8e00084"
}

aws --endpoint-url=http://localhost:4566 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:test --message "TEST"
```

## Actual behavior
Application fails with a 404 on this log line:

```
app_1         |  2020-05-30 01:02:36.955 DEBUG 6 --- [           main] com.amazonaws.request                    : Sending Request: POST http://awslocal:4566 / Parameters: ({"Action":["GetQueueUrl"],"Version":["2012-11-05"],"QueueName":["test"]}Headers: (User-Agent: aws-sdk-java/1.11.415 Linux/4.19.76-linuxkit OpenJDK_64-Bit_Server_VM/11.0.7+10 java/11.0.7, amz-sdk-invocation-id: 1ae4996f-7f4e-509a-0ee1-a5a7d7d274a0, )
app_1         | 2020-05-30 01:02:37.214 DEBUG 6 --- [           main] com.amazonaws.request                    : Received error response: com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 404; Error Code: 404 Not Found; Request ID: null)
app_1         |  2020-05-30 01:02:37.220  WARN 6 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMessageListenerContainer' defined in class path resource [org/springframework/cloud/aws/messaging/config/annotation/SqsConfiguration.class]: Invocation of init method failed; nested exception is com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 404; Error Code: 404 Not Found; Request ID: null)
app_1         |  2020-05-30 01:02:37.224  INFO 6 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
app_1         |  2020-05-30 01:02:37.225  INFO 6 --- [           main] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
app_1         |  2020-05-30 01:02:37.233  INFO 6 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
app_1         |  2020-05-30 01:02:37.235  INFO 6 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
app_1         |  2020-05-30 01:02:37.249  INFO 6 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
app_1         |  2020-05-30 01:02:37.253  INFO 6 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
app_1         |  2020-05-30 01:02:37.271  INFO 6 --- [           main] ConditionEvaluationReportLoggingListener :
app_1         |
app_1         | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
app_1         |  2020-05-30 01:02:37.278 ERROR 6 --- [           main] o.s.boot.SpringApplication               : Application run failed
app_1         |  com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 404; Error Code: 404 Not Found; Request ID: null)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1660)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1324)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
app_1         | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2147)
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2116)
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2105)
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1138)
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1110)
```

# Steps to reproduce
A demo repository is here: https://github.com/MatthewEdge/boot-sqs-test

Relevant client code:

```
@SpringBootApplication
@Slf4j
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

  @SqsListener("test")
  public void receiveMessage(@NotificationMessage String message, @Payload String payload) {
    log.info(payload);
    log.info(message);
  }

  @Value("${cloud.aws.endpoint.uri}")
  private String endpointUrl;

  @Value("${cloud.aws.region.static}")
  private String region;

  private AWSCredentialsProvider credentialsProvider() {
      return new AWSStaticCredentialsProvider(new AnonymousAWSCredentials());
  }

  private EndpointConfiguration endpointConfiguration() {
    log.info("Using endpoint: " + endpointUrl);
    log.info("Region: " + region);
    return new AwsClientBuilder.EndpointConfiguration(endpointUrl, region);
  }

  @Bean
  public AmazonSQS amazonSQS() {
    return AmazonSQSAsyncClientBuilder.standard()
        .withCredentials(credentialsProvider())
        .withEndpointConfiguration(endpointConfiguration())
        .build();
  }
}
```

## Command used to start LocalStack
```
docker-compose up -d localstack
docker-compose up --build app
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-190) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-06-01 08:19
Thanks for the detailed report @MatthewEdge . This should be fixed in #2489 - can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks

**Comment by MatthewEdge** [comment] 2020-06-01 11:17
Can confirm this fixed the issue! Thank you very much!

**Comment by jmisharp** [comment] 2020-08-11 07:36
I still experience this even with the `latest` and `2.3` localstack docker version.

Using the following docker-compose file:
```yml
version: "3.4"

services: 
  localstack:
    image: localstack/localstack
    networks:
      default:
        aliases:
          - localstack
    volumes: 
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    hostname: localstack
    environment:
      - SERVICES=${SERVICES-dynamodb,elasticsearch,sns,sqs,s3}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST="unix:///var/run/docker.sock"
      - HOST_TMP_FOLDER=${TMPDIR-/tmp/localstack}
      - AWS_DEFAULT_REGION=eu-west-1
      - DEFAULT_REGION=${AWS_DEFAULT_REGION-eu-west-1}
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
```

When calling the SQS queue from code, I get an exception from the SDK:
`Amazon.SQS.AmazonSQSException : The specified queue does not exist for this wsdl version.`

The docker-compose logs looks like this:
```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-08-11 07:20:27,557 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2020-08-11 07:20:27,565 INFO supervisord started with pid 13
localstack_1  | 2020-08-11 07:20:28,570 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2020-08-11 07:20:28,574 INFO spawned: 'infra' with pid 20
localstack_1  | 2020-08-11 07:20:28,591 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2020-08-11 07:20:28,592 INFO exited: dashboard (exit status 0; expected)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | 2020-08-11 07:20:29,595 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | LocalStack version: 0.11.3
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Starting edge router (https port 4566)...
localstack_1  | Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
localstack_1  | 2020-08-11T07:20:43:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | Running on 0.0.0.0:4566 over https (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4569 over http (CTRL + C to quit)
localstack_1  | Starting mock S3 service on http ports 4566 (recommended) and 4572 (deprecated)...
localstack_1  | 2020-08-11T07:20:43:INFO:localstack.multiserver: Starting multi API server process on port 52767
localstack_1  | Running on 0.0.0.0:4572 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:52767 over http (CTRL + C to quit)
localstack_1  | Starting mock SNS service on http ports 4566 (recommended) and 4575 (deprecated)...
localstack_1  | Starting mock SQS service on http ports 4566 (recommended) and 4576 (deprecated)...
localstack_1  | Running on 0.0.0.0:4575 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4576 over http (CTRL + C to quit)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-08-11T07:20:51:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | Ready.
localstack_1  | 2020-08-11T07:22:20:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack:4566", path "/*", target header "", auth header "", data "b''"
localstack_1  | 2020-08-11T07:22:22:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | 2020-08-11T07:22:26:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack:4566", path "/*", target header "", auth header "", data "b''"
```

The last log line is printed every time the code is trying to call the SQS queue in localstack:
`localstack_1  | 2020-08-11T07:22:26:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack:4566", path "/*", target header "", auth header "", data "b''"`

**Comment by jmisharp** [comment] 2020-08-11 10:40
It seems to be working if I use the `0.11.2` docker tag, so it's an issue for the `latest` and `0.11.3` versions.

**Comment by kazeshini178** [comment] 2020-08-26 20:42
Seems to also fail on `0.11.4` can see the queues when running CLI command `aws sqs list-queues --endpoint-url http://localhost:4566` but cant seem to access the from any other service.

Kinda sucks as `0.11.4` seems to have a fix for an issue that come with the lasted docker lambda containers (`lambci/lambda:nodejs12.x`) is there anyway to possibly specify an older version of the lambda containers for localstack to use?

**Comment by jkatnik** [comment] 2020-09-17 14:15
Problem still present on latest i.e. 0f5677599463

**Comment by andreas-bergstrom** [comment] 2020-09-18 05:34
Get this error when running 0.11.5 through pip. Can't use the Pro features...

**Comment by fernando-martin** [comment] 2020-09-22 08:50
Error still present on latest.

**Comment by whummer** [comment] 2020-09-23 16:08
Thanks for the updates @kazeshini178 @jkatnik @andreas-bergstrom @fernando-martin . Can you please provide some details (configuration, test code, error logs, ...) about your respective use cases?

I'm assuming that the `Unable to find forwarding rule for host ...` error has been fixed now, or are you still experiencing it with `latest`?

As far as the `NonExistentQueue` error is concerned, there could be several root causes - most likely either (1) a region mismatch, or (2) an issue with the host name encoded in the queue URL.

If you can provide some more details to help us reproduce this issue, that would be much appreciated. Thanks!

**Comment by kazeshini178** [comment] 2020-10-02 12:48
Hi @whummer, It seems the latest version (0.11.5) of localstack fixed the issue I was having with SQS and Lambda's.

Sadly though it seems to have caused an issues with creating cloudwatch alarms that trigger based on SQS DLQ's, but thanks for the 0.11.5 update 😃

**Closed** 2020-12-08 15:58 UTC
Labels: configuration, needs-triaging, should-be-fixed

**Comment by ravithejappl** [comment] 2021-01-03 20:39
I am getting this error on localstack 0.12.4

**Comment by anushacassum** [comment] 2021-01-06 08:43
> I am getting this error on localstack 0.12.4

Me too

**Comment by ravithejappl** [comment] 2021-01-06 14:45
If you are using dynamodb use endpoint as below

options = { endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:4566`, };

**Comment by Abolurah** [comment] 2021-01-18 12:18
LocalStack version: 0.12.5

localstack_main | 2021-01-18T11:52:44:INFO:localstack.services.edge: **Unable to find forwarding rule for host** "localhost:4566", path "GET /favicon.ico", target header "", auth header "", data "b''"

In my case, I'm trying to simulate AWS S3 service

So gays, what will the resolution? if any at all?

**Comment by jedielson** [comment] 2021-05-06 15:02
Having this with s3 api on localstack 0.12.6

```
2021-05-06T15:01:14:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /movidesk-email-received?list-type=2&prefix=webhooks%2Fnotify%2FPENBRGhCUVYydV8tWVp0NjhvSC1VYnlvX2M2Q0RiS0YwbW0yVHE1UHZWajRpOWUxSj00Z0BtYWlsLmdtYWlsLmNvbT4%3D", target header "", auth header "", data "b''"
```

**Comment by jedielson** [comment] 2021-05-06 15:04
Having this with s3 api on localstack 0.12.6

```
2021-05-06T15:01:14:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /core-email-received?list-type=2&prefix=webhooks", target header "", auth header "", data "b''"
```

**Comment by Jay3118** [comment] 2022-09-05 17:13
I face the same issue with 0.17.4. The error is amazon.SQS.AmazonSQSException : The specified queue does not exist for this wsdl version. This error occur when I add the --no-sign-request flag. If I did not have the --no-sign-request flag, it works great.
