### ISSUE TITLE
Is it possible to use the same account id in generated arns for both iam and stepfunctions mocks?

### ISSUE THREAD

**Issue by emilycoco** [localstack/localstack#1173] opened 2019-03-06 02:15 UTC
I'm really appreciating localstack for developing against AWS, it's extremely helpful. I am having a small issue where different aws service mocks use different account ids in generated arns, such as "arn:aws:iam::123456789012:role/my-role" vs "arn:aws:iam::000000000000:role/my-role".

 I don't actually care what that account id is for local development, but it would be much easier to work with docker environment variables for account id if they were the same dummy id across services, as account id will be the same in a deployed scenario. Is there a way to set account id to be the same?

**Comment by whummer** [comment] 2019-03-06 18:41
Thanks for reporting @emilycoco . The account ID should generally be `000000000000` - this looks like a bug. Can you please provide a small example to reproduce this issue? How are your resources getting created - using API calls, or using CloudFormation, or the Serverless framework?

**Comment by emilycoco** [comment] 2019-03-06 19:26
stepfunctions uses 000000000000 as expected, but iam generates a role with another id. to reproduce:
Using docker-compose, with s3, iam, and stepfunctions services enabled, start container:
`TMPDIR=/private${TMPDIR} docker-compose up`

Use aws cli to create an iam role:
`aws --endpoint-url "http://localhost:4593" --region us-east-1 iam create-role --role-name states-execution-role --path /  --assume-role-policy-document file:./test-role-policy.json`

Contents of test-role-policy.json file:
`
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "ec2.amazonaws.com",
          "states.us-east-1.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}`

Output:
`{
    "Role": {
        "Path": "/",
        "RoleName": "states-execution-role",
        "RoleId": "1qyj18rq3jjb7gsu3ysm",
        "Arn": "arn:aws:iam::123456789012:role/states-execution-role",
        "CreateDate": "2012-05-08T23:34:01.495Z",
        "AssumeRolePolicyDocument": "file:./test-role-policy.json"
    }
}`

**Comment by whummer** [comment] 2019-03-08 01:19
Should be fixed in #1174 - please re-open this issue if the problem persists. Thanks

**Closed by whummer** 2019-03-08 01:19 UTC
Labels: bug
