### ISSUE TITLE
bug: Lambda/Kinesis Event Mapping event deserialization failure with dotnet6 Function invocation

### ISSUE THREAD

**Issue by shooresh-golzari-cko** [localstack/localstack#6355] opened 2022-06-27 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a bug that I have encountered after upgrading Localstack from 0.12.12 to 0.14.3 in order to make use of the dotnet6 mock-Lambda provider.

1. Put record onto Kinesis Stream with base64 encoded payload either programmatically with `AWSSDK.Kinesis` or with the CLI
2. Lambda Invoked (using either Localstack Kinesis Provider) by Lambda Event Mapping
3. Kinesis Event Deserialization error from both `System.Text` and `NewtonSoft` Amazon json deserializers - per below exception. Below is System.Text (a little more informative)

```
Amazon.Lambda.Serialization.SystemTextJson.JsonSerializerException: Error converting the Lambda event JSON payload to type Amazon.Lambda.KinesisEvents.KinesisEvent: Value to add was out of range. (Parameter 'value')
 ---> System.ArgumentOutOfRangeException: Value to add was out of range. (Parameter 'value')
   at System.DateTime.<Add>g__ThrowOutOfRange|75_0()
   at System.DateTime.Add(Double value, Int32 scale)
   at System.DateTime.AddSeconds(Double value)
   at Amazon.Lambda.Serialization.SystemTextJson.Converters.DateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.InternalDeserialize[T](Byte[] utf8Json)
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   --- End of inner exception stack trace ---
   at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method1(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 56
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176
```

### Expected Behavior

1. Put record onto Kinesis Stream with base64 encoded json string payload -  either programmatically with `AWSSDK.Kinesis` or with the CLI
2. Lambda Invoked (using either Localstack Kinesis Provider) by Lambda Event Mapping
3. Kinesis Event deserialized without error by AWS Lambda deserializer and processed by function logic.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker compose -f docker-compose.local.yml up --build --remove-orphans`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Docker Compose file:

```yml
version: '3.9'

services:
  localstack:
    image: localstack/localstack:0.14.3
    environment:
      - EDGE_PORT=4584
      - SERVICES=kinesis,lambda
      - DEFAULT_REGION=eu-north-1
      - USE_SINGLE_REGION=1
      - KINESIS_INITIALIZE_STREAMS=live-stream:1:eu-north-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=localstack-network
    volumes:
      - ./content/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
      - ./content/setup:/setup
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4584:4584
    networks:
      - localstack-network

networks:
  localstack-network:
    name: localstack-network
    driver: bridge
```

Lambda Script
```
awslocal lambda create-function \
    --region $DEFAULT_REGION \
    --function-name live-lambda \
    --runtime dotnet6 \
    --handler Live.Lambda::Live.Lambda.Function::HandleAsync \
    --memory-size 512 \
    --zip-file fileb:///app.zip
    --role arn:aws:iam::123456:role/irrelevant \
    --environment "Variables={DOTNET_ENVIRONMENT=localdocker}" \
    --timeout 900
```
Mapping Script
```
awslocal lambda create-event-source-mapping \
    --event-source-arn arn:aws:kinesis:$DEFAULT_REGION:000000000000:stream/live-stream \
    --function-name live-lambda \
    --batch-size 200 \
    --starting-position LATEST
    --maximum-retry-attempts 2
```

### Create and install dotnet Lambda app

```
dotnet new --install Amazon.Lambda.Templates && dotnet new lambda.Kinesis --name Live.Lambda
dotnet tool install -g Amazon.Lambda.Tools && dotnet lambda package
```

```
dotnet-lambda package \
    -pl "./src/Live.Lambda" \
    --output-package "Live.Lambda.Host.Lambda.zip" \
    --configuration Debug

awslocal lambda update-function-code \
    --function-name "live-lambda" \
    --zip-file "fileb://Live.Lambda.Host.Lambda.zip" \
    --endpoint-url "http://localhost:4584" \
    --region "eu-north-1"
```

### Put Record on Stream
Test Json payload to be encoded: `[{\"Name\" :  \"Mongo\", \"Surname\" : \"McLeod\" }]`

```
awslocal kinesis put-records --stream-name live-stream --records Data=<encoded-json-payload> --endpoint-url http://localhost:4584 --region eu-north-1
```

### Environment

```markdown
- OS: Windows 10 (with PS or WSL)
- LocalStack:0.14.3
```

### Anything else?

1. Localstack Kinesis Stream contains expected records using an iterator to get.
2. Function can be invoked directly with same payload
3. The localstack set-up is an exact mirror of AWS proper (which works)
4. Best guess is that the issue is rooted in the event mapping resource as other components work individually and exact same setup worked with 0.12.12 using dotnetcore3.1

**Comment by douglasgpertile** [comment] 2022-08-29 09:51
Hi, I'm having the same issue when triggering a .net lambda with DynamoDB streams.

I've updated from localstack 0.12.11 to the latest version and the same issue related by @shooresh-golzari-cko happened. 
After some investigating I found that the problem seems to be on the `ApproximateCreationDateTime` on the DynamoDB event, which is created with 13 digits instead of 10 (milliseconds instead of seconds) that is the cause of the `ArgumentOutOfRangeException` on `DateTime.Add`.

Are there any plans of including this on the next Localstack release?

**Comment by shooresh-golzari-cko** [comment] 2022-09-08 19:12
> Hi, hope you are having a great day :D.
> 
> I'm having the same issue related by @shooresh-golzari-cko when triggering a .net lambda, but using DynamoDB streams instead of Kinesis. So I thought of commenting here as it seems to be the same root cause.
> 
> I've updated from localstack 0.12.11 to the latest version (1.0.4) and after some investigating, I found that the problem seems to be on the `ApproximateCreationDateTime` on the DynamoDB event, which is created with 13 digits instead of 10 (milliseconds instead of seconds) that is the cause of the `ArgumentOutOfRangeException` on `DateTime.Add`.
> 
> Are there any plans to include a possible fix for this in the next localstack release?

Hi Douglas, there is also this: https://github.com/localstack/localstack/issues/6369
This bug will hobble our acceptance tests come 3.1 end of life. Hope it gets fixed soon 🤞

**Comment by shooresh-golzari-cko** [comment] 2022-09-16 08:26
@dfangl @douglasgpertile https://github.com/aws/aws-lambda-dotnet/issues/839

**Comment by shooresh-golzari-cko** [comment] 2022-11-24 09:43
Update for anyone else suffering from this bug. One of our engineers highlighted a workaround for this by overriding the Lambda runtime using the following flag:

![image](https://user-images.githubusercontent.com/72411857/203750656-bc84cc21-d8fe-41d7-ab14-04adc2ece556.png)

**Comment by douglasgpertile** [comment] 2022-11-25 19:03
Thanks for the update @shooresh-golzari-cko, do you know when this issue will be fixed on localstack version 1?

**Comment by dfangl** [comment] 2022-12-14 16:50
Hi @douglasgpertile @shooresh-golzari-cko !
Can you test if setting `PROVIDER_OVERRIDE_LAMBDA=asf` fixes your issues? It will switch to our new lambda provider, and should increase parity in the environments and of API operations massively.
It will become default with 2.0, so we want to get as much feedback as possible beforehand, and this issues seems like it would be solved with the new provider.
Thank you in advance!

**Comment by shooresh-golzari-cko** [comment] 2022-12-16 14:05
> Hi @douglasgpertile @shooresh-golzari-cko ! Can you test if setting `PROVIDER_OVERRIDE_LAMBDA=asf` fixes your issues? It will switch to our new lambda provider, and should increase parity in the environments and of API operations massively. It will become default with 2.0, so we want to get as much feedback as possible beforehand, and this issues seems like it would be solved with the new provider. Thank you in advance!

Thank you Daniel. I am not in a position, at the moment, to attempt this but will share it with our engineering teams and encourage them to feedback here should they try.

**Comment by dfangl** [comment] 2022-12-20 18:09
Hi, some more updates. I went away and was able to reproduce the issues you described. It indeed seems like the approximateArrivalTimestamp is off by a factor of 1000 (milliseconds instead of seconds). Same for dynamodbs ApproximateCreationDateTime . 
I am in the process of fixing these issues.

**Comment by dfangl** [comment] 2022-12-20 20:38
This is now fixed on master, the images should be available in around 1 hour.
I have tested it with the given samples, and the default dotnet lambda kinesis template. (and the new `asf` provider)
If there are any more issues, please do not hesitate to reach out!
Thank you for reporting this.

**Closed by dfangl** 2022-12-20 20:38 UTC
Labels: type: bug, aws:lambda, aws:kinesis
