### ISSUE TITLE
Access S3 from Lambda

### ISSUE THREAD

**Issue by RodionChachura** [localstack/localstack#878] opened 2018-08-03 07:19 UTC
Hello.

When I try to access S3 from Lambda this error arises:
`Error: connect ECONNREFUSED 127.0.0.1:4572`

Construction of S3 service looks this way:
```
const s3 = new aws.S3({
  endpoint: `${process.env.LOCALSTACK_HOSTNAME}:4572`,
  s3ForcePathStyle: true
})
```
This problem arises only when I am trying access S3 from lambda running on Localstack.
Starting Localstack this way:
```
export SERVICES=s3,lambda
export LAMBDA_EXECUTOR=docker
localstack start &
```

**Comment by whummer** [comment] 2018-09-03 14:01
Thanks for reporting @RodionChachura - can you please share some details about your environment (LocalStack version, OS version, Docker version, etc)?

If you are on a Mac, can you post the output of these commands:
```
docker run --entrypoint= localstack/localstack ping -c 1 docker.for.mac.host.internal
docker run --entrypoint= localstack/localstack ping -c 1 docker.for.mac.localhost
```

**Comment by cadz7** [comment] 2019-02-27 18:11
A possible fix could be setting:
`LAMBDA_DOCKER_NETWORK: host`

**Comment by shenie** [comment] 2019-02-28 21:42
The lambda you kicked off is running in a container and your error message suggests that you are trying to get to localstack s3 on `127.0.0.1` on the lambda container which is not available inside the container.

I think `localstack start` runs localstack on host which means you have to tell your lambda the host IP which you then use as the localstack address.

**Comment by whummer** [comment] 2019-11-24 22:29
Closing this issues as outdated / cannot reproduce. Please note that `LOCALSTACK_HOSTNAME` is a read-only property, so please do not overwrite it in your environment. Please re-open this issue or report here if the problem persists. Thanks

**Closed by whummer** 2019-11-24 22:29 UTC
Labels: bug, needs-triaging
