### ISSUE TITLE
s3 presign works in docker image 0.12.7 but not in latest

### ISSUE THREAD

**Issue by simontankersley** [localstack/localstack#3697] opened 2021-03-09 23:26 UTC
# Type of request: This is a ...

[-] bug report
[ ] feature request

# Detailed description

S3 Presigned urls worked for us using docker localstack image 0.12.7. They don't work for us in 'latest'

## Expected behavior

If you:

1. Create a bucket
2. Create a presigned URL for a file in that bucket
3. Access that presigned URL

Then you should get a 404 response

## Actual behavior

Doing steps 1 to 3 we instead get a 403 with the error message:

The request signature we calculated does not match the signature you provided.                     Check your key and signing method.

# Steps to reproduce

## Command used to start LocalStack

*To start 0.12.7 we used:*

```
docker run -d -p 4566:4566 --name=localstack -e "SERVICES=s3" -e "START_WEB=0" localstack/localstack:0.12.7
```

*To start 'latest' we used:*

```
docker run -d -p 4566:4566 --name=localstack -e "SERVICES=s3" -e "START_WEB=0" localstack/localstack@sha256:86a1feeb1da67c6978af8140a3e8f56e118d3197c6ae95ab607004bfa197a30b
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal s3 mb s3://somebucket
awslocal s3 presign s3://somebucket/somefile --expires-in 2147483647
# feed presigned URL into a curl command to see the result
curl -i $(awslocal s3 presign s3://somebucket/somefile --expires-in 2147483647)
```

With 0.12.7 you get a 404 like this (expected):

```
HTTP/1.1 404
content-type: application/xml; charset=utf-8
content-length: 207
access-control-allow-origin: *
last-modified: Tue, 09 Mar 2021 23:22:24 GMT
x-amz-request-id: FBD7450274A5E81B
x-amz-id-2: MzRISOwyjmnupFBD7450274A5E81B7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
accept-ranges: bytes
content-language: en-US
cache-control: no-cache
content-encoding: identity
access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging
access-control-expose-headers: x-amz-version-id
connection: close
date: Tue, 09 Mar 2021 23:22:24 GMT
server: hypercorn-h11

<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>

    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

With 'latest' you get a 403 like this (actual):

```
HTTP/1.1 403
content-type: text/html; charset=utf-8
content-length: 632
last-modified: Tue, 09 Mar 2021 22:53:11 GMT
x-amz-request-id: 155F1B688529728A
x-amz-id-2: MzRISOwyjmnup155F1B688529728A7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
accept-ranges: bytes
content-language: en-US
cache-control: no-cache
content-encoding: identity
access-control-allow-origin: *
access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging
access-control-expose-headers: x-amz-version-id
connection: close
date: Tue, 09 Mar 2021 22:53:11 GMT
server: hypercorn-h11

<?xml version="1.0" encoding="utf-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided.                     Check your key and signing method.</Message><RequestId>b0a26646</RequestId><HostId>4a2d9f8f</HostId><AWSAccessKeyId>test</AWSAccessKeyId><StringToSign></StringToSign><SignatureProvided>...</SignatureProvided><StringToSignBytes>...</StringToSignBytes></Error>
```

...

**Comment by simontankersley** [comment] 2021-03-10 22:19
Hi again, this isn't an issue.

If I follow the instructions from https://github.com/localstack/localstack#setting-up-local-region-and-credentials-to-run-localstack and change the above commands to:

```
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
awslocal s3 mb s3://somebucket
awslocal s3 presign s3://somebucket/somefile --expires-in 2147483647
# feed presigned URL into a curl command to see the result
curl -i $(awslocal s3 presign s3://somebucket/somefile --expires-in 2147483647)
```

It works the same as the 0.12.7 version

**Comment by efenderbosch** [comment] 2021-03-11 17:54
I think this needs to be re-opened for multipart presigning. If I use a real access key/secret and point to real S3, my multipart-presign request and use of the presigned-url work. If I use test/test and point to localstack, it fails.

**Comment by mruz** [comment] 2021-04-12 07:55
I have the same issue on 0.12.9. It's working on 0.12.7.

**Comment by macnev2013** [comment] 2021-04-15 15:48
Thanks for reporting the issue @mruz . We tried to reproduce the issue but its working.
Below are the commands we used.
```
awslocal s3 mb s3://test
awslocal s3 cp file.txt s3://test
curl -i $(awslocal s3 presign s3://test/file.txt --profile test)
```
Are we missing something? Is it possible to provide steps to reproduce the issue? Thanks.

**Comment by efenderbosch** [comment] 2021-04-15 18:09
My issue has code in to to reproduce: https://github.com/localstack/localstack/issues/3713

**Comment by lvieirajr** [comment] 2021-04-16 22:20
I have the same issue, code works in production running on actual s3, and also works when I downgrade to 0.12.7, but either 0.12.8 or 0.12.9(latest) fail with `localstack.services.s3.s3_listener: Presign signature calculation failed: <Response [403]>`

**Comment by macnev2013** [comment] 2021-05-03 15:50
Thanks for update @lvieirajr . Can you please verify if the issue still persists with the `latest` version ? We'll be happy to look into it in more detail. Thanks!

**Comment by jonminter** [comment] 2021-05-03 17:09
Having the same issue with the `latest` version. My code works in AWS but does not with Localstack. If I downgrade to 0.12.7 it works without the error about the signature being invalid. I am trying to create a presigned URL for a putObject request. AWS key is set to test/test.

**Comment by macnev2013** [comment] 2021-05-03 17:53
Thanks for reporting @jonminter . Can you please share some more details about your setup .  How localstack is configured (Docker/Python Package)? If you can share some more details on how to reproduce (ideally a small Github repo with the full config/docker-compose/docker run command), we'll be happy to look into it. Thanks!

**Comment by whummer** [comment] 2021-05-06 21:29
Thanks for reporting @jonminter @lvieirajr @efenderbosch @mruz  . We're currently looking into this issue in more detail. If you could help us provide a small repro example, that would be great.

Meanwhile, as a workaround we have introduced a **new configuration value `S3_SKIP_SIGNATURE_VALIDATION=1`** which you can enable in your LocalStack container environment, to temporarily skip the signature validation.

Hope that helps - please keep us posted how it goes. Thanks!

**Comment by efenderbosch** [comment] 2021-05-07 19:05
This was resolved for me when #3713 was fixed.

**Comment by jonminter** [comment] 2021-05-08 19:11
@macnev2013 I'll see if I can create a GH repo to reproduce. It's for a work project so I can't share the code directly. But I was running Localstack in a docker container and using the NodeJS AWS SDK to interact with Localstack. And strangely enough I had a coworker try and it worked for him with the latest version but not 0.12.7. I want to rule out it wasn't something config/environmental difference but if I can reproduce outside of the work project I will post here.

**Comment by macnev2013** [comment] 2021-05-22 11:44
Thanks for the repo @mruz . I have tried reproduce the issue but not able to reproduce. Can you please give it a try after updating localstack image to `latest` using `docker pull localstack/localstack`.
If the issue persists feel free to report here. We will be happy to look into it. Thanks.

**Comment by whummer** [comment] 2021-05-28 17:46
Thanks all @mruz @jonminter  - closing as "should be fixed", as we have recently pushed various changes to make S3 presign URLs more robust. Please re-open this issue (or create follow-up issues) if the problem persists.. Thanks for your help!

**Closed by whummer** 2021-05-28 17:46 UTC
Labels: service:s3, should-be-fixed
