### ISSUE TITLE
bug: PROVIDER_OVERRIDE_LAMBDA=asf, difficulties on macOS (linux/arm64 V8)

### ISSUE THREAD

**Issue by elsam** [localstack/localstack#7637] opened 2023-02-07 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're trying to switch from the old lambda implementation to asf. We are developing on Apple M1 chips, so when executing lambda's, localstack pulls the linux/arm64 V8 platform image. When invoking the lambda function, the docker container crashes due to the following issue:

```
time="2023-02-07T08:39:35Z" level=debug msg="Start runtime" func=go.amzn.com/lambda/rapid.doInit file="/home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/rapid/start.go:222"
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

We are able to make it work when immediately pulling the linux/amd64 image, right after the linux/arm64 has been pulled by local stack. This way, localstack uses the linux/amd64 image.

### Expected Behavior

Either the lambda setup works out of the box on Apple M1 chips or we have a way to specify the platform to local stack when pulling lambda images. 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

* We're using the testcontainers for java wrapper to start local stack:
```
LocalStackContainer container = new LocalStackContainer(dockerImageName, false)
            .withServices(LocalStackContainer.Service.SQS) // Just because testcontainers does not allow empty list here
            .withEnv("DEFAULT_REGION", "eu-west-1")
            .withEnv("LAMBDA_EXECUTOR", "docker-reuse")
            .withEnv("PROVIDER_OVERRIDE_LAMBDA", "asf")
            .withEnv("LAMBDA_DOCKER_FLAGS", "--add-host host.containers.internal:host-gateway")
            .withCreateContainerCmdModifier(cmd -> cmd.withPlatform("linux/amd64"))
            .withNetwork(network);
```

* We create a lambda function using the java lambda sdk (runtime: provided.al2)
```
lambdaClient.createFunction(
            CreateFunctionRequest.builder()
                .functionName(lambdaFunctionName)
                .code(
                    FunctionCode.builder()
                        .s3Bucket(lambdaCodeBucket.getBucketName())
                        .s3Key(lambdaFileName)
                        .build()
                )
                .timeout(900)
                .deadLetterConfig(
                    DeadLetterConfig.builder()
                        .targetArn(deadLetterQueue.getQueueArn())
                        .build()
                )
                .role("arn:aws:iam::000000000000:role/lambda")
                .handler("myfunction.lambda_handler")
                .environment(
                    Environment.builder()
                        .variables(environmentVariables)
                        .build()
                )
                .memorySize(10000)
                .runtime(Runtime.PROVIDED_AL2)
                .architectures(Architecture.X86_64)
                .build()
```

### Environment

```markdown
- OS: macOS 13.1 (22C65)
- LocalStack: 1.3.0 / latest
```

**Comment by elsam** [comment] 2023-02-07 19:52
After further investigation, I found the following is causing the issue: We bundle a zip containing a java 17 JRE and our code. The bundled 17 JRE performs a call to /lib64/ld-linux-x86-64.so.2 which seems to be available on the linux/amd64 platform version of the provided:al2 docker image, but not on the linux/arm64 v8 platform version. 

I don't know if this can still be classified as a "bug" in localstack. 

We did however specify "Architecture.X86_64" in our lambda definition as that is the target platform the zip will be used on in production. My new question is: is the platform of the lambda docker image used by local stack (asf) in any way affected by the choice of architecture in the lambda definition? If so, how can I configure it? If not, should it be (It would seem strange that we'd have to bundle a different JRE for testing purposes only)?

**Comment by joe4dev** [comment] 2023-02-09 16:52
Thank you for reaching out @elsam !

## Workaround

As a temporary workaround, setting `LAMBDA_DOCKER_FLAGS=--platform linux/amd64` (see [LocalStack Configuration](https://docs.localstack.cloud/references/configuration/#lambda-new--asf)) forces Docker to use x86-64.

## Background

On ARM hosts, the new Lambda provider *accidentally* runs amd64 lambdas as ARM because the new base image is compatible with both architectures. This will enable us to support ARM lambdas in the future. We are currently developing a solution to resolve the issue and will provide an update here as soon as it is fixed.

## Follow Up

@elsam Does the workaround temporarily resolve the issue?

**Comment by elsam** [comment] 2023-02-15 06:41
Thank you for the suggestion @joe4dev ! I have tried to add the platform flag, but it doesn't seem to be taken in to account. I see you already created #4932 for this. 

My current workaround is to listen to docker pull events and as soon as the lambda  linux/amd64 is being pulled, re-pull the  linux/arm64 image.

**Comment by joe4dev** [comment] 2023-02-20 10:22
Hi @elsam 

Lambda execution on ARM hosts is now fixed in https://github.com/localstack/localstack/pull/7675
Please pull the latest localstack Docker image: `docker pull localstack/localstack-pro` or `docker pull localstack/localstack`. Does this fix your issue?

## Sidenotes

* Localstack now also supports creating ARM lambdas (more testing planned).
* `LAMBDA_DOCKER_FLAGS` supports the `platform` flag for forcing a certain target architecture
* `LAMBDA_DOCKER_FLAGS` supports the `user` flag for forcing a user that executes the first process within the lambda function (more testing planned in the coming weeks).

**Comment by elsam** [comment] 2023-02-21 08:10
Hi @joe4dev 

I tested it with the latest docker version of localstack. Works like a charm on my macbook! 
Thank you very much!

**Comment by joe4dev** [comment] 2023-02-21 08:44
Awesome, we are happy to hear it is working 🎉 🎉 
@elsam Thank you very much for sharing your feedback 🙏

**Closed by joe4dev** 2023-02-21 08:44 UTC
Labels: type: bug, status: response required, aws:lambda, platform: macOS/ARM64

**Comment by mkochco** [comment] 2024-08-31 18:04
@joe4dev - I have a serverless-localstack project that is pushing `linux/arm64/v8` container lambdas.  When I execute the functions I see 
```
image with reference 000000000000.dkr.ecr.us-west-2.localhost.localstack.cloud:4566/serverless-prod-processing-tests-local@sha256:1d04a655b03efc9eedaa560a9bb20918c72631295891fbb3b28e9d3ce9e19d34 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```
I'm on `localstack/localstack-pro:latest`.   What do I need to do to get arm64 lambdas running in localstack?

**Comment by joe4dev** [comment] 2024-09-02 20:18
> @joe4dev - I'm on a Mac M2 Max and have a serverless-localstack project that is pushing `linux/arm64/v8` container lambdas. When I execute the functions I see
> 
> ```
> image with reference 000000000000.dkr.ecr.us-west-2.localhost.localstack.cloud:4566/serverless-prod-processing-tests-local@sha256:1d04a655b03efc9eedaa560a9bb20918c72631295891fbb3b28e9d3ce9e19d34 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
> ```
> 
> I'm on `localstack/localstack-pro:latest`. Why is a localstack-pro container running on an ARM architecture looking for AMD only when running lambda containers? What do I need to do to get arm64 lambdas running in localstack?

Hi @mkochco 👋 

The default target architecture on AWS Lambda is x86_64, which we adopt for providing [AWS Parity](https://blog.localstack.cloud/2022-08-04-parity-explained/). We primarily tested this behavior for zip-based Lambda functions. Do you think AWS detects the architecture based on the ECR image? If this is the case for AWS but doesn't work on LocalStack, please create an issue describing a minimal reproducer 🙏 .

A temporary workaround for executing all Lambda functions natively is the [Lambda configuration](https://docs.localstack.cloud/references/configuration/#lambda) `LAMBDA_IGNORE_ARCHITECTURE=1` (see [Lambda multi-architecture support](https://docs.localstack.cloud/references/arm64-support/#lambda-multi-architecture-support)).
