### ISSUE TITLE
Pro - API Gateway v2 WebSockets $connect behaviour incorrect

### ISSUE THREAD

**Issue by alsper** [localstack/localstack#4039] opened 2021-05-17 18:28 UTC
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description

The implementation of the WebSocket API server is inconsistent with that of API Gateway for the $connect handler. API Gateway does not open a connection until it has received a 200 response from the lambda configured for the $connect route.

If you take a look at the documentation [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-keys-connect-disconnect.html), you'll see the following in the note block:

```
If authorization fails on $connect, the connection will not be established, and the client will receive a 401 or 403 response.
```

When you are building an API that relies on this logic, such as authentication checks that are carried out in the $connect handler, what LocalStack has to offer is effectively unusable. This is also the case for session persistence where the client assumes that when it receives the connection open event it can continue to send messages on the assumption that a session has been persisted.

## Expected behavior

When connecting to the server with something like `wscat -c ws://localhost:4510`, the $connect lambda should be called before opening the connection. The connection should then only be opened if an object is returned from the lambda with a 200 status code.

## Actual behavior

When connecting to the WebSocket server, the connection is opened immediately and the $connect lambda handler is invoked asynchronously.

# Steps to reproduce

- Create a $connect lambda handler which returns a 401 to simulate authentication checks failing.
- You will then see that the connection will be established regardless.

## Command used to start LocalStack

Ran in docker in a compose service:
```yaml
version: '3.1'

services:
  localstack:
    image: localstack/localstack:0.12.10
    ports:
      # LocalStack now exposes one edge port for all services.
      - '4566:4566'
      # The WebSocket API port running in LocalStack.
      - '4510:4510'
      # Uncomment if you want to use the web UI, will conflict with the eReader local env!
      # - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    networks: # cleaup this comment: Needed for when localstack is starting up and endpoint for s3 is incorrect - https://github.com/localstack/localstack/issues/808#issuecomment-819538671
      default:
        aliases:
          - localhost.localstack.cloud
          - s3.localhost.localstack.cloud
    environment:
      HOSTNAME: localhost
      LOCALSTACK_API_KEY: '${LOCALSTACK_API_KEY}'
      SERVICES: 'lambda,secretsmanager,s3,dynamodb,cloudformation,iam,apigateway'
      # Use a docker lambda executor so we can run nodejs lambdas in LocalStack in addition to python lambdas.
      LAMBDA_EXECUTOR: 'docker-reuse'
      # Ensure we mount the lambda code from the host instead of uploading to a local S3 bucket.
      LAMBDA_REMOTE_DOCKER: 'false'
      HOST_TMP_FOLDER: '${PWD}'
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      DEFAULT_REGION: 'eu-west-2'
      DEBUG: 1
    volumes:
      # Share host docker engine to allow the docker lambda executor to invoke functions.
      - /var/run/docker.sock:/var/run/docker.sock
      # Volume that allows LocalStack to use mounted code from the host for lambda functions.
      - .:/tmp/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
wscat -c ws://localhost:4510
```

**Comment by whummer** [comment] 2021-05-19 16:57
Thanks for reporting @alsper . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by tobias-zeptio** [comment] 2021-05-28 07:29
I still see this behavior with the latest image, git hash 7daaf5b8. The 'open' event is sent to the websocket client directly on $connect invoke.

**Comment by whummer** [comment] 2021-06-19 23:15
Hi @tobias-zeptio, apologies for the delay on this one. You mention that an 'open' event is sent in your client library - do you think you could share a few snippets of your client test code? This would be super helpful for us to reproduce the issue - thanks! 

But just to confirm - if your `$connect` Lambda raises an exception, the WebSocket connection should be terminated, or at least accept no further messages. Can you confirm that's the case? Thanks

**Comment by whummer** [comment] 2021-11-23 10:29
Closing due to inactivity - please let us know if the problem persists.. Thanks!

**Closed by whummer** 2021-11-23 10:29 UTC
Labels: needs-triaging, evaluate-or-close, PRO, aws:apigatewayv2
