### ISSUE TITLE
bug: Multiple Lambdas, AWS region not set for 2nd

### ISSUE THREAD

**Issue by ShedPlant** [localstack/localstack#5788] opened 2022-04-01 10:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying more than one (python zip) lambda to localstack, that both create `boto3` SQS clients, the first one is fine but deploying the second one fails with 
```
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the CreateFunction operation: Unable to get handler function from lambda code: You must specify a region.
```

### Expected Behavior

Both lambdas to deploy fine, with AWS region set by localstack

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

My setup (simplified)

`docker-compose.yml`
```
version: '3.8'

services:

  localstack:
    privileged: true
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=sqs,lambda
      - LOCALSTACK_HOSTNAME=localhost
      - DEFAULT_REGION=eu-west-1
```

Define two simple Python lambda handlers which connect to SQS with boto3:

```python
import os
import boto3

AWS_ENDPOINT_URL = os.environ.get("AWS_ENDPOINT_URL")
sqs = boto3.resource("sqs", endpoint_url=AWS_ENDPOINT_URL)

def lambda_handler(event, context):
    return "first lambda ok"
```

```python
import os
import boto3

AWS_ENDPOINT_URL = os.environ.get("AWS_ENDPOINT_URL")
sqs = boto3.resource("sqs", endpoint_url=AWS_ENDPOINT_URL)

def lambda_handler(event, context):
    return "second lambda ok"
```

Script to deploy two Lambdas to localstack:

```python
    import boto3

    localstack_url = f"http://127.0.0.1:{EnvConfig.LOCALSTACK_PORT}"

    # zip already created either manually or in other script, irrelevant for this bug
    with open(_ZIP_FILENAME, "rb") as f:
        zipped_code = f.read()

    lambda_client = boto3.client("lambda", endpoint_url=localstack_url)
    lambda_client.create_function(
        FunctionName="first_lambda",
        Runtime="python3.9",
        Role="not_applicable",
        Handler="first_lambda.lambda_handler.lambda_handler",
        Code={"ZipFile": zipped_code},
        PackageType="Zip",
        Publish=True,
        Environment={
            "Variables": {
                "AWS_ENDPOINT_URL": localstack_url,
            }
        },
    )

    print("first lambda deployed ok")

    lambda_client.create_function(
        FunctionName="second_lambda",
        Runtime="python3.9",
        Role="not_applicable",
        Handler="second_lambda.lambda_handler.lambda_handler",
        Code={"ZipFile": zipped_code},
        PackageType="Zip",
        Publish=True,
        Environment={
            "Variables": {
                "AWS_ENDPOINT_URL": localstack_url,
            }
        },
    )

    # execution never gets this far
    print("second lambda deployed ok")
```

### Environment

```markdown
- OS: MacOS Monterey 12.2.1
- LocalStack: Latest
```

### Anything else?

As a workaround, I can set `AWS_DEFAULT_REGION` environment variable explicitly in all my lambdas:

```
        Environment={
            "Variables": {
                "AWS_ENDPOINT_URL": localstack_url,
                "AWS_DEFAULT_REGION": "eu-west-1",
            }
```

But this shouldn't be necessary:
- localstack already has a region set
- it managed to set it for the 1st lambda
- I wouldn't need to explicitly set `AWS_DEFAULT_REGION` env var when running the lambda in real AWS.

**Comment by whummer** [comment] 2022-04-01 12:49
Thanks for reporting @ShedPlant . Can you please try adding the following to your docker-compose configuration:
```
    environment:
      ...
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

This is to allow LocalStack running Lambda functions in separate Docker containers. If you do not specify the `docker.sock` volume mount above, LocalStack will fall back to using the `local` Lambda executor (`LAMBDA_EXECUTOR=local`) which supposedly has some issues loading your handler script (creating the boto3 client). We'll look into replicating this issue, but the recommended way would be to mount the Docker socket, and use the Docker-based Lambda executor.. 👍 Please let us know if that works, thanks.

**Comment by ShedPlant** [comment] 2022-04-01 13:16
Correction, it 'works' insofar as the lambda function is created. Invoking it fails with `TypeError: a bytes-like object is required, not 'str'`!
So I was better off with the environment variable workaround.

Any idea why this is happening?

```
localstack_1          | 2022-04-01T13:10:31.480:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:eu-west-1:000000000000:function:users-vehicles-stream-forwarder
localstack_1          | 2022-04-01T13:10:42.571:INFO:localstack.services.awslambda.lambda_executors: writing log to file '/tmp/localstack/lambda_ebq343o7.log'
localstack_1          | 2022-04-01T13:10:42.592:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:users-vehicles-stream-forwarder: a bytes-like object is required, not 'str' Traceback (most recent call last):
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 795, in run_lambda
localstack_1          |     result = LAMBDA_EXECUTOR.execute(
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 460, in execute
localstack_1          |     return do_execute()
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 450, in do_execute
localstack_1          |     return _run(func_arn=func_arn)
localstack_1          |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 169, in wrapped
localstack_1          |     raise e
localstack_1          |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 165, in wrapped
localstack_1          |     result = func(*args, **kwargs)
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 437, in _run
localstack_1          |     raise e
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 433, in _run
localstack_1          |     result = self._execute(lambda_function, inv_context)
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 897, in _execute
localstack_1          |     return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 756, in _execute
localstack_1          |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 677, in run_lambda_executor
localstack_1          |     output.output_file()
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1655, in output_file
localstack_1          |     f.write(self._stderr)
localstack_1          |   File "/usr/local/lib/python3.8/tempfile.py", line 473, in func_wrapper
localstack_1          |     return func(*args, **kwargs)
localstack_1          | TypeError: a bytes-like object is required, not 'str'
localstack_1          | 
```

**Comment by whummer** [comment] 2022-04-01 21:22
Hi @ShedPlant - this should be fixed in the meantime, can you do a `docker pull localstack/localstack` and try again with the latest version? Thanks

**Comment by ShedPlant** [comment] 2022-04-04 10:49
I removed the `AWS_DEFAULT_REGION` workaround, pulled latest `localstack` lambda.

With `LAMBDA_EXECUTOR=local` I still see the issue as originally reported. But I don't mind so much if I can get it to work in the 'recommended' way with docker containers.

With this `docker-compose.yml` I no longer see the "TypeError" problem, and my lambdas work as expected when invoked 👍 .

```
version: '3.8'

services:

  localstack:
    privileged: true
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_PORT-4566}:4566"
    environment:
      - LOCALSTACK_SERVICES=${LOCALSTACK_SERVICES-sqs,ssm,kms,lambda,dynamodb}
      - LOCALSTACK_HOSTNAME=localstack
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=myproject_default
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I also found I had to set the AWS endpoint URL to `localstack` _within_ the lambda, not `localhost`.

**Comment by ShedPlant** [comment] 2022-04-04 11:03
The last remaining problem/complaint I have is that the lambda containers are left open and orphaned.
With lambda running in local mode, all I need to do after running my tests is `docker-compose down -v`, which left no containers running as expected.

Now I see:

```
Stopping myproject_localstack_1         ... done
Stopping myproject_core-db_1 ... done
Removing myproject_localstack_1         ... done
Removing myproject_core-db_1 ... done
Removing network myproject_default
ERROR: error while removing network: network myproject_default id 19765ac19c713f5367dc90406e3ba298747239faa51f6453f5081f2d0992142f has active endpoints
```

I tried `docker-compose down --remove-orphans -v` and that hasn't made a difference.

Is this a localstack problem or docker problem? I expected stopping localstack container to stop child lambda containers also.

As a workaround:
`docker rm -f $(docker ps --filter="name=myproject_localstack*" -q)`
`docker-compose down --remove-orphans -v`

**Comment by dfangl** [comment] 2022-05-03 09:05
Thanks for the detailed report. You are right, the containers ought to be removed once LocalStack is stopping. I will look into that now.

For the part of the AWS_ENDPOINT_URL, there is the environment variable "LOCALSTACK_HOSTNAME" set on lambda containers, which should point to LocalStack (only host part, normally its set to the ip address of the container). Still, using `localstack` should work as well as long as you do not change the container name (of localstack), as it relies on docker name resolution instead of LocalStack functionality.

**Comment by dfangl** [comment] 2022-05-03 11:46
Hi @ShedPlant !
For now, as a workaround (this will probably be default at some point), can you set `SET_TERM_HANDLER=1` in your docker-compose.yml file as environment variable for localstack? This should enable clean shutdown and also cleanup of any still-running docker-reuse containers.

**Comment by dfangl** [comment] 2022-05-03 18:21
Hi again! If you pull from `localstack/localstack:latest` the issue should now also be fixed without that change in the environment variables (it actually stopped having any effect in the latest image). Per default, the lambda containers should be cleared up now. I hope this resolves your issue, if so, please close it!

**Comment by ShedPlant** [comment] 2022-05-04 14:52
- pulled latest localstack
- removed workaround to remove localstack containers
Confirmed they are removed by `docker-compose down --remove-orphans -v` 😄  !

**Comment by dfangl** [comment] 2022-05-04 14:55
Great! Will close this now, if there is anything else, please do not hesitate to create a new issue!

**Comment by dfangl** [comment] 2022-05-05 10:04
Thats interesting. On shutdown, it should automatically stop all containers starting with <ls_container_name>_lambda .
Do this leftover containers also conform to this naming scheme?
Would it be possible for you to share the logs of a shutdown with DEBUG=1 enabled? It should contain a debug log entry of the lambda_executor module, saying something like: "Removing <count> containers", with a lot of messages regarding container removal afterwards.

**Comment by ShedPlant** [comment] 2022-07-05 09:45
I tried `docker pull localstack/localstack`, added `DEBUG=1` environment variable to localstack, lowered my test wait time to force a failure.

But I wasn't able to reproduce the problem where the lambda containers are orphaned.

I removed `DEBUG=1` and was able to reproduce again.

All the lambda containers have the same naming convention.

I think it may be related to 

The localstack log shows me exceptions about lambdas taking more than 3 seconds, is that relevant?

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 533, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 466, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 456, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 170, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 166, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 443, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 439, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 903, in _execute
    return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 762, in _execute
    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 684, in run_lambda_executor
    raise InvocationException(
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorMessage":"2022-07-05T09:39:48.98Z 998d52ee-57dd-1371-7b33-ac19dc22cdb9 Task timed out after 3.00 seconds"}. Output:
{"level":"INFO","location":"backfill:27","message":{"status":"Scanning","table":"expenses","start_datetime":"2022-06-18T09:39:13.522120","end_datetime":"2022-06-18T09:39:13.522120"},"timestamp":"2022-07-05 09:39:48,957+0000","service":"expenses-backfiller","sampling_rate":0.1,"cold_start":true,"function_name":"expenses-backfiller","function_memory_size":"1536","function_arn":"arn:aws:lambda:eu-west-1:000000000000:function:expenses-backfiller","function_request_id":"998d52ee-57dd-1371-7b33-ac19dc22cdb9","xray_trace_id":"1-dc99d00f-c079a84d433534434534ef0d"}
```

**Comment by dfangl** [comment] 2022-07-06 12:02
I would like to close this issue in favor of #6312 . Would it be possible to share a complete log of LocalStack when this happens (please feel free to redact sensitive material)? Sadly I cannot reproduce this. A good hint definitively that it seems related to execution errors, or did you find an instance of a working lambda where this happens?

**Closed by dfangl** 2022-07-06 12:02 UTC
Labels: type: bug, aws:lambda

**Comment by ShedPlant** [comment] 2023-04-20 14:51
Seems to work in localstack 2.0 👍
