### ISSUE TITLE
Won't exit with MacOS 10.13.6, bash

### ISSUE THREAD

**Issue by jmm** [localstack/localstack#3456] opened 2021-01-11 15:33 UTC
# Type of request: This is a ...

[X] bug report

# Detailed description

Won't exit.

MacOS 10.13.6
GNU bash, version 3.2.57
Python 3.7.9
pip 20.3.3
Docker Desktop 3.0.4 (Engine 20.10.2)
LocalStack 0.12.4

## Expected behavior

It exits cleanly, the Docker container is stopped, and the shell is usable.

## Actual behavior

```
2021-01-11 15:20:45,994 WARN received SIGINT indicating exit request
2021-01-11 15:20:45,995 INFO waiting for infra to die
2021-01-11 15:20:48,054 INFO stopped: infra (terminated by SIGTERM)
```

Hangs there. At that point CTRL-Z is also ineffective.

If I issue `docker stop localstack_main` in another session, in the original session I get this output and the shell is responsive again:

```
Killing off all processes
/usr/local/bin/docker-entrypoint.sh: line 18: kill: (14) - No such process
```

# Steps to reproduce

* Run `SERVICES=sqs localstack start`

* Wait until it's up and running.

  ```
  Starting local dev environment. CTRL-C to quit.
  LocalStack version: 0.12.4
  2021-01-11 15:19:20,358 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  2021-01-11T15:19:23:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f9909def3a0>
  Waiting for all LocalStack services to be ready
  ...
  Ready.
  ```

* Perform <kbd>CTRL-C</kdb>

## Command used to start LocalStack

```
SERVICES=sqs localstack start
```
****

**Comment by mgagliardo** [comment] 2021-01-11 15:52
Hi there @jmm, I could not reproduce this, check my setup:

```
MacOS Catalina 10.15.7
GNU bash, version 3.2.57
pip 20.3.3 from python 3.9
Docker desktop 3.0.4 - Engine 20.10.2
Localstack v0.12.4
```

So I can see:
* MacOS is not latest release on your machine.
* Python release is not the same (although I don't think this has anything to do with this).

Both methods work on my machine:
With `docker stop`
![Screenshot 2021-01-11 at 16 47 25](https://user-images.githubusercontent.com/11886625/104204210-4d2d2d80-542d-11eb-9a34-53ad21046272.png)

With `CTRL-C`:
![Screenshot 2021-01-11 at 16 47 41](https://user-images.githubusercontent.com/11886625/104204281-62a25780-542d-11eb-9eb3-4c8e08110fb0.png)

Any chance you can upgrade your setup and check if that's the issue? I'll dig in a bit more into this in any case.

**Comment by jmm** [comment] 2021-01-11 16:52
Hi @mgagliardo, thanks for the (quick) reply!

> Is it happening to you with any other container image?

I haven't been running other containers recently, but I don't think it's implicit that <kbd>CTRL+C</kbd> will exit, is it? It seems that you may be [explicitly handling](https://github.com/localstack/localstack/blob/8ed765769ab11ba28197ff96e21273dcbbacd9da/bin/docker-entrypoint.sh#L37) that, and the [Docker Run](https://docs.docker.com/engine/reference/run/) documentation says:

> Note
> A process running as PID 1 inside a container is treated specially by Linux: it ignores any signal with the default action. As a result, the process will not terminate on `SIGINT` or `SIGTERM` unless it is coded to do so.

I did try another container that I start with `-it` that runs Bash and <kbd>CTRL+C</kbd> doesn't cause exit, but <kbd>CTRL+D</kbd> does.

> Any chance you can upgrade your setup and check if that's the issue?

I installed Python 3.9.0 and that makes no difference, as you suspected. I don't want to change my OS major version right now just for this, but it should be supported, right?

**Comment by whummer** [comment] 2021-01-11 17:11
Thanks for the update @jmm @mgagliardo . This looks like an issue that may has been introduced recently, but should have been fixed in ##3450 - can you please pull the `latest` Docker image and confirm whether the problem still persists? Thanks

**Comment by jmm** [comment] 2021-01-11 17:52
Thanks @whummer! I pulled the latest image (5bd560ccc527a063c54a0b8a967cef1a3bc82a1376f45054d1985c1b18757a11) and it now exits with <kbd>CTRL-C<kbd>.

**Closed** 2021-01-11 19:30 UTC
Labels: cannot-reproduce, installation, mac-os

**Comment by jmm** [comment] 2021-01-11 22:30
Thanks again for fixing this. I was just taking a look at the changelog to see if this made it into a release, and that is a real wall of text, it would benefit a lot from being formatted as a list rather than semi-colon delimited (and if it was possible to include links to issues, that would help with context and cross referencing).

**Comment by whummer** [comment] 2021-01-11 22:41
Thanks for the feedback @jmm . Please note that the release notes are also published in more human readable form in the Github release section here: https://github.com/localstack/localstack/releases/tag/v0.12.5 . We'll take your feedback into account and will try to include links to the issues in the future as well.

**Comment by jmm** [comment] 2021-01-12 14:17
Thanks @whummer!

Well, I give you kudos for having an actual changelog. It really annoys me when a project tries to use GitHub's releases as a substitute for a changelog, because, unless there's a way I don't know about, there doesn't seem to be any easy way to search them, you have to page through. Often seeing the notes for just one release in isolation isn't sufficient. Whereas with a real changelog I can just search the page / file for a change that happened in any release. (And if you left GitHub it seems you'd need to write or use some kind of tool to export release notes to some portable format.)

> We'll take your feedback into account and will try to include links to the issues in the future as well.

As an example of how helpful that would be, to see if my issue was resolved I'm looking for "exit", whereas I think the release notes describe this change as:

> add proper signal handling in supervisord to support kubernetes deployment

Which I wouldn't think related to that issue if I didn't have specialized knowledge in this case to connect the dots. Whereas if that item referenced the issue I filed, it would be possible to search the changelog for the issue number to see if something fixed it.
