### ISSUE TITLE
StepFunctions cannot start due to NoCredentialsError

### ISSUE THREAD

**Issue by Indosaram** [localstack/localstack#3828] opened 2021-04-05 07:26 UTC
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
I'm running localstack with awslocal command in Ubuntu 20.04. I tried to execute my StepFunction with awslocal cli and docker-compose, but both have failed.

I have working aws cli, which had set by running `aws configure`, and in `~/.aws` directory my config and credentials are fine.

...

## Expected behavior

...

## Actual behavior
```shell
localstack_main | START RequestId: ce4e64af-d625-1da1-527a-6af811be2f17 Version: $LATEST
localstack_main | [INFO]  JobValidator 0405_task_07  :  f169f03c-95b3-11eb-b13a-6ee761ea90a8 
localstack_main | [ERROR] NoCredentialsError: Unable to locate credentials
```

The exception is raised from `botocore/auth.py`.
...

# Steps to reproduce

## Command used to start LocalStack
```
docker-compose up
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
lambda_build.sh
run.sh
```

two shell scripts are as following:
```shell
SRC_ROOT="/home/indo/code/spiderkim_saas_crawler/lambdas/"

LAMBDA_FUNC_NAMES="
job_validator
crawler
scrapper
update_status
"
mkdir -p lambdas
cd lambdas
PRJ_ROOT=$PWD

index=0
for NAME in $LAMBDA_FUNC_NAMES; do
  echo "🍴️ Creating Lambda function ""$NAME"
  mkdir -p "$NAME"
  rsync -a "$SRC_ROOT""$NAME" . --exclude 'venv'
  pip install -qqq -r "$NAME"/requirements.txt --target "$NAME"
  awslocal lambda create-function \
    --function-name "arn:aws:lambda:ap-northeast-2:00000000000""$index"":function:""$NAME" \
    --code S3Bucket="__local__",S3Key="$PWD"/"$NAME" \
    --handler lambda_function.lambda_handler \
    --runtime python3.8 \
    --role whatever
  ((index++))
done
```

```shell
ROLE_ARN="arn:aws:iam::012345678901:role/DummyRole"
FUNCTION_ARN="arn:aws:states:ap-northeast-2:000000000000:stateMachine:TestStepFunction"

FUNCTION_NAME="TestStepFunction"
DEFINITION=$(<definition.json)
INPUT=$(<input.json)

awslocal dynamodb create-table --table-name Spiderkim-JobDB


echo ""
echo "🛠️ Creating a StepFunction"
awslocal stepfunctions create-state-machine \
  --definition "$DEFINITION" --name "$FUNCTION_NAME" \
  --role-arn "$ROLE_ARN"

echo ""
echo "⏳ Executing a StepFunction"
EXECUTION_ARN=$(awslocal stepfunctions start-execution \
  --state-machine-arn "$FUNCTION_ARN" \
  --input "$INPUT" | jq -r '.executionArn')

awslocal stepfunctions describe-execution \
  --execution-arn "$EXECUTION_ARN"
```

...

**Comment by whummer** [comment] 2021-04-18 12:43
Thanks for reporting @Indosaram . Can you please share some details about your project. From the log output you've posted it seems that the error is actually printed from a Lambda invocation. Any chance you can share the StepFunction definition and Lambda scripts with us? This would make it quite a bit easier to replicate and debug this issue. Thanks

**Comment by Indosaram** [comment] 2021-04-21 01:13
Thank you for the comment. The step function itself only contains a single lambda function, which returns default 200 status response.

**Comment by whummer** [comment] 2021-12-13 19:31
Closing as "cannot reproduce" - this output clearly indicates that the `NoCredentialsError` originates from the Lambda handler execution itself - so, seems to be unrelated to the starting of the StepFunction state machine itself.
```
localstack_main | START RequestId: ce4e64af-d625-1da1-527a-6af811be2f17 Version: $LATEST
localstack_main | [INFO]  JobValidator 0405_task_07  :  f169f03c-95b3-11eb-b13a-6ee761ea90a8 
localstack_main | [ERROR] NoCredentialsError: Unable to locate credentials
```

Please feel free to re-open this issue if the problem persists and you can share a full copy of your example project (in particular, any Lambda handler code). Also, please make sure to pull the `latest` Docker image, as we've recently included a number of enhancements around StepFunctions API and Lambda integration.. Thanks!

**Closed by whummer** 2021-12-13 19:31 UTC
Labels: needs-triaging, configuration, lambda-execution, aws:stepfunctions
