### ISSUE TITLE
SQS - SendMessageBatch error - An error occurred (AWS.SimpleQueueService.InvalidBatchEntryId) when calling the SendMessageBatch operation: A batch entry id can only contain alphanumeric characters, hyphens and underscores. It can be at most 80 letters long.

### ISSUE THREAD

**Issue by AshwinRamesh** [localstack/localstack#12022] opened 2024-12-12 01:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When my sqs-producer (NodeJS) library tries to create messages in BATCH on SQS, I get this error:
```
An error occurred (AWS.SimpleQueueService.InvalidBatchEntryId) when calling the SendMessageBatch operation: A batch entry id can only contain alphanumeric characters, hyphens and underscores. It can be at most 80 letters long.
```

I tried manually running the same commands through CLI and the same error happened.

### Expected Behavior

batch insert via sqs should create messages

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker compose up
aws --endpoint-url="$LOCALSTACK_ENDPOINT" sqs create-queue --queue-name user-upsert
aws --endpoint-url="$LOCALSTACK_ENDPOINT" sqs send-message-batch --queue-url "http://sqs.ap-southeast-2.localhost.localstack.cloud:4566/000000000000/user-upsert" --entries '[{"Id":"this:should:fail","MessageBody":"Hello world!"}]'
```

```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS:OSX 15.1.1 (24B91)
- LocalStack: latest (LocalStack version: 3.8.2.dev120)
LocalStack version: 3.8.2.dev120
LocalStack build date: 2024-11-15
LocalStack build git hash: 75436efc5
```

### Anything else?

Similar to this error: https://github.com/localstack/localstack/issues/7312

**Comment by bentsku** [comment] 2024-12-13 17:38
This issue was also posted on our Community Channel and has been confirmed as resolved there, as this was due to misconfiguration. Closing the issue, thanks for reporting!

**Closed by bentsku** 2024-12-13 17:38 UTC
Labels: type: question, aws:sqs
