### ISSUE TITLE
Dead letter queue "Message contains invalid characters" error on SQS triggered lambda

### ISSUE THREAD

**Issue by kigawas** [localstack/localstack#3897] opened 2021-04-20 07:58 UTC
# Type of request: This is a ...

- [x] bug report 

# Detailed description
When a SQS triggered lambda raises some error, the message should go to dead letter queues. However:

```python
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  |
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 681, in run
localstack_main  |     result = self.func(self.params)
localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 168, in do_execute
localstack_main  |     return _run(func_arn=func_arn)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack_main  |     raise e
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack_main  |     result = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 155, in _run
localstack_main  |     dlq_sent = sqs_error_to_dead_letter_queue(sqs_queue_arn, event, e)
localstack_main  |   File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 25, in sqs_error_to_dead_letter_queue
localstack_main  |     return _send_to_dead_letter_queue('SQS', queue_arn, target_arn, event, error)
localstack_main  |   File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 68, in _send_to_dead_letter_queue
localstack_main  |     raise Exception(msg)
localstack_main  | Exception: Unable to send message to dead letter queue http://localhost:4566/000000000000/DeadLetterQueue.fifo (code None): An error occurred (InvalidMessageContents) when calling the SendMessage operation: Message contains invalid characters
```

# Steps to reproduce

## Lambda code
- package.json
```json
{
  "name": "my_func",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
- index.js
```js
exports.handler = async (event, context) => {
  console.log(event);
  return event;
};
```

## SQS params
- sqs_params.json
```json
{
    "RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:ap-northeast-1:000000000000:DeadLetterQueue.fifo\",\"maxReceiveCount\":\"1000\"}"
}
```

## Commands

```
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name DeadLetterQueue.fifo

aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name MyQueue.fifo --attributes file://sqs_params.json

aws --endpoint-url=http://localhost:4566 lambda create-function --function-name "my-func" --runtime=nodejs12.x --role dummy --zip-file=fileb://my_func.zip  --handler my_func/error/index.handler

aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping \
    --event-source-arn arn:aws:sqs:ap-northeast-1:000000000000:MyQueue.fifo  \
    --function-name "my-func"

aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/MyQueue.fifo --message-body '{"Data":[]}'
```

Now you'll see the error due to incorrect handler, let's fix it:

```
aws --endpoint-url=http://localhost:4566 lambda update-function-configuration --function-name "my-func" --handler my_func/index.handler

aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/MyQueue.fifo --message-body '{"Data":[]}'
```

**Comment by mgagliardo** [comment] 2021-04-20 08:42
Hello @kigawas, thanks for reporting this.
Could you please share a bit more details about your setup, docker version, docker image you are using, etc? I am testing this using the`latest` image and I could not reproduce this.

One little tihng, please note the handler should be `index.handler`, not including the function name as specified [on the command flag](https://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html).

My setup:
`MacOS Big Sur v11.1 (20C69)`
`Docker version 20.10.5, build 55c4c88`

docker-compose.yml:
```
version: '3.9'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,lambda
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=/tmp/example-folder
    volumes:
      - /tmp/example-folder:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

index.js:
```
exports.handler = async (event, context) => {
  console.log("Testing the function!");
  console.log(event);
  return event;
};
```

sqs_params.json:
```
{"RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:DeadLetterQueue.fifo\",\"maxReceiveCount\":\"1000\"}"}
```

Commands:
```
$ awslocal sqs create-queue --queue-name DeadLetterQueue.fifo
{
    "QueueUrl": "http://localhost:4566/000000000000/DeadLetterQueue.fifo"
}

$ awslocal sqs create-queue --queue-name MyQueue.fifo --attributes file://sqs_params.json

$ awslocal sqs create-queue --queue-name MyQueue.fifo --attributes file://sqs_params.json
{
    "QueueUrl": "http://localhost:4566/000000000000/MyQueue.fifo"
}

$ awslocal lambda create-function --function-name "my-func" --runtime=nodejs12.x --role dummy --zip-file=fileb://my_func.zip  --handler index.handler
{
    "FunctionName": "my-func",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:my-func",
    "Runtime": "nodejs12.x",
    "Role": "dummy",
    "Handler": "index.handler",
    "CodeSize": 267,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-04-20T08:36:11.001+0000",
    "CodeSha256": "PdNMGWxU7s5Bgw+sXJXw/tBXHMwbGtbUgG3Hh4dR5XU=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "247f7db0-c972-4517-914e-0086cb52e27d",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}

$ awslocal lambda create-event-source-mapping     --event-source-arn arn:aws:sqs:us-east-1:000000000000:MyQueue.fifo --function-name my-func
{
    "UUID": "4de66157-beca-4122-a1a7-2ecdf3cc4ee7",
    "StartingPosition": "LATEST",
    "BatchSize": 10,
    "EventSourceArn": "arn:aws:sqs:us-east-1:000000000000:MyQueue.fifo",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:my-func",
    "LastModified": 1618907784.0,
    "LastProcessingResult": "OK",
    "State": "Enabled",
    "StateTransitionReason": "User action"
}

$ awslocal lambda create-event-source-mapping     --event-source-arn arn:aws:sqs:us-east-1:000000000000:MyQueue.fifo --function-name my-func

$ awslocal sqs send-message --queue-url http://localhost:4566/000000000000/MyQueue.fifo --message-body '{"Data":[]}'
{
    "MD5OfMessageBody": "a25eb1b98b751d7b52f15d53f41538fa",
    "MessageId": "56caa432-4267-abe5-7684-8cd7b7378fb4"
}
```

output:
```
localstack_1  | > START RequestId: 34e888ab-8f1d-1cd6-a4ad-b14d09e2ec61 Version: $LATEST
localstack_1  | > 2021-04-20T08:36:35.167Z	34e888ab-8f1d-1cd6-a4ad-b14d09e2ec61	INFO	Testing the function!
localstack_1  | > 2021-04-20T08:36:35.172Z	34e888ab-8f1d-1cd6-a4ad-b14d09e2ec61	INFO	{
localstack_1  | >   Records: [
localstack_1  | >     {
localstack_1  | >       body: '{"Data":[]}',
localstack_1  | >       receiptHandle: 'qewddmcuzdciylfeldculkecwubbcwkbniemcfyjfriszhpuqvodizraamrtfkypbipabprjxlwteggwpjprehyjuugtcrflzqpwzorijisqshqtxyurocyfzdgglpgrwgtvbiemvvprjlaofvrekcwtazjrbfkbdcikbpyoxeemwupeqizuzpfbz',
localstack_1  | >       md5OfBody: 'a25eb1b98b751d7b52f15d53f41538fa',
localstack_1  | >       eventSourceARN: 'arn:aws:sqs:us-east-1:000000000000:MyQueue.fifo',
localstack_1  | >       eventSource: 'aws:sqs',
localstack_1  | >       awsRegion: 'us-east-1',
localstack_1  | >       messageId: '56caa432-4267-abe5-7684-8cd7b7378fb4',
localstack_1  | >       attributes: {},
localstack_1  | >       messageAttributes: {},
localstack_1  | >       md5OfMessageAttributes: null,
localstack_1  | >       sqs: true
localstack_1  | >     }
localstack_1  | >   ]
localstack_1  | > }
localstack_1  | > END RequestId: 34e888ab-8f1d-1cd6-a4ad-b14d09e2ec61
localstack_1  | > REPORT RequestId: 34e888ab-8f1d-1cd6-a4ad-b14d09e2ec61	Init Duration: 134.86 ms	Duration: 10.35 ms	Billed Duration: 11 ms	Memory Size: 1536 MB	Max Memory Used: 41 MB
```

**Comment by kigawas** [comment] 2021-04-20 12:44
Please set a wrong handler intentionally. I posted the commands above.

**Comment by mgagliardo** [comment] 2021-04-20 14:55
Could you elaborate a bit more the right behaviour? If I understand correctly the error is fine [according to the docs](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html), please correct me if I'm wrong:

```
When Lambda reads a batch, the messages stay in the queue but become hidden for the length of the queue's visibility timeout. If your function successfully processes the batch, Lambda deletes the messages from the queue. If your function is throttled, returns an error, or doesn't respond, the message becomes visible again. All messages in a failed batch return to the queue, so your function code must be able to process the same message multiple times without side effects. 
```

And:

```
If the function returns an error, all retries are attempted on the affected messages before Lambda receives additional messages from the same group. 
```

So the function keeps actually retrying and that is why you see the message as NotVisible, which makes sense:

```
$ awslocal sqs   get-queue-attributes --queue-url http://localhost:4566/000000000000/MyQueue.fifo
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "1",
        "CreatedTimestamp": "1618929842.297389",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1618929842.297389",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:MyQueue.fifo",
        "RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:DeadLetterQueue.fifo\",\"maxReceiveCount\":1000}",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
```

**Comment by mgagliardo** [comment] 2021-04-20 15:09
Yes, that seems correct. I'll close this as duplicate. Thanks.

**Closed by mgagliardo** 2021-04-20 15:09 UTC
Labels: awaiting reporter response
