### ISSUE TITLE
bug: S3 Error uploading files with post on PresignedURL's 

### ISSUE THREAD

**Issue by nicolkill** [localstack/localstack#7256] opened 2022-11-28 20:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This its my docker-compose config

The `init_localstack.sh` file just creates the bucket

```
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      DEBUG: 1
      SERVICES: s3
      DISABLE_CORS_CHECKS: 1
      S3_SKIP_SIGNATURE_VALIDATION: 1
    volumes:
      - ./.localstack:/var/lib/localstack
      - ./scripts/init_localstack.sh:/docker-entrypoint-initaws.d/init_localstack.sh
    networks:
      default:
        aliases:
          - my_bucket.s3.localhost.localstack
```

Using multipart post request

```
curl --location --request POST 'http://my_bucket.s3.localhost.localstack:4566' \
--form 'content-type="application/pdf"' \
--form 'Policy="some_policy_extra_long_code"' \
--form 'X-Amz-Algorithm="some_algorithm"' \
--form 'X-Amz-Credential="some_credential/some_another_number/us-zone-2/s3/aws4_request"' \
--form 'X-Amz-Date="20221128T173252Z"' \
--form 'X-Amz-Signature="some_another_string_that_its_the_signature"' \
--form 'key="my/route/to/file"' \
--form 'file=@"/home/linux-user/Downloads/document1.pdf"'
```

gives this response

```
"{\"message\": \"Unexpected exception\", \"error\": \"400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\", \"type\": \"ClientDisconnected\"}"
```

and the localstack container shows this log, seems like im using a wrong url format for the s3 call

```
2022-11-28T17:32:52.295 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 32, in __call__
    service = determine_aws_service_name(context.request)
  File "/opt/code/localstack/localstack/aws/protocol/service_router.py", line 358, in determine_aws_service_name
    values = request.values
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 448, in values
    sources.append(self.form)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 428, in form
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2022-11-28T17:32:52.296 DEBUG --- [   asgi_gw_0] l.aws.handlers.fallback    : setting internal failure response for 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2022-11-28T17:32:52.296 ERROR --- [   asgi_gw_0] localstack.aws.chain       : exception while running response handler
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 155, in _call_response_handlers
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/logging.py", line 47, in __call__
    self._log(context, response)
  File "/opt/code/localstack/localstack/aws/handlers/logging.py", line 142, in _log
    "input": restore_payload(context.request),
  File "/opt/code/localstack/localstack/http/request.py", line 222, in restore_payload
    data = request.data
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 354, in data
    return self.get_data(parse_form_data=True)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 404, in get_data
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

### Expected Behavior

Expects an 200 result and save the file in the bucket

seems like im using a wrong url format for the s3 call so if you know the right format of the url would be very helpful

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Add this config to the docker-compose

```
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      DEBUG: 1
      SERVICES: s3
      DISABLE_CORS_CHECKS: 1
      S3_SKIP_SIGNATURE_VALIDATION: 1
    volumes:
      - ./.localstack:/var/lib/localstack
      - ./scripts/init_localstack.sh:/docker-entrypoint-initaws.d/init_localstack.sh
    networks:
      default:
        aliases:
          - my_bucket.s3.localhost.localstack
```

access to the container with this command
```
docker compose exec localstack bash
```

and generate the presigned url 

```
awslocal s3 presign s3://my_bucket/my/route/to/file --expires-in 1800
```

and generates the next file

```
http://localhost:4566/my_bucket/my/route/to/file?AWSAccessKeyId=test&Signature=rpL%2Bmuyn7M%2F4Uc2pQFXcbK6B73A%3D&Expires=1669667692
```

and generate the curl using the query params and make the post call

on my code i use the `presigned_post` so this generates this data to me easily

### Environment

```markdown
- OS:ElementaryOs 6.1
- LocalStack: [Latest](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-fba53b8686e699a8bc478874fe0beaf9cb463ad06386e474ebf3284395d1b4d5?context=explore)
```

**Comment by ramnes** [comment] 2022-12-20 10:09
This is a duplicate of #6588.

**Comment by bentsku** [comment] 2022-12-21 14:44
Hello @nicolkill and thanks for your report.

The fix is now part of the latest Docker image, you can get it by running docker pull localstack/localstack:latest.

In the meantime, we have been working on a new implementation of S3, and it is now available under a feature flag. You can try starting LocalStack with PROVIDER_OVERRIDE_S3=asf (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)). We have overhauled the service globally, and pre-signed URL are part of it, and our efforts to increase parity will be directed towards this new implementation. It will become the default in the next major release.
We'd appreciate the feedback as well!

I'll close #7247 as it was linked to the same issue. Don't hesitate to comment if there's still an issue.

**Closed by bentsku** 2022-12-21 14:44 UTC
Labels: type: bug, aws:s3, status: confirmed
