### ISSUE TITLE
bug: kinesis - create stream immediately after delete not-exist stream return 200 but it is not created

### ISSUE THREAD

**Issue by nao23** [localstack/localstack#9171] opened 2023-09-16 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Stream is actually not created if create immediately after trying to delete not-exist stream

```shell
❯ docker run --name localstack -d localstack/localstack:2.2.0
❯ docker exec -it localstack /bin/bash
root@3bcf79615e9f:/opt/code/localstack# awslocal kinesis delete-stream --stream-name test; awslocal kinesis create-stream --stream-name test;

An error occurred (ResourceNotFoundException) when calling the DeleteStream operation: Stream arn arn:aws:kinesis:us-east-1:000000000000:stream/test not found
root@3bcf79615e9f:/opt/code/localstack# awslocal kinesis list-streams
{
    "StreamNames": []
}
```

If I wait a while before creating stream after delete it, stream is created.

```shell
❯ docker run --name localstack -d localstack/localstack:2.2.0
❯ docker exec -it localstack /bin/bash
root@3bcf79615e9f:/opt/code/localstack# awslocal kinesis delete-stream --stream-name test

An error occurred (ResourceNotFoundException) when calling the DeleteStream operation: Stream arn arn:aws:kinesis:us-east-1:000000000000:stream/test not found
root@3bcf79615e9f:/opt/code/localstack# # wait a while
root@3bcf79615e9f:/opt/code/localstack# awslocal kinesis create-stream --stream-name test;
root@3bcf79615e9f:/opt/code/localstack# awslocal kinesis list-streams
{
    "StreamNames": [
        "test"
    ]
}
```

### Expected Behavior

Stream is created also if delete not-exist stream and immediately create it.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```shell
docker run --name localstack -d localstack/localstack:2.2.0
docker exec -it localstack /bin/bash
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kinesis delete-stream --stream-name test; awslocal kinesis create-stream --stream-name test;

### Environment

```markdown
- OS: macOS 13.5.1
- LocalStack: 2.2.0
```

### Anything else?

logs: 
```
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : [io-compute-8] WARN  2023-09-16 09:10:03,183 k.m.cache.Cache x-amzn-RequestId=d1febdd5-5470-11ee-9855-03454ef9b2fc, action=DeleteStream, contextId=d1fe96c4-5470-11ee-9855-03454ef9b2fc, x-amz-id-2=KZzyQ/GQUHs8SRTKU6+PRB82K8hFAnsVLHrBhfMABBhMSZxBz+1LCDuF2vQckBERl7/ICdKGp8ReZxCIg5YmdUoXCTibmc1G, contentType=application/x-amz-json-1.1, streamName=test - Deleting stream was unuccessful
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : kinesis.mock.ResourceNotFoundException: Stream arn arn:aws:kinesis:us-east-1:000000000000:stream/test not found
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at kinesis.mock.validations.CommonValidations$.$anonfun$findStream$1(CommonValidations.scala:72)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at scala.Option.toRight(Option.scala:593)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at kinesis.mock.validations.CommonValidations$.findStream(CommonValidations.scala:72)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at kinesis.mock.api.DeleteStreamRequest.$anonfun$deleteStream$3(DeleteStreamRequest.scala:33)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at scala.util.Either.flatMap(Either.scala:352)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at kinesis.mock.api.DeleteStreamRequest.$anonfun$deleteStream$2(DeleteStreamRequest.scala:31)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at scala.util.Either.flatMap(Either.scala:352)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at kinesis.mock.api.DeleteStreamRequest.$anonfun$deleteStream$1(DeleteStreamRequest.scala:28)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at cats.effect.kernel.SyncRef.spin$4(SyncRef.scala:90)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at cats.effect.kernel.SyncRef.$anonfun$modify$1(SyncRef.scala:94)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at cats.effect.IOFiber.runLoop(IOFiber.scala:403)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1330)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at cats.effect.IOFiber.run(IOFiber.scala:119)
2023-09-16T09:10:03.184  INFO --- [-functhread9] l.s.k.kinesis_mock_server  : at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:585)
2023-09-16T09:10:03.215  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS kinesis.DeleteStream => 400 (ResourceNotFoundException)
2023-09-16T09:10:03.428  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS kinesis.CreateStream => 200
2023-09-16T09:10:12.765  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS kinesis.ListStreams => 200
```

**Comment by alexrashed** [comment] 2023-09-20 10:24
Hi @nao23!
That's an interesting case, and I can reproduce the issue with 2.2.0. However, I cannot reproduce the issue with the current latest image. Could you please try to use the latest image (make sure to pull it explicitly to make sure that it's up to date), and try if you can reproduce your issue there?
Thanks!

**Comment by nao23** [comment] 2023-09-22 08:40
Hi @alexrashed ! Thank you for checking. I couldn't reproduce this issue for latest image as you say.

**Comment by alexrashed** [comment] 2023-09-22 09:24
Thanks for checking again and letting us know! I'll close this issue for now. We will create the next tagged release 2.3 in a few days.

**Closed by alexrashed** 2023-09-22 09:24 UTC
Labels: type: bug
