### ISSUE TITLE
bug: Internal exception after publishing to sns topic that has a http subscription endpoint - TypeError: object supporting the buffer API required

### ISSUE THREAD

**Issue by surgiie** [localstack/localstack#8034] opened 2023-04-01 01:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im using localstack via a local minikube cluster using the helm charts:

https://github.com/localstack/helm-charts

Ive set up the following topic and endpoint:

```bash
  awslocal sns create-topic --name test
  awslocal sns subscribe \
    --protocol http \
    --topic-arn arn:aws:sns:us-east-1:000000000000:test \
    --endpoint-url http://localstack:4566 \
    --notification-endpoint http://myapp:8000/subscribe
```

Ive got some code in a where I publish a message in the topic manually via boto3, and it calls my endpoint successfully  which I can also confirm from my logs of the pod running the endpoint:

` INFO:     10.244.0.40:40552 - "POST /subscribe HTTP/1.1" 200 OK`

However immediately after, I get an error from localstack pod that looks like:

```

 2023-04-01T01:15:55.238  INFO --- [   sns_pub_0] l.services.sns.publisher   : Received error on sending SNS message, putting to DLQ (if configured): object supporting the buffer API required
 2023-04-01T01:15:55.239 ERROR --- [   sns_pub_0] l.services.sns.publisher   : An internal error occurred while trying to send the SNS message SnsMessage(type='Notification', message={'default': {'foo': 'bar'}}, message_attributes={}, message_structure='json', subject='example subject', message_deduplication_id=None, message_group_id=None, token=None, message_id='6f150269-fe84-4daf-876f-9c7cfae99f87')
 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/services/sns/publisher.py", line 444, in _publish
     store_delivery_log(message_context, subscriber, success=True, delivery=delivery)
   File "/opt/code/localstack/localstack/services/sns/publisher.py", line 853, in store_delivery_log
     "messageMD5Sum": md5(message),
   File "/opt/code/localstack/localstack/utils/strings.py", line 145, in md5
     m.update(to_bytes(string))
 TypeError: object supporting the buffer API required
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/services/sns/publisher.py", line 80, in publish
     self._publish(context=context, subscriber=subscriber)
   File "/opt/code/localstack/localstack/services/sns/publisher.py", line 451, in _publish
     store_delivery_log(message_context, subscriber, success=False)
   File "/opt/code/localstack/localstack/services/sns/publisher.py", line 853, in store_delivery_log
     "messageMD5Sum": md5(message),
   File "/opt/code/localstack/localstack/utils/strings.py", line 145, in md5
     m.update(to_bytes(string))
 TypeError: object supporting the buffer API required
```

From what I can tell, this doesnt appear to be a result of any code or data im in control or at least I dont believe it is but i could be wrong. As I mentioned, my subscription endpoint appears to work as expected and the exception is raised internally after from the local stack modules. Any direction on how I might be able to address this bug and prevent the exception would be great, thanks.

Thanks.

### Expected Behavior

Interanal exception doesnt occur after publish to topic.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

As described in behavior.

### Environment

```markdown
- OS: Pop!_OS 22.04
- LocalStack: 1.4 
```

### Anything else?

As requested.

**Comment by bentsku** [comment] 2023-04-01 16:08
Hi @surgiie and thanks for your report!

It seems the issue arise after publishing the message to your endpoint, when storing delivery logs. May I ask what is the message you're sending? I haven't seen this issue before and I'm not sure how to reproduce the issue. Thanks!

**Comment by surgiie** [comment] 2023-04-01 18:19
Hi @bentsku, 

Im publishing in a message manually on one of my application's pods in a python shell:

`kubectl exec -it deployments/myapp -- ipython`

Then im just publishing a test message manually:

```python
import boto3
import json

client = boto3.client("sns", endpoint_url="http://localstack:4566/")

message = {
    "foo": "bar"
}

client.publish(
    TopicArn="arn:aws:sns:us-east-1:000000000000:test",
    Message=json.dumps({"default": message}),
    MessageStructure="json",
    Subject="Testing",
)

```

As mentioned, the endpoint runs fine, and i've printed out the json payload, which i can see in my pod logs:

```
2023-04-01T18:05:24.179  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS sns.Publish => 200
{'Type': 'Notification', 'MessageId': '41c52616-9ea8-40ed-9a14-b736b71ecafc', 'TopicArn': 'arn:aws:sns:us-east-1:000000000000:test', 'Message': {'foo': 'bar'}, 'Timestamp': '2023-04-01T18:05:24.180Z', 'SignatureVersion': '1', 'Signature': 'EXAMPLEpH+..', 'SigningCertURL': 'https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem', 'UnsubscribeURL': 'http://localhost:4566/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:000000000000:test:cab5dfb7-05ae-496f-9205-d15c26ac5f42', 'Subject': 'Testing'}
INFO:     10.244.0.6:49576 - "POST /subscribe HTTP/1.1" 200 OK
```

But immediately after this when inspecting the logs on the localstack pod:

`kubectl logs -f deployment/localstack`

I get the described error: 


```
2023-04-01T18:05:24.184  INFO --- [   sns_pub_0] l.services.sns.publisher   : Received error on sending SNS message, putting to DLQ (if configured): object supporting the buffer API required
2023-04-01T18:05:24.184 ERROR --- [   sns_pub_0] l.services.sns.publisher   : An internal error occurred while trying to send the SNS message SnsMessage(type='Notification', message={'default': {'foo': 'bar'}}, message_attributes={}, message_structure='json', subject='Testing', message_deduplication_id=None, message_group_id=None, token=None, message_id='41c52616-9ea8-40ed-9a14-b736b71ecafc')
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/sns/publisher.py", line 444, in _publish
    store_delivery_log(message_context, subscriber, success=True, delivery=delivery)
  File "/opt/code/localstack/localstack/services/sns/publisher.py", line 853, in store_delivery_log
    "messageMD5Sum": md5(message),
  File "/opt/code/localstack/localstack/utils/strings.py", line 145, in md5
    m.update(to_bytes(string))
TypeError: object supporting the buffer API required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/sns/publisher.py", line 80, in publish
    self._publish(context=context, subscriber=subscriber)
  File "/opt/code/localstack/localstack/services/sns/publisher.py", line 451, in _publish
    store_delivery_log(message_context, subscriber, success=False)
  File "/opt/code/localstack/localstack/services/sns/publisher.py", line 853, in store_delivery_log
    "messageMD5Sum": md5(message),
  File "/opt/code/localstack/localstack/utils/strings.py", line 145, in md5
    m.update(to_bytes(string))
TypeError: object supporting the buffer API required
```

Doubt it's helpful but FWIW, these are the values im using to pass to the helm charts:

```yaml
debug: false
image:
  repository: localstack/localstack
  tag: "1.4"
  pullPolicy: IfNotPresent
enableStartupScripts: true
startupScriptContent: |
  #!/bin/bash
  awslocal sns create-topic --name test
  awslocal sns subscribe \
    --protocol http \
    --topic-arn arn:aws:sns:us-east-1:000000000000:test \
    --endpoint-url http://localstack:4566 \
    --notification-endpoint http://myapp:8000/subscribe

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
```

From what i can tell, there is disruption or visual impact on my application's end, but I would like to try to figure out how to prevent the error. Im not super familiar with SNS so it's unclear if ive got something misconfigured or im passing something bad to the boto client.

**Comment by bentsku** [comment] 2023-04-02 01:12
Thanks a lot for the information, I'll have a look and come back to you!

**Comment by bentsku** [comment] 2023-04-03 19:59
Hi @surgiie!

I've investigated and it seems LocalStack didn't raise an error where AWS would have.
From the documentation:

> JSON-specific constraints:
>
> - Keys in the JSON object that correspond to supported transport protocols must have simple JSON string values.
> - The values will be parsed (unescaped) before they are used in outgoing messages.
> - Outbound notifications are JSON encoded (meaning that the characters will be reescaped for sending).
> - Values have a minimum length of 0 (the empty string, "", is allowed).
> - Values have a maximum length bounded by the overall message size (so, including multiple protocols may limit message sizes).
> - Non-string values will cause the key to be ignored.
> - Keys that do not correspond to supported transport protocols are ignored.
> - Duplicate keys are not allowed.
> - Failure to parse or validate any key or value in the message will cause the Publish call to return an error (no partial delivery).

As the message is constructed in your example, you are passing an object to the `default` field, and when SNS loads this JSON object, it expects a string. It would need to be "double" encoded, this way:

```python
import boto3
import json

client = boto3.client("sns", endpoint_url="http://localstack:4566/")

message = {
    "foo": "bar"
}

client.publish(
    TopicArn="arn:aws:sns:us-east-1:000000000000:test",
    Message=json.dumps({"default": json.dumps(message)}),
    MessageStructure="json",
    Subject="Testing",
)
```

Now, with the linked PR, LocalStack will reject your publish call because it would ignore the `default` key as it's not a string once decoded, and then would raise an error because there is no default field.
The error you see then down the line is because we're trying to pass a dict to the `md5` function instead of a string, which we shouldn't have accepted in the first place.

Hope that solves your issue, thanks again for your report! I'm glad we can push SNS to be more in line with AWS with this one.

**Comment by surgiie** [comment] 2023-04-03 20:48
@bentsku I appreciate the thorough explanation. Im glad it was a minor issue and will update my end accordingly. Thanks for looking it it.

**Comment by bentsku** [comment] 2023-04-03 20:52
You're welcome! You can try it with the updated sample and see if the error pops again or not, and close the issue if it does fix the issue.

In the meantime, once the PR will be merged and part of the `latest` docker image, we should raise an exception with the first sample above, like AWS would. Thanks again for the very detailed explanation and sample which allowed me to quickly test and see where our error was. 👍

**Closed** 2023-04-04 17:58 UTC
Labels: type: bug, aws:sns, status: confirmed
