### ISSUE TITLE
bug: api-gateway-v2 websocket connect integration not returning Sec-Websocket-Protocol header

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#6521] opened 2022-07-26 21:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When connecting to websocket using sec-websocket-protocol header, chrome requires that the sec-websocket-protocol be provided back during the connection handshake as a header otherwise it will cause an abnormal disconnect error.
in my $connect route lambda I return the following

headers={
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token",
        "Access-Control-Allow-Credentials": "true",
        "Sec-Websocket-Protocol":"auth"
    }

return {"statusCode": 200, "headers": headers, "body": 'connected'}
In the below log you can see that LS is not returning the header in the handshake:

> 2022/07/26 21:21:54.285589  length=1064 from=0 to=1063
GET /ws/ HTTP/1.1\r
Sec-WebSocket-Protocol: auth, XXX\r
Host: localhost:3030\r
Connection: Upgrade\r
Upgrade: websocket\r
Sec-WebSocket-Version: 13\r
Sec-WebSocket-Key: XXX\r
\r
< 2022/07/26 21:21:54.342609  length=203 from=0 to=202
HTTP/1.1 101 Switching Protocols\r
upgrade: websocket\r
connection: Upgrade\r
sec-websocket-accept: XXX\r
date: Tue, 26 Jul 2022 21:21:54 GMT\r
server: Python/3.10 websockets/10.3\r
\r

### Expected Behavior

in aws the "Sec-Websocket-Protocol":"auth" header is presented back in the handshake shown in log below:
> 2022/07/26 21:25:53.883360  length=1072 from=0 to=1071
GET /ws/ HTTP/1.1\r
Sec-WebSocket-Protocol: auth, XXX\r
Host: XXX\r
Connection: Upgrade\r
Upgrade: websocket\r
Sec-WebSocket-Version: 13\r
Sec-WebSocket-Key: XXX\r
\r
< 2022/07/26 21:25:59.286104  length=392 from=0 to=391
HTTP/1.1 101 Switching Protocols\r
Connection: upgrade\r
Date: Tue, 26 Jul 2022 21:25:59 GMT\r
sec-websocket-protocol: auth\r
upgrade: websocket\r
sec-websocket-accept: XXX\r
X-Cache: Miss from cloudfront\r
Via: 1.1 863cb6019a95f0a483e6ece04f49e0a0.cloudfront.net (CloudFront)\r
X-Amz-Cf-Pop: SFO5-P1\r
X-Amz-Cf-Id:XXX==\r
\r

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

compose with pulumi typescript

### Environment

```markdown
- OS: Windows11, OSX
- LocalStack: v1.0.0
```

**Comment by paulrobello** [comment] 2022-08-31 18:41
Any updates on this one? Chrome will not work with LS websockets when using proto header until its fixed.

**Comment by calvernaz** [comment] 2022-09-01 06:55
Hi @paulrobello sorry for the long radio silence, this and other issues related to websockets triggered an internal discussion around our websockets implementation that impacts other services, hence the team still looking into this and hopefully will be prioritised soon.

I saw another [issue](https://github.com/localstack/localstack/issues/6383) created by you that is still looking for a reproducible sample. Would you mind to provide one?

**Comment by cabeaulac** [comment] 2023-05-06 19:46
Any updates on this?

**Comment by kingster307** [comment] 2023-10-26 20:44
@alexrashed issue still present....[reproducer here](https://github.com/kingster307/localstack_ws_bugs/tree/localstack_issue_6521)

**Comment by kingster307** [comment] 2023-11-03 20:01
this reproducer shows it from UI perspective....without the header WS connect with auth token fails [see here](https://github.com/kingster307/localstack_ws_bugs/tree/localstack_ws_bugs_generic)

**Comment by fridaystreet** [comment] 2024-11-11 07:59
any update on this, we are facing the same issue. another show stopper unfortunately :-(

**Comment by cloutierMat** [comment] 2024-11-15 06:44
Hi @fridaystreet,

I did have a look at the issue. And while I can't fully fix it with the current implementation, I will be able to provide a workaround.

The main issue is that the `$connect` route isn't called part of the handshake before returning the response. Which in turn prevents the addition of custom headers to the response. That will remain the case until we work on WebSocket Next Gen.

I have however been working on a workaround to echo back the first `Sec-WebSocket-Protocol` in the request headers back in the handshake response headers. Thank you @peterkingswe for the sample, I was able to validate that my fix can indeed fix the header issue for the `auth` use case.

## What this does

Enable a "happy path" when creating WebSocket connections with protocols defined by the client. Since WebSocket clients only require that one of the requested protocol be observed by the server.

1. :+1: 
```python
 ws = create_connection(base_url_ws_api, subprotocols=["auth", "XXX"])
# The first header found will be "auth" and the response handshake will include the header
assert ws.handshake_response.headers["Sec-WebSocket-Protocol"] == "auth"
```

2. :+1: 
```python
ws = create_connection(base_url_ws_api, subprotocols=["soap", "auth", "XXX"])
# The first header found will be "soap" and the response handshake will include the header
assert ws.handshake_response.headers["Sec-WebSocket-Protocol"] == "soap"
```

## What this does not do

Allow for fine grained control over the returned header, the only returned header will be the first protocol.

Which means the connection will be created regardless of the `$connect` route returned value. The connection will then be closed if ~$connect` returns a `>=400` status code.


I hope this will fix your issue and allow a better experience using WebSocket apis. I will update here once the fix is live.

**Comment by cloutierMat** [comment] 2024-11-15 23:10
Thanks again @fridaystreet for reviving this issue and bringing it to my attention. The fix has now been pushed to our latest pro image. Could you please run `docker pull localstack/localstack-pro:latest` and try your setup again?

Let me know if that fixed the issue you were having.

**Comment by fridaystreet** [comment] 2024-11-16 07:24
@cloutierMat thanks for pushing up a fix. Unfortunately I can't seem to get it to work, I could be doing somehting wrong though.

Just sending this in the chrome inspect, without the 'graphql-ws' (ie no header) it connects fine still. 

const ws = new WebSocket('wss://localhost.localstack.cloud:4510', 'graphql-ws')

It's definitely sending the header
accept-encoding:
gzip, deflate, br, zstd
accept-language:
en-GB,en-US;q=0.9,en;q=0.8
cache-control:
no-cache
connection:
Upgrade
host:
localhost.localstack.cloud:4510
origin:
https://localhost.localstack.cloud:4566
pragma:
no-cache
sec-websocket-extensions:
permessage-deflate; client_max_window_bits
sec-websocket-key:
Ea8AAzGLhdR8S99LucGLFg==
sec-websocket-protocol:
graphql-ws
sec-websocket-version:
13
upgrade:
websocket
user-agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36


Heres the log from my handler (which normally sends the header in return to the $connect from the lambda function. But my understanding from your message is that's irrelevant as it's just bouncing it back at a lower level?

024-11-16T07:17:58.677Z        9f20f68a-bcfa-4dd3-a322-70a67c970a65    INFO    EVENT_TYPE CONNECT
2024-11-16T07:17:58.677Z        9f20f68a-bcfa-4dd3-a322-70a67c970a65    INFO    connectionId d3468683
2024-11-16T07:17:58.758Z        9f20f68a-bcfa-4dd3-a322-70a67c970a65    INFO    {
  statusCode: 200,
  headers: { 'Sec-Websocket-Protocol': 'graphql-transport-ws' }
}
2024-11-16T07:17:58.778Z        3219c9fa-09d4-4e86-b28b-48ed3a873b9d    INFO    EVENT_TYPE DISCONNECT
2024-11-16T07:17:58.778Z        3219c9fa-09d4-4e86-b28b-48ed3a873b9d    INFO    connectionId d3468683
2024-11-16T07:17:58.796Z        3219c9fa-09d4-4e86-b28b-48ed3a873b9d    INFO    { statusCode: 200 }

**Comment by cloutierMat** [comment] 2024-11-18 22:29
Thank you @fridaystreet for the feedback.

> But my understanding from your message is that's irrelevant as it's just bouncing it back at a lower level?

You are correct, but I notice that your `$connect` function is returning `{ 'Sec-Websocket-Protocol': 'graphql-transport-ws' }` while your WebSocket is sending `'graphql-ws'`. The current fix is returning exactly the same header as was sent (in this case `'graphql-ws'`). This is usually what the `WebSocket` connection will require. If your application is requiring something different, I am curious to understand the scenario.

If you are using `graphql-ws` the correct protocol to set is `graphql-transport-ws` as seen in their [doc](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md).

Maybe try to create the connection as such `const ws = new WebSocket('wss://localhost.localstack.cloud:4510', 'graphql-transport-ws')` and report your findings. If that still doesn't work, can you please share a minimal reproducible sample that I could run to reproduce the issue?

**Comment by fridaystreet** [comment] 2024-11-18 22:48
We've just pushed up a template repo for our build environment, if you pull this down, put your localstack auth key in the docker compose and do yarn start, you'll have a basic websicket handler the same as above.

https://github.com/Aleign/serverless-localstack-esbuild-dev-template

**Comment by fridaystreet** [comment] 2024-11-18 22:59
Apologies for this I've just pulled the latest docker file again and it's connecting now with a header. I definitely pulled it after your last message, but I assume maybe I hadn't gotten that build. Apologies again, I should have tried again. 

The graphql issue is that different clients and client versions could send various headers (just inconsistences), it should be graphql-transport-ws but the server should respond with graphql-transport-ws. Hence our code picks up the header, checks that it is one of the valid graphql protocols and always responds with the correct graphql-transport-ws header. 

I'm just testing it now to se if this makes any difference if it just returns the original protocol to the client

Thanks again for your help

**Comment by fridaystreet** [comment] 2024-11-18 23:15
Typical, just gone to fire it up again and the trial license has literally just expired. I ran it 5 minutes ago with the basic websocket to test that and it worked. Went to rerun it with our API to test the graphql side and it flagged as expired :-(. 

Is there any chance of getting this extended, we haven't actually been able to fully run and test localstack for our enviornment yet. Appreciate it's probably not your department so I've contacted support on the matter as well. If it was monthly billing probably would have just signed up, but as it's only annual billing, do need to just validate it's definitley going to work first.

Thanks

**Comment by cloutierMat** [comment] 2024-11-18 23:44
Thank you for confirming the fix is working for you! Your report is very valuable! :pray:

I hope for you that you will be able to keep working with LocalStack, contacting Support is definitely the right step to take!

I will close this issue, but feel free to keep reporting if you run into other bugs.

**Closed by cloutierMat** 2024-11-18 23:44 UTC
Labels: type: bug, aws:apigatewayv2

**Comment by fridaystreet** [comment] 2024-11-19 00:02
no worries, thanks again for all your prompt assistance.

**Comment by fridaystreet** [comment] 2024-11-19 03:21
@cloutierMat @joe4dev 

I realise not entirely related to this closed issue, but we've now had a chance to run this up with the full application. Do you have any advice regarding trying to debug a fully running application? From what we're seeing, localstack debugging is ok if you are trying to debug a single api request, but as soon as you need to debug anything complex it's pretty much impossible with the restricted concurrency and handler invocation?

I really want to be able to run with localstack, I love the fact it's so much closer to the actual AWS deployment overall, but as it stands I can't really see how we're going to be able to use localstack in any practical sense in regards to debugging, especially for websockets. 

Can you provide any advice or insight that maybe we're just missing here?

**Comment by cloutierMat** [comment] 2024-11-21 01:17
Without more information on the full stack it is hard to give specific recommendations. But I would suggest to get it all working a piece at a time. And you can always reach out on github to raise issues or feature requests or join our Community Slack channel to look for advice on how to achieve any specific goal you might have with LocalStack.

I thank you for the feedback. It will be valuable as we tackle the WebSocket upgrade!

**Comment by fridaystreet** [comment] 2024-11-21 04:18
@cloutierMat thanks for getting back to me and I totally appreciate your comments. We basically have done exactly that as you may have been able to follow along with from the issues with been chatting about. We've built it up step by step getting individual items working. Now we have all the features working, ie api calls, websocket calls and we have a dynamo stream handler. Which are all working nicely individually. In fact it's working great if we don't run in debug mode. We get multiple containers firing up to handle the multiple concurrent requests when loading the actual frontend up and it works just like the real application.

However, from a debugging perspective unfortunately it's not the same story. Once we turn on debug mode and the concurrency is restricted, unless we just do a single request via say postman the main localstack container starts throwing the maximum concurrency errors and everything locks up and it doesn't appear to be able to recover even once the requests have stopped, the only remedy is to kill all the containers and redploy the app. From websocket point of view, you can imagine, running our frontend app against this with it trying to subscribe to multiple websocket channels just kills it immediately. 

For now we just aren't able to use this for debugging, so we'll have to go back to serverless-offline. Aside from the debugging though, we're really keen to get the empheral/preview type environment up and running for our testers. So we'll keep moving forward with that and keep an eye on the debugging side to see if you guys can solve these issues at all.

Thanks again for your help

**Comment by cloutierMat** [comment] 2024-11-21 16:30
Hi @fridaystreet, as the current discussion is not related to this issue, I would appreciate if we could move this conversation to our [Community Slack channel](https://localstack.cloud/slack).

You will be able to reach a greater audience that way as well :wink:
