### ISSUE TITLE
bug: S3 putObject fails when invoked more than 1000 times in a row

### ISSUE THREAD

**Issue by pko7bc** [localstack/localstack#10154] opened 2024-02-01 00:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add more than 1000 objects in a row (in Java) it always fails on object no. 1001 (some kind of buffer?) and continues to add correctly the remaining objects. So if I have 1111 objects to add, 1110 will be added correctly.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Java code:
```java
    IntStream.range(1, 1111).forEach(i -> {
      var key = UUID.randomUUID().toString();
      var content = UUID.randomUUID().toString();

      // if (i == 1001) {
      //   try {
      //     Thread.sleep(5000);
      //   } catch (InterruptedException e) {
      //     //ignore
      //   }
      // }

      try {
        s3Client.putObject(x -> x.bucket("bucket").key("test" + key), RequestBody.fromBytes(content.getBytes()));
      } catch (Exception e) {
        log.error("i=" + i, e);
      }
```
The code fails with:
```
i=1001: java.io.UncheckedIOException: java.net.SocketException: Unexpected end of file from server
	at software.amazon.awssdk.utils.FunctionalUtils.asRuntimeException(FunctionalUtils.java:180)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:110)
	at software.amazon.awssdk.utils.FunctionalUtils.invokeSafely(FunctionalUtils.java:136)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.lambda$tryGetOutputStream$0(UrlConnectionHttpClient.java:324)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.getAndHandle100Bug(UrlConnectionHttpClient.java:360)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.tryGetOutputStream(UrlConnectionHttpClient.java:324)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:301)
	at software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient$RequestCallable.call(UrlConnectionHttpClient.java:274)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:67)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:196)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:8783)
	at software.amazon.awssdk.services.s3.S3Client.putObject(S3Client.java:17207)
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:954)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.expect100Continue(HttpURLConnection.java:1333)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1444)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at software.amazon.awssdk.utils.FunctionalUtils.lambda$safeSupplier$4(FunctionalUtils.java:108)
	... 120 more
```

But if the above `if/sleep` statement is uncommented then it works correctly (or fails again at i=2002 if there are more objects to add).

### Environment

```markdown
- OS: Linux Mint 21.3
- LocalStack: localstack/localstack:3.1
```

**Comment by bentsku** [comment] 2024-02-01 21:22
Thanks for the data! 
To be sure the issue does not originate from our S3 implementation itself (the 1000 arbitrary limit does not look like something we would have set in S3, but a more global one), could you try running the same test with `PROVIDER_OVERRIDE_S3=legacy_v2` and see if the issue is still there?
It is also very weird that they are no logs at all for the failed request.

**Comment by pko7bc** [comment] 2024-02-02 09:24
It works with 2.2 but doesn't with 3.1 and `PROVIDER_OVERRIDE_S3=legacy_v2` doesn't help.

I did some additional tests and it works with python. 
I found out that it also works in Java but with different HTTP client.
When I use `software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient` it fails but after changing to `software.amazon.awssdk.http.apache.ApacheHttpClient` it works fine.


Client config:
```java
var s3Client = S3Client.builder()
        //.httpClientBuilder(UrlConnectionHttpClient.builder())
        .httpClientBuilder(ApacheHttpClient.builder())
        .endpointOverride(URI.create(endpoint))
        .credentialsProvider(
            StaticCredentialsProvider.create(
                AwsBasicCredentials.create("dummy", "dummy")
            )
        )
        .build();
```

I managed to get some logs for both clients - maybe it will help somehow.

UrlConnectionHttpClient:
```
2024-02-02T10:04:20.918 DEBUG [so.am.aw.request] Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=127.0.0.1, port=33202, encodedPath=/bucket/test3b204e22-f6f0-4f91-8aab-e70ed29063f6, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent], queryParameters=[])
2024-02-02T10:04:20.919 TRACE [su.ne.ww.pr.ht.HttpURLConnection] ProxySelector Request for http://127.0.0.1:33202/bucket/test3b204e22-f6f0-4f91-8aab-e70ed29063f6
2024-02-02T10:04:20.919 TRACE [su.ne.ww.pr.ht.HttpURLConnection] cached HttpClient was idle for 2
2024-02-02T10:04:20.919 TRACE [su.ne.ww.pr.ht.HttpURLConnection] KeepAlive stream retrieved from the cache, sun.net.www.http.HttpClient(http://127.0.0.1:33202/bucket/teste3ee3af1-cb05-47de-b2bd-e31e09c5a7ff)
2024-02-02T10:04:20.919 TRACE [su.ne.ww.pr.ht.HttpURLConnection] Proxy used: DIRECT
2024-02-02T10:04:20.919 DEBUG [su.ne.ww.pr.ht.HttpURLConnection] sun.net.www.MessageHeader@6fafbdac14 pairs: {PUT /bucket/test3b204e22-f6f0-4f91-8aab-e70ed29063f6 HTTP/1.1: null}{amz-sdk-invocation-id: ca3bbe6a-e579-6efd-b855-ccf99bb378f2}{amz-sdk-request: attempt=1; max=4}{Authorization: AWS4-HMAC-SHA256 Credential=dummy/20240202/eu-central-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=bd7d15df131cf6dbfa56fdbd35f3a465cdb14256d04eab8834ee6db8f97f4a67}{Content-Type: application/octet-stream}{Expect: 100-continue}{User-Agent: aws-sdk-java/2.20.128 Linux/5.15.0-91-generic OpenJDK_64-Bit_Server_VM/17.0.8+7-jvmci-23.0-b15 Java/17.0.8 vendor/GraalVM_Community io/sync http/UrlConnection cfg/retry-mode/legacy}{x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD}{X-Amz-Date: 20240202T090420Z}{x-amz-decoded-content-length: 36}{Accept: */*}{Host: 127.0.0.1:33202}{Connection: keep-alive}{Content-Length: 209}

// for the failed request the following lines are missing

2024-02-02T10:04:20.921 DEBUG [su.ne.ww.pr.ht.HttpURLConnection] sun.net.www.MessageHeader@c7c07ff9 pairs: {null: HTTP/1.1 200}{Content-Type: application/xml}{ETag: "2408d7a077af4628de1c05c9d6b3a2a3"}{x-amz-server-side-encryption: AES256}{x-amz-request-id: 58b36a28-d34a-42ea-9d61-6c44d59d390e}{x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=}{Content-Length: 0}{date: Fri, 02 Feb 2024 09:04:20 GMT}{server: hypercorn-h11}
2024-02-02T10:04:20.922 DEBUG [so.am.aw.request] Received successful response: 200, Request ID: 58b36a28-d34a-42ea-9d61-6c44d59d390e, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
```

ApacheHttpClient:
```
2024-02-02T10:10:53.522 DEBUG [so.am.aw.request] Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=127.0.0.1, port=33204, encodedPath=/bucket/test20fc9439-fc42-4aec-bf62-655b27cf5b5c, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent], queryParameters=[])
2024-02-02T10:10:53.538 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "PUT /bucket/test20fc9439-fc42-4aec-bf62-655b27cf5b5c HTTP/1.1[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "Host: 127.0.0.1:33204[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "amz-sdk-invocation-id: 86004e60-0215-e057-7c58-4a5cf86b8ccb[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "amz-sdk-request: attempt=1; max=4[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=dummy/20240202/eu-central-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=095cafb5c7c608d21b8436217d34f0b0263daed85b25ad0b02fd73aa132e3995[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "Content-Type: application/octet-stream[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "User-Agent: aws-sdk-java/2.20.128 Linux/5.15.0-91-generic OpenJDK_64-Bit_Server_VM/17.0.8+7-jvmci-23.0-b15 Java/17.0.8 vendor/GraalVM_Community io/sync http/Apache cfg/retry-mode/legacy[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "X-Amz-Date: 20240202T091053Z[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "x-amz-decoded-content-length: 36[\r][\n]"
2024-02-02T10:10:53.539 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "Content-Length: 209[\r][\n]"
2024-02-02T10:10:53.540 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2024-02-02T10:10:53.540 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "[\r][\n]"
2024-02-02T10:10:53.541 DEBUG [or.ap.ht.wire] http-outgoing-0 << "HTTP/1.1 100 Continue[\r][\n]"
2024-02-02T10:10:53.541 DEBUG [or.ap.ht.wire] http-outgoing-0 << "date: Fri, 02 Feb 2024 09:10:53 GMT[\r][\n]"
2024-02-02T10:10:53.541 DEBUG [or.ap.ht.wire] http-outgoing-0 << "server: hypercorn-h11[\r][\n]"
2024-02-02T10:10:53.541 DEBUG [or.ap.ht.wire] http-outgoing-0 << "[\r][\n]"
2024-02-02T10:10:53.543 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "24;chunk-signature=2274bc9dccf744c32ce99710050047dc41305a308688d1708487dfea366adc88[\r][\n]"
2024-02-02T10:10:53.543 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "90a8dffa-79f3-4000-81c0-b8a3eea243f2[\r][\n]"
2024-02-02T10:10:53.543 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "0;chunk-signature=449539fe0c96c66c22b9611889ac62f31a27c0a0422f189988038bd9f9723414[\r][\n]"
2024-02-02T10:10:53.543 DEBUG [or.ap.ht.wire] http-outgoing-0 >> "[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "HTTP/1.1 200 [\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "Content-Type: application/xml[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "ETag: "dee801df668b7d852958708518f5a3e4"[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "x-amz-server-side-encryption: AES256[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "x-amz-request-id: f51347ba-5ae7-4457-a0cf-83af1ddd552b[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "Content-Length: 0[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "date: Fri, 02 Feb 2024 09:10:53 GMT[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "server: hypercorn-h11[\r][\n]"
2024-02-02T10:10:53.552 DEBUG [or.ap.ht.wire] http-outgoing-0 << "[\r][\n]"
2024-02-02T10:10:53.557 DEBUG [so.am.aw.request] Received successful response: 200, Request ID: f51347ba-5ae7-4457-a0cf-83af1ddd552b, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
```

**Comment by pko7bc** [comment] 2024-02-29 00:10
Unfortunately I made a mistake while testing this last time with `latest` tag - the error still exists when using Localstack with Java. I've just checked the `3.2` and the newest `latest`.

I have to also change my previous statement about `ApacheHttpClient` - it doesn't work. The only difference is that `ApacheHttpClient` is slightly "smarter" and retries automatically. But in general it also fails at execution no. 1001 but then recovers after 1-2 retries.

Logs for the failed 1001 execution for `ApacheHttpClient` (similar logs for 2002, 3003, ....):
```
Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=127.0.0.1, port=32795, encodedPath=/bucket/1001-test, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent], queryParameters=[])
http-outgoing-0 >> "PUT /bucket/1001-test HTTP/1.1[\r][\n]"
http-outgoing-0 >> "Host: 127.0.0.1:32795[\r][\n]"
http-outgoing-0 >> "amz-sdk-invocation-id: 830942b4-c975-9a0b-3a2a-d9d8c5a2079d[\r][\n]"
http-outgoing-0 >> "amz-sdk-request: attempt=1; max=4[\r][\n]"
http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=test/20240228/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=dac9a437a473bb1c16bfd54830873ef45a8e8da87a06685db6ebdda73d3d4b36[\r][\n]"
http-outgoing-0 >> "Content-Type: application/octet-stream[\r][\n]"
http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
http-outgoing-0 >> "User-Agent: aws-sdk-java/2.20.128 Linux/5.15.0-97-generic OpenJDK_64-Bit_Server_VM/17.0.8+7-jvmci-23.0-b15 Java/17.0.8 vendor/GraalVM_Community io/sync http/Apache cfg/retry-mode/legacy[\r][\n]"
http-outgoing-0 >> "x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD[\r][\n]"
http-outgoing-0 >> "X-Amz-Date: 20240228T221928Z[\r][\n]"
http-outgoing-0 >> "x-amz-decoded-content-length: 9[\r][\n]"
http-outgoing-0 >> "Content-Length: 181[\r][\n]"
http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
http-outgoing-0 >> "[\r][\n]"
http-outgoing-0 << "end of stream"
http-outgoing-0 >> "9;chunk-signature=7a0204981a4ec730c006bea18f3d39303d17e92fb88a2e96727ea3f618f60950[\r][\n]"
http-outgoing-0 >> "1001-test[\r][\n]"
http-outgoing-0 >> "0;chunk-signature=9c26f4a53be22945026b8fb16a20d9a315e8d80110d9dd86bdc079d91b5a502d[\r][\n]"
http-outgoing-0 >> "[\r][\n]"
http-outgoing-0 << "end of stream"
Retryable error detected. Will retry in 35ms. Request attempt number 2: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The target server failed to respond
Retrying Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=127.0.0.1, port=32795, encodedPath=/bucket/1001-test, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, Expect, User-Agent], queryParameters=[])
http-outgoing-1 >> "PUT /bucket/1001-test HTTP/1.1[\r][\n]"
http-outgoing-1 >> "Host: 127.0.0.1:32795[\r][\n]"
http-outgoing-1 >> "amz-sdk-invocation-id: 830942b4-c975-9a0b-3a2a-d9d8c5a2079d[\r][\n]"
http-outgoing-1 >> "amz-sdk-request: attempt=2; max=4[\r][\n]"
http-outgoing-1 >> "Authorization: AWS4-HMAC-SHA256 Credential=test/20240228/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=053b10594abb30de21d945a5a25ae5c1aa04a04ca742d031b16e78cb634be83e[\r][\n]"
http-outgoing-1 >> "Content-Type: application/octet-stream[\r][\n]"
http-outgoing-1 >> "Expect: 100-continue[\r][\n]"
http-outgoing-1 >> "User-Agent: aws-sdk-java/2.20.128 Linux/5.15.0-97-generic OpenJDK_64-Bit_Server_VM/17.0.8+7-jvmci-23.0-b15 Java/17.0.8 vendor/GraalVM_Community io/sync http/Apache cfg/retry-mode/legacy[\r][\n]"
http-outgoing-1 >> "x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD[\r][\n]"
http-outgoing-1 >> "X-Amz-Date: 20240228T221928Z[\r][\n]"
http-outgoing-1 >> "x-amz-decoded-content-length: 9[\r][\n]"
http-outgoing-1 >> "Content-Length: 181[\r][\n]"
http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
http-outgoing-1 >> "[\r][\n]"
http-outgoing-1 << "HTTP/1.1 100 Continue[\r][\n]"
http-outgoing-1 << "date: Wed, 28 Feb 2024 22:19:28 GMT[\r][\n]"
http-outgoing-1 << "server: hypercorn-h11[\r][\n]"
http-outgoing-1 << "[\r][\n]"
http-outgoing-1 >> "9;chunk-signature=163e8a372588b38ce0a7b1090bca5ca39617e285bb2398068664adb6a04b0a33[\r][\n]"
http-outgoing-1 >> "1001-test[\r][\n]"
http-outgoing-1 >> "0;chunk-signature=efec4c921d8873da111a82bf1ec309868b986d6e1f912deb3c9732852de28576[\r][\n]"
http-outgoing-1 >> "[\r][\n]"
http-outgoing-1 << "HTTP/1.1 200 [\r][\n]"
http-outgoing-1 << "Content-Type: application/xml[\r][\n]"
http-outgoing-1 << "ETag: "474822292f50999db74bade2bd9d689c"[\r][\n]"
http-outgoing-1 << "x-amz-server-side-encryption: AES256[\r][\n]"
http-outgoing-1 << "x-amz-request-id: 224c99c5-5208-4ef1-b9b1-674a2a7fe432[\r][\n]"
http-outgoing-1 << "x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=[\r][\n]"
http-outgoing-1 << "Content-Length: 0[\r][\n]"
http-outgoing-1 << "date: Wed, 28 Feb 2024 22:19:28 GMT[\r][\n]"
http-outgoing-1 << "server: hypercorn-h11[\r][\n]"
http-outgoing-1 << "[\r][\n]"
Received successful response: 200, Request ID: 224c99c5-5208-4ef1-b9b1-674a2a7fe432, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
```

As you can see there are two failed requests with error `"end of stream"`. And again docker logs don't contain anything about this error.

**Comment by bentsku** [comment] 2024-03-01 12:57
Hi @pko7bc and sorry to hear the issue is still present. Looks like it might be some handling of `100 Continue` which could be failing?
I can see: 
```
http-outgoing-1 << "HTTP/1.1 100 Continue[\r][\n]"
http-outgoing-1 << "date: Wed, 28 Feb 2024 22:19:28 GMT[\r][\n]"
http-outgoing-1 << "server: hypercorn-h11[\r][\n]"
http-outgoing-1 << "[\r][\n]"
```
Being, like you said, "end of stream" for failing requests. This must be on our low level gateway level and not particularly in S3. Thanks a lot for the report, we'll keep looking.

**Comment by bentsku** [comment] 2024-03-07 16:10
Hello @pko7bc, we're currently working on some experimental support for another gateway, which could solve your issue. 
Could you try starting LocalStack with the following environment variable `GATEWAY_SERVER=twisted` and see if that solves your issue? 
You'll need to pull the `latest` Docker image before that, it has been published today.

**Comment by pko7bc** [comment] 2024-03-07 20:31
No more errors with `.withEnv("GATEWAY_SERVER", "twisted")` in my simple test  :tada: 
I'll try to update my project and run all tests to see if it fixes all problems because there was also another place where it failed with the same message but in a different scenario but unfortunately it was in CI/CD pipeline and I was not able to reproduce it locally.

**Comment by bentsku** [comment] 2024-03-08 13:16
Please feel free to update us on the status! Our whole test suite is green with this flag, so it can be considered stable. If all tests are green, I think we could consider the issue closed. Thanks!

**Comment by pko7bc** [comment] 2024-03-10 18:42
All my tests passed, so it looks like the fix really works!

**Comment by bentsku** [comment] 2024-03-11 10:56
Awesome! I'll close the issue, but feel free to comment again if there is anything. As the results are really promising, we're planning to make this as default in the future. So this feature flag can be considered stable, and you can continue using it. Thanks again for the report!

**Closed by bentsku** 2024-03-11 10:56 UTC
Labels: type: bug, area: performance, area: infrastructure, aws:s3
