### ISSUE TITLE
Connection pool warning

### ISSUE THREAD

**Issue by geoynomous** [localstack/localstack#2597] opened 2020-06-21 12:43 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I often get 

  `WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: localhost `

Is this something that can be already configured, or needs a bugfix?

# Steps to reproduce
## Command used to start LocalStack
`docker run -it --rm -e SERVICES="s3,dynamodb,sqs" -e DATA_DIR="/tmp/localstack/data" -e DEFAULT_REGION="eu-west-1" -e LOCALSTACK_HOSTNAME="localhost" --rm --privileged --name ax-localstack -p 8080:8080 -p 443:443 -p 4566:4566 -v "/Users/geo/development/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="$HOME/development/localstack" "localstack/localstack:0.11.2"`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Various table creations ...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-202) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-06-21 14:50
Thanks for reporting @geoynomous . Looks like you're using image version `0.11.2` - can you please give it a try with the `latest` version of the Docker image? We've made some substantial improvements to the proxy/network layer recently, and these changes are not yet released under a new version. Please keep us posted how it goes - thanks.

**Comment by geoynomous** [comment] 2020-06-22 08:43
It still happens - though less often.

About "latest": It still writes: `LocalStack version: 0.11.2` which is confusing. Is 'latest' in docker meant to be the "next"/"canary" (then 0.11.2 is wrong) or the latest "stable" release (then 0.11.2 is correct, but it should be the same image as 0.11.2)

**Comment by JavierGarciaGarciaPiksel** [comment] 2020-07-02 06:31
I have similar issue using dynamodb streams and Apache Flink
I've created this issue:
https://github.com/localstack/localstack/issues/2652

**Comment by IsaiahJTurner** [comment] 2020-08-23 19:36
This happens if you run too many reads or writes against DynamoDB at one time (e.g. running a test suite and inserting fake data is likely to trigger this). I believe the issue stems from this: https://github.com/localstack/localstack/blob/c9559fc3b4c4e84d88c29d7373ca60d373798227/localstack/services/infra.py#L345

**Comment by MickL** [comment] 2020-08-25 12:14
Having the same problem

**Comment by IsaiahJTurner** [comment] 2020-08-31 22:55
The best fix for this is to not use Localstack for DynamoDB. Install the AWS maintained docker for dynamodb-local. After multiple projects of dealing with this bug, it was great to finally be able to make as many connections as needed!

**Comment by whummer** [comment] 2020-09-23 06:50
Thanks for the update @geoynomous @JavierGarciaGarciaPiksel @IsaiahJTurner @MickL .

The  has recently been refactored - can you please give it another try with the `latest` version?

I'd like to have a simple reproducible test case, so we can generate and compare some numbers.

Tried running this script:
```
import os
import time
import boto3
import threading
import multiprocessing.dummy

TABLE_NAME = 'test1'
STATE = {}
PARALLELIZATION = 100
LOCK = threading.RLock()

def connect():
    os.environ['AWS_ACCESS_KEY_ID'] = 'test'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'test'
    return boto3.client('dynamodb', endpoint_url='http://localhost:4566')

def create():
    client = connect()
    client.create_table(TableName=TABLE_NAME, BillingMode='PAY_PER_REQUEST',
        AttributeDefinitions=[{'AttributeName': 'id', 'AttributeType': 'S'}],
        KeySchema=[{'AttributeName': 'id', 'KeyType': 'HASH'}])

def do_insert(*args):
    inserted = STATE['inserted']
    if inserted > 0 and inserted % 100 == 0:
        delta = time.time() - STATE['start']
        print('%s sec for %s items = %s req/sec' % (delta, inserted, inserted / delta))
    result = STATE['client'].put_item(TableName=TABLE_NAME,
        Item={'id': {'S': str(inserted)}, 'name': {'S': 'Test name'}, 'zip_code': {'N': '12345'}})
    assert 'ConsumedCapacity' in result
    with LOCK:
        STATE['inserted'] += 1

def insert(count):
    STATE['client'] = connect()
    STATE['start'] = time.time()
    STATE['inserted'] = 0
    p = multiprocessing.dummy.Pool(PARALLELIZATION)
    p.map(do_insert, range(count))

def main():
    create()
    insert(1000)
    print('Inserted %s documents' % STATE['inserted'])

if __name__ == '__main__':
    main()
```

I'm getting the following numbers on a Macbook Pro:
```
6.883703947067261 sec for 100 items = 14.52706286745584 req/sec
13.311154842376709 sec for 200 items = 15.024992374312278 req/sec
20.75541615486145 sec for 300 items = 14.45405853400498 req/sec
...
```

That is pretty slow, indeed. I'm also seeing some `Connection pool is full...` warnings (depending on which `MAX_POOL_CONNECTIONS` is configured). Although the processing is slow, ultimately all requests are going through successfully. Can you confirm this behavior and these numbers?

**Comment by carmonac** [comment] 2021-11-02 16:57
I'm having same issue when I perform a lot of writing operations. I'm using localstack 0.12.8 since it's the last version which dynamodb works correctly

**Comment by whummer** [comment] 2021-12-13 11:44
Thanks @carmonac - would be great if we can get this to test with the `latest` version. Can you please elaborate, which features in DynamoDB are not working correctly with version 0.13.1 and above? 

If you could share a small reproducible example, we'll be happy to look into it in more detail. I'd suggest that we open a new Github issue for this, though, as the original issue with "connection pool is full" appears to be resolved in the meantime. Thanks!

**Closed by whummer** 2021-12-13 11:44 UTC
Labels: enhancement, needs-triaging, performance
