### ISSUE TITLE
Updating S3 object tagging for a specific version updates tagging of latest version 

### ISSUE THREAD

**Issue by lmorel3** [localstack/localstack#1667] opened 2019-10-21 14:11 UTC
Let's consider you have two versions of an object : 
1. id=A, version=1, tags = [{key=test, value=test}]
1. id=A, version=2, tags = [{key=test, value=test}]

If you try to update tags of the version 1, it'll update tags of version 2 (the latest)
`s3api put-object-tagging --bucket test --key "A" --version-id "1" --tagging "TagSet=[{Key=test, Value=updated}]`

You'll get :

1. id=A, version=1, tags = [{key=test, value=test}]
1. id=A, version=2, tags = [{key=test, value=updated}]

Regards

**Comment by usmangani1** [comment] 2020-08-07 21:23
@lmorel3 Thanks for raising the issue.

We have tried to reproduce the issue on the latest version and failed.We have attached the aws cli commands using which we tried to reproduce the issue.

```
$ awslocal s3api create-bucket --bucket my-bucket --region us-east-1

$ awslocal s3api put-bucket-versioning --bucket  my-bucket --versioning-configuration Status=Enabled

 $ awslocal s3api put-object --bucket my-bucket --key "A" --body dynamo.json 
{
    "ETag": "\"3589567500447ec47fd99a53d755af3e\"",
    "VersionId": "89c41ab8-ee86-462e-97b0-7547ea95aa6d"
}

$ awslocal s3api put-object --bucket my-bucket --key "A" --body dynamo.json 
{
    "ETag": "\"3589567500447ec47fd99a53d755af3e\"",
    "VersionId": "a4ba273d-ee29-4414-a1db-c9c33d7944f6"
}

$ awslocal s3api get-object  --bucket my-bucket --key "A" data.json
{
    "AcceptRanges": "bytes",
    "LastModified": "Fri, 07 Aug 2020 21:05:57 GMT",
    "ContentLength": 783,
    "ETag": "\"3589567500447ec47fd99a53d755af3e\"",
    "VersionId": "a4ba273d-ee29-4414-a1db-c9c33d7944f6",
    "CacheControl": "no-cache",
    "ContentEncoding": "identity",
    "ContentLanguage": "en-US",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}


$ awslocal s3api put-object-tagging --bucket my-bucket --key A  --tagging 'TagSet=[{Key=test, Value=updated}]' --version-id  "89c41ab8-ee86-462e-97b0-7547ea95aa6d"

$ awslocal s3api get-object-tagging --bucket my-bucket --key "A" --version-id  "89c41ab8-ee86-462e-97b0-7547ea95aa6d"
{
    "TagSet": [
        {
            "Key": "test",
            "Value": "updated"
        }
    ]
}

$ awslocal s3api put-object-tagging --bucket my-bucket --key A  --tagging 'TagSet=[{Key=test, Value=updated}]' --version-id  "a4ba273d-ee29-4414-a1db-c9c33d7944f6"

$ awslocal s3api get-object-tagging --bucket my-bucket --key "A" --version-id  "a4ba273d-ee29-4414-a1db-c9c33d7944f6"
{
    "TagSet": [
        {
            "Key": "test",
            "Value": "updated"
        }
    ]
}

$ awslocal s3api put-object-tagging --bucket my-bucket --key A  --tagging 'TagSet=[{Key=test, Value=changed}]' --version-id  "89c41ab8-ee86-462e-97b0-7547ea95aa6d"

$ awslocal s3api get-object-tagging --bucket my-bucket --key "A" --version-id  "89c41ab8-ee86-462e-97b0-7547ea95aa6d"
{
    "TagSet": [
        {
            "Key": "test",
            "Value": "changed"
        }
    ]
}
```
Please let us know if there are any issues regarding the same.

**Comment by whummer** [comment] 2020-08-09 12:15
Great - looks like this is already fixed in the `latest` version. Thanks for providing the steps to reproduce @lmorel3 and @usmangani1 . 👍

**Closed by whummer** 2020-08-09 12:15 UTC
