### ISSUE TITLE
bug: stack is stuck in REVIEW_IN_PROGRESS

### ISSUE THREAD

**Issue by volkanunsal** [localstack/localstack#6296] opened 2022-06-18 01:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just deployed a stack using CDK, but I can't see the resources are getting created, and the stack is stuck in REVIEW_IN_PROGRESS. 

In the logs, I see this warning

```
2022-06-17T23:34:46.798:WARNING:localstack.aws.protocol.serializer: Response object DescribeChangeSetOutput contains a member which is not specified: ChangeSetType
2022-06-17T23:34:46.798:WARNING:localstack.aws.protocol.serializer: Response object DescribeChangeSetOutput contains a member which is not specified: StackStatus
```

Here is the stack description.

```
{
  "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/backend-local/ba45d020",
  "StackName": "backend-local",
  "Description": "CDK Changeset for execution da9a13ac-b8c5-4a67-af10-48669cc42822",
  "Parameters": [
      {
          "ParameterKey": "BootstrapVersion",
          "ParameterValue": "/cdk-bootstrap/hnb659fds/version",
          "ResolvedValue": "13"
      }
  ],
  "CreationTime": "2022-06-18T01:22:21.845000Z",
  "StackStatus": "REVIEW_IN_PROGRESS",
  "StackStatusReason": "Deployment succeeded",
  "Capabilities": [
      "CAPABILITY_IAM",
      "CAPABILITY_NAMED_IAM",
      "CAPABILITY_AUTO_EXPAND"
  ],
  "Outputs": [],
  "RoleARN": "arn:aws:iam::000000000000:role/cdk-hnb659fds-cfn-exec-role-000000000000-us-east-1",
  "Tags": []
}
```

### Expected Behavior

I expect to see the stack succeed and the resources getting created.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   localstack start -d
   localstack wait -t 30
   cdklocal bootstrap aws://000000000000/us-east-1

### Environment

```markdown
- OS: Mac
- LocalStack:  0.14.4.dev
```

**Comment by MarcelStranak** [comment] 2022-06-20 10:21
Would you mind providing us with the code snippet that's failing and your full logs from LocalStack and CDK?

To activate debug logging, you will need to:
 - Set the environment variable `DEBUG=1`
 - Start LocalStack
 - Run the affected task(s)
 
Thanks.

**Comment by Warkanlock** [comment] 2022-06-30 15:34
same issue here

**Comment by volkanunsal** [comment] 2022-07-01 11:27
Yeah it does. I had to take out the localstack tests due to this issue so I
can’t reproduce it anymore.

**Comment by whummer** [comment] 2022-08-31 23:34
Hi @volkanunsal @Warkanlock, quick follow-up, we've recently added a couple of enhancements for deploying CDK stacks on LocalStack - may we ask you to give it another try after pulling the `latest` Docker image?

Would be great if you could share a few more details about your use case - ideally a minimal version of your CDK sample that helps us replicate the issue end-to-end.. Thanks!

**Comment by chomamaTheBest** [comment] 2022-09-29 07:50
I got a similar problem when deploying the following app. The stack is stucking in REVIEW_IN_PROGRESS after  `cdklocal deploy` failed.
```
import { Duration, Stack, StackProps } from "aws-cdk-lib";
import * as sns from "aws-cdk-lib/aws-sns";
import * as subs from "aws-cdk-lib/aws-sns-subscriptions";
import * as sqs from "aws-cdk-lib/aws-sqs";
import * as ssm from "aws-cdk-lib/aws-ssm";
import { Construct } from "constructs";

export class Localstack3Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const ssmParameter = ssm.StringParameter.valueForStringParameter(
      this,
      "non-existing-parameter"
    );

    const queue = new sqs.Queue(this, "Localstack3Queue", {
      visibilityTimeout: Duration.seconds(300),
    });

    const topic = new sns.Topic(this, "Localstack3Topic");

    topic.addSubscription(new subs.SqsSubscription(queue));
  }
}

```

```
LocalStack version: 1.1.1.dev
localstack-3 git:master*
🤔 cdklocal --version
2.43.1 (build c1ebb85)

localstack-3 git:master*
🤔 cdklocal bootstrap
 ⏳  Bootstrapping environment aws://000000000000/ap-southeast-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
 ✅  Environment aws://000000000000/ap-southeast-1 bootstrapped.


localstack-3 git:master*  12s
🤔 cdklocal deploy

✨  Synthesis time: 2.97s

Localstack3Stack: building assets...

[0%] start: Building 42d8c4e22f15df2d08fcdf55f992030fbc1dd602d4ac2e740fa475ad2b4e0202:000000000000-ap-southeast-1
[100%] success: Built 42d8c4e22f15df2d08fcdf55f992030fbc1dd602d4ac2e740fa475ad2b4e0202:000000000000-ap-southeast-1

Localstack3Stack: assets built

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬─────────────────────────┬────────┬─────────────────┬───────────────────────────┬─────────────────────────────────────────────────────────┐
│   │ Resource                │ Effect │ Action          │ Principal                 │ Condition                                               │
├───┼─────────────────────────┼────────┼─────────────────┼───────────────────────────┼─────────────────────────────────────────────────────────┤
│ + │ ${Localstack3Queue.Arn} │ Allow  │ sqs:SendMessage │ Service:sns.amazonaws.com │ "ArnEquals": {                                          │
│   │                         │        │                 │                           │   "aws:SourceArn": "${Localstack3Topic}"                │
│   │                         │        │                 │                           │ }                                                       │
└───┴─────────────────────────┴────────┴─────────────────┴───────────────────────────┴─────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
Localstack3Stack: deploying...
[0%] start: Publishing 42d8c4e22f15df2d08fcdf55f992030fbc1dd602d4ac2e740fa475ad2b4e0202:000000000000-ap-southeast-1
[100%] success: Published 42d8c4e22f15df2d08fcdf55f992030fbc1dd602d4ac2e740fa475ad2b4e0202:000000000000-ap-southeast-1
Localstack3Stack: creating CloudFormation changeset...

 ❌  Localstack3Stack failed: Error [ValidationError]: Stack Localstack3Stack already exists
    at Request.extractError (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-09-29T07:31:38.927Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 1912.6730551686078
}

 ❌ Deployment failed: Error: Stack Deployments Failed: ValidationError: Stack Localstack3Stack already exists
    at deployStacks (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:312:7)
    at initCommandLine (/home/user123/.config/nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/cli.ts:349:12)

Stack Deployments Failed: ValidationError: Stack Localstack3Stack already exists

localstack-3 git:master*  11s
🤨 awslocal cloudformation list-stacks --region ap-southeast-1
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-1:000000000000:stack/CDKToolkit/75268345",
            "StackName": "CDKToolkit",
            "CreationTime": "2022-09-29T07:31:10.401000+00:00",
            "LastUpdatedTime": "2022-09-29T07:31:10.401000+00:00",
            "StackStatus": "CREATE_COMPLETE",
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-1:000000000000:stack/Localstack3Stack/7cd72a55",
            "StackName": "Localstack3Stack",
            "CreationTime": "2022-09-29T07:31:37.953000+00:00",
            "LastUpdatedTime": "2022-09-29T07:31:37.953000+00:00",
            "StackStatus": "REVIEW_IN_PROGRESS",
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

**Comment by Warkanlock** [comment] 2022-09-29 09:13
> Hi @volkanunsal @Warkanlock, quick follow-up, we've recently added a couple of enhancements for deploying CDK stacks on LocalStack - may we ask you to give it another try after pulling the `latest` Docker image?
> 
> Would be great if you could share a few more details about your use case - ideally a minimal version of your CDK sample that helps us replicate the issue end-to-end.. Thanks!

Thanks for this update! I'll do it on the local pipeline and let you know. If you need a hand with something please let me know I can contribute if's needed

**Comment by whummer** [comment] 2022-10-02 12:09
Thanks @Warkanlock . Closing this issue as "cannot reproduce" for now - please let us know if the problem persists. If you can share a small, reproducible example, we'll be very happy to look into it in more detail (please create a new issue in that case).. Thanks for your help!

@chomamaTheBest looking at the error message `Stack Localstack3Stack already exists`, it seems that you are trying to deploy the CDK stack with a CloudFormation stack already existing in LocalStack, is that correct? Can you please give it another try with a fresh instance of LocalStack (empty state, also please make sure that persistence is not enabled). Please keep us posted how it goes - if the problem persists, please create a new issue with a small, fully reproducible example. Thanks!

**Closed by whummer** 2022-10-02 12:09 UTC
Labels: type: bug, area: integration/aws-cdk
