### ISSUE TITLE
Java SDK + SQS (s3 backed) + latest == The target server failed to respond

### ISSUE THREAD

**Issue by adamdavis40208** [localstack/localstack#1196] opened 2019-03-14 06:44 UTC
We have a legacy sqs connector library in java that uses the older 1.11 Java SDK.

It works fine with 0.8.6, but upgrading to latest gives a "The target server failed to respond" error on the java side, and a pretty large python error in localstack.

Localstack python error:
```
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 112, in ambiguous_response
return self.bucket_response(request, full_url, headers)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 116, in bucket_response
response = self._bucket_response(request, full_url, headers)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 157, in _bucket_response
return self._bucket_response_put(request, body, region_name, bucket_name, querystring, headers)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 452, in _bucket_response_put
forced_region = xmltodict.parse(body)['CreateBucketConfiguration']['LocationConstraint']
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 327, in parse
parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0
```

Will try to dig into this more tomorrow.

**Comment by whummer** [comment] 2019-03-14 12:04
Thanks for reporting @adamdavis40208 . Would be great if we could try to create a reproducible test case, or get a dump of the API calls made by the legacy SQS library. 👍

**Comment by adamdavis40208** [comment] 2019-03-14 18:08
Let me try to recreate with the AWS CLI. I'd hate to dump 3 pages of java code here...

**Comment by adamdavis40208** [comment] 2019-03-14 20:10
I enabled DEBUG in the java aws sdk, so apologies in advance for the structure of these dumps.

[Bad_wire_trace_latest.txt](https://github.com/localstack/localstack/files/2968258/Bad_wire_trace_latest.txt)
[Good_wire_trace_0.8.6.txt](https://github.com/localstack/localstack/files/2968259/Good_wire_trace_0.8.6.txt)

A couple of things: all of the host names are being redirected to localhost via /etc/hosts , and there is a stacktrace in localstack (so the call is making it to localstack).

It seems like a fairly simple PUT, but a simple s3api put works:


```
aws s3api put-object --bucket mine --key test.txt --body test.txt --endpoint-url http://localhost:4572
{
    "ETag": "\"2b00042f7481c7b056c4b410d28f33cf\""
}
```

I see a server side encryption header, but that still works:
```
aws s3api put-object --bucket mine --key test.txt --body test.txt --endpoint-url http://localhost:4572 --server-side-encryption AES256
{
    "ETag": "\"2b00042f7481c7b056c4b410d28f33cf\""
}
```

Any ideas what else is going on in that PUT that is causing moto to explode?

**Comment by adamdavis40208** [comment] 2019-03-14 22:38
out of curiosity, I've also updated to the latest java 1 SDK (1.11.518) and there's no change in the outcome. I'll at least sleep better now :)

**Comment by joaoqalves** [comment] 2019-03-15 15:15
I think this is the same problem we've been facing :) Our use case is:

+ Create SQS queue
+ Link it to an SNS topic

If I debug the thing slowly, it works. If I run it normally, it doesn't. @adamdavis40208 can you confirm you get something around [these lines](https://github.com/aws/aws-sdk-java/issues/1642) in the Java-side?

**Comment by adamdavis40208** [comment] 2019-03-15 16:41
Same error message -- I believe the " The target server failed to respond" would happen anytime localstack/moto threw an unexpected 500.

I'll set aside some time to dig into localstack and moto this weekend.

**Comment by adamdavis40208** [comment] 2019-03-15 21:56
I took the wire trace above and threw it all into a curl, it seems to make localstack/moto explode the same. 

So here's my recreation of this bug:

1. Spin up localstack latest
2. Run this curl:

```
curl -vvv http://127.0.0.1:4572/bb85d258-2bce-4d05-88e0-4a7d28a1d288 -X PUT --data-binary key.txt -H "x-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD" -H "Authorization: AWS4-HMAC-SHA256 Credential=/20190315/us-west-2/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-meta-user-metadata-encoded;x-amz-server-side-encryption, Signature=b0eee54d1d3dbfd2d61211f80fbc00835ff23ca0fa669841a0cb9e5b750c4d3e" -H "X-Amz-Date: 20190315T181831Z" -H "User-Agent: aws-sdk-java/1.11.518 Mac_OS_X/10.13.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.201-b09 java/1.8.0_201 vendor/Oracle_Corporation" -H "amz-sdk-invocation-id: be3101d7-9b5f-258b-f203-c2ad7fbda876" -H "x-amz-decoded-content-length: 14" -H "amz-sdk-retry: 3/64/455" -H "x-amz-server-side-encryption: AES256" -H "x-amz-meta-user-metadata-encoded: true" -H "Content-Type: application/octet-stream" -H "Content-Length: 186" -H "Connection: Keep-Alive" -H "Expect: 100-continue"
```
As it's an octet stream, you'll have to ctrl+c it.

Once you hit ctrl+c you should see a stacktrace in your localstack log.

```
[..]
localstack_1                     | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 157, in _bucket_response
localstack_1                     | return self._bucket_response_put(request, body, region_name, bucket_name, querystring, headers)
localstack_1                     | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 452, in _bucket_response_put
localstack_1                     | forced_region = xmltodict.parse(body)['CreateBucketConfiguration']['LocationConstraint']
localstack_1                     | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 327, in parse
localstack_1                     | parser.Parse(xml_input, True)
localstack_1                     | ExpatError: syntax error: line 1, column 0
```

**Comment by adamdavis40208** [comment] 2019-03-15 22:01
Hitting motoserver directly (the latest version from pypi) with this call works, I get a 200 with an error about my MD5 being a little weird:

```
Caused by: com.amazonaws.SdkClientException: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: 2X/ZDbWumexc+ngh2LROPg== in base 64) didn't match hash (etag: aa28010439eb8ee078b77353b6927ea1 in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@63dd899, bucketName: mine, key: 3f5c8d29-3ccb-45d1-9227-b4008c69a1ad)
```

So this does seem to be between localstack and moto (or the moto version localstack is pinned to)

**Comment by whummer** [comment] 2019-03-17 17:53
Thanks for digging into this @adamdavis40208 .

> As it's an octet stream, you'll have to ctrl+c it.

The reason you need to hit ctrl-c is not related to the `content-type`, but to the fact that the server is expecting 186 bytes of data (as per the `content-length` header), whereas we're only sending 7 bytes of data (`--data-binary key.txt`). I'm afraid something may have get lost (the raw chunked encoding HTTP request) in the translation to the `curl` command - any chance we can set up a small example project on Github that makes use of the original legacy SQS connnector?

**Comment by adamdavis40208** [comment] 2019-03-17 22:06
@whummer apologies in advance: I've been out of the java game for years.

I threw this together: 

https://github.com/adamdavis40208/java-sdk-localstack-test

It creates a putObject request together from a serialized request I stole from my test case that was recreating the error. 

The SDK may try to connect to "mine.localhost" or other localhost names, so some /etc/hosts trickery may be needed. 

Thanks for your eyes on this.

**Comment by adamdavis40208** [comment] 2019-03-19 17:47
btw: I've verified the above code works fine with 0.8.6 but blows up with latest. Still not sure what attributes on the put request are causing it. 

¯\_(ツ)_/¯

**Comment by sab1l** [comment] 2019-04-25 14:46
I think this ticket may be closed, I faced this issue but it does not happen anymore after https://github.com/localstack/localstack/pull/1217

**Comment by adamdavis40208** [comment] 2019-04-25 15:01
oh damn. I'll test it out and close it if true!

**Comment by adamdavis40208** [comment] 2019-04-25 15:19
Because it's s3 backed, I need s3 up and this open issue is keeping me from testing the latest changes: https://github.com/localstack/localstack/issues/1243

**Comment by whummer** [comment] 2019-08-25 20:28
Should be fixed in the latest version (with LocalStack running in Docker by default on Windows) - closing this issue. Please report here if the problem persists. Thanks

**Closed by whummer** 2019-08-25 20:28 UTC
Labels: bug, needs-triaging

**Comment by bobtiernay-okta** [comment] 2020-04-29 21:43
Seeing a similar `The target server failed to respond` issue with DynamoDB in 0.11.0 as described in https://github.com/localstack/localstack/issues/813
