### ISSUE TITLE
Localstack throws a traceback for SNS  create-platform-application 

### ISSUE THREAD

**Issue by metalheart** [localstack/localstack#4040] opened 2021-05-17 18:50 UTC
# Type of request: This is a bug

[x] bug report
[ ] feature request

# Detailed description

Localstack throws exception for SNS create-platform-application  operation when PlatformCredential parameter is empty.
```
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 178, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2069, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2054, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sns/responses.py", line 377, in create_platform_application
    attributes = self._get_attributes()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sns/responses.py", line 29, in _get_attributes
    return dict((attribute["key"], attribute["value"]) for attribute in attributes)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sns/responses.py", line 29, in <genexpr>
    return dict((attribute["key"], attribute["value"]) for attribute in attributes)
KeyError: 'value'
```
## Expected behavior

Localstack server should correctly process  the request

## Actual behavior

Localstack server returns an internal error:
```
Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```
# Steps to reproduce
aws --endpoint-url=http://0.0.0.0:4566 sns create-platform-application --name my.app --platform GCM --attributes PlatformCredential=

## Command used to start LocalStack
pipenv run localstack start

**Comment by mgagliardo** [comment] 2021-05-17 18:56
Hello @metalheart, may I ask you to run this using docker manually or compose? I have tested it out and could not reproduce it.

Log:
```
$ docker run -ti --rm -e SERVICES=sns -e DEBUG=1 -p 4566:4566 localstack/localstack:latest
Waiting for all LocalStack services to be ready

...

Ready.
2021-05-17T18:54:39:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 6144.612789154053ms
2021-05-17 18:54:53,277:API: 127.0.0.1 - - [17/May/2021 18:54:53] "POST / HTTP/1.1" 200 -
```

CLI:
```
$ aws --endpoint-url=http://localhost:4566 sns create-platform-application --name my.app --platform GCM --attributes PlatformCredential=
{
    "PlatformApplicationArn": "arn:aws:sns:us-east-1:000000000000:app/GCM/my.app"
}
```

**Comment by mgagliardo** [comment] 2021-05-19 02:23
Could not reproduce this on Mac and Linux. Closing it.

**Closed by mgagliardo** 2021-05-19 02:23 UTC
Labels: awaiting reporter response, cannot-reproduce
