### ISSUE TITLE
Add documentation for multi-server

### ISSUE THREAD

**Issue by jacobisaliveandwell** [localstack/localstack#2173] opened 2020-03-19 09:10 UTC
It seems like localstack runs a proxy

```
Starting multi API server process on port 51492
```

but there is no documentation on this service. Looking at the code, it seems like it's purpose is only to list what services local stack is running?

```
curl http://localhost:51492/servers
{"__server__": {"port": 51492, "thread": null}, "apigateway": {"port": 4566, "thread": null}, "cloudwatch": {"port": 4582, "thread": null}, "ec2": {"port": 4556, "thread": null}, "iam": {"port": 4557, "thread": null}, "logs": {"port": 4553, "thread": null}, "redshift": {"port": 4577, "thread": null}, "route53": {"port": 4580, "thread": null}, "s3": {"port": 4563, "thread": null}, "secretsmanager": {"port": 4552, "thread": null}, "ses": {"port": 4551, "thread": null}, "sns": {"port": 4562, "thread": null}, "ssm": {"port": 4583, "thread": null}, "sts": {"port": 4592, "thread": null}, "events": {"port": 4554, "thread": null}}
```

If this is all, would it be out of line to open a PR to make this proxy act as a general purpose ingress for all the endpoints?

Edit: looks like there is [a dedicated project](https://github.com/mhmoudgmal/localstack-single-endpoint) to achieve what I'm asking, but I'd bet a lot of magic internet points (that's what we all work for, right?) that I'm not the only one that would rather have this built in.

**Comment by whummer** [comment] 2020-04-04 17:52
Thanks for this suggestion @jacobisaliveandwell - looks like a duplicate of #151 . As you correctly pointed out, port 51492 in multiserver is not an API entry point, but a configuration endpoint that allows to list the status of individual APIs.

A major change has been added in #2250 . Starting with version `0.11.0`, all APIs are now exposed via a single _edge service_, which is accessible on http://localhost:4566 by default (see updated instructions in the [README](https://github.com/localstack/localstack#overview)).

Can you please give it a try with the `latest` version of the Docker image, and report here if there are any issues accessing the services via the edge URL http://localhost:4566 . Thanks

**Closed by whummer** 2020-04-04 17:52 UTC

**Comment by jacobisaliveandwell** [comment] 2020-09-15 21:08
@whummer now it looks like this has changed ports without any documentation :(

```
2020-09-15T21:05:34:INFO:localstack.multiserver: Starting multi API server process on port 37895
```

I would like to depend on this service. Is there a plan for this to become stable??

**Comment by jacobisaliveandwell** [comment] 2020-09-15 21:35
I see that `multiserver.main()` tries to pull the port from the arguments, but this doesn't work using the docker image, which I'm pretty sure is swallowing passed arguments.
