### ISSUE TITLE
enhancement request: Secrets Manager does not implement `batch_get_secret_value`

### ISSUE THREAD

**Issue by frank-lenormand** [localstack/localstack#10661] opened 2024-04-15 10:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

The Secrets Manager endpoint doesn’t implement the `batch_get_secret_value` action.

Attempting to invoke it via `boto3` yields the following error:

```
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the BatchGetSecretValue operation: The batch_get_secret_value action has not been implemented
```

### 🧑‍💻 Implementation

The reference can be found on the API documentation for `boto`:
https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager/client/batch_get_secret_value.html

**Comment by macnev2013** [comment] 2024-04-16 08:36
Hello, This is a duplicate of https://github.com/localstack/localstack/issues/9982, so I am closing the issue. Please follow the discussion and updates there. Thanks for reporting.

**Closed by macnev2013** 2024-04-16 08:36 UTC
Labels: type: enhancement, aws:secretsmanager, status: backlog

**Comment by frank-lenormand** [comment] 2024-04-16 08:44
Sorry for the noise, I missed that issue!
