### ISSUE TITLE
projection against base table succeeds when querying on a GSI

### ISSUE THREAD

**Issue by bgvozdev** [localstack/localstack#478] opened 2017-11-22 00:28 UTC
I have a GSI against a table. The following command succeeds on localstack but fails on aws dynamo with `An error occurred (ValidationException) when calling the Query operation: One or more parameter values were invalid: Global secondary index my_index does not project [table_column]`:

```
 aws dynamodb query \
--table-name my_table \
--endpoint=http://127.0.0.1:8006 \
--index-name="my_gsi_index" \
--key-condition-expression="#gsi_partition_hash_key = :gsi_partition_hash_key" \
--expression-attribute-names='{#gsi_partition_hash_key": "my_gsi_partition_hash_key"}' \
--expression-attribute-values='{ ":gsi_partition_hash_key": {"S": "some_value"}}' \
--projection-expression="some_column_from_my_table_not_projected_in_gsi"
```

**Comment by whummer** [comment] 2017-11-24 23:14
Thanks for reporting @bgvozdev . Can you please provide more details about how the table is created (table structure, indexes, data, ...). Ideally, if you could create a small example project on Github, that would make it a lot easier to reproduce the error. Thanks

**Comment by bgvozdev** [comment] 2017-12-28 03:48
Sorry for the long reply. Here's what I did:
```
#
# Create a table with a GSI
#
aws dynamodb create-table \
      --table-name my_table \
      --attribute-definitions \
            AttributeName=my_partition_key,AttributeType=S \
            AttributeName=my_range_key,AttributeType=S \
            AttributeName=a_attr_gsi_key,AttributeType=S \
      --key-schema \
            AttributeName=my_partition_key,KeyType=HASH \
            AttributeName=my_range_key,KeyType=RANGE \
      --global-secondary-indexes \
            IndexName=my_gsi,KeySchema=["{AttributeName=my_partition_key,KeyType=HASH}","{AttributeName=a_attr_gsi_key,KeyType=RANGE}"],Projection="{ProjectionType=INCLUDE,NonKeyAttributes=b_attr_gsi_projected}",ProvisionedThroughput="{ReadCapacityUnits=10,WriteCapacityUnits=10}"\
      --provisioned-throughput=ReadCapacityUnits=10,WriteCapacityUnits=10 \
--endpoint=http://localhost:4569

#
# Insert an item with an attribute "c_attr_not_projected" that wasn't projected in GSI
#
aws dynamodb put-item --table-name my_table \
    --item '{
      "my_partition_key" : {
        "S": "partition1"
      },
      "my_range_key" : {
        "S": "range1"
      },
      "a_attr_gsi_key" : {
        "S": "gsi_partition1"
      },
      "b_attr_gsi_projected" : {
        "S": "gsi_projected1"
      },
      "c_attr_not_projected" : {
        "S": "non_gsi"
      }
    }' \
--endpoint=http://localhost:4569

#
# Launch a query against GSI and ask to project that attribute that was not in the list of projected attributes
#
aws dynamodb query \
  --table-name my_table \
  --index-name my_gsi \
  --key-condition-expression "#key=:value" \
  --expression-attribute-names ' {
    "#key" : "my_partition_key"
  }' \
  --expression-attribute-values '{
    ":value" : {
      "S": "partition1"
    }
  }' \
  --projection-expression="c_attr_not_projected" \
  --endpoint=http://localhost:4569

```

For localstack, I receive the queried attribute. When doing the same against "real" AWS, I receive

```
An error occurred (ValidationException) when calling the Query operation: One or more parameter values were invalid: Global secondary index my_gsi does not project [c_attr_not_projected]
```

**Comment by bgvozdev** [comment] 2017-12-28 05:46
Posted it here too: https://forums.aws.amazon.com/thread.jspa?threadID=270295 , seems this is a bug in DynamoDB local.

**Comment by whummer** [comment] 2019-08-25 18:40
Closing as solved - seems to be working in the latest version. Thanks @bgvozdev

**Closed by whummer** 2019-08-25 18:40 UTC
Labels: bug, needs-triaging, upstream-issue
