### ISSUE TITLE
ContentBasedDeduplication=false in SNS is always true

### ISSUE THREAD

**Issue by dandsafe** [localstack/localstack#10084] opened 2024-01-17 12:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

awslocal sns create-topic --name mysns.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false

ignores the ContentBaseDeduplication for false. It is always true.

In the Web App I can see

![grafik](https://github.com/localstack/localstack/assets/153176362/3010cbb6-5c39-4a32-97e8-5434636a5fec)

You can also create the same over the Web UI. ContentBasedDeduplication is always TRUE .

> 

> 

### Expected Behavior

awslocal sns create-topic --name mysns.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false

should set ContentBasedDeduplication to false.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal sns create-topic --name mysns.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false

### Environment

```markdown
- OS: Windows 11
- LocalStack: 3.0.2
```

**Comment by bentsku** [comment] 2024-01-25 12:37
Hello @dandsafe and thanks for your report!

I just gave it a try and I could not reproduce the error with both `3.0.2` and the `latest` versions:

```bash
$ awslocal sns create-topic --name mysns.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false
{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:mysns.fifo"
}
$  awslocal sns get-topic-attributes --topic-arn arn:aws:sns:us-east-1:000000000000:mysns.fifo
{
    "Attributes": {
        "Owner": "000000000000",
        "Policy": "{\"Version\":\"2008-10-17\",\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Effect\":\"Allow\",\"Sid\":\"__default_statement_ID\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"SNS:GetTopicAttributes\",\"SNS:SetTopicAttributes\",\"SNS:AddPermission\",\"SNS:RemovePermission\",\"SNS:DeleteTopic\",\"SNS:Subscribe\",\"SNS:ListSubscriptionsByTopic\",\"SNS:Publish\",\"SNS:Receive\"],\"Resource\":\"arn:aws:sns:us-east-1:000000000000:mysns.fifo\",\"Condition\":{\"StringEquals\":{\"AWS:SourceOwner\":\"000000000000\"}}}]}",
        "TopicArn": "arn:aws:sns:us-east-1:000000000000:mysns.fifo",
        "DisplayName": "",
        "SubscriptionsPending": "0",
        "SubscriptionsConfirmed": "0",
        "SubscriptionsDeleted": "0",
        "DeliveryPolicy": "",
        "EffectiveDeliveryPolicy": "{\"defaultHealthyRetryPolicy\": {\"numNoDelayRetries\": 0, \"numMinDelayRetries\": 0, \"minDelayTarget\": 20, \"maxDelayTarget\": 20, \"numMaxDelayRetries\": 0, \"numRetries\": 3, \"backoffFunction\": \"linear\"}, \"sicklyRetryPolicy\": null, \"throttlePolicy\": null, \"guaranteed\": false}",
        "FifoTopic": "true",
        "ContentBasedDeduplication": "false"  # here we can see it is set to false
    }
}
```

It seems this is an issue in the WebUI, and I will forward this issue! The UI reports it as `Yes` when it is really set to `false`.

Did you encounter any issue related to this? Thanks!

**Comment by dandsafe** [comment] 2024-01-25 12:48
I can confirm that the get-topic-attributes says false and the web ui true. 

I created another issue here https://github.com/localstack/localstack/issues/10088. I don`t know if this is something of the same problem.

Best case would be only an visual bug in the WebUI and https://github.com/localstack/localstack/issues/10088 is another problem.

**Comment by bentsku** [comment] 2024-01-25 12:57
Thanks, I've forwarded to the WebUI team, I'll update here once this is fixed.

In the meantime, I'll start looking at your other report and will update on that issue the findings. Thanks again!

**Comment by bentsku** [comment] 2024-02-13 22:05
Hello @dandsafe!

This should now be fixed in the Web UI:
<img width="206" alt="Screenshot 2024-02-13 at 23 04 22" src="https://github.com/localstack/localstack/assets/42031100/d80e56c2-cd6f-490e-8efd-9b26f0d89600">

I'll close the issue as this should be fixed, feel free to comment and re-open if that's not the case.

Thanks!

**Closed by bentsku** 2024-02-13 22:05 UTC
Labels: type: bug, area: web, aws:sns, status: in progress
