### ISSUE TITLE
bug: KMS provides invalid signature by ignoring MessageType

### ISSUE THREAD

**Issue by dissoupov** [localstack/localstack#6815] opened 2022-09-04 08:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that Sign operation ignores MessageType. 
As per AWS documentation the MessageType can be "DIGEST", that means the digest is already computed and just needs to be signed. 
https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html

Localstack ignores this parameter:
https://github.com/localstack/localstack/blob/5fafd1b68f31f5948ec88b00a85966319c2ce8c3/localstack/services/kms/provider.py#L332

In GoLang the `Sign` interface takes the digest, not the raw message.
`Sign(rand io.Reader, digest []byte, opts crypto.SignerOpts)`
Therefore Sign/Verify operations in Go fail by using localstack.

### Expected Behavior

Use `MessageType` parameter and do not compute the digest when MessageType==`DIGEST`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Use Sign/Verify in GoLang

### Environment

```markdown
- OS: ubuntu
- LocalStack: latest
- GoLang 1.19
```

**Comment by taras-kobernyk-localstack** [comment] 2022-09-07 14:52
It doesn't look like we generate digests, just sign whatever we get.
And the AWS doc page you mention says that digests are only generated for messages longer than 4K: "To sign a larger message, generate a hash digest of the message, and then provide the hash digest in the Message parameter".

I am not familiar with the implementation in Go. But as a workaround, I imagine, it should work if you generate digests and then use them both in Go sign/verify calls and in your calls to LocalStack KMS.

As for a proper fix - we have a new version of our KMS code coming. Hopefully in a few days. After that I will add the logic for the MessageType parameter. Will update the ticket. And if you would be able to check afterwards if it works with Go - would be great!

**Comment by dissoupov** [comment] 2022-09-07 15:52
My existing code works with AWS KMS and with nsmithuk/local-kms
and fails with localstack.
I will gladly test your new implementation.
Thanks,
Denis

**Comment by taras-kobernyk-localstack** [comment] 2022-10-17 09:42
Hi Denis,

Apologies for the delay. The change is finally there. If you update your docker image for LocalStack, you should have it.

Let me know if it works for your setup. If it doesn't - which is quite a possibility, as I can't understand why it wasn't working with our old setup - could you please provide me with some simple code that uses these APIs, so I could run the code on my side and debug the issue further without bothering you?

Thanks,
Taras

**Comment by cwkang1998** [comment] 2022-11-10 06:26
Hey @taras-kobernyk-localstack , sorry if this is a dumb question on my part but I would like to confirm that this change is in fact not released in github (as github latest is 1.2.0) nor as a specific verison yet. However, this is available via the `latest` tag in docker?

Currently having issues with signing and verifying with well known examples involving the use of `DIGEST`, not sure if related or not. Going to try out with comparison with live AWS KMS and the latest docker image and report back later.

**Comment by cwkang1998** [comment] 2022-11-10 07:31
Just tested with the latest docker image and live AWS KMS, and found out some things:

Sign Digest works nicely with live AWS KMS, and the return values + tests works as expected.

However, when working with localstack latest, it seems it does not work as expected (In that the produced signature is invalid for my case in respect to the public key).

I believe the issue that I am encountering is not related to this issue, as mine directly deals with the digest message, which is not affected by the problem described by this issue in the first place, so if neede I can open another issue for tracking.

The code I am working on is this https://gist.github.com/dangdennis/3383b554f3c3ffe05356988b91a0d769, which have an expected behaviour of `getSigV` working as expected and have v values of 27 or 28 (It'll throw otherwise, and I am aware the gist I sent shows 17 & 28, its an error). This works as expected with AWS KMS, however when done in localstack, it'll recover the incorrect public key and throw an error.

**Comment by cwkang1998** [comment] 2022-11-10 08:38
Just to follow up on this, found out that the reason why my use case did not work was that `localstack` has yet to support asymmetric keys. I see that there are no issues open for the support of asymmetric keys as of now, is there any plans to support it and any challenges surrounding its implementation? Would be happy to contribute to the implementation of support for ECC keys.

In the meantime, I think a warning message during the creation of asymmetric keys should be given regarding the lack of support for it in regards of signing and other relevant operations, which will help people like me to find out the cause of the issue earlier.

**Comment by taras-kobernyk-localstack** [comment] 2022-11-10 13:09
@cwkang1998 Sign / Verify operations use asymmetric keys for signatures. But we currently ignore [SigningAlgorithm](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html#API_Sign_RequestSyntax) and always [calculate](https://github.com/localstack/localstack/blob/256b0de1f1a6085d3994e8d1322c763962ded2f0/localstack/services/kms/models.py#L229) SHA256 digests.

I can't see why that would matter, though. As long as you call LocalStack for both Sign and Verify, the verification should succeed, as the digest would be calculated the same way. Unless you have some setup where you sign a message with a call to AWS / LocalStack, but then verify the signature by yourself. Let me know if that is the case. Implementing different signatures based on `SigningAlgorithm` might help then.

Not sure, though, it is the same issue as @dissoupov has. So we can spawn a separate issue for various signature algorithms.

Another thing is - I have no idea what those `v` values in your code are. While `r` and `s` are a part of the Elliptic Curve Digital Signature Algorithm, `v` seems to be something related to BitCoin / Ethereum implementation, and I am not familiar with those. So if you could explain me what that `v` parameter does - it would greatly help.

**Comment by dissoupov** [comment] 2022-11-10 13:39
Verify with asymmetric key is performed locally, so in go lang it fails.
Local stack should respect parameters and not calculate hash if DIGEST flag
is passed,
That means the hash is already computed and simply needs to be signed with
private key

**Comment by taras-kobernyk-localstack** [comment] 2022-11-10 14:22
@dissoupov Could you please provide us with a code that fails with LocalStack, but succeeds with AWS?

We only calculate digests if [MessageType](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html#API_Sign_RequestSyntax) is set to `RAW`. And prior to https://github.com/localstack/localstack/pull/6941 there was no digest calculation at all. So if something fails for you with `MessageType` set to `DIGEST` - it might be something other than the digests. But I can't understand, what is wrong, unless I know what what kind of steps are you taking.

**Comment by taras-kobernyk-localstack** [comment] 2022-11-10 14:43
@cwkang I have just created https://github.com/localstack/localstack/issues/7158 for the digests issue.

Still would be very helpful to get some simplified code that works against AWS, but fails against LocalStack. Ideally - CLI commands that would demonstrate the difference. As otherwise we would have to figure out internal implementation of libraries your code might use. But anything might help.

**Comment by cwkang1998** [comment] 2022-11-11 17:59
> I can't see why that would matter, though. As long as you call LocalStack for both Sign and Verify, the verification should succeed, as the digest would be calculated the same way. Unless you have some setup where you sign a message with a call to AWS / LocalStack, but then verify the signature by yourself. Let me know if that is the case. Implementing different signatures based on `SigningAlgorithm` might help then.

Yup, in this case I am verifying it locally after signing, in fact, in my use case I am decoding the signature from DER format to SEC format (Or just its raw form of r and s concatenated). The key is used in multiple places locally and I am attempting to recover the public key back from r and s, which fails probably due to not having asymmetric keys. I suck at explaining math tbh, but here's a short description of the process https://cryptobook.nakov.com/digital-signatures/ecdsa-sign-verify-messages#ecdsa-public-key-recovery-from-signature.

> Not sure, though, it is the same issue as @dissoupov has. So we can spawn a separate issue for various signature algorithms.

I apologize, but I would say that its my misunderstanding that caused this. I believe this is a separate case in which the lack of support for asymmetric keys caused me to assume that it has something to do with digest computation. Although I am not very sure that digest are computed differently based on signing algorithm, I think my problem is simply due to the lack of the support for ECDSA

> Another thing is - I have no idea what those `v` values in your code are. While `r` and `s` are a part of the Elliptic Curve Digital Signature Algorithm, `v` seems to be something related to BitCoin / Ethereum implementation, and I am not familiar with those. So if you could explain me what that `v` parameter does - it would greatly help.

Its meant to be a recovery parameter for use in the the recovery of the public keys from a certain signature. A single signature might resolve to 2 possible public key given just the r and s value, and v value is there to help determine a single public key stated here https://cryptobook.nakov.com/digital-signatures/ecdsa-sign-verify-messages#ecdsa-public-key-recovery-from-signature.

Currently, as the signature was done via the use of a symmetric key, this process (of recovering public key from signature) would yield incorrect result and would not resolve to the public key gotten from `GetPublicKey`, causing my attempt to calculate a correct v value based on Ethereum's standard (which is going to be either 27 or 28) to fail. The v value in this case is required for me to craft a valid Ethereum transaction consisting of r,s & v, accepted by their standard regarding signatures.

**Comment by cwkang1998** [comment] 2022-11-11 18:06
> @cwkang I have just created #7158 for the digests issue.
> 
> Still would be very helpful to get some simplified code that works against AWS, but fails against LocalStack. Ideally - CLI commands that would demonstrate the difference. As otherwise we would have to figure out internal implementation of libraries your code might use. But anything might help.

Thanks for the help! As stated before, I believe that my issue has nothing directly to do with digest, but instead have more to do with the support towards SECP256K1 asymmetric key's support in localstack. However, I think its a great idea to check if other asymmetric signature work as expected with the same digest generation.

I'll try to produce some simple code for both the digests and also the asymmetric signing of specifically ECDSA 256 with SECP256k1, as its the use case that I am familiar with. Not sure if other elliptic curves work similarly and how their recovery works, but if I could find out I'll also include those. 

Regardless, thanks for your work!

**Comment by paullallier** [comment] 2023-03-07 17:40
Localstack 1.3.1, PHP 8.2, AWS SDK PHP 3.258.5

I think I'm seeing something related to this, so I wanted to add some info in case it helps resolve the issue.

I'm working on using the AWS KMS sign function (and the Localstack equivalent) for signing JWTs in my app, using ECDSA 256 keys, and I've found inconsistency.

I've tried signing the same message each time - `eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0`
'SigningAlgorithm' => 'ECDSA_SHA_256'
And checking the JWT validity using the checker at https://jwt.io/

### With AWS KMS, calling Sign with 'MessageType' = 'RAW':
JWT:
`eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.Oh4nCbADlbc9zHmm5ypM2dFPrvjBNIPEzc7lnlms0SdnNVbfgXjxkVHXyAz9_sx47T4FyNzPQ0euiMah5rqMIQ`

pub key:
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsCRUKrhJKsujjhzP9LZm/Qnp/od7
tZgAJldnWxGvFVedhdDXjTVXfrlTFJUqrmdEpCPZYM5oyuAc5QPGvSm5dg==
-----END PUBLIC KEY-----
```

Outcome - **Signature Verified**

### With AWS KMS, calling Sign with MessageType = 'DIGEST':
```
Error executing "Sign" on "https://kms.eu-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://kms.eu-west-2.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"ValidationException","message":"Digest is invalid length for algorithm ECDSA_SHA_256."}
 ValidationException (client): Digest is invalid length for algorithm ECDSA_SHA_256. - {"__type":"ValidationException","message":"Digest is invalid length for algorithm ECDSA_SHA_256."}
```

### Localstack, calling Sign with 'MessageType' = 'RAW':
JWT:
`eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.RWyfwz8hTHnukIeRt6tVvQhfCLdEs9vfnLNGgkfdGxDSgxW3Wt_zc3qCnZjBhN1jRfIPgBHafk6hj-p8Xgqwqg`

pub key:
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbR/JO0fppz3tEnUhhbk2DxJr+GcP
pAumyf5yFAg5w+p2m+XpB6lUFdObMOyiUHVAiYKIAjX718VBplviZ7qCaw==
-----END PUBLIC KEY-----
```

Outcome - **Invalid Signature**

### Localstack, calling Sign with 'MessageType' = 'DIGEST':
JWT:
`eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.6KcQ-kKrJFOYkVFCJnuC4uT75JzLD0GZqJmtCVwMTfiUGYAHTOUXEAEC7h3_azVlPXZHeJ7zHiVZfN3JoCJNbA`

pub key:
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJ44NC/6WrzI/zv8oywQnDHs9V5LQ
Fm+5oAyjzn0uu+GZwhN4xeq8JQz+WBpXDl9ELKQmFHWk4cyAgvawMf3CAA==
-----END PUBLIC KEY-----
```

Outcome - **Signature Verified**

### Summary

So, at least in this particular case, Sign in localstack with DIGEST seems to be working the same as Sign in AWS KMS with RAW.  And, indeed, for this particular message, DIGEST on AWS just throws an error.

**Comment by paullallier** [comment] 2023-03-07 20:38
@taras-kobernyk-localstack: Looking at your PR related to DIGESTs in KMS sign, I think your logic is sound, but the fact that my real KMS RAW matches the localstack DIGEST version (in terms of validity)...

I think what might be happening - and my Python is almost non-existant so sorry if I'm completely wrong - is that the ec signing call is hashing the data a second time (so the AWS RAW version is hashed once, and the localstack DIGEST version is hashed once - which is why they validate).

Potentially you effectively have this, which would hash the data again before signing:
```
signature = private_key.sign(
    data,
    ec.ECDSA(hashes.SHA256())
)
```

And, because you've already hashed it - or the user has if they are calling with MethodType = DIGEST - you actually want this:
```
sig = private_key.sign(
    digest,
    ec.ECDSA(utils.Prehashed(hashes.SHA256()))
)
```
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#elliptic-curve-signature-algorithms

Does that make any sense or am I way off the mark?

(I planned to test this a bit more by signing some prehashed messages, but I'm struggling to get that into a form that AWS will accept - I just get AWS complaining that the digest is the wrong length.)

**Closed** 2023-03-17 06:44 UTC
Labels: type: bug, status: resolved/fixed, aws:kms
