### ISSUE TITLE
Localstack S3 returns 404 in certain networking scenario

### ISSUE THREAD

**Issue by bwidmeier** [localstack/localstack#613] opened 2018-02-13 14:12 UTC
Not entirely sure what the exact scenario is, but I do have a repro case (This is on OSX with Docker for Mac):
- `docker run --name localstack -d -e SERVICES=sqs:4576,s3:4572 -p 4576:4576 -p 4572:4572 localstack/localstack`
- (from host) `aws --endpoint http://localhost:4572 s3 mb s3://test` (successfully creates bucket)
make_bucket: test
- (from host) `aws --endpoint http://localhost:4572 s3 ls` (lists the `test` bucket)
2006-02-03 17:45:09 test
- `docker run --link localstack -e AWS_ACCESS_KEY_ID=a -e AWS_SECRET_ACCESS_KEY=b -e REGION=c -it fstab/aws-cli`
- (from container) `aws --endpoint http://localstack:4572 s3 ls`
2006-02-03 17:45:09 test
- (from container) `aws --endpoint http://docker.for.mac.localhost:4572 s3 ls`

An error occurred (NoSuchBucket) when calling the ListBuckets operation: The specified bucket does not exist

For whatever reason, localstack seems not to like connections made via the docker.for.mac.localhost address, while it does work when using the docker link address.

**Comment by whummer** [comment] 2018-03-05 14:31
Thanks for reporting @bwidmeier . This is most likely caused by an issue with S3's domain-based vs path-based addressing (see also the note on "path style access" in the [README](https://github.com/localstack/localstack#troubleshooting)). Can you try setting the following config parameter (taken from [here](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html)):
```
aws configure set default.s3.addressing_style path
```

**Comment by bwidmeier** [comment] 2018-03-05 14:52
@whummer Unfortunately, that does not help.

From host:

```
$ docker run --name localstack -d -p 4572:4572 localstack/localstack
e1b2167b7687422d4df4d2524fab4fe983484759abc62f7d3254b2a24d712480
$ aws --endpoint http://localhost:4572 s3 mb s3://test
make_bucket: test
$ docker run --link localstack -e AWS_ACCESS_KEY_ID=a -e AWS_SECRET_ACCESS_KEY=b -e REGION=c -it fstab/aws-cli
(env) aws@4738ed50a170:~$ aws configure set default.s3.addressing_style path
(env) aws@4738ed50a170:~$ aws --endpoint http://localstack:4572 s3 ls
2006-02-03 17:45:09 test
(env) aws@4738ed50a170:~$ aws --endpoint http://docker.for.mac.localhost:4572 s3 ls

An error occurred (NoSuchBucket) when calling the ListBuckets operation: The specified bucket does not exist
```

**Comment by dekryptic** [comment] 2018-05-02 15:49
I solved this temporarily by setting up an nginx proxy that sets the `Host` to `localhost`.

**Comment by FlorianDewulf** [comment] 2018-05-03 07:56
I have the same kind of issue.
I have a localstack on my computer (for the dev) and one on a server (for the staging).
- If I go with my browser on http://localhost:4572/my-bucket/ : I have a list of my files (in a xml)
- If I go with my browser on my staging website, let's imagine http://my.staging.website:4572/my-bucket/ : I have a **404** error
- If I curl http://localhost:4572/my-bucket/ in the localstack container on the staging server : I have the list of my files
- If I curl http://localhost:4572/my-bucket/ on the staging server : I have the list of my files

It seems localstack doesn't like the subdomains or anything different than localhost ?
I think I will make a proxy too...

**Comment by whummer** [comment] 2018-05-20 19:28
@bwidmeier @FlorianDewulf @dekryptic This should be fixed in #772 - can you please give it a try with the latest version on `master` (or the `latest` Docker image).

**Comment by baohx2000** [comment] 2018-05-30 21:49
I'm getting a 404 on `latest` but it works fine on `0.8.0`

**Comment by trp956s** [comment] 2018-06-21 13:05
I keep getting 404 regardless of degrading to 0.8.0 (which reports an error with elastic search).
0.8.1-latest both return 404 when running ``aws --endpoint-url=http://localhost:4567 apigateway get-domain-names``

**Comment by rmsmani** [comment] 2020-04-06 11:40
Ran the below commands in the `latest version (as of 05Apr2020) using docker and it works fine.`
```
docker run --name localstack -d -e SERVICES=sqs:4576,s3:4572 -p 4576:4576 -p 4572:4572 localstack/localstack

 aws --endpoint http://localhost:4572 s3 mb s3://test
output ::: 
 make_bucket: test

aws --endpoint http://localhost:4572 s3 ls 
2020-04-06 21:30:58 test

aws --endpoint http://mymachine-123:4572 s3 ls
2020-04-06 21:30:58 test

```
Output from the browser
upon running the `http://mymachine-123:4572 `

```
<ListAllMyBucketsResult>
<Owner>
<ID>bcaf1ffd86f41161ca5fb16fd081034f</ID>
<DisplayName>webfile</DisplayName>
</Owner>
<Buckets>
<Bucket>
<Name>test</Name>
<CreationDate>2020-04-06T11:30:58.897822Z</CreationDate>
</Bucket>
</Buckets>
</ListAllMyBucketsResult>
```

**Comment by rmsmani** [comment] 2020-04-06 11:41
@whummer I think we can close this

**Comment by scirlig-ellation** [comment] 2020-05-04 12:53
This is more of a Docker issue, due to not having enough space on the disk. Try cleaning up unused images, or increasing the Docker allocated space from the application in case you're using it on OSX/Windows

**Comment by whummer** [comment] 2020-05-04 16:40
Thanks for confirming that it works @rmsmani , and thanks @scirlig-ellation for providing possible fixes for Docker environments. 👍

**Closed by whummer** 2020-05-04 16:40 UTC
Labels: configuration, question

**Comment by konsumer** [comment] 2020-09-24 02:03
I may be confused, but I am getting same issue with latest docker and a volume-mounted `/tmp/localstack` (which covers having enough  s3 storage, right?) THis could be totally unrelated, I'm really not sure.

I use this command:

```
docker run -d --rm --privileged \
  -e LOCALSTACK_SERVICES=dynamodb,s3,cloudformation \
  -e DEBUG=1 \
  -e DEFAULT_REGION="us-west-2" \
  -e LOCALSTACK_HOSTNAME="localhost" \
  -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" \
  -p 4566-4620:4566-4620 -p 12121:12121 -p 8080-8081:8080-8081  \
  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" \
  "localstack/localstack"
```

I use cloudformation to setup the S3 bucket, initially (and it shows up in `awslocal cloudformation list-stack-resources`). I get a  signed URL for uploading, and the upload seems to succeed, but I get a 404 (with `NoSuchBucket`) when I try to request the thing I just uploaded.

I can make a simplified test-project, if that would help explain it.

**Comment by kanchanapy** [comment] 2021-07-02 18:08
Thank you @scirlig-ellation, spent so much time troubleshooting and looking in the wrong direction but finally found the solution through your suggestion!!
