### ISSUE TITLE
bug: Standard Amazon SQS queue has maximum batch size of 10

### ISSUE THREAD

**Issue by albulesculoredana** [localstack/localstack#8188] opened 2023-04-24 11:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to deploy a lambda with an sqs trigger and batch size of 1000 it fails with `Error applying changes for CloudFormation stack "sqs-local": An error occurred (InvalidParameterValueException) when calling the CreateEventSourceMapping operation: BatchSize 1000 exceeds the max of 10 Traceback (most recent call last):`

### Expected Behavior

According to the AWS Documentation the maximum batch size for a standard (not FIFO) SQS queue can be 10000. 

### How are you starting LocalStack?

With the `localstack` script

### serverless.yml
```
service: locastack-test
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    NODE_ENV: dev
plugins:
  - serverless-localstack
custom:
  localstack:
    stages: [local]
    host: http://127.0.0.1
    debug: true
functions:
  processSQSRecord:
    handler: processSQSRecord.handle
    memorySize: 512
    timeout: 120
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - mySQSQueue
              - Arn
          batchSize: 1000
          maximumBatchingWindow: 2
resources:
  Resources:
    mySQSQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: mySQSQueue
        VisibilityTimeout: 60
```

### Environment

```markdown
- OS:AWS Linux Workspace
- LocalStack:2.0
```

### Anything else?

[sqslogs.txt](https://github.com/localstack/localstack/files/11309810/sqslogs.txt)

**Comment by thrau** [comment] 2023-05-02 11:44
Hi @albulesculoredana, thanks for reporting. Just letting you know that is a known limitation in our Lambda SQS event source mapping implementation. Because `receive_message` only allows a call with at most 10 messages, we would have to change the loop behavior in our queue polling implementation, and we haven't gotten around to doing that yet.

Here's the affected code
https://github.com/localstack/localstack/blob/821377073f7aa20d7ef0b3aada699db31594ab7c/localstack/services/awslambda/event_source_listeners/sqs_event_source_listener.py#L52-L91

**Comment by thrau** [comment] 2023-05-02 11:51
having said that, the exception that you're getting seems to be coming from our old lambda provider. could you please share whether you are using the legacy lambda provider, or any other special configuration to start up localstack @albulesculoredana ? thanks

**Comment by thrau** [comment] 2023-05-04 10:26
In any case, this seems to be a duplicate of https://github.com/localstack/localstack/issues/5042

**Closed by thrau** 2023-05-04 10:26 UTC
Labels: type: bug, status: triage needed, aws:sqs, aws:lambda

**Comment by epicabbas** [comment] 2025-02-28 06:51
So, I have a question. In the documentation, it mentions that by default, the batch size is 10, but can I increase it to 10k? I see that 10 is a hard limit.

If I want to increase, I have to do it through 1. Client Side Batching 2. Polling SQS Manually.

Please help me understand!
