### ISSUE TITLE
When attempting to download object from S3 from a lambda get proxy handler request error

### ISSUE THREAD

**Issue by CABellamy** [localstack/localstack#3087] opened 2020-10-09 14:58 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When attempting to perform a downloadWithContext action from a Lambda into the LocalStack S3 instance I receive a proxy handler request error. I am able to get headObject information from this S3 bucket but not when trying to do downloadWithContext So I know the S3 bucket and the communication from the Lambda is fine, it's just when doing this specific action that I see the error

## Expected behavior
It downloads the item from the bucket as expected

## Actual behavior
```
localstack_1           | 2020-10-09T14:35:43:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost/asset-upload/1x1.jpg: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
localstack_1           |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 94, in index
localstack_1           |     raise result
localstack_1           |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
localstack_1           |     result = self.func(self.params)
localstack_1           |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1           |     return fn(*args, **kwargs)
localstack_1           |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 557, in handler
localstack_1           |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1           |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
localstack_1           |     listener_result = listener.forward_request(method=method,
localstack_1           |   File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
localstack_1           |     return do_forward_request(api, port, method, path, data, headers)
localstack_1           |   File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
localstack_1           |     result = do_forward_request_inmem(api, port, method, path, data, headers)
localstack_1           |   File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
localstack_1           |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1           |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 400, in modify_and_forward
localstack_1           |     updated_response = update_listener.return_response(**kwargs)
localstack_1           |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1226, in return_response
localstack_1           |     fix_range_content_type(bucket_name, path, headers, response)
localstack_1           |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 448, in fix_range_content_type
localstack_1           |     result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
localstack_1           |     return self._make_api_call(operation_name, kwargs)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
localstack_1           |     raise error_class(parsed_response, operation_name)
localstack_1           | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
localstack_1           | 
```

# Steps to reproduce
## Command used to start LocalStack
Via docker container: 

```
localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8081:8080"
    environment:
      - SERVICES=s3
      - DEBUG=true
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8180
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-tmp/localstack}:/tmp/localstack"
    networks:
      - aws-local-network
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
getParams := s3.GetObjectInput{Bucket: &uploadEvent.BucketName, Key: &key}
	buf := aws.NewWriteAtBuffer([]byte{})
	_, dlErr := s3.DownloadWithContext(ctx, buf, &getParams)
```

The above code works fine on AWS, but fails with localstack. My configuration for local s3 is as follows:

```
session.Must(session.NewSession(&aws.Config{
			Region:           aws.String(endpoints.UsEast1RegionID),
			Endpoint:         aws.String("http://host.docker.internal:4566"),
			S3ForcePathStyle: aws.Bool(true),
		}))
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-284) by [Unito](https://www.unito.io/learn-more)

**Comment by adamdavis40208** [comment] 2020-10-16 01:44
I'm also fighting with this -- I can personally download and upload with the awscli but something with the s3manager is hitting this Not Found Traceback error. I'm not using latest (0.10.9). 

Will keep digging, and see what I can turn up.

**Comment by adamdavis40208** [comment] 2020-10-16 02:15
Setting loglevel to aws.LogDebugWithHTTPBody ...

```
---[ REQUEST POST-SIGN ]-----------------------------
GET /local-functional-test-executor-reports/2020-10-16T01%3A39%3A29Z/my-unique-stack/20200820_666420/cucumber.json HTTP/1.1
Host: localhost:4572
User-Agent: aws-sdk-go/1.31.12 (go1.15; darwin; amd64) S3Manager
Authorization: AWS4-HMAC-SHA256 Credential=fake-access-key/20201016/us-west-2/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=6af181a411206db3ca61688a7334e51981dc856a39be6068123879078f06402f
Range: bytes=0-5242879
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201016T021332Z


-----------------------------------------------------
2020/10/15 19:13:32 DEBUG: Response s3/GetObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 502 Bad Gateway
Connection: close
Date: Fri, 16 Oct 2020 02:13:32 GMT
Server: BaseHTTP/0.6 Python/3.8.2


-----------------------------------------------------
2020/10/15 19:13:32 
2020/10/15 19:13:33 DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /local-functional-test-executor-reports/2020-10-16T01%3A39%3A29Z/my-unique-stack/20200820_666420/cucumber.json HTTP/1.1
Host: localhost:4572
User-Agent: aws-sdk-go/1.31.12 (go1.15; darwin; amd64) S3Manager
Authorization: AWS4-HMAC-SHA256 Credential=fake-access-key/20201016/us-west-2/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=324ee7e3780aa495f8e4772c867445672a9958dfd74f63d5835224894b484e6b
Range: bytes=0-5242879
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201016T021333Z


-----------------------------------------------------
2020/10/15 19:13:33 DEBUG: Response s3/GetObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 502 Bad Gateway
Connection: close
Date: Fri, 16 Oct 2020 02:13:33 GMT
Server: BaseHTTP/0.6 Python/3.8.2


-----------------------------------------------------
2020/10/15 19:13:33 
2020/10/15 19:13:35 DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /local-functional-test-executor-reports/2020-10-16T01%3A39%3A29Z/my-unique-stack/20200820_666420/cucumber.json HTTP/1.1
Host: localhost:4572
User-Agent: aws-sdk-go/1.31.12 (go1.15; darwin; amd64) S3Manager
Authorization: AWS4-HMAC-SHA256 Credential=fake-access-key/20201016/us-west-2/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=032f7acb9c16d0baf0ce6fbea5cd96b69aed91f7484b162303c1202cbb266b3d
Range: bytes=0-5242879
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201016T021335Z


-----------------------------------------------------
2020/10/15 19:13:35 DEBUG: Response s3/GetObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 502 Bad Gateway
Connection: close
Date: Fri, 16 Oct 2020 02:13:35 GMT
Server: BaseHTTP/0.6 Python/3.8.2


-----------------------------------------------------
2020/10/15 19:13:35 
2020/10/15 19:13:38 DEBUG: Request s3/GetObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /local-functional-test-executor-reports/2020-10-16T01%3A39%3A29Z/my-unique-stack/20200820_666420/cucumber.json HTTP/1.1
Host: localhost:4572
User-Agent: aws-sdk-go/1.31.12 (go1.15; darwin; amd64) S3Manager
Authorization: AWS4-HMAC-SHA256 Credential=fake-access-key/20201016/us-west-2/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=fa4881e8ea26043b96c5ff8a258c390955bdcdb578e2820fcde4c50994792bce
Range: bytes=0-5242879
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201016T021338Z


-----------------------------------------------------
2020/10/15 19:13:38 DEBUG: Response s3/GetObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 502 Bad Gateway
Connection: close
Date: Fri, 16 Oct 2020 02:13:38 GMT
Server: BaseHTTP/0.6 Python/3.8.2
```

**Comment by adamdavis40208** [comment] 2020-10-16 04:29
```
aws s3api get-object --bucket local-functional-test-executor-reports --key 2020-10-16T01:39:29Z/my-unique-stack/20200820_666420/cucumber.json test_file.txt --endpoint-url=http://localhost:4572   <-- works

aws s3api get-object --bucket local-functional-test-executor-reports --key 2020-10-16T01:39:29Z/my-unique-stack/20200820_666420/cucumber.json test_file.txt --range bytes=0-5242879 --endpoint-url=http://localhost:4572 <-- no worky

An error occurred (502) when calling the GetObject operation (reached max retries: 2): Bad Gateway
```

**Comment by usmangani1** [comment] 2020-10-26 18:16
@adamdavis40208 

We tried to reproduce the issue with the sample commands attached below and we were not able to reproduce the issue.
Can you please pull the latest image and try with these commands attached below and let us know if you still see the issue ?

```
$ aws s3api create-bucket --bucket my-bucket --region us-east-1 --endpoint-url=http://localhost:4566

$ aws s3api put-object --bucket my-bucket  --key abc --body sample.json --endpoint-url=http://localhost:4566
{
    "ETag": "\"f3d60d5a9ab64a37af11f968af8656b4\""
}

$ aws s3api get-object --bucket my-bucket --key abc --range bytes=0-5242879 --endpoint-url=http://localhost:4566 new.json
{
    "AcceptRanges": "bytes",
    "LastModified": "Mon, 26 Oct 2020 18:09:58 GMT",
    "ContentLength": 169,
    "ETag": "\"f3d60d5a9ab64a37af11f968af8656b4\"",
    "CacheControl": "no-cache",
    "ContentEncoding": "identity",
    "ContentLanguage": "en-US",
    "ContentRange": "bytes 0-168/169",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

**Comment by adamdavis40208** [comment] 2020-10-26 20:03
Interesting. I pared down my docker-compose file, and things started working.

I started adding stuff back in, and once I added:

```
HOSTNAME_EXTERNAL: localstack
```

The get-object call started failing again

I'm not entirely sure why my codebase has HOSTNAME_EXTERNAL set, but any ideas why it would mess with get-object but not put-object?

**Comment by adamdavis40208** [comment] 2020-10-26 23:32
someone at work schooled me a little on this env_var. Having it set to `HOSTNAME_EXTERNAL: localstack`, I can correctly do an s3 get with a range from inside a container connected to the localstack network.

Interesting how it only breaks range with a get. Sorry to clutter your issue @CABellamy if we have different things going on!

**Comment by whummer** [comment] 2021-01-02 19:31
Thanks for the update - this should be fixed in the meantime, with `config.HOSTNAME` defaulting to `localhost` in the latest version. Please let us know if the problem persists. Thanks!

**Closed by whummer** 2021-01-02 19:31 UTC
