### ISSUE TITLE
Terraform with s3 plans and applies but conflicts with .tfstate file on second run

### ISSUE THREAD

**Issue by joeHickson** [localstack/localstack#1365] opened 2019-06-09 18:58 UTC
Hi,
I have a simple terraform script pointing at local stack (launched in docker). I can create an s3 bucket and use it but when I try and re-run terraform plan to push updates it throws an error of "Error: insufficient items for attribute "rules"; must have at least 1". Deleting the .tfstate file allows it to re-run. 
Any idea where I have gone wrong?
Thanks

Joe

Launching localstack:
```
docker run -d -p 4567-4593:4567-4593 -p 8080:8080 --name localstack localstack/localstack
```
Terraform:
```
provider "aws" {
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
  region                      = "us-east-1"
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4567"
    cloudformation = "http://localhost:4581"
    cloudwatch     = "http://localhost:4582"
    dynamodb       = "http://localhost:4569"
    es             = "http://localhost:4578"
    firehose       = "http://localhost:4573"
    iam            = "http://localhost:4593"
    kinesis        = "http://localhost:4568"
    lambda         = "http://localhost:4574"
    redshift       = "http://localhost:4577"
    route53        = "http://localhost:4580"
    s3             = "http://localhost:4572"
    secretsmanager = "http://localhost:4584"
    ses            = "http://localhost:4579"
    sns            = "http://localhost:4575"
    sqs            = "http://localhost:4576"
    ssm            = "http://localhost:4583"
    stepfunctions  = "http://localhost:4585"
    sts            = "http://localhost:4592"
  }
}
resource "aws_s3_bucket" "testBucket" {
  bucket = "myBucket"
  acl = "private"
}
```

**Comment by whummer** [comment] 2019-06-15 15:45
Thanks for reporting @joeHickson . I was unable to reproduce this issue - your template works for me.

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_s3_bucket.testBucket
      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "myBucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_s3_bucket.testBucket: Creating...
  acceleration_status:         "" => "<computed>"
  acl:                         "" => "private"
  arn:                         "" => "<computed>"
  bucket:                      "" => "myBucket"
  bucket_domain_name:          "" => "<computed>"
  bucket_regional_domain_name: "" => "<computed>"
  force_destroy:               "" => "false"
  hosted_zone_id:              "" => "<computed>"
  region:                      "" => "<computed>"
  request_payer:               "" => "<computed>"
  versioning.#:                "" => "<computed>"
  website_domain:              "" => "<computed>"
  website_endpoint:            "" => "<computed>"
aws_s3_bucket.testBucket: Creation complete after 1s (ID: myBucket)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

```
$ terraform -v
Terraform v0.11.14
+ provider.aws v2.15.0
```

Can you try again with the `latest` version of the LocalStack Docker image?

**Comment by joeHickson** [comment] 2019-06-15 17:52
Hi @whummer ,
I should be running the latest localstack - I am trying to ensure I can completely rebuild the stack so I remove it from docker and then rebuild it using docker run -d -p 4567-4593:4567-4593 -p 8080:8080 --name localstack localstack/localstack
Downgrading terraform to 
```
 terraform -v
Terraform v0.11.14
+ provider.aws v2.13.0
```
seems to let it run. 
upgrading again to the latest terraform version seems to trigger it.
```
$ terraform -v
Terraform v0.12.2
+ provider.aws v2.13.0
```

**Comment by joeHickson** [comment] 2019-06-15 17:53
I notice I'm running an older aws provider - I'll try upgrading that later

**Comment by joeHickson** [comment] 2019-06-15 19:57
upgrading the provider to 2.15 didn't help.
```
Terraform v0.12.2
+ provider.aws v2.15.0
```

**Comment by CiolFr** [comment] 2019-07-16 18:12
Hello,

same problem here.
```
$ terraform -v
Terraform v0.12.4
+ provider.aws v2.19.0
```

Using latest docker images of localstack
`docker.io/localstack/localstack       latest              ce2ba85597bf`

**Comment by pyToshka** [comment] 2019-07-30 04:47
This issue reproduced in all version 0.12.xx
localstack working with s3 only with version of terraform less than 0.12.
For second run terraform has creat incorrect state like(part)

```
{
      "module": "module.s3_bucket",
      "mode": "managed",
      "type": "aws_s3_bucket",
      "name": "default",
      "each": "list",
      "provider": "provider.aws",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "acceleration_status": "",
            "acl": "private",
            "arn": "arn:aws:s3:::eg-test-app",
            "bucket": "eg-test-app",
            "bucket_domain_name": "eg-test-app.s3.amazonaws.com",
            "bucket_prefix": null,
            "bucket_regional_domain_name": "eg-test-app.s3.amazonaws.com",
            "cors_rule": [],
            "force_destroy": false,
            "hosted_zone_id": "Z3AQBSTGFYJSTF",
            "id": "eg-test-app",
            "lifecycle_rule": [],
            "logging": [],
            "object_lock_configuration": [
              {
                "object_lock_enabled": "",
                "rule": []
              }
            ],
            "policy": null,
            "region": "us-east-1",
            "replication_configuration": [
              {
                "role": "",
                "rules": []
              }
            ],
            "request_payer": "",
            "server_side_encryption_configuration": [
              {
                "rule": []
              }
            ],
            "tags": {
              "Name": "eg-test-app",
              "Namespace": "eg",
              "Stage": "test"
            },
            "versioning": [
              {
                "enabled": false,
                "mfa_delete": false
              }
            ],
            "website": [],
            "website_domain": null,
            "website_endpoint": null
          },
          "depends_on": [
            "module.default_label"
          ]
        }
      ]
    }
```

**Comment by dieend** [comment] 2019-08-09 19:48
I encountered the same situation.
```
$ terraform version
Terraform v0.12.5
+ provider.aws v2.20.0
```
It worked just fine for the first run, but when terraform tried to read the state on the second run, it throws errors related to the insufficient attributes.

**Comment by ActualAdam** [comment] 2019-08-23 17:55
Same provisioning as @joeHickson. terraform init, apply, then `terraform refresh` fails with the error. I am running terraform as packaged by homebrew on MacOS Mojave. Erring on the side of giving you more info since you are having trouble reproducing. 

I am running the pip3 packaged localstack like `localstack --docker` with `SERVICES=sqs,sns,s3` in my shell env, which according to stdout, runs localstack like  
```
docker run -it -e SERVICES="sqs,sns,s3" -e LOCALSTACK_HOSTNAME="localhost" -e LOCALSTACK_HOSTNAME="localhost" --rm --privileged --name localstack_main -p 8080:8080  -p 4576:4576 -p 4575:4575 -p 4572:4572 -v "/private/var/folders/vr/s8fvqrls6y71j024r6nb0k_w0000gn/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/vr/s8fvqrls6y71j024r6nb0k_w0000gn/T/localstack" "localstack/localstack"
```
```
$ terraform version                                                                                                                                   
Terraform v0.12.7
+ provider.aws v2.25.0
``` 
```
$ brew info terraform
terraform: stable 0.12.7 (bottled), HEAD
Tool to build, change, and version infrastructure
https://www.terraform.io/
Conflicts with:
  tfenv (because tfenv symlinks terraform binaries)
/usr/local/Cellar/terraform/0.12.7 (6 files, 54.7MB) *
  Poured from bottle on 2019-08-23 at 10:08:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/terraform.rb
==> Dependencies
Build: go ✘, gox ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 31,377 (30 days), 110,072 (90 days), 288,303 (365 days)
install_on_request: 29,897 (30 days), 104,414 (90 days), 272,888 (365 days)
build_error: 0 (30 days)
```
tfenv is not installed, btw. 
```
$ pip3 show localstack
Name: localstack
Version: 0.10.2.2
```
```
$ docker -v
Docker version 19.03.1, build 74b1e89
```
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
```

**Comment by whummer** [comment] 2019-09-02 07:10
Thanks for digging into this. This appears to be a known issue in Terraform: https://github.com/terraform-providers/terraform-provider-aws/issues/9048 (found the pointer [here](https://stackoverflow.com/questions/56612381/setting-s3-bucket-with-replication-using-terraform). Closing this issue, please monitor and vote up the other issue on Terraform. Thanks!

**Closed by whummer** 2019-09-02 07:10 UTC
Labels: needs-triaging
