### ISSUE TITLE
bug: head-object response does not include expected AcceptRanges property

### ISSUE THREAD

**Issue by teimatinimarin** [localstack/localstack#6218] opened 2022-06-06 16:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
awslocal s3api head-object --bucket localbucket --key raw/localbucket/2022/06/04/141730/object1.txt
{
    "LastModified": "2022-06-04T19:20:49+00:00",
    "ContentLength": 45,
    "ETag": "\"fa6d82afd1ba8116fd66ceeec0b0f6b9\"",
    "ContentType": "application/octet-stream",
    "Metadata": {
        "myval": "test"
    }
}
```

### Expected Behavior

```
aws --profile xxx s3api head-object --bucket txxxx-bucket --key raw/localbucket/2022/06/04/141730/object1.txt
{
    "AcceptRanges": "bytes",
    "LastModified": "2022-06-04T19:29:58+00:00",
    "ContentLength": 45,
    "ETag": "\"fa6d82afd1ba8116fd66ceeec0b0f6b9\"",
    "ContentType": "application/octet-stream",
    "Metadata": {
        "myval": "test"
    }
}
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

SERVICES="s3" localstack start

### Environment

```markdown
- OS: MAcOs Monterey
- LocalStack: 0.14.4.dev
- LocalStack CLI: LocalStack CLI 0.14.3.2
```

**Comment by jarettmillard** [comment] 2022-07-11 21:33
I'm not sure if this is related or a separate bug, but the `LastModified` XML override does not work for HEAD requests:

HEAD:
```
$ curl -I http://localhost.localstack.cloud:4566/bucket/object
HTTP/1.1 200
last-modified: Mon, 11 Jul 2022 21:06:35 GMT
date: Mon, 11 Jul 2022 21:22:41 GMT
...
```
GET:
```
$ curl -i http://localhost.localstack.cloud:4566/bucket/object
HTTP/1.1 200
Last-Modified: Sun, 10 Jul 2022 21:06:35 GMT
date: Mon, 11 Jul 2022 21:31:56 GMT
...

<LastModified>Sun, 10 Jul 2022 21:06:35 GMT</LastModified>
```

**Comment by bentsku** [comment] 2022-12-22 16:17
Hi again!

As this issue is almost a duplicate of #7114 and it seems like it's solved with the new provider, I'll close the issue.
If you still encounter the issue, don't hesitate to comment again and I'll reopen! 

Thanks again!

**Closed by bentsku** 2022-12-22 16:17 UTC
Labels: type: bug, status: resolved/fixed, status: response required, aws:s3
