### ISSUE TITLE
Kinesis / Firehose: Stream ... under account 000000000000 not found

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#4057] opened 2021-05-20 19:53 UTC
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

I want to use a Kinesis/Firehose stream to put data into an ElasticSearch cluster, but I get the error:
>Stream activity-to-elasticsearch-local under account 000000000000 not found.

First I created an ElasticSearch domain with `aws --endpoint-url http://127.0.0.1:4566 es create-elasticsearch-domain --domain-name es_local` and a Kinesis stream with `aws --endpoint-url http://127.0.0.1:4566 kinesis create-stream --stream-name kinesis_es_local_stream --shard-count 4`. Both requests are successful. I verified the response by calling

   - `aws --endpoint-url http://127.0.0.1:4566 kinesis describe-stream --stream-name kinesis_es_local_stream`
   - `aws --endpoint-url http://127.0.0.1:4566 es describe-elasticsearch-domain --domain-name es_local`
  
 where I copied the ARN for both services. I then create the Firehose stream by using

```sh
aws --endpoint-url http://127.0.0.1:4566 firehose create-delivery-stream --delivery-stream-name activity-to-elasticsearch-local --delivery-stream-type KinesisStreamAsSource --kinesis-stream-source-configuration "KinesisStreamARN=arn:aws:kinesis:us-east-1:000000000000:stream/kinesis_es_local_stream,RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role" --elasticsearch-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,DomainARN=arn:aws:es:us-east-1:000000000000:domain/es_local,IndexName=activity,TypeName=activity,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::000000000000:kinesis-activity-backup-local,CompressionFormat=UNCOMPRESSED,EncryptionConfiguration={NoEncryptionConfig=NoEncryption},CloudWatchLoggingOptions={Enabled=false}},ProcessingConfiguration={Enabled=false}"
```

which again succeeds (as in I get the ARN in response and I can see the stream when I call  `aws --endpoint-url http://127.0.0.1:4566 firehose list-delivery-streams`. However, if I now want to put something in there (so that it is delivered to ElasticSearch) by calling
```sh
aws --endpoint-url http://127.0.0.1:4566 kinesis put-record --stream-name activity-to-elasticsearch-local --data "{ "target": "barry" }" --partition-key partition --cli-binary-format raw-in-base64-out
```

I just get 
> An error occurred (ResourceNotFoundException) when calling the PutRecord operation: Stream activity-to-elasticsearch-local under account 000000000000 not found.

It could be related to https://github.com/localstack/localstack/issues/3630

Am I doing something wrong? 🤔 

## Expected behavior

The specified data is placed in the stream and is delivered to the ElasticSearch domain/cluster.

**Comment by Dgame** [comment] 2021-05-20 20:00
@usmangani1 As #3630 has been open since 22 February and there's still no reply, I'd really appreciate some sort of advice as a comment (ASAP / as soon as you know anything), otherwise I'm a bit screwed. 🙂

**Comment by mgagliardo** [comment] 2021-05-20 23:09
Hello @Dgame, the problem is your stream name is wrong, when you put `KinesisStreamARN=arn:aws:kinesis:us-east-1:000000000000:stream/kinesis_es_local_stream` your stream name is `kinesis_es_local_stream`.

You can see that listing the streams:
```
$ awslocal kinesis list-streams
{
    "StreamNames": [
        "kinesis_es_local_stream"
    ]
}
```

And then:
```
$ awslocal kinesis put-record --stream-name kinesis_es_local_stream --data '{ "target": "barry" }' --partition-key partition --cli-binary-format raw-in-base64-out
{
    "ShardId": "shardId-000000000001",
    "SequenceNumber": "49618446106363770103971216010232921752149281962406707218"
}
```

Let us know if it worked, closing this for now as it seems more like a typo/user issue. Cheers

**Comment by mgagliardo** [comment] 2021-05-20 23:25
Forget what I just wrote, found the issue and working on it.

**Comment by Dgame** [comment] 2021-05-21 09:00
@mgagliardo Thank you for your commitment!

**Comment by Dgame** [comment] 2021-05-23 12:02
@mgagliardo I tried again and indeed it seems to work now with
```sh
aws --endpoint-url http://127.0.0.1:4566 kinesis put-record --stream-name kinesis_es_local_stream --data '{ "target": "barry" }' --partition-key partition --cli-binary-format raw-in-base64-out
```

But after that my Elasticsearch Cluster got a yellow status and the data it not in there for some reason.

`http://localhost:4571/_cluster/health` prints
```json
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 1,
  "active_shards" : 1,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 1,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0
}
```

**Comment by Dgame** [comment] 2021-05-25 18:40
What still doesn't work is
> aws --endpoint-url http://127.0.0.1:4566 firehose put-record --delivery-stream-name firehose_es_local_stream --record '{"Data":"SGVsbG8gd29ybGQ="}'

as it still results in
>An error occurred (ResourceNotFoundException) when calling the PutRecord operation: Firehose firehose_es_local_stream under account 000000000000 not found.

**Comment by Dgame** [comment] 2021-05-25 20:43
I tried to specify the `ClusterEndpoint` instead of the `DomainARN` but it fails with the same error. I tried specifying the host endpoint and the docker-internal endpoint:

  - ` aws --endpoint-url http://127.0.0.1:4566 firehose create-delivery-stream --delivery-stream-name firehose_es_local_stream_2 --delivery-stream-type DirectPut --elasticsearch-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,ClusterEndpoint=http://localhost:8082,IndexName=de,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::000000000000:kinesis-es-backup-local,CompressionFormat=UNCOMPRESSED,EncryptionConfiguration={NoEncryptionConfig=NoEncryption},CloudWatchLoggingOptions={Enabled=false}},ProcessingConfiguration={Enabled=false}"`

 - `aws --endpoint-url http://127.0.0.1:4566 firehose create-delivery-stream --delivery-stream-name firehose_es_local_stream_3 --delivery-stream-type DirectPut --elasticsearch-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,ClusterEndpoint=http://esr_01:9200,IndexName=de,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::000000000000:kinesis-es-backup-local,CompressionFormat=UNCOMPRESSED,EncryptionConfiguration={NoEncryptionConfig=NoEncryption},CloudWatchLoggingOptions={Enabled=false}},ProcessingConfiguration={Enabled=false}"`

**Comment by mgagliardo** [comment] 2021-06-01 09:53
Hello @Dgame, sorry for the delay.

There are a couple things here why this is not working, let me go step by step (I'll try to be as clear as possible):

First of all this is all the configuration I have used to make this work (based on your first comment).

Commands:
```
aws --endpoint-url http://127.0.0.1:4566 --profile localstack es create-elasticsearch-domain --domain-name es_local --output json

aws --endpoint-url http://127.0.0.1:4566 --profile localstack kinesis create-stream --stream-name kinesis_es_local_stream --shard-count 4

aws --endpoint-url http://127.0.0.1:4566 --profile localstack kinesis describe-stream --stream-name kinesis_es_local_stream

aws --endpoint-url http://127.0.0.1:4566 --profile localstack es describe-elasticsearch-domain --domain-name es_local

aws --endpoint-url http://127.0.0.1:4566 --profile localstack firehose create-delivery-stream --delivery-stream-name activity-to-elasticsearch-local --delivery-stream-type KinesisStreamAsSource --kinesis-stream-source-configuration "KinesisStreamARN=arn:aws:kinesis:us-east-1:000000000000:stream/kinesis_es_local_stream,RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role" --elasticsearch-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,DomainARN=arn:aws:es:us-east-1:000000000000:domain/es_local,IndexName=activity,TypeName=activity,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::000000000000:kinesis-activity-backup-local,CompressionFormat=UNCOMPRESSED,EncryptionConfiguration={NoEncryptionConfig=NoEncryption},CloudWatchLoggingOptions={Enabled=false}},ProcessingConfiguration={Enabled=false}"
```

As you can see, putting a record on `kinesis` works just fine:
```
aws --endpoint-url http://127.0.0.1:4566 --profile localstack kinesis put-record --stream-name kinesis_es_local_stream --data '{ "target": "barry" }' --partition-key partition --cli-binary-format raw-in-base64-out
```


Now, and based on [your comment here](https://github.com/localstack/localstack/issues/4057#issuecomment-848134166) the problem is you are pointing to the wrong firehose DeliveryStream, you can use this example based on the past commands:
```
aws --endpoint-url http://127.0.0.1:4566 --profile localstack firehose put-record --delivery-stream-name activity-to-elasticsearch-local --record '{"Data":"SGVsbG8gd29ybGQ="}'
```

This however, will fail because of (You can see this with `DEBUG=1` enabled):
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The problem with this is that you are using an example from the [firehose put-record AWS CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/firehose/put-record.html) which is fine, but it uses a bytes encoded string as example:
```
>>> import base64
>>> data = {"Data":"SGVsbG8gd29ybGQ="}
>>> base64.b64decode(data['Data'])
b'Hello world'
```

The issue here is you are using `Elasticsearch` as `--elasticsearch-destination-configuration`, now the thing with that is that you can't just put a `string record` in Elasticsearch, you can see [here](https://github.com/localstack/localstack/blob/master/localstack/services/firehose/firehose_api.py#L82) it is trying to load a JSON and it is actually ok! Because that is how elasticsearch internally works, you can see the python library for [creating indexes here](https://elasticsearch-py.readthedocs.io/en/v7.13.0/api.html#elasticsearch.client.IndicesClient.create) and the [latest reference here](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/indices-create-index.html), you can check that the body actually expects a JSON record, not a plain one.

Now for example you can see if I would encode in base64 format a record and push it:
Get b64 encoded JSON:
```
>>> import base64
>>> base64.b64encode(b'{"target": "Hello world"}')
b'eyJ0YXJnZXQiOiAiSGVsbG8gd29ybGQifQ=='
```

Push it:
```
$ aws --endpoint-url http://127.0.0.1:4566 --profile localstack firehose put-record --delivery-stream-name activity-to-elasticsearch-local --record '{ "Data": "eyJ0YXJnZXQiOiAiSGVsbG8gd29ybGQifQ==" }'
{
    "RecordId": "57df3d2c-fff9-474b-ae14-4ab50dc1746c"
}
```

It just works as expected, and that is why it also does not crash with kinesis, because the data is `'{ "target": "barry" }'`, again, JSON encoded.
```
$ aws --endpoint-url http://127.0.0.1:4566 --profile localstack kinesis put-record --stream-name kinesis_es_local_stream --data '{ "target": "barry" }' --partition-key partition --cli-binary-format raw-in-base64-out
{
    "ShardId": "shardId-000000000001",
    "SequenceNumber": "49618798908791365859723684718735424450007113454124531730"
}
```

Now one last thing just to show you how internally ES works and why this does make sense, if I would list the records (hits) from the `activity` index (which is the one being created):
```
$ curl -s 'http://localhost:4571/activity/_search'  | jq '.hits.hits'
[
  {
    "_index": "activity",
    "_type": "activity",
    "_id": "80264093-a96f-4db9-91cd-6c93dc9d5e83",
    "_score": 1,
    "_source": {
      "target": "Hello world"
    }
  },
  {
    "_index": "activity",
    "_type": "activity",
    "_id": "06954d58-5c8f-4d9d-9338-51174eb982ff",
    "_score": 1,
    "_source": {
      "target": "barry"
    }
  }
]
```

You can see the `_source` is a JSON object as stated before, you can't just push a simple string based on the `body` object Elasticsearch is expecting.

I am now closing this as it seems more either a config or a usage issue than an localstack one. Let me know if you would need a hand. Cheers

**Closed by mgagliardo** 2021-06-01 09:53 UTC
