### ISSUE TITLE
Errors when using EventBridge

### ISSUE THREAD

**Issue by danielrosewarne** [localstack/localstack#1831] opened 2019-12-05 12:28 UTC
I'm trying to get up and running with my Serverless framework project that uses EventBridge as a trigger. I've tested this with both the latest and 0.10.5 images, both of which have the same issue it seems.

When I start the docker container there are a number of errors in the logs related to `hbmqtt.broker`.

```
localstack_main | 2019-12-05T11:50:57:INFO:hbmqtt.broker: Listener 'default' bind to 0.0.0.0:4510 (max_connections=-1)
localstack_main | 2019-12-05T11:50:57:INFO:hbmqtt.broker: Listener 'default': 1 connections acquired
localstack_main | 2019-12-05T11:50:57:INFO:hbmqtt.broker: Connection from 127.0.0.1:57392 on listener 'default'
localstack_main | 2019-12-05T11:50:57:ERROR:asyncio: Task exception was never retrieved
localstack_main | future: <Task finished coro=<Broker.stream_connected() done, defined at /opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/broker.py:341> exception=IncompleteReadError('0 bytes read on a total of 1 expected bytes')>
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/broker.py", line 343, in stream_connected
localstack_main |     yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/broker.py", line 358, in client_connected
localstack_main |     handler, client_session = yield from BrokerProtocolHandler.init_from_connect(reader, writer, self.plugins_manager, loop=self._loop)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/mqtt/protocol/broker_handler.py", line 129, in init_from_connect
localstack_main |     connect = yield from ConnectPacket.from_stream(reader)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/mqtt/packet.py", line 225, in from_stream
localstack_main |     fixed_header = yield from cls.FIXED_HEADER.from_stream(reader)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/mqtt/packet.py", line 104, in from_stream
localstack_main |     byte1 = yield from read_or_raise(reader, 1)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/codecs.py", line 52, in read_or_raise
localstack_main |     data = yield from reader.read(n)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/hbmqtt/adapters.py", line 146, in read
localstack_main |     data = yield from self._reader.readexactly(n)
localstack_main |   File "/usr/lib/python3.7/asyncio/streams.py", line 677, in readexactly
localstack_main |     raise IncompleteReadError(incomplete, n)
localstack_main | asyncio.streams.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
localstack_main | 2019-12-05T11:50:57:INFO:hbmqtt.broker: Listener 'default': 2 connections acquired
localstack_main | 2019-12-05T11:50:57:INFO:hbmqtt.broker: Connection from 172.18.0.2:41808 on listener 'default'
```

Once it's up and running, I deploy my project and get the following errors during deploy:

```
[36mlocalstack_main |[0m 2019-12-04T16:47:01:WARNING:localstack.utils.cloudformation.template_deployer: Unknown resource type "EventBridge": {'Type': 'Custom::EventBridge', 'Version': 1, 'DependsOn': ['NewUserSignupLambdaFunction', 'CustomDashresourceDasheventDashbridgeLambdaFunction'], 'Properties': {'ServiceToken': 'arn:aws:lambda:eu-west-1:123456789012:function:sls-xero-sync-local-custom-resource-event-bridge', 'FunctionName': 'sls-xero-sync-local-newUserSignup', 'EventBridgeConfig': {'RuleName': 'sls-xero-sync-local-newUserSignup-rule-1', 'Pattern': {'source': ['api.rails'], 'detail-type': ['NewUserSignup']}}}}
[36mlocalstack_main |[0m 2019-12-04T16:47:01:WARNING:localstack.utils.cloudformation.template_deployer: Unknown resource type "EventBridge": {'Type': 'Custom::EventBridge', 'Version': 1, 'DependsOn': ['NewUserSignupLambdaFunction', 'CustomDashresourceDasheventDashbridgeLambdaFunction'], 'Properties': {'ServiceToken': 'arn:aws:lambda:eu-west-1:123456789012:function:sls-xero-sync-local-custom-resource-event-bridge', 'FunctionName': 'sls-xero-sync-local-newUserSignup', 'EventBridgeConfig': {'RuleName': 'sls-xero-sync-local-newUserSignup-rule-1', 'Pattern': {'source': ['api.rails'], 'detail-type': ['NewUserSignup']}}}}
```

Then when I try to access EventBridge through the Ruby AWS API I get the following:

```
[4] pry(main)> eb = Aws::EventBridge::Client.new(region: "eu-west-1", endpoint: "http://localhost:4572")
=> #<Aws::EventBridge::Client>
[5] pry(main)> eb.list_event_buses
Aws::Json::ParseError: 822: unexpected token at '<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets><Bucket><Name>lwe-serverless-deployments-eu-west-1</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-U736EG6P7SLY</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-UPC5V7WTB92U</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-OWQS36XJ9I6D</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-QMUTBIFVZ1FA</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>'
from /Users/dan/.rvm/gems/ruby-2.4.6@api/gems/aws-sdk-core-3.72.1/lib/aws-sdk-core/json.rb:27:in `rescue in load'
[6] pry(main)>
```

...and if I use the AWS cli I get:

```
> awslocal events list-event-buses

An error occurred (500) when calling the ListEventBuses operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Note: This could be related to #1765.

**Comment by whummer** [comment] 2019-12-17 18:44
Thanks for reporting @danielrosewarne . Trying to reproduce the issue you're facing.
```
eb = Aws::EventBridge::Client.new(region: "eu-west-1", endpoint: "http://localhost:4572")
...
Aws::Json::ParseError: 822: unexpected token at '<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets><Bucket><Name>lwe-serverless-deployments-eu-west-1</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-U736EG6P7SLY</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-UPC5V7WTB92U</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-OWQS36XJ9I6D</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket><Bucket><Name>sls-xero-sync-local-ServerlessDeploymentBucket-QMUTBIFVZ1FA</Name><CreationDate>2006-02-03T16:45:09.000Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>'
```
Looks like you're using the port of the S3 API - can you please give it a try with port `4587`:
```
eb = Aws::EventBridge::Client.new(region: "eu-west-1", endpoint: "http://localhost:4587")
```

I also haven't been able to reproduce the CLI issue, unfortunately. This is what I'm seeing with the latest Docker image:
```
$ awslocal events list-event-buses
{
    "EventBuses": [
        {
            "Name": "default",
            "Arn": "arn:aws:events:us-east-2:000000000000:event-bus/default"
        }
    ]
}
```

If you have any hints on how to reproduce these issues, that would be appreciated. Thanks!

**Comment by teroxik** [comment] 2019-12-27 15:25
With the `latest` image seems to be working correctly for me.

**Comment by whummer** [comment] 2019-12-27 21:23
Awesome, thanks for confirming @teroxik . Closing this issue - please re-open if the problem persists @danielrosewarne . Thanks

**Closed by whummer** 2019-12-27 21:23 UTC
Labels: PRO, priority-high
