### ISSUE TITLE
Only old (deprecated) syntax for Map iteration is supported in step functions

### ISSUE THREAD

**Issue by VDBBjorn** [localstack/localstack#7723] opened 2023-02-21 09:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to create a state machine in localstack using a json file with ASL. This is the (very simple) example:

```
{
  "Comment": "A description of my state machine",
  "StartAt": "Map",
  "States": {
    "Map": {
      "Type": "Map",
      "ItemProcessor": {
        "ProcessorConfig": {
          "Mode": "INLINE"
        },
        "StartAt": "Lambda Invoke",
        "States": {
          "Lambda Invoke": {
            "Type": "Task",
            "Resource": "arn:aws:states:::lambda:invoke",
            "OutputPath": "$.Payload",
            "Parameters": {
              "Payload.$": "$",
              "FunctionName": "arn:my-function::handle"
            },
            "Retry": [
              {
                "ErrorEquals": [
                  "Lambda.ServiceException",
                  "Lambda.AWSLambdaException",
                  "Lambda.SdkClientException",
                  "Lambda.TooManyRequestsException"
                ],
                "IntervalSeconds": 2,
                "MaxAttempts": 6,
                "BackoffRate": 2
              }
            ],
            "End": true
          }
        }
      },
      "End": true,
      "ItemsPath": "$"
    }
  }
}
```

When trying to create the state machine using this command:
`aws --endpoint-url http://localhost:4566 --region eu-central-1 stepfunctions create-state-machine --name some-state-machine --definition file://temp.json --role-arn arn:aws:iam::000000000000:role/stepfunctions-role`

I get the validation error:
An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: Invalid State Machine Definition: ''SCHEMA_VALIDATION_FAILED: These fields are required: [Iterator] at /States/Map', 'SCHEMA_VALIDATION_FAILED: Field 'ItemProcessor' is not supported at /States/Map''

If I import this JSON to AWS itself, it is perfectly valid.

I checked with the AWS documentation, this is what they say about this:
The ItemProcessor field replaces the now deprecated [Iterator](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#iterator) field. Although you can continue to include Map states that use the Iterator field, we highly recommend that you replace this field with ItemProcessor. (https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#map-state-inline-deprecated-fields)

Is there any chance this will be supported in the near future? Or should i swap to iterator for now?

### Expected Behavior

I expect the JSON to be valid and the state machine to be created

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url http://localhost:4566 --region eu-central-1 stepfunctions create-state-machine --name some-state-machine --definition file://temp.json --role-arn arn:aws:iam::000000000000:role/stepfunctions-role

with temp.json containing:

```
{
  "Comment": "A description of my state machine",
  "StartAt": "Map",
  "States": {
    "Map": {
      "Type": "Map",
      "ItemProcessor": {
        "ProcessorConfig": {
          "Mode": "INLINE"
        },
        "StartAt": "Lambda Invoke",
        "States": {
          "Lambda Invoke": {
            "Type": "Task",
            "Resource": "arn:aws:states:::lambda:invoke",
            "OutputPath": "$.Payload",
            "Parameters": {
              "Payload.$": "$",
              "FunctionName": "arn:my-function::handle"
            },
            "Retry": [
              {
                "ErrorEquals": [
                  "Lambda.ServiceException",
                  "Lambda.AWSLambdaException",
                  "Lambda.SdkClientException",
                  "Lambda.TooManyRequestsException"
                ],
                "IntervalSeconds": 2,
                "MaxAttempts": 6,
                "BackoffRate": 2
              }
            ],
            "End": true
          }
        }
      },
      "End": true,
      "ItemsPath": "$"
    }
  }
}
```

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```

### Anything else?

https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#map-state-inline-deprecated-fields

**Comment by miki725** [comment] 2023-04-24 21:35
running into same issue via terraform+localstack integration:

```
│ Error: creating Step Functions State Machine (github-newconfig): InvalidDefinition: Invalid State Machine Definition: ''SCHEMA_VALIDATION_FAILED: These fields are required: [Iterator] at /States/AnalyzeRepositories', 'SCHEMA_VALIDATION_FAILED: Field 'ItemProcessor' is not supported at /States/AnalyzeRepositories''
```

Using localstack 2.0.2 version docker image

**Comment by javiertejero** [comment] 2023-05-10 15:05
I think it's related to limitation of the latest [StepFunctionsLocal.jar](https://docs.aws.amazon.com/step-functions/latest/dg/sfn-local-jar.html)

similar issue using the AWS tools used by localstack under the hood:

https://repost.aws/questions/QUmqnTsUWHR1ekkw2KdNtYMA/invaliddefinition-error-when-creating-a-step-functions-state-machine-with-a-map-state-in-the-docker-image-amazon-aws-stepfunctions-local-for-local-testing

**Comment by daMichaelB** [comment] 2023-06-21 08:03
I have the same problem when using the official docker image `amazon/aws-stepfunctions-local`

**Comment by Fettah** [comment] 2023-07-06 14:37
I have the same issue with both localstack and aws-stepfuctions-local

**Comment by amithi-cider** [comment] 2023-07-07 13:06
Is anyone looking into this @dfangl ?
We are using Map Distributed and this is a major obstacle in starting to use localstack

**Comment by cmkennedy20** [comment] 2023-07-24 21:00
I'm also experiencing a problem when calling CreateStateMachine. The JSON definition has been validated from within the StepFunction editor in the AWS Console. 

I'd like to help share some of the error messages in hopes that it might help in resolving the underlying problem. 

**Original error** 
Invalid State Machine Definition

**List of errors**
- 'SCHEMA_VALIDATION_FAILED: The value for the field 'ctx.$' must be a valid JSONPath or a valid intrinsic function call at /States/DebugProfileStart/Parameters'
- 'SCHEMA_VALIDATION_FAILED: These fields are required: [Iterator] at /States/FanOutItems' 
- 'SCHEMA_VALIDATION_FAILED: Field 'ItemProcessor' is not supported at /States/FanOutItems'
- 'SCHEMA_VALIDATION_FAILED: Field 'ItemSelector' is not supported at /States/FanOutItems'

**Comment by marco-luzzara** [comment] 2023-08-04 11:46
Some [SF tests](https://github.com/localstack/localstack/blob/master/tests/integration/stepfunctions/v2/test_stepfunctions_v2.py) use this workflow:

https://github.com/localstack/localstack/blob/ad2f7e021fd12791e63ebb406a8327b25eb458b6/tests/integration/stepfunctions/v2/test_stepfunctions_v2.py#L44-L58

So `ItemProcessor`, and therefore the new API for step functions, have to be supported (otherwise they would not have written a test for this). Is this feature supported with the premium plan? If I remember well, with the Localstack Free plan, we can only use api v1 (which are legacy by now). Please clarify this point in the documentation. Thanks

**Comment by MEPalma** [comment] 2023-08-07 09:23
We are currently involved in the development of our own customized backend for Step Functions. You can access this feature by setting the environment variable `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2`. In the current version (on the main branch) our implementation accommodates both legacy `Iterator` definitions as well as `ItemProcessor`. For a detailed overview of the support provided in this initial version of Step Functions, you can refer to the notes of https://github.com/localstack/localstack/pull/8779.

As we continue to enhance both the support and stability of this service, there is a potential that it might already fulfill your requirements. We are looking forward to your feedback!

**Comment by marco-luzzara** [comment] 2023-08-09 08:22
Hi @MEPalma , thanks for the update. I am particularly interested in the `ItemReader` field (as well as in the `ItemProcessor` field of course) because I need to iterate over an S3 bucket. I have searched it in the draft, but it does not seem to be currently present. Do you think it will be released soon? Thanks again

**Comment by mahawaa** [comment] 2023-09-18 09:29
I tried with PROVIDER_OVERRIDE_STEPFUNCTIONS=v2 var, it fixes the schema validation error however gives the below error now:
An error occurred (InternalFailure) when calling the CreateStateMachine operation: API action 'CreateStateMachine' for service 'stepfunctions' not yet implemented

**Comment by MEPalma** [comment] 2023-09-25 08:46
@mahawaa The problem you're facing might be attributed to the version of LocalStack in use. To utilise the Step Functions v2 provider, please ensure that you are using the latest version.

**Comment by MEPalma** [comment] 2023-09-25 08:48
@marco-luzzara I can confirm that we are actively working on adding support for ItemReader declarations. You can expect to see initial support for this feature available in the upcoming weeks.

**Comment by marco-luzzara** [comment] 2023-10-26 11:37
Hi @MEPalma , thank you, I have tested it and it is working! Great Job :1st_place_medal:

**Comment by MEPalma** [comment] 2023-11-17 15:06
I am marking this issue as resolved since it appears to be addressed in the latest version of LocalStack. If the problem persists on your end, please inform us so that we can investigate further.

**Closed by MEPalma** 2023-11-17 15:06 UTC
Labels: type: feature, aws:stepfunctions, status: accepted

**Comment by noseworthy** [comment] 2023-11-21 05:28
Hey @MEPalma , I'm running the `localstack/localstack-pro:3.0.0` docker image and still need to set the `PROVIDER_OVERRIDE_STEPFUNCTIONS=v2` environment variable to get distributed map to work. Is this expected? I thought I saw in [this PR](https://github.com/localstack/localstack/pull/8779) that v2 should be the default provider for v3.0.0?

**Comment by dominikschubert** [comment] 2023-11-21 05:40
@noseworthy This is unfortunately a known issue right now with the 3.0.0 release. When using -pro the default switches back to legacy, while in the community image v2 is the default now. This should be fixed in latest during the course of this day and we'll ship a 3.0.1 patch release that will also include this fix at the end of this week.

Sorry for the inconvenience!

**Comment by noseworthy** [comment] 2023-11-21 05:44
> @noseworthy This is unfortunately a known issue right now with the 3.0.0 release. When using -pro the default switches back to legacy, while in the community image v2 is the default now. This should be fixed in latest during the course of this day and we'll ship a 3.0.1 patch release that will also include this fix at the end of this week.
> 
> Sorry for the inconvenience!

No worries! Thanks for the super fast response. We're absolutely loving localstack 🙏
