### ISSUE TITLE
bug: Granting rds_iam inside a DO block fails silently

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10308] opened 2024-02-23 15:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After running up a RDS in LocalStack, attempting to grant rds_iam to a user with the following

```sql
DO
$do$
BEGIN
  GRANT rds_iam TO iam_user;
END
$do$;
```

Will return a success but attempting to sign in with a generated rds iam token will fail with `psql: error: FATAL:  password authentication failed for user "iam_user"`. If we run the sql again, it will say that the user has already been granted `rds_iam`, but it still fails to authenticate. Running the grant outside of the `DO` block will work and then iam authentication will be allowed

### Expected Behavior

Running the `GRANT` inside the `DO` block should work and allow us to authenticate with IAM

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose up`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class DatabaseStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    new DatabaseCluster(this, "DatabaseCluster", {
      engine: DatabaseClusterEngine.auroraPostgres({
        version: AuroraPostgresEngineVersion.VER_16_1,
      }),
      credentials: {
        username: "administrator",
      },
      iamAuthentication: true,
      instanceProps: {
        instanceType: new InstanceType("t3.medium"),
        vpc: new Vpc(this, "VPC"),
      },
    });
  }
}
```

```bash
#!/bin/bash

SECRET_NAME=$(awslocal secretsmanager list-secrets --query "SecretList[0].Name" --output text)
SECRET_VALUE=$(awslocal secretsmanager get-secret-value --secret-id=$SECRET_NAME --query "SecretString" --output text)

USERNAME=$(echo $SECRET_VALUE | jq .username -r)
PASSWORD=$(echo $SECRET_VALUE | jq .password -r)
HOST=$(echo $SECRET_VALUE | jq .host -r)
PORT=$(echo $SECRET_VALUE | jq .port -r)
DBNAME=$(echo $SECRET_VALUE | jq .dbname -r)

PGPASSWORD="$PASSWORD" psql --host $HOST --username $USERNAME --port $PORT $DBNAME -c "CREATE ROLE iam_user WITH LOGIN;"
PGPASSWORD="$PASSWORD" psql --host $HOST --username $USERNAME --port $PORT $DBNAME -c "DO
\$do\$
BEGIN
  GRANT rds_iam TO iam_user;
END
\$do\$;"

USERNAME="iam_user"
PASSWORD=$(awslocal rds generate-db-auth-token --hostname $HOST --username $USERNAME --port $PORT --region eu-west-2)

PGPASSWORD="$PASSWORD" psql --host $HOST --username $USERNAME --port $PORT $DBNAME -c "SELECT * FROM pg_roles LIMIT 1"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.1
```

### Anything else?

I've reproduced the bug here: https://github.com/Garethp/localstack-bugs/tree/rds-iam.

If you check out the `rds-iam` branch, run `yarn install` followed by `start.sh` you should see the error pop up

**Comment by bentsku** [comment] 2024-02-28 20:12
Hello @Garethp and thanks for your report!

The fix should now be available in the `latest` docker image. Could you pull `localstack/localstack-pro:latest` and see if that fixes your issue? Thanks!

**Comment by Garethp** [comment] 2024-03-01 14:50
Thanks for taking a look this @bentsku! The example I showed in my reproduction worked, but it didn't work in my actual application. I've updated the reproduction to match it more closely and show the error still occurring, but it looks like the error is still present if you create the user in the same `DO` block as you attempt to grant it `rds_iam`. Here's a bit closer to how we run it in our actual stack:

```sql
DO
$do$
BEGIN
  CREATE ROLE iam_user WITH LOGIN INHERIT;
  IF EXISTS(
      SELECT
      FROM pg_catalog.pg_roles
      WHERE rolname = 'rds_iam')
  THEN
      GRANT rds_iam TO iam_user;
  END IF;
END
$do$;
```

**Comment by bentsku** [comment] 2024-03-01 15:05
I think I understand where the issue lies, thanks a lot for the updated reproducer. I'll work on fixing this now!

**Comment by Garethp** [comment] 2024-03-01 15:10
It's a really strange issue. If it's not private, I'd be really interested to see what the fix is

**Comment by bentsku** [comment] 2024-03-01 18:36
The codebase is private, but I can quickly give you an explanation: with our current implementation of IAM Auth Token, we need to run a query to alter the role/user that has been granted the `rds_iam` role. However, as your query is run in a transaction, the user was not created yet. I think I found a fix, the PR will be reviewed shortly and I hope this will fix your use-case!

**Comment by bentsku** [comment] 2024-03-05 20:34
Hello @Garethp! The new fix should be available in the latest image, if you'd like to give it a try and check if it would be now fixed? Thanks again for your patience!

**Comment by Garethp** [comment] 2024-03-15 12:51
Hey, sorry for the delay in testing. I can confirm that in my project I no longer have any issues with granting rds_iam

**Comment by bentsku** [comment] 2024-03-15 13:58
No worries, I'm glad the issue is resolved! I'll go ahead and close the issue. Thank you so much for the feedback and the samples which helped reproducing the issue.

**Closed by bentsku** 2024-03-15 13:58 UTC
Labels: type: bug, aws:rds, status: in progress
