### ISSUE TITLE
Cannot reach localstack container from a Lambda container via $LOCALSTACK_HOSTNAME

### ISSUE THREAD

**Issue by Frantch** [localstack/localstack#4093] opened 2021-06-02 14:04 UTC
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

I have created a Lambda function which works fine and it is running in 'docker' execution (new container for every execution)

The lambda needs to communicate with a DynamoDB so in the code I have used the
`LOCALSTACK_HOSTNAME` but the container cannot reach the the localstack container using that ip.

It works if I use the localstack container Gateway ip though.

```
bash-4.2$ curl http://$LOCALSTACK_HOSTNAME:4566/health
curl: (7) Failed to connect to 192.168.48.3 port 4566: Connection timed out

bash-4.2$ curl http://172.17.0.1:4566/health
{"services": {"dynamodb": "running", "dynamodbstreams": "running", "kinesis": "running", "lambda": "running", "logs": "running", "s3": "running", "cloudwatch": "running"}, "features": {"persistence": "disabled", "initScripts": "initialized"}}
```

Something strange though the ip contained in LOCALSTACK_HOSTNAME is 192.168.48.3. This doesn't seem to be the correct host IP of the localstack container

docker-compose config:

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.12.10
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES-lambda,dynamodb,s3 }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Expected behavior

curl http://$LOCALSTACK_HOSTNAME:4566/health to work

## Actual behavior

 curl http://$LOCALSTACK_HOSTNAME:4566/health
curl: (7) Failed to connect to 192.168.48.3 port 4566: Connection timed out

using the latest version of localstack and docker

**Comment by mgagliardo** [comment] 2021-06-02 14:21
Hello @Frantch would you please share your current configuration (docker compose, or however you are running localstack) along with the  example lambda config/function as well so we can reproduce this?

Thanks.

**Comment by Frantch** [comment] 2021-06-03 07:02
Yes sorry, added it to the oririnal post

**Comment by mgagliardo** [comment] 2021-06-04 01:44
Hello @Frantch, the problem is that your docker compose has the localstack container on the `network_mode: bridge` and the `LAMBDA_DOCKET_NETWORK` set to another different (and non existent) docker network, the following should work:


docker-compose.yml:
```
version: '3'

services:
  localstack:
    container_name: localstack
    network_mode: bridge # needed for the lambda to reach the localstack container
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - MAIN_CONTAINER_NAME=localstack #container name in envs must match custom container name
      - SERVICES=dynamodb,lambda
      - LAMBDA_EXECUTOR=docker-reuse
      - DEBUG=1
      #- LAMBDA_DOCKER_NETWORK=test_default #network must be configured directly
      - LAMBDA_DOCKER_NETWORK=bridge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

Code (lots of non usable code, but just printing it so you can see it works):
```
import os
import urllib3

def lambda_handler(event, context):
    message = 'Hello world!'
    print("ALL ENV: {}".format(os.environ))
    localstack_hostname = os.environ['LOCALSTACK_HOSTNAME']
    print("ALL ENV: {}".format(localstack_hostname))
    http = urllib3.PoolManager()
    localstack_url = 'http://' + localstack_hostname + ':4566/health'
    r = http.request('GET', localstack_url)
    print("Request output: {}".format(r.data))
    return { 
        'message' : message
    }
```

Output (Localstack DEBUG):
```
localstack    | {"message":"Hello world!"}
localstack    | > START RequestId: 37b6b5dc-a6e2-16bb-3ad9-3beb5d8985dc Version: $LATEST
localstack    | > ALL ENV: environ({'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'EDGE_PORT': '4566', 'HOSTNAME': '4d1cbca8a2da', '_LAMBDA_CONTROL_SOCKET': '14', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '3', 'LOCALSTACK_HOSTNAME': '172.17.0.2', 'AWS_LAMBDA_LOG_GROUP_NAME': '/aws/lambda/test', 'LAMBDA_TASK_ROOT': '/var/task', 'LD_LIBRARY_PATH': '/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib', 'AWS_LAMBDA_RUNTIME_API': '127.0.0.1:9001', 'AWS_LAMBDA_LOG_STREAM_NAME': '2021/06/04/[$LATEST]511d2cf0575ac01f31b4fe519dac8b35', '_LAMBDA_SHARED_MEM_FD': '11', 'AWS_EXECUTION_ENV': 'AWS_Lambda_python3.8', '_LAMBDA_RUNTIME_LOAD_TIME': '1530232235231', 'AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2:2000', 'AWS_LAMBDA_FUNCTION_NAME': 'test', 'PATH': '/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin', '_LAMBDA_LOG_FD': '9', '_LAMBDA_SERVER_PORT': '5006', 'AWS_DEFAULT_REGION': 'us-east-1', 'PWD': '/var/task', 'AWS_SECRET_ACCESS_KEY': '', 'LAMBDA_RUNTIME_DIR': '/var/runtime', 'LANG': 'en_US.UTF-8', 'TZ': ':UTC', 'AWS_REGION': 'us-east-1', 'AWS_ACCESS_KEY_ID': '', 'SHLVL': '0', 'HOME': '/home/sbx_user1051', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:us-east-1:000000000000:function:test', '_AWS_XRAY_DAEMON_ADDRESS': '169.254.79.2', '_AWS_XRAY_DAEMON_PORT': '2000', '_X_AMZN_TRACE_ID': 'Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1', '_LAMBDA_SB_ID': '7', 'AWS_XRAY_CONTEXT_MISSING': 'LOG_ERROR', '_LAMBDA_CONSOLE_SOCKET': '16', 'AWS_LAMBDA_COGNITO_IDENTITY': '{}', '_HANDLER': 'handler.lambda_handler', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '1536', 'AWS_LAMBDA_EVENT_BODY': '{}', 'PYTHONPATH': '/var/runtime'})
localstack    | > ALL ENV: 172.17.0.2
localstack    | > Request output: b'{"services": {"dynamodb": "running", "dynamodbstreams": "running", "kinesis": "running", "lambda": "running", "logs": "running", "cloudwatch": "running"}, "features": {"persistence": "disabled", "initScripts": "initialized"}}'
localstack    | > END RequestId: 37b6b5dc-a6e2-16bb-3ad9-3beb5d8985dc
```

I'll take this issue and clarified and close it. Feel free to comment out if needed. Cheers.

**Closed by mgagliardo** 2021-06-04 01:44 UTC
