### ISSUE TITLE
Latest docker image fails with generic_proxy exceptions

### ISSUE THREAD

**Issue by florianakos** [localstack/localstack#2089] opened 2020-02-25 12:18 UTC
Hi!

I have noticed that today (25th of Feb) a new version of localstack docker image was pushed to the repository (82c83ff027114060938856eac5dc7be1d534afd0b7711510246de4a76dde2396) and this version fails in my integration tests with an exception:

```
2020-02-25T12:09:44:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 303, in forward updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 954, in return_response
send_notifications(method, bucket_name, object_path, version_id)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 178, in send_notifications
send_notification_for_subscriber(notif, bucket_name, object_path,
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 191, in send_notification_for_subscriber
object_size = s3_client.head_object(Bucket=bucket_name, Key=key).get('ContentLength', 0)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
  raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```
The same setup in docker-compose works with version 0.10.7 and 0.10.6 without any errors or exceptions.

**Comment by laggardkernel** [comment] 2020-02-25 13:29
Same problem here. But there's no problem during 1st startup. This only happens after I stop the former container and re-launch `localstack start --docker` again.

**Comment by whummer** [comment] 2020-02-26 09:21
Thanks for reporting. I think we're talking about two different problems here.

@florianakos Can you please share some details about your specific use case. We recently added a change that reports the file size of an object when sending out S3 update notifications. Looks like the S3 object for which the notification is being sent out does not exist or cannot be found (404 error). Any hints on how we can reproduce this issue would be appreciated, thanks.

@laggardkernel Your problem seems to be related to startup of the container. Can you please do a `docker pull localstack/localstack` and give it another try? Please also ensure that sufficient memory is allocated to the Docker engine - we recommend allocating at least 2-3GB to Docker.

**Comment by florianakos** [comment] 2020-02-26 20:44
@whummer I agree that the issue reported by @laggardkernel seems to be of a different kind. My setup runs in docker-compose with 2 containers, one with **localstack** and another with the integration tests.

```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: gm-monitoring-localstack
    ports:
      - '4563-4599:4563-4599'
      - '8080:8080'
    environment:
      - SERVICES=sqs,s3
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integration-tests
    depends_on:
      - "localstack"
```

My integration test code tries to put an object to an S3 bucket and fails with this exception:

`botocore.exceptions.ClientError: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway`

At the same time, the localstack is spewing out the same exception over and over, as the put_object is retried a few times.

I looked at the change you referenced and was wondering about line 190:
`     key = urlparse.urlparse(object_path[1:]).path`
Why is the first character taken off? If I add an extra '/' to the s3_key in my code this error goes away in localstack (however the bucket notification also does not arrive).

**Comment by whummer** [comment] 2020-02-26 22:21
Thanks for the update @florianakos .

Can you please enable `DEBUG=1` and then post the logs of the LocalStack container:
```
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
```

Can you please also confirm whether your S3 client SDK is using _path style addressing_ (as opposed to host name based addressing). LocalStack currently requires path style addressing, as we cannot encode the bucket name in the host name (the host name is usually `localhost`, or `localstack` in your case).

**Comment by florianakos** [comment] 2020-02-26 23:29
It seems that S3 Put operation works, but HEAD fails with 404 because the key seems to be encoded in twice:

```
gm-monitoring-localstack   | 2020-02-26 23:06:04,233:API: 127.0.0.1 - - [26/Feb/2020 23:06:04] "PUT /global-models-monitoring/component%3Dgfc/subComponent%3Dtls/date%3D20200112/metrics.json HTTP/1.1" 200 -
gm-monitoring-localstack   | 2020-02-26 23:06:04,239:API: 127.0.0.1 - - [26/Feb/2020 23:06:04] "HEAD /global-models-monitoring/component%253Dgfc/subComponent%253Dtls/date%253D20200112/metrics.json HTTP/1.1" 404 -
```

First "=" becomes `%3D`, then `%3D` then becomes encoded again to `%253D`.

By the way, I use Python & boto3 with the `localstack_python_client` to create a session to localstack container (hostname set via LOCALSTACK_HOST env variable).

**Comment by whummer** [comment] 2020-02-29 09:46
Thanks for providing the details @florianakos . This should be fixed in #2105 - can you please give it a try with the `latest` version? Please re-open this issue if the problem persists. Thanks

**Closed by whummer** 2020-02-29 09:46 UTC
Labels: bug, regression

**Comment by florianakos** [comment] 2020-02-29 10:07
I did a docker pull to get the latest image as you recommended:
```
 ▶ docker pull localstack/localstack:latest
latest: Pulling from localstack/localstack
Digest: sha256:acde0b9f9b13d991fb236e248a45bfd778e8943905db7fde36b59944eccc61ff
Status: Image is up to date for localstack/localstack:latest
docker.io/localstack/localstack:latest
```
Then I ran my docker-compose setup and turned on Debug and the issue still seems to persist with the same error message:

```
2020-02-29 10:03:24,402:API: 127.0.0.1 - - [29/Feb/2020 10:03:24] "PUT /global-models-monitoring/component%3Dgfc/subComponent%3Dtls/date%3D20200112/metrics.json HTTP/1.1" 200 -
2020-02-29 10:03:24,409:API: 127.0.0.1 - - [29/Feb/2020 10:03:24] "HEAD /global-models-monitoring/component%253Dgfc/subComponent%253Dtls/date%253D20200112/metrics.json HTTP/1.1" 404 -
```

**Comment by whummer** [comment] 2020-02-29 10:48
Hey @florianakos , thanks for the quick response. Looks like I responded too early - I think the Docker image was still being built/pushed by our CI system. Can you please do another pull and see if that updates the image version?

**Comment by florianakos** [comment] 2020-02-29 11:52
Issue is fixed now @whummer! Thanks a lot for the quick help :)
