### ISSUE TITLE
RedrivePolicy from SQS to DLQ is failing 

### ISSUE THREAD

**Issue by maturiaditya** [localstack/localstack#3921] opened 2021-04-22 19:36 UTC
# Type of request: This is a ...

[ X ] bug report
[ ] feature request

# Detailed description
RedrivePolicy from SQS to DLQ is failing 
[sample-project.zip](https://github.com/localstack/localstack/files/6360818/sample-project.zip)

...

## Expected behavior
Redrive policy from SQS to DLQ should be successful 
...

## Actual behavior
Redrive policy from SQS to DLQ is failing 
...

# Steps to reproduce

## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

**Exception** 
```
2021-04-22T19:28:18:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.SQS object at 0x7f44d6ad1ee0>> with params: {'QueueName': 'SAMPLE_SQS', 'Attributes': {'RedrivePolicy': '[{"maxReceiveCount": 5}, {"deadLetterTargetArn": "arn:aws:sqs:us-west-2:000000000000:SAMPLE_SQS_DLQ"}]'}, 'tags': {}} for resource: {'Type': 'AWS::SQS::Queue', 'LogicalResourceId': 'sampleSqs', 'Properties': {'QueueName': 'SAMPLE_SQS', 'RedrivePolicy': [{'maxReceiveCount': 5}, {'deadLetterTargetArn': 'arn:aws:sqs:us-west-2:000000000000:SAMPLE_SQS_DLQ'}]}, '_state_': {}}
2021-04-22T19:28:18:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "aws-nodejs-local": Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 451, in _parse_xml_string_to_dom
    parser.feed(xml_string)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1927, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1978, in do_apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2031, in apply_change
    result = deploy_resource(resource_id, new_resources, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1052, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1156, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1277, in configure_resource_via_sdk
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1272, in configure_resource_via_sdk
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in _send_request
    success_response, exception = self._get_response(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 166, in _get_response
    success_response, exception = self._do_get_response(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 217, in _do_get_response
    parsed_response = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 243, in parse
    parsed = self._do_error_parse(response, shape)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 505, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 454, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```
**docker-compse.yml**
```
version: "3.3"

services:
  # localstack
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - DEFAULT_REGION=us-west-2
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=/tmp/localstack
      - USE_SSL=false
      - LOCALSTACK_HOSTNAME=localstack
    volumes:
      - "${PWD}/:${PWD}"
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 ```

**Resources:**
```
service: aws-nodejs

provider:
  name: aws
  region: us-west-2
  profile: ${opt:profile, self:custom.profile}
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-localstack

custom:
  defaultStage: local
  localstack:
    debug: true
    stages: [local]

functions:
  lambda:
    handler: lambda.handler
    name: lambda
    memorySize: 128
    timeout: 30
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          enabled: true
          arn: { "Fn::GetAtt": ["sampleTableDynamoDB", "StreamArn"] }


# resources
resources:
  Resources:
    sampleTableDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sampleTable
        StreamSpecification:
          StreamEnabled: true
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: key1
            AttributeType: S
          - AttributeName: key2
            AttributeType: S
        KeySchema:
          - AttributeName: key1
            KeyType: HASH
          - AttributeName: key2
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    sampleSqsDlq:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SAMPLE_SQS_DLQ
    sampleSqs:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SAMPLE_SQS
        RedrivePolicy:
          - maxReceiveCount: 5
          - deadLetterTargetArn: { Fn::GetAtt: [sampleSqsDlq, Arn] }
```

**Deploy command**
```
serverless deploy --stage local
```
...

**Comment by pandomic** [comment] 2021-04-23 07:52
@maturiaditya could you attach configuration files to your message or format them as code?

**Comment by maturiaditya** [comment] 2021-04-23 16:07
@pandomic Sure, I will format the message as code. Also, I attached my sample project under the decription which should include the project config.

**Comment by pandomic** [comment] 2021-04-25 22:35
Thank you @maturiaditya, I can confirm this is a **bug**. We will try to solve this issue shortly and will keep you informed.

**Comment by pandomic** [comment] 2021-04-25 22:58
@maturiaditya after having a close look on your template I realised you have an error in your syntax. According to CloudFormation documentation `RedrivePolicy` should be an object ([documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-redrive)), that means your configuration should look like the following:

```yaml
RedrivePolicy:
  maxReceiveCount: 5
  deadLetterTargetArn: { Fn::GetAtt: [sampleSqsDlq, Arn] }
```

**Comment by pandomic** [comment] 2021-04-25 23:02
I'm closing the issue for now since with object-based `RedrivePolicy` service is getting deployed normally. Feel free to reopen it in case new issues arise.

cc @whummer

**Closed** 2021-04-25 23:03 UTC
Labels: won't fix

**Comment by maturiaditya** [comment] 2021-05-05 23:27
@pandomic Thanks for looking into the issue, I will try to fix my code and run again.
