### ISSUE TITLE
bug: [PRO] Cognito oauth2/token endpoint can't handle client id/secret being in the body

### ISSUE THREAD

**Issue by nadeem-clearaccept** [localstack/localstack#4265] opened 2021-07-06 18:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error I have found is that if you the token endpoint to generate the token while adding the client_id and client_secrect in the body of the message, it through an error below.

`{"__type": "InternalServerError", "message": "Error in Cognito action \"\": 'utf-8' codec can't decode byte 0xb8 in
position 2: invalid start byte "}`

Here are the JSON to set up the Cognito the same way as me.
[cognito-setup-json.zip](https://github.com/localstack/localstack/files/6772065/cognito-setup-json.zip)

Here is an cURL command to run this: 
```
curl --location --request POST 'https://localhost.localstack.cloud/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=be/setup transact/threeds internal/all transact/transact be/data vault/tokenisation' \
--data-urlencode 'client_id=0cktktgg9qbqxg6dj1a246gjdo' \
--data-urlencode 'client_secret=301eb7f1'
```

### Expected Behavior

Expected it to get the token without any errors

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create a user-pool, user-pool-client ([cognito-setup-json.zip](https://github.com/localstack/localstack/files/6772065/cognito-setup-json.zip))
2. Get the client id and the user pool id and fill in the following cURL command
`curl --location --request POST 'https://{{LOCAL_STACK_URI}}/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=be/setup transact/threeds internal/all transact/transact be/data vault/tokenisation' \
--data-urlencode 'client_id={{CLIENT_ID}}' \
--data-urlencode 'client_secret={{CLIENT_SECRECT}}'`

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`curl --location --request POST 'https://localhost.localstack.cloud/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=be/setup transact/threeds internal/all transact/transact be/data vault/tokenisation' \
--data-urlencode 'client_id=0cktktgg9qbqxg6dj1a246gjdo' \
--data-urlencode 'client_secret=301eb7f1'`

### Environment

```markdown
- OS: Windows
- LocalStack: Latest
```

### Anything else?

Here are the logs
```
Waiting for all LocalStack services to be ready
2021-07-06 10:36:23,615 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-07-06 10:36:23,625 INFO supervisord started with pid 15
2021-07-06 10:36:24,628 INFO spawned: 'dashboard' with pid 21

2021-07-06 10:36:24,630 INFO spawned: 'infra' with pid 22
2021-07-06 10:36:24,635 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-07-06 10:36:24,636 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2021-07-06 10:36:25,652 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready

LocalStack version: 0.12.14
LocalStack Docker container id: 9f4eb2ba68fe
LocalStack build date: 2021-07-04
LocalStack build git hash: 66b1d1e9

Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-07-06T10:36:42:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Starting mock Cognito Identity Provider (IdP) service on http ports 443/4566 ...
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Starting mock CloudFormation service on http ports 443/4566 ...
Starting mock DynamoDB service on http ports 443/4566 ...
Starting mock DynamoDB Streams service on http ports 443/4566 ...
2021-07-06T10:36:48:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2021-07-06T10:36:48:INFO:botocore.credentials: Found credentials in environment variables.
2021-07-06T10:36:48:INFO:botocore.credentials: Found credentials in environment variables.
[2021-07-06 10:36:49 +0000] [23] [INFO] Running on http://0.0.0.0:58911 (CTRL + C to quit)
2021-07-06T10:36:49:INFO:hypercorn.error: Running on http://0.0.0.0:58911 (CTRL + C to quit)
[2021-07-06 10:36:49 +0000] [23] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-07-06T10:36:49:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-07-06 10:36:49 +0000] [23] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
2021-07-06T10:36:49:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Starting mock S3 service on http ports 443/4566 ...
Starting mock SQS service on http ports 443/4566 ...
2021-07-06T10:36:54:INFO:botocore.credentials: Found credentials in environment variables.
Waiting for all LocalStack services to be ready
Ready.
2021-07-06T10:37:52:INFO:localstack_ext.services.cognito.cognito_helpers: Unable to list Cognito groups for user 0cktktgg9qbqxg6dj1a246gjdo in pool us-east-1_4236789c32cd4a9ca7ad10c9199a9bde: 
2021-07-06T10:37:55:INFO:localstack_ext.services.cognito.cognito_helpers: Unable to list Cognito groups for user 0cktktgg9qbqxg6dj1a246gjdo in pool us-east-1_4236789c32cd4a9ca7ad10c9199a9bde: 
2021-07-06T10:38:42:INFO:botocore.credentials: Found credentials in environment variables.
2021-07-06T10:39:46:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:39:46:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:39:48:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:39:48:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:39:52:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:39:52:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:40:00:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:40:00:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:45:16:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:45:16:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:45:27:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:45:27:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:48:02:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:48:02:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:48:05:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:48:05:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:48:06:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:48:06:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:50:47:INFO:localstack_ext.services.cognito.cognito_listener: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
2021-07-06T10:50:47:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "": 'utf-8' codec can't decode byte 0xb8 in position 2: invalid start byte 
```

**Comment by rbAdylic** [comment] 2021-09-16 09:56
It appears the issue is with grant_type: client_credentials

**Comment by whummer** [comment] 2021-09-17 19:04
Thanks for reporting @rbAdylic @nadeem-clearaccept , and apologies for the delay. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Closed by whummer** 2021-09-17 19:04 UTC
Labels: bug, priority-high, needs-triaging
