### ISSUE TITLE
bug: aws rds describe-db-instances returns wrong endpoint data

### ISSUE THREAD

**Issue by SanderHagen** [localstack/localstack#6130] opened 2022-05-24 13:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `awslocal rds describe-db-instances` I expect the address of the rds instances to be `localhost`. For postgres this is the case, but for mysql this is not the case.

### Expected Behavior

I expect both engines to return `localhost` as the address

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal rds create-db-instance --engine mysql --db-instance-identifier mydbinstance_mysql --db-instance-class db.t3.large --master-username masteruser --master-user-password masteruserpassword

awslocal rds create-db-instance --engine postgres --db-instance-identifier mydbinstance_postgres --db-instance-class db.t3.large --master-username masteruser --master-user-password masteruserpassword

awslocal rds describe-db-instances | grep Endpoint -A 3
```
### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- LocalStack: 0.14.2.9
```

**Comment by steffyP** [comment] 2022-06-03 09:52
Hi @SanderHagen,
thanks for reporting! We are able to reproduce this issue. A fix will be provided soon.

**Comment by steffyP** [comment] 2022-06-07 14:58
Hi @SanderHagen,
the issue should be fixed. Could you try pulling `localstack/localstack:latest` and verify it is working for you now?
Thank you.

**Comment by casio** [comment] 2022-06-15 10:53
This does not seem to be fixed yet. Running ops client commands still yields:
```
$ awslocal rds describe-db-instances | grep Endpoint -A 3
    "Endpoint": {
        "Address": "mydbinstance_mysql.aaaaaaaaaa.us-east-1.rds.amazonaws.com",
        "Port": 3306
    },

    "Endpoint": {
        "Address": "mydbinstance_postgres.aaaaaaaaaa.us-east-1.rds.amazonaws.com",
        "Port": 5432
    },
```

Just pulled the image to confirm.
(my environment: MacOS 12.4(M1), localstack cli 0.14.3.2, run via `localstack start`)

**Comment by steffyP** [comment] 2022-06-15 11:18
Hi @casio, 

the fix is currently only available in the `localstack/localstack:latest` image. 
When you start LocalStack, you should see the version, and build date - can you confirm that it not older than this one:
```
localstack  | LocalStack version: 0.14.4.dev
localstack  | LocalStack Docker container id: b4476e81756d
localstack  | LocalStack build date: 2022-06-14
localstack  | LocalStack build git hash: 7c3e4b90 
```

I just re-tested with this image, calling `awslocal rds create-db-instance` for the following engines: `postgres`, `sqlserver-se` and `mysql`. 

```
awslocal rds describe-db-instances | grep Endpoint -A 3
            "Endpoint": {
                "Address": "localhost",
                "Port": 4510
            },
--
            "Endpoint": {
                "Address": "localhost",
                "Port": 4511
            },
--
            "Endpoint": {
                "Address": "localhost",
                "Port": 4511
            },
```

If you still face this problem with wrong endpoint addresses, could you please share how you start LocalStack and how you create the database instances? 
Thank you!

**Comment by steffyP** [comment] 2022-06-15 12:41
Alright @casio, seems to be a slightly different problem, as you already have a different address for the `create-db-instance` call. 
Do you have an env set for `HOSTNAME_EXTERNAL`  by any chance? 

If not, could you try using `docker compose` for starting LocalStack? We have a [sample here](https://github.com/localstack/localstack/blob/master/docker-compose.yml).

**Comment by steffyP** [comment] 2022-06-15 13:14
Thanks for reporting back, @casio. 
We will further investigate your issue.

**Comment by steffyP** [comment] 2022-06-22 11:06
Hi @casio,

could it be that you are missing the env for `LOCALSTACK_API_KEY`? [RDS is a feature only available for pro.](https://docs.localstack.cloud/aws/rds/) You can sign up for a free trial period though.

I wasn't able to reproduce your issue on MacOS 12.4 M1 with an api key set. 

However, we detected a routing issue for `rds` requests in the community version, which results in a mocked response for `rds` calls and has the `address` set as you described it. 

Anyhow, the `rds` feature is generally not available at all for the community version. My apologies for the misunderstanding. 

Does it explain your issue though?

**Comment by Vizz85** [comment] 2022-06-24 06:48
I confirm the fix solved the issue for us, after updating the image from 0.14.2 to 0.14.4.dev
Thank you!

**Closed** 2022-06-24 11:30 UTC
Labels: type: bug, status: resolved/fixed, aws:rds
