### ISSUE TITLE
cloudwatch internal server errors

### ISSUE THREAD

**Issue by jkuehl2** [localstack/localstack#712] opened 2018-04-10 09:42 UTC
Hello, i ran into several problems adding cloudwatch. Kinesis & dynamodb is working fine in my application if i set the metricsFactory to a NullMetricsFactory. 

running localstack from terminal on mac os x (i also tried running with make install, make infra and http instead of https and some awl-cli commands without success)
```
DATA_DIR=/tmp/localstack/data SERVICES=kinesis:4568,dynamodb:4569,cloudwatch:4582 AWS_CBOR_DISABLE=1 TMPDIR=/private/$TMPDIR DEFAULT_REGION=us-east-1 DEBUG=1 docker-compose up
```

First issue: i tried using cloudwatch with a kinesis worker in java with CBOR disabled and disableCertChecking set to true:

(...)

```
AwsClientBuilder.EndpointConfiguration endpointConfiguration = new AwsClientBuilder.EndpointConfiguration("https://localhost:4582", "us-east-1");
                CWMetricsFactory cwMetricsFactory =
         new CWMetricsFactory(AmazonCloudWatchClientBuilder.standard().withEndpointConfiguration(endpointConfiguration).build(),
                kinesisConfig.getConsumerApplicationName(),
                15000, // 15s buffer time
                100, // max queue size
                MetricsLevel.SUMMARY,
                ImmutableSet.of("ShardId"));
```

(...)
```        
return new Worker.Builder()
                .recordProcessorFactory(shipmentUpdateNotificationRecordProcessorFactory)
                .config(KinesisConsumerShipmentNotificationFactory.createKinesisClientLibConfiguration(kinesisConfig, dynamoDbEventRepositoryConfig))
                .metricsFactory(cwMetricsFactory)
                .build();
```

If i run my worker, i get internal server errors:

```
2018-04-10 11:16:52.237  WARN 61647 --- [trics-publisher] c.a.s.k.m.impl.CWPublisherRunnable       : Could not publish 14 datums to CloudWatch

com.amazonaws.services.cloudwatch.model.AmazonCloudWatchException: null (Service: AmazonCloudWatch; Status Code: 500; Error Code: 500 INTERNAL SERVER ERROR; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.125.jar:na]
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:1073) ~[aws-java-sdk-cloudwatch-1.11.125.jar:na]
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:1049) ~[aws-java-sdk-cloudwatch-1.11.125.jar:na]
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:957) ~[aws-java-sdk-cloudwatch-1.11.125.jar:na]
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:934) ~[aws-java-sdk-cloudwatch-1.11.125.jar:na]
	at com.amazonaws.services.kinesis.metrics.impl.DefaultCWMetricsPublisher.publishMetrics(DefaultCWMetricsPublisher.java:63) ~[amazon-kinesis-client-1.8.8.jar:na]
	at com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.runOnce(CWPublisherRunnable.java:144) [amazon-kinesis-client-1.8.8.jar:na]
	at com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.run(CWPublisherRunnable.java:90) [amazon-kinesis-client-1.8.8.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

debug output from localstack
```
localstack_1  | 172.18.0.1 - - [10/Apr/2018 10:07:48] "POST / HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack_1  | response = self.make_response(self.handle_exception(e))
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 116, in dispatch
localstack_1  | return cls()._dispatch(*args, **kwargs)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 199, in _dispatch
localstack_1  | return self.call_action()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 273, in call_action
localstack_1  | response = method()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 263, in _wrapper
localstack_1  | response = f(*args, **kwargs)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudwatch/responses.py", line 81, in put_metric_data
localstack_1  | self.cloudwatch_backend.put_metric_data(namespace, metric_data)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudwatch/models.py", line 233, in put_metric_data
localstack_1  | namespace, metric_member['MetricName'], float(metric_member['Value']), metric_member.get('Dimensions.member', _EMPTY_LIST), metric_member.get('Timestamp')))
localstack_1  | KeyError: 'Value'

```

second issue: producing a a custom metric it seems to work (with an empty response):
```
final AmazonCloudWatch cw =
                AmazonCloudWatchClientBuilder.standard().withEndpointConfiguration(endpointConfiguration).build();

        com.amazonaws.services.cloudwatch.model.Dimension dimension = new com.amazonaws.services.cloudwatch.model.Dimension()
                .withName("UNIQUE_PAGES")
                .withValue("URLS");

        MetricDatum datum = new MetricDatum()
                .withMetricName("PAGES_VISITED")
                .withUnit(StandardUnit.None)
                .withValue(555D)
                .withDimensions(dimension);

        PutMetricDataRequest request = new PutMetricDataRequest()
                .withNamespace("SITE/TRAFFIC")
                .withMetricData(datum);

       PutMetricDataResult response = cw.putMetricData(request);
```

debug out put from localstack:
```
localstack_1  | 172.18.0.1 - - [10/Apr/2018 10:07:27] "POST / HTTP/1.1" 200 -
```

but recalling it from command-line does not work:
```
aws cloudwatch get-metric-statistics --metric-name PAGES_VISITED --namespace SITE/TRAFFIC --start-time 2016-10-18T23:18:00 --end-time 2019-10-18T23:18:00 --period 360 --no-verify-ssl --endpoint-url https://localhost:4582
```

```
Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

debug output localstack
```
localstack_1  | 172.18.0.1 - - [10/Apr/2018 10:10:39] "POST / HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack_1  | response = self.make_response(self.handle_exception(e))
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 116, in dispatch
localstack_1  | return cls()._dispatch(*args, **kwargs)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 199, in _dispatch
localstack_1  | return self.call_action()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 273, in call_action
localstack_1  | response = method()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 263, in _wrapper
localstack_1  | response = f(*args, **kwargs)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudwatch/responses.py", line 103, in get_metric_statistics
localstack_1  | raise NotImplemented("Must specify either Statistics or ExtendedStatistics")
localstack_1  | TypeError: 'NotImplementedType' object is not callable

```
thirdly, even a simple list-metrics does not work:

```
aws cloudwatch list-metrics --no-verify-ssl --endpoint-url https://localhost:4582
```

```
Error during pagination: The same next token was received twice: {u'NextToken': '\n            96e88479-4662-450b-8a13-239ded6ce9fe\n        '}
```

debug output localstack
```
localstack_1  | 172.18.0.1 - - [10/Apr/2018 10:11:39] "POST / HTTP/1.1" 200 -
localstack_1  | 172.18.0.1 - - [10/Apr/2018 10:11:39] "POST / HTTP/1.1" 200 -
```

in the end i tried other cli commands given below and they worked (although i do not need them, just a POC if i can access the cloudwatch inside the docker with anything and getting it to behave like expected). Therefore the issue seems to be with the internal implementation
````
aws cloudwatch put-dashboard --dashboard-name testDash --dashboard-body {} --no-verify-ssl --endpoint-url https://localhost:4582

aws cloudwatch list-dashboards --no-verify-ssl --endpoint-url https://localhost:4582

aws cloudwatch get-dashboard --dashboard-name testDash --no-verify-ssl --endpoint-url https://localhost:4582
```

**Comment by dan-hook** [comment] 2018-04-23 15:27
I'm seeing similar errors.  I was able to get around the list-metrics error by specifying a value for --max-items.

**Comment by igor-dmitriev** [comment] 2018-05-16 16:38
got the same error, any updates on this?

**Comment by marnett** [comment] 2018-08-03 19:24
You can bypass CloudWatch entirely by passing a NullMetricsFactory to the worker like so:

```
new Worker.Builder()
      .recordProcessorFactory(recordProcessorFactory)
      .config(kclConfig)
      .metricsFactory(new NullMetricsFactory)
      .build
```

**Comment by whummer** [comment] 2019-11-20 21:01
Thanks for reporting. @jkuehl2 @dan-hook @igor-dmitriev @ marnett . It's been a while since this issue has been raised. Can you please confirm that this issue still persists with the latest version? 

Would be great if you could provide a small self-contained example (ideally as a sequence of `awslocal` shell commands) that helps reproduce this issue.

Thanks!

**Comment by whummer** [comment] 2020-05-06 17:59
This should be fixed in the `latest` version. New integration tests have been added to cover this functionality:
https://github.com/localstack/localstack-java-utils/pull/9
https://github.com/localstack/localstack/pull/2399

Please report here if the problem persists. Thanks

**Closed by whummer** 2020-05-06 17:59 UTC
Labels: bug, needs-triaging

**Comment by monosoul** [comment] 2020-07-20 15:03
Still happens in `0.11.3`:
```
2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 2020-07-20 14:59:14,876 WARN software.amazon.kinesis.metrics.CloudWatchMetricsPublisher [cw-metrics-publisher] {} Could not publish 14 datums to CloudWatch
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: null (Service: CloudWatch, Status Code: 500, Request ID: null)
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.services.cloudwatch.model.CloudWatchException$BuilderImpl.build(CloudWatchException.java:95) ~[cloudwatch-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.services.cloudwatch.model.CloudWatchException$BuilderImpl.build(CloudWatchException.java:55) ~[cloudwatch-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.protocols.query.internal.unmarshall.AwsXmlErrorUnmarshaller.unmarshall(AwsXmlErrorUnmarshaller.java:98) ~[aws-query-protocol-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:102) ~[aws-query-protocol-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:82) ~[aws-query-protocol-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88) ~[sdk-core-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129) ~[sdk-core-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:171) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:68) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:287) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495) ~[netty-nio-client-2.10.66.jar!/:?]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
    2020-07-20 14:59:14,877 INFO DOCKER [tc-okhttp-stream-471205577] {} STDOUT: 	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by fatihaksel** [comment] 2020-10-15 19:12
Please make sure you have configured `awscli`. 

`cat ~/.aws/credentials`

```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

`cat ~/.aws/config`

```
[default]
region=us-west-2
output=json
```

Check your `region` value

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
