### ISSUE TITLE
Unable to access cloudformation with out internet access

### ISSUE THREAD

**Issue by Muraligowtham** [localstack/localstack#1617] opened 2019-10-03 14:22 UTC
Hi Team, I am creating a local stack using cloud formation as follow.(using test container local stack version)

The weird thing that I notice is, if I don't have internet access in my laptop, the cloud formation gets stuck and doesn't move forward. and its instantly starts working after getting internet access. 

So what is the cause of this issue. we thought local stack works locally and doesnt require internet. pls clarify.

```
cloudformation = AmazonCloudFormationClientBuilder.standard()
                .withEndpointConfiguration(localstack.getEndpointConfiguration(CLOUDFORMATION))
                .withCredentials(localstack.getDefaultCredentialsProvider()).build();
```

**Comment by whummer** [comment] 2020-01-12 18:10
Thanks for reporting @Muraligowtham . Generally speaking, LocalStack should work (mostly) offline, but under certain circumstances your OS might work differently (e.g., regarding DNS) when not connected to the network, even for invocations on `localhost`.

This issue might be difficult to reproduce, as the behavior is dependent on your operating system, your local networking configuration, etc. I'm afraid we'll have to close this as "cannot reproduce", unless you can provide some more specific debugging details, and a reliably reproducible test case. Thanks a lot!

**Closed by whummer** 2020-01-12 18:10 UTC
