### ISSUE TITLE
bug: Step function SQS task fails to run

### ISSUE THREAD

**Issue by phildunphytoo** [localstack/localstack#4881] opened 2021-11-09 13:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a step function which one of its tasks is to send a SQS message, the task fails with error:
`"An error occurred while executing the state 'Send to SQS" (entered at the event id #7). The input {MD5OfMessageBody: aaaaaaaaaaaaaaaaaaaa,MessageId: aaaaa-aaa-aaaa-aaaaa,} is not a valid JSON"`

### Expected Behavior

A SQS message is send to the queue

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d 
using the example docker-compose with the following services:
lambda,sqs,s3,stepfunctions,iam,cloudwatch

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
aws --endpoint-url http://192.186.0.100:4566 stepfunctions start-execution --state-machine-arn arn:aws:states:us-east-1:00000000000:stateMachine:MyStepFunction

### Environment

```markdown
- OS: RHEL8.1
- LocalStack: 0.12.19
```

### Anything else?

StepFunction ASL, SQS step parameters:
"QueueUrl":"http://192.186.0.100:4566/00000000000/MyQueue",
"MessageBody":
{
"Id.$" : "$.Id",
"Name.$": "$.name"
}

**Comment by phildunphytoo** [comment] 2021-11-09 13:56
Might be connected to #4665

**Comment by simonrw** [comment] 2022-11-23 14:45
This may be a duplicate of #4665 - @phildunphytoo can you try my recreation in the [other issue](https://github.com/localstack/localstack/issues/4665#issuecomment-1325175491) and see if the problem still persists?

**Comment by thrau** [comment] 2023-05-10 15:54
Since there hasn't been any activity on this issue for several months, I'm closing it as stale. If the problem still persists, please open a new issue with more specific reproduction instructions. Thanks!

**Closed by thrau** 2023-05-10 15:54 UTC
Labels: type: bug, status: triage needed, status: response required, aws:sqs, aws:stepfunctions
