### ISSUE TITLE
SQS's FIFO queue is not supported as an EventBridge target

### ISSUE THREAD

**Issue by taoza** [localstack/localstack#3402] opened 2020-12-29 04:11 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

SQS's FIFO queue is not supported as an EventBridge target.

A SQS target is created via API and inspected as below. Note the `MessageGroupId` is supplied properly.

```
aws events list-targets-by-rule --rule minutelyJob
{
    "Targets": [
        {
            "SqsParameters": {
                "MessageGroupId": "123"
            },
            "Id": "Schedule jobs in SQS",
            "Arn": "arn:aws:sqs:us-east-1:000000000000:myqueue.fifo"
        }
    ]
}
```

When the event fires we get the below exception:
```
2020-12-29T04:01:46:WARNING:bootstrap.py: Thread run method <function get_scheduled_rule_func.<locals>.func at 0x7f0ceb256e50>(None) failed: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 514, in run
    self.func(self.params)
  File "/opt/code/localstack/localstack/services/events/events_listener.py", line 75, in func
    sqs_client.send_message(QueueUrl=queue_url, MessageBody=json.dumps(event))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MissingParameter) when calling the SendMessage operation: The request must contain the parameter MessageGroupId.
```

## Expected behavior

EventBridge's target should support SQS's fifo queue.

## Potential fix

Maybe we should support `MessageGroupId` at [here](https://github.com/localstack/localstack/blob/5a723c368b317f3dc61952709c1d07af56be332e/localstack/services/events/events_listener.py#L75)?

**Comment by whummer** [comment] 2020-12-29 10:57
Hi @taoza , thanks for reporting. Good catch, passing `MessageGroupId` at the position you posted should probably do the trick. Do you think you can prepare a small pull request with the change (plus a small integration test to cover this functionality). This would be much appreciated - thanks!

**Comment by whummer** [comment] 2021-01-04 20:16
Hi @taoza, any update on this issue - would you be able to contribute a small pull request? That would be great, thanks.

**Comment by irahulranjan** [comment] 2021-01-14 08:49
Hi @taoza, Please pull the latest docker image and try it out. It should be fixed. If you are still facing any issues please reopen the issue.

**Closed by irahulranjan** 2021-01-14 08:49 UTC
Labels: bug, pr-requested

**Comment by allenbrubaker** [comment] 2023-04-07 12:44
For everyone else having issues still after this PR, no messages were showing up in the FIFO queue even after successfully setting up an event bridge rule. I tried with a standard queue (and omitting the message-group-id) and it worked great. The solution was to set the `ContentBasedDeduplication: true` as an attribute when creating the FIFO queue.

**Comment by bentsku** [comment] 2023-04-07 13:26
Thanks for the pointer @allenbrubaker! 

It seems from the AWS documentation that if an SQS queue is the target, you have to set `ContentBasesDeduplication: true` as you mentioned. I think the lack of way to pass `MessageDeduplicationId` is the cause.

> #### SqsParameters
> Contains the message group ID to use when the target is a FIFO queue.
>
> If you specify an SQS FIFO queue as a target, the queue must have content-based deduplication enabled.
>
> Type: [SqsParameters](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_SqsParameters.html)

**Comment by zhe** [comment] 2023-05-27 07:11
Thanks @allenbrubaker and @bentsku 

Did you find the duplication doesn't work even we set `ContentBasesDeduplication: true`?

I tried to send same message multiple times for testing, the FIFO queue seemed not deduplicate those messages, the queue's consumer - Lambda received all of them with each had a different `messageId`, but the content in `body` is exactly the same.
