### ISSUE TITLE
Internal server error using S3 SelectObjectContent

### ISSUE THREAD

**Issue by david-wb** [localstack/localstack#860] opened 2018-07-21 15:55 UTC
I'm using the aws javascript sdk to invoke `s3.selectObjectContent()`  with a localstack endpoint for s3. This results in the following error
```
localstack_1  | 127.0.0.1 - - [21/Jul/2018 15:40:36] "POST /test-bucket/<file path ...>?select&select-type=2 HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack_1  | response = self.make_response(self.handle_exception(e))
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 568, in key_response
localstack_1  | response = self._key_response(request, full_url, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 627, in _key_response
localstack_1  | return self._key_response_post(request, body, bucket_name, query, key_name, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 1061, in _key_response_post
localstack_1  | "Method POST had only been implemented for multipart uploads and restore operations, so far")
localstack_1  | NotImplementedError: Method POST had only been implemented for multipart uploads and restore operations, so far
localstack_1  | 127.0.0.1 - - [21/Jul/2018 15:40:36] "POST /test-bucket/<file path ...>?select&select-type=2 HTTP/1.1" 500 -
```

I'm using localstack v0.8.7. Any ideas how I might get around this problem? Thanks

**Comment by lkrnac** [comment] 2019-01-18 14:44
I am facing also same issue when using AWS CLI with piping redirection:

{code}
ffmpeg -i input.mp4 -movflags frag_keyframe+empty_moov -f mp4 - | aws --endpoint-url http://localhost:4572 s3 cp - s3://s3BucketName/path
{code}

Localstack version: 0.8.10

**Comment by Mossito** [comment] 2019-07-09 11:53
Hi is there any news about this problem? im experiencing the same, any SelectObjectContent returns 500 error

`2019-07-09T11:52:46:INFO:werkzeug: 127.0.0.1 - - [09/Jul/2019 11:52:46] "POST /securitas-bucket/employees/employees-s3-json-object?select&select-type=2 HTTP/1.1" 500 -
2019-07-09T11:52:46:ERROR:werkzeug: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/s3/responses.py", line 593, in key_response
response = self._key_response(request, full_url, headers)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/s3/responses.py", line 652, in _key_response
return self._key_response_post(request, body, bucket_name, query, key_name, headers)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/s3/responses.py", line 1092, in _key_response_post
"Method POST had only been implemented for multipart uploads and restore operations, so far")
NotImplementedError: Method POST had only been implemented for multipart uploads and restore operations, so far`

**Comment by whummer** [comment] 2020-04-18 18:22
Thanks for reporting @david-wb @lkrnac @Mossito . Closing this as duplicate of #980 - S3 Select is currently not yet available in LocalStack. Please follow the discussion on the other ticket. Thanks

**Closed by whummer** 2020-04-18 18:22 UTC
Labels: enhancement, feature-missing
