### ISSUE TITLE
Serverless SQS Events source issues with latest

### ISSUE THREAD

**Issue by Thomas-Franklin** [localstack/localstack#1595] opened 2019-09-25 10:48 UTC
I am sorry if this is not a localstack issue, but from my testing it seems to be. When using serverless framework and localstack when trying to deploy with an SQS events source using the serverless-localstack plugin noticing some discrepancies between 0.9.6 and the latest localstack docker containers. The following repo has two folders, one where it works as expected (working/ - using localstack:0.9.6) and then the other  (not_working_as_expected/ - using latest localstack).

Repo: https://github.com/thomas-franklin/localstack-reproduction

The steps I have performed is to create an external network called `localstack` `docker network create localstack` then in the folder `working/`:

`docker-compose up -d`

`./gradlew clean build`

`npm install`

`sls deploy --stage local`

This is successful and does create the SQS source mapping as can be seen by:

```
awslocal lambda list-event-source-mappings
{
    "EventSourceMappings": [
        {
            "UUID": "58321539-de66-431d-ab40-0ebac2be1426",
            "BatchSize": 100,
            "EventSourceArn": "arn:aws:sqs:elasticmq:000000000000:TestQueue",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:receiveMessage",
            "LastModified": 1569403127.0,
            "LastProcessingResult": "OK",
            "State": "Enabled",
            "StateTransitionReason": "User action"
        }
    ]
}
```

Only issue is that if I do a `sls invoke -f sendMessage --stage local` it does add the message to queue as expected, but the `receiveMessage` is not invoked - however if I do something like:

```
 awslocal sqs send-message --queue-url "http://localhost:4576/queue/TestQueue" --message-body 'foo'
```

Then the `receiveMessage` is invoked, however I suspect this is mostly that the SQS listener is blocked when another lambda is executing?

*EDIT*: This is my fault really, as I am using batching/buffered client in the sender - if I use normal client and don't send the messages in batches it will invoke from one lambda to another through the queue - after looking through the queue it appears the SQS Listener only reacts to `SendMessage` actions which wouldn't be the case for batches/buffered requests. 

Now the issue with the `not_working_as_expected/` (same steps as above, just need to stop the 0.9.6 container) folder is that it does not deploy and the following stack trace is shown:

```
    'FunctionArn': func.function_arn,
AttributeError: 'NoneType' object has no attribute 'function_arn'
2019-09-25 09:24:13,647:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 132, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 168, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 259, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 340, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/responses.py", line 231, in list_stack_resources
    return template.render(resources=resources)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 4, in top-level template code

  File "/usr/lib/python3.6/_collections_abc.py", line 762, in __iter__
    yield self._mapping[key]
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 410, in __getitem__
    resource_logical_id, resource_json, self, self._region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 149, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 195, in _parse_and_create_resource
    resource_json_arns_fixed, resources_map, region_name)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 306, in parse_and_create_resource
    resource_name, resource_json, region_name)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/awslambda/models.py", line 483, in create_from_cloudformation_json
    'FunctionArn': func.function_arn,
AttributeError: 'NoneType' object has no attribute 'function_arn'
```

However if I comment out:

```
events:
      - sqs:
          arn:
            Fn::GetAtt:
            - TestQueue
            - Arn
          batchSize: 1
```

In the serverless.yml and do some clean up and try the deploy it is fine, and then create the source mapping manually after it is deployed:

```
awslocal lambda create-event-source-mapping \
--function-name  receiveMessage \
--event-source-arn "arn:aws:sqs:us-east-1:000000000000:TestQueue" \
--batch-size 1 \
--starting-position LATEST \
--endpoint http://localhost:4574
```

Then it behaves as expected - except without the event source being created during the serverless deploy; the same issue is present when triggering the `sendMessage` function adds to the queue but the `receiveMessage` function is not triggered, but if I again manually send a message to a queue it does work - this isn't as much of an issue for me as I can just isolate the behaviours anyway and test them individually.

Just wondering if the serverless config is invalid for localstack > 0.10? If so I couldn't find anything.

**Comment by brentmitchell25** [comment] 2019-10-06 16:08
I noticed the problem is lies [here in the moto library](https://github.com/spulec/moto/blob/master/moto/awslambda/models.py#L481). I am not sure if it a moto problem or a problem with localstack not passing the right data along to moto. The `properties['FunctionName']` returns the ARN of the lambda function when it should only return the name of the function.

**Comment by mrosales** [comment] 2020-03-29 06:00
I'm not sure about the second issue you were facing, but it seems like the first bug of the event source not working with SQS send message batch is also reported here in #1364

**Comment by whummer** [comment] 2020-08-23 21:09
Thanks for reporting @Thomas-Franklin @brentmitchell25 @mrosales . This should be fixed in the meantime - another small integration test has been added in #2865 . Please report here if the problem persists. Thanks

**Closed by whummer** 2020-08-23 21:09 UTC
