### ISSUE TITLE
bug: SQS SendMessage fails from @aws-sdk/client-sqs@3.443.0 onwards

### ISSUE THREAD

**Issue by rhobweb** [localstack/localstack#9599] opened 2023-11-10 12:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to send a message to SQS fails.

The following code generates the error:

"Unexpected token < in JSON at position 0 ..."

`const { SQSClient, SendMessageCommand } = require( '@aws-sdk/client-sqs' );
const sqsClient = new SQSClient( { region: process.env.region } );
. . .
const sendMessageCommand = new SendMessageCommand( params );
const response                         = await sqsClient.send( sendMessageCommand );`

### Expected Behavior

The message should send to the SQS queue without error.
This works as expected when using @aws-sdk/client-sqs@3.441.0.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

LocalStack is being started with docker-compose.yml.

Make an API gateway call that invokes a lambda that sends a message to a SQS queue.

### Environment

```markdown
- OS: WSL2 Ubuntu;
- LocalStack: v3 (latest), but same issue with v2.3.0.
```

### Anything else?

The lambda function works fine with @aws-sdk/client-sqs@3.447.0 when running in the cloud, but not under LocalStack.

By hacking the AWS SDK it was found that the SQS error generated is in XML format.
The error generated is shown below.
Comparing @aws-sdk/client-sqs@3.443.0 to 3.441.0 it looks as though the module is expecting JSON rather than XML.

<?xml version='1.0' encoding='utf-8'?>
 <ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
   <Error>
     <Code>InternalError</Code>
     <Message>exception while calling sqs with unknown operation: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).</Message>
   </Error>
   <RequestId>a90d176e-b755-409d-86e3-b47b75855f0d</RequestId>
 </ErrorResponse>
 </xml>

**Comment by bentsku** [comment] 2023-11-10 12:50
Hello, this is a duplicate of #8267 and we are actively working on this critical issue. Please follow the linked issue for resolution. Thanks!

**Closed by bentsku** 2023-11-10 12:50 UTC
Labels: type: bug, status: triage needed
