### ISSUE TITLE
Error: error waiting for SQS Queue Policy to delete: Error unmarshaling policy: unexpected end of JSON input

### ISSUE THREAD

**Issue by csnick93** [localstack/localstack#4225] opened 2021-06-28 15:12 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am using :
* LocalStack: 
```
localstack                        0.12.13.1
localstack-client              1.20
localstack-ext                  0.12.10.11
```
* Terraform: 
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.47.0
```

When setting up an infrastructure containing only a s3 bucket with an associated event notification mechanism to a sqs queue, the destruction of this infrastructure fails using LocalStack (works fine using AWS). The resulting error message is

```
aws_sqs_queue_policy.distributor: Still destroying... [id=http://localhost:4566/000000000000/distributor_queue, 10s elapsed]
aws_sqs_queue_policy.distributor: Still destroying... [id=http://localhost:4566/000000000000/distributor_queue, 20s elapsed]
aws_sqs_queue_policy.distributor: Still destroying... [id=http://localhost:4566/000000000000/distributor_queue, 30s elapsed]
aws_sqs_queue_policy.distributor: Still destroying... [id=http://localhost:4566/000000000000/distributor_queue, 40s elapsed]
aws_sqs_queue_policy.distributor: Still destroying... [id=http://localhost:4566/000000000000/distributor_queue, 50s elapsed]
aws_sqs_queue_policy.distributor: Still destroying... [id=http://localhost:4566/000000000000/distributor_queue, 1m0s elapsed]
╷
│ Error: error waiting for SQS Queue Policy (http://localhost:4566/000000000000/distributor_queue) to delete: Error unmarshaling policy: unexpected end of JSON input
│ 
```

## Expected behavior

I would expect the destruction of the infrastructure to go through without any errors (as is the case when deploying using AWS).

## Actual behavior

Getting an error message related to the aws_sqs_queue_policy `distributor`: 
```
│ Error: error waiting for SQS Queue Policy (http://localhost:4566/000000000000/distributor_queue) to delete: Error unmarshaling policy: unexpected end of JSON input
```

# Steps to reproduce

## Command used to start LocalStack

```
export SERVICES=sqs,s3,iam,kinesis,sts && \
localstack start
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

The following are the terraform files used in the infrastructure. Put them in a directory and run `terraform init && terraform apply` to construct the infrastructure and later on call `terraform destroy` to destroy the infrastructure and witness the error message.

aws.tf
```
provider "aws" {
  access_key                  = "mock_access_key"
  region                      = "eu-central-1"
  s3_force_path_style         = true
  secret_key                  = "mock_secret_key"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}
```

s3.tf
```
resource "aws_s3_bucket" "local_test_events" {
  bucket        = "local-test-events"
  acl = "private"
  force_destroy = true        
} 
  
  
resource "aws_s3_bucket_public_access_block" "s3_privacy" {
  bucket = aws_s3_bucket.local_test_events.id
    
  block_public_acls   = true
  block_public_policy = true
    
  depends_on = [   
    aws_s3_bucket.local_test_events
  ] 
}   
    
resource "aws_s3_bucket_notification" "event_dump" {
  bucket = aws_s3_bucket.local_test_events.id
    
  queue {          
    queue_arn     = aws_sqs_queue.distributor.arn
    events        = ["s3:ObjectCreated:*"]
  }

  depends_on = [
            aws_s3_bucket.local_test_events,
            aws_s3_bucket_public_access_block.s3_privacy,
            aws_sqs_queue.distributor,
            aws_sqs_queue_policy.distributor
  ]
}
```

sqs.tf
```
resource "aws_sqs_queue" "distributor" {
  name = "distributor_queue"
} 
  

resource "aws_sqs_queue_policy" "distributor" {
  queue_url = aws_sqs_queue.distributor.id
  policy    = data.aws_iam_policy_document.sqs_distributor.json
} 
    
data "aws_iam_policy_document" "sqs_distributor" {
  policy_id = "__default_policy_ID"
  statement {
    actions = [
      "sqs:SendMessage",
    ]
    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
  
      values = [
        "${aws_s3_bucket.local_test_events.arn}",
      ]
    }
    effect = "Allow"
    principals {
      type = "AWS"
      identifiers = [
      "*"]  
    }       
    resources = [
      "${aws_sqs_queue.distributor.arn}",
    ]
    sid = "__default_statement_ID"
  }
}
```

Thanks a lot for your help and let me know if I can be of any assistance to solve the issue!

**Comment by jrauen** [comment] 2021-06-30 13:42
I was also experiencing this issue and I believe I've found the root cause. The terraform plugin function responsible for removing the `aws_sqs_queue_policy` resource is found [here](https://github.com/hashicorp/terraform-provider-aws/blob/ccc13f55709c860a2130ecee6e21acde2318e936/aws/resource_aws_sqs_queue_policy.go#L104). Within the function at line 121 there is a wait statement that checks to ensure that the queue policy has been set to the "empty" policy after deletion.

Within localstack the [_set_queue_attributes](https://github.com/localstack/localstack/blob/2b16692bef50ad38242962ca001492738b451361/localstack/services/sqs/sqs_listener.py#L121) function returns without removing the sqs policy from the queue when using an sqs backend other than elasticmq (moto is default). This can be verified by listing the attributes of a queue in localstack, running the set queue attributes command to set the policy to an empty string, and then listing the queue attributes again.

```
root@7e835f06b095:/tmp/bob# awslocal sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/wt-threat-1
2345678-dev-alert_queue_network
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1625056999.760787",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1625059421.06413",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:wt-threat-12345678-dev-alert_queue_network",
        "Policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Sid\": \"\", \"Effect\": \"Allow\", \"Action\": \"sqs:SendMessage\", \"Resource\": \"arn:aws:sqs:us-east-1:000000000000:wt-threat-12345678-dev-alert_queue_network\", \"Condition\": {\"ArnEquals\": {\"aws:SourceArn\": [\"arn:aws:s3:::wt-threat-12345678-dev\"]}}}]}",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
root@7e835f06b095:/tmp/bob# awslocal sqs set-queue-attributes --queue-url http://localhost:4566/000000000000/wt-threat-1
2345678-dev-alert_queue_network --attributes Policy=""
root@7e835f06b095:/tmp/bob# awslocal sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/wt-threat-1
2345678-dev-alert_queue_network
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1625056999.760787",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1625059480.963466",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:wt-threat-12345678-dev-alert_queue_network_bah",
        "Policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Sid\": \"\", \"Effect\": \"Allow\", \"Action\": \"sqs:SendMessage\", \"Resource\": \"arn:aws:sqs:us-east-1:000000000000:wt-threat-12345678-dev-alert_queue_network\", \"Condition\": {\"ArnEquals\": {\"aws:SourceArn\": [\"arn:aws:s3:::wt-threat-12345678-dev\"]}}}]}",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
```

I'm not sure how the moto backend works so I'm unable to propose a specific code change at this time to fix the issue and test it, but it looks like the solution is to ensure the `_set_queue_attributes` is properly implemented for the moto backend.

**Comment by csnick93** [comment] 2021-07-01 14:12
Hey @jrauen ,
thanks a lot for taking the time to write this extensive reply! The workaround you proposed works just fine for now :)

**Comment by mgagliardo** [comment] 2021-07-01 14:17
Thanks @jrauen ! Great debugging on that one, I was struggling around this and now I have found the issue (which is a very weird bug actually unrelated to moto directly but more with how the API works internally). I'm pushing a PR in a couple hours, thanks again!

**Comment by mgagliardo** [comment] 2021-09-01 00:27
Tests passed. Closing this one

**Closed by mgagliardo** 2021-09-01 00:27 UTC
