### ISSUE TITLE
Performance: LS 1.3.0/1.3.1/1.4.0 SQS performance (receiving/deleting) is degraded comparing to 1.2.0

### ISSUE THREAD

**Issue by a-wi** [localstack/localstack#7342] opened 2022-12-16 09:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SQS operations with LocalStack 1.3.0 are much slower comparing to 1.2.0 - 5-10% for sending messages, ~2.5 times for receiving and deleting.

![image](https://user-images.githubusercontent.com/7330332/208067766-4ab2801b-8562-4bea-ae10-067f2f423dba.png)

![image](https://user-images.githubusercontent.com/7330332/208067816-3b2aba76-dd60-45cd-b2bf-56e479e2dfec.png)

![image](https://user-images.githubusercontent.com/7330332/208067847-11f212d0-a115-4a03-9d67-f5b71ea7506e.png)

### Expected Behavior

Performance of SQS operations for LS 1.3.0 should be at least as good as for 1.2.0.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -p 4566:4566 --rm -e SERVICES=sqs -e EAGER_SERVICE_LOADING=1 localstack/localstack:1.3.0

#### Code snippet to check SQS performance
```cs
static async Task TestSQS(int numMsgs)
{
    Stopwatch stopWatch = new();

    using (AmazonSQSClient SQS = new("ignore", "ignore", new AmazonSQSConfig { ServiceURL = "http://localhost:4566" }))
    {
        // Create a queue.
        CreateQueueResponse createQueueResp = await SQS.CreateQueueAsync($"testQueue_{Guid.NewGuid()}");
        string msgText = new('x', 100);
        ReceiveMessageRequest receiveMessageReq = new(createQueueResp.QueueUrl)
        {
            WaitTimeSeconds = 5,
            MaxNumberOfMessages = 10
        };

        // Send messages
        Console.WriteLine($"Sending {numMsgs} messages...");
        Task[] sentMsgs = new Task[numMsgs];
        stopWatch.Restart();
        for (int i = 0; i < numMsgs; i++)
        {
            sentMsgs[i] = SQS.SendMessageAsync(createQueueResp.QueueUrl, msgText);
        }
        await Task.WhenAll(sentMsgs);
        stopWatch.Stop();
        Console.WriteLine($"Num. messages={numMsgs}  Sending time={stopWatch.ElapsedMilliseconds:F0} ms");

        // Process (receive/delete) messages
        Console.WriteLine($"Processing {numMsgs} messages...");
        Stopwatch stopWatchRcv = new();
        Stopwatch stopWatchDel = new();
        int msgCount = 0;
        stopWatch.Restart();
        while (msgCount < numMsgs)
        {
            stopWatchRcv.Start();
            receiveMessageResp = await SQS.ReceiveMessageAsync(receiveMessageReq);
            stopWatchRcv.Stop();
            stopWatchDel.Start();
            foreach (Amazon.SQS.Model.Message msg in receiveMessageResp.Messages)
            {
                await SQS.DeleteMessageAsync(createQueueResp.QueueUrl, msg.ReceiptHandle);
            }
            stopWatchDel.Stop();
            msgCount += receiveMessageResp.Messages.Count;
        }
        stopWatch.Stop();
        Console.WriteLine($"Num. messages={msgCount}  Processing time={stopWatch.ElapsedMilliseconds:F0} ms  (Receiving={stopWatchRcv.ElapsedMilliseconds:F0} ms Deleting={stopWatchDel.ElapsedMilliseconds:F0} ms)");

        await SQS.DeleteQueueAsync(createQueueResp.QueueUrl);
    }
}
```

### Environment

```markdown
- OS: Win 10
- LocalStack: 1.3.0
- AWS SDK SQS 3.7.100.36 / .NET 6
```

**Comment by chrisribble** [comment] 2023-01-22 20:40
FWIW, `1.2.0` also has substantially worse performance than `0.14.5` (the version we've been sticking on my team with due to how much time newer versions add to our integration tests).

@a-wi , it would be interesting to see data for `0.14.5` included here as well if it's straightforward to collect it.

In my use case (start Docker container, send a handful of messages and consume them), `0.14.5` is dramatically faster than both `1.2.0` and `1.3.1`.

**Comment by a-wi** [comment] 2023-03-02 10:08
The issue still stands for LS 1.4.0.
![image](https://user-images.githubusercontent.com/7330332/222397639-78b564ac-e70b-49f9-aa17-b2b4383e50c6.png)
![image](https://user-images.githubusercontent.com/7330332/222397748-04376827-fefd-41fc-908a-8f6ea035e796.png)
![image](https://user-images.githubusercontent.com/7330332/222397811-ca201167-62ae-4243-99d1-e1234ae8d047.png)

**Comment by xtaixe** [comment] 2023-05-03 08:17
+1 to to both the issue and to what @chrisribble is saying.

We have at least 1 team stuck on `0.14.5`. They are considering moving to `1.2.0` by splitting the tests in batches, since otherwise they can't keep upgrading our internal tool which we already have adapted to LocalStack 1.x (initialization hooks).

By the way, we need to do some further checks, but in case it helps, the slowdown seems to only happen on AMD and not ARM.

**Comment by xtaixe** [comment] 2023-05-03 10:10
Discarded architecture. Last experiment points this might be also related to Docker version somehow, since upgrading Docker Desktop from `4.12` to `4.19` reduced the time by half.

**Comment by xtaixe** [comment] 2023-05-03 16:24
Back to crazytown... on AMD, running on latest Docker doesn’t seem to help and the team test suite takes the 24 min mentioned before. So, at least on AMD, the perfomance regressions stated in this issue are clear, since the test suite runs in about 8 min with LocalStack `0.14.5` (same as ARM with latest Docker and LocalStack `1.4.0`) .

**Comment by thrau** [comment] 2023-05-06 13:44
Thanks for further debugging @xtaixe, and thanks for sticking with localstack regardless!

Could you share the particular queue configurations you are using? Are they fifo queues or standard queues? Do they have redrive policies or something similar?

I'd like to look into this more closely but haven't been able to really reproduce the numbers, but so far I've only tried on Linux systems without Docker.

**Comment by thrau** [comment] 2023-05-10 00:22
Hey folks, a quick update:

I replicated the numbers using this script:
```python
import os
import timeit

import boto3

os.environ["AWS_REGION"] = "us-east-1"
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"
os.environ["ACCESS_KEY_ID"] = "test"
os.environ["SECRET_ACCESS_KEY"] = "test"

sqs = boto3.client("sqs", endpoint_url="http://localhost:4566")

queue_url = None


def setup_queue():
    global queue_url
    queue_url = sqs.create_queue(QueueName="my-queue")["QueueUrl"]


def send_message():
    sqs.send_message(QueueUrl=queue_url, MessageBody="x" * 100)


def receive_message():
    sqs.receive_message(QueueUrl=queue_url)


def main():
    n = 1000
    result = timeit.timeit(stmt=send_message, setup=setup_queue, number=n)
    print(
        f"send message: {n} requests took {result:.4f}s = {(result * 1000) / n:.4f} ms/op = {n / result:.2f} req/sec"
    )

    n = 1000
    result = timeit.timeit(stmt=receive_message, setup=setup_queue, number=n)
    print(
        f"receive message: {n} requests took {result:.4f}s = {(result * 1000) / n:.4f} ms/op = {n / result:.2f} req/sec"
    )


if __name__ == "__main__":
    main()
```

## Results

My results are as follows:
| Version | Send Message (req/sec) | Receive Message (req/sec) |
|---------|------------------------|---------------------------|
| latest  | 156.24                 | 270.85                    |
| 1.3.0   | 162.89                 | 271.91                    |
| 1.2.0   | 527.82                 | 563.72                    |
| 0.14.5   | 407.50                 | 416.38                    |
| 0.13.0  | 166.14                 | 56.90                     |

I was not able to reproduce @chrisribble's issue described in https://github.com/localstack/localstack/issues/7342#issuecomment-1399602004 . I'd have to get more information on what exactly is slow and adapt the benchmark.

I was however able to reproduce the performance decrease seen with 1.3.0, and also able to confirm my suspicion that it has to do with the sqs/cloudwatch integration introduced in #7182 empirically using git bisect and the script from above. We did make cloudwatch sending async, but it appears the queuing of the request calls still adds too much latency. We'll have to investigate how to improve the cloudwatch integration.

## Workaround

In the meantime, we introduced a change to disable cloudwatch metrics logging: #8269. If you start localstack with `SQS_DISABLE_CLOUDWATCH_METRICS=1`, SQS will no longer call cloudwatch, and starts exhibiting the same performance again as in 1.2.0.

running the above script with `latest` and `SQS_DISABLE_CLOUDWATCH_METRICS=1` gives me:
```
send message: 1000 requests took 2.0803s = 2.0803 ms/op = 480.71 req/sec
receive message: 1000 requests took 2.0048s = 2.0048 ms/op = 498.80 req/sec
```

Sorry this took so long. I hope this is an acceptable workaround for now @a-wi @xtaixe! /cc @steffyP

**Comment by xtaixe** [comment] 2023-05-10 07:28
@thrau any initial ideas on why the slowdown only happens on AMD? Were you able to reproduce that? I'm just curious...

**Comment by thrau** [comment] 2023-05-10 13:10
I can only speculate as I haven't investigated it in detail.

We're invoking `ThreadPoolExecutor.submit` a lot https://github.com/localstack/localstack/blob/2977f13b8028bcc8b393e9797a2ac37f78e9b590/localstack/services/sqs/provider.py#L185-L192

So if I had to take a guess I'd say it has to do and how threads are scheduled which may exhibit slightly different behavior depending on the platform which then compounds to the performance degradation. Although `publish_sqs_metric` should be IO-bound, it's still possible that the GIL is slowing us down. Again, just speculation.

**Closed** 2023-05-10 15:11 UTC
Labels: type: bug, area: performance, status: resolved/workaround, aws:sqs

**Comment by a-wi** [comment] 2023-05-11 09:20
I can confirm that latest LS 2.0.3 dev with `SQS_DISABLE_CLOUDWATCH_METRICS=1` is much faster than 1.4 and comparable with 1.2 (however slightly slower):
![image](https://github.com/localstack/localstack/assets/7330332/657af543-c464-461f-850a-eb20edfc34b8)
![image](https://github.com/localstack/localstack/assets/7330332/ad67dd69-cca7-4814-8adf-461de6d2c659)
![image](https://github.com/localstack/localstack/assets/7330332/6852d7a0-e461-4fd6-8b0f-5d6b546b6af3)

**Comment by thrau** [comment] 2023-05-11 10:20
> A workaround is not a fix... Even if this is now not a priority now, if there isn't any other issue to follow, why not keep this open, so we know we can remove the workaround if it's eventually properly fixed?

TBH i think sqs -> cloudwatch integration will slow down SQS, nothing will really change that. so disabling cloudwatch integration is a fix for the performance issue.

**Comment by chrisribble** [comment] 2024-01-20 19:42
Sorry to comment on a closed issue, but I finally got a chance to try upgrading to `3.0.2` with `SQS_DISABLE_CLOUDWATCH_METRICS=1` and performance is within measurement error compared to `0.14.2`.

🥳

**Comment by steffyP** [comment] 2024-01-29 13:04
Hi @chrisribble, great to hear 🎉 
We also recently added a new cloudwatch provider, which should also solve the performance issue. 
You could give it another try with the `PROVIDER_OVERRIDE_CLOUDWATCH=v2` flag enabled. 
We would be happy to get your feedback! 🙏

**Comment by chrisribble** [comment] 2024-01-29 15:15
> Hi @chrisribble, great to hear 🎉 We also recently added a new cloudwatch provider, which should also solve the performance issue. You could give it another try with the `PROVIDER_OVERRIDE_CLOUDWATCH=v2` flag enabled. We would be happy to get your feedback! 🙏

At least for my simple test scenario, using `PROVIDER_OVERRIDE_CLOUDWATCH=v2` (instead of `SQS_DISABLE_CLOUDWATCH_METRICS=1`) also seems to result in reasonable performance.
