### ISSUE TITLE
com.amazonaws.util.IOUtils with wrong method signature on the classpath causes an exception

### ISSUE THREAD

**Issue by Alexey007gold** [localstack/localstack#952] opened 2018-10-08 08:46 UTC
When I deploy a lambda written in java, that uses aws dependencies, and these dependencies are trying to use IOUtils.release() method, exception is thrown.
java.lang.NoSuchMethodError: com.amazonaws.util.IOUtils.release(Ljava/io/Closeable;Lorg/apache/commons/logging/Log;)V 

class is loaded from /opt/code/localstack/localstack/infra/localstack-utils-fat.jar
the IOUtils.release method is actually present there but with different signature of Log argument

**Comment by whummer** [comment] 2020-08-07 17:11
Thanks for reporting. This is looks like a duplicate of #1160, and should be fixed in #2378 . Please report here if the problem persists. Thanks

**Closed by whummer** 2020-08-07 17:11 UTC
