### ISSUE TITLE
lambda can't import numpy in localstack

### ISSUE THREAD

**Issue by 0rangeMan** [localstack/localstack#646] opened 2018-03-08 15:05 UTC
I am deploying lambda function written in python to localstack.
Everything works smoothly except recently I am using `numpy`, `pandas` etc. inside my lambda functions.
I packaged `numpy` by picking it up from site-packages/ and zip it in...

But, the following error comes up:

ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

I have been googling around, looks like the reason is that `numpy` has some extra (even OS) dependencies because large part of it is written in C...

Any clue of how to fix it in a decent way?

**Comment by 0rangeMan** [comment] 2018-03-08 15:55
Update:

I have tried to upload the same zip to AWS env, it works fine.

Looks like either localstack doesn't create the same execution env as AWS or the linux hosting localstack is missing some extra dependencies.

**Comment by whummer** [comment] 2018-03-31 18:53
Thanks for reporting @0rangeMan . Any chance you can share the zip file with us to reproduce he issue? (please remove any sensitive files.) Also, which command exactly are you using to start localstack?

**Comment by 0rangeMan** [comment] 2018-04-05 12:14
[numpy-test.zip](https://github.com/localstack/localstack/files/1879915/numpy-test.zip)
This should be the zip file.
docker-compose is used to start localstack.

**Comment by rsosnin** [comment] 2019-04-02 12:10
I am having same issue...(using python2.7) Using same lambda artifact (zip containing the lambda code + external dependencies) - working in AWS, but cannot deploy in localstack:
```
localstack-init_1        | Lambda | Error occurred while creating Function: save_event | Details: An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 4): Unknown error: ('Unable to get handler function from lambda code.', ImportError('No module named <MY_DEPENDENCY>',)) Traceback (most recent call last):
```

BUT

I'm getting this error actually when running with mode: `LAMBDA_EXECUTOR: local`
But if I use mode: `LAMBDA_EXECUTOR: docker-reuse` - i don't have that issue

**Comment by justinian336** [comment] 2019-05-22 05:11
Before this gets closed: I have the same problem, and it gets solved by using `docker-reuse`, but probably not everyone wants to run the localstack container in privileged mode.

**Comment by anthonydelarosa** [comment] 2019-07-09 16:30
any update on this? I'm trying to test localstack with a Lambda function that works in Production as it imports numpy like it should but with localstack I get the same error "ImportError: Missing required dependencies ['numpy']" 

this is the way i'm trying to create my Lambda function: awslocal lambda create-function --function-name test --role my-role --runtime python3.6 --handler app.handler --timeout 60 --memory-size 512 --zip-file "fileb://file.zip"

**Comment by anthonydelarosa** [comment] 2019-07-09 17:07
ok i figured it out and thought i'd share the solution here
unlike npm where by default it creates a folder called node_modules and Lambda is smart enough to look for the dependencies in there Python doesn't create such folder so when you do the old "pip install some_package --target ." it is installed in the root of the project. Like most people I created a folder called "packages" and told my Python app.py file to look for the dependencies in ./packages folder and even though this works in AWS Lambda for some reason Localstack doesn't like it. I then removed that packages folder and had all the dependencies installed at the root of the project, created my Lambda function again and it worked. That was my solution although very messy now 'cause everything is at the root of the folder/project

**Comment by whummer** [comment] 2019-11-08 19:56
Thanks for sharing your solution @anthonydelarosa ! Closing this issue - please report here if the problem persists.

**Closed by whummer** 2019-11-08 19:56 UTC
Labels: bug, diverges-from-aws

**Comment by ltomes** [comment] 2020-03-19 22:53
I believe this is still an issue. 
If I try to run a python3.8 lambda with `localstack/localstack:0.10.8` that was built in `lambci/lambda:build-python3.8` I get c binding errors. 
```
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/opt/code/localstack/.venv/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.
Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by andrybicio** [comment] 2021-03-22 11:16
> [numpy-test.zip](https://github.com/localstack/localstack/files/1879915/numpy-test.zip)
> This should be the zip file.
> docker-compose is used to start localstack.

One note: this works only with Python2.7

**Comment by whummer** [comment] 2022-09-09 17:59
For the record - AWS ships a custom built version of numpy (and other python libraries) that are compatible with the Lambda runtime environment.

For LocalStack Pro users, you should be able to point to the Lambda layer that's published here: https://aws-sdk-pandas.readthedocs.io/en/2.16.1/layers.html

When running the following minimal working example (with Pro):
```
echo 'def handler(context, event): import numpy; print(numpy)' > /tmp/testlambda.py
(cd /tmp; zip testlambda.zip testlambda.py)
awslocal lambda create-function --function-name func1 --runtime python3.9 --role r1 --handler testlambda.handler --timeout 30 --zip-file fileb:///tmp/testlambda.zip --layers arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python39:9
funcArn=$(awslocal lambda get-function --function-name func1 | jq -r .Configuration.FunctionArn)
sleep 20
awslocal lambda invoke --function-name func1 /tmp/tmp.out
```
... the result should be something like:
```
>START RequestId: e946bea4-2f48-1b78-87fd-4a0d7c0142db Version: $LATEST
> <module 'numpy' from '/opt/python/numpy/__init__.py'>
> END RequestId: e946bea4-2f48-1b78-87fd-4a0d7c0142db
> REPORT RequestId: e946bea4-2f48-1b78-87fd-4a0d7c0142db	Init Duration: 1409.05 ms	Duration: 3965.59 ms	Billed Duration: 3966 ms	Memory Size: 1536 MB	Max Memory Used: 166 MB
```

**Comment by ltomes** [comment] 2022-09-09 20:09
Not every orgs security posture allows the use of public lambda layers. I think the reality of localstack relying on a version of python that may not be the version ran by the end user, and that those two python environments are not running in isolated VENVs is the cause of this. localstack should be able to run in isolation of whatever the client code is. 

Alas I don't have any projects running on localstack at the moment, just adding context from what I remember of this issue, and how the docker was configured. I presume localstack users are not running into this/don't run cbinded libraries with particular python version requirements or this closed thread would have a lot more feedback. 

Localstack is pretty cool and I'm glad it solves a lot of use cases for local development of lambdas.

**Comment by Psynbiotik** [comment] 2023-05-26 07:49
I managed to fix this without using layers

- first make sure to source/use a python virtual environment that matches the runtime for the lambda (3.9 in my case)
- pip3 install --target ./package --platform=manylinux2014_aarch64 --only-binary=:all: --python 3.9 --upgrade numpy
- pip3 install --target ./package --platform=manylinux2014_aarch64 --only-binary=:all: --python 3.9 --upgrade numexpr

package up the binary platform specific version of numpy and numexpr, I'm running aarch64 but for a lot of people I imagine it will be manylinux2014_x86_64 instead of manylinux2014_aarch64, see this for valid options: https://github.com/pypa/manylinux

Note: numpy does not have support for manylinux_2_28 or manylinux_2_24 at the time of this comment
