### ISSUE TITLE
API Gateway does not allow CORS preflight when using withCredentials in requests (Missing Mock integrations)

### ISSUE THREAD

**Issue by richardbaltariu** [localstack/localstack#3924] opened 2021-04-23 11:27 UTC
# This is a ...

[x] bug report
[ ] feature request

# Detailed description

When running an `serverless-express` API in a lambda pushed to localstack in Docker, OPTIONS requests from a client with the `withCredentials` flag fail because of the wildcard `'*'` in `Access-Control-Allow-Origin` header returned by calling the endpoint (e.g.: `http://localhost:4566/restapis/<id>/<stage>/_user_request_/api/`). The request doesn't reach the lambda at all.

docker-compose.yml:
```yml

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=iam,lambda,apigateway,s3,ses,sts,sns,cloudformation,cloudwatch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=0
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${PWD}/.localstack
      - LAMBDA_DOCKER_NETWORK=bridge
    volumes:
      - "${PWD}/.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

## Expected behavior

Allow defining a single(?) allowed origin for the header so that the preflight request doesn't fail.

## Actual behavior

Browser errors out with: 

```
Access to XMLHttpRequest at '<endpoint>' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

# Steps to reproduce

- Create a simple API based on `serverless-express` with `express-session` as session handler.
- Use `withCredentials` flag to send requests to the API via `axios` or similar

## Command used to start LocalStack

`docker-compose up`

**Comment by pandomic** [comment] 2021-05-03 19:20
Thanks for reporting @richardbaltariu. Could you attach a sample repo reproducing the issue since there various ways to configure express and express-session?

**Comment by richardbaltariu** [comment] 2021-05-04 08:43
Hi @pandomic , thank you for checking this out. I've created a very stripped down version of the setup we have to reproduce the issue. You can check it out here: https://github.com/richardbaltariu/ls-test

**Comment by pandomic** [comment] 2021-05-10 08:55
Thanks @richardbaltariu I'll check later tonight

**Comment by pandomic** [comment] 2021-05-11 22:02
@richardbaltariu after having a close look at CloudFormation template generated by Serverless I found it using "mock" integration for OPTIONS requests. Unfortunately, "mock" integrations are currently unsupported by moto or localstack. I'll convert this ticket into a `feature request`.

As a temporary solution you can try to deal with cors headers on your own:

1. Remove `cors` section from sls file
```yaml
# Serverless yml
...
- http:
     path: /
     method: any
- http:
     path: /{proxy+}
     method: any
```
2. Handle preflight requests in code
```js
// indx.js

// Before other routes
app.options('*', cors(corsOpts))
```
3. Wait until [this PR](https://github.com/localstack/localstack/pull/4003) is merged 🙂 (it fixes doubled response headers which is critical in your case)

@whummer, please correct me if I'm wrong

**Comment by richardbaltariu** [comment] 2021-05-12 10:15
@pandomic This looks good. We'll use the temporary solution until PR is merged. Thank you for checking this out and coming up with a fix.

**Comment by calvernaz** [comment] 2022-01-04 11:21
Hi @richardbaltariu thank you for detailed verification steps, that makes a big difference. 

So, it seems there is a misconception how CORS works. CORS is a policy applicable to the browser but it's the origin server responsibility to enable access to third party domais.

In your case, the origin server is `localhost:8080`. So you just need to add this snippet to your vue-cli-service and it should be fine.

`vue.config.js` inside the `frontend` directory.
```
module.exports = {
	configureWebpack: {
		devServer: {
			headers: {
				"Access-Control-Allow-Origin": "*",
				"Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
				"Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization",
				"Access-Control-Allow-Credentials": true
			}
		}
	}
};
```

Also make sure to change the rest api id in `App.js`.

Tell me how it goes, i could reproduce the issue and the above policy worked afterwards.

**Closed** 2022-01-21 23:01 UTC
Labels: awaiting reporter response, aws:apigateway
