### ISSUE TITLE
Dockerfile.base node:alpine using node v10

### ISSUE THREAD

**Issue by montge** [localstack/localstack#1555] opened 2019-09-10 15:00 UTC
It appears that there's an issue with referencing node:alpine (which is currently based on node v12). This appears to be an upstream issue.

```
make: Leaving directory '/opt/code/localstack/localstack/node_modules/leveldown/build'
make: *** [leveldown.target.mk:127: Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.184-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/code/localstack/localstack/node_modules/leveldown
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN localstack@0.0.1 No repository field.
npm WARN localstack@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@4.0.2 (node_modules/leveldown):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@4.0.2 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Modified the `Dockerfile.base` to leverage node v10, which seems to build fine after.

```
FROM node:10-alpine
```

node-gyp still has warnings, but I think that's mostly because that's still on python 2

**Comment by whummer** [comment] 2019-09-10 19:19
Thanks for reporting @montge . Is this consistently reproducible? I just did a full build (without caching) of the base image, and it seemed to work..?

**Comment by whummer** [comment] 2019-10-05 10:52
Unable to reproduce - closing. Please report back here if the problem persists and is consistently reproducible. Thanks!

**Closed by whummer** 2019-10-05 10:52 UTC
Labels: bug, installation, needs-triaging
