### ISSUE TITLE
DynamoDB streams records seem to be always "NEW_AND_OLD_IMAGES" regardless the configuration

### ISSUE THREAD

**Issue by fredliporace** [localstack/localstack#3851] opened 2021-04-08 22:34 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Thanks for this awesome project!

It seems to me that the records generated by DynamoDB streams are always set to "NEW_AND_OLD_IMAGES" no matter how it is configured.

## Expected behavior

```StreamViewType``` and the remaining stream records should follow the configuration.

## Actual behavior

```StreamViewType``` from generated DynamoDB streams records are always ```NEW_AND_OLD_IMAGES``` regardless of the stream configuration.

# Steps to reproduce

## Command used to start LocalStack

Using docker-compose and localstack 0.12.9.1

```yaml
version: '2.1'

services:
  localstack:
    container_name: cbers04aonaws-localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs,s3,sns,lambda,cloudwatch,dynamodb
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash

# Table creation, StreamViewType reported as KEYS_ONLY as expected
$ awslocal dynamodb create-table --table-name BarkTable --attribute-definitions AttributeName=Username,AttributeType=S --key-schema AttributeName=Username,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --stream-specification StreamEnabled=true,StreamViewType=KEYS_ONLY
{
    "TableDescription": {
        "AttributeDefinitions": [
            {
                "AttributeName": "Username",
                "AttributeType": "S"
            }
        ],
        "TableName": "BarkTable",
        "KeySchema": [
            {
                "AttributeName": "Username",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": 1617920506.981,
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": 0.0,
            "LastDecreaseDateTime": 0.0,
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5
        },
        "TableSizeBytes": 0,
        "ItemCount": 0,
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable",
        "StreamSpecification": {
            "StreamEnabled": true,
            "StreamViewType": "KEYS_ONLY"
        },
        "LatestStreamLabel": "2021-04-08T22:21:46.981",
        "LatestStreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981"
    }
}

# Getting information required by get-records, ShardID...
$  awslocal dynamodbstreams describe-stream --stream-arn="arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981"
{
    "StreamDescription": {
        "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981",
        "StreamLabel": "2021-04-08T22:21:46.981",
        "StreamStatus": "ENABLED",
        "TableName": "BarkTable",
        "KeySchema": [
            {
                "AttributeName": "Username",
                "KeyType": "HASH"
            }
        ],
        "Shards": [
            {
                "ShardId": "shardId-00000001617900000000-000000000000",
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49617150634644171324284995361341429422745156736717422594"
                }
            }
        ]
    }
}

# ... and shard iterator
$ awslocal dynamodbstreams get-shard-iterator --stream-arn="arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981" --shard-id="shardId-00000001617900000000-000000000000" --shard-iterator=TRIM_HORIZON
{
    "ShardIterator": "AAAAAAAAAAEPsmwF8Fvs/QhgJDRP15GeHp3/u7iiURU8nIyDMrMapgxLeTPURcS4x+w0gHLk0fZHukhfuOS4DXzDAOYxLKRdVX2NSY+f8Si6EnU1AomYwfJyOKvqUV2ZdHWl+5vezq4Q4HWCk97ACEyXSqr9PIHsg7Du/Z8RiVc/i99Jtc5I98diZ42qxVjiGsKTj2i+zOw2wUR1tZYrC2NnFD0fzgiq"
}

# Changing table to create event
$ awslocal dynamodb put-item --table-name="BarkTable" --item Username={S="Fred"}
{
    "ConsumedCapacity": {
        "TableName": "BarkTable",
        "CapacityUnits": 1.0
    }
}

# Getting records from stream. Note that StreamViewType is NEW_AND_OLD_IMAGES
$ awslocal dynamodbstreams get-records --shard-iterator="AAAAAAAAAAEPsmwF8Fvs/QhgJDRP15GeHp3/u7iiURU8nIyDMrMapgxLeTPURcS4x+w0gHLk0fZHukhfuOS4DXzDAOYxLKRdVX2NSY+f8Si6EnU1AomYwfJyOKvqUV2ZdHWl+5vezq4Q4HWCk97ACEyXSqr9PIHsg7Du/Z8RiVc/i99Jtc5I98diZ42qxVjiGsKTj2i+zOw2wUR1tZYrC2NnFD0fzgiq"
{
    "Records": [
        {
            "eventID": "1",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "us-east-1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1617921007.9894187,
                "Keys": {
                    "Username": {
                        "S": "Fred"
                    }
                },
                "NewImage": {
                    "Username": {
                        "S": "Fred"
                    }
                },
                "SequenceNumber": "49617150634644171324284995361341429422745191302614220802",
                "SizeBytes": 27,
                "StreamViewType": "NEW_AND_OLD_IMAGES"
            }
        }
    ],
    "NextShardIterator": "AAAAAAAAAAEUjdV11Z6RQmhn033hSccCMELdl5BP5YjBYrTFDQ+w5mY0EUknKqVut2rMCt7LaB0lwsPeQnshyaSDglDm2rNj98fwGfa2pdDomsMkWVOOzNiWE2k7QYNm7mYFna7uT7+hIjYLGYsPdytfdl46hieN5M73okNMskY6QIsf+HBX0are/gUx60sx+zl0ljkevoGpIFHar8CpBoLxXocbJSZG"
}





```

**Comment by whummer** [comment] 2021-04-14 11:54
Thanks for reporting @fredliporace . This should be fixed in #3862 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!

**Comment by fredliporace** [comment] 2021-04-15 15:29
@KrishnanRanjithkumar @whummer thanks for looking into that.

I confirm that the latest image solves the reported case with awslocal commands but I'm still getting NEW_AND_OLD_IMAGES types for INSERT events when reading the DynamoDB streams by a lambda function (for  MODIFY events the type is the expected one).

Could not isolate if the problem origin is the integration through lambda or the particular DynamoDB structure or batch writing operation I'm using - the use case reported is a simplified one. Still working on a new use case.

**Comment by KrishnanRanjithkumar** [comment] 2021-04-18 22:48
Thanks for reporting @fredliporace . We'll look into the issue and update you soon.

**Comment by whummer** [comment] 2021-04-22 06:57
Thanks for the update @fredliporace @KrishnanRanjithkumar . This should now be resolved in #3916 - please let us know if there are any other issues. Thanks!

**Closed by whummer** 2021-04-22 06:57 UTC

**Comment by fredliporace** [comment] 2021-04-25 01:37
:wave: @KrishnanRanjithkumar @whummer checked with 2021-04-23 build and the keys are correct.

The records however contain ```NewImage``` key (and ```OldImage``` key for ```MODIFY``` events), AFAIK these [should not](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) be there.

Here is an example record from the same environment described in https://github.com/localstack/localstack/issues/3851#issuecomment-820520453:

```json
{
    "eventID":"028b8026",
    "eventVersion":"1.1",
    "dynamodb": {
        "ApproximateCreationDateTime": 1619313016.530618,
        "SizeBytes": 308,
        "Keys": {"PK": {"S": "CBERS4A_MUX20914520200930"}, "SK": {"S": "SCENE"}},
        "OldImage": {"collection_id": {"S": "CBERS4A_MUX_L4_DN"}, "converted_assets_no": {"N": "3"}, "SK": {"S": "SCENE"}, "scene_id": {"S": "CBERS4A_MUX20914520200930"}, "PK": {"S": "CBERS4A_MUX20914520200930"}, "bucket_prefix": {"S": "CBERS4A/MUX/209/145/CBERS_4A_MUX_20200930_209_145_L4"}, "downloaded_assets_no": {"N": "5"}},
        "NewImage": {"collection_id": {"S": "CBERS4A_MUX_L4_DN"}, "converted_assets_no": {"N": "4"}, "SK": {"S": "SCENE"}, "scene_id": {"S": "CBERS4A_MUX20914520200930"}, "PK": {"S": "CBERS4A_MUX20914520200930"}, "bucket_prefix": {"S": "CBERS4A/MUX/209/145/CBERS_4A_MUX_20200930_209_145_L4"}, "downloaded_assets_no": {"N": "5"}},
        "StreamViewType": "KEYS_ONLY"},
    "awsRegion": "us-east-1",
    "eventSource": "aws:dynamodb",
    "eventName": "MODIFY",
    "eventSourceARN": "arn:aws:dynamodb:us-east-1:000000000000:table/TheTableA"
}
```

Appreciate all the effort put on that. Not sure if this should be another issue since the problem originally reported is solved.

**Comment by KrishnanRanjithkumar** [comment] 2021-04-26 20:12
@fredliporace Thanks for reporting. Could you please try to read the records directly from the DynamoDB streams and check if the behavior is same as that of reading from the lambda function or different?

**Comment by fredliporace** [comment] 2021-04-27 20:37
@KrishnanRanjithkumar I think you are on the right track. When reading the records using ```awslocal``` I do not see the "NewImage" and "OldImage" fields, they are only present on the record received by the lambda function.

There is an exception though: for the first generated record, an ```INSERT```, I get the "NewImage" field in both lambda and awslocal. The only difference I see in my app is that the first insertion is a single item inserted in a batch write operation ,the remaining insertions have multiple items for the same batch write.

**Comment by KrishnanRanjithkumar** [comment] 2021-04-28 09:08
Thanks for the response @fredliporace. I'm not able to reproduce the issue related to exception (for the first generated record). Can you please open a new issue since the original problem reported is resolved and also share some sample code (to reproduce the bug related to exception)?
