### ISSUE TITLE
"Internal Server Error" using ListObjectsV2

### ISSUE THREAD

**Issue by peterbe** [localstack/localstack#215] opened 2017-07-28 16:27 UTC
I have a piece of code that runs in a Celery task. The logic is that it asks S3 if the file is there and how big it is. Based on that the code can decide to upload (PUT) a file or ignore it because a file already exists of the exact same name and size. 

Here's the critical code:
```python
def _key_existing_size(client, bucket, key):
    """return the key's size if it exist, else None.

    See
    https://www.peterbe.com/plog/fastest-way-to-find-out-if-a-file-exists-in-s3
    for why this is the better approach.
    """
    response = client.list_objects_v2(
        Bucket=bucket,
        Prefix=key,
    )
    for obj in response.get('Contents', []):
        if obj['Key'] == key:
            return obj['Size']
```

This works perfectly well when I use AWS S3. But I get an "Internal Server Error" on that. This is the output I get in my Celery task:

```
worker_1         | Traceback (most recent call last):
worker_1         |   File "/app/tecken/boto_extra.py", line 75, in wrapper
worker_1         |     return f(*args, **kwargs)
worker_1         |   File "/app/tecken/boto_extra.py", line 57, in wrapper
worker_1         |     return f(*args, **kwargs)
worker_1         |   File "/app/tecken/upload/tasks.py", line 87, in upload_inbox_upload
worker_1         |     previous_uploads_keys,
worker_1         |   File "/usr/local/lib/python3.6/site-packages/markus/main.py", line 357, in _timer_decorator
worker_1         |     return fun(*args, **kwargs)
worker_1         |   File "/app/tecken/upload/tasks.py", line 195, in create_file_upload
worker_1         |     upload=upload,
worker_1         |   File "/app/tecken/upload/tasks.py", line 228, in upload_file_upload
worker_1         |     size_in_s3 = _key_existing_size(s3_client, bucket_name, key_name)
worker_1         |   File "/app/tecken/upload/tasks.py", line 167, in _key_existing_size
worker_1         |     Prefix=key,
worker_1         |   File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 310, in _api_call
worker_1         |     return self._make_api_call(operation_name, kwargs)
worker_1         |   File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
worker_1         |     raise error_class(parsed_response, operation_name)
worker_1         | botocore.exceptions.ClientError: An error occurred (500) when calling the ListObjectsV2 operation (reached max retries: 4): Internal Server Error
```

How do I get into that to figure out what's wrong?

Also, *before*, I used do a HEAD get on the bucket with that key but found that it's faster and mor convenient to do a `ListObjectsV2`. [See this blog post](https://www.peterbe.com/plog/fastest-way-to-find-out-if-a-file-exists-in-s3)

**Comment by peterbe** [comment] 2017-07-28 16:58
Actually, it only happens sometimes. However, I can't yet decipher if it happens sporadically on the same key. Here was an interesting case:

```python
key = 'v1/mshtml.pdb/DD4D332D611D4416A6336208D1ECEDAA1/mshtml.sym'
response = s3_client.list_objects_v2(
    Bucket=bucket,
    Prefix=key,
)
print(response.get('Contents'))

key = 'v1/propsys.pdb/81C477DAB7BB762F3DEE66831F94369D1/propsys.sym'
response = s3_client.list_objects_v2(
    Bucket=bucket,
    Prefix=key,
)
print(response.get('Contents'))
```
When I ran this, it worked on the first key but `500 Internal Server Error` on the second key. 
Both of these keys certainly exist in the bucket. I verified that by my little aws s3 client wrapper:
```
▶ laws.sh ls testbucket/v1/mshtml.pdb/DD4D332D611D4416A6336208D1ECEDAA1/mshtml.sym
2017-07-28 12:47:33    1854846 mshtml.sym
▶ laws.sh ls testbucket/v1/propsys.pdb/81C477DAB7BB762F3DEE66831F94369D1/propsys.sym
2017-07-28 12:36:11      83015 propsys.sym
```

**Comment by peterbe** [comment] 2017-07-28 16:59
However, when I run the exact same code (see previous comment) again (over and over) it always works. It's almost as if it fails the first time and then not any more.

**Comment by peterbe** [comment] 2017-07-28 17:00
Key question; how can I debug this? 
I'm running locastack in a docker container started with docker-compose.

**Comment by whummer** [comment] 2017-07-28 17:52
Thanks for reporting @peterbe . How are you starting LocalStack? A good starting point may be to set the `DEBUG=1` environment variable, and then observe the log output in the terminal. Can you post some (server-side) error logs here?

Generally, instead of running in Docker, the best option for debugging is to clone the repo and start LocalStack locally via `make infra`. That gives you direct access to the source files, you can use print statements or an IDE/debugger to dig into the issue. Thanks

**Comment by peterbe** [comment] 2017-07-28 20:34
Oh! So I haven't figured out how to NOT run it in docker yet. (because ports).
However, when I start it, in docker, with `DEBUG=1`, and running it in the foreground I now get something "interesting":

```
localstack-s3_1  | Error on request:
localstack-s3_1  | Traceback (most recent call last):
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
localstack-s3_1  | execute(self.server.app)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
localstack-s3_1  | application_iter = app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 84, in __call__
localstack-s3_1  | return backend_app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack-s3_1  | return self.wsgi_app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack-s3_1  | response = self.make_response(self.handle_exception(e))
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack-s3_1  | reraise(exc_type, exc_value, tb)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack-s3_1  | response = self.full_dispatch_request()
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack-s3_1  | rv = self.handle_user_exception(e)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack-s3_1  | reraise(exc_type, exc_value, tb)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack-s3_1  | rv = self.dispatch_request()
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack-s3_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 131, in __call__
localstack-s3_1  | result = self.callback(request, request.url, {})
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 104, in ambiguous_response
localstack-s3_1  | return self.bucket_response(request, full_url, headers)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 108, in bucket_response
localstack-s3_1  | response = self._bucket_response(request, full_url, headers)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 141, in _bucket_response
localstack-s3_1  | body = body.decode('utf-8')
localstack-s3_1  | File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
localstack-s3_1  | return codecs.utf_8_decode(input, errors, True)
localstack-s3_1  | UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by peterbe** [comment] 2017-07-28 20:47
I'm trying to understand how this `make infra` works. It started but not sure how I'm supposed to access it
```
▶ make infra
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
```
There's nothing running on `localhost:8080` or `localhost:4572`.

**Comment by whummer** [comment] 2017-07-31 13:20
Unable to reproduce, your example works for me on the latest Docker image with `boto3` version `1.4.4`. Can you please provide a few more details. What version of the Docker image are you using?
```
docker images | grep localstack
```
Also, how do you construct `s3_client`, and what version of `boto3` and `botocore` is used in your example? Thanks

**Comment by peterbe** [comment] 2017-07-31 14:09
I use 

* boto3==1.4.4
* botocore==1.5.90
* atlassianlabs/localstack:0.6.1

That `s3_client` is created like this:
```
options = {'endpoint_url': 'http://localstack-s3:4572'}
session = boto3.session.Session()
s3_client = session.client('s3', **options)
```

**Comment by peterbe** [comment] 2017-07-31 14:34
So, for what it's worth, the error appears to go away after it's been accessed once. 
I get this output:
```
localstack-s3_1  | 127.0.0.1 - - [31/Jul/2017 14:30:32] "GET /testbucket?list-type=2&prefix=v1%2Fd3d11.pdb%2F88C16A895AE1F6099FC84075317298971%2Fd3d11.sym HTTP/1.1" 500 -
localstack-s3_1  | Error on request:
localstack-s3_1  | Traceback (most recent call last):
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
localstack-s3_1  | execute(self.server.app)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
localstack-s3_1  | application_iter = app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 84, in __call__
localstack-s3_1  | return backend_app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack-s3_1  | return self.wsgi_app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack-s3_1  | response = self.make_response(self.handle_exception(e))
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack-s3_1  | reraise(exc_type, exc_value, tb)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack-s3_1  | response = self.full_dispatch_request()
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack-s3_1  | rv = self.handle_user_exception(e)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack-s3_1  | reraise(exc_type, exc_value, tb)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack-s3_1  | rv = self.dispatch_request()
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack-s3_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 131, in __call__
localstack-s3_1  | result = self.callback(request, request.url, {})
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 104, in ambiguous_response
localstack-s3_1  | return self.bucket_response(request, full_url, headers)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 108, in bucket_response
localstack-s3_1  | response = self._bucket_response(request, full_url, headers)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 141, in _bucket_response
localstack-s3_1  | body = body.decode('utf-8')
localstack-s3_1  | File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
localstack-s3_1  | return codecs.utf_8_decode(input, errors, True)
localstack-s3_1  | UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```
But it works now with `curl`:

```
▶ curl -v "http://localhost:4572/testbucket?list-type=2&prefix=v1%2Fd3d11.pdb%2F88C16A895AE1F6099FC84075317298971%2Fd3d11.sym"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4572 (#0)
> GET /testbucket?list-type=2&prefix=v1%2Fd3d11.pdb%2F88C16A895AE1F6099FC84075317298971%2Fd3d11.sym HTTP/1.1
> Host: localhost:4572
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: BaseHTTP/0.3 Python/2.7.13
< Date: Mon, 31 Jul 2017 14:33:59 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 612
< Server: Werkzeug/0.12.2 Python/2.7.13
< Date: Mon, 31 Jul 2017 14:33:59 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< Access-Control-Allow-Headers: authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
<
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>testbucket</Name>
  <Prefix>v1/d3d11.pdb/88C16A895AE1F6099FC84075317298971/d3d11.sym</Prefix>
  <MaxKeys>1000</MaxKeys>
  <KeyCount>1</KeyCount>
  <IsTruncated>false</IsTruncated>
    <Contents>
      <Key>v1/d3d11.pdb/88C16A895AE1F6099FC84075317298971/d3d11.sym</Key>
      <LastModified>2017-07-31T14:33:46.222Z</LastModified>
      <ETag>&#34;38aa4775beb94bf1a4886d162025c73f&#34;</ETag>
      <Size>276089</Size>
      <StorageClass>STANDARD</StorageClass>
    </Contents>
* Connection #0 to host localhost left intact
  </ListBucketResult>%
```

**Comment by whummer** [comment] 2017-07-31 14:51
Please note that the Docker image is now published under a new name `localstack/localstack`, if you want to update to the most recent version (`0.7.3`). My suspicion is that this issue might still be present in that version, though.

It's weird, the error seems to indicate that there is some data in the payload of the GET request (error happens at `body = body.decode('utf-8')`). However, that should usually not be the case. We can add try/catch logic to avoid raising an error in this case, but the question is why it happens in the first place. Btw, what operating system are on?

**Comment by peterbe** [comment] 2017-07-31 17:21
Ok. I'll switch to `localstack/localstack`.
I've made *some* progress with going into bash in the container and putting print statements in various places. One thing I discovered was that `full_url` in `/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py` (around line 141) is: `http://localstack-s3:4572/testbucket?list-type=2&prefix=v1%2Fmshtml.pdb%2FDD4D332D611D4416A6336208D1ECEDAA1%2Fmshtml.sym` the `body` is a gzipped binary string. 

What my code does, is something like this:

1. Does the file `/foo.sym` exist in bucket 'mybucket'?
2. No, OK, first gzip its content upload as `/foo.sym` in `mybucket` with this gzipped payload. 

Now, in the next iteration it starts over:

1. Does the file `/foo.sym` exist in bucket 'mybucket'?
UnicodeDecodeError !!

The way it actually does "Does the file `/foo.sym` exist in bucket 'mybucket'?" is that it uses `ListObjectsV2` aka. `s3_client.list_objects_v2(Bucket='mybucket', Key='/foo.sym')`. 

What `moto` seems to do is that it tries to return the contents of the file, even though I didn't ask for it. Curious!

So, the curious thing is why GET requests, whose `request.body` is the payload of the file itself. I put this into `/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py`:

```python
# around line 141

        if isinstance(body, six.binary_type):
            if method == 'GET' and body:
                raise Exception('WHY DO YOU HAVE A {} bytes BODY??'.format(len(body)))
```
and got this:
```
localstack-s3_1  | 127.0.0.1 - - [31/Jul/2017 17:19:13] "GET /testbucket?list-type=2&prefix=v1%2Fd3d11.pdb%2F88C16A895AE1F6099FC84075317298971%2Fd3d11.sym HTTP/1.1" 500 -
localstack-s3_1  | Error on request:
localstack-s3_1  | Traceback (most recent call last):
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
localstack-s3_1  | execute(self.server.app)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
localstack-s3_1  | application_iter = app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 84, in __call__
localstack-s3_1  | return backend_app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack-s3_1  | return self.wsgi_app(environ, start_response)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack-s3_1  | response = self.make_response(self.handle_exception(e))
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack-s3_1  | reraise(exc_type, exc_value, tb)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack-s3_1  | response = self.full_dispatch_request()
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack-s3_1  | rv = self.handle_user_exception(e)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack-s3_1  | reraise(exc_type, exc_value, tb)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack-s3_1  | rv = self.dispatch_request()
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack-s3_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 133, in __call__
localstack-s3_1  | result = self.callback(request, request.url, {})
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 104, in ambiguous_response
localstack-s3_1  | return self.bucket_response(request, full_url, headers)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 108, in bucket_response
localstack-s3_1  | response = self._bucket_response(request, full_url, headers)
localstack-s3_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 142, in _bucket_response
localstack-s3_1  | raise Exception('WHY DO YOU HAVE A {} bytes BODY??'.format(len(body)))
localstack-s3_1  | Exception: WHY DO YOU HAVE A 109176 bytes BODY??
```

**Comment by peterbe** [comment] 2017-07-31 19:34
I don't know if it helps at all, but I wanted to try this with regular moto, as if it was a unit test. No problems there: https://gist.github.com/peterbe/1cf4878be1881a03a5f1246b6c990254

**Comment by whummer** [comment] 2017-08-02 10:38
Thanks for posting the gist. Interestingly, when I run that code on my machine (Mac OS, `moto==1.0.1`), it fails with a moto-internal exception.

After a bit of debugging, it turns out that the bucket key in `put_object` should not be prefixed with a slash (`/`), see for instance here: http://boto3.readthedocs.io/en/latest/guide/quickstart.html . In other words, if I change this:
```
        s3_client.put_object(
            Bucket='mybucket',
            Key='/foo.sym',
            Body=file_buffer,
            **extras,
        )
        found = s3_client.list_objects_v2(
            Bucket='mybucket',
            Prefix='/foo.sym'
        )
        assert found['Contents'][0]['Key'] == '/foo.sym'
```
to this:
```
        s3_client.put_object(
            Bucket='mybucket',
            Key='foo.sym',
            Body=file_buffer,
            **extras
        )
        found = s3_client.list_objects_v2(
            Bucket='mybucket',
            Prefix='foo.sym'
        )
        assert found['Contents'][0]['Key'] == 'foo.sym'
```
... then the code works. Can you please fix/update your test code and then give it a try with the latest version of LocalStack? Thanks

**Comment by peterbe** [comment] 2017-08-02 16:24
No luck :(
Instead of focusing on the test script I went back into my real code and made this change:
```diff
def _key_existing_size(client, bucket, key):
    """return the key's size if it exist, else None.

    See
    https://www.peterbe.com/plog/fastest-way-to-find-out-if-a-file-exists-in-s3
    for why this is the better approach.
    """
+    assert not key.startswith('/'), key
     response = client.list_objects_v2(
         Bucket=bucket,
         Prefix=key,
    )
    for obj in response.get('Contents', []):
        if obj['Key'] == key:
            return obj['Size']
```

Basically, making sure I'm not using a / prefix when querying ListObjectsV2. 
It did not happen. The key name never starts with a `/`. 
However, I still get 500 Internal Server Errors.

**Comment by peterbe** [comment] 2017-08-02 16:25
Besides, the code works using AWS S3. I never get these errors when I use a real S3 bucket over the internet.

**Comment by whummer** [comment] 2019-08-25 17:29
Closing this issue as outdated - should be fixed in the meantime.

**Closed by whummer** 2019-08-25 17:29 UTC
Labels: bug, upstream-issue
