### ISSUE TITLE
Setting KINESIS_ERROR_PROBABILITY causes start to fail

### ISSUE THREAD

**Issue by LeeDavidMalcolm** [localstack/localstack#619] opened 2018-02-19 12:55 UTC
If starting localstack with env variable KINESIS_ERROR_PROBABILITY set to 1.0 (or any other value greater than 0.0) causes the start up to fail: 
```
2018-02-19T12:52:52:ERROR:localstack.services.generic_proxy: Error forwarding request: 'Records' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 24, in forward_request
localstack_1  |     return kinesis_error_response(data)
localstack_1  |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 71, in kinesis_error_response
localstack_1  |     for record in data['Records']:
localstack_1  | KeyError: 'Records'
```

Have pulled down the latest master repo, updated the docker-compose.yml as well as testing the latest docker image. 

Looking at the code on the lines above it looks like start up is invoking the listener which applies the probability rule which causes it to fail

**Comment by aldegoeij** [comment] 2018-02-27 07:01
Getting the same with KINESIS_ERROR_PROBABILITY set to 0.1

```
tmp_localstack     |
tmp_localstack     | 2018-02-27T06:53:35:ERROR:localstack.services.generic_proxy: Error forwarding request: 'Records' Traceback (most recent call last):
tmp_localstack     |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
tmp_localstack     |     path=path, data=data, headers=forward_headers)
tmp_localstack     |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 24, in forward_request
tmp_localstack     |     return kinesis_error_response(data)
tmp_localstack     |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 71, in kinesis_error_response
tmp_localstack     |     for record in data['Records']:
tmp_localstack     | KeyError: 'Records'
```

**Comment by LeeDavidMalcolm** [comment] 2018-05-11 13:52
Is there any update on this? This would be a great feature to have

**Comment by whummer** [comment] 2018-05-20 19:28
@LeeDavidMalcolm @aldegoeij This should be fixed in #772 - can you please give it a try with the latest version on `master` (or the `latest` Docker image).

**Comment by gbiv** [comment] 2019-03-01 18:46
This is still failing as far as I can tell.

**Comment by whummer** [comment] 2019-10-10 21:18
Did another test, unable to reproduce this issue. Closing this issue for now, as it seems to be fixed. Can you please provide a small reproducible test case @gbiv , then we can re-open this issue and investigate. Thanks!

**Closed by whummer** 2019-10-10 21:18 UTC
Labels: bug, configuration, priority-high
