### ISSUE TITLE
SQS startup throwing errors during kickstart

### ISSUE THREAD

**Issue by diegofduarte** [localstack/localstack#595] opened 2018-02-04 02:43 UTC
Hello there,

I've just installed localstack, and tried to run it for the first time (and others).

However, everytime I try to run it, I get stuck in the following error:

``` 
(venv3) diego@Shelly:~$ localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock SNS (http port 4575)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Lambda service (http port 4574)...
Starting mock ES service (http port 4578)...
Starting mock CloudWatch (http port 4582)...
Starting mock SSM (http port 4583)...
Starting mock Redshift (http port 4577)...
Starting mock Route53 (http port 4580)...
Starting mock DynamoDB (http port 4569)...
Starting mock API Gateway (http port 4567)...
Starting mock S3 (http port 4572)...
Starting mock SES (http port 4579)...
Starting mock Firehose service (http port 4573)...
Starting local Elasticsearch (http port 4571)...
Starting mock Kinesis (http port 4568)...
Starting mock SQS (http port 4576)...
2018-02-04T00:40:14:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6ecef71d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd6ecef71d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6ecef71d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd6ecef71d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```  
Specs here:

NodeJS 8.9.4 installed under NPM
Python 3.5.2 + virtualenv
localstack 0.8.4
Ubuntu 16.04 LTS

**Comment by frosas** [comment] 2018-03-01 22:23
Do you have an SQS consumer trying to connect to localstack as it starts? And do the errors stop after a while? In my case, those `Connection refused` are caused by the requests made by an SQS consumer while localstack is not fully started. They don't do any harm but are very noisy and confusing.

**Comment by diegofduarte** [comment] 2018-03-11 02:10
@frosas unfortunatelly I don't... From AWS I just got a CLI installed here and the Troposphere libraries.

**Comment by whummer** [comment] 2018-05-20 16:49
Are you still experiencing this issue @diegofduarte ? Looks like DynamoDB didn't come up properly. Can you try starting LocalStack with debug output enabled:
```
localstack -d start
```
Also, can you post the output of these commands:
```
echo $(python -c 'import os, localstack; print(os.path.dirname(localstack.__file__))')
ls -la $(python -c 'import os, localstack; print(os.path.dirname(localstack.__file__))')/infra/dynamodb
```

**Comment by diegofduarte** [comment] 2018-05-20 23:16
localstack -d: https://gist.github.com/diegofduarte/542da9e10becbc0d5fdfe3491a93183b (looks like my node env is not being correctly recognized as far as I see here. Idk if this problem is related tho)

$ python -c 'import os, localstack; print(os.path.dirname(localstack.__file__))'
/home/diego/workspace/venv3/lib/python3.5/site-packages/localstack

$ ls -la $(python -c 'import os, localstack; print(os.path.dirname(localstack.__file__))')/infra/dynamodb
total 16
drwxrwxr-x 2 diego diego 4096 May 20 20:11 .
drwxrwxr-x 5 diego diego 4096 Feb  4 00:35 ..
-rw-rw-r-- 1 diego diego  374 May 20 20:11 DynamoDBLocal.jar
-rw-rw-r-- 1 diego diego  344 May 20 20:11 log4j2.xml

**Comment by whummer** [comment] 2018-05-21 01:31
ok, that doesn't look right:
```
-rw-rw-r-- 1 diego diego  374 May 20 20:11 DynamoDBLocal.jar
```
Looks like the jar file hasn't been downloaded properly. Can you try deleting it and then re-running LocalStack:
```
rm -rf /home/diego/workspace/venv3/lib/python3.5/site-packages/localstack/infra/dynamodb
rm -rf /tmp/localstack.ddb.zip
rm -rf $TMPDIR/localstack.ddb.zip
localstack -d start
```

**Comment by diegofduarte** [comment] 2018-05-22 03:39
Hey @whummer, thanks for the heads up. Your tip fixed the DynamoDB problem. However, now Iḿ seeing another one:

```
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock CloudFormation (http port 4581)...
2018-05-22T00:35:02:WARNING:infra.py: Service "elasticsearch" not yet available, retrying...
2018-05-22T00:35:05:WARNING:infra.py: Service "elasticsearch" not yet available, retrying...
2018-05-22T00:35:08:WARNING:infra.py: Service "elasticsearch" not yet available, retrying...
2018-05-22T00:35:12:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f098c437780>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f098c437780>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f098c437780>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/diego/workspace/venv3/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f098c437780>: Failed to establish a new connection: [Errno 111] Connection refused',))
``` 

Ok, I'm close to reinstall the whole localstack, I think that would be better than fix this in a cherry-pick manner.

**Comment by whummer** [comment] 2019-09-13 16:10
Shouldn't happen anymore with the new installation method, using Docker. Closing

**Closed by whummer** 2019-09-13 16:10 UTC
Labels: bug, installation, needs-triaging
