### ISSUE TITLE
Firehose put-record returns 500 Internal Server Error with the latest localstack

### ISSUE THREAD

**Issue by harikamankala** [localstack/localstack#5129] opened 2021-12-15 17:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

500 Internal Server Error is returned when trying to put record into firehose

An error occurred (500) when calling the PutRecord operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

### Expected Behavior

the record should be created successfully
{
    "RecordId": <with some id>"
}

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   version: '3.8'

services:
  awslocal:
    image: localstack/localstack
    volumes:
      - awslocal-vol:/tmp/localstack
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:4566/health" ]
      interval: 10s
      retries: 6
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=${SERVICES:-s3,firehose,dynamodb,s3api,kinesis}
      - DEBUG=${DEBUG:- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=${TMPDIR}
      - USE_SINGLE_REGION=1
      - DEFAULT_REGION=us-west-1
      - EDGE_PORT=4566
    networks:
      - localst

volumes:
  awslocal-vol:

networks:
  localst:
    driver: bridge

docker-compose up to start the container

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

step 1 : awslocal s3api create-bucket --bucket awsclient-bucket  --> succesful
step 2 : awslocal firehose create-delivery-stream --cli-input-json file:///project/firehose.json  --> succesful
step 3 : awslocal kinesis create-stream --stream-name awsclient --shard-count 1  --> succesful
step 4 : awslocal firehose put-record --delivery-stream-name awsclient_poc_firehose --record '{"Data":"SGVsbG8gd29ybGQ="}'  -->  returns 500 internal server error

### Environment

```markdown
- OS: Ubuntu 18.04.4
- LocalStack:latest
```

### Anything else?

awslocal_1  | 2021-12-15T15:43:23.699:ERROR:firehose_api: Exception on / [POST]
awslocal_1  | Traceback (most recent call last):
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
awslocal_1  |     response = self.full_dispatch_request()
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
awslocal_1  |     rv = self.handle_user_exception(e)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
awslocal_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
awslocal_1  |     rv = self.dispatch_request()
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
awslocal_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 431, in post_request
awslocal_1  |     response = put_record(stream_name, record)
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 151, in put_record
awslocal_1  |     return put_records(stream_name, [record])
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 215, in put_records
awslocal_1  |     raise e
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 212, in put_records
awslocal_1  |     s3.Object(bucket, obj_path).put(Body=batched_data)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
awslocal_1  |     response = action(self, *args, **kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
awslocal_1  |     response = getattr(parent.meta.client, operation_name)(*args, **params)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
awslocal_1  |     return self._make_api_call(operation_name, kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
awslocal_1  |     raise error_class(parsed_response, operation_name)
awslocal_1  | botocore.exceptions.ClientError: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway
awslocal_1  | 2021-12-15T15:43:36.528:ERROR:localstack.services.firehose.firehose_api: Unable to put record to stream: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway Traceback (most recent call last):
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 212, in put_records
awslocal_1  |     s3.Object(bucket, obj_path).put(Body=batched_data)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
awslocal_1  |     response = action(self, *args, **kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
awslocal_1  |     response = getattr(parent.meta.client, operation_name)(*args, **params)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
awslocal_1  |     return self._make_api_call(operation_name, kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
awslocal_1  |     raise error_class(parsed_response, operation_name)
awslocal_1  | botocore.exceptions.ClientError: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway
awslocal_1  | 
awslocal_1  | 2021-12-15T15:43:36.529:ERROR:firehose_api: Exception on / [POST]
awslocal_1  | Traceback (most recent call last):
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
awslocal_1  |     response = self.full_dispatch_request()
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
awslocal_1  |     rv = self.handle_user_exception(e)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
awslocal_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
awslocal_1  |     rv = self.dispatch_request()
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
awslocal_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 431, in post_request
awslocal_1  |     response = put_record(stream_name, record)
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 151, in put_record
awslocal_1  |     return put_records(stream_name, [record])
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 215, in put_records
awslocal_1  |     raise e
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 212, in put_records
awslocal_1  |     s3.Object(bucket, obj_path).put(Body=batched_data)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
awslocal_1  |     response = action(self, *args, **kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
awslocal_1  |     response = getattr(parent.meta.client, operation_name)(*args, **params)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
awslocal_1  |     return self._make_api_call(operation_name, kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
awslocal_1  |     raise error_class(parsed_response, operation_name)
awslocal_1  | botocore.exceptions.ClientError: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway
awslocal_1  | 2021-12-15T15:43:43.184:ERROR:localstack.services.firehose.firehose_api: Unable to put record to stream: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway Traceback (most recent call last):
awslocal_1  |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 212, in put_records
awslocal_1  |     s3.Object(bucket, obj_path).put(Body=batched_data)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
awslocal_1  |     response = action(self, *args, **kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
awslocal_1  |     response = getattr(parent.meta.client, operation_name)(*args, **params)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
awslocal_1  |     return self._make_api_call(operation_name, kwargs)
awslocal_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
awslocal_1  |     raise error_class(parsed_response, operation_name)
awslocal_1  | botocore.exceptions.ClientError: An error occurred (502) when calling the PutObject operation (reached max retries: 4): Bad Gateway

**Comment by KrishnanRanjithkumar** [comment] 2021-12-27 21:44
Thanks for reporting the issue @harikamankala. I couldn't reproduce the issue with latest Localstack image. It seems to me the issue might be in `S3DestinationConfiguration` when we create the delivery stream . Could you please either share your `firehose.json` or the output the `awslocal firehose describe-delivery-stream --delivery-stream-name awsclient_poc_firehose` to investigate further.

**Comment by harikamankala** [comment] 2022-01-03 08:47
Thanks for looking into the issue. Here is my firehose.json

`{
    "DeliveryStreamName": "awsclient_poc_firehose",
    "S3DestinationConfiguration": {
        "RoleARN": "awsclient_role",
        "BucketARN": "awsclient-bucket",
        "Prefix": "",
        "BufferingHints": {
            "SizeInMBs": 5,
            "IntervalInSeconds": 300
        },
        "CompressionFormat": "GZIP",
        "EncryptionConfiguration": {
            "NoEncryptionConfig": "NoEncryption"
        },
        "CloudWatchLoggingOptions": {
            "Enabled": false,
            "LogGroupName": "",
            "LogStreamName": ""
        }
    }
}`

**Comment by KrishnanRanjithkumar** [comment] 2022-01-04 22:14
@harikamankala Thanks for sharing the firehose.json  I'm still not able to reproduce this issue with the `docker-compose.yml` and awslocal commands you've shared. Could you please pull latest the docker image and give it another try? In case the problem still persists, please set DEBUG=1 in your docker-compose.yml and share the logs which might help us to understand the issue better. Thanks!!!

**Comment by harikamankala** [comment] 2022-01-07 09:48
Thanks. Now it works with the latest docker image.

**Comment by thrau** [comment] 2022-05-18 17:03
hey @harikamankala, it's not quite clear what you mean. if closing this for now. please open up a new issue if you have a specific question or problem. thanks!

**Closed** 2022-05-18 17:02 UTC
Labels: bug, needs-triaging, awaiting-response, aws:firehose
