### ISSUE TITLE
Question: Advice on integrating aws-mock into localstack?

### ISSUE THREAD

**Issue by nottoseethesun** [localstack/localstack#51] opened 2017-04-01 22:59 UTC
Background: https://github.com/treelogic-swe/aws-mock has good support for mocking EC2, which I don't see is available in localstack. 

How would one go about integrating the EC2 mocking support in aws-mock with localstack?  Where is the integration point for a new AWS mock service, and what is its API?

**Comment by russellc92** [comment] 2018-12-21 12:11
hey, did you or anyone have any luck with this?

**Comment by whummer** [comment] 2019-03-02 19:06
Closing this issue as duplicate of #691 - let's continue the discussion here:
https://github.com/localstack/localstack/issues/691

**Closed by whummer** 2019-03-02 19:06 UTC
Labels: api-request, documentation, priority-medium

**Comment by nottoseethesun** [comment] 2019-03-03 05:39
Cool, thanks.
