### ISSUE TITLE
Unknown port mapping for service: s3 when TestUtils.getClientS3()

### ISSUE THREAD

**Issue by gaetan224** [localstack/localstack#4117] opened 2021-06-08 15:22 UTC
trying to run localstack-utils and first line fails
`AmazonS3 client = TestUtils.getClientS3();`

**Comment by jasonab** [comment] 2021-06-10 03:57
Dupe of #4115

**Comment by cabral-ricardo** [comment] 2021-06-14 20:44
same problem,
java.lang.IllegalArgumentException: Unknown port mapping for service: s3
at cloud.localstack.Localstack.getServicePort(Localstack.java:232)
at cloud.localstack.Localstack.endpointForService(Localstack.java:223)
at cloud.localstack.Localstack.getEndpointS3(Localstack.java:122)
at cloud.localstack.awssdkv1.TestUtils.getEndpointConfigurationS3(TestUtils.java:232)
at cloud.localstack.awssdkv1.TestUtils.getClientS3(TestUtils.java:133)

**Comment by cabral-ricardo** [comment] 2021-06-15 18:29
great. I changed to findify.s3mock while I wait this deploy
https://stackoverflow.com/questions/6615988/how-to-mock-amazon-s3-in-an-integration-test

**Comment by pinzon** [comment] 2021-07-05 17:15
The PR addressing the original issue has been merged, so I'm gonna close this issue.

**Closed by pinzon** 2021-07-05 17:15 UTC
