### ISSUE TITLE
bug: Not compatible with latest awscli version

### ISSUE THREAD

**Issue by lbenedetto** [localstack/localstack#9620] opened 2023-11-13 22:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is the behavior with `aws-cli/2.13.34`
```
$ aws sqs list-queues --region=eu-west-1 --endpoint-url=http://localhost:14005

An error occurred (500) when calling the ListQueues operation (reached max retries: 2): <?xml version='1.0' encoding='utf-8'?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception while calling sqs with unknown operation: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).</Message></Error><RequestId>b42307a4-ba7b-435c-b098-a229d035425d</RequestId></ErrorResponse>
```

And the corresponding logs:

```
2023-11-13T22:53:47.813 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : POST localhost:14005/
2023-11-13T22:53:47.814 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 367, in parse
    raise ProtocolParserError(
localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
2023-11-13T22:53:47.814 DEBUG --- [   asgi_gw_0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-amz-json-1.0) as preferred response Content-Type.
2023-11-13T22:53:47.815  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500; Request(b'{}', headers={'Host': 'localhost:14005', 'Accept-Encoding': 'identity', 'X-Amz-Target': 'AmazonSQS.ListQueues', 'Content-Type': 'application/x-amz-json-1.0', 'User-Agent': 'aws-cli/2.13.34 Python/3.11.6 Linux/5.15.0-88-generic source/x86_64.linuxmint.21 prompt/off command/sqs.list-queues', 'X-Amz-Date': '20231113T225347Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=asdf/20231113/eu-west-1/sqs/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=d35afcea887731fa6703f0c1b133531347b567a1a49da51823ba4c1131a38aac', 'Content-Length': '2', 'x-localstack-tgt-api': 'sqs', 'x-moto-account-id': '000000000000'}); Response(b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<ErrorResponse xmlns="[http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception](http://queue.amazonaws.com/doc/2012-11-05/%22%3E%3CError%3E%3CCode%3EInternalError%3C/Code%3E%3CMessage%3Eexception) while calling sqs with unknown operation: Traceback (most recent call last):\n  File &quot;/opt/code/localstack/localstack/aws/chain.py&quot;, line 90, in handle\n    handler(self, self.context, response)\n  File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 64, in __call__\n    return self.parse_and_enrich(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 77, in parse_and_enrich\n    operation, instance = parser.parse(context.request)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 173, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 367, in parse\n    raise ProtocolParserError(\nlocalstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).\n</Message></Error><RequestId>dd470f94-d881-4b40-b96d-7fc8825436ff</RequestId></ErrorResponse>', headers={'Content-Type': 'text/xml', 'Content-Length': '1290', 'Connection': 'close', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
2023-11-13T22:53:48.216 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : POST localhost:14005/
2023-11-13T22:53:48.217 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 367, in parse
    raise ProtocolParserError(
localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
2023-11-13T22:53:48.218 DEBUG --- [   asgi_gw_0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-amz-json-1.0) as preferred response Content-Type.
2023-11-13T22:53:48.219  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500; Request(b'{}', headers={'Host': 'localhost:14005', 'Accept-Encoding': 'identity', 'X-Amz-Target': 'AmazonSQS.ListQueues', 'Content-Type': 'application/x-amz-json-1.0', 'User-Agent': 'aws-cli/2.13.34 Python/3.11.6 Linux/5.15.0-88-generic source/x86_64.linuxmint.21 prompt/off command/sqs.list-queues', 'X-Amz-Date': '20231113T225348Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=asdf/20231113/eu-west-1/sqs/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=b7fbb48c254fcd8fc4e1031212ea9905fa82c3adffeb2e7d12cc599b5f7820dc', 'Content-Length': '2', 'x-localstack-tgt-api': 'sqs', 'x-moto-account-id': '000000000000'}); Response(b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<ErrorResponse xmlns="[http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception](http://queue.amazonaws.com/doc/2012-11-05/%22%3E%3CError%3E%3CCode%3EInternalError%3C/Code%3E%3CMessage%3Eexception) while calling sqs with unknown operation: Traceback (most recent call last):\n  File &quot;/opt/code/localstack/localstack/aws/chain.py&quot;, line 90, in handle\n    handler(self, self.context, response)\n  File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 64, in __call__\n    return self.parse_and_enrich(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 77, in parse_and_enrich\n    operation, instance = parser.parse(context.request)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 173, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 367, in parse\n    raise ProtocolParserError(\nlocalstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).\n</Message></Error><RequestId>99306c38-a1b9-48f9-816d-69b8fb40cde7</RequestId></ErrorResponse>', headers={'Content-Type': 'text/xml', 'Content-Length': '1290', 'Connection': 'close', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
2023-11-13T22:53:48.593 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET localhost:4566/_localstack/health
2023-11-13T22:53:48.933 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : POST localhost:14005/
2023-11-13T22:53:48.933 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 367, in parse
    raise ProtocolParserError(
localstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).
2023-11-13T22:53:48.934 DEBUG --- [   asgi_gw_0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-amz-json-1.0) as preferred response Content-Type.
2023-11-13T22:53:48.935  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500; Request(b'{}', headers={'Host': 'localhost:14005', 'Accept-Encoding': 'identity', 'X-Amz-Target': 'AmazonSQS.ListQueues', 'Content-Type': 'application/x-amz-json-1.0', 'User-Agent': 'aws-cli/2.13.34 Python/3.11.6 Linux/5.15.0-88-generic source/x86_64.linuxmint.21 prompt/off command/sqs.list-queues', 'X-Amz-Date': '20231113T225348Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=asdf/20231113/eu-west-1/sqs/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=b7fbb48c254fcd8fc4e1031212ea9905fa82c3adffeb2e7d12cc599b5f7820dc', 'Content-Length': '2', 'x-localstack-tgt-api': 'sqs', 'x-moto-account-id': '000000000000'}); Response(b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<ErrorResponse xmlns="[http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>InternalError</Code><Message>exception](http://queue.amazonaws.com/doc/2012-11-05/%22%3E%3CError%3E%3CCode%3EInternalError%3C/Code%3E%3CMessage%3Eexception) while calling sqs with unknown operation: Traceback (most recent call last):\n  File &quot;/opt/code/localstack/localstack/aws/chain.py&quot;, line 90, in handle\n    handler(self, self.context, response)\n  File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 64, in __call__\n    return self.parse_and_enrich(context)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/handlers/service.py&quot;, line 77, in parse_and_enrich\n    operation, instance = parser.parse(context.request)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 173, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File &quot;/opt/code/localstack/localstack/aws/protocol/parser.py&quot;, line 367, in parse\n    raise ProtocolParserError(\nlocalstack.aws.protocol.parser.ProtocolParserError: Operation detection failed. Missing Action in request for query-protocol service ServiceModel(sqs).\n</Message></Error><RequestId>fd503402-da3f-4c3b-be3e-722df5ceb70d</RequestId></ErrorResponse>', headers={'Content-Type': 'text/xml', 'Content-Length': '1290', 'Connection': 'close', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
```

### Expected Behavior

This is the behavior with `aws-cli/2.13.26`
```
$ aws sqs list-queues --region=eu-west-1 --endpoint-url=http://localhost:14005
{
    "QueueUrls": [ ... ]
}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
  localstack:
    image: localstack/localstack:2.3.2
    environment:
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
      - LS_LOG=trace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "14005:4566"
```

### Environment

```markdown
- LocalStack: 2.3.2
```

### Anything else?

Similar issue: https://github.com/localstack/localstack/issues/7752

**Comment by bentsku** [comment] 2023-11-13 23:11
Hello, this is a duplicate of #8267, which has been solved in the `latest` version. You can read more about the problem in the mentioned issue. We're releasing a major version, 3.0, on Thursday, 16th of November. Thanks!

**Closed by bentsku** 2023-11-13 23:11 UTC
Labels: type: bug, status: triage needed

**Comment by lbenedetto** [comment] 2023-11-13 23:46
Ok, and looks like this would also explain this error
> com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonSQS; Status Code: 500; Error Code: null; Request ID: null; Proxy: null)

when using `com.amazonaws:aws-java-sdk-sqs:1.12.584` or higher

**Comment by bentsku** [comment] 2023-11-13 23:52
Hi @lbenedetto, yes, there is the list of the AWS SDK versions which will fail against LocalStack before `localstack/localstack:latest` and the next major release:
https://github.com/localstack/localstack/issues/8267#issuecomment-1806421471

This is because the new SDK versions will have a whole new protocol to communicate with the SQS services, which older LocalStack versions are not able to parse as they came out before these new SDK releases.
See this comment: https://github.com/localstack/localstack/issues/8267#issuecomment-1808638756
