### ISSUE TITLE
Cannot start lambda service

### ISSUE THREAD

**Issue by rsosnin** [localstack/localstack#1309] opened 2019-05-12 09:24 UTC
After upgrading localstack to `latest` version, Lambda service stopped working.

I run localstack in a container. Getting following error log:
`localstack               | ERROR: 'docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"': exit code 1; output: b''`

This is the full log:
```
Attaching to localstack
localstack               | Waiting for all LocalStack services to be ready
localstack               | 2019-05-12 09:23:02,045 INFO supervisord started with pid 11
localstack               | 2019-05-12 09:23:03,051 INFO spawned: 'dashboard' with pid 18
localstack               | 2019-05-12 09:23:03,055 INFO spawned: 'infra' with pid 19
localstack               | 2019-05-12 09:23:03,063 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack               | (. .venv/bin/activate; bin/localstack web)
localstack               | (. .venv/bin/activate; exec bin/localstack start)
localstack               | 2019-05-12 09:23:04,069 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack               |  * Serving Flask app "app" (lazy loading)
localstack               |  * Environment: production
localstack               |    WARNING: Do not use the development server in a production environment.
localstack               |    Use a production WSGI server instead.
localstack               |  * Debug mode: on
localstack               | 2019-05-12T09:23:05:INFO:werkzeug:  * Running on http://0.0.0.0:8079/ (Press CTRL+C to quit)
localstack               | 2019-05-12T09:23:05:INFO:werkzeug:  * Restarting with stat
localstack               | Starting local dev environment. CTRL-C to quit.
localstack               | Starting mock S3 (http port 4572)...
localstack               | Starting mock SNS (http port 4575)...
localstack               | Starting mock SQS (http port 4576)...
localstack               | Starting mock DynamoDB (http port 4569)...
localstack               | Starting mock Lambda service (http port 4574)...
localstack               | Starting mock CloudWatch Logs (http port 4586)...
localstack               | ERROR: 'docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"': exit code 1; output: b''
localstack               | Waiting for all LocalStack services to be ready
localstack               | 2019-05-12T09:23:08:WARNING:werkzeug:  * Debugger is active!
localstack               | 2019-05-12T09:23:08:INFO:werkzeug:  * Debugger PIN: 314-544-496
localstack               | 2019-05-12T09:23:11:INFO:localstack.utils.persistence: Restored 3 API calls from persistent file: /tmp/localstack/data/s3_api_calls.json
localstack               | Ready.
```

With version from 5 weeks ago, I don't get this error & everything works as expected

**Comment by rsosnin** [comment] 2019-05-12 09:37
Actually I get this error with `0.9.2` & `latest` , but `0.9.1` is stable.

**Comment by whummer** [comment] 2019-05-12 14:28
Thanks for reporting @rsosnin . Can you please provide some details about your environment, and post the full command you're using to start the stack. Also, can you try starting again with the `latest` version of the image. Thanks

**Comment by whummer** [comment] 2019-05-13 16:17
Possible duplicate of #1306 - should be fixed in the meantime. Please reopen if the problem persists.

**Closed by whummer** 2019-05-13 16:17 UTC

**Comment by rsosnin** [comment] 2019-05-29 18:01
@whummer The issue was resolved in the latest localstack image. sorry for the delay and thanks!
