### ISSUE TITLE
bug: calls from nodejs 14 lambda to dynamo with localstack/latest hang and never return

### ISSUE THREAD

**Issue by brucekaufman** [localstack/localstack#4946] opened 2021-11-18 02:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the integration test suite of a private repo that is passing with localstack:0.12.16, I found that nearly all the tests were failing when I tried to update to latest.  When debugging, I found that calls from the nodejs14 lambda container to dynamodb local are hanging and never returning.  Before running the testing, I can access and see that the dynamodb service is in the expected states EG:
```
awslocal dynamodb list-tables
{
    "TableNames": [
        "PhoneLookupCache",
        "communication-local",
        "legacy-number-pool"
    ]
}
```

These tables are added by our deployment automation.  After the test suite fails, the list-table command (and any other dynamodb command i try) hang and do not respond.  I enabled debug logging in the localstack container and this is the last output i see:

```
2021-11-18T02:14:04:DEBUG:localstack.services.edge: IN(dynamodb): "POST /" - headers: {'Remote-Addr': '172.17.0.3', 'User-Agent': 'aws-sdk-nodejs/2.996.0 linux/v14.16.0 exec-env/AWS_Lambda_nodejs12.x promise', 'Content-Type': 'application/x-amz-json-1.0', 'X-Amz-Target': 'DynamoDB_20120810.Query', 'X-Amz-Content-Sha256': 'fd8a3479703f90eca1f66b4eff7bcea60f2d75b94ea26e24fba99f0fad52a082', 'Content-Length': '134', 'Host': '172.17.0.2:4566', 'X-Amz-Date': '20211118T021404Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20211118/us-east-1/dynamodb/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=2367409fc101a065e10b4218a03cb9cb4d1977c9cacaa1f01ceff8fbf59410ac', 'Connection': 'keep-alive', 'X-Forwarded-For': '172.17.0.3, 172.17.0.2:4566', 'x-localstack-edge': 'http://172.17.0.2:4566'} - data: b'{"TableName":"PhoneLookupCache","KeyConditionExpression":"phoneNumber = :ph","ExpressionAttributeValues":{":ph":{"S":"+16086587152"}}}'
```

Not sure what additional information would be useful here but this is a private repo so i cannot share the exact setup.  There is clearly a difference between 0.12.16 and latest.

### Expected Behavior

Calls to dynamodb should not hang.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

This is contained in a private repo but this is a pretty basic setup, with a nodejs14 lambda function running in docker connecting to dynamodb.

### Environment

```markdown
- OS: OS X Big Sur
- LocalStack: latest
```

**Comment by brucekaufman** [comment] 2021-11-18 03:08
digging into the release notes, i found that setting `EAGER_SERVICE_LOADING=1`.  Eliminates this behavior and all works as before.  I think this indicates some bug with the lazy service loading, specifically with dynamodb?

**Comment by whummer** [comment] 2021-11-21 20:36
Hi @brucekaufman , thanks for reporting this issue. Can you please help us create a reproducible sample that exposes this issue.

Looks like running the bash script below works against `latest` - can you verify that it also works for you?
```
#!/bin/bash

echo 'def handler(*args, **kwargs):' > /tmp/testlambda.py
echo '  import boto3; client = boto3.client("dynamodb")' >> /tmp/testlambda.py
echo '  print(client.list_tables())' >> /tmp/testlambda.py
(cd /tmp; zip testlambda.zip testlambda.py)
awslocal lambda create-function --function-name func1 --runtime python3.6 --role r1 --handler testlambda.handler --timeout 30 --zip-file fileb:///tmp/testlambda.zip

awslocal lambda invoke --function-name func1 /tmp/foo.tmp
```
Thanks!

**Comment by brucekaufman** [comment] 2022-02-15 18:50
hi @whummer and apologies for delaying so long on a response here.  I am again engaged around trying to update our localstack version for our micro services and have run into a number of problems.  With localstack version 0.13.0 I am still able to reproduce this behavior in our test suite.  The suite has more than 50 tests and so I haven't had time to start digging in and finding a minimal reproducible combination yet.  With newer versions of localstack I am running into this issue - once the below has beeen resolved i'll see if i can still reproduce with a more recent  version.
https://github.com/localstack/localstack/issues/5465

**Comment by morlombakop** [comment] 2022-03-27 17:56
> digging into the release notes, i found that setting `EAGER_SERVICE_LOADING=1`. Eliminates this behavior and all works as before. I think this indicates some bug with the lazy service loading, specifically with dynamodb?

@brucekaufman how and where do you set this  `EAGER_SERVICE_LOADING=1`, I'm having the same issue. I appreciate you help.

**Comment by morlombakop** [comment] 2022-03-28 10:48
@whummer I'm able to reproduce this from docker image `localstack/localstack:0.12.18` onward. 
To get around this I pinned my image version to `localstack/localstack:0.12.17`. I hope it helps

**Comment by giograno** [comment] 2023-07-03 09:17
Thanks again for reporting the problem. I am going to close the issue since the LocalStack version used is quite old and a lot of improvements have been made since. 
Of course, if you are still experiencing the issue with the current version, feel free to open a new ticket. 
Thank you very much.

**Closed by giograno** 2023-07-03 09:17 UTC
Labels: type: bug, status: triage needed, area: infrastructure, aws:dynamodb
