### ISSUE TITLE
S3 has support for virtual-hosted style

### ISSUE THREAD

**Issue by davesnyckers** [localstack/localstack#1512] opened 2019-08-29 05:57 UTC
As Amazon will be deprecating the support for path-style model (https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/), I was wondering if Localstack will be support the virtual-hosted style in the near future?

I tried a number of ways to get virtual-hosted style working (using Localstack via docker), but can't get things working at the moment (trying to connect to the S3 from Java).

Only solution that is currently working is falling back to the path-style model using the solution in your troubleshooting section.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-114) by [Unito](https://www.unito.io/learn-more)

**Comment by cscetbon** [comment] 2020-04-16 03:16
Any idea when it'll be implemented ? September is soon and we need to use the new way asap for our applications to be ready.

**Comment by jhrf** [comment] 2020-06-09 16:09
I'm also interested in this feature

**Comment by rayjlinden** [comment] 2020-11-17 09:27
They pushed out the September date.  However, I assume this will still be a problem at some point?

**Comment by mewtlu** [comment] 2020-11-17 09:56
Looks like we've got at least a year on it if I'm understanding correctly, so at least we can ignore it for a while longer!

**Comment by mojtabacazi** [comment] 2020-11-17 21:53
As far as I undrestand new users (like us) can't use the old style anymore, so yes this is a problem.

**Comment by rayjlinden** [comment] 2020-11-18 06:05
What matters more is them removing the feature from the SDK rather than AWS
actually making this move.  If it is removed from the SDK we would not be
able to use localstack (unless localstack figures out something very
cool...)

I would suspect the SDKs will support it long after there are no longer any
S3 buckets on AWS that support it.  So you may have a few years to solve
this problem.  But I imagine at some point they will rip out that support.

**Comment by hertzsprung** [comment] 2020-12-14 16:13
See also a partial workaround in #43 which involves configuring an additional subdomain per bucket.

**Comment by whummer** [comment] 2021-03-04 22:15
Thanks all for chiming in - marking this as a duplicate of #2631 , let's continue the discussion there. Thanks

**Closed by whummer** 2021-03-04 22:15 UTC
Labels: configuration, diverges-from-aws, enhancement
