### ISSUE TITLE
bug: malformed cloudformation template is deployable

### ISSUE THREAD

**Issue by zaro0508** [localstack/localstack#10674] opened 2024-04-16 14:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I attempt to deploy a malformed cloudformation template in real AWS i get an error, however when I deploy it in localstack it deploys the template without any errors.   It seems like localstack does not work the same as AWS in this case.

### Expected Behavior

I expect localstack cloudformation to behave the same as AWS.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

     % localstack start -d

### Deploy to AWS, result is an error...
```
➜ AWS_PROFILE=sceptredev-admin AWS_DEFAULT_REGION=us-east-1 aws cloudformation deploy --stack-name foo1 --template-file "./temp/test.yaml"

An error occurred (ValidationError) when calling the CreateChangeSet operation: Invalid template property or properties [Malformed]
```

### Deploy to localstack, result is no error..

```
➜ AWS_PROFILE=localstack AWS_ENDPOINT_URL=http://localhost:4566/ AWS_DEFAULT_REGION=us-east-1 aws cloudformation deploy --stack-name foo1 --template-file "./temp/test.yaml"

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - foo1

```

```
➜ AWS_PROFILE=localstack AWS_ENDPOINT_URL=http://localhost:4566/ AWS_DEFAULT_REGION=us-east-1 aws cloudformation --output json list-stacks
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/foo1/82ae9cc2",
            "StackName": "foo1",
            "CreationTime": "2024-04-12T21:01:46.913000+00:00",
            "LastUpdatedTime": "2024-04-12T21:01:46.913000+00:00",
            "StackStatus": "CREATE_COMPLETE",
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

### Environment

```markdown
- OS:  OSX Sonoma 14.4
- LocalStack: version 3.3.0
```

### Anything else?

This is the malformed cloudformation template..

```
➜  cat temp/test.yaml

AWSTemplateFormatVersion: 2010-09-09
Resources:
  ServiceUser:
    Type: ‘AWS::IAM::User’
Malformed:
  WaitConditionHandle:
    Type: “AWS::CloudFormation::WaitCondition”
```

**Comment by simonrw** [comment] 2024-04-21 14:50
Hi @zaro0508, this seems to be a duplicate of #9844, down to the same reproduction example (missing `Resources` property, and a malformed property in its place). Would you be happy to close this issue in favour of #9844?

**Closed** 2024-04-22 16:24 UTC
Labels: type: bug, aws:cloudformation, status: backlog
