### ISSUE TITLE
aws-sdk-go-v2 SQS SendMessage with MessageAttributes causing KeyError

### ISSUE THREAD

**Issue by Etomyutikos** [localstack/localstack#4080] opened 2021-05-28 20:59 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When sending an SQS message with attributes, `localstack` fails with a detailed stack trace, but no indication what the error could be.

## Expected behavior

Message is successfully sent with its attributes.

## Actual behaviour

Stacktrace:
```
localstack_1  | 2021-05-28 20:47:02,708:API: 127.0.0.1 - - [28/May/2021 20:47:02] "POST / HTTP/1.1" 500 -
localstack_1  | 2021-05-28 20:47:02,728:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 177, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 203, in dispatch
localstack_1  |     return cls()._dispatch(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 313, in _dispatch
localstack_1  |     return self.call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 259, in _wrapper
localstack_1  |     response = f(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 291, in _wrapper
localstack_1  |     response = f(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/responses.py", line 76, in call_action
localstack_1  |     status_code, headers, body = super(SQSResponse, self).call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 403, in call_action
localstack_1  |     response = method()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/responses.py", line 423, in receive_message
localstack_1  |     return template.render(messages=messages, attributes=attributes)
localstack_1  |   File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 89, in render
localstack_1  |     return render_orig(*args, _escape=_escape, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
localstack_1  |     self.environment.handle_exception()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
localstack_1  |     reraise(*rewrite_traceback_stack(source=source))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
localstack_1  |     raise value.with_traceback(tb)
localstack_1  |   File "<template>", line 8, in top-level template code
localstack_1  |
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
localstack_1  |     return getattr(obj, attribute)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/models.py", line 118, in attribute_md5
localstack_1  |     elif len(attrValue["string_list_value"]) > 0:
localstack_1  | KeyError: 'string_list_value'
```

# Steps to reproduce

Between the `docker-compose.yml` and sample Go code, it should be pretty straightforward. I don't have any special configuration.

## Command used to start LocalStack

```yml
# docker-compose.yml
version: '3.8'
services:
  localstack:
    image: localstack/localstack:0.12.10
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - './docker-compose-configs/configure-localstack.sh:/docker-entrypoint-initaws.d/configure-localstack.sh'
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```go
// using the following dependencies...
/*
github.com/aws/aws-sdk-go-v2 v1.6.0
github.com/aws/aws-sdk-go-v2/config v1.3.0
github.com/aws/aws-sdk-go-v2/credentials v1.2.1
github.com/aws/aws-sdk-go-v2/service/sqs v1.4.1
github.com/aws/smithy-go v1.4.0
*/

// these are basic string fields that may or may not be empty
// examples:
//   traceparent: 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
//   tracestate: congo=t61rcWkgMzE
mattrs := make(map[string]types.MessageAttributeValue)
if p := header.Get("Traceparent"); p != "" {
	mattrs[otelTraceParentKey] = types.MessageAttributeValue{
		DataType:    aws.String("String"),
		StringValue: aws.String(p),
	}
}
if s := header.Get("Tracestate"); s != "" {
	mattrs[otelTraceStateKey] = types.MessageAttributeValue{
		DataType:    aws.String("String"),
		StringValue: aws.String(s),
	}
}

// MessageBody is a marshaled JSON object
i := &sqs.SendMessageInput{
	QueueUrl:          aws.String(s.uri),
	MessageBody:       aws.String(string(j)),
	MessageAttributes: mattrs,
}

// sqs is a basic SQS client using the SDK
if _, err := s.sqs.SendMessage(ctx, i); err != nil {
	return fmt.Errorf("failed to send payload on SQS queue: %w", err)
}
```

**Comment by mgagliardo** [comment] 2021-06-01 15:39
Hello @Etomyutikos, I was unable to reproduce this, here's the piece of code I have used, would you please let me know if there's anything different I might be doing?

Code:
```
package main

import (
	"context"
	"flag"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/aws/aws-sdk-go-v2/service/sqs/types"
)

type SQSSendMessageAPI interface {
	GetQueueUrl(ctx context.Context,
		params *sqs.GetQueueUrlInput,
		optFns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error)

	SendMessage(ctx context.Context,
		params *sqs.SendMessageInput,
		optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)
}

func GetQueueURL(c context.Context, api SQSSendMessageAPI, input *sqs.GetQueueUrlInput) (*sqs.GetQueueUrlOutput, error) {
	return api.GetQueueUrl(c, input)
}

func SendMsg(c context.Context, api SQSSendMessageAPI, input *sqs.SendMessageInput) (*sqs.SendMessageOutput, error) {
	return api.SendMessage(c, input)
}

func main() {
	queue := flag.String("q", "", "The name of the queue")
	flag.Parse()

	if *queue == "" {
		fmt.Println("You must supply the name of a queue (-q QUEUE)")
		return
	}

	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithEndpointResolver(
		aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{
				PartitionID:   "aws",
				URL:           "http://localhost:4566",
				SigningRegion: "us-east-1",
			}, nil
		}),
	),
		config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider("test", "test", "test")),
	)

	if err != nil {
		log.Fatalf("unable to load SDK config, %v", err)
	}

	client := sqs.NewFromConfig(cfg)

	// Get URL of queue
	gQInput := &sqs.GetQueueUrlInput{
		QueueName: queue,
	}

	result, err := GetQueueURL(context.TODO(), client, gQInput)
	if err != nil {
		fmt.Println("Got an error getting the queue URL:")
		fmt.Println(err)
		return
	}

	queueURL := result.QueueUrl

	sMInput := &sqs.SendMessageInput{
		DelaySeconds: 10,
		MessageAttributes: map[string]types.MessageAttributeValue{
			"Title": {
				DataType:    aws.String("String"),
				StringValue: aws.String("The Whistler"),
			},
			"Author": {
				DataType:    aws.String("String"),
				StringValue: aws.String("John Grisham"),
			},
			"WeeksOn": {
				DataType:    aws.String("Number"),
				StringValue: aws.String("6"),
			},
		},
		MessageBody: aws.String("Information about the NY Times fiction bestseller for the week of 12/11/2016."),
		QueueUrl:    queueURL,
	}

	resp, err := SendMsg(context.TODO(), client, sMInput)
	if err != nil {
		fmt.Println("Got an error sending the message:")
		fmt.Println(err)
		return
	}

	fmt.Println("Sent message with ID: " + *resp.MessageId)
}
```

Commands:
```
$ awslocal sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}

$ go run main.go -q test
Sent message with ID: 53777f03-5454-55e0-6276-f1f8203acb5c

$ awslocal sqs receive-message --queue-url "http://localhost:4566/000000000000/test" --attribute-names All --message-attribute-names All
{
    "Messages": [
        {
            "MessageId": "53777f03-5454-55e0-6276-f1f8203acb5c",
            "ReceiptHandle": "khrnmtmhxlrzubpcsmoanjmmdkxosjilhuxxrxziqbhzfmmkcrjnsannomvuqqisxxzikqjshhanozgovehrrskxenbewffhvamfzggzinpcxukgegnudecjgnwdyrkdvwfdushglgconbbmdtsqtnfkbfemcutlgseymjpznudbggbktbemedvpr",
            "MD5OfBody": "076d4593c7d63a5ad51691453a6f4fe5",
            "Body": "Information about the NY Times fiction bestseller for the week of 12/11/2016.",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1622561858857",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1622561869030"
            },
            "MD5OfMessageAttributes": "d25a6aea97eb8f585bfa92d314504a92",
            "MessageAttributes": {
                "Author": {
                    "StringValue": "John Grisham",
                    "DataType": "String"
                },
                "Title": {
                    "StringValue": "The Whistler",
                    "DataType": "String"
                },
                "WeeksOn": {
                    "StringValue": "6",
                    "DataType": "Number"
                }
            }
        }
    ]
}
```

**Comment by Etomyutikos** [comment] 2021-06-01 15:50
Interesting. The only difference I can see off-hand is that you're pulling the queue URL dynamically, while I pass it in statically. I'll do some experimenting to see if that moves the needle at all.

**Comment by Etomyutikos** [comment] 2021-06-01 17:22
I've done some experimenting. I cleared my local data (`rm -rf .localstack`), as well as adjusted my code to pull the queue URL dynamically as in your sample.

I'm no longer seeing the issue. I wish I could provide more detail, but unfortunately I don't have any more.

**Comment by mgagliardo** [comment] 2021-06-01 17:56
No worries, I'm closing this as I can't reproduce it and you are not seeing the issue anymore. Feel free to comment out if needed. Cheers

**Closed by mgagliardo** 2021-06-01 17:56 UTC
Labels: cannot-reproduce
