### ISSUE TITLE
bug: localstack.aws.skeleton    : No moto route for service sns on path

### ISSUE THREAD

**Issue by ThomJN** [localstack/localstack#11482] opened 2024-09-09 06:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack fails with an internal error, stating that there is no route for SNS on the specified path, which causes the tests to fail. 

Forcing localstack to use version 3.7.1 makes the problem go away.

Specific error example:

`Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceException : No moto route for service sns on path /ttp://sns.us-east-1.amazonaws.com/ found.
[xUnit.net 00:00:40.67]       ---- Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.`

### Expected Behavior

LocalStack should properly simulate SNS requests and not throw a “No moto route for service sns” error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- LocalStack:
  LocalStack version: 3.7.2
  LocalStack Docker image sha: sha256:f7097fcc26c972932ff6d9c6bca71bd6c8929dc650ba2d36c620b735d8d4a645
  LocalStack build date: 2024-09-06
  LocalStack build git hash: a607fed9132d6e09b58bd84717c4da83b2b4e505
```

**Comment by dfangl** [comment] 2024-09-10 09:00
Hi @ThomJN !
Could you please share the commands or code for the sqs call raising this error for you?

**Comment by bentsku** [comment] 2024-10-16 13:07
Hello! This is now a duplicate of #11652 which indicated how to reproduce the issue, and that we fixed.

You can get the fix by pulling `localstack/localstack:latest`. Thank you!

**Closed by bentsku** 2024-10-16 13:07 UTC
Labels: type: bug, aws:sns, status: backlog
