### ISSUE TITLE
bug: Creating multiple EKS clusters

### ISSUE THREAD

**Issue by clementblaise** [localstack/localstack#7132] opened 2022-11-04 22:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behavior only allows a single cluster to be deployed using the embedded k3d mechanism.

When a second cluster is deployed the docker daemon deletes the Pod because the binding for the proxy container is already being used by the first cluster.

Localstack Logs
```
2022-11-04T22:04:09.151 DEBUG --- [functhread56] localstack.utils.run       : Executing command: ['/var/lib/localstack/lib/k3d/v5.3.0/k3d-linux-arm64', 'cluster', 'delete', 'cluster1']
2022-11-04T22:04:10.269 DEBUG --- [functhread56] l.services.eks.provider    : Unable to start EKS cluster cluster1: Timeout while waiting for EKS startup...
```

Docker Logs
```
==> /Users/clementblaise/Library/Containers/com.docker.docker/Data/log/vm/dockerd.log <==
[308:22:01:14.849][I] time="2022-11-04T22:01:14.848328094Z" level=warning msg="Failed to allocate and map port 8081-8081: Bind for 0.0.0.0:8081 failed: port is already allocated"
==> /Users/clementblaise/Library/Containers/com.docker.docker/Data/log/vm/containerd.log <==
[308:22:01:15.172][I] time="2022-11-04T22:01:15.172205178Z" level=debug msg="event forwarded" ns=moby topic=/tasks/exit type=containerd.events.TaskExit
[308:22:01:15.208][I] time="2022-11-04T22:01:15.208286303Z" level=debug msg="event forwarded" ns=moby topic=/tasks/delete type=containerd.events.TaskDelete
```

### Expected Behavior

Dynamically assigns the port on the k3s-proxy so that multiple EKS clusters can be deployed.

It seems localstack is using the bridge IP to communicate with the k3s-proxy, I am wondering if it would optionally be possible to not bind on the localhost ?
```
2022-11-04T22:18:07.165 DEBUG --- [functhread17] l.services.eks.k8s_utils   : Waiting for connectivity on EKS load balancer from container: https://192.168.65.2:8081
2022-11-04T22:20:53.891 DEBUG --- [functhread17] l.services.eks.k8s_utils   : Connectivity check for 'https://192.168.65.2:8081' complete
```

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run  -p 4566:4566   -p 4510-4559:4510-4559  -e LOCALSTACK_API_KEY=<Redacted> -e SERVICES="s3, ec2, eks, iam, rds, ecr" -e DEBUG=1 -v /var/run/docker.sock:/var/run/docker.sock localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal eks create-cluster --name cluster0 --role-arn r0 --resources-vpc-config '{}'
    awslocal eks create-cluster --name cluster1 --role-arn r1 --resources-vpc-config '{}'

### Environment

```markdown
- OS: MacOS 12.6 
- LocalStack: latest (6eefd24a05b6)
```

**Comment by HarshCasper** [comment] 2022-11-06 18:12
Hi 👋 

I unfortunately could not replicate the issue. Did you try running any further commands apart from the one mentioned on the `Client commands`, which can help me drill further? 

P.S — Please use `SERVICES=sqs,s3,...` together with `EAGER_SERVICE_LOADING=1` while starting LocalStack.

**Comment by clementblaise** [comment] 2022-11-07 20:50
Thank you for getting back @HarshCasper, I have not run other commands than the ones mentioned.

I tried again with `EAGER_SERVICE_LOADING=1` and got the same result.

I am wondering if this could be platform specific.

Also, I am curious did the command that spawned the clusters contained the localhost binding?

I saw the following on my side, both have `'8081:80@loadbalancer'`
```
2022-11-07T20:38:09.322 DEBUG --- [functhread17] localstack.utils.run       : Executing command: ['/var/lib/localstack/lib/k3d/v5.3.0/k3d-linux-arm64', 'cluster', 'create', 'cluster0', '--api-port', '6443', '-p', '8081:80@loadbalancer']
2022-11-07T20:41:55.275 DEBUG --- [functhread53] localstack.utils.run       : Executing command: ['/var/lib/localstack/lib/k3d/v5.3.0/k3d-linux-arm64', 'cluster', 'create', 'cluster1', '--api-port', '6443', '-p', '8081:80@loadbalancer']
```

**Comment by agermain** [comment] 2022-11-09 16:44
FWIW I can reproduce it:
```
2022-11-09T16:34:11.214058 ERRO[0026] Failed Cluster Start: Failed to add one or more helper nodes: runtime failed to start node 'k3d-cluster1-serverlb': docker failed to start container for node 'k3d-cluster1-serverlb': Error response from daemon: driver failed programming external connectivity on endpoint k3d-cluster1-serverlb (1ea83a1560e9aedca11189365764d62139e3e056171dbd194df5af78ffb6de06): Bind for 0.0.0.0:8081 failed: port is already allocated
```
Docker tag: `sha256:52d649b5106e8f069b47ad57ad011e8f22ab9a13cc2d3967732a2ea9b108dae1`
```
$ awslocal --version
aws-cli/2.7.20 Python/3.9.11 Linux/5.19.0-76051900-generic exe/x86_64.pop.22 prompt/off
```

**Comment by whummer** [comment] 2022-11-15 22:24
Thanks for reporting @clementblaise @agermain - looks like we've been able to reproduce this issue. We'll look into it and will get back to you soon with an update.. Thanks!

**Comment by whummer** [comment] 2022-12-20 23:17
Hi @clementblaise @agermain @bsuv @korenyoni, quick update - we have now pushed a few enhancements that should make it easier to create multiple EKS clusters in parallel.

First, a new special tag `_api_port_` has been introduced that can be used to customize the exposed Kubernetes API port. It defaults to port `6443` (if available), and LocalStack will automatically chose a free port if `6443` cannot be bound.

Second, you can customize the load balancer port (LB) via the special tag `_lb_ports_` - see below for a simple example on how to start two EKS clusters with LB ports `8082` and `8083`, respectively:

```
$ awslocal eks create-cluster --name c1 --role-arn r1 --resources-vpc-config '{}' --tags '_lb_ports_=8082'
# wait a bit until deployed ...
$ awslocal eks create-cluster --name c2 --role-arn r1 --resources-vpc-config '{}' --tags '_lb_ports_=8083'
```

Can you please pull the `latest` Docker image and confirm if that works for you? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment] 2022-12-27 09:52
Closing as resolved - please do let us know if there are any other questions or issues.. Thanks!

**Closed by whummer** 2022-12-27 09:52 UTC
Labels: type: bug, status: resolved/fixed, status: response required, aws:eks
