### ISSUE TITLE
Dashboard not showing the resources that are created  

### ISSUE THREAD

**Issue by urvikalia** [localstack/localstack#1453] opened 2019-08-01 16:31 UTC
Hi ,
I am running localstack in docker. All the services are to be running fine. Have created  SNS , SWS and lambda functions etc [All good]. But the resources created don't appear on the dashboard. Attached screen short for references.

Wanted to know if its a know issue or I am missing out something 
![Image 01-08-19 at 9 40 PM (1)](https://user-images.githubusercontent.com/8938130/62310288-cee20300-b4a6-11e9-8d18-86fd50551a2a.jpg)

Messages on the console
![Image 01-08-19 at 9 55 PM (2)](https://user-images.githubusercontent.com/8938130/62310704-b4f4f000-b4a7-11e9-90ed-be75f56042f5.jpg)

**Comment by dknepprath** [comment] 2019-08-12 03:59
I've been seeing some weird behavior with the dashboard recently as well. 

I have noticed that if I hit refresh in the browser before the resources load then it will reload `http://localhost:8282/#/infra` and it will never show the resources. But if I drop `/#/infra` and load `http://localhost:8282`, then the resources will show. 

I can reliably recreate this issue in Chrome.

**Comment by dknepprath** [comment] 2019-08-12 04:04
Possible duplicate of https://github.com/localstack/localstack/issues/1392

**Comment by Deblob12** [comment] 2019-08-17 05:00
Could you check what local path Docker is mounted too? I had a similar error as well but after specifying file sharing to my local equivalent of /tmp instead of /tmp/localstack I was able to get my dashboard up and running.

**Comment by whummer** [comment] 2019-08-17 09:09
Closing as duplicate of #1392 - please post there if the problem persists. Thanks

**Closed by whummer** 2019-08-17 09:09 UTC
