### ISSUE TITLE
Regression between 0.11.2 & 0.11.3 causes events in event bridge to not serialize correctly

### ISSUE THREAD

**Issue by phillip-haydon** [localstack/localstack#2735] opened 2020-07-17 08:05 UTC
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Running docker-compose with `latest` or `0.11.3` causes messages to come out wrong. Going back to `0.11.2` they work fine.

Executing the lambda directly the serialization happens correctly. So it's an issue somewhere in the event bridge.

## Expected behavior

Messages published to an event bus which are ruled to a Lambda should deserialize to the correct information.

## Actual behavior

The information is incorrect.

In 0.11.2 I get:

```
localstack_main | START RequestId: d4e76268-5617-169a-e9f1-0b0f76fe30e9 Version: $LATEST
localstack_main | Executing Lambda::BeginQCHandler | FileId: 957481
localstack_main | It's wrong: Exception
```

In 0.11.3 I get:

```
localstack_main | START RequestId: daa063db-42e8-1b69-3c64-34ced4eaecaf Version: $LATEST
localstack_main | Executing Lambda::BeginQCHandler | FileId: 0
localstack_main | It's wrong: Exception
```

The `FileId` is `0` when it should be the value from the event.

# Steps to reproduce

## Command used to start LocalStack

`sudo docker-compose up` using the compose file from the repository.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Setup aws stuff:

```
awslocal iam create-role --role-name lambda-role --assume-role-policy-document file://testrole.json
dotnet tool run dotnet-lambda package -pl ./src/TestLocalStack.Workflows.MediaServices/ -o ./output/QCWorkflowBeginQCHandler.zip -c Release -f netcoreapp3.1 --msbuild-parameters "--self-contained true"
awslocal lambda create-function --function-name workflow-begin-qc --runtime dotnetcore3.1 --memory-size 256 --timeout 60 --zip-file fileb://output/QCWorkflowBeginQCHandler.zip --handler TestLocalStack.Workflows.MediaServices::TestLocalStack.Workflows.MediaServices.QCWorkflowHandler::BeginQCHandler --role arn:aws:iam::000000000000:role/lambda-role
awslocal events create-event-bus --name test-event-bus
awslocal events put-rule --name request-qc-event-rule --event-bus-name test-event-bus --event-pattern "{\"source\":[\"test.events\"],\"detail-type\":[\"QCRequestEvent\"]}"
awslocal events put-targets --rule request-qc-event-rule --event-bus-name test-event-bus --targets "Id"="1","Arn"="arn:aws:lambda:us-east-1:000000000000:function:workflow-begin-qc"
awslocal lambda add-permission --function-name workflow-begin-qc --statement-id request-qc-event-rule-statement --action 'lambda:InvokeFunction' --principal events.amazonaws.com --source-arn arn:aws:events:us-east-1:000000000000:rule/request-qc-event-rule
```

Lambda Code

```csharp
public class QCWorkflowHandler
{
    public QCWorkflowHandler()
    {
    }

    public async Task<RequestQCResponse> BeginQCHandler(QCRequestEvent request, ILambdaContext context)
    {
        context.Logger.LogLine($"Executing Lambda::BeginQCHandler | FileId: {request.FileId}");

        throw new Exception("It's wrong");

        return new RequestQCResponse
        {
            Message = $"The requested FileId = {request.FileId}"
        };
    }
}

public class RequestQCResponse
{
    public string MessageId { get; set; } = null!;

    public string Message { get; set; } = null!;
}

public class QCRequestEvent
{
    public int FileId { get; set; }
}
```

Publishing the event:

```
awslocal events put-events --entries file://testevent.json
```

testevent.json
```json
[
	{
		"Source": "test.events",
		"DetailType": "QCRequestEvent",
		"Detail": "{\"fileId\":957481}",
		"EventBusName": "test-event-bus"
	}
]
```

**Comment by phillip-haydon** [comment] 2020-07-18 10:02
I think it maybe this commit which may have broken it.

https://github.com/localstack/localstack/commit/73e65ff60aa01739a7f15a843c936205882701a1#diff-b9a3af230c23fcc5d55f5170ccd9d87a

@loganasherjones

**Comment by loganasherjones** [comment] 2020-07-18 13:55
Hello, this change was caused by me, but not that commit. I made a PR (#2670) which changed the behavior based on my understanding of how the event triggers work, which I got from [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html)

The commit @phillip-haydon referenced is definitely not the problem. If anything I did is a problem it would be [this commit](https://github.com/localstack/localstack/pull/2670/commits/d8e9646f64422e815c9a1b54574a70aebb18afe5)

**Comment by phillip-haydon** [comment] 2020-07-20 06:02
@loganasherjones thanks for the info. Do you think it's an issue with something I've done? Or could this be an issue on the lambda side or with the chance you've made?

I don't know python so it's difficult for me to understand. Definitely need to learn so I could try fix it.

**Comment by loganasherjones** [comment] 2020-07-20 11:09
Hi @phillip-haydon I think the problem is with the lambda code you've written. As far as I understand, the event that gets sent in to the lambda should look like the full cloudwatch event, not just the `Detail` portion of the event.

**Comment by phillip-haydon** [comment] 2020-07-22 05:02
@loganasherjones I think it must be a bug in LocalStack lambda, because if I run this in AWS like so:

```csharp
        public async Task<RequestQCResponse> BeginQCHandler(QCRequestEvent request, ILambdaContext context)
        {
            context.Logger.LogLine($"Executing Lambda::BeginQCHandler | FileId: {request.FileId}");
```

OR

```csharp
        public async Task<RequestQCResponse> BeginQCHandler(CloudWatchEvent<QCRequestEvent> request, ILambdaContext context)
        {
            context.Logger.LogLine($"Executing Lambda::BeginQCHandler | FileId: {request.Detail.FileId}");
```

It works correctly and renders the actual `FileId` but when run in LocalStack, the former results in `0` and the latter results in an exception. 

> localstack_main | Error converting the Lambda event JSON payload to type Amazon.Lambda.CloudWatchEvents.CloudWatchEvent`1[[NewLocalStack.Events.QCRequestEvent, NewLocalStack.Events, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]: The JSON value could not be converted to NewLocalStack.Events.QCRequestEvent. Path: $.detail | LineNumber: 0 | BytePositionInLine: 252.: JsonSerializerException

I suck too much to be able to help fix LocalStack, would it help if I create a repo to reproduce this that works in AWS but fails in LocalStack, so LS can be matched?

**Comment by loganasherjones** [comment] 2020-07-23 00:42
Hi @phillip-haydon 

So, I think I know what's going on here. When you create a target for your lambda like this:

```
awslocal events put-targets --rule myFirstRule --event-bus-name default --targets "Id"="3","Arn"="mylambdaarn"
```

There is an implicit input set. By default, that input is the whole event, not just the detail type of the event. It's possible that in your production configuration you've specified a JSON path that will get you down to the event detail. That's my guess as to why your actual lambda function works, but localstack doesn't.

The change that I made brings localstack more in line with what actually happens from an AWS perspective (at least by default). One thing I'm not sure of is if localstack currently has support for setting up those input path/input transformers.

More than likely there should be a new issue created for the ability for a user to specify this input path/transformers.

@usmangani1  @whummer do either of you have thoughts on this?

**Comment by whummer** [comment] 2020-07-29 17:39
Thanks for the update @phillip-haydon @loganasherjones . 

> ..., would it help if I create a repo to reproduce this that works in AWS but fails in LocalStack, so LS can be matched?

That would be fantastic - if you could provide a small example with a compiled test lambda like here: https://github.com/localstack/localstack/tree/master/tests/integration/lambdas/dotnetcore31 Thanks

**Comment by phillip-haydon** [comment] 2020-07-30 09:18
Will do! Will sort this out this week. Thanks.

**Comment by whummer** [comment] 2020-08-07 15:09
Hey @phillip-haydon - any updates on this issue? Would be great if you could help us with a small sample project (including a pre-compuled .Net core Lambda. Thanks for your help.

**Comment by phillip-haydon** [comment] 2020-08-07 15:19
Hey @whummer, I was focusing on the service inside a lambda first which I messaged you on Slack about. I've got some sample code for that. Will upload it tomorrow and then start an example for this scenario.

Sorry it's taking a while. Super busy :)

**Comment by phillip-haydon** [comment] 2020-08-10 14:18
Just an update. While setting up the project for the Service inside a Lambda I started looking into what the SDK is doing and realised the way configuration works can cause settings to get wiped out. 

So I'm digging into that a bit more before I come back to this particular issue.

**Comment by phillip-haydon** [comment] 2020-08-13 14:29
OK So.

I can confirm that what works in AWS, doesn't appear to work in LocalStack. 

I've created a repo here:

Notes:

1) When event bridge raises the event it's wrapped with `CloudWatchEvent<>` so your method argument must be like: `CloudWatchEvent<Input>` 

2) I've added all the `awslocal` commands in the readme.md (the lambda is already pre-built so you can skip the build step if you like)

3) It's currently built with a webhook.site test which can be found here: https://webhook.site/#!/4173f469-44ef-473d-a753-c8c8d4a994bc/55986fdd-f2eb-4659-8a1a-626c1ec438c6/1

4) There's versions, one takes `object` which shows that the message can come in and execute the webhook endpoint. The 2nd uses the event class and fails with the following:

<details>

```
localstack_main  | START RequestId: 8b87c134-05b4-152e-1eda-34c10ff5252f Version: $LATEST
localstack_main  | Error converting the Lambda event JSON payload to type Amazon.Lambda.CloudWatchEvents.CloudWatchEvent`1[[TestLambdas.InputEvent, TestLambdas, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]: The JSON value could not be converted to TestLambdas.InputEvent. Path: $.detail | LineNumber: 0 | BytePositionInLine: 291.: JsonSerializerException
localstack_main  |    at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
localstack_main  |    at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
localstack_main  | 
localstack_main  |    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
localstack_main  |    at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
localstack_main  |    at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
localstack_main  |    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
localstack_main  |    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
localstack_main  |    at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
localstack_main  |    at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
localstack_main  |    at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
localstack_main  | 
localstack_main  | END RequestId: 8b87c134-05b4-152e-1eda-34c10ff5252f
localstack_main  | REPORT RequestId: 8b87c134-05b4-152e-1eda-34c10ff5252f	Init Duration: 175.11 ms	Duration: 67.08 ms	Billed Duration: 100 msMemory Size: 1536 MB	Max Memory Used: 47 MB	
```

</details>

https://github.com/phillip-haydon/LocalStackTests

So I can confirm that the commit by @loganasherjones is correct. It seems to be when it invokes the lambda it's an issue. What I don't understand is why?!? Because the error appears to be in .NET but this exact same thing works when I uploaded it to my aws account.

**Comment by phillip-haydon** [comment] 2020-08-13 14:33
Also: Sorry for taking so long to supply the repo :(

**Comment by macnev2013** [comment] 2020-08-15 13:39
Hello @phillip-haydon , Thanks for providing sample code. We will be happy to fix this.

**Comment by whummer** [comment] 2020-08-25 20:53
Hi again @phillip-haydon , thanks for providing the sample code. This should be fixed in #2870 - can you please give it another try with the `latest` Docker image? Please report here if the problem persists. Thanks

**Closed by whummer** 2020-08-25 20:53 UTC

**Comment by phillip-haydon** [comment] 2020-08-28 10:47
@whummer this appears to be working now! Thanks!

**Comment by phillip-haydon** [comment] 2020-08-28 10:47
Thanks @macnev2013
