### ISSUE TITLE
Could you please add Apache Iceberg Athena tables type as an option

### ISSUE THREAD

**Issue by orenzion-LC** [localstack/localstack#7497] opened 2023-01-15 09:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Apache Iceberg table type is supported in AWS Athena. Would be very helpful if you could add it to Localstack

**Comment by thrau** [comment] 2023-01-15 13:08
thanks for the suggestion @orenzion-LC, could you share a bit about your setup, how you are using it, maybe with some code examples? that would be helpful to drive things forward :-) thanks!

**Comment by whummer** [comment] 2023-02-13 08:44
Hi @orenzion-LC , thanks for reporting. Just a quick heads-up - we have started implementation of this feature, and should be able to provide an update soon (over the next couple of days).

Related to / duplicate of #7435

**Comment by whummer** [comment] 2023-02-15 12:41
Hi @orenzion-LC , another quick update. We have now added initial support for Iceberg tables in Athena - can you please pull the `latest` Docker image and give it a try? Please note that this feature is only available in the bigdata "mono container" mode, which can be enabled by setting `BIGDATA_MONO_CONTAINER=1` in the LocalStack container environment.

With the latest version, you can now define an Iceberg table in Athena as follows (for example):
```
CREATE TABLE mytable (c1 integer, c2 string, c3 double)
LOCATION 's3://mybucket/prefix/' TBLPROPERTIES ( 'table_type' = 'ICEBERG' )
```

Once the table has been created and data `INSERT`ed into it, we'll see Iceberg metadata and data files being created in S3:
```
s3://test-bucket-f7efd504/_tmp.prefix/
s3://test-bucket-f7efd504/prefix/data/00000-0-user1_20230212221600_cd8f8cbd-4dcc-4c3f-96a2-f08d4104d6fb-job_local1695603329_0001-00001.parquet
s3://test-bucket-f7efd504/prefix/data/00000-0-user1_20230212221606_eef1fd88-8ff1-467a-a15b-7a24be7bc52b-job_local1976884152_0002-00001.parquet
s3://test-bucket-f7efd504/prefix/metadata/00000-06706bea-e09d-4ff1-b366-353705634f3a.metadata.json
s3://test-bucket-f7efd504/prefix/metadata/00001-3df6a04e-070d-447c-a213-644fe6633759.metadata.json
s3://test-bucket-f7efd504/prefix/metadata/00002-5dcd5d07-a9ed-4757-a6bc-9e87fcd671d5.metadata.json
s3://test-bucket-f7efd504/prefix/metadata/2f8d3628-bb13-4081-b5a9-30f2e81b7226-m0.avro
s3://test-bucket-f7efd504/prefix/metadata/70de28f7-6507-44ae-b505-618d734174b9-m0.avro
s3://test-bucket-f7efd504/prefix/metadata/snap-8425363304532374388-1-70de28f7-6507-44ae-b505-618d734174b9.avro
s3://test-bucket-f7efd504/prefix/metadata/snap-9068645333036463050-1-2f8d3628-bb13-4081-b5a9-30f2e81b7226.avro
s3://test-bucket-f7efd504/prefix/temp/
```

Hope that helps support your use case. Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment] 2023-03-02 19:59
Closing as resolved, please let us know if there are any questions or issues with Iceberg tables in Athena, @orenzion-LC . Looking forward to getting your feedback!

**Closed by whummer** 2023-03-02 19:59 UTC
Labels: status: resolved/fixed, status: response required, type: feature, aws:athena
