### ISSUE TITLE
bug: RDS master-username with insufficient permissions

### ISSUE THREAD

**Issue by jandroav** [localstack/localstack#9421] opened 2023-10-20 11:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The specified master username does not have enough privileges over the created instance. It seems it has only all permissions on its schema

### Expected Behavior

I would like the master username could create databases or execute GRANT commands

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 `localstack start -d`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal rds create-db-cluster --db-cluster-identifier mariadb-primary-cluster --engine mariadb --engine-version 10.6 --database-name lbcat --master-username lbuser --master-user-password test

awslocal rds create-db-instance --db-instance-identifier mariadb-primary-cluster-instance --db-cluster-identifier mariadb-primary-cluster --engine mariadb --db-instance-class db.t3.medium
```

#### Test

Trying to list users:

![image](https://github.com/localstack/localstack/assets/67458478/eb19ec4a-5059-4fb7-a7df-fcaec2339d65)

### Environment

```markdown
- OS: macOS Sonoma 14-0
- LocalStack: 2.2.o
```

**Comment by jandroav** [comment] 2023-12-18 10:31
Hey team! Is this something to be planned in the next few sprints? We at Liquibase are waiting for this to start using localstack among our test infra.

**Comment by steffyP** [comment] 2024-01-03 09:14
Hi @jandroav!

Thanks for the report and your patience! We released a fix in the `latest` localstack-pro image so for MariaDB the master-username should have the permissions now. 

Please let us know if you have any other issues! 
In case you still face limitations with other database engines, please provide some details about the engine-type and the operations you need to run 🙏

**Comment by jandroav** [comment] 2024-01-04 12:04
Hey @steffyP !

I tested it and it worked for mariadb. Thanks a lot.

It seems it is failing with the same issue for:

**mysql RDS**

```bash
awslocal rds create-db-instance --db-instance-identifier mysql --engine mysql --engine-version 8.0  --db-name lbcat --master-username *** --master-user-password test --db-instance-class db.t3.medium
```

**mysql Aurora**

```bash
awslocal rds create-db-cluster --db-cluster-identifier aurora-mysql-primary-cluster --engine aurora-mysql --engine-version 8.0 --database-name lbcat --master-username *** --master-user-password test
```

**sqlserver**

```bash
awslocal rds create-db-instance --db-instance-identifier mssql2019 --engine sqlserver-ee --engine-version 2019  --db-name lbcat --master-username *** --master-user-password Test.2024 --db-instance-class db.t3.medium
```
Same issue for all of them:

```bash
[2024-01-04 11:23:07] [SEVERE ] Stacktrace: StatementCallback; bad SQL grammar [DROP DATABASE IF EXISTS PROSCHEMA_HCUS_U_P]; nested exception is java.sql.SQLSyntaxErrorException: Access denied for user '***'@'%' to database 'PROSCHEMA_HCUS_U_P':
[598](https://github.com/liquibase/liquibase-pro-tests/actions/runs/7408833933/job/20157869706#step:12:599)
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DROP DATABASE IF EXISTS PROSCHEMA_HCUS_U_P]; nested exception is java.sql.SQLSyntaxErrorException: Access denied for user '***'@'%' to database 'PROSCHEMA_HCUS_U_P'
```

**Comment by steffyP** [comment] 2024-01-04 17:33
Hi @jandroav, 

thanks the feedback! I am able to reproduce the issue with `mysql` + `mysql-aurora` (will provide a fix soon).

However, for `sqlserver` I am not able to reproduce the issue. The masteruser should already have the role `sysadmin`. 
Could there be an issue with the sql-query? 
I ran tests with the `DROP DATABASE IF EXISTS mydb` that you provided. For mssql this is not a valid syntax however, it should be something like 
```
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'YourDatabaseName')
BEGIN
    -- The database exists, so drop it
    DROP DATABASE YourDatabaseName;
END
```

Please let me know if this is indeed the issue for `sqlserver` 🙏 Otherwise I would need more information on the commands you actually trying to run for that engine type. 
Thank you!

**Comment by jandroav** [comment] 2024-01-05 15:13
Hey @steffyP !

Sorry, the issue we are getting for `sqlserver` is another thing:

```bash
Could not find stored procedure 'msdb.dbo.rds_drop_database'.; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Could not find stored procedure 'msdb.dbo.rds_drop_database'.
```

Our QA team is taking a look, I don't think it is related to the issue form this ticket.

Glad to see the fix for mysql + mysql-aurora is planned! Thanks!

**Comment by jandroav** [comment] 2024-01-08 08:59
Hey @steffyP. I have news from our QA team. We are using in our automation the following:https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.CommonDBATasks.DropMirrorDB.html

So it seems the `localstack` **sqlserver** instance does not have those built-in procedures, right?

**Comment by steffyP** [comment] 2024-01-08 10:49
Hi @jandroav, thanks for the update! 
No, those built-in procedures are currently not available. 
If you need those, could you please create a new ticket, along with a list of the procedures you require?

**Comment by jandroav** [comment] 2024-01-08 13:52
Hey @steffyP , issue create here https://github.com/localstack/localstack/issues/10018
I did not include other procedures since queue only need that one.

**Comment by steffyP** [comment] 2024-01-09 10:30
Hi @jandroav, 

the masteruser permissions for `mysql` and `mysql-aurora` should be fixed now in the `latest` localstack image.

**Comment by jandroav** [comment] 2024-01-09 12:16
Hi @steffyP huge thanks for doing it. I am testing it right now but it seems to be working:

![image](https://github.com/localstack/localstack/assets/67458478/28dd3577-7e07-40d1-9bac-bbb11f5823f8)

So we are only getting the issue for SQLServer. Is this something to be expected soon? I am just asking you because we could workaround it in the meantime if it is something that requires a big effort from your end.

**Comment by steffyP** [comment] 2024-01-09 12:25
Great to hear, @jandroav! 🥳 

regarding SQLServer: I am afraid we don't have a timeline yet! 
Hope you can use a workaround in the meantime, we will provide updates in the [other ticket](https://github.com/localstack/localstack/issues/10018) you have created.

I think we close this ticket then? :)

**Comment by jandroav** [comment] 2024-01-09 12:48
Sure!

**Closed** 2024-01-09 12:57 UTC
Labels: type: bug, aws:rds, status: in progress
