### ISSUE TITLE
Couldn't create a bucket or queue without the --no-sign-request option on aws cli

### ISSUE THREAD

**Issue by djangofan** [localstack/localstack#716] opened 2018-04-15 00:10 UTC
Couldn't create a bucket or queue without the **--no-sign-request** option on aws cli

Maybe you could mention that in your docs?  Would have saved me some time.  Also, when you first startup the UI, it's not obvious why its blank.

For example:

```
aws --region us-west-2 --no-sign-request --endpoint-url=http://192.168.99.100:4572 s3 mb s3://mytestbucket

aws --no-sign-request --endpoint-url=http://192.168.99.100:4570 sqs create-queue --queue-name MyQueue
```

**Comment by whummer** [comment] 2019-11-08 23:03
Thanks for reporting @djangofan . Unable to reproduce this in the latest version - seems to be fixed. Closing this issue - please re-open if the problem persists.

**Closed by whummer** 2019-11-08 23:03 UTC
