### ISSUE TITLE
bug: initiate_auth_srp 

### ISSUE THREAD

**Issue by benjaminlhai** [localstack/localstack#6499] opened 2022-07-22 06:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Latest Version and
[0.14.3.1](https://hub.docker.com/layers/localstack/localstack/localstack/0.14.3.1/images/sha256-c47f5ede1e5fc4fec941ef8605e0b85be66f8b61ed20828e2ea1e51581637932?context=explore)

A few months ago, Initial SRP auth worked with localstack pro, but now it fails. Stack trace below.

Executing awslocal commands/interacting with the CLI mostly works, but this flow does not work. Same actions works fine with AWS Cognito live. 

This exception is from when you try to use boto3 to initiate auth. 

```
2022-07-22T05:53:59.493:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localstack:4566/: '__salt__' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 992, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 80, in B
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 76, in G
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cognito_idp/provider.py.enc", line 398, in initiate_auth
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cognito_idp/provider.py.enc", line 495, in initiate_auth_srp
KeyError: '__salt__'

```

and this is via the CLI

```
2022-07-22T06:00:34.557:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'NoneType' object has no attribute 'get' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 992, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 80, in B
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 76, in G
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cognito_idp/provider.py.enc", line 385, in initiate_auth
AttributeError: 'NoneType' object has no attribute 'get'
```

### Expected Behavior

You should be able to initiate SRP auth the same as with the live cognito API

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack
    docker compose (custom)
    Call from boto3

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cognito-idp initiate-auth --auth-flow USER_SRP_AUTH --client-id XXXYYYZZZ

### Code Example

```
    def login(self):
        try:
            response = self.client.initiate_auth(
                ClientId=self.client_id,
                AuthFlow="USER_SRP_AUTH",
                AuthParameters=self.get_auth_params(),
            )
         except <...> e:
         
        if response["ChallengeName"] == self.PASSWORD_VERIFIER_CHALLENGE:
            challenge_response = self.challenge(
                challenge_name=self.PASSWORD_VERIFIER_CHALLENGE,
                challenge_parameters=response["ChallengeParameters"],
                data=self.device_key,
            )
            return challenge_response
        else:
            return response
```

### Environment

```markdown
- OS: Multiple, but I am running OSX, happens on Windows as well.
- LocalStack: latest, 0.14.3.1 upwards, Can't confirm for lower versions at the moment
```

**Comment by MarcelStranak** [comment] 2022-07-26 10:57
Hi @benjaminlhai, can you please share the full steps how are you creating the app client for cognito? Thank you.

**Comment by benjaminlhai** [comment] 2022-07-27 01:32
hey @MarcelStranak 

Here are the steps to create the pool and client:

There are some auxiliary steps that I usually run, but for the purposes of this testing I have omitted them from my setup workflow to isolate the issue.


1. Create Pool

``` 
awslocal cognito-idp create-user-pool \
--pool-name "local-user-pool" \
--policies '{"PasswordPolicy":{"MinimumLength":8,"RequireUppercase":true,"RequireLowercase":true,"RequireNumbers":true,"RequireSymbols":true}}' \
--auto-verified-attributes '["phone_number"]' \
--mfa-configuration "OFF" \
--admin-create-user-config '{"AllowAdminCreateUserOnly":false}' \
--schema '[{"Name":"id","AttributeDataType":"Number","Mutable":true,"NumberAttributeConstraints":{"MinValue":"0","MaxValue":"1000"},"StringAttributeConstraints":{"MinLength":"1","MaxLength":"256"}},{"Name":"special_id","AttributeDataType":"Number","Mutable":true,"NumberAttributeConstraints":{"MinValue":"0","MaxValue":"1000"},"StringAttributeConstraints":{"MinLength":"1","MaxLength":"256"}},{"Name":"username","AttributeDataType":"String","Mutable":true,"NumberAttributeConstraints":{"MinValue":"0","MaxValue":"1000"},"StringAttributeConstraints":{"MinLength":"1","MaxLength":"256"}}]'
```

2. Create user pool client

```
awslocal cognito-idp create-user-pool-client \
--user-pool-id "user_pool_id_xxx_yyy_zzz" \
--client-name "localclient" \
--generate-secret \
--read-attributes '["address","irthdate","custom:id","custom:special_id","custom:username","email","email_verified","family_name","gender","given_name","locale","middle_name","name","nickname","phone_number","phone_number_verified","picture","preferred_username","profile","updated_at","website","zoneinfo"]' \
--refresh-token-validity 30 \
--write-attributes '["address","birthdate","custom:id","custom:special_id","custom:username","email","family_name","gender","given_name","locale","middle_name","name","nickname","phone_number","picture","preferred_username","profile","updated_at","website","zoneinfo"]'
```
 
3. Create one user
```
awslocal cognito-idp admin-create-user \
--user-pool-id "user_pool_id_xxx_yyy_zzz"  \
--username "<email>" \
--user-attributes '[{"Name": "name", "Value": "Admin"},{"Name": "email", "Value": "<emailstr>"},{"Name": "email_verified", "Value": "true"},{"Name": "custom:username", "Value": "<emailstr>"}, {"Name": "custom:special_id", "Value": <int>}, {"Name": "custom:id", "Value": <int>},{"Name": "phone_number", "Value": "<phonestr>"},{"Name": "phone_number_verified", "Value": "true"}]' \
--temporary-password <password>
```

**Comment by giograno** [comment] 2022-07-27 15:31
Hi @benjaminlhai, thanks for the details. I have been trying to replicate your issues.
The exceptions given by the CLI and by `boto` look different to me. I think that the second one is caused by calling `initiate-auth` without any challenge response. Can you confirm it?
For the code example, could you please share some more insights about the `AuthParameters` passed to the `initiate_auth` function? 
Thank you very much for your help.

**Comment by benjaminlhai** [comment] 2022-07-28 04:41
Hi, apologies for late reply.. I am now having some issues with just getting the 1.0.x and latest containers to start, so I will need to come back to you with some more specifics on your first question once I can successfully launch the container.

But on the topic at hand, the authentication parameters are as follows...

Our code is similar to an implementation like the one that can be found in pycognito, but not identical, so the link below can only really be used as a reference for how the SRP_A values are generated, but should give you a general idea of what we're doing

https://github.com/pvizeli/pycognito/blob/master/pycognito/aws_srp.py


```
        auth_params = {
            "USERNAME": self.username,
            "SRP_A": long_to_hex(self.large_a_value), 
            "SECRET_HASH": get_secret_hash(self.username),
        }
```

**Comment by whummer** [comment] 2022-09-24 10:10
Hi again @benjaminlhai , quick follow-up - have you been able to get the latest version of LocalStack started? There have been a number of enhancements in Cognito auth flows in the meantime, and we believe (hope) that this should be fixed in the meantime. Please let us know if the problem persists, or if we can close this issue.. Thanks!

**Comment by benjaminlhai** [comment] 2022-09-26 02:00
Hi, unfortunately, I've cancelled my Pro subscription and won't be able to test this further.

**Closed** 2022-09-26 16:26 UTC
Labels: type: bug, status: resolved/fixed, aws:cognito
