### ISSUE TITLE
S3 create bucket stops working in last two versions

### ISSUE THREAD

**Issue by chrisburrell** [localstack/localstack#138] opened 2017-06-29 17:08 UTC
Hi

I'm trying to create a simple bucket on localstack (via the dockerhub image) and this fails on version 0.5.5 of the docker image. Having downgraded to 0.5.3.1 or 0.5.4, the creation of the bucket works fine. 

My code is quite simple. 

```
        AmazonS3 s3Client = new AmazonS3Client(new BasicAWSCredentials(accessKey, secretKey));
        s3Client.setEndpoint(s3Endpoint);
        S3ClientOptions options = S3ClientOptions.builder().setPathStyleAccess(true).disableChunkedEncoding().build();
        s3Client.setS3ClientOptions(options);

        if (!s3Client.doesBucketExist(BUCKET_NAME)) {
            s3Client.createBucket(BUCKET_NAME);
        }

```

I get the following error:
```
com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: null)
, S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4137)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:998)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:939)
	at uk.co.landbay.integration.IntegrationSteps.iReceiveAFileFromContainingTheFollowingContentWithName(IntegrationSteps.java:88)
	at ✽.When I receive a file containing the following content with name "2017-06-20-0-reconciliation":(process_file.feature:10)
```

As you can see the line that fails is the createBucket (which is a bit odd as debugging through the cilent suggests it's making a HEAD request, though perhaps this is expected as a pre-emptive call). Either way, the exception is thrown up.

**Comment by whummer** [comment] 2017-08-01 09:34
Thanks for reporting @chrisburrell, and apologies for the long delay. I was unable to reproduce this error locally. There have been a few updates since version `0.5.5`, could you please give it a try with the latest version (`0.7.3`)? Thanks

**Comment by whummer** [comment] 2017-08-06 07:02
Any update on this issue @chrisburrell - have you been able to reproduce this issue on the most recent version? Thanks

**Comment by whummer** [comment] 2017-08-31 13:23
Closing this ticket as this issue is likely fixed in one of the latest versions. Please re-open if the issue persists.

**Closed by whummer** 2017-08-31 13:23 UTC
Labels: bug, needs-triaging
