### ISSUE TITLE
Unable to start localstack. java/mvn/npm/pip are up to date

### ISSUE THREAD

**Issue by Sudhamsh** [localstack/localstack#1121] opened 2019-02-12 06:46 UTC
```
localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting mock Secrets Manager (http port 4584)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2019-02-11T22:38:03:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:38:17:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:38:31:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:38:45:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:38:59:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:39:13:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:39:27:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:39:41:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:39:55:ERROR:localstack.services.dynamodb.dynamodb_starter: DynamoDB health check failed:  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/dynamodb/dynamodb_starter.py", line 18, in check_dynamodb
    wait_for_port_open(DEFAULT_PORT_DYNAMODB_BACKEND, http_path='/', expect_success=False, sleep_time=1)
  File "/usr/local/lib/python2.7/site-packages/localstack/utils/common.py", line 274, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/usr/local/lib/python2.7/site-packages/localstack/utils/common.py", line 295, in retry
    raise raise_error
Exception

2019-02-11T22:39:55:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-02-11T22:39:55:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 349, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 487, in start_infra
    check_infra(apis=apis)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 356, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR: 'NoneType' object has no attribute '__getitem__'
```

**Comment by bhandariakshay1601** [comment] 2019-02-25 11:01
facing the same issue

**Comment by whummer** [comment] 2019-03-06 22:04
@Sudhamsh can you please post the output of `DEBUG=1 localstack start`?

**Comment by PatrickMans** [comment] 2019-03-18 10:47
I got that same error, over and over again. I started localstack with the debug option and noticed one line:
```
Starting local Elasticsearch (http port 4571)...
Error: Invalid or corrupt jarfile DynamoDBLocal.jar
...followed by:
2019-03-18T11:45:21:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4572: (9, 'Bad file descriptor') Traceback (most recent call last):
  File "/Users/claranet/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 312, in run_cmd
    self.httpd.serve_forever()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
error: (9, 'Bad file descriptor')

2019-03-18T11:45:21:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4585: (9, 'Bad file descriptor') Traceback (most recent call last):
  File "/Users/claranet/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 312, in run_cmd
    self.httpd.serve_forever()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
error: (9, 'Bad file descriptor')

ERROR: 'NoneType' object has no attribute '__getitem__'

```
I pulled the repo once again this morning, and did a make install. This made no difference for the dynamodblocal.jar file. 
(installing/running on a mac).

**Comment by bitbrain** [comment] 2019-05-02 08:43
Same issue here:
```
File "/opt/code/localstack/localstack/services/infra.py", line 415, in check_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR: 'NoneType' object has no attribute '__getitem__'
Waiting for all LocalStack services to be ready
2019-05-02 08:40:16,514 INFO exited: infra (exit status 0; expected)
2019-05-02 08:40:16,536 INFO spawned: 'infra' with pid 366
```
**Docker version 18.09.2, build 6247962**
**localstack/localstack:latest@d7d5a42641d9**

**Comment by whummer** [comment] 2019-11-27 21:26
Thanks for reporting - this issue should be fixed in the meantime, given that the default installation is now using a pre-built Docker image. Closing this issue - please re-open if the problem persists. Thanks

**Closed by whummer** 2019-11-27 21:26 UTC
Labels: installation, needs-triaging

**Comment by qasimzee** [comment] 2019-12-03 18:14
I think the issue is still there.
