### ISSUE TITLE
Windows can't find localstack

### ISSUE THREAD

**Issue by GionRubitschung** [localstack/localstack#1415] opened 2019-07-10 07:55 UTC
I have some trouble to start and run localstack. I can install localstack relatively easy with "pip install localstack". This worked for me without problems. After the installation I tried to start localstack with "localstack start" but then windows tells me it can't find localstack.

```
The command "localstack" is either misspelled or
could not be found.
```

I searched alot and found out there are some simillar problems. In one issue I found something that could eventually work for me. In [this question](https://github.com/localstack/localstack/issues/822). Because I never worked with python this is a litle bit confusing for me. I tried [this answer](https://github.com/localstack/localstack/issues/822#issuecomment-404233924). I switched into the python scripts folder and runed the command "py localstack start". Here it is interesting, that I get an error again, but this time windows recognizes localstack. This here is the error

```
Traceback (most recent call last):
  File "localstack", line 31, in <module>
    from localstack.utils import cli
  File "c:\users\gion rubitschung\appdata\local\programs\python\python37\lib\site-packages\localstack\utils\cli.py", line 4, in <module>
    from localstack.services import infra
  File "c:\users\gion rubitschung\appdata\local\programs\python\python37\lib\site-packages\localstack\services\infra.py", line 20, in <module>
    from localstack.utils import common, persistence
  File "c:\users\gion rubitschung\appdata\local\programs\python\python37\lib\site-packages\localstack\utils\common.py", line 5, in <module>
    import pty
  File "c:\users\gion rubitschung\appdata\local\programs\python\python37\lib\pty.py", line 11, in <module>
    import tty
  File "c:\users\gion rubitschung\appdata\local\programs\python\python37\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
```

How can I start localstack just by typing "localstack start"?

**Comment by netmailgopi** [comment] 2019-07-30 18:44
localstack for windows is broken after 0.9.0 version, there's another ticket about termios. termios is not available for windows hence it can't work. you could do a `pip install "localstack==0.9.0"` to install that version which might work for you.

**Comment by whummer** [comment] 2019-08-03 19:03
Closing as duplicate of https://github.com/localstack/localstack/issues/563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

    only install the bare minimum dependencies by default
    start LocalStack in Docker by default, and
    lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:03 UTC
