### ISSUE TITLE
S3 Service not starting on Ubuntu

### ISSUE THREAD

**Issue by gubiniliya** [localstack/localstack#4480] opened 2021-08-24 08:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

localstack can't runing correctly

The following problem is observed during normal startup. And it is constant, but sometimes, after restarting the system and several attempts, the local stack starts.
there have been various attempts to fix it, for example i tryed:

    docker-compose -f localstack.yalm stop
    docker ps #and kill all containers
    docker volume ls
    docker volume prune #for clear all volumes
    AND AGAIN
    docker-compose -f localstack.yalm build
    docker-compose -f localstack.yalm start

#### terminal output with error
    localstack                  | 2021-08-24T06:49:28:WARNING:localstack.services.plugins: Service "s3" not yet available, retrying...
    localstack                  | Waiting for all LocalStack services to be ready

Why this behavior is not clear, then it works, then it does not. Because of this, it is impossible to consistently engage in the project.
Someone may have had a similar problem and have a clear solution.

### Expected Behavior

localstack is runnig, ready and work correctly

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack 

    docker-compose -f localstack.yalm build
    docker-compose -f localstack.yalm start

#### localstack.yalm

    localstack-local:
    image: localstack/localstack:0.12.10 (or latest)
    hostname: localstack-local
    container_name: localstack-local
    ports:
      - 4566:4566
    environment:
      - LOCALSTACK_API_KEY=*********
      - SERVICES=cognito,sqs,elasticache,timestream,cloudwatch,s3,cognito-idp,ses,sns

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack: 0.12.10 or latest
- Docker: 20.10.8, build 3967b7d
```

### Anything else?

If you have any questions and I can somehow supplement this ticket, I will be grateful for the tips to do everything in as much detail as possible.

**Comment by dfangl** [comment] 2021-08-24 08:13
Hi @gubiniliya !
When the s3 service does not start, can you check if `dig s3.localhost.localstack.cloud` resolves to 127.0.0.1?
Thanks in advance!

**Comment by gubiniliya** [comment] 2021-08-24 11:46
Hello @dfangl thansk for quiclky answer!
Now localstack work and im'm working on my project and can't check it in error moment, but now, where everything is fine i see on dig:

    dig s3.localhost.localstack.cloud
    
    ; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> s3.localhost.localstack.cloud
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15681
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 65494
    ;; QUESTION SECTION:
    ;s3.localhost.localstack.cloud.	IN	A
    
    ;; Query time: 366 msec
    ;; SERVER: 127.0.0.53#53(127.0.0.53)
    ;; WHEN: Tue Aug 24 13:42:59 CEST 2021
    ;; MSG SIZE  rcvd: 58

**Comment by gubiniliya** [comment] 2021-08-24 13:29
@dfangl 
Okay, after reboot my laptop I'm again can't run localstack from first attempt
And output in error moment

    dig s3.localhost.localstack.cloud    
    ; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> s3.localhost.localstack.cloud
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4851
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 65494
    ;; QUESTION SECTION:
    ;s3.localhost.localstack.cloud. IN  A
    
    ;; Query time: 130 msec
    ;; SERVER: 127.0.0.53#53(127.0.0.53)
    ;; WHEN: Tue Aug 24 15:27:15 CEST 2021
    ;; MSG SIZE  rcvd: 58

**Comment by dfangl** [comment] 2021-08-24 13:50
Some ISPs or Router configuration block external domains resolving for local addresses (as DNS rebind protection). Can you try pointing this domain to 127.0.0.1 (e.g via your hosts file) and check if the problem is solved?

**Comment by gubiniliya** [comment] 2021-08-24 14:39
Okay, add string in /etc/hosts like

    127.0.0.1	s3.localhost.localstack.cloud

When i check it, ask you, thanks for hint, hope it's help.
Make test(restart localstack) after laptop reboot

**Comment by dfangl** [comment] 2021-08-25 15:25
I hope this fixed it for you, if not, please do not hesitate to comment again!

**Closed by dfangl** 2021-08-25 15:25 UTC
Labels: bug, needs-triaging
