### ISSUE TITLE
Weird behaviour when building localstack locally 

### ISSUE THREAD

**Issue by kprzerwa-r7** [localstack/localstack#1192] opened 2019-03-13 17:48 UTC
I hit very strange issue few days ago. I've set up a test framework for async lambda and wanted to debug it, as I was not getting message in the queue that the function supposed to push into. Debugging async lambda is nearly impossible as there is no log output, unless it's an exception, so I modified `lambda_executors.py` to put log into `stderr` and later append it to the default log output (https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py#L118). I build it locally and my tests passed. I found it weird, so I reverted all my changes to localstack, cleaned and removed all docker images, rebuilt `master` branch, and again my tests passed, while they kept failing on any version of localstack over 0.8.6 I pull.
I tried couple more times, every time clearing pulled/built images, with same results.

Here are commands I used to build docker locally:
```
make clean
make install
make init 
make prepare-java-tests-infra-jars 
make docker-build-base
make docker-build
```
I believe this should be similar to the build steps for localstack, but I am wondering where the difference could come from? Am I missing as step, or is the build process missing one?

**Comment by whummer** [comment] 2019-03-14 12:20
> Debugging async lambda is nearly impossible as there is no log output

Can you check CloudWatch logs - the logs of both, sync and async Lambdas, should get stored there.

> they kept failing on any version of localstack over 0.8.6 I pull.

Not sure what the root cause is here, but Is it possible that we already pushed a fix to `master` that has not been released as a new version yet? What if you pull the `latest` version of the image - does that work?

**Comment by kprzerwa-r7** [comment] 2019-03-14 13:58
`latest` does not work. It looks like base image makes the difference. I get failures I use the remote version: `localstack/java-maven-node-python            latest                    acf7bda02a36        35 hours ago        551MB`

**Comment by kprzerwa-r7** [comment] 2019-03-14 13:59
I'll see if I can get anything out from CloudWatch logs.

**Comment by kprzerwa-r7** [comment] 2019-03-14 15:04
CloudWatch logs are empty as they are being fed with fixed output for asynchronous lambda https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py#L118. With debug enabled all I see is:
```
2019-03-14T15:00:08:DEBUG:localstack.services.awslambda.lambda_executors: Lambda result / log output:
{"asynchronous": "True"}
> Lambda executed asynchronously
```

**Comment by kprzerwa-r7** [comment] 2019-03-21 18:30
I thought that this is may be caused by `localstack/java-maven-node-python` image not being updated, as `latests` was built couple days before last build of `localstack/localstack:latest`. Even now, the base image is 6 days older. Thoughts?

**Comment by Psynbiotik** [comment] 2019-03-27 16:08
This may or may not help you but one issue I've had is that in order for the latest code to be run you have to run make test-java before running make infra in order for it to use the latest code.

To use latest code you have to run:
make install
make test-java
make infra

This is because the make infra actually uses the code from the last release and not the current code unless you use make test-java.

I'd suggest having make infra copy the latest code to the directory it launches from when running make infra.

**Comment by Psynbiotik** [comment] 2019-03-27 16:17
This may or may not help you as I haven't tried the docker build but one issue I've had is that in order for the latest code to be run you have to run make test-java before running make infra in order for it to use the latest code.

You might think that make prepare-java-tests-infra-jars would be enough, but it isn't.

To use latest code you have to run:
make install
make test-java
make infra

This is because the make infra actually uses the code from the last release and not the current code unless you use make test-java.

I'd suggest having make infra copy the latest code to the directory it launches from when running make infra.

I'm not sure if this applies to the docker builds or not.

**Comment by whummer** [comment] 2019-12-04 23:05
This should be fixed in the latest version. When fetching the logs from Lambda, please make sure your CLI call matches the region configured in the LocalStack server (`DEFAULT_REGION`). Closing as outdated / cannot reproduce - please re-open if the problem persists. Thanks

**Closed by whummer** 2019-12-04 23:05 UTC
Labels: bug, needs-triaging
