### ISSUE TITLE
bug: Kinesis unable to lazily load in 0.13.0

### ISSUE THREAD

**Issue by kgston** [localstack/localstack#5060] opened 2021-12-03 03:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When localstack inits on the first request to the edge service, Kinesis fails to load properly. Seems to be a bad assertion in the logic path.

However, it works when setting eager loading to true `EAGER_SERVICE_LOADING=1`

See container logs for details:

```
2021-12-03T03:02:58:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fc649242820>(None) failed: failed to get service for kinesis:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 239, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 184, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 198, in check_kinesis
    assert not kinesis_stopped.is_set()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 165, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for kinesis: 

2021-12-03T03:02:58:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fc649242550>(None) failed: failed to get service for kinesis:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 239, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 184, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 198, in check_kinesis
    assert not kinesis_stopped.is_set()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 165, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for kinesis: 

2021-12-03T03:02:58:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: failed to get service for kinesis:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 239, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 184, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 198, in check_kinesis
    assert not kinesis_stopped.is_set()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 165, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for kinesis: 

2021-12-03T03:02:58:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: failed to get service for kinesis:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 239, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 184, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 198, in check_kinesis
    assert not kinesis_stopped.is_set()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 165, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for kinesis: 
```

### Expected Behavior

Expect it to init successfully

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```shell
docker-compose up
```

`docker-compose.yml`
```yaml
localstack:
  image: localstack/localstack:0.13.0
  ports:
    - 4566:4566
  environment:
    - SERVICES=lambda,firehose,kinesis,sns,sqs,dynamodb
    - DEBUG=1
```

### Environment

```markdown
- OS: Ubuntu 20.04 in WSL 1
- LocalStack: 0.13.0
```

**Comment by naspeh** [comment] 2021-12-07 11:02
Hi @kgston, do you really start `localstack` with the command from the description?

> docker run localstack/localstack

localstack doesn't support this kind of start.

----

It would be helpful to get more logs, could you please add `DEBUG=1` env var and run the command once again.

**Comment by kgston** [comment] 2021-12-07 12:17
I updated the reproduction steps in the issue description and attached the full debug log below. A quick glance seems to suggest this might be the culprit.

[docker.log](https://github.com/localstack/localstack/files/7668197/docker.log)

```log
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,445 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis TLS Mock Service on port 4567
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,445 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis Plain Mock Service on port 41623
[io-compute-0] [34mINFO [0;39m 2021-12-07 12:09:23,446 [36mk.m.KinesisMockService[0;39m [33mcontextId=83f72a08-5756-11ec-9389-8dd0c1e2629a[0;39m - Not configured to persist data, persist loop not started
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,448 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis TLS Mock Service on port 4567
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,448 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis Plain Mock Service on port 39153
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,449 [36mk.m.KinesisMockService[0;39m [33mcontextId=83f79f31-5756-11ec-9893-5738db6a1e14[0;39m - Not configured to persist data, persist loop not started
java.net.BindException: Address in use
at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_BindException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
at sun.nio.ch.Net.bind0(Net.java)
at sun.nio.ch.Net.bind(Net.java:455)
at sun.nio.ch.Net.bind(Net.java:447)
at sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServerSocketChannelImpl.java:164)
at java.nio.channels.AsynchronousServerSocketChannel.bind(AsynchronousServerSocketChannel.java:198)
at fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$serverResource$3(SocketGroupPlatform.scala:93)
at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$serverResource$2(SocketGroupPlatform.scala:87)
at traverse @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.serverResource(SocketGroupPlatform.scala:86)
at flatMap @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.serverResource(SocketGroupPlatform.scala:86)
at apply @ kinesis.mock.cache.Cache$.$anonfun$apply$4(Cache.scala:1442)
at apply @ kinesis.mock.cache.Cache$.$anonfun$apply$4(Cache.scala:1442)
at uncancelable @ fs2.Pull$.acquireCancelable(Pull.scala:375)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at handleErrorWith @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.handleErrorWith(Compiler.scala:150)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at uncancelable @ fs2.Compiler$TargetLowPriority$MonadCancelTarget.uncancelable(Compiler.scala:158)
at unique @ fs2.Compiler$Target$ConcurrentTarget.unique(Compiler.scala:183)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at of @ kinesis.mock.cache.Cache$.apply(Cache.scala:1436)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at run @ com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
Exception in thread "main" java.net.BindException: Address in use
at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_BindException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
at sun.nio.ch.Net.bind0(Net.java)
at sun.nio.ch.Net.bind(Net.java:455)
at sun.nio.ch.Net.bind(Net.java:447)
at sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServerSocketChannelImpl.java:164)
at java.nio.channels.AsynchronousServerSocketChannel.bind(AsynchronousServerSocketChannel.java:198)
at fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$serverResource$3(SocketGroupPlatform.scala:93)
at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$serverResource$2(SocketGroupPlatform.scala:87)
at traverse @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.serverResource(SocketGroupPlatform.scala:86)
at flatMap @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.serverResource(SocketGroupPlatform.scala:86)
at apply @ kinesis.mock.cache.Cache$.$anonfun$apply$4(Cache.scala:1442)
at apply @ kinesis.mock.cache.Cache$.$anonfun$apply$4(Cache.scala:1442)
at uncancelable @ fs2.Pull$.acquireCancelable(Pull.scala:375)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at handleErrorWith @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.handleErrorWith(Compiler.scala:150)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at uncancelable @ fs2.Compiler$TargetLowPriority$MonadCancelTarget.uncancelable(Compiler.scala:158)
at unique @ fs2.Compiler$Target$ConcurrentTarget.unique(Compiler.scala:183)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at of @ kinesis.mock.cache.Cache$.apply(Cache.scala:1436)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152)
at run @ com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
2021-12-07T12:09:23:ERROR:localstack.services.kinesis.kinesis_starter: kinesis terminated with return code 1
2021-12-07T12:09:34:ERROR:localstack.services.kinesis.kinesis_starter: Kinesis health check failed
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 186, in check_kinesis
    wait_for_port_open(PORT_KINESIS_BACKEND, http_path="/", expect_success=False, sleep_time=1)
  File "/opt/code/localstack/localstack/utils/common.py", line 660, in wait_for_port_open
    return wait_for_port_status(
  File "/opt/code/localstack/localstack/utils/common.py", line 693, in wait_for_port_status
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 796, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 792, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 688, in check
    raise Exception(
Exception: Port 39153 (path: /) was not open
```

**Comment by naspeh** [comment] 2021-12-10 14:31
Hm, it's interesting, seems localstack is trying to start Kinesis Mock two times for some reasons
```
2021-12-07T12:09:22:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.aws.provider.kinesis:default = <function kinesis at 0x7f3632646280>)
2021-12-07T12:09:22:DEBUG:plugin.manager: loading plugin localstack.aws.provider:kinesis:default
2021-12-07T12:09:22:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2021-12-07T12:09:22:DEBUG:plugin.manager: loading plugin localstack.aws.provider:kinesis:default
2021-12-07T12:09:22:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2021-12-07T12:09:22:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2021-12-07T12:09:22:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2021-12-07T12:09:23:INFO:localstack.services.infra: Starting mock Kinesis service on http port 4566 ...
2021-12-07T12:09:23:INFO:localstack.services.infra: Starting mock Kinesis service on http port 4566 ...
2021-12-07T12:09:23:DEBUG:localstack.utils.run: Executing command: KINESIS_MOCK_PLAIN_PORT=41623 SHARD_LIMIT=100 CREATE_STREAM_DURATION=500ms DELETE_STREAM_DURATION=500ms REGISTER_STREAM_CONSUMER_DURATION=500ms START_STREAM_ENCRYPTION_DURATION=500ms STOP_STREAM_ENCRYPTION_DURATION=500ms DEREGISTER_STREAM_CONSUMER_DURATION=500ms MERGE_SHARDS_DURATION=500ms SPLIT_SHARD_DURATION=500ms UPDATE_SHARD_COUNT_DURATION=500ms  LOG_LEVEL=INFO  /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static --gc=G1
2021-12-07T12:09:23:DEBUG:localstack.utils.run: Executing command: KINESIS_MOCK_PLAIN_PORT=39153 SHARD_LIMIT=100 CREATE_STREAM_DURATION=500ms DELETE_STREAM_DURATION=500ms REGISTER_STREAM_CONSUMER_DURATION=500ms START_STREAM_ENCRYPTION_DURATION=500ms STOP_STREAM_ENCRYPTION_DURATION=500ms DEREGISTER_STREAM_CONSUMER_DURATION=500ms MERGE_SHARDS_DURATION=500ms SPLIT_SHARD_DURATION=500ms UPDATE_SHARD_COUNT_DURATION=500ms  LOG_LEVEL=INFO  /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static --gc=G1
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,297 [36mk.m.KinesisMockService[0;39m [33mcontextId=83e06db6-5756-11ec-9389-8dd0c1e2629a, cacheConfig={"awsAccountId":"000000000000","awsRegion":"ap-northeast-1","createStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"initializeStreams":null,"mergeShardsDuration":{"length":500,"unit":"MILLISECONDS"},"persistConfig":{"fileName":"kinesis-data.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"data","shouldPersist":false},"registerStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":500,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":500,"unit":"MILLISECONDS"}}[0;39m - Logging Cache Config
[io-compute-2] [34mINFO [0;39m 2021-12-07 12:09:23,301 [36mk.m.KinesisMockService[0;39m [33mcontextId=83e109ef-5756-11ec-9893-5738db6a1e14, cacheConfig={"awsAccountId":"000000000000","awsRegion":"ap-northeast-1","createStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"initializeStreams":null,"mergeShardsDuration":{"length":500,"unit":"MILLISECONDS"},"persistConfig":{"fileName":"kinesis-data.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"data","shouldPersist":false},"registerStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":500,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":500,"unit":"MILLISECONDS"}}[0;39m - Logging Cache Config
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,445 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis TLS Mock Service on port 4567
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,445 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis Plain Mock Service on port 41623
[io-compute-0] [34mINFO [0;39m 2021-12-07 12:09:23,446 [36mk.m.KinesisMockService[0;39m [33mcontextId=83f72a08-5756-11ec-9389-8dd0c1e2629a[0;39m - Not configured to persist data, persist loop not started
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,448 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis TLS Mock Service on port 4567
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,448 [36mk.m.KinesisMockService[0;39m [33m[0;39m - Starting Kinesis Plain Mock Service on port 39153
[io-compute-1] [34mINFO [0;39m 2021-12-07 12:09:23,449 [36mk.m.KinesisMockService[0;39m [33mcontextId=83f79f31-5756-11ec-9893-5738db6a1e14[0;39m - Not configured to persist data, persist loop not started
java.net.BindException: Address in use
```

@thrau do you know what can cause this?

----

@kgston have you tried to run `localstack/localstack:latest` image instead of `localstack/localstack:0.13.0`? Do you still see this error?

**Comment by kgston** [comment] 2021-12-10 15:41
So I just tried both `latest` and `0.13.1` and they both now have an additional SQS regression for me. You can still see the Kinesis issue in `0.13.1` but it does not appear in `latest`. I'm not sure if it just did not even boot due to SQS failing to boot.

I've attached both logs for your reference.

[docker-0.13.1.log](https://github.com/localstack/localstack/files/7693816/docker-0.13.1.log)
[docker-latest.log](https://github.com/localstack/localstack/files/7693818/docker-latest.log)

**Comment by thrau** [comment] 2021-12-10 18:25
> @thrau do you know what can cause this?

those logs look very odd. it looks like services are being started multiple times for some reason, which then causes the bind exceptions. so probably the issue is not related to kinesis but as @kgston suggested it has something to do with this import error.

**Comment by thrau** [comment] 2022-08-06 00:46
Closing this issue die to staleness. Please check whether this still occurs with the latest version of LocalStack and re-open the issue if it still occurs. Thanks!

**Closed by thrau** 2022-08-06 00:46 UTC
Labels: type: bug, status: triage needed, aws:kinesis
