### ISSUE TITLE
S3 Instable - bucket being lost

### ISSUE THREAD

**Issue by vdimikj** [localstack/localstack#1355] opened 2019-06-05 12:17 UTC
Hi Guys,
After trying localstack/s3 service I've experienced that s3 is not stable i.e after creating a bucket and listing that bucket using s3 cli, one out of 10 will fail thus showing that no bucket is created. 

When i run integration tests one or two will fails as either `NoSuchBucket` exception or `The target server failed to respond`
Testing with s3 cli of listing buckets
`aws s3api list-buckets --endpoint=http://localhost:5000`
Same command if previously retuned a bucket which was created.
Now will return an empty bucket list

Refer to image bellow : 
![image](https://user-images.githubusercontent.com/28303714/58955193-87d3dc00-879b-11e9-8a2d-fac78db9fd15.png)

Image from tests execution where one fails - image bellow: 
![image](https://user-images.githubusercontent.com/28303714/58955306-f1ec8100-879b-11e9-9be7-effd07e3f0e4.png)

Java error ->`Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond`

docker-compose

>  localstack:
    ports:
    - "5000:5000"
    environment:
    - SERVICES=s3:5000
    - DEFAULT_REGION=eu-central-1
    - HOSTNAME=localstack-s3
    - DATA_DIR=/tmp/localstack/data
    image: localstack/localstack:latest

S3Client configuration:

> AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                        Config.toString("aws.credentials.key"), Config.toString("aws.credentials.secret")
                )))
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(S3_ENDPOINT, S3_REGION))
                .withPathStyleAccessEnabled(true)
                .build();

More images:
![image](https://user-images.githubusercontent.com/28303714/58955250-bea9f200-879b-11e9-8100-86839d9ab2d3.png)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-101) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2019-12-08 22:53
Thanks for reporting @vdimikj . Are you still experiencing this in the latest version? Having troubles reproducing this issue. I replicated the configuration you posted (including `DATA_DIR`), but seems to be working for me (also tested with 50+ requests):
```
$ (for i in {1..50}; do awslocal s3api list-buckets | grep foobar || echo 'not found'; done)
            "Name": "foobar",
            "Name": "foobar",
            "Name": "foobar",
            "Name": "foobar",
            "Name": "foobar",
            "Name": "foobar",
            "Name": "foobar",
...
```

**Comment by macnev2013** [comment] 2020-12-08 17:23
Thanks for reporting @vdimikj. This issue should be fixed in the `latest` version of `localstack`. I used list-bucket 500 times and it seems to be working fine. Can you please give it a try with latest docker image? Thanks.

**Closed** 2020-12-09 12:00 UTC
Labels: cannot-reproduce, installation, needs-triaging, should-be-fixed
