### ISSUE TITLE
bug: s3.GetObject throws error with applied lifecycle rule

### ISSUE THREAD

**Issue by febluthn** [localstack/localstack#9857] opened 2023-12-12 13:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An unexpected error (python) occurred when calling the GetObject operation

```
An error occurred (InternalError) when calling the GetObject operation (reached max retries: 2): exception while calling s3.GetObject: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/api/core.py", line 160, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/s3/v3/provider.py", line 784, in get_object
    if expiration_header := self._get_expiration_header(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/s3/v3/provider.py", line 376, in _get_expiration_header
    if lifecycle_rule := get_lifecycle_rule_from_object(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/s3/utils.py", line 676, in get_lifecycle_rule_from_object
    if any(
       ^^^^
  File "/opt/code/localstack/localstack/services/s3/utils.py", line 677, in <genexpr>
    _match_lifecycle_filter(key, value, object_key, size, object_tags)
  File "/opt/code/localstack/localstack/services/s3/utils.py", line 696, in _match_lifecycle_filter
    return object_tags.get(filter_value.get("Key")) == filter_value.get("Value")
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

### Expected Behavior

simply get the requested object regardless of any applied lifecylce rule.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`) and Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#!/usr/bin/env bash

shopt -s expand_aliases

rule='
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "ID": "purge_objects_rule",
            "Filter": {
                "Tag": {
                    "Key": "purge",
                    "Value": "true"
                }
            },
            "Status": "Enabled",
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 1
            }
        }
    ]
}
'
sample_file="./sample.file"
echo "${rule}" >> $sample_file

docker run \
  -d --rm -it \
  -p 4566:4566 \
  -p 4510-4559:4510-4559 \
  -e "DEBUG=1" \
  localstack/localstack:3.0.2

sleep 1

export AWS_DEFAULT_OUTPUT=json
export AWS_PAGER=""

alias aws='aws --no-paginate --region=eu-central-1 --endpoint-url=http://localhost:4566'

demo_bucket=demo

aws s3api create-bucket --bucket $demo_bucket --create-bucket-configuration LocationConstraint=eu-central-1
aws s3api put-bucket-lifecycle-configuration --bucket $demo_bucket --lifecycle-configuration "${rule}"

aws s3 cp ./sample.file s3://$demo_bucket/$sample_file

aws s3api get-object --bucket $demo_bucket --key $sample_file output.file

docker kill $(docker ps -q)
```

### Environment

```markdown
- OS: debian bookworm
- LocalStack:3.0.2
```

**Comment by bentsku** [comment] 2023-12-21 23:24
Hello @febluthn and thanks for your report! The issue is now fixed, and the `latest` image should now resolve your issue.
Could you try running `docker pull localstack/localstack:latest` and see if that would solve your issue? Thanks!

**Comment by bentsku** [comment] 2024-01-02 15:24
Closing as this should be fixed. Thanks again for the report!

**Closed by bentsku** 2024-01-02 15:24 UTC
Labels: type: bug, status: resolved/fixed, status: response required, aws:s3

**Comment by febluthn** [comment] 2024-01-03 08:14
Hello and sorry for my late response. I tested `localstack/localstack:latest` and can confirm that the bug is solved. thanks.
