### ISSUE TITLE
"TypeError: string indices must be integers" when a Java Lambda returns

### ISSUE THREAD

**Issue by sohah** [localstack/localstack#7680] opened 2023-02-14 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We get an exception raised due to a type error. The error happens when the java lambda return statement is executed 

### Expected Behavior

I am actually not sure what would be the side effect of this error. I could see on the debugger when that there is some sort of crashing happing on the execution of the return statement.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am using a docker-compose with the below configuration

```
version: '3.0'
services:
  localstack:
    #build: ./localstack
    container_name: localstack
    image: localstack/localstack
    network_mode: bridge
    environment:
      - DEBUG=1
      #- SERVICES=${LOCALSTACK_SERVICES:-ssm,cloudwatch,cloudformation}
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=xxx
#      - LAMBDA_JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5050
#      - LAMBDA_DOCKER_FLAGS=-p 127.0.0.1:5050:5050
    volumes:
      - ./localstack/bootstrap:/opt/bootstrap/
      - ./data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - '4566:4566'
      - '443:443'
      
```

The lambda I try to run is:

```
public class ContractDynamodbHandler implements RequestHandler<S3Event, String> {

    @Override
    public String handleRequest(S3Event event, Context context) {

            return Constants.SUCCESS;

          }
        }

```

The stacktrace I get is:

```
localstack    | 2023-02-12T10:30:14.962 ERROR --- [   asgi_gw_2] localstack.aws.chain       : exception while running response handler
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/aws/chain.py", line 155, in _call_response_handlers
localstack    |     handler(self, self.context, response)
localstack    |   File "/opt/code/localstack/localstack/aws/chain.py", line 212, in __call__
localstack    |     handler(chain, context, response)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/persistence/handlers.py.enc", line 19, in __call__
localstack    |   File "/opt/code/localstack/localstack/services/plugins.py", line 85, in update_state
localstack    |     serializer.update_state(context, request)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/base.py.enc", line 69, in update_state
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/base.py.enc", line 45, in update_state
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/s3/s3_extended.py.enc", line 69, in update_backend_state
localstack    |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/s3/s3_extended.py.enc", line 89, in do_update_backend_state
localstack    | TypeError: string indices must be integers

```

### Environment

```markdown
- OS:Ubuntu 22.04.1 LTS
- LocalStack: latest
```

**Comment by dominikschubert** [comment] 2023-02-14 12:15
Hi @sohah. Could you please share a bit more about the scenario you're running? What does the deployed infrastructure look like?

Ideally please also provide a longer part of the stacktrace so we can get a better idea about what causes the issue you're seeing.

**Comment by sohah** [comment] 2023-02-15 12:16
Hi @dominikschubert ,

I looked into it a little more further. It turns out that the reproducible code I posted above isn't accurate. There was some implicit code that was causing the above error. I am getting this error when I run the code below. In particular, when executing `        s3Client.deleteObjects(dor);`. There is nothing special about my infrastructure. I just have a single bucket, `my-bucket` and a single file inside it. I am using the same docker-compose I posted before. Also, the stack backtrace I posted is the entire stack backtrace for the error. I hope this is useful, but let me know if there is anything that I can help out with, and thanks for looking into it.

```

public class ContractDynamodbHandler implements RequestHandler<S3Event, String> {

  private AmazonS3 s3Client = prepareS3();

  @Override
  public String handleRequest(S3Event event, Context context) {

    List<Bucket> buckets = s3Client.listBuckets();
    for (Bucket bucket : buckets) {
      List<S3ObjectSummary> s3Summaries = s3Client.listObjects(bucket.getName())
          .getObjectSummaries();

      String[] s3Keys = s3Summaries.stream().map(s3Obj -> s3Obj.getKey()).toArray(String[]::new);

      if (s3Keys.length > 0) {
        DeleteObjectsRequest dor = new DeleteObjectsRequest(bucket.getName())
            .withKeys(s3Keys).withQuiet(false);
        s3Client.deleteObjects(dor);
      }
    }
    return "true";

  }

  public static AmazonS3 prepareS3() {
      BasicAWSCredentials awsCredentials = new BasicAWSCredentials("access_key", "secret_key");
      return AmazonS3ClientBuilder.standard()
              .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
              .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(LOCAL_STACK_ENDPOINT, Config.REGION))
              .withPathStyleAccessEnabled(true)
              .build();
  }
}

```

**Comment by dominikschubert** [comment] 2023-02-16 07:09
@sohah Since this might be persistence related, could you please try removing the `DATA_DIR` line from your `docker-compose` file and check if this changes the observed behavior?

**Comment by sohah** [comment] 2023-02-16 09:30
Thanks, @dominikschubert ! that fixed it. I was just debugging a reference to an old bucket that the localstack seems to be trying to find initially but failing to. Now that I have removed the `DATA_DIR` line, I no longer see this problem, nor do I see the type error I reported in this issue. So, I guess you are suggesting for now, to turn off that line for `DATA_DIR` as a workaround for that issue?

By the way, perhaps this is a different problem but I could see `Unable to get DNS result from fallback server 192.168.65.5 for domain analytics.localstack.cloud.: The DNS operation timed out.`, do not really know what is going on with that one, any suggestions or insights?

Many thanks, @dominikschubert. That is great help!

**Comment by dominikschubert** [comment] 2023-02-16 09:35
> By the way, perhaps this is a different problem but I could see Unable to get DNS result from fallback server 192.168.65.5 for domain analytics.localstack.cloud.: The DNS operation timed out., do not really know what is going on with that one, any suggestions or insights?

This seems to be related to your local DNS setup. Failing to resolve `analytics.localstack.cloud` should not affect your normal usage though. The endpoint is simply used by default to send usage statistics like which service is being used, etc.


Regarding the DATA_DIR. You can also delete your local state (seems like you save it in `./data`) and check if that error happens again with persistence enabled. If you can reproduce this somehow we can pick this up and try to provide a fix. For now there is unfortunately not enough information to reproduce.

**Comment by sohah** [comment] 2023-02-16 10:12
Yes, I can see that it is difficult to reproduce the problematic state. 

By the way, deleting `./data' didn't fix the problem for me; I still see the same error. Luckily, I do not need to keep the state, so I can remove the `DATA_DIR`, at least for now.  for now as well as the volumes `- ./data:/var/lib/localstack` , and `"/var/run/docker.sock:/var/run/docker.sock"`, these the right volumes to turn off, right?

**Comment by dominikschubert** [comment] 2023-02-16 11:20
Ok. Since this has for now resolved the issue, I'll close it. Feel free to re-open if you want to tackle the persistence issue at some point.

`"/var/run/docker.sock:/var/run/docker.sock"`` should generally stay in there, since it's needed to spawn containers via localstack.

**Closed by dominikschubert** 2023-02-16 11:20 UTC
Labels: type: bug, status: triage needed, status: response required
