### ISSUE TITLE
Localstack S3 Uploads fail with parse error

### ISSUE THREAD

**Issue by steowens** [localstack/localstack#4146] opened 2021-06-14 22:08 UTC
# Type of request: This is a ...

[* ] bug report
[ ] feature request

# Detailed description
When attempting to upload an image file to localstack S3 with a resigned Put request the server fails with internal logging error: 
2021-06-14T21:59:36:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request PUT http://localhost:4566/kmaas-local-fileshares/ea3ce40c-477d-11e3-80ea-7d49c594634a/strong-old-men-10.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210614T215935Z&X-Amz-SignedHeaders=host&X-Amz-Expires=600&X-Amz-Credential=test%2F20210614%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=4c92f4da850bac3a455300fe0f5d5c0383fd942aaafd607049998e3952fb0299: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 671, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 56, in forward_request
    auth_header = get_auth_string(method, path, headers, data)
  File "/opt/code/localstack/localstack/services/edge.py", line 181, in get_auth_string
    data_components = parse_request_data(method, path, data)
  File "/opt/code/localstack/localstack/utils/common.py", line 833, in parse_request_data
    result = parse_qs(to_str(data or ''))
  File "/opt/code/localstack/localstack/utils/common.py", line 984, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byt
...

## Expected behavior
The file upload succeeds.
...

## Actual behavior
The s3 localstack server fails with no message and a 500 error, but the docker image logs the above logs.
...

# Steps to reproduce
Create a signed put such as: 
    {
	"PUT": {
		"scheme": "http",
		"host": "localhost:4566",
		"filename": "/kmaas-local-fileshares/ea3ce40c-477d-11e3-80ea-7d49c594634a/strong-old-men-10.jpg",
		"query": {
			"X-Amz-Algorithm": "AWS4-HMAC-SHA256",
			"X-Amz-Date": "20210614T215935Z",
			"X-Amz-SignedHeaders": "host",
			"X-Amz-Expires": "600",
			"X-Amz-Credential": "test/20210614/us-east-1/s3/aws4_request",
			"X-Amz-Signature": "4c92f4da850bac3a455300fe0f5d5c0383fd942aaafd607049998e3952fb0299"
		},
		"remote": {
			"Address": "127.0.0.1:4566"
		}
	}
    }

## Command used to start LocalStack
localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
    // Java code to generate signed url
    public String makeThe URL(String bucketName, String s3Key){
      PutObjectRequest objectRequest = null;
		if (StringUtils.isBlank(request.getEncryptionKey())) {
			objectRequest = PutObjectRequest.builder()
					.bucket(bucketName)
					.key(s3Key)
					.build();
		} else {
			objectRequest = PutObjectRequest.builder()
					.bucket(bucketName)
					.key(s3Key)
					.sseCustomerAlgorithm("AES256")
					.sseCustomerKey(request.getEncryptionKey())
					.sseCustomerKeyMD5(request.getEncryptionKeyHash())
					.build();
		}

        PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
                .signatureDuration(Duration.ofMinutes(10))
                .putObjectRequest(objectRequest)
                .build();

        PresignedPutObjectRequest presignedRequest = s3Presigner.presignPutObject(presignRequest);

		return presignedRequest.url().toString();
    }

    // Javascript file upload given signed URL
    async function readFile(file) {
	return new Promise((resolve) => {
		let reader = new FileReader();
		reader.addEventListener("load", () => { resolve(reader.result); });
		reader.readAsArrayBuffer(file);
	});
    }
    export default class RestClient {
    putFileS3 = (s3PutUrl, file) => {
		console.log("New putFileS3");
		let promise = readFile(file);
		let headers = new Headers(); 
		headers.append("Content-Type", "application/octet-stream; charset ascii");
		promise.then((data) => { return fetch(s3PutUrl, { method: "PUT", headers: headers, body: data});},
			 (err) => {console.error("File send failed. " + err.message);});	
		
	}...
    }

**Comment by pinzon** [comment] 2021-06-15 22:13
Hi @steowens, I just tested the presing feature with this [test](https://github.com/localstack/localstack-java-utils/blob/1b79626a4c5892e470a9627d9bcdb2a5d3049124/src/test/java/cloud/localstack/S3FeaturesTest.java#L163) and it works. 

I also modified the test to include the header and the timing. 

So I believe that the problem is that the data is not being correctly send inside your put request.
```java
public void testPresignedURLUpload() throws Exception {
	AmazonS3 s3client = TestUtils.getClientS3();
	Date expiration = new Date(System.currentTimeMillis() + 1000*60*10);
	String bucketName = UUID.randomUUID().toString();
	String keyName = "presign-test-key";
	s3client.createBucket(bucketName);

	GeneratePresignedUrlRequest generatePresignedUrlRequest =
		new GeneratePresignedUrlRequest(bucketName, keyName)
			.withMethod(HttpMethod.PUT)
			.withExpiration(expiration)
			.withKey(keyName);
	URL presignedUrl = s3client.generatePresignedUrl(generatePresignedUrlRequest);

	// upload content
	String content = "test content";
	HttpPut httpPut = new HttpPut(presignedUrl.toString());
	httpPut.setEntity(new StringEntity(content));
	
	
	httpPut.addHeader("Content-Type","application/octet-stream; charset ascii");
	SSLContextBuilder builder = new SSLContextBuilder();
	builder.loadTrustMaterial(null, new TrustSelfSignedStrategy());
	SSLConnectionSocketFactory sslsf = new SSLConnectionSocketFactory(builder.build());
	CloseableHttpClient httpclient = HttpClients.custom().setSSLSocketFactory(sslsf).build();

	httpclient.execute(httpPut);
	httpclient.close();

	// download content
	GetObjectRequest req = new GetObjectRequest(bucketName, keyName);
	S3Object stream = s3client.getObject(req);
	String result = IOUtils.toString(stream.getObjectContent());
	Assert.assertEquals(result, content);
}
```

**Comment by pinzon** [comment] 2021-06-17 19:55
I'll close this issue. Feel free to let me know if you need any more help.

**Closed by pinzon** 2021-06-17 19:55 UTC
