### ISSUE TITLE
bug: S3 service no longer starts up in v0.12.9 and v0.12.10

### ISSUE THREAD

**Issue by acraven** [localstack/localstack#5154] opened 2021-12-20 17:48 UTC
### Current Behavior

I've been using the S3 service with `v0.12.9` for some time now but as of this afternoon it's stopped working. I have some logs from a PR running on our CI server from around 15:00 today where it worked, but the next run triggered by the merge of the PR failed.

I tried running CI of a different repo that uses the same S3 service in `v0.12.9` and that fails too.

I have reproduced the issue with just `docker run` (below).

### Expected Behavior

I expect the S3 service to start up in a timely manner so I can run the AWS CLI against it to create a bucket.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

My use-case is docker-compose, but I have been able to reproduce the same error using `docker run`.

a. v0.12.10 no longer starts S3
`docker run -it -e SERVICES=s3 localstack/localstack:0.12.10`
```
LocalStack version: 0.12.10
LocalStack build date: 2021-04-24
LocalStack build git hash: 9b57e6a9

Starting edge router (https port 4566)...
Starting mock S3 service on http port 4566 ...
2021-12-20T17:36:04:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 4072.9100704193115ms
2021-12-20T17:36:04:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 4073.976993560791ms
2021-12-20T17:36:05:INFO:localstack.multiserver: Starting multi API server process on port 41193
[2021-12-20 17:36:05 +0000] [23] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-12-20T17:36:05:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-12-20 17:36:05 +0000] [23] [INFO] Running on http://0.0.0.0:41193 (CTRL + C to quit)
2021-12-20T17:36:05:INFO:hypercorn.error: Running on http://0.0.0.0:41193 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-12-20T17:36:29:WARNING:localstack.services.plugins: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2021-12-20T17:36:49:WARNING:localstack.services.plugins: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
```

b. v0.12.11  S3 starts successfully
```
LocalStack version: 0.12.11
LocalStack build date: 2021-05-06
LocalStack build git hash: 0728a51c

Starting edge router (https port 4566)...
Starting mock S3 service on http port 4566 ...
2021-12-20T17:44:21:INFO:localstack.multiserver: Starting multi API server process on port 45157
[2021-12-20 17:44:21 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-12-20T17:44:21:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-12-20 17:44:21 +0000] [22] [INFO] Running on http://0.0.0.0:45157 (CTRL + C to quit)
2021-12-20T17:44:21:INFO:hypercorn.error: Running on http://0.0.0.0:45157 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Ready.
```

### Environment

```markdown
- OS: Docker on Windows
- LocalStack: 0.12.9 and 0.12.10 - not a problem in 0.12.11, 0.12.12, 0.12.15 and 0.12.20

I can upgrade to the most recent 0.12.x and not experience the problem but I wanted to capture this issue in case others are facing the same problem.
```

### Anything else?

Looking through the release notes https://github.com/localstack/localstack/releases/tag/v0.12.11 I see there may have been a fix applied "add dynamic DNS check to fix issues with resolving s3.localhost.localstack.cloud".

I'm not sure if the problem is related to this, but I'd be interested to know why it would stop working when it's been running successfully for a number of months.

**Comment by dominikschubert** [comment] 2021-12-20 20:09
The certificate we bundle for *.s3.localhost.localstack.cloud was renewed today and there were some minor issues that should be resolved now. Please try again and let us know if you continue to experience these issues.

Closing this first as its a duplicate of #5152

**Closed by dominikschubert** 2021-12-20 20:09 UTC
Labels: bug, needs-triaging
