### ISSUE TITLE
bug: SNS Subscription Confirmation fails with: InvalidParameter: Token

### ISSUE THREAD

**Issue by dave-mclean** [localstack/localstack#8118] opened 2023-04-12 07:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you perform the SubscriptionConfirmation request after subscribing an HTTP endpoint to an SNS topic localstack responses with:

```
<?xml version='1.0' encoding='utf-8'?>
<ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
    <Error>
        <Code>InvalidParameter</Code>
        <Message>Invalid parameter: Token</Message>
        <Type>Sender</Type>
    </Error>
    <RequestId>WC33COKFDOENIKQE90648TUZNUJFAISR71ZLRPFDAXGN1MTHHX02</RequestId>
</ErrorResponse>%
```

When you subscribe an HTTP endpoint to an SNS Queue you receive a SubscriptionConfirmation message as described in [the docs](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.prepare.html). 

Endpoints should parse the message and extract the SubsbscriptionConfirmationURL, then perform a GET request to that URL to confirm the subscription. 

**In localstack/localstack:1.1.0 this process works well**

The following code is used to create a bucket and a topic and subscribe
```
#! /bin/sh

BUCKET=test-bucket
TOPIC=test-topic
CONFIG_FILE=local/usr/s3-config.json
ENDPOINT=http://webapp:8000/api/process_dataflow

# Create the bucket and topic
awslocal s3api create-bucket --bucket $BUCKET
awslocal sns create-topic --name $TOPIC

# Configure the bucket to notify the topic when an object is created in it.
awslocal s3api put-bucket-notification-configuration --bucket $BUCKET --notification-configuration file://$CONFIG_FILE

# Subscribe the Dataflow processing endpoint to the topic
awslocal sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:$TOPIC --protocol http --notification-endpoint $ENDPOINT
```

After the command to subscribe the endpoint to the topic the endpoint receives an SNS SubscriptionConfirmation message like this:

```
{
    "Message": "You have chosen to subscribe to the topic arn:aws:sns:us-east-1:000000000000:test-topic.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
    "MessageId": "fd13c8a3-9e86-4c93-8d1d-4557aea236a3",
    "Signature": "EXAMPLEpH+..",
    "SignatureVersion": "1",
    "SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem",
    "SubscribeURL": "http://localhost:4566/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-east-1:000000000000:test-topic&Token=b2e114b1",
    "Timestamp": "2023-04-12T07:16:55.800Z",
    "Token": "b2e114b1",
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:test-topic",
    "Type": "SubscriptionConfirmation"
}
```

and when I make a request to the given `SubscribeURL` the request succeeds although the content does seem quite strange and claims to come from `http://s3.amazonaws.com`....

```
CONTENT

b'<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets><Bucket><Name>test-bucket</Name><CreationDate>2023-04-12T07:16:54.000Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>'
```

```
STATUS_CODE

200
```

This "success" is shown in the localstack logs as a successful call to `ListBuckets`

```
flux-s3            | 2023-04-12T07:16:57.192  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListBuckets => 200
```

**In localstack/localstack:2.0.1 this process fails**

The SubscriptionConfirmation message is identical (apart from the tokens and timestamps):
```
{
    "Message": "You have chosen to subscribe to the topic arn:aws:sns:us-east-1:000000000000:test-topic.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
    "MessageId": "fa1eb360-8fe4-4a47-be0a-bc0e223f413f",
    "Signature": "EXAMPLEpH+..",
    "SignatureVersion": "1",
    "SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem",
    "SubscribeURL": "http://localhost:4566/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-east-1:000000000000:test-topic&Token=7bbbf53b",
    "Timestamp": "2023-04-12T07:26:38.555Z",
    "Token": "7bbbf53b",
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:test-topic",
    "Type": "SubscriptionConfirmation"
}
```

But a get request to the `SubscribeURL` fails:
```
CONTENT

b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/"><Error><Code>InvalidParameter</Code><Message>Invalid parameter: Token</Message><Type>Sender</Type></Error><RequestId>VWNS74HBW8GXDI435DNGPRTO7JO371XH47CZNK3YHHEYNTCFFMC9</RequestId></ErrorResponse>'
```

```
STATUS_CODE

400
```

This failure is seem in the localstack logs:

```
flux-s3            | 2023-04-12T07:26:39.947  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sns.ConfirmSubscription => 400 (InvalidParameter)
```

### Expected Behavior

When you perform the SubscriptionConfirmation request after subscribing an HTTP endpoint to an SNS topic localstack responses with: 

```
200, ok
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
# docker-compose.yml

  s3:
    image: localstack/localstack:2.0.1
    container_name: flux-s3
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI:-8080}:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=./local/s3/
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    volumes:
      - "./local/localstack:/var/lib/localstack"
    hostname: s3
```

```
$ docker compose up s3 webapp
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#! /bin/sh

BUCKET=test-bucket
TOPIC=test-topic
CONFIG_FILE=local/usr/s3-config.json
ENDPOINT=http://webapp:8000/api/process_dataflow

# Create the bucket and topic
awslocal s3api create-bucket --bucket $BUCKET
awslocal sns create-topic --name $TOPIC

# Configure the bucket to notify the topic when an object is created in it.
awslocal s3api put-bucket-notification-configuration --bucket $BUCKET --notification-configuration file://$CONFIG_FILE

# Subscribe the Dataflow processing endpoint to the topic
awslocal sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:$TOPIC --protocol http --notification-endpoint $ENDPOINT
```

### Environment

```markdown
- OS: MacOS
- LocalStack: anything after 1.1.0 fails
```

### Anything else?

My endpoint successful confirms it's subscription in real AWS so I believe that this is a bug in localstack.

**Comment by bentsku** [comment] 2023-04-12 23:21
Hello @dave-mclean and thanks for your report!

I think I could spot where the issue lies. The weird S3 response from 1.1 is a bit suspicious, and with the sample you gave I couldn't reproduce the issue with 2.0.1.

I think the issue is about the region. I'll try to work on a fix and link the PR here. In the meantime, would it be possible to give us the logs with `DEBUG=1` and `LS_LOG=trace`? We could get more informations on the incoming request. Thanks!

**Comment by dave-mclean** [comment] 2023-04-13 11:56
hello @bentsku - thanks very much for the rapid response!

**Comment by bentsku** [comment] 2023-04-18 20:37
I'll close the issue, the fix is now part of the `latest` docker image, and will then be part of the `2.1` next release. Thanks again for the report!

**Closed by bentsku** 2023-04-18 20:37 UTC
Labels: type: bug, aws:sns, status: confirmed
