### ISSUE TITLE
bug: SSM Put parameter error in latest Local stack image

### ISSUE THREAD

**Issue by bajajyog** [localstack/localstack#8360] opened 2023-05-24 00:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This error is coming in localstack latest image. It is working fine in Local stack 1.4.0 image.

2023-05-24T00:27:28.953  INFO --- [   asgi_gw_0] l.aws.handlers.service     : API for service 'ssm' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
2023-05-24T00:27:28.953  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ssm.PutParameter => 501 (InternalFailure)

### Expected Behavior

SSM Put operation should work fine in latest local stack image

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Localstack test container is started from junit test  

(LocalStackTestContainer) new LocalStackTestContainer()
                            .withServices(Service.LAMBDA,
                                     Service.SQS,
                                     Service.S3,
                                     Service.IAM,
                                     Service.API_GATEWAY,
                                     Service.CLOUDWATCH,
                                     Service.CLOUDWATCHLOGS,
                                     Service.SSM)
                            .withNetwork(Network.SHARED)
                            .withNetworkAliases(localstackNetworkAlias)
                              .withEnv("SERVICES", "events")
                             .withEnv("LAMBDA_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
                        
                            .withEnv("AWS_ACCESS_KEY_ID", "abc")
                            .withEnv("AWS_SECRET_ACCESS_KEY", "abc")
                       
            ;

### Environment

```markdown
- OS:MAC
- LocalStack:latest
```

**Comment by bajajyog** [comment] 2023-05-24 18:49
As per localstack coverage document,  SSM put parameter is available in community edition. Why in latest local stack image, we are getting error this feature is available only in pro.

**Comment by bajajyog** [comment] 2023-05-25 15:42
I learned from loaclstack team that JDK 17 support is available in latest localstack. Please provide updates for this issue whether I am doing some thing wrong or latest image ssm PUT parameter will not be available

**Comment by bajajyog** [comment] 2023-05-26 14:05
Any updates for this issue

**Comment by bajajyog** [comment] 2023-05-30 13:53
Please provide updates.

**Comment by bajajyog** [comment] 2023-06-05 17:38
My requirement is to have jave 17 runtime support for lambda in localstack. Please advise, if with localstack 1.4.x docker image, this is possible. In that case I can keep on working on Localstack 1.4.0 image and do not switch to latest local stack image.

**Comment by thrau** [comment] 2023-06-19 21:10
hello @bajajyog , thanks for reporting. Could you please provide more detailed instructions on how to reproduce the issue? Ideally with specific aws cli commands or relevant snippets from your code. `ssm.PutParameter` should definitely work, so something else may not be working or configured correctly, but we cannot say with the limited information in the issue report. Thanks!

**Comment by steffyP** [comment] 2023-07-03 17:08
Hi @bajajyog, 

thanks for providing the snippet 🙏 
So far I am not able to reproduce your issue though. 

I have installed Java Version 17 `jdk-17.0.7+7` and using the testcontainers `1.18.3`
```
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>localstack</artifactId>
            <version>1.18.3</version>
            <scope>test</scope>
        </dependency>
```

I modified your code slightly, but here is how my Test class looks like:
```
public class TestSSM {

    private DockerImageName localstackImage = DockerImageName.parse("localstack/localstack:latest");
    private String localstackNetworkAlias = "my-localstack-network";

    @Rule
    public LocalStackContainer localstack = new LocalStackContainer(localstackImage)
            .withServices(LocalStackContainer.Service.LAMBDA,
                    LocalStackContainer.Service.SQS,
                    LocalStackContainer.Service.S3,
                    LocalStackContainer.Service.IAM,
                    LocalStackContainer.Service.API_GATEWAY,
                    LocalStackContainer.Service.CLOUDWATCH,
                    LocalStackContainer.Service.CLOUDWATCHLOGS,
                    LocalStackContainer.EnabledService.named("events"),
                    LocalStackContainer.Service.SSM)
            .withNetwork(Network.SHARED)
            .withNetworkAliases(localstackNetworkAlias)
            .withEnv("LAMBDA_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
            .withEnv("SQS_DOCKER_NETWORK", ((Network.NetworkImpl) Network.SHARED).getName())
            .withEnv("AWS_ACCESS_KEY_ID", "access-key")
            .withEnv("AWS_SECRET_ACCESS_KEY", "secret-key")
            .withEnv("AWS_SESSION_TOKEN", "session-key")
            .withCommand("sh", "-c", "tail -f /dev/null");

    @Test
    public void testSSM() throws IOException, InterruptedException {
        final Container.ExecResult result = localstack.execInContainer("awslocal", "ssm", "put-parameter", "--name", "myparam", "--value", "myvalue",
                "--type", "String");

        System.out.println("container error logs: " + result.getStderr());

        System.out.println("container out logs: " + result.getStdout());
    }
}

```

When I run this test, the output is:
``` 
container error logs: 
container out logs: {
    "Version": 1
}
```

Here are the logs from the localstack container:
```
LocalStack version: 2.1.1.dev
LocalStack Docker container id: d8ab85f17b30
LocalStack build date: 2023-07-03
LocalStack build git hash: b4cfd0f3
2023-07-03T17:05:31.580  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-07-03T17:05:31.580  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-07-03T17:05:31.874  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 608.60ms
Ready.
2023-07-03T17:05:36.086  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 825.50ms
2023-07-03T17:05:36.087  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 826.79ms
2023-07-03T17:05:36.933  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ssm.PutParameter => 200
```

Could you please try to pull the `latest` image manually, to make sure you are really using the latest? E.g.:
`docker pull localstack/localstack:latest`

Can you please make sure you are using the latest `testcontainers` version, and give it another go with the sample I provided? 🙏

**Comment by bajajyog** [comment] 2023-07-06 03:37
Thanks for your test case. I am having custom docker file to install certificates for local stack as SSL verifier error is coming my company network while running local stack component test. I used the latest docker image in my test instead of docker file image, SSM error not coming. Looks some issue due to certficates  in docker file.I am debugging this. If required , I will share my docker file with you. Thanks a great for your test case and help.

**Comment by steffyP** [comment] 2023-07-06 07:46
Thanks for testing and clarifying that your issues are related to a special setup @bajajyog 🙏 

As the SSM parameter feature works in LocalStack in general, we will close this ticket.

**Closed by steffyP** 2023-07-06 07:46 UTC
Labels: type: bug, aws:ssm
