### ISSUE TITLE
Can't deploy to localstack, proxy error

### ISSUE THREAD

**Issue by seunlanlege** [localstack/localstack#1199] opened 2019-03-16 10:11 UTC
`docker-compose.yml`
```
version: '3'
services:
  ...
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
...
```

`serverless.yml`
```

stage: local
region: us-east-1
plugins:
  - serverless-plugin-typescript
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs8.10
 
custom:
  localstack:
    host: http://localhost
    stages:
      # list of stages for which the plugin should be enabled
      - local
  lambda:
      # Enable this flag to improve performance
      mountCode: True

functions:
  hello:
    handler: src/resolvers/index.hello
  graphql:
    handler: src/resolvers/index.server
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: src/resolvers/index.playground
    events:
    - http:
        path: /playground
        method: get
        cors: true
  verifyTransaction:
    handler: src/resolvers/index.verifyTransaction
    events:
    - http:
        path: /transaction/verify
        method: post
        cors: true
  pusherAuth:
    handler: src/resolvers/index.pusherAuth
    events:
    - http:
        path: /pusher/auth
        method: post
        cors: true
  consumer:
    handler: src/resolvers/index.consumer
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"
```

logs

```
Waiting for all LocalStack services to be ready
2019-03-16 09:59:29,779 INFO Set uid to user 0 succeeded
2019-03-16 09:59:29,783 INFO supervisord started with pid 10
2019-03-16 09:59:30,786 INFO spawned: 'dashboard' with pid 17
2019-03-16 09:59:30,788 INFO spawned: 'infra' with pid 18
(. .venv/bin/activate; bin/localstack web)
2019-03-16 09:59:30,811 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start)
2019-03-16 09:59:31,813 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
2019-03-16T09:59:35:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2019-03-16T09:59:35:INFO:werkzeug:  * Restarting with stat
Starting local dev environment. CTRL-C to quit.
Starting mock SES (http port 4579)...
Starting mock CloudWatch Logs (http port 4586)...
Starting mock Redshift (http port 4577)...
Starting mock CloudFormation (http port 4581)...
Starting mock Firehose service (http port 4573)...
 * Serving Flask app "firehose_api" (lazy loading)
Starting mock Route53 (http port 4580)...
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Starting mock ES service (http port 4578)...
 * Serving Flask app "es_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
Starting mock IAM (http port 4593)...
   Use a production WSGI server instead.
 * Debug mode: off
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock S3 (http port 4572)...
 * Serving Flask app "ddb_streams_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Starting mock CloudWatch (http port 4582)...
Starting mock DynamoDB (http port 4569)...
Starting mock Kinesis (http port 4568)...
Starting mock SQS (http port 4576)...
Starting mock SSM (http port 4583)...
Starting mock SNS (http port 4575)...
Starting mock API Gateway (http port 4567)...
Starting mock Secrets Manager (http port 4584)...
Starting local Elasticsearch (http port 4571)...
Waiting for all LocalStack services to be ready
Starting mock STS (http port 4592)...
Starting mock StepFunctions (http port 4585)...
Starting mock Lambda service (http port 4574)...
 * Serving Flask app "lambda_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Waiting for all LocalStack services to be ready
2019-03-16T09:59:48:WARNING:werkzeug:  * Debugger is active!
2019-03-16T09:59:48:INFO:werkzeug:  * Debugger PIN: 237-647-138
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Ready.
2019-03-16T10:03:55:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', error(104, 'Connection reset by peer')) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

[output trimmed by whummer]
...

2019-03-16T10:04:09:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', error(104, 'Connection reset by peer')) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2019-03-16T10:04:10:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', error(104, 'Connection reset by peer')) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2019-03-16T10:04:10:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', error(104, 'Connection reset by peer')) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2019-03-16T10:04:11:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', error(104, 'Connection reset by peer')) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

2019-03-16T10:04:11:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', error(104, 'Connection reset by peer')) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by whummer** [comment] 2019-03-17 16:54
Thanks for reporting @seunlanlege . I'm unable to reproduce this issue. One potential problem is that the LocalStack services take some time to start up - up to 15-20 seconds, depending on the of your machine.

You should see something like this:
```
$ docker-compose up
Creating tmp_localstack_1 ... done
Attaching to tmp_localstack_1
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-16 20:43:58,255 INFO Set uid to user 0 succeeded
localstack_1  | 2019-03-16 20:43:58,261 INFO supervisord started with pid 11
localstack_1  | 2019-03-16 20:43:59,270 INFO spawned: 'dashboard' with pid 18
localstack_1  | 2019-03-16 20:43:59,274 INFO spawned: 'infra' with pid 19
...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Ready.
```

Can you please share a few details about your environment - operating system, Docker version, etc.

**Comment by seunlanlege** [comment] 2019-03-18 08:29
Ubuntu 18.04
Docker version 18.09.2, build 6247962
i have 16gb allocated to docker/and 100% cpu

**Comment by whummer** [comment] 2019-11-27 23:29
Closing as "unable to reproduce". The solution to this issue should be to customize the `SERVICES` configuration variable, and leave out memory-hungry APIs that may not be required (e.g., Elasticsearch). Thanks

**Closed by whummer** 2019-11-27 23:29 UTC
Labels: bug, installation, needs-triaging, performance
