### ISSUE TITLE
Unable to find forwarding rule for host "localhost:4566", path "POST /", target header "secretsmanager.GetSecretValue"

### ISSUE THREAD

**Issue by AdamSLevy** [localstack/localstack#3819] opened 2021-04-01 21:04 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am running the latest version of localstack 0.12.9 and I'm getting the following error when using the AWS golang API to call GetSecretValue.
```
2021-04-01T20:45:15:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "POST /", target header "secretsmanager.GetSecretValue", auth header "", data "b'{"SecretId":"REDACTED"}'"
```

## Expected behavior

GetSecretValue should return successfully.

## Actual behavior

HTTP status code 404

# Steps to reproduce

## Command used to start LocalStack

docker-compose snippet
```
  localstack:
    image: localstack/localstack:0.12.9
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,secretsmanager,route53,acm-pca,s3,kms
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./local-dev/localstack:/docker-entrypoint-initaws.d
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```
```
docker-compose up -d localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
	secretOutput, err := s.smClient.GetSecretValue(&secretsmanager.GetSecretValueInput{
		SecretId: aws.String(secretID),
	})
```

where `s.smClient` is a `github.com/aws/aws-sdk-go/service/secretsmanager/secretsmanageriface.SecretsManagerAPI` with `github.com/aws/aws-sdk-go v1.32.8`.

Note that this same API succeeds when using the awslocal CLI.

**Comment by mgagliardo** [comment] 2021-04-04 20:27
Hello @AdamSLevy, could you please show the fullcode you are using for this? I am running the following with no issues.

Create the secret:
```
awslocal secretsmanager create-secret --name test2 --secret-string test2
```

main.go:
```
package main

import (
  "fmt"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/secretsmanager"
)

var (
	secretName   string = "test2"
        endpoint     string = "http://localhost:4566"
	region       string = "us-east-1"
)

func main() {
	svc := secretsmanager.New(
		session.New(),
		aws.NewConfig().WithEndpoint(endpoint).WithRegion(region),
	)

	input := &secretsmanager.GetSecretValueInput{
		SecretId:     aws.String(secretName),
	}

	result, err := svc.GetSecretValue(input)
	if err != nil {
		panic(err.Error())
	}
  fmt.Printf("%+v", result)
}
```

output:
```
$ go run main.go 
{
  ARN: "arn:aws:secretsmanager:us-east-1:000000000000:secret:test2-CdoHC",
  CreatedDate: 2021-04-04 20:23:18 +0000 UTC,
  Name: "test2",
  SecretString: "test2",
  VersionId: "4462cfcd-1507-40b8-877e-b32218605ba1",
  VersionStages: ["AWSCURRENT"]
}
```

Which is exactly the same as the awscli output:

```
awslocal secretsmanager list-secrets --output=json
{
    "SecretList": [
        {
            "ARN": "arn:aws:secretsmanager:us-east-1:000000000000:secret:test2-CdoHC",
            "Name": "test2",
            "Description": "",
            "KmsKeyId": "",
            "RotationEnabled": false,
            "RotationLambdaARN": "",
            "RotationRules": {
                "AutomaticallyAfterDays": 0
            },
            "Tags": [],
            "SecretVersionsToStages": {
                "4462cfcd-1507-40b8-877e-b32218605ba1": [
                    "AWSCURRENT"
                ]
            }
        }
    ]
}
```

**Comment by AdamSLevy** [comment] 2021-04-04 20:30
Thank you. I'll dig in and figure out where the implementations differ and report back this week.

**Comment by mgagliardo** [comment] 2021-04-04 20:47
Sure thing, one side comment, I have also tested this out with a binary secret and no issues with it, example below:

```
echo 'hello world' | base64 > test.binary
awslocal secretsmanager create-secret --name test --secret-binary file://test.binary
```

```
$ awslocal secretsmanager get-secret-value --secret-id test --output=json
{
    "ARN": "arn:aws:secretsmanager:us-east-1:000000000000:secret:test-puccP",
    "Name": "test",
    "VersionId": "7f11f8c2-4e3e-4b79-93dc-615d572ca084",
    "SecretBinary": "aGVsbG8gd29ybGQK",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2021-04-04T22:44:25+02:00"
}
```


output
```
$ go run main.go
{
  ARN: "arn:aws:secretsmanager:us-east-1:000000000000:secret:test-puccP",
  CreatedDate: 2021-04-04 20:44:25 +0000 UTC,
  Name: "test",
  SecretBinary: <binary> len 12,
  VersionId: "7f11f8c2-4e3e-4b79-93dc-615d572ca084",
  VersionStages: ["AWSCURRENT"]
}
```

In any case I'll wait for your response. Cheers.

**Comment by AdamSLevy** [comment] 2021-04-05 02:26
Did you use the same version tag for the aws go sdk?

**Comment by mgagliardo** [comment] 2021-04-05 17:15
> Did you use the same version tag in your go.mod file for the aws go sdk?

No, I am using `v1.38.12` which is the latest but bugfix so backward compatible version, so you should be able to upgrade and use it as well I guess.

**Comment by mgagliardo** [comment] 2021-04-05 17:54
Just a small edit, I have check'd out to `v1.32.8` and no issues, both with plaintext string and base64 encoded. I am closing this as I could not reproduce this with both latest and the same version you are pointing to. Feel free to comment out. Cheers

**Closed by mgagliardo** 2021-04-05 17:54 UTC
Labels: awaiting reporter response, cannot-reproduce
