### ISSUE TITLE
Support for deployment through AWS-CDK

### ISSUE THREAD

**Issue by MathiasKoch** [localstack/localstack#1557] opened 2019-09-11 06:23 UTC
Hi guys.

Any plans to add some way of supporting deployment to a localstack through AWS-CDK, now that it is considered stable? 

I am not sure if this would be a task for localstack, or if it would be a task for aws-cdk to add a way of setting endpoint to localhost?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-117) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2019-12-18 22:27
Thanks for reporting @MathiasKoch . If this is currently not supported in aws-cdk, I'd assume it shouldn't be too hard to add a config to specify the API endpoints.

Do you think you could pick this up and contribute a small pull request against CDK? That would be awesome, thanks!

Side note: As a workaround, I've also seen projects where people use `cdk synth` to generate a CloudFormation template from CDK sources, in order to then deploy this template using regular AWS CLI or SDK tools. This approach could also be used easily with LocalStack. However, the direct integration with CDK would of course be much more elegant and useful.

**Comment by MathiasKoch** [comment] 2019-12-19 09:21
Hi @whummer 

Actually i did the PR a while back, it's just not merged yet (https://github.com/aws/aws-cdk/pull/4200) 

But i think other than the CDK PR being merged, the main issue is the general lack of changeset support in localstack, as CDK uses changesets for everything, opposite to eg. serverless framework, that updates the stack directly.

**Comment by whummer** [comment] 2019-12-19 19:10
@MathiasKoch  Oh, that's great! Looks like there are still a few comments in the PR - would be great if we can work towards getting it merged. I'm very interested in getting the integration with CDK to work. We'll be happy to contribute the required features to get CF changesets working.

**Comment by MathiasKoch** [comment] 2019-12-20 07:51
@whummer 
Alright, i will try to address their comments asap, so we can get it merged. I am also very interested in making it work fully with CDK, and I also had a somewhat working version, but i ended up giving up, as it was very unmanageable with the way localstack patches all its dependencies, and never seems to push them upstream.

**Comment by marcindulak** [comment] 2020-03-05 22:36
@whummer https://github.com/aws/aws-cdk/pull/4200 got stale - help is needed to move it forward.

**Comment by 486** [comment] 2020-04-01 08:57
I am also very interested in this. But, skimming the code, it looks to me like we'd also need a cloudformation mock that actually creates mock services according to the submitted template? Or am I missing something?

**Comment by franz-see** [comment] 2020-06-04 23:58
Has anybody tried this? https://stackoverflow.com/questions/58539338/local-development-with-the-aws-cdk#answer-59000654

**Comment by marcindulak** [comment] 2020-06-05 00:16
> Has anybody tried this? https://stackoverflow.com/questions/58539338/local-development-with-the-aws-cdk#answer-59000654

Yes. The goal of the issue is to not have to go through the explicit, intermediate cloudformation template.

**Comment by franz-see** [comment] 2020-06-05 00:20
Cool. At least there's a workaround. thanks! :)

**Comment by kritulrathod** [comment] 2020-09-23 13:11
**Build ASP.NET code on the Build Server without installing VS**
[https://stackoverflow.com/questions/12944502/build-asp-net-4-5-without-visual-studio-on-build-server](https://stackoverflow.com/questions/12944502/build-asp-net-4-5-without-visual-studio-on-build-server)

**Using MS Tests on Build Server without installing VS**
[https://stackoverflow.com/questions/3402899/can-i-use-mstest-exe-without-installing-visual-studio](https://stackoverflow.com/questions/3402899/can-i-use-mstest-exe-without-installing-visual-studio)

**Comment by whummer** [comment] 2020-09-23 14:43
Thanks for the updates @MathiasKoch @marcindulak @franz-see . We have recently launched a small wrapper script `cdklocal` which should simplify the process of deploying CDK applications locally: https://github.com/localstack/aws-cdk Any feedback welcome - thanks!

**Comment by mdere** [comment] 2021-01-24 17:16
@whummer  I am having issues getting apigateway working with this - just want to make sure it isn't my end.

**Comment by whummer** [comment] 2021-01-25 20:11
Thanks @mdere - the issue you're facing is probably unrelated to `cdklocal`, but rather a CloudFormation deployment issue. (discussion to be continued on Slack...) Thanks

**Closed by whummer** 2021-01-25 20:11 UTC
Labels: cloudformation, enhancement, should-be-fixed, upstream-issue
