### ISSUE TITLE
Underscore is removed in Dynamodb query

### ISSUE THREAD

**Issue by gustavotemple** [localstack/localstack#3156] opened 2020-10-22 18:42 UTC
# Type of request: This is a ...
* [x] bug report

# Detailed description
There is some "replace" that removes all underscores at the end in Dynamodb queries. Maybe this issue is related to this one: https://github.com/localstack/localstack/issues/459

## Expected behavior (AWS)
With database SK values:
Foo_Bar_1_2_3
Foo_Bar_1_20_30
Foo_Bar_10_20_30
Foo_Bar_10_2_3

Query results:
Foo_Bar_1 → OK, return all, works fine
Foo_Bar_1_ → OK, return Foo_Bar_1_2_3 and Foo_Bar_1_20_30
Foo_Bar_1____ → OK, return nothing

## Actual behavior (LocalStack)
With database SK values:
Foo_Bar_1_2_3
Foo_Bar_1_20_30
Foo_Bar_10_20_30
Foo_Bar_10_2_3

Query results:
Foo_Bar_1 → OK, return all, works fine
Foo_Bar_1_ → NOK, return all, ignores the underscore
Foo_Bar_1____ → NOK, return all, ignores underscores

# Steps to reproduce
## Command used to start LocalStack
```shell
docker-compose down -v --remove-orphans && docker-compose up
```

with the https://github.com/localstack/localstack/blob/master/docker-compose.yml

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```javascript
  const params = {
    TableName: 'Table',
    KeyConditionExpression: '#p = :p And begins_with(#s, :s)',
    ExpressionAttributeValues: {
      ':p': pk,
      ':s': sk
    },
    ExpressionAttributeNames: {
      '#p': 'PK',
      '#s': 'SK'
    },
  };

  const data = await dynamoDb.query(params).promise();
```

Or:

```javascript
dynamoose.model('Table', Schema)
    .query({ PK: { eq: pk }, SK: { beginsWith: sk } })
    .exec();
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-300) by [Unito](https://www.unito.io/learn-more)

**Comment by irahulranjan** [comment] 2020-12-14 20:37
Hi @gustavotemple .
Can you share more details for the issue as I am unable to reproduce the issue with the above-given steps?
aws cli used:
```
aws dynamodb create-table --cli-input-json file://table_input.json --endpoint-url=http://localhost:4566
aws dynamodb batch-write-item --request-items 'file://data.json' --endpoint-url=http://localhost:4566
aws dynamodb query --table-name MusicCollection --key-condition-expression "Artist= :pk and begins_with(SongTitle, :sk)"  --expression-attribute-values '{":pk":{"S":"1"},":sk":{"S":"Foo_Bar_1_"}}' --endpoint-url=http://localhost:4566
```
table_input.json
```
{
    "TableName": "MusicCollection",
    "KeySchema": [
      { "AttributeName": "Artist", "KeyType": "HASH" },
      { "AttributeName": "SongTitle", "KeyType": "RANGE" }
    ],
    "AttributeDefinitions": [
      { "AttributeName": "Artist", "AttributeType": "S" },
      { "AttributeName": "SongTitle", "AttributeType": "S" }
    ],
    "ProvisionedThroughput": {
      "ReadCapacityUnits": 5,
      "WriteCapacityUnits": 5
    }
}
```

data.json
```
{
    "MusicCollection": [
        {
            "PutRequest": {
                "Item": {
                    "Artist": {
                        "S": "1"
                    },
                    "SongTitle": {
                        "S": "Foo_Bar_1_2_3"
                    }
                }
            }
        },
        {
            "PutRequest": {
                "Item": {
                    "Artist": {
                        "S": "1"
                    },
                    "SongTitle": {
                        "S": "Foo_Bar_1_20_30"
                    }
                }
            }
        },
        {
            "PutRequest": {
                "Item": {
                    "Artist": {
                        "S": "1"
                    },
                    "SongTitle": {
                        "S": "Foo_Bar_10_20_30"
                    }
                }
            }
        },
        {
            "PutRequest": {
                "Item": {
                    "Artist": {
                        "S": "1"
                    },
                    "SongTitle": {
                        "S": "Foo_Bar_10_2_3"
                    }
                }
            }
        }
    ]
}
```

**Comment by gustavotemple** [comment] 2020-12-16 12:01
@irahulranjan, your test is perfectly right, maybe the problem is in the library below? I use it with nodejs/npm
```javascript
"dependencies": {
    "aws-sdk": "2.803.0",
```

**Comment by gustavotemple** [comment] 2020-12-16 12:28
@irahulranjan, your test is perfectly right, maybe the problem is in the library below? I use it with nodejs/npm
```javascript
"dependencies": {
    "aws-sdk": "2.803.0",
```

In production we use ECS + Fargate, and in development we use Ubuntu + LocalStack

**Comment by irahulranjan** [comment] 2020-12-16 16:04
@gustavotemple If you could share the source code, it would be very helpfull.

**Comment by whummer** [comment] 2021-01-31 00:40
Thanks for the update @gustavotemple @irahulranjan . This appears to have been a bug in the underlying DynamoDB Local implementation - see here: https://forums.aws.amazon.com/thread.jspa?threadID=303035

The issue should now be fixed in the `latest` Docker image. Please report here if the problem persists. Thanks

**Closed by whummer** 2021-01-31 00:40 UTC
Labels: awaiting reporter response, cannot-reproduce, evaluate-or-close
