### ISSUE TITLE
ClassNotFoundException for java handler for aws lambda on invoking lambda function

### ISSUE THREAD

**Issue by codeKgu** [localstack/localstack#865] opened 2018-07-24 18:30 UTC
This is what I used to start up localstack. `SERVICES=lambda:4569 TMPDIR=/private$TMPDIR docker-compose up` from downloading the repository. I have also tried the pip install way and have gotten the same error. 

This is the output of ` jar -tf dbupdater-aws-lambda-1.0-SNAPSHOT.jar | grep RuleUpdater `

```
com/ticketmaster/resale/dynamicfees/converter/RuleUpdater.class
com/ticketmaster/resale/dynamicfees/converter/RuleUpdater$Progress.class
```

This is the error from invoking lambda: ` aws --endpoint-url=http://localhost:4569 lambda invoke --function-name "lambda-attempt" result.log`

```

An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.ClassNotFoundException: com.ticketmaster.resale.dynamicfees.converter.RuleUpdater::handleRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:137)
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:52)
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 269, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 136, in execute
    result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 69, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.ClassNotFoundException: com.ticketmaster.resale.dynamicfees.converter.RuleUpdater::handleRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:137)
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:52)
```

Any help would be appreciated. Thanks!

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-312) by [Unito](https://www.unito.io/learn-more)

**Comment by meriouma** [comment] 2018-10-04 16:00
I've just encountered the same problem. It seems localstack doesn't support the syntax `package.class::methodHandler` as a valid handler definition (see [source](https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java#L137)). Moreover, it seems the handler will *only* be called if the class extends `RequestHandler` or `RequestStreamHandler` ([source](https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LambdaExecutor.java#L99))

**Comment by ladams81** [comment] 2018-10-26 12:17
Hi @meriouma did you overcome this issue as i seem to get the same even though my class does extend RequestHandler. This lambda works fine on AWS but I get this when trying to invoke it locally via localstack

i upload lambda using

`
aws --endpoint-url=http://localhost:4574 lambda create-function --function-name=f2 --runtime=java8 --role=r1 --handler=lambda.handler --zip-file fileb://my-lambda-0.1.0-1540476215-64df908.zip
`

I then tried to call it using the following:

`
aws lambda --endpoint-url=http://localhost:4574 invoke --function-name f2 --region eu-west-1 --payload {\"store\":\"9722\"\,\"pos\":\"80\"\,\"app\":\"price\"} out.txt
`

And i get the following error

An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.ClassNotFoundException: lambda.handler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:137)
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:52)
 Traceback (most recent call last):
  File "/Users/macintosh/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_api.py", line 259, in run_lambda
    event, context=context, version=version, async=async)
  File "/Users/macintosh/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 462, in execute
    process.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/macintosh/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 458, in do_execute
    result = lambda_function(event, context)
  File "/Users/macintosh/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_api.py", line 369, in execute
    event, context, handler=handler, main_file=main_file)
  File "/Users/macintosh/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 483, in execute_java_lambda
    result, log_output = self.run_lambda_executor(cmd, async=async)
  File "/Users/macintosh/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 69, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.ClassNotFoundException: lambda.handler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:137)
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:52)

Can someone give me some pointers as resolve ClassNotFoundException pls?

**Comment by ladams81** [comment] 2018-10-26 13:55
I have whittled my problem down to my lambda not being able to pick up its dependencies locally via localstack even though they are present in the jars situated in the top level lib directory of the uploaded zip file.

**Comment by Ghilteras** [comment] 2019-05-21 20:55
Have the same issue here, it's like the jar I upload to localstack is not considered and the classes are not searched there, but using the localstack-utils java module

**Comment by animate-object** [comment] 2019-11-20 15:08
Seeing the same issue here -- was anyone able to find a reasonable workaround while we wait for a fix?

**Comment by whummer** [comment] 2019-12-02 09:57
Thanks for reporting @codeKgu @meriouma @ladams81 @Ghilteras @animate-object . The Java Lambda executor has been significantly reworked recently (a set of PRs in the last couple of days). 

Can you please give it a try with the latest version (after `docker pull localstack/localstack`).

If the problem still persists, please provide a small self-contained example to help reproduce this issue. Thanks!

**Comment by whummer** [comment] 2019-12-08 10:02
New version `0.2.0` of the Java libs have been released to Maven Central. Going to close this issue, until we have more details or a small test to reproduce this issue (if the problem still persists and hasn't been fixed yet). Thanks

**Comment by davidhesson** [comment] 2020-02-11 23:48
Everything that @meriouma stated still holds true in the master branch (line numbers have shifted). The `Class.forName(handlerName)` will fail on a string such as `package.class::methodHandler`, and further down the line, the `instanceof` checks will not pass if you didn't extend the appropriate class. Localstack should probably support this since AWS does. I may PR if I get some time. Should I open a new feature request?

**Comment by whummer** [comment] 2020-05-10 14:23
Thanks @davidhesson - can you please confirm whether the issue reported by @meriouma still persists in the `latest` version? Would be great if you could provide a small, reproducible sample that will allow us to fix and close this issue. Thanks!

**Closed** 2020-11-19 17:59 UTC
Labels: java, lambda-execution, priority-high

**Comment by meriouma** [comment] 2020-11-20 18:51
@miho120 Was there a PR that fixed this issue?

**Comment by miho120** [comment] 2020-11-20 21:59
@whummer ^

**Comment by MadaraUchiha** [comment] 2021-09-26 07:02
@whummer This *still* reproduces. It's trivial to repro it, just upload the following code:

```java
class Handler {
  public static String handle(Object event, Object context) {
    return "Hello world!";
  }
}```

And set the handler to `Handler::handle`. This works in AWS, and fails in localstack with `ClassNotFoundException: Handler::handle`
