### ISSUE TITLE
bug: Localstack fails to boot up if SQS endpoint hit too soon

### ISSUE THREAD

**Issue by mboudreau** [localstack/localstack#4782] opened 2021-10-25 02:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an app that runs locally in docker-compose.  That app tries to poll an SQS queue of `http://127.0.0.1:4566/000000000000/test` as soon as it starts.  However, if Localstack isn't fully initialized with the queue created (queue creation done through `docker-entrypoint-initaws.d`) before the app calls the queue, Localstack will show errors, never call any of the scripts under `docker-entrypoint-initaws.d` and never fully initialize without a restart.  Refer to logs attached.

It's some kind of timing issue as I have seen it work as well, still showing errors, but runs the SQS creation script eventually.  I think this happens if localstack is called before it's ready for calls.  Either way, this makes it incredibly frustrating to work with and now my app needs to have a delayed start to make sure localstack is fully initialized.  Also, why does it take so long to initialize in the first place?

### Expected Behavior

There shouldn't be a request to localstack that would make it error and not initialize.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Reproducing is tricky as the SQS queue needs to be called at a particular moment when the plugins are being initialized: 

```
localstack    | 2021-10-25T01:49:32:INFO:bootstrap.py: Execution of "prepare_environment" took 664.74ms
localstack    | [2021-10-25 01:49:32 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack    | 2021-10-25T01:49:32:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
app_1         | Waiting on SQS queues to be available...
app_1         | Checking for localstack initialization...
localstack    | 2021-10-25T01:49:33:INFO:bootstrap.py: Execution of "_load_service_plugin" took 800.40ms
localstack    | 2021-10-25T01:49:33:INFO:bootstrap.py: Execution of "require" took 800.70ms
app_1         | Calling queues: http://localstack:4566/000000000000/push, http://localstack:4566/000000000000/backfill
app_1         | Queue http://localstack:4566/000000000000/push not ready...
app_1         | Waiting for 5000ms
localstack    | 2021-10-25T01:49:34:INFO:localstack.services.infra: Starting mock SQS service on http port 4566 ...
localstack    | 2021-10-25T01:49:34:INFO:localstack.services.infra: Starting mock SQS service on http port 4566 ...
localstack    | 2021-10-25T01:49:34:INFO:localstack.multiserver: Starting multi API server process on port 59361
localstack    | 2021-10-25T01:49:34:ERROR:localstack.services.plugins: error while starting service sqs: 'thread'
localstack    | [2021-10-25 01:49:34 +0000] [22] [INFO] Running on http://0.0.0.0:59361 (CTRL + C to quit)
localstack    | 2021-10-25T01:49:34:INFO:hypercorn.error: Running on http://0.0.0.0:59361 (CTRL + C to quit)
localstack    | 2021-10-25T01:49:34:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localstack:4566/000000000000/push: failed to get service for sqs: 'thread' Traceback (most recent call last):
```
My application can consistently hit this window on initialization, but doing it manually or even with a script seems to be difficult, potentially because of caching?  I'm not sure.  Maybe it's because it's receiving 2 calls at the same time as the http request to the queue URL is done with in a `Promise.all` to parallelize the calls.  Since the first call never comes back, I'm guessing there's some kind of state issue somewhere?

### Environment

```markdown
- OS: Ubuntu 21.04
- LocalStack: 0.12.19.1
```

### Anything else?

[logs.txt](https://github.com/localstack/localstack/files/7406770/logs.txt)

**Comment by thrau** [comment] 2021-11-05 22:55
closing this issue for now, since i was not able to reproduce it again. please re-open if the problem resurfaces.

**Closed by thrau** 2021-11-05 22:55 UTC
Labels: bug, infra-startup, awaiting reporter response

**Comment by mboudreau** [comment] 2021-11-06 00:02
@thrau thanks for looking into it mate 👍

**Comment by bleggett** [comment] 2021-12-21 18:05
Seems this is still an issue as of today with `localstack:latest`:

```
 File "/opt/code/localstack/localstack/services/edge.py", line 219, in _require_service
raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for sqs: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name'
2021-12-21T18:03:08.057:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://dcr-localstack:4566/: failed to get service for sqs: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 325, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/edge.py", line 217, in _require_service
self.service_manager.require(api)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
raise container.errors[-1]
File "/opt/code/localstack/localstack/services/plugins.py", line 229, in start
self.service.start(asynchronous=True)
File "/opt/code/localstack/localstack/services/plugins.py", line 173, in start
return self.start_function(**kwargs)
File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 71, in start_sqs
_server = start_sqs_moto(*args, **kwargs)
File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 149, in start_sqs_moto
patch_moto()
File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 129, in patch_moto
def sqs_responses_get_queue_name(self):
File "/opt/code/localstack/localstack/utils/patch.py", line 140, in wrapper
fn.patch = Patch.function(target, fn, pass_target=pass_target)
File "/opt/code/localstack/localstack/utils/patch.py", line 78, in function
return Patch(obj, name, new)
File "/opt/code/localstack/localstack/utils/patch.py", line 48, in __init__
self.old = getattr(self.obj, name)
AttributeError: module 'localstack.services.sqs.sqs_starter' has no attribute 'sqs_responses_get_queue_name'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
result = await run_sync(handler, request, data)
File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
File "/opt/code/localstack/localstack/utils/run.py", line 155, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 912, in handler
response = modify_and_forward(
File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
result = modify_and_forward_orig(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/services/edge.py", line 162, in forward_request
self._require_service(api)
File "/opt/code/localstack/localstack/services/edge.py", line 219, in _require_service
```

**Comment by bleggett** [comment] 2021-12-21 18:17
I think the actual proper solution here is to make sure the container's readiness probe doesn't return 200 until the container is actually ready to accept requests.

**Comment by Andrioden** [comment] 2021-12-28 21:19
Similar error with similar problem, where i try to create some sqs queues which is immediately attempted read from by celery tasks.

```
localstack_1      | 2021-12-28T21:14:26:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localstack:4566/: failed to get service for sqs: 'thread' Traceback (most recent call last):
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/infra.py", line 468, in preload_services
localstack_1      |     SERVICE_PLUGINS.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 284, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
localstack_1      |     self.service_manager.require(api)
localstack_1      |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
localstack_1      |     return f(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 290, in require
localstack_1      |     raise container.errors[-1]
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 188, in start
localstack_1      |     self.service.start(asynchronous=True)
localstack_1      |   File "/opt/code/localstack/localstack/services/plugins.py", line 133, in start
localstack_1      |     return self.start_function(**kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 60, in start_sqs
localstack_1      |     return start_sqs_moto(*args, **kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 147, in start_sqs_moto
localstack_1      |     update_listener=update_listener,
localstack_1      |   File "/opt/code/localstack/localstack/services/infra.py", line 231, in start_moto_server
localstack_1      |     return MotoServerProperties(multiserver.start_api_server(key, server_port), server_port)
localstack_1      |   File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 114, in start_api_server
localstack_1      |     thread = start_server_process(server_port)
localstack_1      |   File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 129, in start_server_process
localstack_1      |     return API_SERVERS["__server__"]["thread"]
localstack_1      | KeyError: 'thread'
localstack_1      | 
localstack_1      | During handling of the above exception, another exception occurred:
localstack_1      | 
localstack_1      | Traceback (most recent call last):
localstack_1      |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
localstack_1      |     result = await run_sync(handler, request, data)
localstack_1      |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
localstack_1      |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_1      |   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
localstack_1      |     result = self.fn(*self.args, **self.kwargs)
localstack_1      |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 545, in handler
localstack_1      |     server_address=parsed_url.netloc,
localstack_1      |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 206, in modify_and_forward
localstack_1      |     method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
localstack_1      |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
localstack_1      |     method=method, path=path, data=data, headers=headers
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 172, in forward_request
localstack_1      |     self._require_service(api)
localstack_1      |   File "/opt/code/localstack/localstack/services/edge.py", line 225, in _require_service
localstack_1      |     raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack_1      | localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for sqs: 'thread'
```
