### ISSUE TITLE
bug: .Net lambda not deleting SQS message

### ISSUE THREAD

**Issue by barry-roomex** [localstack/localstack#10307] opened 2024-02-23 14:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am experiencing the same as closed issue #8283 but have some more information.

A .Net 6 lambda with SQS event source is executing successfully but the message is not deleted.

Running localstack with trace logging shows the following:

```
2024-02-23 13:29:02 2024-02-23T13:29:02.264  INFO --- [   asgi_gw_1] localstack.request.http    : POST /_localstack_lambda/451df979d84ca72131aa2d5248f3398a/invocations/98e7e200-7e83-4cb7-8e60-b787fcef6c59/response => 202; Request(b'', headers={'Host': '172.17.0.3:4566', 'User-Agent': 'Go-http-client/1.1', 'Content-Length': '0', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip'}); Response(b'', headers={'Content-Type': 'text/plain; charset=utf-8'})
...
2024-02-23 13:29:02 2024-02-23T13:29:02.269 DEBUG --- [b787fcef6c59] l.s.l.e.adapters           : Encountered an exception while handling callback
2024-02-23 13:29:02 Traceback (most recent call last):
2024-02-23 13:29:02   File "/opt/code/localstack/localstack/services/lambda_/event_source_listeners/adapters.py", line 133, in _invoke_sync
2024-02-23 13:29:02     result=to_str(json.loads(result.payload)),
2024-02-23 13:29:02                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 13:29:02   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2024-02-23 13:29:02     return _default_decoder.decode(s)
2024-02-23 13:29:02            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 13:29:02   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2024-02-23 13:29:02     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-02-23 13:29:02                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-23 13:29:02   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2024-02-23 13:29:02     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-02-23 13:29:02 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Note the empty content being posted

For a nodejs lambda the posted response has a body and the message is deleted, eg
```
2024-02-23 13:44:01 2024-02-23T13:44:01.057  INFO --- [   asgi_gw_2] localstack.request.http    : POST /_localstack_lambda/434aa24cae75ed32fdc2766f30b22796/invocations/b627c769-1028-4b25-a4e6-5929c9ca78e5/response => 202; Request(b'{"statusCode":200,"body":"The message: {\\"Records\\":[{\\"body\\":\\"hello\\",\\"receiptHandle\\":\\"NzAyY2NhYjgtMmZlZi00YTA1LWFlN2YtZGU1NTk2ZDI4NDBkIGFybjphd3M6c3FzOmV1LXdlc3QtMTowMDAwMDAwMDAwMDA6bG9jYWxzdGFjay10ZXN0LWxhbWJkYS1xdWV1ZSA1Y2M1Mzk5Yy1mNWI0LTQ0NTAtYjAxNi0wNzcwOWE0ODZmMmYgMTcwODY5NTgzNS45NTk5NTg2\\",\\"md5OfBody\\":\\"5d41402abc4b2a76b9719d911017c592\\",\\"eventSourceARN\\":\\"arn:aws:sqs:eu-west-1:000000000000:localstack-test-lambda-queue\\",\\"eventSource\\":\\"aws:sqs\\",\\"awsRegion\\":\\"eu-west-1\\",\\"messageId\\":\\"5cc5399c-f5b4-4450-b016-07709a486f2f\\",\\"attributes\\":{\\"SenderId\\":\\"000000000000\\",\\"SentTimestamp\\":\\"1708695835533\\",\\"ApproximateReceiveCount\\":\\"1\\",\\"ApproximateFirstReceiveTimestamp\\":\\"1708695835959\\"},\\"messageAttributes\\":{}}]}"}', headers={'Host': '172.17.0.3:4566', 'User-Agent': 'Go-http-client/1.1', 'Content-Length': '754', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip'}); Response(b'', headers={'Content-Type': 'text/plain; charset=utf-8'})
...
2024-02-23 13:44:01 2024-02-23T13:44:01.115  INFO --- [   asgi_gw_1] l.request.internal.aws     : AWS sqs.DeleteMessageBatch => 200
```

### Expected Behavior

.Net 6 lambda should delete message after successful execution

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run -d --restart unless-stopped --name LocalStack -p 4566:4566 -p 53:53 -p 53:53/udp -p 4510-4559:4510-4559 -e DEBUG=1 -e LS_LOG=trace -v //var/run/docker.sock:/var/run/docker.sock localstack/localstack:3.1

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

This is easily reproduced with a new project created in VS2022 from the `AWS Lambda Project (.NET Core - C#)` template selecting the `Simple SQS Function` blueprint

No further code changes have been made other than to edit the aws-lambda-tools-defaults.json file and

* Change the region value to `eu-west-1`
* Add the following line `"function-name": "localstack-net-lambda"`

With the lambda CLI tools installed (`dotnet tool install -g Amazon.Lambda.Tools`) run the following commands in the csproj working directory
```
dotnet lambda package

aws lambda create-function --profile localstack --function-name localstack-net-lambda --runtime dotnet6 --zip-file fileb://bin/Release/net6.0/AwsLambda1.zip --handler AWSLambda1::AWSLambda1.Function::FunctionHandler --role arn:aws:iam::000000000000:role/lambda-role --no-cli-pager

aws sqs create-queue --profile localstack --queue-name localstack-net-lambda-queue --attributes VisibilityTimeout=180 --no-cli-pager

aws lambda create-event-source-mapping --profile localstack --function-name localstack-net-lambda --batch-size 5 --maximum-batching-window-in-seconds 5 --event-source-arn arn:aws:sqs:eu-west-1:000000000000:localstack-net-lambda-queue --no-cli-pager

aws sqs send-message --profile localstack --message-body "hello" --queue-url http://sqs.eu-west-1.localhost.localstack.cloud:4566/000000000000/localstack-net-lambda-queue
```

### Environment

```markdown
- OS: Windows 10
- LocalStack: 3.1 to 3.1.1.dev (2024-02-23)
```

**Comment by justvinny** [comment] 2024-03-04 20:25
Hi Barry. Encountered this exception `adapters.py line 133 on NET 6` at my workplace recently and we were able to get it working by making sure our Lambda returned a string. It was failing on ours because we were using a void method. Don't know if this is intended behaviour though or if it's a bug but this workaround should hopefully help.

**Comment by barry-roomex** [comment] 2024-03-05 08:57
Thanks @justvinny. The lack of a return value from the function matches my situation so presumably could be fixed with the change you suggested. Unfortunately I am trying to get many existing lambdas that work fine in AWS running in a LocalStack test environment without code changes.

**Comment by joe4dev** [comment] 2024-06-12 08:04
Hi @barry-roomex 

Your PR is now merged and released for both images (i.e., localstack and localstack-pro). Thank you very much for your contribution 🙇 

Can you confirm whether the fix in the latest Docker image resolves this issue?

**Closed** 2024-06-12 13:52 UTC
Labels: type: bug, aws:sqs, aws:lambda, area: integration/aws-sdk-dotnet
