### ISSUE TITLE
layer mounted at /var/task instead of /opt

### ISSUE THREAD

**Issue by jwoptio** [localstack/localstack#2246] opened 2020-04-03 18:44 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Using lambda with a layer and during lambda execution the files in the layer appear on the filesystem under /var/task instead of /opt where I would expect them.

Following is output from `ls -la /var/task/bin` during lambda execution:

```
> /var/task/bin:
> total 31372
> drwxr-xr-x 2 root root     4096 Apr  1 04:35 .
> drwxrwxr-x 1 root root     4096 Apr  3 18:02 ..
> -rwxr-xr-x 1 root root    19664 Apr  1 04:35 file
> -rwxr-xr-x 1 root root  7764896 Apr  1 04:35 gm
> -rwxr-xr-x 1 root root     1186 Apr  1 04:35 GraphicsMagick-config
> -rwxr-xr-x 1 root root     1239 Apr  1 04:35 GraphicsMagickWand-config
> -rwxr-xr-x 1 root root 23865144 Apr  1 04:32 gs
> -rwxr-xr-x 1 root root     2321 Apr  1 04:33 libpng16-config
> -rwxr-xr-x 1 root root     2321 Apr  1 04:33 libpng-config
> -rwxr-xr-x 1 root root   126600 Apr  1 04:33 pngfix
> -rwxr-xr-x 1 root root    15024 Apr  1 04:33 png-fix-itxt
> -rwxr-xr-x 1 root root   132408 Apr  1 04:35 ripmime
> -rwxr-xr-x 1 root root   166520 Apr  1 04:33 unzip
> 
```

These are files in my layer which i would expect to be found at /opt/bin but they are not. Contents of /opt is:

```
drwxr-xr-x 2 root root 4096 Nov  7 20:32 .
drwxr-xr-x 1 root root 4096 Apr  3 18:33 ..
```

ie empty.

Layer zip contains:

```
Archive:  layer.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  03-31-2020 22:35   bin/
    19664  03-31-2020 22:35   bin/file
   132408  03-31-2020 22:35   bin/ripmime
 23865144  03-31-2020 22:32   bin/gs
  7764896  03-31-2020 22:35   bin/gm
     1186  03-31-2020 22:35   bin/GraphicsMagick-config
     1239  03-31-2020 22:35   bin/GraphicsMagickWand-config
   126600  03-31-2020 22:33   bin/pngfix
     2321  03-31-2020 22:33   bin/libpng-config
    15024  03-31-2020 22:33   bin/png-fix-itxt
     2321  03-31-2020 22:33   bin/libpng16-config
   166520  03-31-2020 22:33   bin/unzip
        0  03-31-2020 22:35   lib/
      911  03-31-2020 22:29   lib/libmagic.la
   111744  03-31-2020 22:35   lib/libmagic.so.1
   111744  03-31-2020 22:35   lib/libmagic.so.1.0.0
   111744  03-31-2020 22:35   lib/libmagic.so
  1223112  03-31-2020 22:35   lib/libjpeg.so.9
    85976  03-31-2020 22:35   lib/libz.so.1
        0  03-31-2020 22:35   lib/pkgconfig/
      259  03-31-2020 22:33   lib/pkgconfig/libpng16.pc
      259  03-31-2020 22:33   lib/pkgconfig/libpng.pc
      265  03-31-2020 22:35   lib/pkgconfig/GraphicsMagickWand.pc
      256  03-31-2020 22:35   lib/pkgconfig/GraphicsMagick.pc
        0  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/
        0  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/config/
       86  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/config/type.mgk
     7639  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/config/delegates.mgk
    15792  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/config/type-windows.mgk
     5253  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/config/type-solaris.mgk
    11040  03-31-2020 22:35   lib/GraphicsMagick-1.3.35/config/type-ghostscript.mgk
      992  03-31-2020 22:35   lib/libGraphicsMagickWand.la
 16575644  03-31-2020 22:35   lib/libGraphicsMagick.a
  1089948  03-31-2020 22:35   lib/libGraphicsMagickWand.a
      951  03-31-2020 22:35   lib/libGraphicsMagick.la
   912208  03-31-2020 22:33   lib/libpng16.so.16
  1699426  03-31-2020 22:33   lib/libpng16.a
   912208  03-31-2020 22:33   lib/libpng16.so
   912208  03-31-2020 22:33   lib/libpng.so
      937  03-31-2020 22:33   lib/libpng16.la
   912208  03-31-2020 22:33   lib/libpng16.so.16.37.0
  1699426  03-31-2020 22:33   lib/libpng.a
      937  03-31-2020 22:33   lib/libpng.la
        0  03-31-2020 22:35   share/
        0  03-31-2020 22:29   share/misc/
  5818072  03-31-2020 22:29   share/misc/magic.mgc
   624764  03-31-2020 22:35   share/magic
        0  03-31-2020 22:35   share/GraphicsMagick-1.3.35/
        0  03-31-2020 22:35   share/GraphicsMagick-1.3.35/config/
      497  03-31-2020 22:35   share/GraphicsMagick-1.3.35/config/colors.mgk
     2513  03-31-2020 22:35   share/GraphicsMagick-1.3.35/config/log.mgk
      439  03-31-2020 22:35   share/GraphicsMagick-1.3.35/config/modules.mgk
```

## Expected behavior

Layer files would be found under /opt/ as defined by aws lambda layer spec.

`Layers are extracted to the /opt directory in the function execution environment. Each runtime looks for libraries in a different location under /opt , depending on the language. Structure your layer so that function code can access libraries without additional configuration.`
https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

## Actual behavior

Layer files are mounted or copied into /var/task.

# Steps to reproduce

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Lambda created with:

```
awslocal lambda create-function --function-name processInbound \
  --zip-file fileb://function.zip \
  --timeout 60 \
  --handler processInbound.handler \
  --runtime nodejs12.x \
  --role whatever \
  --environment "Variables={LOG_LEVEL=debug,STAGE=local}"
```

Layer assigned with:

```
aws --endpoint-url=http://localhost:4574 lambda update-function-configuration \
  --function-name processInbound \
  --layers "arn:aws:lambda:us-east-1:000000000000:layer:insight-email-processing:${LAYER_VERSION}"
```

**Comment by techdragon** [comment] 2020-09-30 02:35
This is blocking me from using localstack effectively. I looked at fixing it myself, but of the 6 places I found '/var/task' referred to in the code, I wasn't able to identify which one was clearly responsible for the layer mounting. Is this because the layer handling code isn't in the public repo? This is a _significant_ issue since layer support is the main reason I paid for localstack instead of just using the open source version.

**Comment by whummer** [comment] 2020-10-04 23:07
Thanks for reporting @jwoptio @techdragon , and apologies for the long delay on this one. This should be fixed in the meantime - can you please pull the `latest` version of the Docker image and give it another try? The Lambda layer contents should now be accessible under `/opt`, like in the real AWS environment. Please let us know if the problem persists or if there are any other issues. Many thanks for your help!

**Closed by whummer** 2020-10-04 23:07 UTC
Labels: PRO, lambda-execution, priority-high

**Comment by smurphnturf** [comment] 2020-12-04 02:47
I am also affected by this

**Comment by whummer** [comment] 2020-12-04 10:19
Thanks for reporting @smurphnturf . Can you please share some details about your setup - which version (tag) of the LocalStack Docker image are you using? This issue should be fixed in the `latest` version (and upwards of version `0.12.2`), but we'll be happy to look into it if you can share some pointers and steps to reproduce. Thanks!

**Comment by smurphnturf** [comment] 2020-12-09 02:46
@whummer, I've tested with 0.12.1, 0.12.2, and the latest version but still no layers are found.
The image I am currently using:
`"Id": "sha256:01144a07c6d917117c5f73164e092fc1a55ea47ea9bb5576152d6eba8206dbf8",
        "RepoTags": [
            "localstack/localstack:latest"
        ],
        "RepoDigests": [
            "localstack/localstack@sha256:2c4562050d364f56930c18a54901241b262f2e511db0b904e841cc70fc50107c"
        ],`
Seems to be the latest possible image that still fails with stack:
`File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 551, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 303, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 210, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'slyp-common-merchant'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}`
Where you can see here that the layer does exists under:
/var/task/__layers__/node_modules
![image](https://user-images.githubusercontent.com/58239200/101567280-a36d1200-3a24-11eb-8924-0c704c1c5037.png)
I have been creating and using layers in version 0.11.2 by using this command:
`aws --endpoint http://localhost:4566 lambda publish-layer-version --layer-name $1 --description "$1 layer" --license-info "MIT" --zip-file fileb://$BASE_DIR/$layer/$1.zip --compatible-runtimes nodejs12.x`
