### ISSUE TITLE
bug: HeaderParameters and QueryStringParameters values from the Connection must take precedence over Rule

### ISSUE THREAD

**Issue by bentcoder** [localstack/localstack#5878] opened 2022-04-16 21:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I duplicate keys in [create-connection](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/create-connection.html) and [put-targets](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/put-targets.html) for `HeaderParameters` and `QueryStringParameters`, I would expect the values from the connection take precedence over rule as the documentation states. However, it is currently not the case so, works as the other way around.

### Expected Behavior

[AWS Documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/events/put-targets.html)

**HttpParameters -> (structure)**
> If you specify an API Gateway REST API or EventBridge ApiDestination as a target, you can use this parameter to specify headers, path parameters, and query string keys/values as part of your target invoking request. If you’re using ApiDestinations, the corresponding Connection can also have these values configured. In case of any conflicting keys, values from the Connection take precedence.

Use `HeaderParameters` and `QueryStringParameters` from Connection, not from Rule in case of duplicated keys.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create your own https://webhook.site link and use below. These commands will let you produce a dummy request where you can see the bug.

```bash
- CREATE RULE
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events put-rule \
    --name my-cron-rule \
    --schedule-expression "cron(* * * * *)"

{
    "RuleArn": "arn:aws:events:eu-west-1:000000000000:rule/my-cron-rule"
}

----------------------------------------------------------------------
 
- CREATE CONNECTION
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events create-connection \
    --name my-connection \
    --authorization-type Basic \
    --auth-parameters "{\"BasicAuthParameters\":{\"Username\":\"hello\",\"Password\":\"world\"},\"InvocationHttpParameters\":{\"HeaderParameters\":[{\"Key\":\"hdr-c\",\"Value\":\"val-c\",\"IsValueSecret\":false},{\"Key\":\"hdr-t\",\"Value\":\"val-c\",\"IsValueSecret\":false}],\"QueryStringParameters\":[{\"Key\":\"qry-c\",\"Value\":\"val-c\",\"IsValueSecret\":false},{\"Key\":\"qry-t\",\"Value\":\"val-c\",\"IsValueSecret\":false}]}}"
 
{
    "ConnectionArn": "arn:aws:events:eu-west-1:000000000000:connection/my-connection/6acf473d-db2f-48ec-b86d-c3e27a413503"
}

----------------------------------------------------------------------
 
- CREATE API DESTINATION
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events create-api-destination \
    --name my-destination \
    --connection-arn "arn:aws:events:eu-west-1:000000000000:connection/my-connection/6acf473d-db2f-48ec-b86d-c3e27a413503" \
    --http-method POST \
    --invocation-endpoint "https://webhook.site/5c2b623f-a9d5-439a-833c-6ab632e57d9d"
 
{
    "ApiDestinationArn": "arn:aws:events:eu-west-1:000000000000:api-destination/my-destination/cd90913d-83c6-4d28-a5f2-77061b2aa244"
}

----------------------------------------------------------------------

- CREATE TARGET
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events put-targets \
    --rule my-cron-rule \
    --targets '[{"Id":"1","Arn":"arn:aws:events:eu-west-1:000000000000:api-destination/my-destination/cd90913d-83c6-4d28-a5f2-77061b2aa244","HttpParameters":{"PathParameterValues":["par-t"],"HeaderParameters":{"hdr-t":"val-t"},"QueryStringParameters":{"qry-t":"val-t"}}}]'
```

### Environment

```markdown
- OS: macOS
- LocalStack: latest
```

### Anything else?

This is a follow up issue to https://github.com/localstack/localstack/issues/5229 where @pinzon did a good work.

**Comment by pinzon** [comment] 2022-04-29 02:50
Thanks @bentcoder for your comment. I'll take care of this one too.

**Comment by whummer** [comment] 2022-05-26 21:40
Thanks @bentcoder @pinzon . This should be fixed via  #5959 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by bentcoder** [comment] 2022-06-05 11:40
Either reopen the issue or open a new one referencing to this issue please **because** the actual problem has been solved but, **what used to work before has been broken now**.

`x` and `y` keys are conflicting so you must keep the ones from `create-connection`, not from `put-targets`. You have corrected this now which is good. **However**, while correcting it, you broke something else. Non-conflicting keys coming from `create-connection` which are `c-1` keys for header and query string params are lost.

create-connection
- HeaderParameters:
  - c-1: val-c
  - x: val-c
- QueryStringParameters:
  - c-1: val-c
  - y: val-c

put-targets
- HeaderParameters:
  - t-1: val-t
  - x: val-t
- QueryStringParameters:
  - t-1: val-t
  - y: val-t

A **correct** HTTP request **must** contain:

Header params:
- c-1: val-c // from connection (you lost this!)
- t-1: val-t // from target
- x: val-c.  // from connection

Query string params:
- c-1: val-c // from connection (you lost this!)
- t-1: val-t // from target
- y: val-c.  // from connection

**Comment by pinzon** [comment] 2022-06-05 12:30
Thanks for the feedback, so I'll reopen the issue.

**Comment by pinzon** [comment] 2022-06-08 21:28
hi @bentcoder, I refactored a test to validate what you say but it shows that the feature works. Please review the test and if you still have problems, submit a new issue with code to reproduce it.

**Closed by pinzon** 2022-06-08 21:28 UTC
Labels: bug, needs-triaging, aws:eventbridge

**Comment by bentcoder** [comment] 2022-06-17 21:58
Not sure if the test there is sufficient enough. I think the best way to, at least visually, verify is to use commands below. I created them for you to run and check in [web hooks ](https://webhook.site) website. Make sure you get your own link and change the command ARNs as you run the commands. The `REQUEST DUMP` at the bottom is expected one which currently doesn't work as described.

```bash
- CREATE RULE
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events put-rule \
    --name game-cron-rule \
    --schedule-expression "cron(* * * * *)"
 
{
    "RuleArn": "arn:aws:events:eu-west-1:000000000000:rule/game-cron-rule"
}
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events list-rules
 
{
    "Rules": [
        {
            "Name": "game-cron-rule",
            "Arn": "arn:aws:events:eu-west-1:000000000000:rule/game-cron-rule",
            "State": "ENABLED",
            "ScheduleExpression": "cron(* * * * *)",
            "EventBusName": "default"
        }
    ]
}
 
----------------------------------------------------------------------
 
- CREATE CONNECTION
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events create-connection \
    --name game-connection \
    --authorization-type BASIC \
    --auth-parameters "{\"BasicAuthParameters\":{\"Username\":\"hello\",\"Password\":\"world\"},\"InvocationHttpParameters\":{\"HeaderParameters\":[{\"Key\":\"hdr-c\",\"Value\":\"val-c\",\"IsValueSecret\":false,\"Key\":\"hdr-x\",\"Value\":\"val-c\",\"IsValueSecret\":false}],\"QueryStringParameters\":[{\"Key\":\"qry-c\",\"Value\":\"val-c\",\"IsValueSecret\":false,\"Key\":\"qry-x\",\"Value\":\"val-c\",\"IsValueSecret\":false}],\"BodyParameters\":[{\"Key\":\"bdy-c\",\"Value\":\"val-c\",\"IsValueSecret\":false}]}}"
 
{
    "ConnectionArn": "arn:aws:events:eu-west-1:000000000000:connection/game-connection/314c648e-0905-4e3b-9731-5144e6c99616",
    "ConnectionState": "AUTHORIZED",
    "CreationTime": "2022-03-12T12:12:16.384584+00:00",
    "LastModifiedTime": "2022-03-12T12:12:16.384584+00:00"
}
 
----------------------------------------------------------------------
 
- CREATE API DESTINATION
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events create-api-destination \
    --name game-destination \
    --connection-arn "arn:aws:events:eu-west-1:000000000000:connection/game-connection/314c648e-0905-4e3b-9731-5144e6c99616" \
    --http-method POST \
    --invocation-endpoint "https://webhook.site/XXXXXXXXXXXXXXXXXX/game"
 
{
    "ApiDestinationArn": "arn:aws:events:eu-west-1:000000000000:api-destination/game-destination/448f2e65-222a-4dbf-8602-a5219dc9529b",
    "ApiDestinationState": "ACTIVE",
    "CreationTime": "2022-03-12T12:12:47.789677+00:00",
    "LastModifiedTime": "2022-03-12T12:12:47.789677+00:00"
}
 
----------------------------------------------------------------------
- CREATE TARGET
 
$ aws --profile localstack --endpoint-url http://localhost:4566 events put-targets \
    --rule game-cron-rule \
    --targets '[{"Id":"1","Arn":"arn:aws:events:eu-west-1:000000000000:api-destination/game-destination/448f2e65-222a-4dbf-8602-a5219dc9529b","Input":"{\"bdy-t\":\"val-t\"}","HttpParameters":{"PathParameterValues":["par-t"],"HeaderParameters":{"hdr-t":"val-t","hdr-x":"val-t"},"QueryStringParameters":{"qry-t":"val-t","qry-x":"val-t"}}}]'
 
 
----------------------------------------------------------------------
LOGS
 
localstack    | 2022-03-12T12:20:50.104:DEBUG:localstack.services.events.events_listener: Notifying 1 targets in response to triggered Events rule game-cron-rule
localstack    | 2022-03-12T12:20:50.123:DEBUG:localstack.utils.aws.message_forwarding: Calling EventBridge API destination (state "ACTIVE"): POST https://webhook.site/XXXXXXXXXXXXXXXXXX/game
 
 
----------------------------------------------------------------------
REQUEST DUMP (expected)
 
curl \
    -X 'POST' 'https://webhook.site/XXXXXXXXXXXXXXXXXX/game/par-t?qry-c=val-c&qry-x=val-c&qry-t=val-t' \
    -H 'content-length: 36' \
    -H 'hdr-c: val-c' \
    -H 'hdr-x: val-c' \
    -H 'hdr-t: val-t' \
    -H 'authorization: Basic aGVsbG86d29ybGQ=' \
    -H 'content-type: application/json; charset=utf-8' \
    -H 'user-agent: Amazon/EventBridge/ApiDestinations' \
    -d $'{"bdy-t": "val-t", "bdy-c": "val-c"}'
```

**Comment by pinzon** [comment] 2022-06-19 18:02
Hi @bentcoder, it took some time to triage but I found and error in your code.

When creating your connection, there are some characters missing in the invocation parameters:
```
"InvocationHttpParameters\":{
     \"HeaderParameters\":[{\"Key\":\"hdr-c\",\"Value\":\"val-c\",\"IsValueSecret\":false,\"Key\":\"hdr-x\",\"Value\":\"val-c\",\"IsValueSecret\":false}],
    \"QueryStringParameters\":[{\"Key\":\"qry-c\",\"Value\":\"val-c\",\"IsValueSecret\":false,\"Key\":\"qry-x\",\"Value\":\"val-c\",\"IsValueSecret\":false}],
    \"BodyParameters\":[{\"Key\":\"bdy-c\",\"Value\":\"val-c\",\"IsValueSecret\":false}]
}
```
Instead of sending 2 headers parameters and 2 query parameters, you're sending just one big one, and since the object takes only the last value it seems like Localstack is ignoring the first one. 

for example, header parameters should look like this:
```
\"HeaderParameters\":[
     {\"Key\":\"hdr-c\",\"Value\":\"val-c\",\"IsValueSecret\":false},
     {\"Key\":\"hdr-x\",\"Value\":\"val-c\",\"IsValueSecret\":false}
],
```
and the same with the query parameters.
