### ISSUE TITLE
Lambda CreateFunction fails with InternalError

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#4148] opened 2021-06-15 09:42 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When using latest localstack image, Lambda CreateFunction fails with the following error.
The client code has not changed, but this error started happening.
```
An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 4): Unknown error: module 'localstack.services.awslambda.lambda_api' has no attribute 'BUCKET_MARKER_LOCAL' Traceback (most recent call last):
--
41 | File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1090, in create_function
42 | result = set_function_code(func_details.code, lambda_name)
43 | File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 311, in set_function_code
44 | AttributeError: module 'localstack.services.awslambda.lambda_api' has no attribute 'BUCKET_MARKER_LOCAL'
45 | Traceback (most recent call last):
46 | File "/drone/src/./drone/localstack/init-aws.py", line 675, in &lt;module&gt;
```

## Expected behavior

CreateFunction should succeed

## Actual behavior

CreateFunction fails

# Steps to reproduce

## Command used to start LocalStack

docker compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
func = lambda_client.create_function(
    FunctionName=lambda_info['FunctionName'],
    Role=role['Arn'],
    Code={
        'ZipFile': file_data.read()
    },
    Handler=f'some-lambda.handler',
    Runtime='python3.8',
    PackageType='Zip',
    Environment={
        'Variables': {
            'SERVER_URL': server_url,
            'SOME_BOOLEAN': 'true'
        }
    }
```

**Comment by whummer** [comment] 2021-06-15 09:52
Thanks for reporting this issue @John-D8 . Looks like a duplicate of https://github.com/localstack/localstack/issues/4147 - this should be fixed in the `latest` version of the Docker image. Please let us know if the problem persists. Thanks!

**Closed by whummer** 2021-06-15 09:52 UTC
