### ISSUE TITLE
Rust Lambda stuck in localstack

### ISSUE THREAD

**Issue by Frederick888** [localstack/localstack#3264] opened 2020-11-22 13:56 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Simple Rust Lambda function got stuck in localstack.

## Expected behavior
Lambda works normally as it does in AWS.

## Actual behavior
Lambda can start, but it gets stuck as soon as it tries to read request.

Via `docker logs <container id>` I can see:
```
Started!
START RequestId: 8736a8ca-e1b1-151b-ec25-1d825d277d49 Version: $LATEST
```

# Steps to reproduce
## Command used to start LocalStack
```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR-/tmp/localstack}
      - HOSTNAME_EXTERNAL=xxx.lan
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Then `docker-compose up`.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```rust
use lambda_runtime::error::HandlerError;
use lambda_runtime::lambda;
use serde::{Deserialize, Serialize};
use std::error::Error;

#[derive(Deserialize, Debug, Clone)]
struct FooRequest {
    bar: String,
}

#[derive(Serialize, Clone)]
struct FooResponse {
    success: bool,
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("Started!");

    lambda!(hello_world);

    Ok(())
}

fn hello_world(ev: FooRequest, _ctx: lambda_runtime::Context) -> Result<FooResponse, HandlerError> {
    println!("{:?}", ev);
    Ok(FooResponse { success: true })
}
```

```sh
$ cargo build --target=x86_64-unknown-linux-musl --release
$ cp target/x86_64-unknown-linux-musl/release/hello_world ./bootstrap
$ zip -j lambda.zip bootstrap
$ aws --endpoint-url http://xxx:4566 lambda create-function --function-name "helloworld" --handler "hello.world" --runtime provided.al2 \
    --zip-file fileb://./lambda.zip --role "" --environment Variables={RUST_BACKTRACE=1} \
    --timeout 30 --memory-size 512
$ aws --endpoint-url http://xxx:4566 lambda invoke --function-name helloworld --payload '{"bar":"bar"}' ./output.json
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-341) by [Unito](https://www.unito.io/learn-more)

**Comment by Frederick888** [comment] 2020-11-22 13:56
Sorry, accidentally hit enter, will fill in details in a min.

**Comment by needanamehelp** [comment] 2020-11-23 08:21
Okay, I'll try and look into this issue, thank you :)

**Comment by macnev2013** [comment] 2020-12-08 15:35
Thanks for reporting @Frederick888 . I tried to reproduce the issue. But I am getting some errors when using this command `cargo build --target=x86_64-unknown-linux-musl --release`. Can you provide a zip package which is working on real AWS, It would help us a lot in reproducing the issue. Thanks.

**Comment by Frederick888** [comment] 2020-12-08 23:16
@macnev2013 Sure :) 
[lambda.zip](https://github.com/localstack/localstack/files/5662486/lambda.zip)

Btw if you have trouble building the code, make sure you have:
1. Added the following dependencies into `Cargo.toml`
  ```toml
  [dependencies]
  lambda_runtime = "0.2.1"
  serde = { version = "1.0.117", features = ["derive"] }
  serde_json = "1.0.59"
  ```
0. Installed the target by running `rustup target add x86_64-unknown-linux-musl`
0. If you are using macOS, [`musl-cross`](https://github.com/FiloSottile/homebrew-musl-cross) also needs to be installed beforehand; or simply build it in Docker

**Comment by whummer** [comment] 2020-12-11 12:29
Thanks for reporting @Frederick888 . This should be (hopefully) fixed in #3344 - can you please pull the `latest` image and give it another try? Please report here if the problem persists. Thanks

**Comment by Frederick888** [comment] 2020-12-11 14:42
@whummer I now see the following logs:

```
localstack_main | 2020-12-11T14:37:51:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e RUST_BACKTRACE="$RUST_BACKTRACE" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"   --rm "lambci/lambda:provided.al2" "hello.world")";docker cp "/tmp/localstack/zipfile.560b15ed/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
localstack_main | 2020-12-11T14:37:51:INFO:localstack.services.edge: Unable to find forwarding rule for host "92ec21b9be3f:4566", path "GET /", target header "", auth header "", data "b''"
localstack_main | 2020-12-11T14:37:51:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:helloworld: Lambda process returned error status code: 1. Result: . Output:
localstack_main | must specify at least one container source
localstack_main | json: cannot unmarshal array into Go value of type types.ContainerJSON Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 551, in run_lambda
localstack_main |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
localstack_main |     return do_execute()
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
localstack_main |     return _run(func_arn=func_arn)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack_main |     result = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
localstack_main |     result = self._execute(func_arn, func_details, event, context, version)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 316, in _execute
localstack_main |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 223, in run_lambda_executor
localstack_main |     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_main | Exception: Lambda process returned error status code: 1. Result: . Output:
localstack_main | must specify at least one container source
localstack_main | json: cannot unmarshal array into Go value of type types.ContainerJSON
```

And the `output.json` I get:

```json
{
  "errorMessage": "Lambda process returned error status code: 1. Result: . Output:\nmust specify at least one container source\njson: cannot unmarshal array into Go value of type types.ContainerJSON",
  "errorType": "Exception",
  "stackTrace": [
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 551, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 173, in execute\n    return do_execute()\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 165, in do_execute\n    return _run(func_arn=func_arn)\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 158, in _run\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 146, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 316, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 223, in run_lambda_executor\n    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"
  ]
}
```

By the way, the expected output, which is also what I get from AWS, is:
```json
{"success":true}
```

**Comment by whummer** [comment] 2020-12-11 18:17
Thanks for the update @Frederick888 - looks like we still had a minor bug in our logic. Can you please pull the `latest` image one more time and give it another try? Thanks for your help.

**Closed by whummer** 2020-12-11 18:17 UTC

**Comment by Frederick888** [comment] 2020-12-13 11:50
Yup, can confirm it works now!

```
localstack_main | 2020-12-13T11:49:19:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e RUST_BACKTRACE="$RUST_BACKTRACE" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"   --rm "lambci/lambda:provided.al2" "hello.world")";docker cp "/tmp/localstack/zipfile.3e693ea9/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
localstack_main | 2020-12-13T11:49:20:INFO:localstack.services.edge: Unable to find forwarding rule for host "e791fefcbcbf:4566", path "GET /", target header "", auth header "", data "b''"
```

And the docker container was correctly destructed after lambda execution. Thanks!
