### ISSUE TITLE
LocalStack CLoudWatch Logs Not Getting Loaded | No CloudWatch Logs for Lambda

### ISSUE THREAD

**Issue by aiswaryamshr966** [localstack/localstack#2003] opened 2020-01-31 05:42 UTC
CloudWatch Logs not present in the log stream, showing 0 bytes of data.

* API Gateway Creation is successfull.
* Lambda is integrated with the API Gateway created.
* Environment Variables are set for the working of the Lambda.
* DynamoDB is also integrated with the Lambda for the access to the database.
* The Endpoint is accessible and the Lambda can be triggered using Postman/CURL and response is available.
* But at the end the CLoudWatch Logs are not getting loaded for the Lambda, when we try to find out the logs in the CloudWatch Logstream, it says there are 0 bytes present i.e. no data present.

Please help us if some configurations are missing at the earliest. It will be a great help.
Thanks in advance.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-150) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2020-02-26 12:29
Thanks for reporting @aiswaryamshr966 . We do have a couple of integration tests which assert that Lambda logs are being written to CloudWatch Logs - see here: https://github.com/localstack/localstack/blob/master/tests/integration/test_lambda.py#L58-L71 .

Can you please provide a small, reproducible test case to help reproduce this issue?

This could potentially be a region mismatch - can you double-check that the region you're using to fetch the CloudWatch logs matches the region specified when creating and invoking the Lambda function, and also matches the region specified as `DEFAULT_REGION` on the server side (or `us-east-1` by default)? Hope that helps, please let us know. Thanks

**Comment by phil-f** [comment] 2020-07-16 16:15
i was wrestling with this myself & found out the issue is that i was using `awslocal`. if you're using it in your cli, it will default the region to `us-east-1` & so if you're using any other region it won't show up

switching over to `aws --endpoint-url [cloudwatch-endpoint-goes-here] --region [region-goes-here]` did the trick

**Comment by mayuresh-kumbhar** [comment] 2021-01-20 13:15
I am also facing this issue, in my case I can see log group is created but while describing log stream its saying `The specified log group does not exist`


```
$  aws logs describe-log-groups --endpoint-url http://localhost:4566
{
    "logGroups": [
        {
            "logGroupName": "/aws/lambda/HeaderProcessor",
            "creationTime": 1611147550287,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/HeaderProcessor",
            "storedBytes": 592
        }
    ]
}

$ aws logs describe-log-streams --endpoint-url http://localhost:4566 --log-group-name /aws/lambda/HeaderProcessor

An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist
```

**Comment by whummer** [comment] 2021-09-06 08:29
Thanks all for reporting @phil-f @mayuresh-kumbhar @aiswaryamshr966  - this should be resolved in the meantime, support for multi-region setups has been added in 59294e6 . Please let us know if the problem persists. Thanks!

**Closed by whummer** 2021-09-06 08:29 UTC
Labels: needs-triaging, lambda-execution, region-issue

**Comment by ashameem123** [comment] 2022-03-30 18:39
> --region


> I am also facing this issue, though my default region set to `us-east-1` in my case I can see log group is created but while describing log stream its saying `The specified log group does not exist`
> 
> ```
> $  aws logs describe-log-groups --endpoint-url http://localhost:4566
> {
>     "logGroups": [
>         {
>             "logGroupName": "/aws/lambda/HeaderProcessor",
>             "creationTime": 1611147550287,
>             "metricFilterCount": 0,
>             "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/HeaderProcessor",
>             "storedBytes": 592
>         }
>     ]
> }
> 
> $ aws logs describe-log-streams --endpoint-url http://localhost:4566 --log-group-name /aws/lambda/HeaderProcessor
> 
> An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist
> ```

was this issue resolved for you I'm getting exactly same thing!

**Comment by ashameem123** [comment] 2022-03-30 18:59
> I am also facing this issue, though my default region set to `us-east-1` in my case I can see log group is created but while describing log stream its saying `The specified log group does not exist`
> 
> ```
> $  aws logs describe-log-groups --endpoint-url http://localhost:4566
> {
>     "logGroups": [
>         {
>             "logGroupName": "/aws/lambda/HeaderProcessor",
>             "creationTime": 1611147550287,
>             "metricFilterCount": 0,
>             "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/HeaderProcessor",
>             "storedBytes": 592
>         }
>     ]
> }
> 
> $ aws logs describe-log-streams --endpoint-url http://localhost:4566 --log-group-name /aws/lambda/HeaderProcessor
> 
> An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist
> ```

was this resolved? Facing same issue

**Comment by alexandrei2007** [comment] 2022-05-02 20:33
> > I am also facing this issue, though my default region set to `us-east-1` in my case I can see log group is created but while describing log stream its saying `The specified log group does not exist`
> > ```
> > $  aws logs describe-log-groups --endpoint-url http://localhost:4566
> > {
> >     "logGroups": [
> >         {
> >             "logGroupName": "/aws/lambda/HeaderProcessor",
> >             "creationTime": 1611147550287,
> >             "metricFilterCount": 0,
> >             "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/HeaderProcessor",
> >             "storedBytes": 592
> >         }
> >     ]
> > }
> > 
> > $ aws logs describe-log-streams --endpoint-url http://localhost:4566 --log-group-name /aws/lambda/HeaderProcessor
> > 
> > An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist
> > ```
> 
> was this resolved? Facing same issue

I had the same issue. 
What worked for me was replacing the logGroupName from "/" to "-". 
e.g. "aws-lambda-HeaderProcessor"

**Comment by daniyal-ogre** [comment] 2025-08-13 23:17
> > > I am also facing this issue, though my default region set to `us-east-1` in my case I can see log group is created but while describing log stream its saying `The specified log group does not exist`
> > > ```
> > > $  aws logs describe-log-groups --endpoint-url http://localhost:4566
> > > {
> > >     "logGroups": [
> > >         {
> > >             "logGroupName": "/aws/lambda/HeaderProcessor",
> > >             "creationTime": 1611147550287,
> > >             "metricFilterCount": 0,
> > >             "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/HeaderProcessor",
> > >             "storedBytes": 592
> > >         }
> > >     ]
> > > }
> > > 
> > > $ aws logs describe-log-streams --endpoint-url http://localhost:4566 --log-group-name /aws/lambda/HeaderProcessor
> > > 
> > > An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist
> > > ```
> > 
> > 
> > was this resolved? Facing same issue
> 
> I had the same issue. What worked for me was replacing the logGroupName from "/" to "-". e.g. "aws-lambda-HeaderProcessor"

This did not work for me, I'm not sure if it's because I have a "-" in my lambda name. Has anyone else resolved this?
