### ISSUE TITLE
Test class crashes when trying to get docker image

### ISSUE THREAD

**Issue by tvieira-ebsco** [localstack/localstack#647] opened 2018-03-08 16:29 UTC
The test class code:
```
@RunWith(LocalstackDockerTestRunner.class)
@LocalstackDockerProperties(randomizePorts = true)
@Profile("test")
public class KinesisTest {
    @Test
    public void myTest() { ... }
}
```
The log error:
```
mar 08, 2018 1:12:38 PM cloud.localstack.docker.LocalstackDockerTestRunner processDockerPropertiesAnnotation
INFORMAÇÕES: External host name is set to: localhost
mar 08, 2018 1:12:39 PM cloud.localstack.docker.Container createLocalstackContainer
INFORMAÇÕES: Pulling latest image...
java.lang.RuntimeException: Failed to execute command

	at cloud.localstack.docker.DockerExe.execute(DockerExe.java:74)
	at cloud.localstack.docker.command.PullCommand.execute(PullCommand.java:19)
	at cloud.localstack.docker.Container.createLocalstackContainer(Container.java:52)
	at cloud.localstack.docker.LocalstackDockerTestRunner.run(LocalstackDockerTestRunner.java:118)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at cloud.localstack.docker.DockerExe.execute(DockerExe.java:68)
	... 16 more
```
Version: 0.1.11

It started today, until yesterday it worked.
Is someone experiencing similar error?

**Comment by twolak2003** [comment] 2019-03-15 20:26
I am seeing the same issue.  This works in my localhost but when I run it on the my integration server it fails.  I have verified that the container starts up fine way before the test fails.

docker logs --tail all d38b6b7796b0
....
Starting local dev environment. CTRL-C to quit.
Starting mock SQS (http port 4576)...
Starting mock SNS (http port 4575)...
Waiting for all LocalStack services to be ready
Ready.

**Comment by whummer** [comment] 2019-11-08 20:00
Not sure how to reproduce this issue - looks like the code times out when pulling the Docker image? Can you try running the command `docker pull localstack/localstack` in your CI, in order to have the image available when the test suite starts?

Closing this issue for now, as more details are needed to reproduce it. Please report here if the problem persists or more details are available. Thanks!

**Closed by whummer** 2019-11-08 20:00 UTC
Labels: bug, java, regression
