### ISSUE TITLE
bug: Lambda `lambda-runtime-cognito-identity` header is wrong

### ISSUE THREAD

**Issue by milenkovicm** [localstack/localstack#5783] opened 2022-03-31 21:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Latest `lambda rust sdk` with latest `localstack` does not work, invocation will panic with:

```
Error: Error("missing field `identity_id`", line: 1, column: 82)
```

After looking at `rust sdk` I believe that there is a bug in `lambda-runtime-cognito-identity` which is set by localstack before lambda invocation on line 
https://github.com/localstack/localstack/blob/6f4bcb61081acaa478e3fb372a46a45afb9546f1/localstack/services/awslambda/lambda_executors.py#L322

headers set by localstack:

```json
{
    "content-type": "application/json",
    "docker-lambda-log-type": "Tail",
    "lambda-runtime-aws-request-id": "b24ac0cd-0271-1f84-8c9e-ec80afe5c542",
    "lambda-runtime-cognito-identity": "{\"accountId\": \"000000000000\", \"sourceIp\": \"127.0.0.1\", \"userAgent\": \"curl/7.79.1\"}",
    "lambda-runtime-deadline-ms": "1648758046612",
    "lambda-runtime-invoked-function-arn": "arn:aws:lambda:us-east-1:000000000000:function:sam-app-HelloHttpRustFunction-9b5ba8a8",
    "lambda-runtime-trace-id": "Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1",
    "date": "Thu, 31 Mar 2022 20:20:17 GMT",
    "content-length": "1451"
}
```

looking at rust code, `identity_id` is linked with `lambda-runtime-cognito-identity`, to elaborate, if we cross reference `lambda-runtime-cognito-identity` header with rust lambda sdk (https://github.com/awslabs/aws-lambda-rust-runtime/blob/eac2e144f8210a38c333ec57bb00ef94cd28160e/lambda-runtime/src/types.rs#L131) 
we see that it is an optional header (https://github.com/awslabs/aws-lambda-rust-runtime/blob/eac2e144f8210a38c333ec57bb00ef94cd28160e/lambda-runtime/src/types.rs#L115),  with json format like (https://github.com/awslabs/aws-lambda-rust-runtime/blob/eac2e144f8210a38c333ec57bb00ef94cd28160e/lambda-runtime/src/types.rs#L88):

```rust
pub struct CognitoIdentity {
    /// The unique identity id for the Cognito credentials invoking the function.
    pub identity_id: String,
    /// The identity pool id the caller is "registered" with.
    pub identity_pool_id: String,
}
```

`CognitoIdentity` has two mandatory properties: `identity_id` and `identity_pool_id`
which are not camel case.

So header set, should not have same structure as `requestContext\identity` property, set at https://github.com/localstack/localstack/blob/6f4bcb61081acaa478e3fb372a46a45afb9546f1/localstack/services/awslambda/lambda_executors.py#L144 

This issue currently blocks use of `lambda rust sdk` on latest localstack.

### Expected Behavior

There are two ways to fix this issue:

- do not set `lambda-runtime-cognito-identity` header.
- set it with correct json. `"lambda-runtime-cognito-identity": "{\"identity_id\": \"000000000000\", \"identity_pool_id\": \"000000\"}",` ( somewhere along those lines :) ) 

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

deploy rust sdk example https://github.com/awslabs/aws-lambda-rust-runtime/blob/main/lambda-http/examples/hello-http.rs

### Environment

```markdown
- OS: MacOS
- LocalStack: localstack/localstack                       latest                46fd3a044758   28 hours ago    1.51GB
```

**Comment by pennytextures** [comment] 2022-04-06 09:04
this causes issues with java quarkus lambdas, it's unable to deserialize the object and blows up, 0.14.0 is fine, the issue is present on 0.14.1 and 0.14.2

**Comment by milenkovicm** [comment] 2022-04-06 18:02
@pennytextures you're right. header is not set in 0.14.0 thus no problem

**Comment by dfangl** [comment] 2022-04-12 15:47
Hi there!
Just need some more information: How exactly are you invoking your lambdas. In the context of cognito authentication, or just using something like `awslocal lambda invoke`?
In which context does the error occur? You mentioned the rust sdk, do you execute sdk functions from the context of your lambda?
It would also be immensely helpful if you could provide the logs of an invocation which produces this behavior. I just tested a basic rust lambda, and it seemed to work.

**Comment by pennytextures** [comment] 2022-04-13 05:26
My issue with quarkus is essentially the same setup, just with java/quarkus behind it, api gateway is invoking the lambda.

**Comment by dfangl** [comment] 2022-05-03 08:59
Yes, it seems like an issue with the apigateway - lambda integration. We are working on a fix, but we need to make sure nothing else depends on this (to be honest, really weird) behavior first.

**Comment by milenkovicm** [comment] 2022-05-05 17:10
Hey @dfangl,

It works now. Problematic header is gone, thus no issues with deserialisation 

It's up to you if this issue should be closed or kept open until you deliver proper fix.

Thanks

**Comment by dfangl** [comment] 2022-05-05 17:12
Thanks for the feedback. I will close this now, the issue will be tracked in another issue.

**Closed by dfangl** 2022-05-05 17:12 UTC
Labels: bug, needs-triaging, aws:lambda

**Comment by pennytextures** [comment] 2022-05-13 14:04
latest works fine with quarkus now too :)
