### ISSUE TITLE
bug: S3 PutObject fails with 500 error

### ISSUE THREAD

**Issue by jusmark123** [localstack/localstack#7314] opened 2022-12-12 23:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a bucket with the following TopicConfiguration

```
{
 "TopicConfigurations": [
        {
            "Id": "user-reach-file-s3-upload",
            "TopicArn": "arn:aws:sns:us-west-2:000000000000:tf-en-local-sns-client-v2",
            "Events": [
                "s3:ObjectCreated:*"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "user/"
                        },
                        {
                            "Name": "Suffix",
                            "Value": ""
                        }
                    ]
                }
            }
        }
    ]
}
```
I get the following TypeError:
```
localstack_main     | 2022-12-12T22:42:51.971 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
localstack_main     | Traceback (most recent call last):
localstack_main     |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
localstack_main     |     handler(self, self.context, response)
localstack_main     |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
localstack_main     |     handler(chain, context, response)
localstack_main     |   File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
localstack_main     |     result = self.forward_request(
localstack_main     |   File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
localstack_main     |     return do_forward_request(
localstack_main     |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
localstack_main     |     return new(target, *args, **kwargs)
localstack_main     |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 40, in D
localstack_main     |   File "/opt/code/localstack/localstack/services/edge.py", line 224, in do_forward_request
localstack_main     |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main     |   File "/opt/code/localstack/localstack/services/edge.py", line 248, in do_forward_request_inmem
localstack_main     |     response = modify_and_forward(
localstack_main     |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 483, in wrapper
localstack_main     |     value = func(*args, **kwargs)
localstack_main     |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 656, in modify_and_forward
localstack_main     |     updated_response = listener.return_response(
localstack_main     |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1659, in return_response
localstack_main     |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 302, in send_notifications
localstack_main     |     for notif in notification_configs:
localstack_main     |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 326, in send_notification_for_subscriber
localstack_main     |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 216, in filter_rules_match
localstack_main     |     elif rule_name_lower == "suffix":
localstack_main     | TypeError: endswith first arg must be str or a tuple of str, not NoneType
localstack_main     | 2022-12-12T22:42:51.972  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.PutObject => 500 (InternalError)

```
In the code I see the line here https://github.com/localstack/localstack/blob/1132017f1503853df390cdfecbadace31c419054/localstack/services/s3/s3_listener.py#L216

I think the issue is here https://github.com/localstack/localstack/blob/1132017f1503853df390cdfecbadace31c419054/localstack/services/s3/s3_listener.py#L210

it's searching for "FilterRule" but the property is "FilterRules". This is preventing me from testing my pipeline which begins with the putObject process. The file is queued and then processed by lambda. The file is uploaded, but no notification is sent. Any guidance would be much appreciated . 

### Expected Behavior

The putObject function should create a SNS notification.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
    docker-compose 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
    awslocal s3api put-object --endpoint-url http://localhost:4566 --bucket <bucket> --key <Key> --body <CSV file>

### Environment

```markdown
- OS: Ubuntu Ubuntu 22.04.1 LTS
- LocalStack: localstack/localstack-pro:latest
```

**Comment by bentsku** [comment] 2022-12-13 13:55
Hello @jusmark123 and thanks for your report. 

We have been working on a new implementation of S3, and it is now available under a feature flag. Could you try starting LocalStack with `PROVIDER_OVERRIDE_S3=asf` (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)) and see if that would fix your problem? We overhauled the S3 notifications and I think your issue would be fixed with the new version. 

In the case it's not, don't hesitate to provide us any logs where the exception can be seen. Thanks a lot for your feedback! 

Note: if you are a Pro user, you should use the flag value `asf_pro` instead of `asf`.

**Comment by bentsku** [comment] 2022-12-30 14:49
Hello, as it's been 2 weeks and the issue is not reproducible anymore with the solution above (and we have integration tests covering this use case), I'll close the issue.

If you still encounter the issue, don't hesitate to comment again and I'll reopen!
Thanks again for your report.

**Closed by bentsku** 2022-12-30 14:49 UTC
Labels: type: bug, status: response required, aws:s3
