### ISSUE TITLE
Localstack v0.12.9.1 complaining about missing policy when removing permission

### ISSUE THREAD

**Issue by ylebon-vf** [localstack/localstack#3864] opened 2021-04-12 11:55 UTC
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
When upgrading localstack version to 0.12.9.1 **_lambda_client.remove_permission_**  throws exception related to missing policy ressource.

The  lambda function 

lambda_.Function(
            self,
            "lambda-name",
            function_name="function-name",
            runtime=lambda_.Runtime.PYTHON_3_8,
            code=make_python_zip_bundle(get_module_path("lambda-code")),
            handler="handler.on_event",
            description="Example lambda function",
            vpc=ecs_cluster.vpc,
            timeout=core.Duration.seconds(15),
        )

`botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: Unable to find policy for Lambda function`

...

## Expected behavior
As in the previous version localstack 0.12.6 should not throw exception. 

...

## Actual behavior
`botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: Unable to find policy for Lambda function lambda-function-name`
...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment] 2021-04-13 09:16
Hello @ylebon-vf, could you please show a bit more of the code you are using, example commands, etc.? I was unable to reproduce this, example below:

```
$ awslocal lambda add-permission --function-name test --action lambda:InvokeFunction --statement-id sns --principal sns.amazonaws.com

{
    "Statement": "{\"Sid\": \"sns\", \"Effect\": \"Allow\", \"Action\": \"lambda:InvokeFunction\", \"Resource\": \"arn:aws:lambda:us-east-1:000000000000:function:test\", \"Principal\": {\"Service\": \"sns.amazonaws.com\"}}"
}
```

```
$ awslocal lambda list-functions
{
    "Functions": [
        {
            "FunctionName": "test",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:test",
            "Runtime": "python3.8",
            "Role": "test",
            "Handler": "lambda_function.lambda_handler",
            "CodeSize": 493,
            "Description": "",
            "Timeout": 3,
            "LastModified": "2021-04-13T09:04:22.133+0000",
            "CodeSha256": "4gcoq0qm6fhb3SWXRZgmbPWUmO64GSBvva0nbrGKeF0=",
            "Version": "$LATEST",
            "VpcConfig": {},
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "c0c53007-f9ad-49ad-8c79-f6aaf7593155",
            "State": "Active",
            "LastUpdateStatus": "Successful",
            "PackageType": "Zip"
        }
    ]
}
```

```
$ awslocal lambda get-policy --function-name test
{
    "Policy": "{\"Version\": \"2012-10-17\", \"Id\": \"default\", \"Statement\": [{\"Sid\": \"sns\", \"Effect\": \"Allow\", \"Action\": \"lambda:InvokeFunction\", \"Resource\": \"arn:aws:lambda:us-east-1:000000000000:function:test\", \"Principal\": {\"Service\": \"sns.amazonaws.com\"}}], \"PolicyArn\": \"arn:aws:iam::000000000000:policy/lambda_policy_test\"}",
    "RevisionId": "test1234"
}
```

```
$ awslocal lambda remove-permission --function-name test --statement-id sns
```

```
$ awslocal lambda get-policy --function-name test

An error occurred (ResourceNotFoundException) when calling the GetPolicy operation: The resource you requested does not exist.
```
(Which is expected, the policy does not exist and the AWS CLI fails on purpose).

**Comment by mgagliardo** [comment] 2021-04-16 07:50
Marking this as closed as I did not get a response. Please post here if you have any findings. Cheers

**Closed** 2021-04-16 07:49 UTC
Labels: awaiting reporter response, lambda-execution
