### ISSUE TITLE
bug: StepFunctions SQS.SendMessage fails with invalid URL

### ISSUE THREAD

**Issue by sam-goodwin** [localstack/localstack#6816] opened 2022-09-05 00:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `QueueUrl` of a SQS Queue is totally broken in localstack. The `QueueUrl` output by a new Queue resource cannot be used from within and outside of the localstack container. The QueueUrl value MUST be valid regardless of the context.

For Lambda, we have to hack it by replacing the hostname with `process.env.LOCALSTACK_HOSTNAME` but this is impossible to do in Step Functions, so if you use any of the Step Functions direct SDK Integrations for SQS, you get the following error.

```
UnknownEndpoint: Inaccessible host: `localhost'. This service may not be available in the `us-east-1' region
```

### Expected Behavior

Using the `QueueUrl` property of a SQS Queue should "just work" as normal without any hacking required.

Using the `SendMessage` Direct SDK Integration with a Step Function should work and not throw an "invalid hostname" error.

When creating a Step Function and SQS Queue with CloudFormation and deploying to LocalStack, the `QueueUrl` property output by the `Queue` should be valid when passed in to the Step Function's state machine definition.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. Create a Step Function with a CloudFormation Template
2. Define a Step Function and Queue in the Template
3. Use `!Ref Queue` to retrieve the QueueUrl and pass it in to the state machine definition JSON
```json
{
  "StartsAt": "SendMessage",
  "States": {
    "SendMessage": {
      "Type": "Task",
      
      "Parameters": {
        "MessageBody": "hello world",
        "QueueUrl": "!Ref Queue"
      },
      "Resource": "arn:aws:states:::aws-sdk:sqs:sendMessage",
      "End": true
    }
  }
}
```

### Environment

```markdown
- OS: MacOS 11.5.1
- LocalStack: latest
```

**Comment by ChandanChainani** [comment] 2022-09-22 12:32
@sam-goodwin Please can you attach a sample cloudformation template that you have used, it would be lot easier to test and debug

**Comment by omerls-pw** [comment] 2022-12-18 12:06
try adding this to env variable:
```bash
export DOCKER_DEFAULT_PLATFORM=linux/amd64  
```

**Comment by thrau** [comment] 2023-05-10 16:21
using `SQS_ENDPOINT_STRATEGY=domain` will give you SQS queue URls that look something like `http://queue.localhost.localstack.cloud:4566/...`

if you set up your networking to resolve `*.queue.localhost.localstack.cloud` to the localstack container, then you should be good. unfortunately, there's no better way for us to generalize this at the moment. we're working on a DNS component to do this transparently for users when container instantiation is controlled by localstack, but this is still in the making and not necessarily related to SQS.

closing this issue since there has also not been any activity for several months. if you still have problems, please re-open the issue with more specific reproduction instructions. a minimal reproducible example would help immensely. thanks!

**Closed by thrau** 2023-05-10 16:21 UTC
Labels: type: bug, status: triage needed, area: networking, aws:sqs, aws:stepfunctions
