### ISSUE TITLE
Error 502 when deploying serverless appplication to localstack

### ISSUE THREAD

**Issue by hqthao** [localstack/localstack#1154] opened 2019-02-28 08:12 UTC
I want to deploy serverless onto localstack. Here is my step to deploy system:

1. Clone project and run whole stack using docker. (command: `docker-compose up`)
2. Install library [serverless-localstack][3] and update `serverless.yml` in my project

Here is my config:

   ```
 plugins:
      - serverless-localstack
      
    custom:
      localstack:
        host: http://localhost
        debug: false
        endpoints:
        stages:
          - local
          - dev
        lambda:
          mountCode: False # Enable this flag to improve performance
```

After that, I deploy this stack using command: `serverless deploy --stage local`. But I always meet exception.

    Serverless: Updating Stack...
    Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 1 of 4
    Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 2 of 4
    Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 3 of 4
    Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 4 of 4
     
      Serverless Error ---------------------------------------
     
      502

Here is my full deployment log:

    

> Serverless: Generated requirements from /Users/hqt/Documents/avex/requirements.txt in /Users/hqt/Documents/avex/.serverless/requirements.txt...
>     Serverless: Installing requirements from /Users/hqt/Documents/avex/.serverless/requirements/requirements.txt ...
>     Serverless: Docker Image: lambci/lambda:build-python2.7
>     Serverless: Running docker run --rm -v /Users/hqt/Documents/avex/.serverless/requirements\:/var/task\:z -u 0 lambci/lambda\:build-python2.7 python2.7 -m pip install -t /var/task/ -r /var/task/requirements.txt...
>     Serverless: Packaging service...
>     Serverless: Excluding development dependencies...
>     Serverless: Injecting required Python packages to package...
>     Serverless: WARNING: Function crawl_twitter_accounts_api has timeout of 900 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
>     Serverless: Using serverless-localstack
>     Serverless: Creating Stack...
>     Serverless: Checking Stack create progress...
>     ..
>     Serverless: Stack create finished...
>     Serverless: Uploading CloudFormation file to S3...
>     Serverless: Uploading artifacts...
>     Serverless: Uploading service avex.zip file to S3 (25.08 MB)...
>     Serverless: Validating template...
>     Serverless: Skipping template validation: Unsupported in Localstack
>     Serverless: Updating Stack...
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 1 of 4
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 2 of 4
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 3 of 4
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 4 of 4
>      
>       Serverless Error ---------------------------------------
>      
>       502
>      
>       Get Support --------------------------------------------
>          Docs:          docs.serverless.com
>          Bugs:          github.com/serverless/serverless/issues
>          Issues:        forum.serverless.com
>      
>       Your Environment Information -----------------------------
>          OS:                     darwin
>          Node Version:           11.6.0
>          Serverless Version:     1.38.0
>     Serverless: Generated requirements from /Users/hqt/Documents/avex/requirements.txt in /Users/hqt/Documents/avex/.serverless/requirements.txt...
>     Serverless: Installing requirements from /Users/hqt/Documents/avex/.serverless/requirements/requirements.txt ...
>     Serverless: Docker Image: lambci/lambda:build-python2.7
>     Serverless: Running docker run --rm -v /Users/hqt/Documents/avex/.serverless/requirements\:/var/task\:z -u 0 lambci/lambda\:build-python2.7 python2.7 -m pip install -t /var/task/ -r /var/task/requirements.txt...
>     Serverless: Packaging service...
>     Serverless: Excluding development dependencies...
>     Serverless: Injecting required Python packages to package...
>     Serverless: WARNING: Function crawl_twitter_accounts_api has timeout of 900 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
>     Serverless: Using serverless-localstack
>     Serverless: Creating Stack...
>     Serverless: Checking Stack create progress...
>     ..
>     Serverless: Stack create finished...
>     Serverless: Uploading CloudFormation file to S3...
>     Serverless: Uploading artifacts...
>     Serverless: Uploading service avex.zip file to S3 (25.08 MB)...
>     Serverless: Validating template...
>     Serverless: Skipping template validation: Unsupported in Localstack
>     Serverless: Updating Stack...
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 1 of 4
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 2 of 4
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 3 of 4
>     Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 4 of 4
>      
>       Serverless Error ---------------------------------------
>      
>       502
>      
>       Get Support --------------------------------------------
>          Docs:          docs.serverless.com
>          Bugs:          github.com/serverless/serverless/issues
>          Issues:        forum.serverless.com
>      
>       Your Environment Information -----------------------------
>          OS:                     darwin
>          Node Version:           11.6.0
>          Serverless Version:     1.38.0

**Comment by whummer** [comment] 2019-03-06 19:41
Thanks for reporting @hqthao . I was unable to reproduce this issue.
```
$ cat serverless.yml 
service: test1

plugins:
   - serverless-localstack
   
custom:
   localstack:
     host: http://localhost
     debug: false
     endpoints:
     stages:
       - local
       - dev
     lambda:
       mountCode: False # Enable this flag to improve performance

provider:
  name: aws
```

```
$ serverless deploy --stage local
Serverless: Using serverless-localstack
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
..
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..
Serverless: Stack update finished...
Service Information
service: test1
stage: local
region: us-east-1
stack: test1-local
resources: 1
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None
```

Can you pull the latest version of the `localstack/localstack` docker image, then give it another try?

Also, make sure to hold back the deployment until you see the line "`Ready.`" in the log output from LocalStack.

**Comment by aslack19** [comment] 2019-05-13 18:01
I tried the same I am getting

**Comment by whummer** [comment] 2019-11-30 19:48
Thanks @hqthao @aslack19 . Serverless deployment has been significantly reworked in the meantime. Closing this issue as outdated, please report here or create a follow-up ticket with specific error details and steps to reproduce if the problem persists. Thanks

**Closed by whummer** 2019-11-30 19:48 UTC
Labels: needs-triaging
