### ISSUE TITLE
Dyanmodb is not starting inside a container

### ISSUE THREAD

**Issue by adityabhatia02** [localstack/localstack#2294] opened 2020-04-15 11:37 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Unable to start dynamodb inside a container, It's failing with the exception:
```
  File "/opt/code/localstack/localstack/services/plugins.py", line 101, in check_infra
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 94, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 113, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 109, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 30, in check_dynamodb
    assert isinstance(out['TableNames'], list)
TypeError: 'NoneType' object is not subscriptable
```

# Steps to reproduce
I started localstack inside a container, Other services are working except dynamodb
The start of the debug logs:
```
localstack version - "0.11.0"
Starting local dev environment. CTRL-C to quit.
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Starting mock DynamoDB (https port 0)...
Starting mock Kinesis (https port 4568)...
Starting mock S3 (https port 4572)...
2020-04-15T11:29:58:INFO:localstack.multiserver: Starting multi API server process on port 51492
Listening at http://:::4564
Initializing DynamoDB Local with the following configuration:
Port:	4563
InMemory:	true
DbPath:	null
SharedDb:	true
shouldDelayTransientStatuses:	false
CorsParams:	*

2020-04-15 11:29:59,341:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2020-04-15 11:29:59,341:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2020-04-15 11:29:59,341:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
Starting mock SNS (https port 4575)...
2020-04-15 11:29:59,348:API:  * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
2020-04-15 11:29:59,348:API:  * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
2020-04-15 11:29:59,348:API:  * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
Starting mock SQS (https port 4576)...
11:29:59.931 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
11:30:00.802 [elasticmq-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
11:30:01.971 [elasticmq-akka.actor.default-dispatcher-5] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4560, visible server address http://awslocal-569c8548bc-frzdq:4576
```

## Command used to start LocalStack
```DEBUG=1 python bin/localstack start --host```

## Version
localstack version:
```python bin/localstack -v
0.11.0
```
docker version:
```
Docker version 17.05.0-ce, build 89658be
```

python version:
```python
Python 3.8.2
```

**Comment by whummer** [comment] 2020-06-22 20:52
Thanks for reporting this issue @adityabhatia02 . Looks like this could be a duplicate of #2534 - closing in favor of the other issue, please chime in to the discussion on #2534. Thanks!

**Closed by whummer** 2020-06-22 20:52 UTC
