### ISSUE TITLE
Localstack won't start on windows due to dependency on sh

### ISSUE THREAD

**Issue by gaffo** [localstack/localstack#417] opened 2017-10-22 22:31 UTC
Searching for sh
Reading https://pypi.python.org/simple/sh/
Downloading https://pypi.python.org/packages/7c/71/199d27d3e7e78bf448bcecae0105a1d5b29173ffd2bbadaa95a74c156770/sh-1.12.14.tar.gz#md5=a8351aef25d25f707c17e0a7a6280251
Best match: sh 1.12.14
Processing sh-1.12.14.tar.gz
Writing C:\Users\gaffo\AppData\Local\Temp\easy_install-l8gz7pbo\sh-1.12.14\setup.cfg
Running sh-1.12.14\setup.py -q bdist_egg --dist-dir C:\Users\gaffo\AppData\Local\Temp\easy_install-l8gz7pbo\sh-1.12.14\egg-dist-tmp-ngjc8ymp
Traceback (most recent call last):
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 157, in save_modules
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 198, in setup_context
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 248, in run_setup
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 278, in run
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 246, in runner
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 47, in _execfile
  File "C:\Users\gaffo\AppData\Local\Temp\easy_install-l8gz7pbo\sh-1.12.14\setup.py", line 5, in <module>
    description='Roboreadr.com',
  File "C:\Users\gaffo\AppData\Local\Temp\easy_install-l8gz7pbo\sh-1.12.14\sh.py", line 36, in <module>
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    tests_require=['pytest', 'localstack'])
  File "C:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\users\gaffo\ws-roboreadr\roboreadr.com\.eggs\pytest_runner-2.12.1-py3.6.egg\ptr.py", line 194, in run
  File "c:\users\gaffo\ws-roboreadr\roboreadr.com\.eggs\pytest_runner-2.12.1-py3.6.egg\ptr.py", line 181, in _super_run
  File "c:\users\gaffo\ws-roboreadr\roboreadr.com\.eggs\pytest_runner-2.12.1-py3.6.egg\ptr.py", line 132, in install_dists
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\command\test.py", line 194, in install_dists
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\dist.py", line 361, in fetch_build_eggs
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\pkg_resources\__init__.py", line 850, in resolve
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\pkg_resources\__init__.py", line 1122, in best_match
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\pkg_resources\__init__.py", line 1134, in obtain
  File "c:\users\gaffo\ws-roboreadr\roboreadr.com\.eggs\pytest_runner-2.12.1-py3.6.egg\ptr.py", line 76, in fetch_build_egg
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\command\easy_install.py", line 665, in easy_install
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\command\easy_install.py", line 695, in install_item
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\command\easy_install.py", line 876, in install_eggs
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\command\easy_install.py", line 1115, in build_and_install
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\command\easy_install.py", line 1101, in run_setup
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 251, in run_setup
  File "C:\Python36\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 198, in setup_context
  File "C:\Python36\lib\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 169, in save_modules
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 144, in resume
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\pkg_resources\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 157, in save_modules
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 198, in setup_context
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 248, in run_setup
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 278, in run
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 246, in runner
  File "C:\Users\gaffo\ws-roboreadr\roboreadr.com\venv\lib\site-packages\setuptools-28.8.0-py3.6.egg\setuptools\sandbox.py", line 47, in _execfile
  File "C:\Users\gaffo\AppData\Local\Temp\easy_install-l8gz7pbo\sh-1.12.14\setup.py", line 5, in <module>
    description='Roboreadr.com',
  File "C:\Users\gaffo\AppData\Local\Temp\easy_install-l8gz7pbo\sh-1.12.14\sh.py", line 36, in <module>
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

**Comment by gaffo** [comment] 2017-10-22 22:31
I tried installing pbs and it didn't do anything

**Comment by whummer** [comment] 2019-08-03 19:15
Thanks for reporting. Closing this one as duplicate of #563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

* only install the bare minimum dependencies by default
* start LocalStack in Docker by default, and
* lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:15 UTC
Labels: bug, installation, windows
