### ISSUE TITLE
LocalStack & dead Letter Q for SQS not working

### ISSUE THREAD

**Issue by dusinof** [localstack/localstack#2107] opened 2020-02-28 13:36 UTC
Hi, 
I'm having  issue with using SQS Dead Letter Queue. Am I missing something? I'm using Q for communication between 2 apps. Even if i raise the exception 3,4,5...x times and threshold is 2, message is never sent to dead letter q. More over, aws cli command:`list-dead-letter-source-queues` is not working, neither his JAVA version. Is this some limitation on localstack side ? I don't have access to aws currently, so, I can't validate it there. 
I was following  [aws docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-dead-letter-queue.html#configure-dead-letter-queue-java)

```
aws --endpoint-url=http://localhost:4576 sqs get-queue-attributes --queue-url=http://localhost:4576/queue/standard-Q

{
    "Attributes": {
        "RedrivePolicy": "{\"maxReceiveCount\":\"2\", \"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:deadLetter-Q\"}"
    }
}

aws --endpoint-url=http://localhost:4576 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4576/queue/standard-Q",
        "http://localhost:4576/queue/deadLetter-Q"
    ]
}

aws --endpoint-url=http://localhost:4576 sqs list-dead-letter-source-queues --queue-url http://localhost:4576/queue/deadLetter-Q

An error occurred (InvalidAction) when calling the ListDeadLetterSourceQueues operation: InvalidAction; see the SQS docs.
```

```
  @Bean
    public AmazonSQSAsync amazonSqs() {

        AmazonSQSAsync client = AmazonSQSAsyncClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(localStackSqsUrl, awsRegion))
                .build();

        createQueue(client);
        return client;
    }

public void createQueue(AmazonSQSAsync amazonSqs) {
        amazonSqs.createQueue(queue);
        amazonSqs.createQueue(dqueue);

        String dl_queue_url = amazonSqs.getQueueUrl(dqueue).getQueueUrl();

        GetQueueAttributesResult queue_attrs = amazonSqs.getQueueAttributes(
                new GetQueueAttributesRequest(dl_queue_url)
                        .withAttributeNames("QueueArn"));

        String dl_queue_arn = queue_attrs.getAttributes().get("QueueArn");

        // Set dead letter queue with redrive policy on source queue.
        String src_queue_url = amazonSqs.getQueueUrl(queue).getQueueUrl();


        final SetQueueAttributesRequest request = new SetQueueAttributesRequest()
                .withQueueUrl(src_queue_url)
                .addAttributesEntry(QueueAttributeName.RedrivePolicy.toString(),
                        "{\"maxReceiveCount\":\"2\", \"deadLetterTargetArn\":\""
                                + dl_queue_arn + "\"}");

        amazonSqs.setQueueAttributes(request);

    }
```

_Originally posted by dusinof in https://github.com/localstack/localstack/issues/238#issuecomment-592512589_

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-159) by [Unito](https://www.unito.io/learn-more)

**Comment by bogdanlazea** [comment] 2020-03-02 22:10
I'm having the same issue.
```java
    @Bean
    public AWSCredentialsProvider awsCredentialsProvider() {
        return new AWSStaticCredentialsProvider(
                new BasicAWSCredentials(amazonAWSAccessKey, amazonAWSSecretKey)
        );
    }

    @Bean
    public AmazonSQS awsSqsClient(AWSCredentialsProvider awsCredentialsProvider) {
        return AmazonSQSClientBuilder.standard()
                .withCredentials(awsCredentialsProvider)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, region))
                .build();
    }
```

```java
        final CreateQueueRequest createQueueRequest = new CreateQueueRequest(queueName);
        return awsSqsClient.createQueue(createQueueRequest).getQueueUrl();
```

```java
amazon.aws.endpoint=http://localhost:4576
amazon.aws.accesskey=mykey
amazon.aws.region=us-east-1
amazon.aws.secretkey=secret
```

I am getting in docker logs
`localstack_env | 21:46:12.660 [elasticmq-akka.actor.default-dispatcher-12] WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Unknown action: CreateQueue`

and in Java
`500 InvalidAction; see the SQS docs. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidAction; Request ID: 00000000-0000-0000-0000-000000000000)`

**Comment by BisratYalew** [comment] 2020-03-07 10:44
@dusinof  currently,  _list-dead-letter-source-queues_ API is not implemented.

**Comment by dusinof** [comment] 2020-03-07 11:08
But the problem isn't related to  list-dead-letter-source-queues command. The message which should be send to dead letter Q after X failed attempt is not send and remain in standard Q. So Dead letter Q is pretty much usless and not working at all.

**Comment by whummer** [comment] 2020-03-15 11:26
Thanks for reporting @dusinof . The `list-dead-letter-source-queues` API has been added in #2152. We'll add support for SQS DLQ processing shortly - keeping this issue open in the meantime.

**Comment by mikicho** [comment] 2020-03-16 12:11
@whummer Is it possible to just limit the number of retires?

**Comment by dusinof** [comment] 2020-03-16 12:52
> @whummer Is it possible to just limit the number of retires?

not sure what you mean. You can simply set, after witch number of attempts is message sent to D.L.Q.  I tried limit that number to 5, 3, and even 1, but result was always the same. D.L.Q was empty and message was still in SQS Q.

**Comment by janakerman** [comment] 2020-03-25 16:50
I believe I'm seeing the same issue as @dusinof - whereby the re-drive policies aren't being respected. I'm sending a message to an SQS queue, and I'm unable to get the message to reach the DLQ as I can with a real SQS queue.

I replicated the problem with a `localstack`(`0.10.8`) running as a docker container on my machine, and using `awscli`.

1. Create a dead letter queue
```bash
sqs create-queue --queue-name test-queue-dead-letter --attributes "ReceiveMessageWaitTimeSeconds=1,VisibilityTimeout=20"
ARN=$(awslocal sqs get-queue-attributes --queue-url http://localhost:4576/queue/test-queue-dead-letter --attribute-names QueueArn | jq -r .Attributes.QueueArn)
```

2. Create the source queue
```bash
awslocal sqs create-queue --queue-name test-queue --attributes "ReceiveMessageWaitTimeSeconds=1,VisibilityTimeout=20,RedrivePolicy.deadLetterTargetArn=$ARN,RedrivePolicy.maxReceiveCount=1"
```

3. Querying the attributes of the queues, I can't see anything regarding the RedrivePolicy (may or may not be related).
```bash
$ awslocal sqs get-queue-attributes --queue-url http://localhost:4576/queue/test-queue --attribute-names All | jq -r .
{
  "Attributes": {
    "VisibilityTimeout": "20",
    "DelaySeconds": "0",
    "ReceiveMessageWaitTimeSeconds": "1",
    "ApproximateNumberOfMessages": "0",
    "ApproximateNumberOfMessagesNotVisible": "0",
    "ApproximateNumberOfMessagesDelayed": "0",
    "CreatedTimestamp": "1585153850",
    "LastModifiedTimestamp": "1585153850",
    "QueueArn": "arn:aws:sqs:us-east-1:000000000000:test-queue"
  }
}
$ awslocal sqs get-queue-attributes --queue-url http://localhost:4576/queue/test-queue-dead-letter --attribute-names All | jq -r .
{
  "Attributes": {
    "VisibilityTimeout": "20",
    "DelaySeconds": "0",
    "ReceiveMessageWaitTimeSeconds": "20",
    "ApproximateNumberOfMessages": "0",
    "ApproximateNumberOfMessagesNotVisible": "0",
    "ApproximateNumberOfMessagesDelayed": "0",
    "CreatedTimestamp": "1585153534",
    "LastModifiedTimestamp": "1585153534",
    "QueueArn": "arn:aws:sqs:us-east-1:000000000000:test-queue-dead-letter"
  }
}
```

4. Send a message to the source queue.
```bash
$ awslocal sqs send-message --queue-url http://localhost:4576/queue/test-queue --message-body jan
{
    "MD5OfMessageBody": "fa27ef3ef6570e32a79e74deca7c1bc3",
    "MessageId": "fa8d0763-a3a2-400d-8335-863e80556ae0"
}
```

5. I'm able to receive the message multiple times, after letting the VisibilityTimeout lapse.

```bash
$ awslocal sqs receive-message --queue-url http://localhost:4576/queue/test-queue
{
    "Messages": [
        {
            "MessageId": "fa8d0763-a3a2-400d-8335-863e80556ae0",
            "ReceiptHandle": "fa8d0763-a3a2-400d-8335-863e80556ae0#36408386-c7d8-40d0-aac8-2d10fcc6c5c3",
            "MD5OfBody": "fa27ef3ef6570e32a79e74deca7c1bc3",
            "Body": "jan"
        }
    ]
}

# Wait 20+ seconds for the visibility timeout.

$ awslocal sqs receive-message --queue-url http://localhost:4576/queue/test-queue
{
    "Messages": [
        {
            "MessageId": "fa8d0763-a3a2-400d-8335-863e80556ae0",
            "ReceiptHandle": "fa8d0763-a3a2-400d-8335-863e80556ae0#36408386-c7d8-40d0-aac8-2d10fcc6c5c3",
            "MD5OfBody": "fa27ef3ef6570e32a79e74deca7c1bc3",
            "Body": "jan"
        }
    ]
}

# Repeat as many times as you like.
```

**Comment by janakerman** [comment] 2020-03-27 16:53
Supplying the queue attributes in JSON format works as expected. Looks like this could just be an error on my part, but I'm not sure if this is expected behaviour or not :
```
  awslocal sqs create-queue --queue-name test-queue --attributes \
  "{\"ReceiveMessageWaitTimeSeconds\":\"1\",\"VisibilityTimeout\":\"20\",\"RedrivePolicy\": \"{\\\"deadLetterTargetArn\\\":\\\"...\\\",\\\"maxReceiveCount\\\":\\\"10\\\"}\"}"
```

Note that the redrive policy is an escaped JSON within a field.

**Comment by jgslima** [comment] 2020-04-11 18:26
Having same issue, with version 0.11.0

**Comment by egraumann** [comment] 2020-05-29 14:34
having same issue with version 0.11.2. Any updates?

**Comment by whummer** [comment] 2020-06-28 19:17
Thanks for the update @mikicho @dusinof @egraumann @jgslima @janakerman . There have been a couple of changes and improvements related to SQS and dead letter queues in the last couple of weeks. An integration test with SQS and DLQ has also been added to the code here: https://github.com/localstack/localstack/blob/ab4bf6dc1d2e2edf77b368f11e5f69a2daa46a51/tests/integration/test_sqs.py#L273-L281 Can you please give it another try with the `latest` version, and confirm whether this issue has been fixed in the meantime? Thanks

**Comment by geordiepaul8** [comment] 2020-07-02 22:28
Hi, I have been following this thread for the past few days and I am also experiencing the same issue as stated above. I have tried using version 0.11.2 and 0.11.3 and whilst the RedrivePolicy is correctly set on the queue attributes, when the received message count goes above the maxReceiveCount it does not get sent to the DLQ. whenever I set the queue attributes using a json file, the maxReceiveCount figure is not displayed as a string (even though it has been inputted as one from the json file), could this be something to do with why it is not being checked?

ps - keep up the good work, this service is awesome!

**Comment by geordiepaul8** [comment] 2020-07-06 19:29
Just to update on my last message, if i set up the Queue and DLQ using a cloud formation script then the redive policy works and the message is sent to the DLQ

this is a brief example of the cloud formation script I used (bare bones):

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'testq-dlq'
      ContentBasedDeduplication: false
      DelaySeconds: 0
      FifoQueue: false
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'testq'
      ContentBasedDeduplication: false
      DelaySeconds: 0 #s
      FifoQueue: false
      VisibilityTimeout: 5 #s
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 1
```

so the error with the redrive policy not working seems to be when parsing the `.json` file with the queue attributes in. I hope that helps?

**Comment by whummer** [comment] 2020-07-07 10:36
Thanks for confirming that it works with the JSON-encoded policy @janakerman and with the CloudFormation YAML @geordiepaul8 . 

@janakerman The syntax you've been using in your first example does not seem to be valid - see output of the command below when running against real AWS:
```
$ aws sqs create-queue --queue-name test-queue --attributes "ReceiveMessageWaitTimeSeconds=1,VisibilityTimeout=20,RedrivePolicy.deadLetterTargetArn=$ARN,RedrivePolicy.maxReceiveCount=1"

An error occurred (InvalidAttributeName) when calling the CreateQueue operation: Unknown Attribute RedrivePolicy.deadLetterTargetArn.
```

An integration test has been added in #2688 which should cover the functionality reported here:
1) create a queue with redrive policy, DLQ target, and maxReceiveCount=1
2) put a message to the queue
3) receive the message from the queue (without deleting it)
4) wait until the visibility timeout has passed
5) attempt to receive the message again (returns empty result, as the message has been put to the DLQ)
6) receive the message from the DLQ


Can you please give it another try with the `latest` version? Please report here if the problem persists. Thanks

**Comment by geordiepaul8** [comment] 2020-07-07 13:52
Hi @whummer those steps unfortunately did not resolve the problem. I have followed the steps you outlined above, plus I created a queue using an attributes `json` file - both did not work. The message remained on the original queue and the receive count was higher than the maxReceiveCount value.

This was how i created the queue with the json file:

```bash
aws sqs set-queue-attributes --queue-url http://localstack:4566/000000000000/test-queue --attributes file:./queue-attributes.json
```

this was my `queue-attributes.json` file: 

```json
{
  "RedrivePolicy": "{\"deadLetterTargetArn\": \"arn:aws:sqs:eu-west-2:000000000000:test-dlq\",\"maxReceiveCount\": \"1\"}",
  "VisibilityTimeout": 5
}
```

**Comment by Mattchewone** [comment] 2020-07-17 20:28
I am experiencing the same issue. I thought it was a problem with my code but searching for localstack sqs and dlq led me here so this is a relief to see it's not something I have done. 

Is there a work around that I could use to get me going? I am not overly familiar with serverless so any help would be great thanks.

**Comment by BenRbtz** [comment] 2020-10-01 06:59
I've got this to work with both terraform and a python script. However, when I try to increase the `maxReceiveCount` to a value greater than 1 it seems to still treat the value as 1 . 

I can see in #2688 PR that the test case added only tests with a value of 1. Is this intended behaviour or is this an issue with the locastack/elasticmq?

**Comment by AnjaneyalnDatla** [comment] 2020-10-06 12:44
We are facing the same issue as @geordiepaul8 mentioned. We are using the latest localstack docker image - https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-51927c1177ce0bf025e3045c4c983eb46dc584abd8ad84f5b18dc7ba48f379ef?context=explore

**Comment by jogamod** [comment] 2021-07-27 13:14
> I've got this to work with both terraform and a python script. However, when I try to increase the `maxReceiveCount` to a value greater than 1 it seems to still treat the value as 1 .
> 
> I can see in #2688 PR that the test case added only tests with a value of 1. Is this intended behaviour or is this an issue with the locastack/elasticmq?

@BenRbtz did you manage to solve this, I have the same problem. `maxReceiveCount` is 1 even if I put smth greater than 1.

**Comment by whummer** [comment] 2021-08-31 23:35
Looks like this is fixed in the `latest` version - a small integration test has been added [here](https://github.com/localstack/localstack/commit/ce727fe6f4147b9410699b2583192cbae7d29754#diff-1927ab6433d0401dd8d1f4eb814e7a33696fce68bd6caed8c0b60e82fa6d77fcR114-R121) to assert the value of `maxReceiveCount`. Please let us know if the problem persists. Thanks!

**Closed by whummer** 2021-08-31 23:35 UTC
Labels: priority-high, needs-triaging, feature-missing, should-be-fixed, seen_202011
