### ISSUE TITLE
PRO:Can't access internet or services from lambda inside localstack

### ISSUE THREAD

**Issue by aaron-parsons** [localstack/localstack#3135] opened 2020-10-20 11:34 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
whummer  So I've allowed my code to update to include the features in #2983 . This code was functioning before this update and has now ceased to work due to two reasons.

1. I cannot access the internet from inside a lambda running in localstack. I can reproduce this by running a lambda with:
import requests
a = requests.get("https://news.bbc.co.uk")
print(a)

I get:
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='news.bbc.co.uk', port=443): Max retries exceeded with url:  (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca54f588e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"))"

This command works in just plain python. I also made sure that I had allowed port 443 in the docker-compose.yaml.

1. I can't connect to other services (i.e. SNS) from inside the lambda.
I am using:

sns_client = boto3.client('sns', endpoint_url="http://%s:4566" % os.environ["LOCALSTACK_HOSTNAME"])
and getting:
2020-10-20T10:56:43:INFO:localstack.services.edge: Unable to find forwarding rule for host "cb620fdea748:4566", path "/", target header "", auth header "", data "b''"

On startup I also get:

2020-10-20 10:20:54.838: Configure [SNS Endpoint] to [http://cb620fdea748:4566]

It turns out that cb620fdea748 is the docker container ID.

If I set the HOSTNAME variable in the docker-compose.yaml to localhost then I get subprocess.CalledProcessError: Command 'docker inspect -f '{{ .Name }}' localhost' returned non-zero exit status 1

I guess because it can't find the container called localhost. If I rename the container --> localhost then I get 
localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "/", target header "", auth header "", data "b''"

Could you please advise how to get this working? Even a hack to get me going would be fine.
...

## Expected behavior
1. To be able to access the internet from inside a lambda in localstack
1. To be able to access other services from inside a lambda in localstack.

## Command used to start LocalStack
docker-compose up  (using the packaged docker-compose.yaml)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-295) by [Unito](https://www.unito.io/learn-more)

**Comment by aaron-parsons** [comment] 2020-10-22 10:08
Hi @whummer,
I was wondering what your thoughts on this bug were?

Aaron

**Comment by aaron-parsons** [comment] 2020-11-05 13:01
Hi @whummer ,

Any chance of an update on this?

Aaron

**Comment by whummer** [comment] 2020-11-07 17:26
Thanks for reporting @aaron-parsons , and apologies for the delay. Regarding the two issues you've reported:

1. Regarding the `Temporary failure in name resolution` - I'm not sure if this has to do with the recent changes we've made. Looks like this could be a general issue in your Docker environment, or in your DNS/networking setup..? Are you running behind a corporate firewall, by any chance..? Also, can you please share the logs from the LocalStack Docker container - in particular, there should be a log entry `docker run ...` when the Lambda function gets started in a separate container.

Also, can you please try accessing the target host directly from the container, e.g., by running something like this:
```
$ docker exec -it localstack_main curl https://news.bbc.co.uk
```

2. Regarding the second issue, the creation of a boto3 client (e.g., via `boto3.client(...)`) usually does not immediately make a request / API call. Can you please share the rest of the code where the `sns_client` is actually used to make an API call?

In general - would be great if you could provide a small example project to help us reproduce this issue. If you can share a consistently reproducible example, we'll be happy to look into it. Many thanks for your help.

**Comment by whummer** [comment] 2020-11-19 18:56
Quick follow-up @aaron-parsons - were you able to give it a try with the command posted above? Would be great if you could help us with some diagnostic information, to help reproduce this issue - we'll be happy to look into it in more detail (also please feel free to ping us directly via email or Slack). Thanks for your help.

**Comment by tarunsingh2789** [comment] 2021-02-02 19:57
I am not able to access internet if I am hitting api of other docker container(port-9090 ) inside localstack(12.5,port 4566)  lambda.

ConnectionError","errorMessage":"HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url: Caused by NewConnectionError('\u003curllib3.connection.HTTPConnection object at 0x7ff8185c8ad0\u003e: Failed to establish a new connection:


Python file 

import sys
import requests

def handler(event, context):
    print("Inside handler")
    x = requests.get('http://localhost:9090/ping')
    print(x.status_code)
    return str(x.content)

**Comment by CristianAThompson** [comment] 2021-02-05 06:48
I want to throw my hat into this ring as well. I'm working like hell to give my execution containers the ability to talk with my true local environment or even any external host(literally anything with a https://www.google.com style syntax) and no matter what I do the container the lambda runs in can't seem to access external resources at all, in this specific case I have a separate container running with a port exposed of 5650 and I can't for the life of me configure localstack to allow my lambda function container to connect to this host container(not in a network or anything fancy as it's a separate application we are testing integration communications with and we expose the port for other applications to talk to it successfully).

Application layout and function would look like this:
I start the integration docker application, it exposes port 5650, host system and ngrok can both see this application by specifying this port in browser or via CLI, application is responsive and fully functional
I then start up localstack as a part of a separate docker-compose with proper config to run all my services and then deploy my lambda, it gets deployed successfully after which I manually trigger it, which causes it to try and fire a request to my host system at the aforementioned port to communicate with this integration application.
I check the docker logs for my localstack instance and see a failure to communicate with said host resource.

Any ideas @whummer?

**Comment by CristianAThompson** [comment] 2021-02-05 06:51
![image](https://user-images.githubusercontent.com/16628217/106999591-19070d00-674c-11eb-8997-256f46a75774.png)

This is the output I am receiving, I have tried modifying the address to any local path I can think of but it doesn't seem to know how to externally communicate with my local system from within the scope of the lambda function container

**Comment by whummer** [comment] 2021-02-05 12:06
Thanks for the update @CristianAThompson . Can you please share the details of your configuration. The issue is that by default docker-compose creates separate sub-networks which are isolated and not accessible from one another. However you should be able to set something like this in your docker-compose.yml (see also our sample [here](https://github.com/localstack/localstack/blob/master/docker-compose.yml#L7)):
```
    network_mode: bridge
```
The containers can then interact with each other via the Docker bridge (usually reachable under IP address `172.17.0.2` or `172.17.1.2`). Hope that helps - please keep us posted. Thanks

**Comment by tarunsingh2789** [comment] 2021-02-05 19:01
The issue has been resolved by adding below env variable in localstack

LAMBDA_DOCKER_NETWORK="host"

**Closed** 2021-04-25 09:56 UTC
Labels: needs-triaging, networking, priority-high, seen_202011
