### ISSUE TITLE
When installing via pip in a virtualenv, "localstack" script is not executable

### ISSUE THREAD

**Issue by jcmcken** [localstack/localstack#530] opened 2017-12-29 15:43 UTC
Using Python 3.6 and installing within a ``virtualenv``, the ``localstack`` script runner gets installed with non-executable mode (``0644``). I'm installing via wheels, so the problem might be in how the wheels are built.

**Comment by DamianDex** [comment] 2018-01-04 18:13
I had the same on my machine. Any solution??

**Comment by whummer** [comment] 2018-01-09 01:17
Thanks for reporting @jcmcken . I was unable to reproduce the issue, installing within a `virtualenv` in Python 3.6 works for me:
```
$ uname 
Darwin
$ virtualenv -p `which python3` venv
$ . venv/bin/activate
(venv) $ python --version
Python 3.6.2
(venv) $ which localstack
/tmp/venv/bin/localstack
(venv) $ localstack -v
0.8.4
```
Can you please post the exact commands to reproduce this issue? Thanks

**Comment by jcmcken** [comment] 2018-01-09 15:46
I'm on Linux. I tried again a few minutes ago and it seems to work now. Not really sure what the issue was.

**Comment by whummer** [comment] 2018-01-09 17:19
ok, thanks for confirming. I'm closing this issue now, please comment here if the problem persists. Thanks

**Closed by whummer** 2018-01-09 17:19 UTC
Labels: bug, installation
