### ISSUE TITLE
cannot install localslack in windows 10

### ISSUE THREAD

**Issue by soham308** [localstack/localstack#1150] opened 2019-02-26 08:17 UTC
The error I am getting in command prompt is following.

Command "c:\users\user.name\appdata\local\programs\python\python38\python.exe c:\users\user.name\appdata\local\programs\python\python38\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\user.name\AppData\Local\Temp\pip-build-env-o96apxje\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=18.5 wheel "cffi>=1.8,!=1.11.3; python_implementation != 'PyPy'"" failed with error code 1 in None

**Comment by rakid** [comment] 2019-02-27 19:03
Hello @soham308,

What about using localstack inside a docker container ?

**Comment by soham308** [comment] 2019-03-04 07:44
on I will give it a try and get back to you.

**Comment by ManfredLange** [comment] 2019-03-18 02:21
Using latest `docker-compose.yml` with latest image of localhost/localhost (Image Id `89287d40745b`) doesn't seem to work either ....

Command is `docker-compose up -d`

Content of `docker-compose.yml` is:
```
version: '3.7'

services:
  # Localstack source: https://github.com/localstack/localstack/blob/master/docker-compose.yml
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Where do I find instructions to switch on diagnostic output and/or log files?

**Comment by whummer** [comment] 2019-08-03 19:13
Closing as duplicate of #563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

* only install the bare minimum dependencies by default
* start LocalStack in Docker by default, and
* lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:13 UTC
