### ISSUE TITLE
S3 path style access is deprecated

### ISSUE THREAD

**Issue by jafl** [localstack/localstack#1792] opened 2019-11-22 23:47 UTC
Related to #1180

https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

Since path style access is being deprecated, localstack should not require it to be used.  (Currently, there is a note in the Troubleshooting section about path style access being required.)

**Comment by jtomaszewski** [comment] 2020-06-24 12:08
What would be the other approach to this problem? 

Editing `/etc/hosts` on the client machine, so that all bucket domain names are redirected to localstack? This means you'll need to hardcode bucket names, and can't use ones that are generated dynamically on runtime ;/ (Unless you find a way to use [wildcard](https://serverfault.com/questions/118378/in-my-etc-hosts-file-on-linux-osx-how-do-i-do-a-wildcard-subdomain) in the /etc/hosts file.)...

Any other ideas?

**Comment by whummer** [comment] 2020-06-27 10:18
Thanks for reporting @jafl @jtomaszewski . This is indeed something we should tackle asap, given the timeline for the deprecation. This is a duplicate of #2631 - let's please continue the discussion in the other thread. Thanks!

**Closed by whummer** 2020-06-27 10:18 UTC
Labels: configuration, enhancement
