### ISSUE TITLE
Unable to enqueue to SQS with custom attribute value

### ISSUE THREAD

**Issue by ax-slad** [localstack/localstack#3737] opened 2021-03-16 23:03 UTC
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

LocalStack SQS implementation fails to accept messages with custom attribute type. As per AWS documentation this is supported - https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-java-send-message-with-attributes.html

When using Spring's Cloud Messaging project, queueMessageTemplate tries to send messages with custom type. Any integration tests using localstack in such scenario fails.

After debugging I narrowed it down to localstack issue and here is the example test which confirm that issue.

...

## Expected behavior

SQS messages with custom attribute types are enqueued with localstack queue

...

## Actual behavior

Localstack fails to enqueue the message with custom attribute types

...

# Steps to reproduce

Below test using TestContainers confirms the behavior.
``` java
package com.test;

import com.amazonaws.services.sqs.AmazonSQSAsync;
import com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder;
import com.amazonaws.services.sqs.model.CreateQueueRequest;
import com.amazonaws.services.sqs.model.MessageAttributeValue;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.localstack.LocalStackContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.util.Collections;

import static org.testcontainers.containers.localstack.LocalStackContainer.Service.SQS;

@Testcontainers
public class LocalStackBugTest {

    @Container
    public static LocalStackContainer localstackContainer = new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.11.3"))
            .withServices(SQS);

    @Test
    public void testSingleWebhook(){

        AmazonSQSAsync amazonSQSClient = AmazonSQSAsyncClientBuilder
                .standard()
                .withCredentials(localstackContainer.getDefaultCredentialsProvider())
                .withEndpointConfiguration(localstackContainer.getEndpointConfiguration(SQS))
                .build();

        //create queue
        amazonSQSClient.createQueue(new CreateQueueRequest()
                .withQueueName("localstack-que")
                .withAttributes(Collections.singletonMap("VisibilityTimeout", "1")));

        amazonSQSClient.sendMessage(new SendMessageRequest()
                .withQueueUrl(amazonSQSClient.getQueueUrl("localstack-que").getQueueUrl())
                .withMessageAttributes(Collections.singletonMap("timestamp", new MessageAttributeValue()
                        .withStringValue("1614717034367").withDataType("Number.java.lang.Long")))
                .withMessageBody("from-integration-test"));
    }
}
```

## Command used to start LocalStack

Using TestContainers with JUnit Tests

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See the snippet above
...

**Comment by usmangani1** [comment] 2021-04-21 16:10
@ax-slad Thanks for reporting the issue.

Can you please let us know the version of localstack which you are using.I tried to reproduce this using on the current version of localstack and it works completely fine.

**Comment by jsx101** [comment] 2021-09-02 18:15
Version 0.11.3

**Comment by whummer** [comment] 2021-12-13 19:24
Closing as resolved / cannot reproduce - additional integration tests have been added in #4856 . Please let us know if the problem persists with the `latest` Docker image (happy to dig into it in more detail in that case..). Thanks!

**Closed by whummer** 2021-12-13 19:24 UTC
Labels: needs-tests, awaiting reporter response, aws:sqs
