### ISSUE TITLE
Python 2.7 localstack start error with zip archive on MacOS

### ISSUE THREAD

**Issue by vfangellation** [localstack/localstack#221] opened 2017-07-31 06:39 UTC
I'm trying to just run 0.7.3 localstack start using Python 2.7 on my Mac but I get an issue with es.zip file

```
(venv-2.7) vfang-mlt:T vfang$ localstack start
Starting local dev environment. CTRL-C to quit.
ERROR: 'cd /Users/vfang/venv-2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/lh/q6nyrn4s62qd9792pn5p55jhf2wtqv/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip': [es.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of es.zip or
        es.zip.zip, and cannot find es.zip.ZIP, period.

Error starting infrastructure: Command 'cd /Users/vfang/venv-2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/lh/q6nyrn4s62qd9792pn5p55jhf2wtqv/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9
Traceback (most recent call last):
  File "/Users/vfang/venv-2.7/bin/localstack", line 86, in <module>
    infra.start_infra()
  File "/Users/vfang/venv-2.7/lib/python2.7/site-packages/localstack/services/infra.py", line 366, in start_infra
    raise e
subprocess32.CalledProcessError: Command 'cd /Users/vfang/venv-2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/lh/q6nyrn4s62qd9792pn5p55jhf2wtqv/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9
```

There's something wrong with the zip file but it's what I installed running pip install localstack, so not sure if there's a step missing or this shouldn't be happening.

**Comment by whummer** [comment] 2017-07-31 07:36
Thanks for reporting @vfangellation . This appears to be a duplicate of https://github.com/localstack/localstack/issues/213 , can we please continue the conversation there. Thanks!

**Closed by whummer** 2017-07-31 07:36 UTC
