### ISSUE TITLE
bug: SNS Topic does not respect Content-Type for Subscribed HTTP Endpoint

### ISSUE THREAD

**Issue by hop-along-polly** [localstack/localstack#11617] opened 2024-10-01 18:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using this command
```
awslocal sns publish \
    --topic-arn arn:aws:sns:us-east-1:000000000000:local-events \
    --message '{ "clientId": "13471337" }' \
    --message-structure json
```

I am able to successfully publish a message to SNS running in Localstack. The HTTP endpoint I've subscribed to the `local-events` SNS topic receives the notification, but the message body is empty i.e. `{}`.

### Expected Behavior

I would expect the Request Body in my HTTP Endpoint to be `'{ "clientId": "13471337" }'` OR `{ "message": "13471337" }`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

**docker-compose.yml** file
```yaml
version: '3.8'

services:
  my-api:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/my-api/src

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=sns
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      # https://docs.localstack.cloud/references/init-hooks/
      - ./localstack-init-scripts/:/etc/localstack/init/ready.d/ # init.py script included below for reference.

volumes:
  localstack-data:
```

**localstack-init-scripts/init.py**
```python
import boto3
import requests

# SNS Client
sns = boto3.client('sns', endpoint_url='http://localhost:4566', region_name='us-east-1')

# Create Topic
topic_arn = sns.create_topic(Name='local-events')['TopicArn']
print('Topic Arn:', topic_arn)

#Subscribe HTTP endpoint to Topic
subscription_arn = sns.subscribe(
    TopicArn=topic_arn,
    Protocol='http',
    Endpoint='http://host.docker.internal:3000/events',
    # I've also tried Endpoint='http://my-api:3000/events',
    ReturnSubscriptionArn=True
)['SubscriptionArn']
print('Subscription Arn:', subscription_arn)

# Get the Subscription Token and Confirm the Subscription
token_res = requests.get(f'http://localhost:4566/_aws/sns/subscription-tokens/{subscription_arn}').json()
print('Token Res:', token_res)
confirmation_status_code = sns.confirm_subscription(
    TopicArn=topic_arn,
    Token=token_res['subscription_token']
).get('ResponseMetadata', {}).get('HTTPStatusCode', 500)

confirmed = True if confirmation_status_code == 200 else False 
print('Subscription Confirmed:', confirmed)
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal sns publish \
    --topic-arn arn:aws:sns:us-east-1:000000000000:local-events \
    --message '{ "clientId": "13471337" }' \
    --message-structure json
```

### Environment

```markdown
- OS: Mac OSX Sonoma 14.6.1
- LocalStack:
  LocalStack version: 3.7.3.dev37
  LocalStack Docker image sha: sha256:c95a34a63785cdf6a701f4ea8d455af2168baa0da4bc2577ea4678683d0f69af
  LocalStack build date: 2024-09-19
  LocalStack build git hash: b770a274e
```

**Comment by hydrocat** [comment] 2024-10-01 19:06
I just so happen to hit a similar case.
My docker-compose starts a localstack instance with this init file:
```bash
awslocal sns create-topic --name my-topic
awslocal sns subscribe \
   --topic-arn arn:aws:sns:us-east-1:000000000000:my-topic \
   --protocol http \
   --notification-endpoint http://mywebsite/handler
```

`mywebsite` being another container with a webserver listening on port 80.

`mywebsite` receives a subscription confirmation request without body.
```js
localstack-1   | 2024-10-01T19:03:24.927  INFO --- [et.reactor-2] localstack.request.aws     : AWS sns.Subscribe => 200
mywebsite-1    | Received request
mywebsite-1    | {
mywebsite-1    |   host: 'mywebsite',
mywebsite-1    |   'user-agent': 'Amazon Simple Notification Service Agent',
mywebsite-1    |   'accept-encoding': 'gzip,deflate',
mywebsite-1    |   accept: '*/*',
mywebsite-1    |   connection: 'keep-alive',
mywebsite-1    |   'content-type': 'text/plain; charset=UTF-8',
mywebsite-1    |   'x-amz-sns-message-type': 'SubscriptionConfirmation',
mywebsite-1    |   'x-amz-sns-message-id': '372942dd-ab45-4598-b3a0-6e4df141c053',
mywebsite-1    |   'x-amz-sns-topic-arn': 'arn:aws:sns:us-east-1:000000000000:ticket-purchased',
mywebsite-1    |   'content-length': '1166'
mywebsite-1    | }
mywebsite-1    | BODY: {}
```

Without the body, there is no way to confirm the request.

**Comment by hop-along-polly** [comment] 2024-10-02 19:50
As I dig into this more it seems like I need to set the `HTTP` and `HTTPS` Delivery Policies to use `application/json` as the `Content-Type` header. 

From what I can tell a "default" policy can be set on the Topic itself, and each subscription can specify it's own Delivery Policy (or at least I can through the AWS Console)

To account for that I've added the following to my `init.py` script

```python
res = sns.set_topic_attributes(
    TopicArn=topic_arn,
    AttributeName='DeliveryPolicy',
    AttributeValue='{ http: { "defaultContentType": "application/json" }, https: { "defaultContentType": "application/json" } }'
)
print('Set the Default Content-Type Headers', res)

subscription_arn = sns.subscribe(
    TopicArn=topic_arn,
    Protocol='http',
    Endpoint='http://transaction-monitoring-api:3000',
    Attributes={
        'RawMessageDelivery': 'false',
        'DeliveryPolicy': '{"healthyRetryPolicy":{"minDelayTarget":20,"maxDelayTarget":20,"numRetries":3,"numMaxDelayRetries":0,"numNoDelayRetries":0,"numMinDelayRetries":0,"backoffFunction":"linear"},"sicklyRetryPolicy":null,"throttlePolicy":null,"requestPolicy":{"headerContentType":"application/json"},"guaranteed":false}'
    },
    ReturnSubscriptionArn=True
)['SubscriptionArn']
print('Subscription Arn:', subscription_arn)
```

However even setting this Delivery Policies doesn't fix my originally stated issue.

**Comment by hop-along-polly** [comment] 2024-10-02 20:09
FWIW I also setup an SNS Topic in AWS, set the DeliveryPolicies as stated previously, and using Ngrok  subscribe this very same Rest API as an HTTPS subscriber and The SubscriptionConfirmation notification and other notifications all came through without a problem, so there's definitely an issue w/ Localstack not setting the Content-Type headers.

To further confirm that I was able to log the received headers and saw `'content-type': 'text/plain; charset=UTF-8',`

**Comment by bentsku** [comment] 2024-10-02 22:31
Hello @hop-along-polly and thanks for your report!

So reading your comments, all in all, the issue isn't SNS not sending the body, but the `Content-Type` not following the `defaultContentType` of the topic, or `requestPolicy. headerContentType` of the subscription, is that right?

I could confirm that by default, AWS does send the data with `text/plain; charset=UTF-8`, as even some third party integrations actively depends on it, as was shown during implementation for https://github.com/localstack/localstack/pull/9323 ([Opsgenie](https://www.atlassian.com/software/opsgenie) from Atlassian won't accept the request nor validate the subscription if the content-type isn't exactly `text/plain; charset=UTF-8` (we were missing the charset). 

I'll look into supporting setting the content type of the outgoing request. 

I suppose your server isn't parsing the incoming JSON data if the Content-Type isn't set to `application/json`, but the body is still present, is that right?

**Comment by hop-along-polly** [comment] 2024-10-03 17:55
@bentsku You got it!

**Comment by hop-along-polly** [comment] 2024-10-03 18:08
@bentsku I found where the header is hardcoded https://github.com/localstack/localstack/blob/master/localstack-core/localstack/services/sns/publisher.py#L476

I could probably fix this pretty quickly, if this is going to be placed on the backlog and not going to be fixed for a while.

**Comment by bentsku** [comment] 2024-10-03 18:10
@hop-along-polly I'll work on it pretty soon, tomorrow or latest on Monday! I'm not sure the data is available at the moment we send the request, so I can work on it, no worries!

**Comment by bentsku** [comment] 2024-10-03 22:38
Hey @hop-along-polly, from my initial testing against AWS, setting the `requestPolicy` on the subscription or the `defaultRequestPolicy` on the topic to a specific `Content-Type` does not change the `Content-Type` of the `SubscriptionConfirmation`, only for the following `Notification` message types. Could you confirm on your side?

**Comment by bentsku** [comment] 2024-10-03 23:08
Once the linked PR is merged, you will need to either configure your topic or your subscription with those values. Your `Subscribe` call in your `init.py` follows the right format. 

For the `sns.set_topic_attributes` call, the format should be a bit different:
```python
res = sns.set_topic_attributes(
    TopicArn=topic_arn,
    AttributeName="DeliveryPolicy",
    AttributeValue=json.dumps(
        {
            "http": {
                "defaultRequestPolicy": {"headerContentType": "application/json"},
            },
            "https": {
                "defaultRequestPolicy": {"headerContentType": "application/json"},
            }
        }
    ),
)
print('Set the Default Content-Type Headers', res)
```

Hopefully, this should fix your issue! I'll update you once the fix is in the latest image.

**Closed** 2024-10-04 09:06 UTC
Labels: type: bug, aws:sns, status: in progress
