### ISSUE TITLE
bug: put over s3 via http URL doesn't work

### ISSUE THREAD

**Issue by fphilip** [localstack/localstack#6651] opened 2022-08-11 07:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Request
`http://localhost:4566/bucket-local/folder/sample.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220803T144402Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=86339&X-Amz-Credential=test%2F20220803%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=8a635ca924cef2a7d2c5263d32446e7c13892c63e5fea0496a25c7cad566d990`

Error
`2022-08-08T11:15:56:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request PUT http://localhost:4566/bucket-local/folder/sample.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220808T104303Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=86400&X-Amz-Credential=test%2F20220808%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=8a635ca924cef2a7d2c5263d32446e7c13892c63e5fea0496a25c7cad566d990: failed to get service for apigateway: service apigateway is disabled Traceback (most recent call last):
2022-08-08T11:15:57.412280211Z   File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
2022-08-08T11:15:57.412282670Z     self.service_manager.require(api)
2022-08-08T11:15:57.412284971Z   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
2022-08-08T11:15:57.412287418Z     return f(*args, **kwargs)
2022-08-08T11:15:57.412289684Z   File "/opt/code/localstack/localstack/services/plugins.py", line 277, in require
2022-08-08T11:15:57.412292096Z     raise ServiceDisabled("service %s is disabled" % name)
2022-08-08T11:15:57.412294514Z localstack.services.plugins.ServiceDisabled: service apigateway is disabled
2022-08-08T11:15:57.412296876Z `

Conigure
` aws --endpoint-url=http://localhost:4566 s3api get-bucket-cors --bucket  bucket-local`
`{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "POST",
                "PUT",
                "DELETE"
            ],
            "AllowedOrigins": [
                "*"
            ],
            "ExposeHeaders": [
                "ETag"
            ],
            "MaxAgeSeconds": 3000
        }
    ]
}`

### Expected Behavior

file uploaded

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands

##this case works fine
aws s3api put-object --bucket  bucket-local --key folder/sample.pdf  --body sample.pdf  

##this case doesn't work
   curl -T  sample.pdf `http://localhost:4566/bucket-local/folder/sample.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220803T144402Z&X-Amz-SignedHeaders=content-type%3Bhost&X-Amz-Expires=86339&X-Amz-Credential=test%2F20220803%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=8a635ca924cef2a7d2c5263d32446e7c13892c63e5fea0496a25c7cad566d990

### Environment

```markdown
- OS: Docker 
- LocalStack:
```

**Comment by pinzon** [comment] 2022-08-18 16:30
Hi @fphilip could you try with the latest version? I'm unable to reproduce your issue.

**Comment by daveykane** [comment] 2022-08-26 12:23
I am getting this same issue since upgrade to v1, previously I think it worked due to the bride network mode but I'm not 100% sure. The post request from inside the Lambda never seems to reach the running localstack endpoint

**Comment by daveykane** [comment] 2022-08-27 15:16
The issue I'm having it actually linked to https://github.com/localstack/localstack/issues/6588 it seems

**Comment by pinzon** [comment] 2022-08-31 16:34
I'm closing this issue due to the original problem cannot be reproduced and the @daveykane's problem (Media upload with a presign POST) already has a report open.

**Closed by pinzon** 2022-08-31 16:34 UTC
Labels: type: bug, aws:s3, area: asf
