### ISSUE TITLE
bug: Invocation of lambdas deployed via serverless fail

### ISSUE THREAD

**Issue by ivanmartos** [localstack/localstack#4927] opened 2021-11-16 10:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Invoking node lambdas deployed using serverless, serverless webpack and serverless-localstack plugin throws error about missing modules
Invoking lambdas deployed using serverless-offline works (with webpack)

### Expected Behavior

Invoking lambdas deployed in localstack should work same as for lambdas running offline

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

sample to reproduce is in repository https://github.com/ivanmartos/serverless-localstack-example

### Environment

```markdown
- OS: docker on mac (Docker version 20.10.8, build 3967b7d)
- LocalStack: 0.12.20
```

### Anything else?

I also submitted the issue here
https://github.com/localstack/serverless-localstack/issues/171

Not sure where the issue belongs so I rather open an issue also here. If it should be resolved in serverless-localstack then please close this issue

**Comment by ivanmartos** [comment] 2021-11-23 14:47
Small u[date - funny thing is that the issue does not occur when invoking lambda via SQS (SQS is also managed by localstack). Then the lambda works correctly. Issue occurs when invoking lambda via api gateway

**Comment by ivanmartos** [comment] 2021-11-23 15:11
Small update about my experiments - I found a way how to make this work
This is my serverless.yml
```
package:
  individually: true
  patterns:
    - '!./**'
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-localstack

custom:
  namespace: crowdhouse
  webpack:
    excludeFiles: '**/*.spec.ts'
    packager: 'npm'
    concurrency: 4
    includeModules: true
    keepOutputDirectory: true
  localstack:
    debug: true
    stages:
      - offline
    lambda:
      mountCode: true
```

When I deploy the serverless project to localstack and try to invoke any lambda, then it fails on missing node modules. However if I deploy to localstack (stage `offline`) and then trigger via serverless-offline plugin `serverless offline -s offline` (notice the same stage) then code actually works :)
I guess the plugin does not bundle the node_modules, but if the `mountCode:true` is set, then it uses local file system that is populated by the output of `serverless-offline` plugin and then it works :)

**Comment by ackdav** [comment] 2022-12-07 09:10
Hi @ivanmartos - thank you for raising this issue! I'm closing this for now as it seems to be a duplicate of [serverless-localstack/issues/171](https://github.com/localstack/serverless-localstack/issues/171) - which already received a merged fix... 👍

**Closed by ackdav** 2022-12-07 09:10 UTC
Labels: type: bug, status: triage needed, aws:lambda
