### ISSUE TITLE
S3 bucket notification configuration with multiple QueueConfigurations

### ISSUE THREAD

**Issue by nsalhaji** [localstack/localstack#450] opened 2017-11-06 15:41 UTC
Hi guys,

When I try to add a configuration with multiple QueueConfigurations I got this error:

```
2017-11-06T16:27:30:ERROR:localstack.services.generic_proxy: Error forwarding request: 'list' object has no attribute 'get' Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 161, in forward
    path=path, data=data, headers=forward_headers)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 402, in forward_request
    events = config.get('Event')
AttributeError: 'list' object has no attribute 'get'
```

**My S3 configuration file:**
```
{
    "QueueConfigurations": [
        {
            "Id": "DevInventoryLoaderForOffersPut",
            "QueueArn": "arn:aws:sqs:eu-west-1:211526072230:devInventoryLoaderOffersEvents",
            "Events": [
                "s3:ObjectCreated:Put",
                "s3:ObjectCreated:CompleteMultipartUpload"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "workspace/offer/"
                        }
                    ]
                }
            }
        },
        {
            "Id": "DevInventoryLoaderForClientPut",
            "QueueArn": "arn:aws:sqs:eu-west-1:211526072230:devInventoryLoaderClientsEvents",
            "Events": [
                "s3:ObjectCreated:Put",
                "s3:ObjectCreated:CompleteMultipartUpload"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "workspace/client/"
                        }
                    ]
                }
            }
        },
        {
            "Id": "DevInventoryLoaderForProductsPut",
            "QueueArn": "arn:aws:sqs:eu-west-1:211526072230:devInventoryLoaderProductsEvents",
            "Events": [
                "s3:ObjectCreated:Put",
                "s3:ObjectCreated:CompleteMultipartUpload"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "workspace/product/"
                        }
                    ]
                }
            }
        },
        {
            "Id": "DevInventoryLoaderForStocksPut",
            "QueueArn": "arn:aws:sqs:eu-west-1:211526072230:devInventoryLoaderStocksEvents",
            "Events": [
                "s3:ObjectCreated:Put",
                "s3:ObjectCreated:CompleteMultipartUpload"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "workspace/stock/"
                        }
                    ]
                }
            }
        }
    ]
}

```

Thanks.

**Comment by OliverHofkens** [comment] 2018-01-05 12:23
I'm having the same error on the latest Docker image. The error disappears when the list of QueueConfiguration contains only a single element.

**Comment by sjblacknz** [comment] 2018-01-15 23:20
This also happens for me.  When there is one QueueConfiguration things work fine, but with more than one I get a timeout error.  This happens both via the AWS S3 CLI and the C# S3 client (SDK v3.x)

**Comment by duhruh** [comment] 2018-01-15 23:29
Also experiencing this, can confirm goes away when `QueueConfiguration` only contains 1 element.

**Comment by whummer** [comment] 2019-03-18 03:19
Closing this issue - should have been fixed in the meantime. Please re-open this issue if the problem persists. Thanks!

**Comment by fbn-roussel** [comment] 2019-04-05 11:24
The problem is still happening on 0.9.1.
Could you please reopen the issue ?

**Comment by mascah** [comment] 2019-07-07 18:45
Same problem exists with `TopicConfigurations` as well.

**Closed** 2019-11-02 23:07 UTC
Labels: bug, priority-high

**Comment by whummer** [comment] 2019-11-03 14:13
Thanks @mascah @fbn-roussel @duhruh @sjblacknz @OliverHofkens @nsalhaji This should be fixed in the `latest` version of the Docker image. Please give it a try and report back if the problem persists. Thanks
