### ISSUE TITLE
bug: localstack CLI seems to download old images (slowly!) if `latest` is missing

### ISSUE THREAD

**Issue by gchappel** [localstack/localstack#6458] opened 2022-07-14 14:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been having issues with either Docker or Localstack, so a couple of times today I've removed all the images (and eventually reset/reinstalled Docker Desktop which deleted all the images again). I've noticed that when I run `localstack start` (installed with `pip`, on the host macOS) and the `localstack/localstack:latest` image is not present, `localstack` starts downloading a bunch of old images instead of `latest`.

```sh
bash-3.2$ docker image ls
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

bash-3.2$ localstack start
# this step will remain silent for as long as you let it
# nothing will happen for several minutes but eventually you'll see bursts of network activity
<Ctrl-C to see a KeyboardInterrupt stack trace>

bash-3.2$ docker image ls
REPOSITORY              TAG        IMAGE ID       CREATED        SIZE
localstack/localstack   0.10.1.2   9bf25773d5f0   2 years ago    855MB
localstack/localstack   0.10.0     835c5cec4d47   2 years ago    855MB
```

### Expected Behavior

The `localstack` CLI tool sees that `localstack/localstack:latest` does not exist on the local machine, and pulls that version of the image _only_

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```sh
docker image ls
docker image rm localstack/localstack:latest
localstack start
```

### Environment

```markdown
- OS: macOS 12.4, Docker Desktop 4.10, Python 3.9.13 (Homebrew)
- LocalStack: 
  - `localstack          1.0.0`
  - `localstack-client   1.35`
  - `localstack-ext      1.0.0`
```

**Comment by dfangl** [comment] 2022-07-14 14:08
Interesting issue, I have a hunch what could cause this but can you post the output of `localstack --debug start` to make sure?

**Comment by gchappel** [comment] 2022-07-14 14:33
> Interesting issue, I have a hunch what could cause this but can you post the output of `localstack --debug start` to make sure?

It behaves no differently - a silent console while it downloaded the `0.10.0` image in the background, and then I Ctrl-C'ed and got the same stack trace as I did without `--debug`:

```
Traceback (most recent call last):
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 542, in create_container
    container = create_container()
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 524, in create_container
    return self.client().containers.create(
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: localstack/localstack:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gchappel/Library/Python/3.9/bin/localstack", line 23, in <module>
    main()
  File "/Users/gchappel/Library/Python/3.9/bin/localstack", line 19, in main
    main.main()
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/cli/main.py", line 5, in main
    cli = create_with_plugins()
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/cli/localstack.py", line 30, in create_with_plugins
    load_cli_plugins(cli)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/cli/plugin.py", line 39, in load_cli_plugins
    loader.load_all()
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/plugin/manager.py", line 190, in load_all
    for name, container in self._plugins.items():
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/plugin/manager.py", line 231, in _plugins
    self._plugin_index = self._init_plugin_index()
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/plugin/manager.py", line 294, in _init_plugin_index
    return {plugin.name: plugin for plugin in self._import_plugins() if plugin}
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/plugin/manager.py", line 294, in <dictcomp>
    return {plugin.name: plugin for plugin in self._import_plugins() if plugin}
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/plugin/manager.py", line 297, in _import_plugins
    for spec in self.finder.find_plugins():
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/plugin/manager.py", line 333, in find_plugins
    manager = ExtensionManager(
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/stevedore/extension.py", line 133, in __init__
    extensions = self._load_plugins(invoke_on_load,
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/stevedore/extension.py", line 221, in _load_plugins
    ext = self._load_one_plugin(ep,
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/stevedore/extension.py", line 255, in _load_one_plugin
    plugin = ep.load()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack_ext/cli/localstack.py", line 8, in <module>
    from localstack_ext.bootstrap.licensing import is_logged_in
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack_ext/bootstrap/licensing.py", line 15, in <module>
    from localstack_ext import __version__,config
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack_ext/config.py", line 171, in <module>
    out, _ = DOCKER_CLIENT.run_container(
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 579, in run_container
    container = self.create_container(
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 544, in create_container
    self.pull_image(image_name)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 210, in pull_image
    self.client().images.pull(docker_image)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/models/images.py", line 447, in pull
    for _ in pull_log:
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/docker/api/client.py", line 345, in _stream_helper
    data = reader.read(1)
  File "/Users/gchappel/Library/Python/3.9/lib/python/site-packages/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 497, in readinto
    return self._readinto_chunked(b)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 592, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 560, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 520, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

**Comment by gchappel** [comment] 2022-07-14 14:55
> Does using `LEGACY_DOCKER_CLIENT=1` (as set environment variable) when starting localstack fixes this behavior? It seems like a compatibility issue with the localstack CLI and the installed python-docker version.

Yes, it does; I kept the `latest` image around but renamed the tag and when I ran `localstack start` with that environment variable set, Localstack started immediately because all the layers for `latest` were still on my system.

**Comment by gchappel** [comment] 2022-07-14 15:00
Hmmm, having the environment variable set allows Localstack to _start_ quickly. However, it then enters a restart loop. Unsetting the environment variable allows me to actually _successfully_ start Localstack...

**Comment by gchappel** [comment] 2022-07-14 15:01
With `LEGACY_DOCKER_CLIENT=1`
```
Waiting for all LocalStack services to be ready
2022-07-14 15:00:28,444 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-07-14 15:00:28,446 INFO supervisord started with pid 16
2022-07-14 15:00:29,450 INFO spawned: 'infra' with pid 21
2022-07-14 15:00:30,453 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-07-14 15:00:30,743 INFO exited: infra (exit status 1; not expected)

LocalStack version: 1.0.1.dev
Error starting infrastructure: [Errno 2] No such file or directory: 'docker' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 406, in start_infra
print_runtime_information(is_in_docker)
File "/opt/code/localstack/localstack/services/infra.py", line 372, in print_runtime_information
id = get_main_container_id()
File "/opt/code/localstack/localstack/utils/container_networking.py", line 86, in get_main_container_id
container_name = get_main_container_name()
File "/opt/code/localstack/localstack/utils/container_networking.py", line 103, in get_main_container_name
return DOCKER_CLIENT.get_container_name(hostname)
File "/opt/code/localstack/localstack/utils/container_utils/container_client.py", line 590, in get_container_name
return self.inspect_container(container_id)["Name"].lstrip("/")
File "/opt/code/localstack/localstack/utils/container_utils/docker_cmd_client.py", line 363, in inspect_container
return self._inspect_object(container_name_or_id)
File "/opt/code/localstack/localstack/utils/container_utils/docker_cmd_client.py", line 350, in _inspect_object
cmd_result = run(cmd)
File "/opt/code/localstack/localstack/utils/run.py", line 69, in run
output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/local/lib/python3.10/subprocess.py", line 501, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/local/lib/python3.10/subprocess.py", line 969, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.10/subprocess.py", line 1845, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'

Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/opt/code/localstack/localstack/cli/main.py", line 10, in <module>
main()
File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
cli()
File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
self.group(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/cli/localstack.py", line 148, in cmd_start
bootstrap.start_infra_locally()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 260, in start_infra_locally
return infra.start_infra()
File "/opt/code/localstack/localstack/services/infra.py", line 433, in start_infra
raise e
File "/opt/code/localstack/localstack/services/infra.py", line 406, in start_infra
print_runtime_information(is_in_docker)
File "/opt/code/localstack/localstack/services/infra.py", line 372, in print_runtime_information
id = get_main_container_id()
File "/opt/code/localstack/localstack/utils/container_networking.py", line 86, in get_main_container_id
container_name = get_main_container_name()
File "/opt/code/localstack/localstack/utils/container_networking.py", line 103, in get_main_container_name
return DOCKER_CLIENT.get_container_name(hostname)
File "/opt/code/localstack/localstack/utils/container_utils/container_client.py", line 590, in get_container_name
return self.inspect_container(container_id)["Name"].lstrip("/")
File "/opt/code/localstack/localstack/utils/container_utils/docker_cmd_client.py", line 363, in inspect_container
return self._inspect_object(container_name_or_id)
File "/opt/code/localstack/localstack/utils/container_utils/docker_cmd_client.py", line 350, in _inspect_object
cmd_result = run(cmd)
File "/opt/code/localstack/localstack/utils/run.py", line 69, in run
output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/local/lib/python3.10/subprocess.py", line 501, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/local/lib/python3.10/subprocess.py", line 969, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.10/subprocess.py", line 1845, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
2022-07-14 15:00:31,749 INFO spawned: 'infra' with pid 29
^CShutting down...
Sending -15 to supervisord
2022-07-14 15:00:32,751 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-07-14 15:00:32,752 WARN received SIGTERM indicating exit request
2022-07-14 15:00:32,752 INFO waiting for infra to die
2022-07-14 15:00:32,763 INFO stopped: infra (terminated by SIGTERM)
```

Without `LEGACY_DOCKER_CLIENT=1`
```
Waiting for all LocalStack services to be ready
2022-07-14 14:59:39,626 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-07-14 14:59:39,629 INFO supervisord started with pid 16
2022-07-14 14:59:40,632 INFO spawned: 'infra' with pid 21
2022-07-14 14:59:41,634 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 1.0.1.dev
LocalStack Docker container id: a8d4ce2ba439
LocalStack build date: 2022-07-13
LocalStack build git hash: b848ed37

2022-07-14T14:59:42.407  WARN --- [  Thread-108] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-07-14T14:59:42.407  WARN --- [  Thread-108] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-07-14T14:59:42.409  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-07-14T14:59:42.409  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
^CShutting down...
Sending -15 to supervisord
2022-07-14 15:00:19,717 WARN received SIGTERM indicating exit request
2022-07-14 15:00:19,719 INFO waiting for infra to die
2022-07-14 15:00:21,187 INFO stopped: infra (exit status 0)
```

**Comment by gchappel** [comment] 2022-07-14 15:22
It is not correct, there is a `docker` binary:

```sh
bash-3.2$ type docker
docker is /usr/local/bin/docker

bash-3.2$ file /usr/local/bin/docker
/usr/local/bin/docker: Mach-O 64-bit executable x86_64

bash-3.2$ pip3 freeze | grep docker
docker==4.2.2
```

This is a macOS system using Docker Desktop, so it uses the complex system of a Linux VM running the Docker engine with sockets mounted from the host so that the `docker` binary works from the host outside the VM...but from the user perspective, I can run `docker` commands from my macOS shell and "magic happens" to get them executed transparently in the Linux VM where the Docker engine is.

**Comment by dfangl** [comment] 2022-07-14 15:47
Ah OK, I think I see the the whole picture here. I am going to assign this to me and should get to it in the coming days.

**Comment by dfangl** [comment] 2022-07-14 15:50
As a quick fix for now, please uninstall docker in your pip, or upgrade to 5.0.0 (afaik there are some issues with aws sam depending on a lower version of it though)

**Comment by gchappel** [comment] 2022-07-15 10:18
> As a quick fix for now, please uninstall docker in your pip, or upgrade to 5.0.0 (afaik there are some issues with aws sam depending on a lower version of it though)

I'm fine with the way it's working for now - now I have the `latest` image again I can simply unset the environment variable and Localstack runs correctly. So I guess there are two issues here:
1. If the `localstack/localstack:latest` image is deleted, the **new** Docker client incorrectly downloads old images instead of just the latest one; **fixed** by using the legacy Docker client
2. The **legacy** Docker client cannot correctly run Localstack; **fixed** by using the new Docker client

**Comment by dfangl** [comment] 2022-07-15 10:23
Basically, yes. In general, the cli should never use the "new" docker Client (which uses python-docker to communicate with the daemon, which can lead to some in the cli, as you have seen), and the image never the legacy one (which uses and runs the docker binary  which isn't in the docker image to save space).

In general, the issue is that a component is using the wrong client. It should either be the first or the second, but seems like a mix if you have the python docker package installed. I will correct this, of course.

**Comment by dfangl** [comment] 2022-08-01 09:23
Hi @gchappel !
This bug should be fixed with 1.0.2. Can you upgrade localstack using pip and try again?

**Comment by gchappel** [comment] 2022-08-02 09:09
This seems much better, yep!

- I upgraded `localstack` with `pip`
- deleted my copy of `localstack/localstack:latest`
- verified that I did **not** have `LEGACY_DOCKER_CLIENT=1` in my environment
- ran `localstack start`

This time, Localstack correctly only downloaded the `latest` tag of the image, and everything started and stayed running successfully. Thanks for the fix!

**Comment by dfangl** [comment] 2022-08-02 09:14
Great to hear that, thanks for the report!

**Closed by dfangl** 2022-08-02 09:14 UTC
Labels: type: bug, status: response required, area: cli
