### ISSUE TITLE
cdklocal deployment fails

### ISSUE THREAD

**Issue by sazzadabdulhasib** [localstack/localstack#7122] opened 2022-11-03 18:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cdklocal deploy --context env=dev

✨  Synthesis time: 5.11s

RusStack: building assets...

[0%] start: Building 8a3ff7ff2fe4306354f64f6df3190e346845b27b7769f829cfd63375b22588c9:current_account-current_region
[0%] start: Building 8008ab1c17af8ecd8fc53056e00657560c1a9f152948aef259e79b63eee8fd05:current_account-current_region
[0%] start: Building 5647487aca1777e5cf4e15d43f03fd4f99bb93e808b834190ca8a35d7a09ec32:current_account-current_region
[33%] success: Built 8a3ff7ff2fe4306354f64f6df3190e346845b27b7769f829cfd63375b22588c9:current_account-current_region
[66%] success: Built 8008ab1c17af8ecd8fc53056e00657560c1a9f152948aef259e79b63eee8fd05:current_account-current_region
[100%] success: Built 5647487aca1777e5cf4e15d43f03fd4f99bb93e808b834190ca8a35d7a09ec32:current_account-current_region

RusStack: assets built

RusStack: deploying...
[0%] start: Publishing 8a3ff7ff2fe4306354f64f6df3190e346845b27b7769f829cfd63375b22588c9:current_account-current_region
[0%] start: Publishing 8008ab1c17af8ecd8fc53056e00657560c1a9f152948aef259e79b63eee8fd05:current_account-current_region
[0%] start: Publishing 5647487aca1777e5cf4e15d43f03fd4f99bb93e808b834190ca8a35d7a09ec32:current_account-current_region
[33%] success: Published 8a3ff7ff2fe4306354f64f6df3190e346845b27b7769f829cfd63375b22588c9:current_account-current_region
[66%] success: Published 5647487aca1777e5cf4e15d43f03fd4f99bb93e808b834190ca8a35d7a09ec32:current_account-current_region
[100%] success: Published 8008ab1c17af8ecd8fc53056e00657560c1a9f152948aef259e79b63eee8fd05:current_account-current_region
RusStack: creating CloudFormation changeset...

 ❌  RusStack failed: Error: The stack named RusStack failed to deploy: CREATE_FAILED (Deployment failed)
    at FullCloudFormationDeployment.monitorDeployment (/Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at deployStack2 (/Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
    at /Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named RusStack failed to deploy: CREATE_FAILED (Deployment failed)
    at deployStacks (/Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:315:7)
    at initCommandLine (/Users/sazzad/.nvm/versions/node/v16.17.1/lib/node_modules/aws-cdk/lib/cli.ts:358:12)

Stack Deployments Failed: Error: The stack named RusStack failed to deploy: CREATE_FAILED (Deployment failed)

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: macos 13.0
- LocalStack: 1.2.0
```

**Comment by MJDeligan** [comment] 2022-11-03 22:52
We are likely facing the same problem. On 3 separate machines we've tried deploying the sample app (generated by cdklocal init sample-app) in multiple languages on different versions of aws-cdk-lib, aws-cdk and aws-cdk-local and with multiple ways of starting localstack.

It seems to fail for us as soon as an sqs-subscription is added to a topic.

We've tried:  

- **aws-cdk versions**:
    - 2.46.0
    - 2.50.0

- **localstack starting methods**:
    - docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
    - docker-compose up with [docker-compose file](https://github.com/localstack/localstack/blob/master/docker-compose.yml)
    - localstack cli (localstack start)

Running with --verbose contains the following:

`Stack cdk-test has an ongoing operation in progress and is not stable (CREATE_IN_PROGRESS (Deployment failed))`

We are following the [cdk-integration guide](https://docs.localstack.cloud/integrations/aws-cdk/).

This seems to be a problem with cdk-local and not localstack, since using the aws-local cli we are able to deploy the services that would be deployed by cdk-local.

**Comment by steffyP** [comment] 2022-11-04 11:13
Hi @sazzadabdulhasib and @MJDeligan ,

thanks for reporting. We are able to reproduce this issue with the sample-app.

Adding the logs here:
<details>
<summary>cdklocal deploy --verbose</summary>

## cdklocal output
```
CdkTestsStack: deploying...
[11:45:16] Retrieved account ID 000000000000 from disk cache
[11:45:16] Assuming role 'arn:aws:iam::000000000000:role/cdk-hnb659fds-deploy-role-000000000000-us-east-1'.
[11:45:16] Waiting for stack CDKToolkit to finish creating or updating...
[0%] start: Publishing 9b8cd215719374434ffa495047d66c0b08e37f59d77cba05290f062c1fcba8bb:current_account-current_region
[11:45:16] Retrieved account ID 000000000000 from disk cache
[11:45:16] Assuming role 'arn:aws:iam::000000000000:role/cdk-hnb659fds-file-publishing-role-000000000000-us-east-1'.
[11:45:16] [0%] check: Check s3://cdk-hnb659fds-assets-000000000000-us-east-1/9b8cd215719374434ffa495047d66c0b08e37f59d77cba05290f062c1fcba8bb.json
[11:45:16] Call failed: getBucketEncryption({"Bucket":"cdk-hnb659fds-assets-000000000000-us-east-1"}) => The server side encryption configuration was not found (code=ServerSideEncryptionConfigurationNotFoundError)
[11:45:16] [0%] upload: Upload s3://cdk-hnb659fds-assets-000000000000-us-east-1/9b8cd215719374434ffa495047d66c0b08e37f59d77cba05290f062c1fcba8bb.json
[100%] success: Published 9b8cd215719374434ffa495047d66c0b08e37f59d77cba05290f062c1fcba8bb:current_account-current_region
[11:45:16] Call failed: describeStacks({"StackName":"CdkTestsStack"}) => Stack with id CdkTestsStack does not exist (code=ValidationError)
[11:45:16] CdkTestsStack: checking if we can skip deploy
[11:45:16] CdkTestsStack: no existing stack
[11:45:16] CdkTestsStack: deploying...
[11:45:16] Attempting to create ChangeSet with name cdk-deploy-change-set to create stack CdkTestsStack
CdkTestsStack: creating CloudFormation changeset...
[11:45:16] Initiated creation of changeset: arn:aws:cloudformation:us-east-1:000000000000:changeSet/cdk-deploy-change-set/7b450e71; waiting for it to finish creating...
[11:45:16] Waiting for changeset cdk-deploy-change-set on stack CdkTestsStack to finish creating...
[11:45:16] Initiating execution of changeset arn:aws:cloudformation:us-east-1:000000000000:changeSet/cdk-deploy-change-set/7b450e71 on stack CdkTestsStack
[11:45:17] Execution of changeset arn:aws:cloudformation:us-east-1:000000000000:changeSet/cdk-deploy-change-set/7b450e71 on stack CdkTestsStack has started; waiting for the update to complete...
[11:45:17] Waiting for stack CdkTestsStack to finish creating or updating...
[11:45:17] Stack CdkTestsStack has an ongoing operation in progress and is not stable (CREATE_IN_PROGRESS)
CdkTestsStack | 0/6 | 11:45:16 AM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | CdkTestsStack
CdkTestsStack | 0/6 | 11:45:16 AM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack | BootstrapVersion
CdkTestsStack | 0/6 | 11:45:16 AM | UPDATE_IN_PROGRESS   | AWS::CloudFormation::Stack | CDKMetadata/Condition (CDKMetadataAvailable)
CdkTestsStack | 1/6 | 11:45:17 AM | CREATE_COMPLETE      | AWS::CloudFormation::Stack | CdkTestsQueue (CdkTestsQueue93097384)
CdkTestsStack | 2/6 | 11:45:18 AM | CREATE_COMPLETE      | AWS::CloudFormation::Stack | CdkTestsTopic (CdkTestsTopic65C33ED2)
CdkTestsStack | 3/6 | 11:45:18 AM | CREATE_COMPLETE      | AWS::CloudFormation::Stack | CDKMetadata/Default (CDKMetadata)
CdkTestsStack | 4/6 | 11:45:18 AM | CREATE_COMPLETE      | AWS::CloudFormation::Stack | CdkTestsQueue/Policy (CdkTestsQueuePolicyBF717E8A)
CdkTestsStack | 4/6 | 11:45:18 AM | CREATE_FAILED        | AWS::CloudFormation::Stack | CdkTestsStack

Failed resources:

 ❌  CdkTestsStack failed: Error: The stack named CdkTestsStack failed to deploy: CREATE_FAILED (Deployment failed)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:496:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at deployStack2 (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
    at /usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/usr/local/lib/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named CdkTestsStack failed to deploy: CREATE_FAILED (Deployment failed)
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:357:12)
[11:45:22] Reading cached notices from /Users/stefanie/.cdk/cache/notices.json

Stack Deployments Failed: Error: The stack named CdkTestsStack failed to deploy: CREATE_FAILED (Deployment failed)
[11:45:22] Error: Stack Deployments Failed: Error: The stack named CdkTestsStack failed to deploy: CREATE_FAILED (Deployment failed)
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:357:12)
```

## LocalStack logs
```
localstack_main  | 2022-11-04T10:45:18.969  INFO --- [   asgi_gw_1] l.request.internal.aws     : AWS sqs.GetQueueAttributes => 200
localstack_main  | 2022-11-04T10:45:18.973 DEBUG --- [uncthread111] l.u.c.template_deployer    : Dependency for resource {'Type': 'AWS::SNS::Subscription', 'DependsOn': ['CdkTestsQueuePolicyBF717E8A'], 'Metadata': {'aws:cdk:path': 'CdkTestsStack/CdkTestsQueue/CdkTestsStackCdkTestsTopic169D6339/Resource'}, 'LogicalResourceId': 'CdkTestsQueueCdkTestsStackCdkTestsTopic169D63390FFA94A0', 'Properties': {'Protocol': 'sqs', 'TopicArn': 'arn:aws:sns:us-east-1:000000000000:CdkTestsStack-CdkTestsTopic65C33ED2-f8cecfd6', 'Endpoint': 'arn:aws:sqs:us-east-1:000000000000:CdkTestsStack-CdkTestsQueue93097384-8d4c3387'}, '_state_': {}} not yet deployed: CdkTestsQueuePolicyBF717E8A {'Type': 'AWS::SQS::QueuePolicy', 'Properties': {'PolicyDocument': {'Statement': [{'Action': 'sqs:SendMessage', 'Condition': {'ArnEquals': {'aws:SourceArn': {'Ref': 'CdkTestsTopic65C33ED2'}}}, 'Effect': 'Allow', 'Principal': {'Service': 'sns.amazonaws.com'}, 'Resource': {'Fn::GetAtt': ['CdkTestsQueue93097384', 'Arn']}}], 'Version': '2012-10-17'}, 'Queues': [{'Ref': 'CdkTestsQueue93097384'}]}, 'Metadata': {'aws:cdk:path': 'CdkTestsStack/CdkTestsQueue/Policy/Resource'}, 'LogicalResourceId': 'CdkTestsQueuePolicyBF717E8A'}
localstack_main  | 2022-11-04T10:45:18.974 DEBUG --- [uncthread111] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "CdkTestsStack": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'CdkTestsQueueCdkTestsStackCdkTestsTopic169D63390FFA94A0', 'PhysicalResourceId': None, 'ResourceType': 'AWS::SNS::Subscription', 'Scope': [], 'Details': [], '_deployed': False}}] Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1412, in _run
localstack_main  |     self.do_apply_changes_in_loop(changes, stack)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1503, in do_apply_changes_in_loop
localstack_main  |     raise Exception(
localstack_main  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'CdkTestsQueueCdkTestsStackCdkTestsTopic169D63390FFA94A0', 'PhysicalResourceId': None, 'ResourceType': 'AWS::SNS::Subscription', 'Scope': [], 'Details': [], '_deployed': False}}]
```

</details>

<details>
<summary>cdklocal destroy --verbose (hangs, needs to be stopped then)</summary>

## LocalStack log loops with:
```
localstack_main  | 2022-11-04T10:47:02.248 DEBUG --- [   asgi_gw_1] l.u.c.template_deployer    : Running action "delete" for resource type "SNS::Subscription" id "CdkTestsQueueCdkTestsStackCdkTestsTopic169D63390FFA94A0"
localstack_main  | 2022-11-04T10:47:02.249 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
localstack_main  |     handler(self, self.context, response)
localstack_main  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
localstack_main  |     handler(chain, context, response)
localstack_main  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
localstack_main  |     skeleton_response = self.skeleton.invoke(context)
localstack_main  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
localstack_main  |     return self.dispatch_request(context, instance)
localstack_main  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
localstack_main  |     result = handler(context, instance) or {}
localstack_main  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
localstack_main  |     return self.fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 151, in operation_marker
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 608, in delete_stack
localstack_main  |     deployer.delete_stack()
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1106, in delete_stack
localstack_main  |     delete_resource(self, resource_id)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 787, in delete_resource
localstack_main  |     return execute_resource_action(resource_id, stack, ACTION_DELETE)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 825, in execute_resource_action
localstack_main  |     result = configure_resource_via_sdk(
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 888, in configure_resource_via_sdk
localstack_main  |     prop_value = prop_key(
localstack_main  |   File "/opt/code/localstack/localstack/services/cloudformation/models/sns.py", line 138, in sns_subscription_arn
localstack_main  |     return resource["PhysicalResourceId"]
localstack_main  | KeyError: 'PhysicalResourceId'
```
</details>

Afterwards, the deployment seems to work, but when trying to delete the successfully deployed stack, LocalStack loops with the same exception regarding `KeyError 'PhysicalResourceId'`

**Comment by MJDeligan** [comment] 2022-11-04 15:39
Hey @steffyP,

thanks for confirming.  

While deploying doesn't error out after destroying the stack, it does not seem to correctly deploy the stack. `cdklocal deploy` does not detect any changes and therefore does not seem to deploy the queue and subscription.

With aws-local:

```
awslocal sns list-topcis             -> lists 1 topic
awslocal sqs list-queues             -> lists 0 queues
awslocal sns list-subscriptions      -> lists 0 subscriptions
```
The topic seems to remain because it is not removed by `cdklocal destroy`.

**Comment by sazzadabdulhasib** [comment] 2022-11-04 18:24
Sorry, I forgot to add  localstack logs
### LocalStack logs
` 2022-11-04T18:22:55.923  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sts.AssumeRole => 200
2022-11-04T18:22:56.882  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 940.12ms
2022-11-04T18:22:56.883  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 940.71ms
2022-11-04T18:22:56.989  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 400 (ValidationError)
2022-11-04T18:22:57.075  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ssm.GetParameter => 400 (ParameterNotFound)
`

**Comment by MJDeligan** [comment] 2022-11-05 23:18
For now we will be using an older version of aws-cdk (v2.44.0) as a temporary solution.

I tried older versions of aws-cdk and this happens starting from [v2.45.0](https://github.com/aws/aws-cdk/releases/tag/v2.45.0). v2.44.0 works without error.

Given that this error occured whenever we added an sqs-topic-subscription it might be related to the bug fix regarding sqs queue policies and sns subscriptions ([issue](https://github.com/aws/aws-cdk/issues/21797), [commit](https://github.com/aws/aws-cdk/commit/cf43b03c0c6231f93ca1db0b24df7c623d55dd2b))

**Comment by steffyP** [comment] 2022-11-09 12:19
Hi @MJDeligan, hi @sazzadabdulhasib,

the issue should be resolved in the `latest` LocalStack image. Could you try to pull the image (`docker pull localstack/localstack:latest`) and give it another try? 🙏

**Comment by MJDeligan** [comment] 2022-11-09 14:09
Hey @steffyP,

the sample-app now works fine for me on aws-cdk@v.2.50.0 (latest). Thanks for the swift fix 👍

**Closed** 2022-11-22 09:26 UTC
Labels: type: bug, status: response required, area: integration/aws-cdk, status: confirmed
