### ISSUE TITLE
Any plan to support ElasticCache?

### ISSUE THREAD

**Issue by mirak94** [localstack/localstack#790] opened 2018-05-29 08:35 UTC
Hello guys,

Do you have any plans to add support for aws ElasticCache?

Thank you very much in advance!

**Comment by pingvinen** [comment] 2018-06-06 09:11
We simply use redis or memcached for that. If you do not need to orchestrate/manage ElastiCache that seems to work just fine.

**Comment by whummer** [comment] 2020-08-07 10:07
Thanks for reporting - closing as duplicate of #158

**Closed by whummer** 2020-08-07 10:07 UTC
Labels: api-request, feature-missing
