### ISSUE TITLE
Reached max retries: 4 when trying to use SNS

### ISSUE THREAD

**Issue by valonhaliti** [localstack/localstack#1125] opened 2019-02-13 11:10 UTC
I'm using Windows 10 and `localstack start` is working when I use only sns for environment variable SERVICES.
The problem is, when I'm trying to do a simple thing like list topics:
 `aws --endpoint-url=http://localhost:4575 sns list-topics`
It isn't working. It is giving me this error:
**An error occurred (502) when calling the ListTopics operation (reached max retries: 4): Bad Gateway**
Server was also logging some errors yesterday, but now that I wanted to report it isn't logging anything 😄.

**Comment by whummer** [comment] 2019-03-08 01:22
Thanks for reporting @valonhaliti . Can you try starting the localstack process with `DEBUG=1` and then post the error logs here?

**Comment by sleepyneko** [comment] 2019-04-05 20:49
I'll chime in here with my sns error using awslocal:
```
2019-04-05 13:46:08,879 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.140 Python/2.7.3 Darwin/18.2.0 botocore/1.12.130
2019-04-05 13:46:08,879 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--endpoint-url=http://localhost:4575', 'sns', 'publish', '--topic-arn', 'arn:aws:sns:us-east-1:123456789012:test_topic', '--message', 'Test Notification', '--debug']
2019-04-05 13:46:08,879 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x106b5f500>
2019-04-05 13:46:08,880 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x106162d70>
2019-04-05 13:46:08,880 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x106183e60>
2019-04-05 13:46:08,885 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x106a86320>
2019-04-05 13:46:08,886 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/michael.lai/anaconda2/lib/python2.7/site-packages/botocore/data/sns/2010-03-31/service-2.json
2019-04-05 13:46:08,908 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.sns: calling handler <function register_retries_for_service at 0x104d4c500>
2019-04-05 13:46:08,909 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: sns
2019-04-05 13:46:08,910 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sns: calling handler <function add_waiters at 0x106b638c0>
2019-04-05 13:46:08,922 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'topic-arn', <awscli.arguments.CLIArgument object at 0x106d54510>), (u'target-arn', <awscli.arguments.CLIArgument object at 0x106d545d0>), (u'phone-number', <awscli.arguments.CLIArgument object at 0x106d54910>), (u'message', <awscli.arguments.CLIArgument object at 0x106d54950>), (u'subject', <awscli.arguments.CLIArgument object at 0x106d54990>), (u'message-structure', <awscli.arguments.CLIArgument object at 0x106d549d0>), (u'message-attributes', <awscli.arguments.CLIArgument object at 0x106d54a10>)])
2019-04-05 13:46:08,922 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sns.publish: calling handler <function add_streaming_output_arg at 0x106b5f9b0>
2019-04-05 13:46:08,922 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sns.publish: calling handler <function add_cli_input_json at 0x10618fb90>
2019-04-05 13:46:08,923 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sns.publish: calling handler <function unify_paging_params at 0x106afb848>
2019-04-05 13:46:08,932 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/michael.lai/anaconda2/lib/python2.7/site-packages/botocore/data/sns/2010-03-31/paginators-1.json
2019-04-05 13:46:08,933 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sns.publish: calling handler <function add_generate_skeleton at 0x106aeb398>
2019-04-05 13:46:08,933 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sns.publish: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x106d54a90>>
2019-04-05 13:46:08,933 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sns.publish: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10616e250>>
2019-04-05 13:46:08,934 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.topic-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,934 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.sns.publish: calling handler <awscli.argprocess.ParamShorthandParser object at 0x106b6ded0>
2019-04-05 13:46:08,935 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'arn:aws:sns:us-east-1:123456789012:test_topic' for parameter "topic_arn": u'arn:aws:sns:us-east-1:123456789012:test_topic'
2019-04-05 13:46:08,935 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.target-arn: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,935 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.phone-number: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,935 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.message: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,935 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.sns.publish: calling handler <awscli.argprocess.ParamShorthandParser object at 0x106b6ded0>
2019-04-05 13:46:08,935 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'Test Notification' for parameter "message": u'Test Notification'
2019-04-05 13:46:08,936 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.subject: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,936 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.message-structure: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,936 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.message-attributes: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,936 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,936 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sns.publish.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x106bda8d0>
2019-04-05 13:46:08,936 - MainThread - botocore.hooks - DEBUG - Event calling-command.sns.publish: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x106d54a90>>
2019-04-05 13:46:08,937 - MainThread - botocore.hooks - DEBUG - Event calling-command.sns.publish: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10616e250>>
2019-04-05 13:46:08,937 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2019-04-05 13:46:08,937 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2019-04-05 13:46:08,937 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/michael.lai/anaconda2/lib/python2.7/site-packages/botocore/data/endpoints.json
2019-04-05 13:46:08,959 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x104d4bc80>
2019-04-05 13:46:08,961 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sns: calling handler <function add_generate_presigned_url at 0x104d04758>
2019-04-05 13:46:08,961 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2019-04-05 13:46:08,966 - MainThread - botocore.endpoint - DEBUG - Setting sns timeout as (60, 60)
2019-04-05 13:46:08,967 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: sns
2019-04-05 13:46:08,968 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sns.Publish: calling handler <function generate_idempotent_uuid at 0x104d4bed8>
2019-04-05 13:46:08,968 - MainThread - botocore.hooks - DEBUG - Event before-call.sns.Publish: calling handler <function inject_api_version_header_if_needed at 0x104d4d6e0>
2019-04-05 13:46:08,968 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=Publish) with params: {'body': {'Action': u'Publish', u'Message': u'Test Notification', 'Version': u'2010-03-31', u'TopicArn': u'arn:aws:sns:us-east-1:123456789012:test_topic'}, 'url': u'http://localhost:4575/', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.16.140 Python/2.7.3 Darwin/18.2.0 botocore/1.12.130'}, 'context': {'auth_type': None, 'client_region': 'us-east-1', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x107f5ad50>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
2019-04-05 13:46:08,968 - MainThread - botocore.hooks - DEBUG - Event request-created.sns.Publish: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x107f5ad10>>
2019-04-05 13:46:08,969 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sns.Publish: calling handler <function set_operation_specific_signer at 0x104d4bde8>
2019-04-05 13:46:08,969 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2019-04-05 13:46:08,969 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/

content-type:application/x-www-form-urlencoded; charset=utf-8
host:localhost:4575
x-amz-date:20190405T204608Z

content-type;host;x-amz-date
a6169bd922d70dc7895dc67f46f2f5e29286a113be0968aab1c04f52accd4a4e
2019-04-05 13:46:08,969 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20190405T204608Z
20190405/us-east-1/sns/aws4_request
f30b4f5df882bac07f7508c23bbfeb81c52f0a666b7bf53c9594a9a98276b039
2019-04-05 13:46:08,969 - MainThread - botocore.auth - DEBUG - Signature:
5f4a3663672fe682bc11cd7855150b51aaff930b6e762113a61eca056b66de14
2019-04-05 13:46:08,970 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://localhost:4575/, headers={'Content-Length': '124', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'Authorization': 'AWS4-HMAC-SHA256 Credential=_not_needed_locally_/20190405/us-east-1/sns/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=5f4a3663672fe682bc11cd7855150b51aaff930b6e762113a61eca056b66de14', 'X-Amz-Date': '20190405T204608Z', 'User-Agent': 'aws-cli/1.16.140 Python/2.7.3 Darwin/18.2.0 botocore/1.12.130'}>
2019-04-05 13:46:08,970 - MainThread - urllib3.util.retry - DEBUG - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-04-05 13:46:08,970 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost
2019-04-05 13:46:09,004 - MainThread - urllib3.connectionpool - DEBUG - http://localhost:4575 "POST / HTTP/1.1" 502 None
2019-04-05 13:46:09,005 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Fri, 05 Apr 2019 20:46:09 GMT', 'Server': 'BaseHTTP/0.3 Python/2.7.15'}
2019-04-05 13:46:09,005 - MainThread - botocore.parsers - DEBUG - Response body:


```

**Comment by whummer** [comment] 2019-11-27 22:57
Thanks for providing some details, but the logs do not provide much more insights. Closing this as potentially outdated, or "cannot reproduce". Please try to create a reproducible test case that we can systematically look into. Thank you.

**Closed by whummer** 2019-11-27 22:57 UTC
Labels: cannot-reproduce, needs-triaging
