### ISSUE TITLE
bug: can't delete s3 bucket

### ISSUE THREAD

**Issue by shonigbaum** [localstack/localstack#6869] opened 2022-09-14 06:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a bucket and want to delete ist, I get the message:

> An error occurred (NoSuchBucket) when calling the DeleteBucket operation: The specified bucket does not exist

### Expected Behavior

Bucket should be deleted.

Still works in localstack version 1.0.3.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

````
aws s3api create-bucket --endpoint http://localhost:4566 --region eu-central-1 --bucket "hallo"  --create-bucket-configuration LocationConstraint=eu-central-1

aws s3api delete-bucket --endpoint-url http://localhost:4566 --region eu-central-1 --bucket hallo
````

### Environment

```markdown
- OS: Ubuntu 20.04 (WSL)
- LocalStack: 1.1.0
```

**Comment by steffyP** [comment] 2022-09-14 08:04
Hi @shonigbaum,
thanks for your report. Unfortunately, I am not able to reproduce your issue.

Could you elaborate on how you start localstack? Simply running `docker run localstack/localstack` should normally use the `latest` image you have cached locally - which might be an older version and should have the `-dev` version included. 

To help us further analyze your problem, could you please set the environment variables: `DEBUG=1` and `LS_LOG=TRACE` when starting LocalStack and attach your log output? 🙏

**Comment by shonigbaum** [comment] 2022-09-14 08:56
Hey @steffyP,

I started docker like this:
``docker run --name localstack_main --rm -d -e HOSTNAME_EXTERNAL="localhost" -e DISABLE_EVENTS="1" -p 4566:4566 -p 8080-8081:8080-8081 "localstack/localstack:1.1.0"``

**Logs**
Create Bucket:
````
````

**Comment by shonigbaum** [comment] 2022-09-22 14:34
Hey @steffyP,

what I already noticed while testing: I can't create a bucket without the location contraint.
And I'm not using awslocal cli, I use the normal aws cli (v2.4.23) with --endpoint-url http://localhost:4566. But awslocal everything works.

Maybe there's a little difference between awslocal and original aws cli?

I will provide the logs tomorrow.

Thank you and kind regards
Sven

**Comment by steffyP** [comment] 2022-09-22 14:42
Hi @shonigbaum,

thanks for getting back to us!

>  With awslocal everything works.

That's interesting. Actually `awslocal` should only be a wrapper for the aws cli. Do you have any specific aws-settings, e.g in  `~/.aws/config`? What is the default-region you have configured?

> I will provide the logs tomorrow.
Thanks!

**Comment by shonigbaum** [comment] 2022-09-23 07:06
Hi @steffyP,

so, happy to found some time to provide you more information.
Btw ... is awslocal wrapping aws cli version 1 or 2?

---

~/.aws/config
```
[default]
region=eu-central-1
output=json
aws_account_id = 000000000000
```

~/.aws/credentials
```
[default]
aws_access_key_id = 000000000000000
aws_secret_access_key = 000000000000000000000000
```

---

**Version 1.1.0**

Logs: [logs-v1.1.0.txt](https://github.com/localstack/localstack/files/9631310/logs-v1.1.0.txt)
Diagnose: [diagnose-v1.1.0.json.gz](https://github.com/localstack/localstack/files/9631309/diagnose-v1.1.0.json.gz)

Steps:

```sh
docker run --rm -d -e DEBUG=1 -e LS_LOG=TRACE -e DISABLE_EVENTS="1" -p 4566:4566 -p 8080-8081:8080-8081 "localstack/localstack:1.1.0"

# does not work
aws s3api create-bucket --endpoint http://localhost:4566 --bucket "hallo"
# An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

# works
aws s3api create-bucket --endpoint http://localhost:4566 --bucket "hallo"  --create-bucket-configuration LocationConstraint=eu-central-1

# {
#    "Location": "http://hallo.s3.localhost.localstack.cloud:4566/"
# }

aws s3api list-buckets --endpoint-url http://localhost:4566
# {
#    "Buckets": [
#        {
#            "Name": "hallo",
#            "CreationDate": "2022-09-23T06:43:55+00:00"
#        }
#    ],
#    "Owner": {
#        "DisplayName": "webfile",
#        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
#    }
# }

# does not work
aws s3api delete-bucket --endpoint-url http://localhost:4566 --bucket hallo
# An error occurred (NoSuchBucket) when calling the DeleteBucket operation: The specified bucket does not exist

# does not work
aws s3api delete-bucket --endpoint-url http://localhost:4566 --bucket hallo --region eu-central-1
# An error occurred (NoSuchBucket) when calling the DeleteBucket operation: The specified bucket does not exist
```

--- 


**Version 1.0.3**

Log file: [logs-v1.0.3.txt](https://github.com/localstack/localstack/files/9631358/logs-v1.0.3.txt)
Diagnose: [diagnose-v1.0.3.json.gz](https://github.com/localstack/localstack/files/9631360/diagnose-v1.0.3.json.gz)


Steps:


```sh
docker run --rm -d -e DEBUG=1 -e LS_LOG=TRACE -e DISABLE_EVENTS="1" -p 4566:4566 -p 8080-8081:8080-8081 "localstack/localstack:1.0.3"

# does not work
aws s3api create-bucket --endpoint http://localhost:4566 --bucket "hallo"
# An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

# works
aws s3api create-bucket --endpoint http://localhost:4566 --bucket "hallo"  --create-bucket-configuration LocationConstraint=eu-central-1
# {
#    "Location": "http://hallo.s3.localhost.localstack.cloud:4566/"
# }

aws s3api list-buckets --endpoint-url http://localhost:4566
# {
#    "Buckets": [
#        {
#            "Name": "hallo",
#            "CreationDate": "2022-09-23T07:02:37+00:00"
#        }
#    ],
#    "Owner": {
#        "DisplayName": "webfile",
#        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
#    }
# }

# works
aws s3api delete-bucket --endpoint-url http://localhost:4566 --bucket hallo
```
---

Thank you :)

**Comment by steffyP** [comment] 2022-09-23 11:49
Hi @shonigbaum,

thanks so much for the detailed report! We were able to reproduce your issue with the configuration you provided.
It doesn't seem to be related to the cli-version though. 

>  Btw ... is awslocal wrapping aws cli version 1 or 2?

In theory, the wrapper can be used with both versions, [as described here](https://github.com/localstack/awscli-local).

What I found is a problem with a new feature we are introducing, related to account-ids. 
S3 cannot handle this feature yet, but with your current configuration it is somehow using a different account-id than expected (e.g., when using the aws-cli without the wrapper).

As a workaround,  you could change your `~/.aws/credentials` to the following, it should work (the `aws_access_key_id` has now 12 zeros, you currently have 15 in your config):
```
[default]
aws_access_key_id = 000000000000
aws_secret_access_key =000000000000000000000000
```
This worked at least for me, I hope it will also work for you :) 

That being said, we are currently heavily re-factoring the S3 provider, and the issue should be fixed in an upcoming version.

**Comment by shonigbaum** [comment] 2022-09-23 12:48
Ah! :) Shame on me. Thank you so much! Wish you a nice weekend! :-)

**Closed** 2022-09-23 12:51 UTC
Labels: type: bug, status: response required, aws:s3
