### ISSUE TITLE
localstack initialization is broken on Windows

### ISSUE THREAD

**Issue by nerdkid93** [localstack/localstack#678] opened 2018-03-23 17:45 UTC
After getting localstack installed and adding a `localstack.cmd` file to the `[python dir]\Scripts\` directory to correctly trigger `localstack` from any directory, I get errors when running `localstack start` because this line isn't creating a directory in a cross-platform compatible way: https://github.com/localstack/localstack/blob/be5687c5d003a02abb5ff4883f92c6e64bb835d1/localstack/services/install.py#L37

I am a Linux user trying to use this package for testing, but if can't work for my Windows teammates, then `localstack` is DOA, and we'll need to find other ways of testing AWS functionality.

**Comment by whummer** [comment] 2018-04-02 03:08
Thanks for reporting @nerdkid93 - should be fixed in #698 . Looks like this is a duplicate of #663 - please report on that issue if there are any other problems with installation in Windows. Thanks

**Closed by whummer** 2018-04-02 03:08 UTC
