### ISSUE TITLE
localstack [sns invoking lambda] and lambda update mongo issue.

### ISSUE THREAD

**Issue by amitdhawan** [localstack/localstack#801] opened 2018-06-07 04:40 UTC
Hi,

Im facing issue in updating my mongodb through lambda which is invoked through sns message.
My mongodb is locally hosted on my machine and i start the db thorugh mongod command on my terminal.

Im running local stack in docker by below command:-

```
docker run -it -e LAMBDA_EXECUTOR=docker -e DEBUG=1  -e TMPDIR=/private$TMPDIR -e SERVICES=sns,lambda -e LOCALSTACK_HOSTNAME=localstack -e DATA_DIR=/tmp/localstack/data -p 4567-4578:4567-4578 -p 8080:8080 localstack/localstack

```

Below is the shell script:-

```
 
jobStatusUpdateSNSTopic=`aws --endpoint-url=http://localhost:4575 sns create-topic \
--name jobstatustopic` \


echo "jobStatusUpdateSNSTopic: $jobStatusUpdateSNSTopic" 

jobStatusUpdateSNSTopicARN=`echo $jobStatusUpdateSNSTopic | jq ".TopicArn"` \

echo "jobStatusUpdateSNSTopicARN: $jobStatusUpdateSNSTopicARN" 


jobStatusLambda=`aws --endpoint-url=http://localhost:4574 lambda create-function \
--function-name jobStatusUpdateLambda_test \
--runtime nodejs6.10 \
--role r1 \
--environment "{\"Variables\":{\"MONGODB_URL\":\"mongodb://localhost:27017/testDb\"}}" \
--handler index.handler \
--zip-file fileb:///Users/amitdhawan/Desktop/Monotype/MLS/jobstatusupdate-lambda/job_status_update_lambda.zip` \

echo "jobStatusLambda: $jobStatusLambda" \


jobStatusLambdaArn=`echo $jobStatusLambda | jq ".FunctionArn"` 

echo "jobStatusLambdaArn: $jobStatusLambdaArn" 


# below snsstopic is hard coded....$jobStatusUpdateSNSTopicARN not found error coming
subscriptionArn=`aws --endpoint-url=http://localhost:4575 sns subscribe \
--topic-arn arn:aws:sns:us-east-1:123456789012:jobstatustopic \
--protocol lambda \
--notification-endpoint arn:aws:lambda:us-east-1:000000000000:function:jobStatusUpdateLambda_test` \

echo "subscriptionArn: $subscriptionArn"

message_attributes="{\"jobId\":{\"DataType\":\"String\",\"StringValue\":\"5aa665a74341890001c803b5\"},\"appId\":{\"DataType\":\"String\",\"StringValue\":\"testzipOnTestEnv\"},\"status\":{\"DataType\":\"String\",\"StringValue\":\"STARTED\"}}"
echo "message_attributes :  $message_attributes"		

publishsnsmessage=`aws --endpoint-url=http://localhost:4575 sns publish \
--topic-arn  $jobStatusUpdateSNSTopicARN \
--message JobStatusUpdate \
--message-attributes $message_attributes` \

echo "publishsnsmessage :  $publishsnsmessage"		

```

The respnse of above shell script is below:-

```
jobStatusUpdateSNSTopic: {
    "TopicArn": "arn:aws:sns:us-east-1:123456789012:jobstatustopic"
}
jobStatusUpdateSNSTopicARN: "arn:aws:sns:us-east-1:123456789012:jobstatustopic"
jobStatusLambda: {
    "TracingConfig": {}, 
    "FunctionName": "jobStatusUpdateLambda_test", 
    "VpcConfig": {
        "SubnetIds": [
            null
        ], 
        "SecurityGroupIds": [
            null
        ]
    }, 
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:jobStatusUpdateLambda_test", 
    "Environment": {
        "Variables": {
            "MONGODB_URL": "mongodb://fontdiscoverypreproduser:fdspreprod3#09@fontdisc-preprod-shard-00-00-cn7ye.mongodb.net:27017,fontdisc-preprod-shard-00-01-cn7ye.mongodb.net:27017,fontdisc-preprod-shard-00-02-cn7ye.mongodb.net:27017/dcstestenv?ssl=true&replicaSet=fontdisc-preprod-shard-0&authSource=admin"
        }, 
        "Error": {}
    }, 
    "Handler": "index.handler", 
    "Role": "r1", 
    "Runtime": "nodejs6.10"
}
jobStatusLambdaArn: "arn:aws:lambda:us-east-1:000000000000:function:jobStatusUpdateLambda_test"
subscriptionArn: {
    "SubscriptionArn": "arn:aws:sns:us-east-1:123456789012:jobstatustopic:107fdf6f-e340-4b59-86af-bed15f2859b0"
}
message_attributes :  {"jobId":{"DataType":"String","StringValue":"5aa665a74341890001c803b5"},"appId":{"DataType":"String","StringValue":"testzipOnTestEnv"},"status":{"DataType":"String","StringValue":"STARTED"}}
publishsnsmessage :  {
    "MessageId": "41935aba"
}

```

Im getting the MessageId in publish command of sns i.e. the message is getting posted but im not sure is my lambda getting invoked. If yes, my mongodb is not getting updated with the message sent to lambda.

Please suggest what im doing wrong.

**Comment by jonaskint** [comment] 2018-08-09 14:22
Check with ```docker ps -a``` if your lambda container is still there. You can access it's logs with through docker logs.

**Comment by jewelsjacobs** [comment] 2018-11-07 22:47
I'm having the same issue but trying to update postgres ...

**Comment by joerg-pfruender** [comment] 2019-05-24 13:40
@amitdhawan Maybe the root cause of the problem is the same as in https://github.com/localstack/localstack/issues/800 : "jq" does not work well during the initialization of the container?

**Comment by whummer** [comment] 2019-11-18 22:26
Thanks for reporting @amitdhawan @jewelsjacobs , closing this issue as outdated. Please re-open if the problem persists. Thanks

**Closed by whummer** 2019-11-18 22:26 UTC
