### ISSUE TITLE
bug: Creating SQS queue with `receive_wait_time_seconds = 1` fails

### ISSUE THREAD

**Issue by richardjhughes** [localstack/localstack#5197] opened 2021-12-28 16:18 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

SQS queue not created, with error:

> Error: error waiting for SQS Queue (http://localhost:4566/000000000000/my_queue_name) attributes to create: timeout while waiting for state to become 'equal' (last state: 'notequal', timeout: 2m0s)

### Expected Behavior

Queue created with no error message.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```bash
SERVICES=sqs localstack start
terraform apply -auto-approve
```

#### Terraform script

```terraform
provider "aws" {
  access_key = "test"
  secret_key = "test"
  region  = "us-east-1"
  s3_force_path_style = true
  skip_credentials_validation = true
  skip_metadata_api_check = true
  skip_requesting_account_id = true

  endpoints {
    sqs = "http://localhost:4566"
  }
}

resource "aws_sqs_queue" "my_queue" {
  name                      = "my_queue_name"
  receive_wait_time_seconds = 1    # If this is commented out, the queue is created successfully
}
```

### Environment

```markdown
- OS: MacOS Monterey & Windows 10
- LocalStack version: 0.13.2
- LocalStack Docker container id: b846f1f3ac71
- LocalStack build date: 2021-12-28
- LocalStack build git hash: 60d2c3dc
```

### Anything else?

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_sqs_queue.my_queue will be created
  + resource "aws_sqs_queue" "my_queue" {
      + arn                               = (known after apply)
      + content_based_deduplication       = false
      + deduplication_scope               = (known after apply)
      + delay_seconds                     = 0
      + fifo_queue                        = false
      + fifo_throughput_limit             = (known after apply)
      + id                                = (known after apply)
      + kms_data_key_reuse_period_seconds = (known after apply)
      + max_message_size                  = 262144
      + message_retention_seconds         = 345600
      + name                              = "my_queue_name"
      + name_prefix                       = (known after apply)
      + policy                            = (known after apply)
      + receive_wait_time_seconds         = 1
      + tags_all                          = (known after apply)
      + url                               = (known after apply)
      + visibility_timeout_seconds        = 30
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_sqs_queue.my_queue: Creating...
aws_sqs_queue.my_queue: Still creating... [10s elapsed]
aws_sqs_queue.my_queue: Still creating... [20s elapsed]
aws_sqs_queue.my_queue: Still creating... [30s elapsed]
aws_sqs_queue.my_queue: Still creating... [40s elapsed]
aws_sqs_queue.my_queue: Still creating... [50s elapsed]
aws_sqs_queue.my_queue: Still creating... [1m0s elapsed]
aws_sqs_queue.my_queue: Still creating... [1m10s elapsed]
aws_sqs_queue.my_queue: Still creating... [1m20s elapsed]
aws_sqs_queue.my_queue: Still creating... [1m30s elapsed]
aws_sqs_queue.my_queue: Still creating... [1m40s elapsed]
aws_sqs_queue.my_queue: Still creating... [1m50s elapsed]
aws_sqs_queue.my_queue: Still creating... [2m0s elapsed]
╷
│ Error: error waiting for SQS Queue (http://localhost:4566/000000000000/my_queue_name) attributes to create: timeout while waiting for state to become 'equal' (last state: 'notequal', timeout: 2m0s)
│ 
│   with aws_sqs_queue.my_queue,
│   on terraform.tf line 15, in resource "aws_sqs_queue" "my_queue":
│   15: resource "aws_sqs_queue" "my_queue" {
```

**Comment by BrianHarboldt** [comment] 2022-01-04 20:03
I am also seeing this happen with redrive_policy.
My current workaround is to comment both redrive_policy and receive_wait_time_seconds out and then execute. After completion re-add/uncomment and rerun to set those values properly, which then succeeds.

**Comment by brandonsaurus** [comment] 2022-01-05 19:35
I am seeing this happen when using Terraform with a SQS resource. I do not have `redrive_policy` set but I do have `receive_wait_time_seconds` set.
Downgrading localstack (confirmed with 0.11.6) I am able to retrieve the get-queue-attributes response successfully, whereas in later versions (0.12.18+) I am not.

**Comment by SwatsonCodes** [comment] 2022-01-07 00:13
I am currently investigating this issue. It seems to be related to a change in terraform and/or the AWS provider. As a temporary workaround, you may use Terraform `0.13.7` and the AWS provider version < `3.7.0`, like so:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.60.0, <= 3.69.0"
    }
  }

  required_version = "0.13.7"
}
```
I realize this is far from an ideal solution, but I offer it in case it's useful in the meantime as I work to get the code up to date.

**Comment by brandonsaurus** [comment] 2022-01-07 16:15
@SwatsonCodes Your suggestion worked for me, thank you for the response.

**Comment by SwatsonCodes** [comment] 2022-01-07 20:12
not sure what changed but I am no longer able to reproduce this issue 🤔

**Comment by mattbartel-tyler** [comment] 2022-01-07 20:43
The latest version of the terraform aws provider (3.71.0 released ~20 hours ago) fixed it for me.

**Comment by SwatsonCodes** [comment] 2022-01-07 20:56
great catch @mattbartel-tyler , looks like that was it. closing this issue.

**Closed by SwatsonCodes** 2022-01-07 20:56 UTC
Labels: bug, needs-triaging, aws:sqs

**Comment by alekspickle** [comment] 2022-03-17 11:06
I get this only on localstack with `sqs_managed_sse_enabled = true`. 
Provider version: 4.3.0
Terraform version: 1.0.0

**Comment by Deku-shrub** [comment] 2023-03-17 18:27
I worked around this issue by taking the active AWS aws_sqs_queue policy and putting it back into the code. This involved adding a 'version' statement and matching the brackets with the production policy definition
