### ISSUE TITLE
SES does not work with RawEmail

### ISSUE THREAD

**Issue by franlas23** [localstack/localstack#616] opened 2018-02-15 10:35 UTC
When try to sen a new message:
```
15-02-2018 11:08:49.647 [pool-1-thread-6] INFO  c.a.http.DefaultErrorResponseHandler.parseXml - Unable to parse HTTP response (Invocation Id:bc083852-aed8-c4cf-5d4c-2ed1452e4126) content to XML document '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
' 
org.xml.sax.SAXParseException: Son necesarios espacios en blanco entre publicId y systemId.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanExternalID(XMLScanner.java:1072)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.scanDoctypeDecl(XMLDocumentScannerImpl.java:642)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:924)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:162)
	at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:169)
	at com.amazonaws.http.DefaultErrorResponseHandler.parseXml(DefaultErrorResponseHandler.java:124)
	at com.amazonaws.http.DefaultErrorResponseHandler.documentFromContent(DefaultErrorResponseHandler.java:105)
	at com.amazonaws.http.DefaultErrorResponseHandler.createAse(DefaultErrorResponseHandler.java:84)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:71)
	at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:47)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1621)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.doInvoke(AmazonSimpleEmailServiceClient.java:5123)
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.invoke(AmazonSimpleEmailServiceClient.java:5099)
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.executeSendRawEmail(AmazonSimpleEmailServiceClient.java:3643)
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.sendRawEmail(AmazonSimpleEmailServiceClient.java:3620)
	```

**Comment by grvhi** [comment] 2018-07-11 17:57
I have just come across the same problem. The exception raised in the localstack logs is this:

```
Error on request:
Traceback (most recent call last):
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
result = self.callback(request, request.url, {})
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/moto/core/responses.py", line 116, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/moto/core/responses.py", line 199, in _dispatch
return self.call_action()
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/moto/core/responses.py", line 273, in call_action
response = method()
File "/Users/george/.pyenv/versions/2.7.10/lib/python2.7/site-packages/moto/ses/responses.py", line 78, in send_raw_email
source = self.querystring.get('Source')[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

This can be resolved by setting a string value for the `Source` kwarg in `send_raw_email`. It is safe to set this kwarg to use the same value as the `From` header set within the email itself. However, the boto3 docs note that this kwarg is not required, so this is still a bug.

**Comment by whummer** [comment] 2020-03-08 18:29
Thanks for reporting @franlas23 @grvhi . It's been a while since this has been reported - has this issue been solved in the meantime? Can you please provide a small, self-contained example that helps reproduce this issue? We'll be happy to look into it if you can provide some more details. Thanks!

**Closed** 2020-03-18 04:08 UTC
Labels: bug, feature-missing, needs-triaging
