### ISSUE TITLE
bug: I'm trying to connect to ws using docker but it doesnt work any idea?

### ISSUE THREAD

**Issue by emanuel1542** [localstack/localstack#7814] opened 2023-03-07 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
wscat -c ws://localhost:4510                       
Connected (press CTRL+C to quit)
Disconnected (code: 1000, reason: "")
```

### Expected Behavior

```
wscat -c ws://localhost:4510                       
Connected (press CTRL+C to quit)
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
wscat -c ws://localhost:4510                       
Connected (press CTRL+C to quit)
Disconnected (code: 1000, reason: "")
```

```
awslocal apigatewayv2 get-apis 
{
    "Items": [
        {
            "ApiEndpoint": "ws://localstack_main:4510",
            "ApiId": "6077adf1",
            "Description": "Serverless Websockets",
            "Name": "local-veo-websockets",
            "ProtocolType": "WEBSOCKET",
            "RouteSelectionExpression": "$request.body.action"
        }
    ]
}
```
```
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro
    ports:
      - "4566:4566"
      - "4571:4571"
      - "4510:4510"
    environment:
      - SERVICES=${SERVICES- }
      # - SERVICES=${SERVICES-dynamodb,s3,lambda }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
```

### Environment

```markdown
- OS:
- LocalStack:
```

### Anything else?

no

**Comment by whummer** [comment] 2023-03-26 21:42
Hi @emanuel1542, thanks for reporting. Can you please share a few more details about your environment setup - I'm assuming that you're running the `wscat` command from the host (i.e., outside of Docker). Are there any API Gateway authorizers or special routes defined for the WebSockets API?

We've recently added a number of enhancements - can you please pull the `latest` Docker image and give it another try? Thanks!

**Comment by whummer** [comment] 2023-04-08 21:14
Hi @emanuel1542 - quick follow-up, were you able to run a few more test using the `latest` Docker image? Please keep us posted on how it goes, or whether we can close this issue.. Thanks!

**Comment by whummer** [comment] 2023-04-16 12:57
Closing as due to inactivity - please do let us know if the problem persists, we'll be happy to provide guidance if we can create a reproducible example. 👍  Thanks

**Closed by whummer** 2023-04-16 12:57 UTC
Labels: type: bug, area: infrastructure, status: response required, aws:apigatewayv2
