### ISSUE TITLE
Localstack ec2 instance connection issue

### ISSUE THREAD

**Issue by durgadeviramadoss** [localstack/localstack#2560] opened 2020-06-15 10:41 UTC
Hi Team,

I have installed localstack on ubuntu 16.04

Localstack installed successfully and could able to run all the commands related to aws ec2 instance creation

Below are the set of set commands i have ran
**VPC Creation**

> Step 1:  Create VPC 
aws ec2 create-vpc --cidr-block 10.0.0.0/16 --endpoint-url=http://localhost:4597 
Step 2: Create Subnets using VPC ID
aws ec2 create-subnet --vpc-id <Created VPC ID> --cidr-block 10.0.1.0/24 --endpoint-url=http://localhost:4597
Step 3: Create 2nd Subnet
aws ec2 create-subnet --vpc-id <Created VPC-ID> --cidr-block 10.0.0.0/24 --endpoint-url=http://localhost:4597
Step 4: Create internet gateway  
aws ec2 create-internet-gateway --endpoint-url=http://localhost:4597
Step 5: Attach the Internet gateway to your VPC using internet-gateway-id
aws ec2 attach-internet-gateway --vpc-id <Created VPC-ID> --internet-gateway-id <Created internet-gateway-id> --endpoint-url=http://localhost:4597
Step 6: Create a custom route table for your VPC.
aws ec2 create-route-table --vpc-id <Created VPC-ID> --endpoint-url=http://localhost:4597
Step 7: Create a route in the route table that points all traffic (0.0.0.0/0) to the Internet gateway. 
aws ec2 create-route --route-table-id <Created route-table-id> --destination-cidr-block 0.0.0.0/0 --gateway-id <Created internet-gateway-id> --endpoint-url=http://localhost:4597
Step 8: To confirm that your route has been created and is active, you can describe the route table and view the results. 
aws ec2 describe-route-tables --route-table-id <Created route-table-id> --endpoint-url=http://localhost:4597
Step 9: Associate Routetable to subnet
aws ec2 associate-route-table  --subnet-id <provide subnet-id> --route-table-id <Created route-table-id> --endpoint-url=http://localhost:4597
Step 10: Subnet to have Publicip
aws ec2 modify-subnet-attribute --subnet-id <provide subnet-id> --map-public-ip-on-launch --endpoint-url=http://localhost:4597
> 

**SecurityGroup Creation**

> EC-2 Security Group: 
Step 1: Create security Group
aws ec2 create-security-group --group-name my-sg --description "My security group" --vpc-id <Created VPC-ID> --endpoint-url=http://localhost:4597
 Step 2: Add rules to security group
aws ec2 authorize-security-group-ingress --group-id <Created security-group-id> --protocol tcp --port 22 --cidr 0.0.0.0/0 --endpoint-url=http://localhost:4597

**Key-pair Creation**

> aws ec2 create-key-pair --key-name <key-pairnam> --query 'KeyMaterial' --output text > <key-pairnam>.pem --endpoint-url=http://localhost:4597

**Instance Creation**

> aws ec2 run-instances --image-id ami-0ce2e5b7d27317779 --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids <Created security-group-id> --subnet-id subnet-a457f5df --endpoint-url=http://localhost:4597

When i tried to ssh to the created instance i am getting connection timed out

> Durgadevi.ramadoss@xxx:~$ ssh -i "localstack-ec2.pem"  ec2-user@54.214.30.244
**ssh: connect to host 54.214.30.244 port 22: Connection timed out**

**My issue is not able to access the created instance. Please guide me**

Thanks in advance

**Comment by clarkbains** [comment] 2020-07-14 15:03
localstack does not actually create the resource. It only mocks the aws apis. Therefore you will not be able to access the created instance via ssh, since there is no actual instance.

**Comment by whummer** [comment] 2020-08-02 20:39
Thanks for reporting @durgadeviramadoss . Please note that launching EC2 instances (i.e., creating actual virtual machines that you can connect to via EC2) is not (yet) fully supported in LocalStack. Closing this issue as a duplicate of #1996 - let's please continue the discussion on the other issue... Thanks!

**Closed by whummer** 2020-08-02 20:39 UTC
