### ISSUE TITLE
Localstack suddenly stopped working

### ISSUE THREAD

**Issue by steowens** [localstack/localstack#5152] opened 2021-12-20 17:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had localstack installed and it had been working fine for quite a while.  But then when I restarted it this morning (a thing I have done several times in the past without error) the system fails to come up because it cannot seem to start S3.  

I tried doing a pip install -U localstack to see if maybe there are changes that fix the issue and I noticed that it gives the following errors:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 1.19.34 requires botocore==1.20.34, but you have botocore 1.23.24 which is incompatible.
awscli 1.19.34 requires s3transfer<0.4.0,>=0.3.0, but you have s3transfer 0.5.0 which is incompatible.
Successfully installed boto3-1.20.24 botocore-1.23.24 commonmark-0.9.1 deepdiff-5.7.0 dill-0.3.2 docker-5.0.0 localstack-0.13.1.2 localstack-client-1.28 localstack-ext-0.13.1 localstack-plugin-loader-1.1.1 ordered-set-4.0.2 pbr-5.8.0 psutil-5.8.0 pygments-2.10.0 python-dotenv-0.19.2 rich-10.16.1 s3transfer-0.5.0 semver-2.13.0 stevedore-3.5.0 tabulate-0.8.9 tailer-0.4.1 websocket-client-1.2.3
C02WT117HTDG:iam-garage sowens$ pip install -U botocore
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: botocore in /usr/local/lib/python3.9/site-packages (1.23.24)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python3.9/site-packages (from botocore) (1.25.11)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.9/site-packages (from botocore) (2.8.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.9/site-packages (from botocore) (0.10.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore) (1.15.0)
C02WT117HTDG:iam-garage sowens$ pip install -U s3transfer
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```

### Expected Behavior

Localstack starts up and runs without error.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

### Environment

```markdown
- OS: MacosX
- LocalStack: 
localstack --version
0.13.1.2
```

**Comment by acraven** [comment] 2021-12-20 17:52
Apologies if I've created a duplicate of this (see https://github.com/localstack/localstack/issues/5154). My issue started happening today despite being happy for a number of months.

My issue was also in 0.12.10 and fixed in 0.12.11 but wanted to record it in case anyone else has the same issue.

**Comment by dominikschubert** [comment] 2021-12-20 20:08
The certificate we bundle for *.s3.localhost.localstack.cloud was renewed today and there were some minor issues that should be resolved now. Please try again and let us know if you continue to experience these issues.

**Comment by kiview** [comment] 2021-12-21 09:24
@dominikschubert At which point does this certificate get bundled? I am just trying to understand how the image starts to work again, without you needing to push a new image to the Docker Hub.

Some Testcontainers users were affected by this yesterday, so I want to understand how we can support them in the best way 🙂

**Comment by dominikschubert** [comment] 2021-12-21 09:28
> @dominikschubert At which point does this certificate get bundled? I am just trying to understand how the image starts to work again, without you needing to push a new image to the Docker Hub.
> 
> Some Testcontainers users were affected by this yesterday, so I want to understand how we can support them in the best way slightly_smiling_face

The certificate is currently fetched on startup from our artifacts repository, which is why no changes in the image itself were necessary for this fix.

**Comment by whummer** [comment] 2022-01-03 22:22
Thanks @steowens @kiview @dominikschubert . Looks like the issue with S3 and the certificate has been resolved in the meantime. Closing this issue, but please do let us know if the problem persists. (We'll make sure that there will be no interruptions when the certificate gets updated next time..) Thanks!

**Closed by whummer** 2022-01-03 22:22 UTC
Labels: bug, needs-triaging, infra-startup
