### ISSUE TITLE
bug: AWS .NET SDK S3 Pre-Signed Url does not appear to be supported

### ISSUE THREAD

**Issue by wyatttroutman** [localstack/localstack#6229] opened 2022-06-07 18:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
I am generating a pre-signed URL with localstack using the AWS .NET SDK class, AmazonS3Client. I've found that the URL currently being output by the `GetPreSignedUrl` method of that class does not work for uploading to a localstack S3 bucket.

Here is a sample output: `https://localhost-bucket.localhost:4566/public/0a95d139-e834-478a-a856-06bc9f9bd906/test?AWSAccessKeyId=....&Expires=.....&Signature=%.....%3D`

You can see that the bucket name is prepending the localhost name. Localstack does not seem to support this format. If I try to PUT a file to this URL in postman, I get this error:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>public</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```
Presumably because it is trying to recognize the `public` folder as the bucket name, which does not exist.

If I manually shuffle around the generated URL to be something like:
`https://localhost:4566/localhost-bucket/public/24c7e57a-5df7-413b-9c18-4e6efa491cc2/test?AWSAccessKeyId=....&Expires=....&Signature=%....%3D`

then it works. 

### Expected Behavior

I would expect for the S3 pre-signed generated URL from the AWS .NET SDK to be supported by Localstack.

### How are you starting LocalStack?

With a docker-compose file

##### Run docker compose to deploy the application stack, including localstack, to local environment.
    docker-compose ....

##### Create the test bucket
    aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket localhost-bucket --region us-east-1

### Environment

```markdown
- OS: Windows
- LocalStack: latest
```

### Anything else?

Seems kind of related to: https://github.com/localstack/localstack/issues/3266

**Comment by bentsku** [comment] 2022-12-21 17:17
Hi and thanks for your report!

You're right, LocalStack does not support having the bucket prefixed before `localhost` directly.

There are two solutions to this, related to the [configuration of your S3 Client](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Config.html) in the SDK:

- Use a different endpoint for LocalStack, specific for s3, which accepts having the bucket in the host: `http://s3.localhost.localstack.cloud:4566` as your `ServiceURL`. I'm not an expert in .NET, so bear with me, but it could look like this.
```csharp
var config = new AmazonS3Config { ServiceURL = "http://s3.localhost.localstack.cloud:4566" };
var s3client = new AmazonS3Client(config);
```
This endpoint will accept the host addressed bucket request, the pre-signed URL will look like:
`http://{bucket-name}.s3.localhost.localstack.cloud/{key-name}?{queryParams}`
We also have some [documentation about setting the endpoint with the AWS .NET SDK.](https://docs.localstack.cloud/user-guide/integrations/sdks/dotnet/)

- Second solution, use the path addressed bucket, making the bucket part of the path instead, like you did manually. 
```csharp
var config = new AmazonS3Config { ForcePathStyle = true };
var s3client = new AmazonS3Client(config);
```
This will force the SDK to use the path style, having your pre-signed URL look like:
`http://localhost:4566/{bucket-name}/{key-name}?{queryParams}`

There is a similar issue with the Javascript SDK, you can see it here: #7295

Hope that fixes your issue!

In the meantime, we have been working on a new implementation of S3, and it is now available under a feature flag. You can try starting LocalStack with PROVIDER_OVERRIDE_S3=asf (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)). We have overhauled the service globally, and pre-signed URL are part of it, and our efforts to increase parity will be directed towards this new implementation. It will become the default in the next major release.

We'd appreciate the feedback as well!

**Comment by mikomatic** [comment] 2023-01-26 10:48
Hello, I had the same issue with the AWS Java V2 SDK V2 - this was solved by configuring the client with the endpoint `http://s3.localhost.localstack.cloud:4566`  (instead of  `http://localhost:4566`) as suggested @bentsku 

Thanks !

**Comment by bentsku** [comment] 2023-02-06 21:58
As it seems the issue can be resolved with the solution provided above, I'll close the issue. Don't hesitate to open again if the issue is still present! Thanks again for the report and the feedback.

**Closed by bentsku** 2023-02-06 21:58 UTC
Labels: type: usage, aws:s3, area: integration/aws-sdk-dotnet

**Comment by pkoch** [comment] 2023-03-01 22:23
For reference, in the Ruby client, I didn't have to supply a different endpoint, but I did have to set `force_path_style: true` in my client's options.
