### ISSUE TITLE
localstack cloudformation fails to parse my template file

### ISSUE THREAD

**Issue by bnegrao** [localstack/localstack#803] opened 2018-06-12 22:49 UTC
Hello,
I'm trying to deploy to localstack cloudformation a lambda app with a simple template.yml file
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Function
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: helloworld-bucket
        Key: "some-key"
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          PARAM1: param1
          PARAM2: param2      
  HelloApiGateway: 
    Type: "AWS::ApiGateway::Resource"
    Properties: 
      RestApiId: 
        Ref: "HelloWorldFunction"
      ParentId: 
        Fn::GetAtt: 
          - "HelloWorldFunction"
          - "RootResourceId"
      PathPart: "/hello"  
```       

It fails with the error:

```
2018-06-12T22:46:07:ERROR:localstack.services.generic_proxy: Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
path=path, data=data, headers=forward_headers)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 152, in forward_request
return execute_change_set(req_data)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 107, in execute_change_set
TemplateBody=template)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
operation_model, request_dict)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 148, in make_request
return self._send_request(request_dict, operation_model)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 175, in _send_request
request, operation_model, attempts)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 256, in _get_response
response_dict, operation_model.output_shape)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 240, in parse
parsed = self._do_error_parse(response, shape)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 473, in _do_error_parse
root = self._parse_xml_string_to_dom(xml_contents)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 425, in _parse_xml_string_to_dom
"invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

```

Bellow are the commands I use to package and deploy:

```
aws --endpoint-url=http://localhost:4581 cloudformation package --template-file ./template.yaml --s3-bucket helloworld-bucket --output-template-file packaged-samapp.json
aws --endpoint-url=http://localhost:4581  cloudformation deploy --template-file /home/bruno.zica/zz/sam-app/packaged-samapp.json --stack-name HELLO_WORLD_STACK2
```

**Comment by I159** [comment] 2018-06-15 15:20
I'm experiencing the same issue with `create-stack`, `deploy`.

 ```
aws --endpoint-url=http://localhost:4581 cloudformation create-stack --stack-name speechmatics_integration --region us-east-1

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'
```

```
localstack==0.8.6.2
localstack-client==0.4
localstack-ext==0.8.6
boto==2.46.1
boto3==1.7.39
botocore==1.10.39
```

**Comment by bnegrao** [comment] 2018-06-26 19:05
I was able to deploy stacks to localstack's cloudformation service using the template.JSON format, not yaml.
I had to remove every intrinsic function from the json. 
And it looks like localstack's cloudformation does not suport "AWS::Serverless::Function", so I had to deploy my lambda function straight to localstack's lambda service, using "aws cli create-lambda..."

**Comment by johnhaley81** [comment] 2018-11-09 19:12
I also left a comment on https://github.com/localstack/localstack/issues/965 but I'm hitting the same issue and using the `json` format I still hit the issue.

It sounds like there's some internal bug in the code that cloudformation stacks hit quite often that hasn't either been patched or hasn't made its way upstream yet.

**Comment by ahmed-abdulmoniem** [comment] 2018-12-21 12:06
Any solution to this so far?

**Comment by tcbenkhard** [comment] 2019-10-22 07:12
Am experiencing the same issue with a clean serverless project, using serverless-localstack plugin and the default hello handler.

Node Version:              12.12.0
Framework Version:         1.54.0
Plugin Version:            3.1.2
SDK Version:               2.1.2
Components Core Version:   1.1.2
Components CLI Version:    1.4.0

**Comment by whummer** [comment] 2019-10-22 07:27
@tcbenkhard Thanks for reporting . CloudFormation support has been much improved in the meantime, could you please post any error logs (with `DEBUG=1` enabled) and share a few snippets of code to reproduce this issue? Thanks

**Comment by whummer** [comment] 2019-10-30 14:07
Closing this issue as "cannot reproduce" for now. Please re-open and provide more details (error logs, sample project to reproduce the issue) if the problem persists. Thanks!

**Closed by whummer** 2019-10-30 14:07 UTC
Labels: cannot-reproduce, needs-triaging, priority-high

**Comment by nicchristeller** [comment] 2021-07-05 02:30
Had this occur when my JSON template had `\t` characters included for formatting: removing them fixed the issue.
