### ISSUE TITLE
SqsException: Concurrent access: Queue already exists

### ISSUE THREAD

**Issue by drewboardman** [localstack/localstack#3977] opened 2021-05-06 14:28 UTC
# Type of request: This is a ...

[X ] (possible) bug report

# Detailed description
I'm using the Java AWS SDK in an integration test. The particulars are:

* Scala project running with ScalaTest and sbt
* `testcontainers` is used with a docker-compose file
* The test creates an sqs queue and sends a message
* before the test run, `docker ps` returns an empty result, no running containers. This is the expected success state.
Upon running the test, two containers show up

```
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS                  PORTS                                                                                                      NAMES
dd9cc725ce8c   localstack/localstack:0.11.0   "docker-entrypoint.sh"   2 seconds ago   Up Less than a second   0.0.0.0:4566-4599->4566-4599/tcp, :::4566-4599->4566-4599/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   eazc9c9prwzr_localstack_1
5519f8fd0c3c   testcontainers/ryuk:0.3.1      "/app"                   3 seconds ago   Up 1 second             0.0.0.0:49166->8080/tcp, :::49166->8080/tcp                                                                testcontainers-ryuk-21704f24-b42a-455f-b19a-9c92f0ed30b3
```

One of these containers is started by testcontainers, the other one seems to be a straight `docker compose up`. It's as if the queue already exists on one of the containers and is conflicting with creation of the queue during the test run. This behavior is flaky and sometimes does not occur.

I'm not 100% sure that this is a localstack issue. It's possible that it could be either the java sdk or testcontainers.

However `createQueue` in the java SDK is only executed once, even on failures.

**Comment by whummer** [comment] 2021-12-16 20:46
Thanks for reporting @drewboardman . This is potentially related to persistence configuration - are you using `DATA_DIR` in your LocalStack container environment, by any chance? This would explain why the queue already exists when you're starting up your app. 

Closing this issue as outdated as it's been a while since it was reported. Please do let us know if the problem persists (ideally with a small sample project or detailed steps to reproduce) - we'll be happy to look into it in more detail.. Thanks!

**Closed by whummer** 2021-12-16 20:46 UTC
Labels: needs-triaging, java, needs-tests, aws:sqs, integration:aws-sdk
