### ISSUE TITLE
Does LocalStack support HTTP Integrations in ApiGateway (Websockets)?

### ISSUE THREAD

**Issue by sbenali** [localstack/localstack#4719] opened 2021-10-11 16:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Using a websocket apigatewayv2 in localstack and i need to change the body of the request e.g. add the connectionid, which is something i can do with a HTTP integration on the AWS gateway, however when I try this with localstack i receive the following error "Unsupported integration type "HTTP" for Websocket API ID" and then prints the ID of the API, if this feature is not enabled then how should we test the actual API where the connectionId and other things are added to the request body

**Comment by lhegarty** [comment] 2021-10-12 23:18
+1 for this issue. Can get this to work in the real API GW v2 by connecting using a websocket and outputting a HTTP request in 'HTTP' mode for the $connect route. In Localstack Pro it just flat out rejects the websocket connection when in HTTP mode as commenter above mentions. Can get it to connect in HTTP_Proxy mode and it does some Template Selection Expression transformation (albeit incorrectly + in proxy mode it shouldn't by transforming). Trying to get my organisation to sign up for an enterprise license but it's a hard sell with this issue!

**Comment by sbenali** [comment] 2021-10-13 10:28
hi @whummer, quick update to say that on HTTP integration it no longer drops the socket, however the request which comes through has no body or content-type header which means the template wasnt applied...thank u

**Comment by lhegarty** [comment] 2021-10-15 08:37
Hey @whummer, any news on if this issue has been triaged etc? We currently have a ticket in our sprint to setup our local apigw v2 and we've marked it as blocked awaiting this :) We're implementing a live webchat feature for our customers so having a working localstack apigw for our websocket would be great! 

If it's going to be a while though let me know and we'll move to using the real infrastructure instead.

**Comment by lhegarty** [comment] 2021-11-03 12:55
Hey guys, we've done a work around to use the real infrastructure for now for API GW; would love to know a timeline of when this issue might be played as we would like to be able to use localstack for our local development infrastructure as opposed to a real gateway.

**Comment by whummer** [comment] 2021-11-07 20:23
Hey @sbenali @lhegarty , apologies for the delay on this one - somehow the notifications on this issues must have slipped through the cracks. We'll look into this with high priority now.. Thanks for your help!

**Comment by lhegarty** [comment] 2021-11-07 20:27
Hey @whummer , appreciate the update thanks :) if you need any help diagnosing anything then please let me know.

**Comment by sbenali** [comment] 2021-11-08 13:00
thank you @whummer , this will make a big difference for us, plz let me know if i can do anything to assist

**Comment by whummer** [comment] 2021-11-08 13:10
Thanks @sbenali . Quick note on your sample - looks like the static values for `request_parameters` should be enclosed in single quotes (see docs [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_integration#example-usage)). So, instead of this...:
```
  request_parameters = {
    "integration.request.header.content-type" = "application/json"
  }
```
... it should be:
```
  request_parameters = {
    "integration.request.header.content-type" = "'application/json'"
  }
```

We're still in the process of testing your sample end-to-end - will keep you posted on the progress.. Thanks

**Comment by whummer** [comment] 2021-11-08 14:18
Quick update @sbenali @lhegarty . We have now pushed a couple of enhancements for API GW v2 WebSocket integrations - can you please pull the `latest` Docker image and give it another try?

@sbenali after slightly modifying the sample you've provided (using "http://example.com" as the `integration_uri`), we :
```
% wscat -c ws://localhost:4511
Connected (press CTRL+C to quit)
# note: $connect action triggers the first call to example.com
# triggering "sendMessage" action below:
> {"action":"sendMessage"}
< <!doctype html>
<html>
<head>
    <title>Example Domain</title>
...
``` 

@lhegarty - in case you are still seeing this issue, can you please provide a small sample to help us reproduce this issue? Thanks!

**Comment by lhegarty** [comment] 2021-11-09 16:19
Hey @whummer , appreciate the work you are doing on this. Pulled down the latest image and I'm seeing the following behaviour..

- Content-type is not being pulled through correctly.
- User-Agent is not being pulled through
- Template selection expression has to be named after content-type and is not applying as intended.

These are the headers that I am setting in postman.

![Screenshot 2021-11-09 at 16 10 57](https://user-images.githubusercontent.com/26256165/140961339-f288966a-363c-468b-98b4-40ba14f9b85a.png)

Websocket connects successfully under HTTP which is great. When posting to the app though I get..

```
Nest] 35492   - 09/11/2021, 15:54:54   [ExceptionsHandler] Unsupported Media Type: %s +2599ms
FastifyError: Unsupported Media Type: %s
```
This is despite the header being set as shown above.
---

When I force the content type within my application.. some of the selection expression templates aren't applying correctly.

Line 370 on https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py looks as though we have to name our template selection expression after the content type? This isn't the case with the normal gateway but for now we've called our template 'application/json' ; in our actual application we've called it $default

Here is my initial request.

```
{
    "action": "myGatewayRoute",
    "message": {
        "randomProperty": "hello world", 
        "randomProperty2": "foo", 
        "randomProperty3": "bar"
    }
}
```

Here is my selection expression. 

```
  {
      "connectionId":"$context.connectionId",
      "payload": "$util.escapeJavaScript($input.json('$.message'))",
      "userAgent": "$context.identity.userAgent"
  }
```

And this is what we're getting through the gateway..

```
body: {
  connectionId:'db70591e'
  payLoad:'[]'
  userAgent:'$context.identity.userAgent'
}
```
connectionId is working brilliantly 👍  

What I would expect to see from the above template/headers is

```
body: {
  connectionId:'db70591e',
  payload: '{"randomProperty": "hello world", "randomProperty2": "foo", "randomProperty3": "bar" }',
  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0t'
}
```
I can see you've made some commits whilst I've been writing this response however so I shall try with those updates!

Hope this helps.

**Comment by whummer** [comment] 2021-11-13 01:58
Thanks for the update @lhegarty . We have now pushed a couple of enhancements for extracting the request details via different selection expressions. Can you please pull the `latest` image again and give it another try? Thanks for your help!

**Comment by lhegarty** [comment] 2021-11-13 08:51
Hey @whummer , progress! We're now seeing the userAgent pull through from the User-Agent header on the body as expected 👍 The payload property however is still pulling through as an empty array and not mapping the properties on the internal message object to it.

**Comment by calvernaz** [comment] 2022-01-24 12:42
Hi @lhegarty, do you still have the project around so I can reproduce?

**Comment by lhegarty** [comment] 2022-01-24 13:10
Hey @calvernaz , yes however unfortunately I'm unable to send you the project code due to it being a corporate project; I can explain steps to reproduce however :) 

We are using a NestJs app with Fastify which we send HTTP requests to using API GW v2. Hopefully that should be easy to scaffold with a controller? Our request pattern looks like this

Client (Websocket connection to gateway) -> API GW v2 (Template selection expression + HTTP) -> NestJs app

In the gateway, we are modifying our request so that it meets the contract of our nestjs app. 

We send it this
```
{
    "action": "$gatewayRoute",
    "message": {
        "randomProperty": "hello world", 
        "randomProperty2": "foo", 
        "randomProperty3": "bar"
    }
}
```
With these headers

![image](https://user-images.githubusercontent.com/26256165/150787884-552c69c4-c46e-4122-847a-26835d90d828.png)

We apply a selection expression to it in the gateway

```
  {
      "connectionId":"$context.connectionId",
      "payload": "$util.escapeJavaScript($input.json('$.message'))",
      "userAgent": "$context.identity.userAgent"
  }
```

and it ends up coming out the gateway on the other side like this

```
body: {
  connectionId:'db70591e',
  payload: '{"randomProperty": "hello world", "randomProperty2": "foo", "randomProperty3": "bar" }',
  userAgent: 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0t'
}
```

---
Only in our localstack v2 gateway when we set to HTTP, it doesn't match this behaviour.

Fastify doesn't recognise the content-type and we get this

`Nest] 35492   - 09/11/2021, 15:54:54   [ExceptionsHandler] Unsupported Media Type: %s +2599ms
FastifyError: Unsupported Media Type: %s`

and the request into our app doesn't meet the expected results (this is after we've monkey patched to avoid the content-type issue)

```
body: {
  connectionId:'db70591e'
  payLoad:'[]'
  userAgent:'$context.identity.userAgent'
}
```

Hope that helps a bit?

**Comment by calvernaz** [comment] 2022-01-24 13:45
@lhegarty thanks, working on it :)

**Comment by calvernaz** [comment] 2022-01-28 13:57
Hi, @lhegarty a fix for this issue was merged so I'd encourage you to give it a try with the `latest` docker image.

I have a couple of remarks tho.

You're right when you say AWS allows naming the templates with different names than `application/json`. I verified myself that that's the case and found terraform examples where it shows that. However, the documentation states something different either in boto and terraform documentation (example below). 

The current implementation is following what the documentation says, so you should name your template, at least with LocalStack, `application/json`. We can look at this and eventually improve for other content types, but at the moment that's where we are. I will also follow up with AWS to understand their recommendation.


Boto [documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewayv2.html#ApiGatewayV2.Client.create_integration):

```
Represents a map of Velocity templates that are applied on the request payload 
based on the value of the Content-Type header sent by the client. 
The content type value is the key in this map, and the template (as a String) is the value. 
Supported only for WebSocket APIs.
```

**Closed** 2022-02-09 14:23 UTC
Labels: question, PRO, awaiting reporter response, aws:apigatewayv2
