### ISSUE TITLE
Unable to import module lambda

### ISSUE THREAD

**Issue by conan19842002** [localstack/localstack#3807] opened 2021-03-31 10:34 UTC
# Type of request: This is a bug

[x] bug report
[ ] feature request

# Detailed description
I've tried to create a mock lambda function and invoked the function with some payload. However, I got this error 
```
{'errorMessage': 'Lambda process returned error status code: 1. Result: {"errorMessage": "Unable to import module \'test_lambda_py\'"}
```
I then checked if the function was created successfully with the below command:
```
aws lambda list-functions --endpoint http://localhost:4566 --region eu-west-1
```
and here is output:
```
{
    "Functions": [
        {
            "FunctionName": "test_lambda_py",
            "FunctionArn": "arn:aws:lambda:eu-west-1:000000000000:function:test_lambda_py",
            "Runtime": "python3.8",
            "Role": "r1",
            "Handler": "test_lambda_py.handler",
            "CodeSize": 1284,
            "Description": "",
            "Timeout": 3,
            "LastModified": "2021-03-31T10:01:54.105+0000",
            "CodeSha256": "Bh1QPJ8WNDBI8+BoXapVLWDyLqbEqlPDLRAFNmzUZa8=",
            "Version": "$LATEST",
            "VpcConfig": {},
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "caa99c75-c5a2-4fbe-9800-bbd7d4291c2a",
            "State": "Active",
            "LastUpdateStatus": "Successful",
            "PackageType": "Zip"
        }
    ]
}
```
I could not find anything wrong with the way the lambda function was created so have no idea what was going on
## Expected behavior
The lambda function should be invoked without error
...

## Actual behavior
The function was created successfully but failed to be invoked with error
```
{'errorMessage': 'Lambda process returned error status code: 1. Result: {"errorMessage": "Unable to import module \'test_lambda_py\'"}
```

# Steps to reproduce

## Command used to start LocalStack
1. Start localstack
2. Create a mock lambda function
3. Invoke the function for testing
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
confest.py
```

import pytest
import json
import boto3
import botocore
from pathlib import Path
import os

from zipfile import ZipFile

from botocore.exceptions import ClientError
import logging

logger = logging.getLogger(__name__)

LOCALSTACK_ENDPOINT = 'http://localhost:4566'
REGION = 'eu-west-1'    
CONFIG = botocore.config.Config(retries={'max_attempts': 0})
RESOURCES = Path(__file__).parent / "resources"

class LambdaClient:
    """
    A mock of the context object that is passed to the lambda function
    """

    def __init__(self):
        self.lambda_client = self._lambda_client()
        self.function_name = "mock-lambda-function"

    def _lambda_client(self):
        return boto3.client(
            service_name='lambda',
            region_name=REGION,
            endpoint_url=LOCALSTACK_ENDPOINT
        )
    def invoke_with_invocation_type(self):
        return self.lambda_client.invoke(
            FunctionName=self.function_name,
            InvocationType='RequestResponse'
        )
    def invoke_with_payload(self, function_name, payload):
        return self.lambda_client.invoke(
            FunctionName=self.function_name if function_name is None else function_name,
            Payload=payload
        )
    
    def get_function(self):
        return self.lambda_client.get_function(FunctionName=self.function_name)


    def create_function(self, function_name, lambda_python, lambda_zip, handler, runtime, role):
        
        self.create_lambda_zip(lambda_python, lambda_zip)
        with open(lambda_zip, 'rb') as f:
            zipped_code = f.read()
        
        self.lambda_client.create_function(
            FunctionName=function_name,
            Runtime=runtime,
            Role=role,
            Handler=f"{function_name}.{handler}",
            Code=dict(ZipFile=zipped_code)
        )
        return self.lambda_client
        
    
    def create_lambda_zip(self, lambda_python, lambda_zip):
        with ZipFile(lambda_zip, 'w') as z:
            z.write(lambda_python)
   
    def delete_lambda(function_name, lambda_zip):
   
@pytest.fixture
def lambda_client():
    return LambdaClient()

```
lambda_function.py:
```
import logging
import urllib.request
import boto3
import botocore
from os import environ
import json
LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)
CONFIG = botocore.config.Config(retries={'max_attempts': 0})
LOCALSTACK_HOSTNAME = environ['LOCALSTACK_HOSTNAME']
def get_s3_client():
    return boto3.client('s3', aws_access_key_id='', aws_secret_access_key='', region_name='eu-west-1',
                            endpoint_url=f'http://{LOCALSTACK_HOSTNAME}:4566', config = CONFIG)

def handler(event, context):
    LOGGER.info('I\'m putting something in S3')
    s3_client = get_s3_client()
    s3_client.put_object(
        Bucket= 'mock-gp-bucket',
        Key="mock-key",
        Body='mock-body'
    )
    response = {
        "statusCode": 200,
        "body": "Training is completed",
        "isBase64Encoded": False,
        # additional headers can be passed here..
    }
    return response
   
```
test_lambda.py:
```
import pytest
import json

TEST_LAMBDA_PYTHON = 'lambda_function.py'
TEST_LAMBDA_NAME_PY = 'test_lambda_py'
TEST_LAMBDA_ZIP = 'test_lambda.zip'

def test_lambda_runtimes(lambda_client):
   
    # deploy and invoke lambda - Python 3.8
    lambda_client.create_function(function_name=TEST_LAMBDA_NAME_PY, lambda_python=TEST_LAMBDA_PYTHON, 
            lambda_zip=TEST_LAMBDA_ZIP, handler='handler.lambda_handler', runtime=LAMBDA_RUNTIME_PYTHON38, role='r1')

    result = lambda_client.invoke_with_payload(function_name=TEST_LAMBDA_NAME_PY, payload=b'{}')
    assert result['StatusCode'] == 200
    result_data = result['Payload'].read()
    assert to_str(result_data).strip() == '{}'

```

**Comment by mgagliardo** [comment] 2021-04-04 21:44
Hello @conan19842002, looks like you might have issues either with your code and/or your docker-compose (if you are using that). Please check the config below, it should work for you.

docker-compose.yml
```
version: '3.4'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - HOST_TMP_FOLDER=${PWD}/localstack_tmp
      - SERVICES=lambda,s3
    volumes:
      - ${PWD}/localstack_tmp:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

lambda_function.py (hardcoded access/secret keys and changed main function to `lambda_handler`):
```
import logging
import urllib.request
import boto3
import botocore
from os import environ
import json
LOGGER = logging.getLogger()
LOGGER.setLevel(logging.INFO)
CONFIG = botocore.config.Config(retries={'max_attempts': 0})
LOCALSTACK_HOSTNAME = environ['LOCALSTACK_HOSTNAME']
def get_s3_client():
    return boto3.client('s3', aws_access_key_id='test', aws_secret_access_key='test', region_name='eu-west-1',
                            endpoint_url=f'http://{LOCALSTACK_HOSTNAME}:4566', config = CONFIG)

def lambda_handler(event, context):
    LOGGER.info('I\'m putting something in S3')
    s3_client = get_s3_client()
    s3_client.put_object(
        Bucket= 'mock-gp-bucket',
        Key="mock-key",
        Body='mock-body'
    )
    response = {
        "statusCode": 200,
        "body": "Training is completed",
        "isBase64Encoded": False,
        # additional headers can be passed here..
    }
    return response
```

Process/command line arguments:
```
$ zip -9 -r test_lambda_py.zip .
```

Please note the following argument, the `--handler` is `$file_name.$function_name`, so `lambda_function.lambda_handler`:
``` 
$ awslocal lambda create-function --function-name test_lambda_py --zip-file fileb://test_lambda_py.zip --handler lambda_function.lambda_handler --runtime python3.8 --role test
```

Create bucket:
```
$ awslocal s3 mb s3://mock-gp-bucket
```

Invoke:
```
$ awslocal lambda invoke --function-name test_lambda_py test.txt
```

Output:
```
localstack_1  | 2021-04-04T21:38:56:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test_lambda_py result / log output:
localstack_1  | {"statusCode":200,"body":"Training is completed","isBase64Encoded":false}
localstack_1  | > START RequestId: 5d2fbaee-aeed-1f78-c2a1-01130f795b16 Version: $LATEST
localstack_1  | > [INFO]	2021-04-04T21:38:56.472Z	5d2fbaee-aeed-1f78-c2a1-01130f795b16	I'm putting something in S3
localstack_1  | > END RequestId: 5d2fbaee-aeed-1f78-c2a1-01130f795b16
localstack_1  | > REPORT RequestId: 5d2fbaee-aeed-1f78-c2a1-01130f795b16	Init Duration: 512.95 ms	Duration: 202.34 ms	Billed Duration: 203 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB	
```

File output:
```
$ cat test.txt 
{"body":"Training is completed","isBase64Encoded":false,"statusCode":200}
```

Let me know if you run into any issues, I'm closing this as can't reproduce in any case. Cheers!

**Closed by mgagliardo** 2021-04-04 21:44 UTC
Labels: awaiting reporter response, cannot-reproduce, service:s3

**Comment by YisusThreepwood** [comment] 2021-05-09 07:43
Hi @mgagliardo,

Thanks a lot for your help!. I had the same issue and It seems that the issue was with my docker compose file.

No need to rename the lambda handler to lambda_handler

**Comment by tudor2004** [comment] 2021-09-14 12:25
@YisusThreepwood what exactly was wrong with your docker-compose file?

**Comment by YisusThreepwood** [comment] 2021-09-14 13:58
> @YisusThreepwood what exactly was wrong with your docker-compose file?

uuuummmm, Sorry but I can't remember. I think that my issue was because I was using empty as the default value for the HOST_TMP_FOLDER environment variable and I was using that default value for getting the container up, but I am not sure
