### ISSUE TITLE
Transfer-encoding: chunked fails for S3 PUT request

### ISSUE THREAD

**Issue by peter-formlogic** [localstack/localstack#2925] opened 2020-09-03 02:30 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
localstack does not support http chunked uploads.  I've attached two wireshark dumps, one with chunked uploading & the other not.  Both are valid HTTP requests but if the request is chunked (i.e, `transfer-encoding: chunked` in the header), then I am seeing errors from localstack.

[wireshark.zip](https://github.com/localstack/localstack/files/5165791/wireshark.zip)

Depending on the size of the request, I sometimes see the following:

```
2020-09-03T02:22:39:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request PUT http://localhost:4566/example-bucket/43/f4/43f4ed24-7d0c-41e3-bb4d-565852551287/report.log: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1043, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 965, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1043, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 965, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 86, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 54, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 69, in forward_request
    response = function(url, data=data, headers=headers, verify=False, stream=True)
  File "/opt/code/localstack/localstack/utils/common.py", line 1148, in _wrapper
    return method(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

```

## Expected behavior
Chunked Transfers are supported

## Actual behavior
Localstack fails and throws an exception, returning either a 400 or 500

# Steps to reproduce
## Command used to start LocalStack
Using standard docker image (version `0.11.4`)

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Using `rusoto` rust client.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-247) by [Unito](https://www.unito.io/learn-more)

**Comment by peter-subscale** [comment] 2020-09-06 22:30
Just an update: If you specify the `content-length` header in the request, then it appears to work.  This is a little bit of a pain though, as sometimes you may not know the entire length of the request (i.e, if you are generating a file in memory).

However: I would expect that at least a `411 Length Required` would be returned in this case, rather than bomb out.

**Comment by whummer** [comment] 2020-09-15 16:41
Thanks for reporting @peter-subscale . Glad you've been able to find a workaround in the meantime, but still we'd like to ensure that the behavior is identical to the one on real AWS. You mentioned that you're using the `rusoto` Rust client - any chance you can share a small, isolated sample project with a simple test to help reproduce this issue? Thanks for your help!

**Comment by chrisharrisonkiwi** [comment] 2020-09-29 20:56
Also worth noting here, chunked requests to an elasticsearch instance within localstack also appear to have issues.
Adding content length may not be possible depending on what library you are using to generate queries

**Comment by whummer** [comment] 2021-12-13 10:07
Closing this issue as outdated - chunked encoding S3 uploads should be working in the meantime (also covered by some integration tests in this repo). 

@chrisharrisonkiwi - it's been a while since you've posted the issue, but would you mind helping create a new issue with steps to reproduce the Elasticsearch issue? That would be super helpful - thanks!

**Closed by whummer** 2021-12-13 10:07 UTC
Labels: needs-triaging, diverges-from-aws, aws:s3

**Comment by chrisharrisonkiwi** [comment] 2021-12-16 02:44
Yup, happy to close.
Although I was never able to specify content length due to the dynamic nature of what was being served, I ended up using an alternative technique.

**Comment by pablosichert** [comment] 2024-02-10 23:11
Not looking to reopen this issue, just leaving this here for posterity:

> Closing this issue as outdated - chunked encoding S3 uploads should be working in the meantime (also covered by some integration tests in this repo).

This doesn't seem correct, the [tests](https://github.com/localstack/localstack/blob/49ddea2ac66d25c6d3598a52b3b286134a91f670/tests/aws/services/s3/test_s3.py#L2692-L2719) I found regarding "chunked encoding" are related to AWS [`Content-Encoding: aws-chunked`](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html), not `Transfer-Encoding: chunked` as per this issue's title. Please correct me if I'm wrong.

As far as I'm aware, using `Transfer-Encoding: chunked` with S3 is currently not possible and will yield a `501 Not Implemented` response from AWS.
