### ISSUE TITLE
bug: S3 presigned URL ignores HOSTNAME_EXTERNAL

### ISSUE THREAD

**Issue by cabeaulac** [localstack/localstack#6301] opened 2022-06-19 16:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My `docker-compose.yml` has HOSTNAME_EXTERNAL set. My web app hits an APIGW REST endpoint to create an S3 presigned post URL like this
```
        data = s3_client.generate_presigned_post(
            bucket_name,
            key,
            Fields=additional_fields,
            Conditions=None,
            ExpiresIn=expires_in,
        )
        return data
```
My docker-compose.yml looks like this
```
version: '3.8'

services:
  localstack:
    # Rolled back from version 0.14.0 to get lambda functions to work
    # see https://github.com/localstack/localstack/issues/5432
    # image: "localstack/localstack:0.14.2"
    #image: "localstack/localstack:0.14.3.1"
    image: "localstack/localstack:latest"
    # @sha256:9fe2eb9c1d86e728a3cd5dd4f184cd50b6ab399b091ef1933b5bb82ebaa6898e
    networks:
      devnet:
#        ipv4_address: 169.254.170.3
    ports:
      - "8001:8080"            # only required for Pro
      - "53:53"                # only required for Pro
      - "53:53/udp"            # only required for Pro
      - "443:443"              # only required for Pro
      - "4510-4560:4510-4560"  # only required for Pro
      - "4566:4566"
      - "4571:4571"
    environment:
      # - SERVICES=s3,secretsmanager,apigateway,lambda,iam,dynamodb,stepfunctions,route53,cloudfront,sts
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse}
      # Tell Localstack to put Lambda containers on the same shared network
      - LAMBDA_DOCKER_NETWORK=devnet
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      # - HOSTNAME=localstack
      - MAIN_CONTAINER_NAME=localstack
      - HOSTNAME_EXTERNAL=host.docker.internal
      #      - USE_SSL=false
      # - DNS_ADDRESS=127.0.0.11
      # - HOSTNAME=localstack
      # - HOSTNAME_EXTERNAL=localstack
      # - DNS_RESOLVE_IP=169.254.170.3
      # - DOCKER_BRIDGE_IP=169.254.170.1
      # - LOCALSTACK_HOSTNAME=host.docker.internal
      # - CLOUDFRONT_STATIC_PORTS=1

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

The returned URL to the web app look like this:
```
url: "http://169.254.170.4:4566/fp-chad-local-bucket-us-east-1"
```

### Expected Behavior

The returned URL to the web app should look like this:
```
url: "http://host.docker.internal:4566/fp-chad-local-bucket-us-east-1"
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose -f auto_tests/docker-compose.yml up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using the CLI to call presign does not reproduce the error. You have to run a boto3 client to call `s3client.generate_presigned_post(...)`

For example, this does not reproduce the problem.
```
$ aws --endpoint-url=http://host.docker.internal:4566 s3 presign s3://fp-chad-local-bucket-us-east-1/stuff.txt
```

### Environment

```markdown
- OS: ubuntu:latest
- LocalStack: latest PRO
```

**Comment by MarcelStranak** [comment] 2022-06-20 09:40
I have tried  it with this simple script and I could not reproduce your issue. 

```python
import boto3

endpoint_url = "http://localhost:4566"

bucket_name = "my-bucket"
key = "test/a1"

expires_in = 24*60*60

s3_client = boto3.client('s3') 

response = s3_client.generate_presigned_post(bucket_name, key, ExpiresIn=expires_in)

print(response['url'])
print(response['fields'])
```

**docker-compose.yml**

```docker
---
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - '8001:8080'
      - '53:53'
      - 53:53/udp
      - '443:443'
      - 4510-4560:4510-4560
      - '4566:4566'
      - '4571:4571'
    environment:
      - DEBUG=${DEBUG-1 }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=123_REAL_LOCALSTACK_API_KEY
      - MAIN_CONTAINER_NAME=localstack
      - HOSTNAME_EXTERNAL=host.docker.internal
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

output:
```json
{
    "url": "https: //my-bucket.s3.amazonaws.com/",
    "fields": {
        "key": "test/a1",
        "AWSAccessKeyId": "None",
        "policy": "XXX",
        "signature": "XXX"
    }
}
```

**Comment by sergolius** [comment] 2022-08-28 21:07
Upd: Presigned URL generated via CLI has `localhost` as host, but URL generated via SDK(AWS) request has `Endpoint`(`aws.Config{}.Endpoint`) as host.

**Comment by sergolius** [comment] 2022-12-08 22:14
@macnev2013  `HOSTNAME_FROM_LAMBDA=localhost` has no impact. URL still referenced to `localstack:4566`

**Comment by macnev2013** [comment] 2022-12-09 05:00
Hi @sergolius, Thanks for responding.

Would it be possible to share detailed steps (localstack version, commands, code snippets) that you use for this task?

**Comment by sergolius** [comment] 2022-12-09 13:50
@macnev2013 I use free version of LocalStack and the latests docker image.

`docker-compose.localstack.yml`

```yaml
version: "3.9"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - volume:/var/lib/localstack
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  volume:
```

Connection:
```go
sess, err := session.NewSession(&aws.Config{
	Credentials:      credentials.NewStaticCredentials(cfg.AccessKey, cfg.SecretKey, ""),
	Endpoint:         aws.String(endpoint),
	Region:            aws.String(cfg.Region),
	S3ForcePathStyle: aws.Bool(true),
})

s3svc := s3.New(sess)
s3uploader := s3manager.NewUploader(sess)
```

Utilization:
```go
req, _ := s3svc.GetObjectRequest(&s3.GetObjectInput{
	Bucket: aws.String(cfg.Bucket),
	Key:    aws.String(key),
})
return req.Presign(time.Hour)
```

`s3svc` used for managing objects. `s3uploader` used to upload files.

Default configuration via ENV:
```
ACCESS_KEY=test
SECRET_KEY=test
REGION=us-east-1
BUCKET=test
ENDPOINT=http://localstack:4566
```

Bucket for region created manually.

**Comment by chris-stetter** [comment] 2023-05-23 07:24
Is this still an issue on Localstack 2?

**Comment by cabeaulac** [comment] 2023-05-23 15:31
I was able to resolve it in my API Gateway Lambda by setting the AWS endpoint explicitly and using a PUT URL like this. I haven't tested the POST again in awhile.
When I don't set the s3_endpoint URL like this, **I get the wrong post URL still**. I have not tried using `HOSTNAME_FROM_LAMBDA=localhost` as @sergolius suggested above yet, but I will. Although in my case Localstack is running in Docker so I'll have to set it to `host.docker.internal`.

```python
UPLOAD_ROLE = os.environ["UPLOAD_ROLE"]
LOCALSTACK = int(os.environ["LOCALSTACK"])

if LOCALSTACK:
    LOCALSTACK_ENDPOINT = os.environ.get('LOCALSTACK_ENDPOINT', 'http://host.docker.internal:4566')
else:
    LOCALSTACK_ENDPOINT = None


def handler(event, _):
    logger.info(f"handler event: {event}")
    logger.info(f"Localstack {LOCALSTACK}")
    logger.info(f"Localstack_endpoint {LOCALSTACK_ENDPOINT}")

    # Assume the IAM role that's allowed to upload objects to the target bucket
    # We do this because we have to create the S3 Signed URL with these credentials,
    # so the receiver of the Signed URL will have permissions to do the upload.
    sts_client = get_client.client("sts")
    assume_response = sts_client.assume_role(
        RoleArn=UPLOAD_ROLE,
        RoleSessionName=f"{event['requestContext']['requestId']}-upload-file-role",
        DurationSeconds=30*60,
    )
    credentials = assume_response["Credentials"]
    s3 = boto3.client(
        "s3",
        region_name=os.environ["AWS_REGION"],
        config=boto3.session.Config(signature_version='s3v4', ),
        endpoint_url=LOCALSTACK_ENDPOINT,
        aws_access_key_id=credentials["AccessKeyId"],
        aws_secret_access_key=credentials["SecretAccessKey"],
        aws_session_token=credentials["SessionToken"],)
        
    # Then I use that S3 client to generate a presigned PUT URL like this
    method_parameters = {
            "Bucket": bucket_name,
            "Key": key,
            "ContentType": file_type,
        }
    data = s3_client.generate_presigned_url(
            ClientMethod="put_object", Params=method_parameters, ExpiresIn=expires_in
        ) 
```

**Comment by bentsku** [comment] 2023-05-23 21:49
Hi @cabeaulac and thanks for providing a resolution here.

I can add a bit of context to this solution: generating a pre-signed URL is a _pure client-side operation_. Whichever tool you will use, SDK or the CLI, will use the credentials it has configured to sign the request you want to execute. In a regular setting, your SDK will sign your request before sending it to AWS. When generating a pre-signed URL, it will instead use those credentials to pre-signed that URL, and make it non-temperable. 

So, when generating these URLs, it won't even try to send a request to LocalStack, as it will all happen inside your SDK. That's why configuring LocalStack won't change the kind of URL you get.

Creating your S3 client with the hostname you want your pre-signed URL to use is the only way, as you've now done. 

Also, please note that when using pre-signed URL with LocalStack, if you want to validate that these are actually valid, you can set `S3_SKIP_SIGNATURE_VALIDATION=0` to actually enforce their validation. However, the pre-signed URL need to be created with the `test`/`test` credentials (`access_key`/`secret_access_key`), that's a shortcoming for now. 

I'll close the issue as it is now resolved, thanks for all your reports!

**Closed by bentsku** 2023-05-23 21:49 UTC
Labels: type: usage, aws:s3, aws:lambda
