### ISSUE TITLE
Unable to start localstack on Windows platform

### ISSUE THREAD

**Issue by konkonstantinidis** [localstack/localstack#663] opened 2018-03-13 07:56 UTC
Hi,
I have installed localstack on my Windows machine ( dir : C:\Program Files\Python36\Lib\site-packages)

and when im trying >localstack start , I get the following response : 

'localstack' is not recognized as an internal or external command,
operable program or batch file.

I want also to mention that i have added the directories to the PATH. (set PATH=%PATH%;C:\Program Files\Python36\Lib\site-packages)

**Comment by dev-bandai** [comment] 2018-03-19 07:06
Since I also output a similar error, I gave it to python with an absolute path, but the following error occurs.

```
C:\Users\dev_bandai>python C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\Scripts\localstack start
Starting local dev environment. CTRL-C to quit.
2018-03-19T14:44:05:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
ERROR: 'mkdir -p C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra': b'\x83R\x83}\x83\x93\x83h\x82\xcc\x8d\\\x95\xb6\x82\xaa\x8c\xeb\x82\xc1\x82\xc4\x82\xa2\x82\xdc\x82\xb7\x81B\r\n'
Error starting infrastructure: Command 'mkdir -p C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra' returned non-zero exit status 1. Traceback (most recent call last):
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 136, in install_components
    parallelize(install_component, names)
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 716, in parallelize
    result = pool.map(func, list)
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 130, in install_component
    install_elasticsearch()
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 37, in install_elasticsearch
    run('mkdir -p %s' % INSTALL_DIR_INFRA)
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 618, in run
    return do_run(cmd)
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 615, in do_run
    raise e
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 600, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'mkdir -p C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra' returned non-zero exit status 1.

ERROR: Command 'mkdir -p C:\Users\dev_bandai\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra' returned non-zero exit status 1.
```

**Comment by whummer** [comment] 2018-04-02 02:54
Thanks for reporting @konkonstantinidis @dev-bandai . There are still a few Unix-specific shell commands in the code base - some of them have been fixed in #698. can you please give it a try with the latest version (by cloning the repository, then running `make install`, `make infra`)? Thanks

**Comment by bcbeatty** [comment] 2018-04-02 15:36
I receive the follow error when I try 
```

\localstack>make install

make i info Invoking install target

(node:6460) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined

make × ERR  not found: make-##

```
ideas?

**Comment by DmytroRybka** [comment] 2018-06-14 12:40
Same error with the latest version on win 10 pro

**Comment by ajbazz** [comment] 2018-06-14 21:37
@DmytroRybka I got the same error. So many headaches when trying to install things on Windows.

**Comment by bhbusch** [comment] 2018-09-11 12:56
Receiving the same error on Windows 10 Home. Any known fix that I have been missing?

**Comment by kamiua** [comment] 2018-12-19 15:50
@bhbusch What is the change that you've made for it to work?

**Comment by matheusmaximo** [comment] 2019-01-14 12:17
Same error here. Any chance to have it fixed already?

**Comment by arnagarjun** [comment] 2019-01-24 18:44
Still getting the error 
localstack' is not recognized as an internal or external command,
operable program or batch file.

Hoping this issue will be fixed soon

**Comment by bikerp** [comment] 2019-03-19 12:09
Same error here (Win 10)

**Comment by MuazOthman** [comment] 2019-04-27 03:50
How about trying to run it from inside bash instead of windows command line? you can try using the git shell that comes with [Git for Windows](https://gitforwindows.org/)

**Comment by whummer** [comment] 2019-08-03 19:14
Thanks for reporting. Closing this one as duplicate of #563. Please see the comment there:

----
Can you please try installing the latest version 0.10.0 under Windows.

The installation has been entirely refactored, and now works as follows:

* only install the bare minimum dependencies by default
* start LocalStack in Docker by default, and
* lazy-load any dependencies, if needed, when starting locally (outside of Docker).

Hope that works. Please report here - thanks.

**Closed by whummer** 2019-08-03 19:14 UTC
Labels: bug, installation, windows

**Comment by JacquesJamiesonLancom** [comment] 2019-08-07 02:32
> Thanks for reporting. Closing this one as duplicate of #563. Please see the comment there:
> 
> Can you please try installing the latest version 0.10.0 under Windows.
> 
> The installation has been entirely refactored, and now works as follows:
> 
> only install the bare minimum dependencies by default
> start LocalStack in Docker by default, and
> lazy-load any dependencies, if needed, when starting locally (outside of Docker).
> Hope that works. Please report here - thanks.


I just did this and still run into same issue of localstack not being a recognized command.

Windows 10
python 3.6
