### ISSUE TITLE
Lambda: Docker Containers not removed

### ISSUE THREAD

**Issue by manuelwaltschek** [localstack/localstack#8616] opened 2023-07-05 07:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using localstack image 2.1.0 with testcontainers in version 1.18.0 in my spring boot integration tests.

I implemented the localstack container with a singleton pattern.

```
    public static LocalStackContainer getContainer() {
        if (localStackContainer == null) {
            DockerImageName image = DockerImageName.parse("localstack/localstack:2.1.0");
            localStackContainer =
                    new LocalStackContainer(image)
                            .withServices(SNS, SQS)
                            .withServices(LAMBDA)
                            .withEnv("DEBUG", "1")
                            .withEnv("LAMBDA_REMOVE_CONTAINERS", "1")
                            .withLogConsumer(new Slf4jLogConsumer(log));
        }
        return localStackContainer;
    }
```

Note the `LAMBDA_REMOVE_CONTAINERS` option

When I run my tests the lambda containers are not discarded when they finish. How so? Could not find anything meaningful in the logs. 

### Expected Behavior

Containers are removed when the JVM exits (when the test is finished), or when the lambda function is deleted.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
public class LocalStackITHelper implements InitializingBean {
...
       private static void ensureContainerStarted() {
            LocalStackContainer container = getContainer();
            if (!container.isRunning()) {
                container.start();
            }
        }
 ...       
}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I have the following methods in `LambdaService` to create and delete functions:

```
@SneakyThrows
    public String createLambdaFunction(
            String functionName,
            @NonNull Resource resource,
            String role) {
        LambdaWaiter waiter = awsLambda.waiter();
        SdkBytes fileToUpload = SdkBytes.fromInputStream(resource.getInputStream());

        FunctionCode code = FunctionCode.builder()
                .zipFile(fileToUpload)
                .build();

        String handler = functionName + ".handler";
        CreateFunctionRequest functionRequest = CreateFunctionRequest.builder()
                .functionName(functionName)
                .description("Created by the Lambda Java API")
                .code(code)
                .handler(handler)
                .runtime(Runtime.NODEJS16_X)
                .role(role)
                .build();

        // Create a Lambda function using a waiter.
        CreateFunctionResponse functionResponse = awsLambda.createFunction(functionRequest);
        GetFunctionRequest getFunctionRequest = GetFunctionRequest.builder()
                .functionName(functionName)
                .build();
        WaiterResponse<GetFunctionResponse> waiterResponse = waiter.waitUntilFunctionExists(getFunctionRequest);
        waiterResponse.matched().response().ifPresent(response -> log.info(response.toString()));
        return functionResponse.functionArn();

    }

    public boolean deleteLambdaFunction(String functionName) {
        DeleteFunctionRequest request = DeleteFunctionRequest.builder()
                .functionName(functionName)
                .build();

        LambdaWaiter waiter = awsLambda.waiter();
        DeleteFunctionResponse response = awsLambda.deleteFunction(request);

        log.info("The " + functionName + " function was deleted");
        return response.sdkHttpResponse().isSuccessful();
    }
```

### Environment

```markdown
- OS: MacOS Monterey 12.4
- LocalStack: 2.1.0
```

**Edit:** I added the configuration 

`.withEnv("LAMBDA_KEEPALIVE_MS", "10000")`

This seems to stop and then discard the containers after 10 seconds.

I have some new questions:
What effect does "deleting" lambdas have? I assumed it will also delete the running containers.
If not, is there any way to associate the lambda container with the parent localstack container so that I can clean up by myself on shutdown?

**Comment by eddumelendez** [comment] 2023-08-04 17:14
Hi, Testcontainers kill the containers and not stop them. I think that's the reason why the lambda container is still alive even when LocalStack containers doesn't exist anymore. Testcontainers has its own Resource Cleaner and every container started with Testcontainers will contain the following labels

```
"org.testcontainers": "true",
"org.testcontainers.lang": "java",
"org.testcontainers.sessionId": "bc2c90b3-c307-40b1-aa78-1cab46afb9a0",
"org.testcontainers.version": "1.18.3"
```

`org.testcontainers.sessionId` will be the one used to kill the container when tests finish. I had this issue couple of months ago and just recently found this issue. My first though is start the lambda container with the same labels as LocalStack containers. Looking forward to figure out a solution for this :)

**Comment by manuelwaltschek** [comment] 2023-08-04 20:32
@joe4dev sorry for the late response.

Well I found that the containers are NOT removed when I don't set the `LAMBDA_KEEPALIVE_MS`.
By "deleting lambda" I was referring to the execution of my `deleteLambdaFunction ` which deletes the function via the aws sdk. I expected that this will also lead to the termination of the associated container, which it does not.

@eddumelendez thanks for that information. So which kind of "issue" did you have exactly?

**Comment by eddumelendez** [comment] 2023-08-04 20:34
lambda container not being removed when starting LocalStack container by using Testcontainers. I understand that's the same issue you have.

**Comment by eddumelendez** [comment] 2023-09-29 17:48
I have a workaround for this.

In Java

```java
static String testcontainersLabels() {
	return Stream
		.of(
			DockerClientFactory.DEFAULT_LABELS.entrySet().stream(),
			ResourceReaper.instance().getLabels().entrySet().stream()
		)
		.flatMap(Function.identity())
		.map(entry -> String.format("-l %s=%s", entry.getKey(), entry.getValue()))
		.collect(Collectors.joining(" "));
}
```

So, the container definition looks like this

```java
static LocalStackContainer localstack = new LocalStackContainer(
			DockerImageName.parse("localstack/localstack:2.3.0"))
	.withEnv("LAMBDA_DOCKER_FLAGS", testcontainersLabels());
```

Then, Testcontainers will make sure to kill the lambda as well.

I also tried using `DOCKER_FLAGS` to make it generic and avoid setting every env var but that doesn't seem to work.

**Comment by moxue1989** [comment] 2023-10-03 18:56
I ran into this issue as well, any lambda functions created are not cleaned up by localstack and remains stuck running in docker. Every trigger creates a new container and I have to manually clean it up each time.

I followed @mgrundie-r7 suggestion of making a `DeleteFunctionRequest` but that only terminates the kills the container and does not delete it.

@eddumelendez I tried your workaround and it didn't work for me. Resources still remained.

I have however discovered that setting the env: `PROVIDER_OVERRIDE_LAMBDA` to `legacy` works very well. I guess something broke with the migration. 

Example:
```
@LocalStack(
        services = {
                @LocalStackService(name = Service.LAMBDA),
                @LocalStackService(name = Service.SNS),
                @LocalStackService(name = Service.SQS)
        },
        env = {
                @EnvVar(name = "PROVIDER_OVERRIDE_LAMBDA", value = "legacy")  // TODO: remove this once issue fixed: https://github.com/localstack/localstack/issues/8616
        }
)
```

Ref: https://docs.localstack.cloud/references/configuration/#lambda-legacy

**Comment by eddumelendez** [comment] 2023-10-03 19:43
@moxue1989 you can find an example [here](https://github.com/eddumelendez/testcontainers-localstack/blob/main/lambda/src/test/java/com/example/springcloudfunctionaws/SpringCloudFunctionAwsApplicationTests.java#L48-L54)

**Comment by dfangl** [comment] 2024-05-07 12:41
With testcontainers/testcontainers-java#8595 the labels are now added to lambda containers, which should lead to testcontainers cleaning the containers up, even if LocalStack does not delete them.

In general, LocalStack will delete the lambda containers if the function (version) is deleted or localstack is stopped. If LocalStack is killed before it gets the chance, then the containers are left over. The container deletion can also be controlled using `LAMBDA_REMOVE_CONTAINERS`. If you set `LAMBDA_REMOVE_CONTAINERS=0` LocalStack will stop, but not remove, the containers (can be used for debug reasons). The default is to stop and remove the containers on deletion / stop of the container.

Since this is resolved with testcontainers, I will close this issue for now - feel free to comment / open a new one if the issue is not resolved.

**Closed by dfangl** 2024-05-07 12:41 UTC
Labels: type: feature, aws:lambda, status: backlog
