### ISSUE TITLE
Error 500 during serverless deploy 

### ISSUE THREAD

**Issue by warnerpinz** [localstack/localstack#1027] opened 2018-11-28 10:47 UTC
```
warner$ localstack start --docker
Starting local dev environment. CTRL-C to quit.
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -p 8080:8080 -p 443:443 -p 4567-4583:4567-4583 -p 4590-4593:4590-4593 -v "/private/var/folders/qr/s_k39h1s6bd1nzlc3t_05xgr0000gn/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/qr/s_k39h1s6bd1nzlc3t_05xgr0000gn/T/localstack" "localstack/localstack"
2018-11-28 10:44:01,453 CRIT Supervisor running as root (no user in config file)
2018-11-28 10:44:01,461 INFO supervisord started with pid 1
2018-11-28 10:44:02,465 INFO spawned: 'dashboard' with pid 10
2018-11-28 10:44:02,470 INFO spawned: 'infra' with pid 11
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start)
2018-11-28 10:44:03,484 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-11-28 10:44:03,484 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
2018-11-28T10:44:03:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2018-11-28T10:44:03:INFO:werkzeug:  * Restarting with stat
2018-11-28T10:44:04:WARNING:werkzeug:  * Debugger is active!
2018-11-28T10:44:04:INFO:werkzeug:  * Debugger PIN: 298-979-887
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting mock Secrets Manager (http port 4584)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2018-11-28T10:44:16:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-11-28T10:44:19:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-11-28T10:44:23:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
Ready.
2018-11-28T10:44:35:INFO:werkzeug: 172.17.0.1 - - [28/Nov/2018 10:44:35] "GET / HTTP/1.1" 200 -
2018-11-28T10:44:35:INFO:werkzeug: 172.17.0.1 - - [28/Nov/2018 10:44:35] "GET /node_modules/angular/angular.js HTTP/1.1" 200 -
2018-11-28T10:44:35:INFO:werkzeug: 172.17.0.1 - - [28/Nov/2018 10:44:35] "GET /node_modules/swagger-client/browser/swagger-client.js HTTP/1.1" 200 -
2018-11-28T10:44:35:INFO:werkzeug: 172.17.0.1 - - [28/Nov/2018 10:44:35] "GET /img/localstack_icon.png HTTP/1.1" 200 -
2018-11-28T10:44:35:INFO:werkzeug: 172.17.0.1 - - [28/Nov/2018 10:44:35] "GET //localhost:8080/swagger.json HTTP/1.1" 200 -
2018-11-28T10:44:41:INFO:werkzeug: 172.17.0.1 - - [28/Nov/2018 10:44:41] "POST /graph HTTP/1.1" 200 -
2018-11-28T10:45:20:ERROR:localstack.services.generic_proxy: Error forwarding request: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 218, in forward
updated_response = self.proxy.update_listener.return_response(**kwargs)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
template_deployer.deploy_template(template, req_data.get('StackName')[0])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 509, in deploy_template
stack_resources = describe_stack_resources(stack_name, resource_id)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 227, in describe_stack_resources
resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 611, in _make_api_call
operation_model, request_dict)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
return self._send_request(request_dict, operation_model)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 134, in _send_request
request, operation_model, attempts)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 197, in _get_response
response_dict, operation_model.output_shape)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 240, in parse
parsed = self._do_error_parse(response, shape)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 480, in _do_error_parse
root = self._parse_xml_string_to_dom(xml_contents)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/parsers.py", line 432, in _parse_xml_string_to_dom
"invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
```

**Comment by whummer** [comment] 2019-03-08 04:08
Thanks for reporting @warnerpinz . Can you please provide some more details - which command are your running, what is your serverless configuration file that causes this error?

Also, can you please give it a try with the latest version - there have been some improvements in the serverless/cloudformation implementation recently. See also here: https://github.com/localstack/serverless-localstack

**Comment by whummer** [comment] 2019-11-27 21:21
Closing as outdated / unable to reproduce.

**Closed by whummer** 2019-11-27 21:21 UTC
Labels: needs-triaging
