### ISSUE TITLE
CloudFormation goes into an infinite loop when deploying Serverless

### ISSUE THREAD

**Issue by fsproru** [localstack/localstack#2743] opened 2020-07-18 05:47 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When deploying Serverless into LocalStack with an existing S3 bucket connected to a Lambda, CloudFormation goes into a loop and then fails, failing the serverless deployment too.
...

## Expected behavior
Deploy works the same way as deploying into a real AWS account.

...

## Actual behavior
Serverless deployment fails. Seeing this error in LocalStack logs:

CloudFormation keeps on trying and then fails with the following error: 

```
2020-07-18T05:27:53:WARNING:bootstrap.py: Thread run method <function apply_patches.<locals>.run_dependencies_deployment_loop.<locals>.run_loop at 0x7f0683ae4b80>(None) failed: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 492, in run
    self.func(self.params)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 808, in run_loop
    raise Exception('Unable to resolve all CloudFormation resources after traversing ' +
Exception: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): ['CustomDashresourceDashexistingDashs3LambdaFunction']
```

Here is the full output from LocalStack

```
2020-07-18T05:27:46:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'localstack.services.cloudformation.service_models.S3BucketPolicy'>
2020-07-18T05:27:51:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:commandeer-tanks-local-tankS3FileCreatedEvent
2020-07-18T05:27:52:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:commandeer-tanks-local-custom-resource-existing-s3
2020-07-18T05:27:52:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:commandeer-tanks-local-custom-resource-existing-s3
2020-07-18T05:27:52:INFO:localstack.services.cloudformation.cloudformation_starter: Resource CustomDashresourceDashexistingDashs3LambdaFunction cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'commandeer-tanks-local-serverlessdeploymentbucket-c0j12nhsd67t', 'S3Key': 'serverless/commandeer-tanks/local/1595050065823-2020-07-18T05:27:45.823Z/custom-resources.zip'}, 'FunctionName': 'commandeer-tanks-local-custom-resource-existing-s3', 'Handler': 's3/handler.handler', 'MemorySize': 1024, 'Runtime': 'nodejs12.x', 'Timeout': 180, 'Role': 'arn:aws:iam::123456789012:role/commandeer-tanks-local-IamRoleCustomResourcesLambdaExecution-EBP6FTJCNTA5'}, 'DependsOn': ['IamRoleCustomResourcesLambdaExecution']}
2020-07-18T05:27:52:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:commandeer-tanks-local-tankS3FileCreatedEvent
2020-07-18T05:27:53:WARNING:moto: No Moto CloudFormation support for Custom::S3
2020-07-18T05:27:53:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:commandeer-tanks-local-custom-resource-existing-s3
2020-07-18T05:27:53:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:commandeer-tanks-local-custom-resource-existing-s3
2020-07-18T05:27:53:INFO:localstack.services.cloudformation.cloudformation_starter: Resource CustomDashresourceDashexistingDashs3LambdaFunction cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'commandeer-tanks-local-serverlessdeploymentbucket-c0j12nhsd67t', 'S3Key': 'serverless/commandeer-tanks/local/1595050065823-2020-07-18T05:27:45.823Z/custom-resources.zip'}, 'FunctionName': 'commandeer-tanks-local-custom-resource-existing-s3', 'Handler': 's3/handler.handler', 'MemorySize': 1024, 'Runtime': 'nodejs12.x', 'Timeout': 180, 'Role': 'arn:aws:iam::123456789012:role/commandeer-tanks-local-IamRoleCustomResourcesLambdaExecution-EBP6FTJCNTA5'}, 'DependsOn': ['IamRoleCustomResourcesLambdaExecution']}
2020-07-18T05:27:53:WARNING:localstack.services.cloudformation.cloudformation_starter: Unresolvable dependencies, there may be undeployed stack resources: {'CustomDashresourceDashexistingDashs3LambdaFunction': ['CustomDashresourceDashexistingDashs3LambdaFunction', {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'commandeer-tanks-local-serverlessdeploymentbucket-c0j12nhsd67t', 'S3Key': 'serverless/commandeer-tanks/local/1595050065823-2020-07-18T05:27:45.823Z/custom-resources.zip'}, 'FunctionName': 'commandeer-tanks-local-custom-resource-existing-s3', 'Handler': 's3/handler.handler', 'MemorySize': 1024, 'Runtime': 'nodejs12.x', 'Timeout': 180, 'Role': 'arn:aws:iam::123456789012:role/commandeer-tanks-local-IamRoleCustomResourcesLambdaExecution-EBP6FTJCNTA5'}, 'DependsOn': ['IamRoleCustomResourcesLambdaExecution']}, <moto.cloudformation.parsing.ResourceMap object at 0x7f06842d7070>, 'us-east-1']}
2020-07-18T05:27:53:WARNING:bootstrap.py: Thread run method <function apply_patches.<locals>.run_dependencies_deployment_loop.<locals>.run_loop at 0x7f0683ae4b80>(None) failed: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 492, in run
    self.func(self.params)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 808, in run_loop
    raise Exception('Unable to resolve all CloudFormation resources after traversing ' +
Exception: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): ['CustomDashresourceDashexistingDashs3LambdaFunction']
```

And here is the output of `AWS_ACCESS_KEY_ID=NONE_FOR_LOCAL AWS_SECRET_ACCESS_KEY=NONE_FOR_LOCAL serverless deploy --stage local`

```
Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.024s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:000000000000:stack/commandeer-tanks-local/aa1706df-8fea-4c18-b045-60c78e77d227' })
CloudFormation - UPDATE_FAILED - AWS::CloudFormation::Stack - commandeer-tanks-local
Serverless: [AWS cloudformation 200 0.021s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:000000000000:stack/commandeer-tanks-local/aa1706df-8fea-4c18-b045-60c78e77d227' })
Serverless: [AWS cloudformation 200 0.025s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:000000000000:stack/commandeer-tanks-local/aa1706df-8fea-4c18-b045-60c78e77d227' })
Serverless: [AWS cloudformation 200 0.023s 0 retries] describeStackEvents({ StackName:
   'arn:aws:cloudformation:us-east-1:000000000000:stack/commandeer-tanks-local/aa1706df-8fea-4c18-b045-60c78e77d227' })
...
```

...

# Steps to reproduce
## Command used to start LocalStack
localstack start

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
We're trying to deploy this project: https://github.com/commandeer/open/tree/ansible-tutorial/sample-apps/tanks/serverless

Here is serverless.yml

```
service: commandeer-tanks

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  region: us-east-1
  stage: ${opt:stage, 'development'}
  timeout: 30
  versionFunctions: false

plugins:
  - serverless-plugin-typescript
  - serverless-localstack
  - serverless-dynamo-stream-plugin

functions:

  # S3 Events
  tankS3FileCreatedEvent: ${file(./handlers/s3/tankS3FileCreatedHandler.yml):tankS3FileCreatedHandler}

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    # autostart: true  # optional - start LocalStack in Docker on Serverless deploy
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False
```

Here is package.json

```
{
  "name": "tank-serverless-setup",
  "author": "commandeer",
  "license": "MIT",
  "main": "handlers/index",
  "scripts": {
    "deploy": "sls deploy",
    "test": "mocha -r ts-node/register/transpile-only tests/setup.ts \"tests/handlers/**/*.test.ts\" --timeout 30000 --exit"
  },
  "dependencies": {
    "aws-sdk": "2.556.0"
  },
  "devDependencies": {
    "@types/aws-lambda": "8.10.24",
    "@types/mocha": "5.2.6",
    "@types/sinon-chai": "3.2.2",
    "chai": "4.2.0",
    "chai-shallow-deep-equal": "1.4.6",
    "lambda-tester": "3.6.0",
    "mocha": "5.2.0",
    "serverless-dynamo-stream-plugin": "0.0.2",
    "serverless-plugin-typescript": "1.1.7",
    "serverless-localstack": "0.4.21",
    "ts-node": "8.1.0",
    "typescript": "3.6.4"
  }
}
```

Here is the handler yaml file

```
tankS3FileCreatedHandler:
  handler: handlers/s3/tankS3FileCreatedHandler.process
  timeout: 900
  tags:
    DEPARTMENT: MACHINERY
    ENVIRONMENT: DEV

  events:
    - s3:
        bucket: commandeer-tank
        event: s3:ObjectCreated:*
        existing: true
        rules:
          - suffix: .json
```

and the handler code

```
import { Context, Handler, S3CreateEvent } from 'aws-lambda';

/**
 * @description handle receiving a tank file from s3
 * @param {S3CreateEvent} event event object
 * @param {Context} context context object
 * @returns {boolean} status
 */
const process: Handler = async (event: S3CreateEvent, context: Context) => {
  console.log('tankS3FileCreatedEvent.handleFile', { event, context });

  try {
    const fileName: string = decodeURIComponent(event.Records[0].s3.object.key);
    console.log(fileName);

    context.succeed(true);
  } catch (exception) {
    context.fail(exception);
  }
};

export { process };
```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-220) by [Unito](https://www.unito.io/learn-more)

**Comment by macnev2013** [comment] 2020-08-20 19:42
Hello, Thanks for reporting @fsproru  .
We have tried to reproduce the issue and we are not able to reproduce the issue. Can you please let us know if we are missing anything?
I have created a repo of the code which we have used to reproduce the issue.
[https://github.com/macnev2013/serverless-lambda-test.git](https://github.com/macnev2013/serverless-lambda-test.git)

**Comment by whummer** [comment] 2020-12-06 11:09
Thanks for reporting @fsproru and providing the reproducible sample @macnev2013 . Closing, as this issue should be fixed in the `latest` version. Please let us know if the problem persists. Thanks!

**Closed by whummer** 2020-12-06 11:09 UTC
