### ISSUE TITLE
Can't start localstack, permission denied: /tmp/localstack/server.test.pem

### ISSUE THREAD

**Issue by johnjeffers** [localstack/localstack#1743] opened 2019-11-08 19:01 UTC
I'm trying to start localstack in a containerized Jenkins build agent for unit testing. In other words, trying to start the localstack docker container from within a docker container. We do this all the time with other images, using the method of mounting `/var/run/docker.sock` in the "parent" container, but localstack will not start.

I get this error:

```
2019-11-08T18:53:53:ERROR:localstack.services.generic_proxy: Exception running proxy on port 8081: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 384, in run_cmd
    combined_file, cert_file_name, key_file_name = GenericProxy.create_ssl_cert(serial_number=self.port)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 401, in create_ssl_cert
    return generate_ssl_cert(SERVER_CERT_PEM_FILE, serial_number=serial_number)
  File "/opt/code/localstack/localstack/utils/common.py", line 828, in generate_ssl_cert
    save_file(target_file, file_content)
  File "/opt/code/localstack/localstack/utils/common.py", line 642, in save_file
    with open(file, mode) as f:
PermissionError: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'
```

Port 8081 is not already in use, and `/tmp/localstack` is writable, so I don't understand why it's getting permission denied.

**Comment by sepo-one** [comment] 2019-11-21 11:09
same here

**Comment by Ri0n** [comment] 2019-11-21 17:33
after adding "USER root" do derived dockerfile seems to work.

**Comment by Ri0n** [comment] 2019-11-21 17:37
oh wrong. that was `docker volume prune` which fixed the problem.

**Comment by Ri0n** [comment] 2019-11-21 17:51
I'm wrong again. Looks totally random in fact

**Comment by whummer** [comment] 2019-11-23 21:51
Thanks for reporting @johnjeffers @sepo-one @Ri0n. This should be fixed in #1796 - can you please give it a try with the `latest` version of the Docker image. Please re-open this issue if the problem persists. Thanks

**Closed by whummer** 2019-11-23 21:51 UTC
Labels: bug, installation, priority-high

**Comment by johnjeffers** [comment] 2019-11-23 22:20
Does not appear to be fixed. Same error as before.

```
# SERVICES=s3 localstack start
Starting local dev environment. CTRL-C to quit.
docker run -it -e SERVICES="s3" -e HOSTNAME="infinite-runner-2ebcb04a-8f07-43f8-9797-0f1c05b9aebc-vnbc-3r14t" -e LOCALSTACK_HOSTNAME="infinite-runner-2ebcb04a-8f07-43f8-9797-0f1c05b9aebc-vnbc-3r14t" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="infinite-runner-2ebcb04a-8f07-43f8-9797-0f1c05b9aebc-vnbc-3r14t" --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081   -p 4572:4572  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"
Unable to find image 'localstack/localstack:latest' locally
latest: Pulling from localstack/localstack
267bb819df12: Pull complete
Digest: sha256:a5dc20c9e1978c29c21eed2cec16cbe7d5e2be1987a8ec50cabe417571811f6f
Status: Downloaded newer image for localstack/localstack:latest
Waiting for all LocalStack services to be ready
2019-11-23 22:18:55,432 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-11-23 22:18:55,435 INFO supervisord started with pid 13
2019-11-23 22:18:56,438 INFO spawned: 'dashboard' with pid 19
2019-11-23 22:18:56,440 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2019-11-23 22:18:56,448 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2019-11-23 22:18:57,450 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-23T22:19:00:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
2019-11-23T22:19:00:ERROR:localstack.services.generic_proxy: Exception running proxy on port 8081: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 384, in run_cmd
    combined_file, cert_file_name, key_file_name = GenericProxy.create_ssl_cert(serial_number=self.port)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 401, in create_ssl_cert
    return generate_ssl_cert(SERVER_CERT_PEM_FILE, serial_number=serial_number)
  File "/opt/code/localstack/localstack/utils/common.py", line 836, in generate_ssl_cert
    save_file(target_file, file_content)
  File "/opt/code/localstack/localstack/utils/common.py", line 650, in save_file
    with open(file, mode) as f:
PermissionError: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'

Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
Starting mock S3 (http port 4572)...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-11-23T22:19:21:WARNING:infra.py: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-11-23T22:19:27:WARNING:infra.py: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
```

**Comment by whummer** [comment] 2019-11-24 13:28
Thanks for testing @johnjeffers .

Which version of the Docker image are you using - what's the output of this command?
```
docker images | grep localstack
```
The error above indicates that the error happens in `line 836, in generate_ssl_cert`- however, in the latest version this code is on line 851: https://github.com/localstack/localstack/blob/master/localstack/utils/common.py#L851

Can you please try this command and restart the localstack container:
```
docker pull localstack/localstack
```
Hope that helps, thanks

**Comment by johnjeffers** [comment] 2019-11-24 19:29
Image is `latest`:
```# docker images | grep localstack
localstack/localstack                                                latest              316cd69439ea        3 hours ago         865MB
```

Pulling the image doesn't do anything because I already have `latest`:
```
# docker pull localstack/localstack
Using default tag: latest
latest: Pulling from localstack/localstack
Digest: sha256:5cf0a7cf925ec6486d39048f05dddf992196075c05eea6f68cb838e7262b83b3
Status: Image is up to date for localstack/localstack:latest
docker.io/localstack/localstack:latest
```

Stil getting the error `Permission denied: '/tmp/localstack/server.test.pem'`:
```
# SERVICES=s3 localstack start
Starting local dev environment. CTRL-C to quit.
docker run -it -e SERVICES="s3" -e HOSTNAME="infinite-runner-eb2f2790-c71e-4c29-9054-37af70614fd1-6npr-wjxl4" -e LOCALSTACK_HOSTNAME="infinite-runner-eb2f2790-c71e-4c29-9054-37af70614fd1-6npr-wjxl4" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="infinite-runner-eb2f2790-c71e-4c29-9054-37af70614fd1-6npr-wjxl4" --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081   -p 4572:4572  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"
Waiting for all LocalStack services to be ready
2019-11-24 19:26:31,108 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-11-24 19:26:31,112 INFO supervisord started with pid 14
2019-11-24 19:26:32,114 INFO spawned: 'dashboard' with pid 20
2019-11-24 19:26:32,116 INFO spawned: 'infra' with pid 21
(. .venv/bin/activate; bin/localstack web)
2019-11-24 19:26:32,123 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2019-11-24 19:26:33,127 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-24T19:26:35:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
2019-11-24T19:26:35:INFO:localstack.utils.common: Unable to store certificate file under /tmp/localstack/server.test.pem, using tmp file instead: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'
Starting local dev environment. CTRL-C to quit.
Starting mock S3 (http port 4572)...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-11-24T19:26:47:WARNING:infra.py: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-11-24T19:27:00:WARNING:infra.py: Service "s3" not yet available, retrying...
```

**Comment by whummer** [comment] 2019-11-24 22:06
Thanks for confirming @johnjeffers . The message you're seeing is an `INFO` message, shouldn't be the root cause for this problem.

I tried running the `docker run ...` command from your post and was able to reproduce the issue. It seems that the `HOSTNAME` and/or `LOCALSTACK_HOSTNAME` configuration could be the issue here.

It does work for me if I remove the `*HOSTNAME` configurations:
```
docker run -it -e DEBUG=1 -e SERVICES="s3" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="0000000000" --rm --privileged --name localstack_main -p 8080:8080 -p 8081:8081   -p 4572:4572  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack"
...
Ready.
```
Can you please try to unset or adjust the `*HOSTNAME` configurations to properly reflect the host names in your environment?

**Comment by johnjeffers** [comment] 2019-11-24 23:48
Thanks for the suggestion! This command worked:
```
SERVICES=s3 HOSTNAME=localhost localstack start
```

**Comment by RSHUKL01** [comment] 2020-06-26 05:38
@whummer  I am facing the same issue. please find my docker-compose.yml file below
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=2kgAL1q5TV
      - SERVICES=s3,emr,ec2,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localhost localstack start
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by RSHUKL01** [comment] 2020-06-26 05:38
@whummer I am facing the same issue. please find my docker-compose.yml file below
version: '2.1'
services:
localstack:
image: localstack/localstack
ports:
- "53:53"
- "443:443"
- "4510-4520:4510-4520"
- "4566-4620:4566-4620"
- "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
environment:
- LOCALSTACK_API_KEY=2****
- SERVICES=s3,emr,ec2,cloudformation
- DEBUG=1
- DATA_DIR=/tmp/localstack/data
- DOCKER_HOST=unix:///var/run/docker.sock
- HOSTNAME=localhost localstack start
volumes:
- "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
- "/var/run/docker.sock:/var/run/docker.sock"

**Comment by RSHUKL01** [comment] 2020-06-26 05:39
@whummer Could you please help on the above comment

**Comment by johnmee** [comment] 2021-04-07 01:51
YMMV, this solved it for me: `docker container prune`

**Comment by sagarjunnarkar** [comment] 2021-05-22 21:15
I have removed data directory from host machine - ```sudo rm -rf /tmp/localstack```.
This fixed the issue but at the same time its going to delete all objects/data which you have created earlier.
