### ISSUE TITLE
bug: LocalStack CLI version 0.14.3.5 still uses Localstack version of 0.14.3.1

### ISSUE THREAD

**Issue by giriprashant7891** [localstack/localstack#6337] opened 2022-06-23 19:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I previously had localstack install via pip. I recently updated it via: `pip3.9 install localstack --upgrade`, which upgraded it to the latest version of 0.14.3.5. However, when i start localstack, I still see this:

```
Starting LocalStack with Services: dynamodb,s3; Edge port: 4566
     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.14.3.5

[12:11:56] starting LocalStack in Docker mode 🐳                                                                                                                                                                      localstack.py:135
──────────────────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ────────────────────────────────────────────────────────────────────────────────────────────
Waiting for all LocalStack services to be ready
2022-06-23 19:11:56,955 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-23 19:11:56,957 INFO supervisord started with pid 15
2022-06-23 19:11:57,961 INFO spawned: 'infra' with pid 20
2022-06-23 19:11:58,965 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.14.3.1
LocalStack Docker container id: a9192a270ef4
LocalStack build date: 2022-05-26
LocalStack build git hash: 5f46acaa

```

The localstack CLI version is upgraded to 0.14.3.5, while the localstack version is still 0.14.3.1. This is causing a problem to me, that I am unable to utilize a bug fix which went in recently: https://github.com/localstack/localstack/pull/6152/files.

When I check where localstack is installed:
```
pip3.9 show localstack
Name: localstack
Version: 0.14.3.5
Summary: LocalStack - A fully functional local Cloud stack
Home-page: https://github.com/localstack/localstack
Author: LocalStack Contributors
Author-email: info@localstack.cloud
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: apispec, boto3, cachetools, click, localstack-client, localstack-ext, plux, psutil, python-dotenv, pyyaml, requests, rich, semver, stevedore, tailer
Required-by: localstack-ext
```
and I check the code at this path: `vim /usr/local/lib/python3.9/site-packages/localstack/services/dynamodb/provider.py`, I can see that the bug fix is present at that code path.

However, when I start localstack, and run my code, I still get the exception:
```
2022-06-23T19:07:07.171:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Object of type bytes is not JSON serializable Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
result = await run_sync(handler, request, data)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 992, in handler
return modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
result = do_forward_request(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
result = do_forward_request_inmem(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
response = self.request(request)
File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
return self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
result = handler(context, instance) or {}
File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
return handler(context, req)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
return self.fn(*args, **kwargs)
File "/opt/code/localstack/localstack/aws/api/core.py", line 95, in operation_marker
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 752, in transact_write_items
records = self.prepare_transact_write_item_records(
File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1094, in prepare_transact_write_item_records
new_record["dynamodb"]["SizeBytes"] = len(json.dumps(put_request["Item"]))
File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

which is reflecting the earlier version of the package. 

### Expected Behavior

I expect the latest version of localstack to have that bug fixed.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

localstack start

### Environment

```markdown
- OS: MAC Monterey 12.2.1
- LocalStack:

Name: localstack
Version: 0.14.3.5
Summary: LocalStack - A fully functional local Cloud stack
Home-page: https://github.com/localstack/localstack
Author: LocalStack Contributors
Author-email: info@localstack.cloud
License: Apache License 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: apispec, boto3, cachetools, click, localstack-client, localstack-ext, plux, psutil, python-dotenv, pyyaml, requests, rich, semver, stevedore, tailer
Required-by: localstack-ext
```
```


### Anything else?

_No response_

**Comment by MarcelStranak** [comment] 2022-06-24 05:57
Hi @giriprashant7891, with the new version of LocalStack CLI you can use subcommand to update the docker image directly from your terminal.
You can use `localstack update all` to update all the LocalStack components.

```
Usage: localstack update [OPTIONS] COMMAND [ARGS]...

  Update LocalStack components

Options:
  --help  Show this message and exit.

Commands:
  all             Update all LocalStack components
  docker-images   Update container images LocalStack depends on
  localstack-cli  Update LocalStack CLI tools
```

**Comment by thrau** [comment] 2022-08-06 00:25
This is actually not a bug. The CLI version and runtime version can differ and you can keep them synced with the command that Marcel supplied. I agree that the user experience and documentation could be improved here! Thanks for reporting, closing for now.

**Closed by thrau** 2022-08-06 00:25 UTC
Labels: type: question, status: response required, area: cli
