### ISSUE TITLE
Build Fails on MacOS Sierra

### ISSUE THREAD

**Issue by mwpenna** [localstack/localstack#260] opened 2017-08-24 16:47 UTC
Build is failing when issuing the following command: pip install localstack
Stack trace is:
Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-1FIMZk-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by whummer** [comment] 2017-08-27 03:16
Thanks for reporting @mwpenna . This appears to be a duplicate of https://github.com/localstack/localstack/issues/248 - can we please continue the discussion on the other ticket and close this one. This looks like an issue with file permissions ("Operation not permitted") - sometimes that happens when you've been running `pip install` using `sudo` or a different system user in the past.

What is the output of this command:
```
ls -la /tmp/pip-1FIMZk-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info
```

Looks like this could be related to this one: https://github.com/pypa/pip/issues/3165 . One of the solutions suggested is to re-install using the `--ignore-installed` flag.

**Comment by mwpenna** [comment] 2017-08-28 13:43
I tried using the --ignore-installed flag and still got the same error. The output from above command was: ls: /tmp/pip-1FIMZk-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info: Permission denied
When i run it with sudo i get the following:
-rw-r--r--  1 root  wheel  1422 Jul 30  2016 /tmp/pip-1FIMZk-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info

**Comment by whummer** [comment] 2017-08-28 13:58
Can you try to run this:
```
sudo chmod -R 777 /tmp/pip-1FIMZk-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib
```
... and then try to re-install:
```
pip install --no-cache --upgrade localstack
```

**Comment by mwpenna** [comment] 2017-08-28 14:39
Build failed with the following error output: 
Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/gc/cq25hthn6sv04yhn8npf8b21xjkw8p/T/pip-kbMo_s-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by whummer** [comment] 2017-08-28 14:56
OK, we're getting closer. Looks like setting permissions is not enough, we need to be the owner of the temporary directory. Can you please try:
```
sudo chown -R `whoami` /tmp/pip-1FIMZk-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib
pip install --no-cache --upgrade localstack
```

**Comment by p1ng** [comment] 2017-10-05 13:05
I was able to get this installed on MacOS Sierra with the following:

Uninstall old version of pip (if necessary)
`sudo pip uninstall pip`

Install python from brew
`brew install python`

Make sure pip is working after brew install
`which pip`

If not, run this
`brew unlink python && brew link python`

To resolve permission errors, I ran install with the --user flag
`pip install --user localstack`

**Comment by whummer** [comment] 2017-10-08 04:00
Closing this issue as resolved, with the solution from @p1ng . Please re-open if the problem persists. Thanks

**Closed by whummer** 2017-10-08 04:00 UTC
Labels: installation, possible-duplicate

**Comment by Pyrolistical** [comment] 2019-07-04 21:09
@jasondavis25 2 years later, now `brew install python` installs python 3, which means `pip3`.
Command that that work today are:
```
brew install python
pip3 install --user localstack

// starting sqs only for example
SERVICES=sqs /Users/YOU/Library/Python/3.7/bin/localstack start
```
