### ISSUE TITLE
bug: REST ApiGateway responses header content-type always text/html

### ISSUE THREAD

**Issue by salah-mueller** [localstack/localstack#6134] opened 2022-05-24 18:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I Created an REST APIGatway with lambda handler using AWS CDK. when I hit the API the response header content type is always  set to "text/html"  instead of `application/json` . even if I changed the response template or added the header to lambda returned response. when I deploy the same stack on AWS account  the response header is fine and work as expected

### Expected Behavior

Response Header content-type to be `application/json`

### How are you starting LocalStack?

  `localstack start` command

#### How are you starting localstack (e.g., `bin/localstack` command`)

    `localstack start` command

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using AWS CDK typescript application and deploy it using `cdklocal` command on localstack

Using CDK follow the steps:
- create  REST ApiGateway
- create Lambda function 
- integrate lambda with APIGatway

On Command line:
- deploy using `cdklocal deploy` command

Finally
- test the endpoint and check the response header content-type

### Environment

```markdown
- OS: Windows 
- LocalStack: latest
```

### Anything else?

When I deploy the same stack on AWS account everything works fine and the response header content-type is `application/json`

**Comment by pinzon** [comment] 2022-05-30 18:09
Yes, while triaging this issue I figure out that it the integration works as intended just that localstack doesn't validate the response as AWS explains [here](https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway/). 

So the work I'm doing for this issue is this:
- add a test that confirms that the integration returns the headers that the lambda defines.
- add the validation for the response like AWS does and a test for that.
- and now, add the default behavior that @avanmalleghem mentions.
 
It's taking some time because I'm stuck with some internal utilities for testing.

**Comment by alexrashed** [comment] 2022-07-05 11:40
Hi @salah-mueller!
This should be fixed with #6170 which has just been merged. The fix should already be contained in the `localstack/localstack:latest` image. Is there a chance you could verify the fix? Thanks!

**Comment by avanmalleghem** [comment] 2022-07-06 13:11
Hello @alexrashed, looks like it doesn't work ! I still have "text/html; charset=utf-8" as default Content-Type header.

**Closed** 2022-07-08 08:11 UTC
Labels: type: bug, status: triage needed, aws:apigateway
