### ISSUE TITLE
bug: Creating a glacier vault with terraform and a Pro LocalStack license hangs forever "aws_glacier_vault.my_archive: Still creating... [6m30s elapsed]"

### ISSUE THREAD

**Issue by donrhummy** [localstack/localstack#5922] opened 2022-04-22 23:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No errors are shown in LocalStack, but it hangs forever like:

aws_glacier_vault.my_archive: Still creating... [4m10s elapsed]
aws_glacier_vault.my_archive: Still creating... [4m20s elapsed]
aws_glacier_vault.my_archive: Still creating... [4m30s elapsed]
aws_glacier_vault.my_archive: Still creating... [4m40s elapsed]
aws_glacier_vault.my_archive: Still creating... [4m50s elapsed]
aws_glacier_vault.my_archive: Still creating... [5m0s elapsed]
aws_glacier_vault.my_archive: Still creating... [5m10s elapsed]
aws_glacier_vault.my_archive: Still creating... [5m20s elapsed]
aws_glacier_vault.my_archive: Still creating... [5m30s elapsed]
aws_glacier_vault.my_archive: Still creating... [5m40s elapsed]
aws_glacier_vault.my_archive: Still creating... [5m50s elapsed]
aws_glacier_vault.my_archive: Still creating... [6m0s elapsed]
aws_glacier_vault.my_archive: Still creating... [6m10s elapsed]
aws_glacier_vault.my_archive: Still creating... [6m20s elapsed]
aws_glacier_vault.my_archive: Still creating... [6m30s elapsed]
aws_glacier_vault.my_archive: Still creating... [6m40s elapsed]
aws_glacier_vault.my_archive: Still creating... [6m50s elapsed]
aws_glacier_vault.my_archive: Still creating... [7m0s elapsed]

### Expected Behavior

It would create the Glacier Vault (like it does for S3 buckets)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
```shell
export LOCALSTACK_API_KEY=<hidden_key>
docker-compose -f localstack.yaml up
```
#### Terraform
```terraform
# Terraform configuration

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"

  # Notice this uses a diff syntax to refer to the
  # variable. Either is allowed, but the first one
  # guarantees it's a string
  access_key                  = "localstacktest"
  secret_key                  = "localstacktestkey"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  s3_use_path_style           = true

  endpoints {
    # These are always this port in LocalStack
    ec2 = "http://localhost:4566"
    iam = "http://localhost:4566"
    s3  = "http://localhost:4566"
    glacier = "http://localhost:4566"
    sns = "http://localhost:4566"
  }
}

resource "aws_glacier_vault" "my_archive" {

  name = "my-archive-vault"

  tags = {
    "VaultPurpose" = "Archive"
  }
}
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
terraform init
terraform apply
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.2.3
```

**Comment by Cesarsk** [comment] 2022-04-23 18:56
Hello. My first comment here.

![image](https://user-images.githubusercontent.com/3224160/164942592-ebe2a84e-d00c-407d-97ce-52c72ce73fbf.png)

I tried reproducing your issue and apparently Glacier is not supported by Localstack.

Checking the docs it looks like it's confirming what I'm saying.

See https://docs.localstack.cloud/aws/feature-coverage/

Best.

**Comment by donrhummy** [comment] 2022-04-25 17:19
> Hello. My first comment here.
> 
> ![image](https://user-images.githubusercontent.com/3224160/164942592-ebe2a84e-d00c-407d-97ce-52c72ce73fbf.png)
> 
> I tried reproducing your issue and apparently Glacier is not supported by Localstack.
> 
> Checking the docs it looks like it's confirming what I'm saying.
> 
> See https://docs.localstack.cloud/aws/feature-coverage/
> 
> Best.

That's not true. This page says Glacier _**is**_ covered as part of Pro: https://localstack.cloud/features/

**Comment by whummer** [comment] 2022-04-29 15:51
Hi @donrhummy , thanks for reporting. We've been able to replicate this issue - working on a fix that should get rolled out soon (will update here once available). Thanks!

**Comment by whummer** [comment] 2022-04-30 10:15
Hi @donrhummy , quick update - we have now pushed a few enhancements for Glacier that should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by whummer** [comment] 2022-05-14 14:05
Closing this issue as resolved - please do let us know if the problem persists.. Thanks!

**Closed by whummer** 2022-05-14 14:05 UTC
Labels: bug, needs-triaging, should-be-fixed, awaiting-response, aws:glacier
