### ISSUE TITLE
bug: Value {messageGroupId} for parameter MessageGroupId is invalid

### ISSUE THREAD

**Issue by haroutbezdjian** [localstack/localstack#5465] opened 2022-02-10 12:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MessageGroupId is considered invalid even though its a valid value, in localstack version 0.13.0 this was working when MessageGroupId was sent to sqs_client.send_message(..., MessageGroupId=message_group_id), in the latest version it is being included in kwargs and therefore started to get "Value 2bdf9987-fab8-4e9c-a0d6-e6360a85e7a8 for parameter MessageGroupId is invalid" error message, please could you look into this?

Thanks!

### Expected Behavior

Not getting "Value 2bdf9987-fab8-4e9c-a0d6-e6360a85e7a8 for parameter MessageGroupId is invalid"

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4587 sns publish  --topic-arn arn:aws:sns:eu-west-1:000000000000:local-video-meeting-events.fifo --message-group-id 2bdf9987-fab8-4e9c-a0d6-e6360a85e7a8 --message 'Test message'

### Environment

```markdown
- OS: MacOs Monterey 12.2
- LocalStack: 0.14.0
```

**Comment by giograno** [comment] 2022-02-12 17:03
Hi @haroutbezdjian, thanks for reporting the issue, I am having looking at it. 
Could I please ask you to do check if you are trying to subscribe to a standard queue (and not to a FIFO one)?
Standard queues do not accept the `MessageGroupId` argument and I was able to reproduce the issue by subscribing to a standard one. 
To create a FIFO queue, you should  specify `FifoTopic` as attribute and picking a name with the `.fifo` suffix, like the following example.
```
awslocal sns create-topic --name test.fifo --attributes '{"FifoTopic": "True"}'
```
Do you also get `Reason: The request include parameter that is not valid for this queue type` attached to your error message? In version 0.13.0 we were not checking this corner case; that's why likely you did not encounter the error.

**Comment by haroutbezdjian** [comment] 2022-02-13 20:49
Hello @giograno, thank you for getting back to me.

Yes i am creating and subscribing to a FIFO queue.


`aws sns create-topic --endpoint-url="http://localhost:4587" --attributes '{"FifoTopic": "True"}' --name test_topic.fifo
`


`aws sqs create-queue --endpoint-url="http://localhost:4587" --queue-name test_queue.fifo
`


`
aws --region="eu-west-1" --endpoint-url="http://localhost:4587" sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:test_topic.fifo --protocol sqs --notification-endpoint http://localhost:4587/000000000000/test_queue.fifo --attributes RawMessageDelivery=true
`

And then publishing message programatically but even with aws cli
`aws --endpoint-url=http://localhost:4587 sns publish  --topic-arn arn:aws:sns:eu-west-1:000000000000:test_topic.fifo --message-group-id 1 --message 'Test'`

i am getting:
` Unable to forward SNS message to SQS: An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value 1 for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type
`

I do get the same error with standard queue. I would really appreciate a help 🙏 . Thank you!

**Comment by brucekaufman** [comment] 2022-02-14 18:57
Also seeing this behavior with our serverless services when trying to upgrade.  I've found that this broke between releases `0.13.0` and `0.13.1`

**Comment by giograno** [comment] 2022-05-25 22:08
Hi @haroutbezdjian, @brucekaufman,

we recently reworked our SQS implementation and moved it to ASF 🎉 
Could you please try again with the `latest` Docker image?

I've been trying to reproduce the issue with the following commands, and the following combination works for me.

```
awslocal sns create-topic --attributes '{"FifoTopic": "True"}' --name test_topic.fifo

awslocal sqs create-queue --queue-name test_queue.fifo --attributes '{"FifoQueue": "True"}'

awslocal sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test_topic.fifo --protocol sqs --notification-endpoint http://localhost:4566/000000000000/test_queue.fifo --attributes RawMessageDelivery=true

awslocal sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:test_topic.fifo --message-group-id 1 --message 'Test'
```

To create a FIFO queue, one would need to specify `--attributes '{"FifoQueue": "True"}'` (the `.fifo` suffix alone is not sufficient; in fact, AWS would also trigger an error). I believe that our previous implementation did not implement this check, ending up creating a normal queue and not a FIFO one. Therefore, you were getting that error. 

Please let us know if this issue is now solved 🙏

**Comment by brucekaufman** [comment] 2022-05-26 16:42
@giograno I can confirm this bug has been fixed with localstack latest.  Now we are blocking on upgrading by this bug, so we still cannot take advantage of all the improvements.

https://github.com/localstack/localstack/issues/5860

**Comment by giograno** [comment] 2022-05-26 16:46
@brucekaufman thanks for your confirmation! I am closing this and having a look at your other blocking issue as soon as possible 👀

**Closed by giograno** 2022-05-26 16:46 UTC
Labels: bug, awaiting-response, aws:sns
