### ISSUE TITLE
Issue with x-ray client 

### ISSUE THREAD

**Issue by sunnylbk** [localstack/localstack#1706] opened 2019-10-31 06:07 UTC
- When using localstack pro x-ray client to invoke API operations, it throws errors.

Below is the code used for `GetTraceSummaries`,

```
		It("should add traces to xray", func() {
			xrayClient := services.XRayClient()
			_, err := xrayClient.GetTraceSummaries(&xray.GetTraceSummariesInput{
				StartTime: aws.Time(time.Now().Add(-1 * time.Hour)),
				EndTime:   aws.Time(time.Now()),
			})
			Expect(err).To(BeNil())
		})
```

Above test fails with the following error:

```
    Expected
        <*awserr.baseError | 0xc0004b4080>: {
            code: "RequestError",
            message: "send request failed",
            errs: [
                {
                    Op: "Post",
                    URL: "http://localhost:4603/TraceSummaries",
                    Err: {
                        Op: "dial",
                        Net: "tcp",
                        Source: nil,
                        Addr: {
                            IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                            Port: 4603,
                            Zone: "",
                        },
                        Err: {Syscall: "connect", Err: 0x3d},
                    },
                },
            ],
        }
    to be nil
```

**Comment by whummer** [comment] 2019-11-04 23:13
Hi @sunnylbk, thanks for reporting this issue.
```
                        Addr: {
                            IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                            Port: 4603,
                            Zone: "",
                        },
                        Err: {Syscall: "connect", Err: 0x3d},
```

It seems like your client code cannot connect to the API on port 4603 - can you please double check that the XRay API has been started up properly?The LocalStack output should contain something like:

```
Starting mock XRay (http port 4603)...
```

Also, the port 4603 should be exposed by the container. Which command do you use to start LocalStack?

A few fixes have been pushed recently - can you please give it a try with the latest version? Thanks!

**Comment by whummer** [comment] 2019-12-04 20:37
Closing this issue for now as "cannot reproduce", but please feel free to re-open it with more details if the problem persists. Thanks!

**Closed by whummer** 2019-12-04 20:37 UTC
Labels: PRO
