### ISSUE TITLE
Cloudformation failing when using stackId

### ISSUE THREAD

**Issue by arqex** [localstack/localstack#1477] opened 2019-08-10 14:53 UTC
Hey, first thanks for this amazing project!

I was trying to use serverless and localstack together, and I was having problems deploying a lambda function. In the logs I was getting errors 502 all the time:

```Serverless: Recoverable error occurred (502), sleeping for 5 seconds. Try 4 of 4

  Serverless Error ---------------------------------------

  502
```

I then start tracking the error, since this one above didn't give me much information, and I ended up at Serverless calling cloud formation's `describe-stack-events` using the unique stack id, instead of the stack name:

https://github.com/serverless/serverless/blob/f93b27bf684d9a14b1e67ec554a7719ca3628135/lib/plugins/aws/lib/monitorStack.js#L33

That is a legit request, as seen in the aws docs:

https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-stack-events.html#options

The cloudformation mock within localstack accepts the stackName without problems:

```
> aws --endpoint-url=http://localhost:4581 cloudformation list-stacks    
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3",
            "StackName": "steamRoller-local",
            "CreationTime": "2011-05-23T15:47:44Z",
            "StackStatus": "UPDATE_COMPLETE",
            "TemplateDescription": "The AWS CloudFormation template for this Serverless application"
        }
    ]
}

> aws --endpoint-url=http://localhost:4581 cloudformation describe-stack-events --stack-name steamRoller-local
{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3",
            "EventId": "a49fd67b-ce7b-4a33-9a00-6ebe2242adae",
            "ResourceStatus": "UPDATE_COMPLETE",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2019-08-10T13:44:44.550022Z",
            "StackName": "steamRoller-local",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3",
            "StackName": "steamRoller-local",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3",
            "LogicalResourceId": "steamRoller-local"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3",
            "EventId": "35ef5c91-99a0-483d-b6b7-e01ee3dda2dd",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2019-08-10T13:37:51.124574Z",
            "ResourceStatusReason": "User Initiated",
            "StackName": "steamRoller-local",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3",
            "LogicalResourceId": "steamRoller-local"
        }
    ]
}
```

But it doesn't accept the stackId as the argument (the one used by serverless):

```
> aws --endpoint-url=http://localhost:4581 cloudformation describe-stack-events --stack-name arn:aws:cloudformation:us-east-1:000000000000:stack/steamRoller-local/fcbeb0ef-9739-44a2-8a37-f599bbf4e5f3

An error occurred (502) when calling the DescribeStackEvents operation (reached max retries: 4): Bad Gateway
```

If I have a look at the docker logs I can see:

```
"invalid XML received:\n%s" % (e, xml_string)) botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:

b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

That matches what other colleagues were seeing: https://github.com/localstack/localstack/issues/965

Please, make localstack's cloudformation handle the stackId in describe-stack-events and other actions that accepts it. This is a blocker for using localstack for me :/

Thanks

**Comment by arqex** [comment] 2019-08-10 15:33
I am not a python guy, but having a look at the code I see that there is an intent of fixing the method using ARNs:

https://github.com/localstack/localstack/blob/841a16d8823fd46aa11519800958117a11b92ace/localstack/services/cloudformation/cloudformation_listener.py#L71

However, moto handles the ids ok:

https://github.com/spulec/moto/blob/88e1f0fa2329364392ff82f2cd5627726cccba51/moto/cloudformation/models.py#L523

Maybe it's something that needed fixing at some point and moto got updated later. Is the fix causing the bug?

**Comment by arqex** [comment] 2019-08-10 16:23
More people hitting this issue:
https://github.com/localstack/serverless-localstack/issues/3

and

https://github.com/localstack/serverless-localstack/issues/33

**Comment by wesselvdv** [comment] 2019-08-26 11:16
> I am not a python guy, but having a look at the code I see that there is an intent of fixing the method using ARNs:
> 
> https://github.com/localstack/localstack/blob/841a16d8823fd46aa11519800958117a11b92ace/localstack/services/cloudformation/cloudformation_listener.py#L71
> 
> However, moto handles the ids ok:
> 
> https://github.com/spulec/moto/blob/88e1f0fa2329364392ff82f2cd5627726cccba51/moto/cloudformation/models.py#L523
> 
> Maybe it's something that needed fixing at some point and moto got updated later. Is the fix causing the bug?

I removed that particular portion to test if it would work without the fix, but it doesn't. The issue then seems to be a mismatch in account_id. localstack/serverless uses 000000000, whereas moto uses 123456789.

I pushed a fix for this in my forked branch, 

https://github.com/wesselvdv/localstack/commit/ae7aac7a6a4a3f44e2c44fbb4dc5738c66541ca8

I am not convinced that this is the correct approach. I am not a diehard python developer.

**Comment by whummer** [comment] 2019-08-26 17:59
A fix has been pushed in https://github.com/localstack/localstack/pull/1504 . Can you please give it a try with the `latest` version of the Docker image, and create a simple example (code + commands to start) to reproduce the issue? Thanks!

**Comment by wesselvdv** [comment] 2019-08-27 06:14
@whummer Works for me now! I truly am stunned as to why your fix seems to work? I was debugging it for a while, and the only thing I consistently saw was that the `cloudformation_backend.stacks` in moto was empty when calling `describe_stack_events`. I hadn't seen any errors regarding the lambda part.

**Comment by whummer** [comment] 2019-09-01 20:32
Glad to hear it is working now. Thanks for helping debug this issue. Closing

**Closed by whummer** 2019-09-01 20:32 UTC
