### ISSUE TITLE
Underscore converted to hyphen while put it as metadata using amazon-sdk

### ISSUE THREAD

**Issue by itaimarts** [localstack/localstack#459] opened 2017-11-12 13:03 UTC
Hi,
When try to put object with metadata that include underscore(the metadata include underscore) we got the underscore converted to  hyphen.
The same code in Amazon will return the metadata  with underscore - not converted.

for example:
we put map of string as metadata - the "__key1" will convert to "--key1"

```
public class MyAwsS3Tester {

    public static final String IP = "10.0.0.24";
    public static final String BUCKET_NAME = "zanavi-test";

    public static void main(String[] args) {
        AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://" + IP + ":4572/", "us-east-1"))
                .disableChunkedEncoding()
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("zanavi", "1234")))
                .build();
        if (s3.doesBucketExistV2(BUCKET_NAME)) {
            System.out.println("bucket zanavi exists");
        }
        else {
            System.out.println("bucket " + BUCKET_NAME + " doesn't exists");
            s3.createBucket(BUCKET_NAME);
        }

        String dummyStr = "dummy-str";

        Map<String, String> myMap = new HashMap<String, String>();
        myMap.put("__key1", "val1");

        ObjectMetadata objectMetadata = new ObjectMetadata();
        objectMetadata.setUserMetadata(myMap);

        InputStream is = new ByteArrayInputStream(dummyStr.getBytes(StandardCharsets.UTF_8));
        s3.putObject(new PutObjectRequest(BUCKET_NAME, "my-key1", is, objectMetadata));

        S3Object getObj = s3.getObject(new GetObjectRequest(BUCKET_NAME, "my-key1"));
        ObjectMetadata objectMetadataResponse = getObj.getObjectMetadata();

        Map<String, String> myMap1 = objectMetadataResponse.getUserMetadata();

        System.out.println("done " + myMap1);
    }
```

**Comment by whummer** [comment] 2017-11-24 07:04
Thanks for reporting @itaimarts . I was able to reproduce this bug. 

Note that S3 metadata values are transmitted via HTTP header values. In your example, the metadata is transmitted using the following header:
```
x-amz-meta-__key1: val1
```

The root cause for this issue is that underscores in HTTP header names have traditionally been an issue (you can find more details if you google for "underscore header spoofing in CGI"). Therefore, most web frameworks are stripping underscores from HTTP header names, or ignore these headers entirely.

In our case, LocalStack makes use of [moto](https://github.com/spulec/moto), which uses the [flask](https://github.com/pallets/flask) framework to start local API servers. Flask is based on [werkzeug](https://github.com/pallets/werkzeug) which provides an implementation of [WSGI](https://wsgi.readthedocs.io/en/latest/) (the Python equivalent of CGI). Werkzeug is the culprit in our case. As you can see in [line 139 of serving.py](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L139), werkzeug creates an environment map by uppercasing all header names to variable names and replacing dashes with underscores:
```
        for key, value in self.headers.items():
            key = key.upper().replace('-', '_')
```

.. and then later when the environment variables are converted back to headers, underscores are converted back to dashes in [datastructurs.py](
https://github.com/pallets/werkzeug/blob/master/werkzeug/datastructures.py#L1360-L1364):
```
        for key, value in iteritems(self.environ):
            ...
                yield (key[5:].replace('_', '-').title(), _unicodify_header_value(value))
```
Given the tricky nature of this bug, I'm going to mark this as "Won't fix". Please feel free to bring up this issue in the upstream repositories (flask/werkzeug) to see if they can come up with a viable solution to pass HTTP headers with underscores to Flask apps. Note that there has been a similar bug request in the past which might be related: https://github.com/pallets/werkzeug/issues/940

At this point, I don't see an easy way we can fix this in LocalStack. I think the best workaround would be to not use underscores at all. If you find out more about this issue, please report back here. Thanks

**Closed** 2018-02-04 22:23 UTC
Labels: bug, upstream-issue, wontfix
