### ISSUE TITLE
Secrets Manager response CreatedDate Invalid Format

### ISSUE THREAD

**Issue by akichidis** [localstack/localstack#981] opened 2018-10-26 09:02 UTC
I am using the Secrets Manager service on the latest localstack version. I am using the Amazon's latest [Secrets Manager Java SDK](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-secretsmanager/1.11.437) to perform all the operations with Java 10. 

Although creating a new secret seems to working as expected, retrieving the secret via `get secret` operation throws the following exception through the SDK:

```
Unable to unmarshall response (Invalid format: "2018-05-23 13:16:57.198000" is malformed at " 13:16:57.198000"). Response Code: 200, Response Text: OK
```

After having a look on the SDK's code it seems that on the response it expects the `CreatedDate` to be of format `unixTimestamp`

The current localstack Secrets Manager implementation returns the `CreatedDate` as a date format (e.x  2018-05-23 13:16:57.198000) instead of `unixtimestamp`.

After checking against the real Secrets Manager on AWS, and based on their current documentation (see [here](https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/get-secret-value.html#examples)), it seems that the response `CreateDate` should be a unixtimestamp.

The same issue has been reported [here](https://github.com/localstack/localstack/pull/937#issuecomment-427832576) by @frank-bee  as well.

**Comment by MichaelDSalzman** [comment] 2018-11-03 16:40
I'm hitting the same issue.
Here's a response from AWS:
```
{
    "Name": "test", 
    "VersionId": "FB4BC522-ABE2-40EC-86AE-48B44F0F1AB5", 
    "SecretString": "test", 
    "VersionStages": [
        "AWSCURRENT"
    ], 
    "CreatedDate": 1539621655.505, 
    "ARN": "arn:aws:secretsmanager:us-east-1:........:test"
}
```
here's a response from localstack:
```
{
    "Name": "mike", 
    "VersionId": "A435958A-D821-4193-B719-B7769357AER4", 
    "SecretString": "test", 
    "VersionStages": [
        "AWSCURRENT"
    ], 
    "CreatedDate": "2018-05-23 13:16:57.198000", 
    "ARN": "arn:aws:secretsmanager:us-east-1:1234567890:secret:mike-rIjad"
}
```

You can see the CreatedDate fields are in different formats.

**Comment by MichaelDSalzman** [comment] 2018-11-03 19:55
Looks like the issue is with the moto library. There's a PR submitted for it: https://github.com/spulec/moto/pull/1898

**Comment by hugocordz** [comment] 2019-01-04 16:47
You know when this will be released or how to make a workaround for this?

**Comment by vergnes** [comment] 2019-05-30 15:59
moto 1.3.8 is out. It contains several enhancements for the secrets manager: i.e. fixing this bug, support secret deletion, support multiple secrets, ...
https://github.com/spulec/moto/compare/1.3.7...1.3.8
When all those changes can be back port to moto-ext?

**Comment by whummer** [comment] 2020-03-31 19:52
Thanks for reporting @akichidis @MichaelDSalzman @hugocordz @vergnes . This should be fixed in the latest version - an integration test has been added in #2223 . Please report if the problem persists. Thanks

**Closed by whummer** 2020-03-31 19:52 UTC
