### ISSUE TITLE
DynamoDB stream + invoke lambda function

### ISSUE THREAD

**Issue by tibeoh** [localstack/localstack#519] opened 2017-12-19 11:45 UTC
Hi,

I have  issue to invoke lambda by a DynamoDB stream.

I created a DynamoDB table and Lambda function:
```aws dynamodb create-table --endpoint="http://localhost:4569" --cli-input-json file://ddb/dev_sensors-live-distances.json```
```aws lambda create-function --endpoint="http://localhost:4574" --role=r1 --cli-input-json file://lambda/live-analyse.json --zip-file fileb://../live-analyse/live-analyse.zip```

I created an event source mapping too:
```
aws lambda create-event-source-mapping \
--function-name  live-analyse\
--event-source *************************** \
--batch-size 100 \
--starting-position LATEST \
--endpoint http://localhost:4574
```

With ********* is the result of: ```aws dynamodb describe-table --endpoint="http://localhost:4569" --table-name="dev_sensors-live-distances" | grep LatestStreamArn```

How can I check logs of my lambda function?
I only have this returned in localstack terminal:
```2017-12-19T11:41:29:WARNING:localstack.services.dynamodb.dynamodb_listener: Unknown table: dev_sensors-live-distances not found in {}```

My lambda function save new items in an other dynamodb table, but this one is already empty. So I guess my lambda is not inkoked...

Thanks for you help.

PS: I'm on MacOS and run localstack with docker. ```localstack start --docker```

**Comment by teroxik** [comment] 2017-12-19 18:19
@tibeoh 
Hi current version of mapping which works for me I'm getting using the dynamoDB streams:

```
STREAM_ARN=`aws dynamodbstreams list-streams --endpoint ${LOCAL_HOST}:4570 --region us-east-1 | jq -r '.Streams[0].StreamArn'\`
```
I have described here, that the output of these 2 commands differs, maybe it should be fixed:

https://github.com/localstack/localstack/issues/491

**Comment by whummer** [comment] 2018-01-09 00:22
Thanks for reporting @tibeoh, which language is your lambda written in? Invoking Lambdas from DynamoDB events has been be fixed in #518. Can you please confirm whether your example works with the latest version?

Lambda logging has been improved in a recent PR (#542). You should be able to see the output of your lambdas if setting the `DEBUG=1` environment variable or `--debug` CLI flag.

If the problem persists, can you please provide a small example to reproduce the issue. Thanks

**Comment by ccorcos** [comment] 2018-08-16 00:37
Similar issue here.

I'm getting `WARNING:localstack.services.dynamodb.dynamodb_listener: Unknown table: history not found in {}`. 


However, the table is there with a stream arn.

```
❯❯❯ awslocal dynamodb describe-table --table-name "history"
{
    "Table": {
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/history",
        "AttributeDefinitions": [
            {
                "AttributeName": "time_window",
                "AttributeType": "N"
            },
            {
                "AttributeName": "record_id",
                "AttributeType": "S"
            }
        ],
        "ProvisionedThroughput": {
            "NumberOfDecreasesToday": 0,
            "WriteCapacityUnits": 20,
            "LastIncreaseDateTime": 0.0,
            "ReadCapacityUnits": 20,
            "LastDecreaseDateTime": 0.0
        },
        "TableSizeBytes": 566,
        "TableName": "history",
        "TableStatus": "ACTIVE",
        "StreamSpecification": {
            "StreamViewType": "NEW_IMAGE",
            "StreamEnabled": true
        },
        "LatestStreamLabel": "2018-08-16T00:29:26.863",
        "KeySchema": [
            {
                "KeyType": "HASH",
                "AttributeName": "record_id"
            },
            {
                "KeyType": "RANGE",
                "AttributeName": "time_window"
            }
        ],
        "ItemCount": 1,
        "CreationDateTime": 1534379366.863,
        "LatestStreamArn": "arn:aws:dynamodb:ddblocal:000000000000:table/history/stream/2018-08-16T00:29:26.863"
    }
}
```

But the streams aren't there...

```
❯❯❯ awslocal dynamodbstreams list-streams
{
    "LastEvaluatedStreamArn": "TODO",
    "Streams": []
}
```

Meanwhile my functions are there and they're connected with a mapping...

```
❯❯❯ awslocal lambda list-functions
{
    "Functions": [
        {
            "Version": "$LATEST",
            "FunctionName": "historyToEdits",
            "CodeSize": 50,
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:historyToEdits",
            "Environment": {},
            "Handler": "historyToEdits.handler",
            "Timeout": 3,
            "Runtime": "nodejs8.10"
        }
    ]
}
❯❯❯ awslocal lambda list-event-source-mappings
{
    "EventSourceMappings": [
        {
            "UUID": "ba7c7be5-a6fa-417e-91bb-b75bd5c10bdb",
            "StateTransitionReason": "User action",
            "LastModified": 1534379481.0,
            "BatchSize": 100,
            "State": "Enabled",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:historyToEdits",
            "EventSourceArn": "arn:aws:dynamodb:ddblocal:000000000000:table/history/stream/2018-08-16T00:29:26.863",
            "LastProcessingResult": "OK"
        }
    ]
}
```

Any ideas?

**Comment by ccorcos** [comment] 2018-08-16 02:10
Alright, several hours down the drain and I figured out my issue. Dynamodb is persisted but Dynamodbstreams are not persisted. This leaves localstack in an awkard state.

**Comment by whummer** [comment] 2019-11-08 19:25
Thanks for digging into this. Closing this issue in favor of #900

**Closed by whummer** 2019-11-08 19:25 UTC
Labels: bug, enhancement
