### ISSUE TITLE
Lambda Crashes Running Non-Existant Ruby docker image

### ISSUE THREAD

**Issue by theomarkkuspaul** [localstack/localstack#2448] opened 2020-05-23 05:19 UTC
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
After setting up localstack from a fresh installation, I create a lambda function passing the `—runtime ruby` arg to the `awslocal lambda create-function` command. A bundled “Hello World” ruby function is also included. After this, an api gateway is constructed using awslocal, and I expose a GET endpoint to invoke the lambda, alongside a local deployment of the api gateway.

When I hit the endpoint and the lambda is run, digging through the stack trace I have found this error:

`Unable to find image 'lambci/lambda:ruby' locally`

When I visit LambCI’s docker hub repository https://hub.docker.com/r/lambci/lambda/ it looks like they no longer have a tag for their ruby distribution. It appears they only support `ruby2.5`

## Expected behavior
A ruby lambda script is executed when I invoked by an API Gateway.

## Actual behavior
Crash and burn.

# Steps to reproduce
## Command used to start LocalStack
`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
    #!/bin/sh
    
    API_NAME=api
    STAGE=test
    
    function fail() {
        echo $2
        exit $1
    }
    
    awslocal lambda create-function \
        --function-name ${API_NAME} \
        --runtime ruby2.5 \
        --handler function.handler \
        --memory-size 128 \
        --zip-file fileb://function.zip \
        --role arn:aws:iam::123456:role/irrelevant
    
    [ $? == 0 ] || fail 1 "Failed: AWS / lambda / create-function"
    
    LAMBDA_ARN=$(awslocal lambda list-functions --query "Functions[?FunctionName==\`${API_NAME}\`].FunctionArn" --output text)
    
    awslocal apigateway create-rest-api \
        --name ${API_NAME}
    
    [ $? == 0 ] || fail 2 "Failed: AWS / apigateway / create-rest-api"
    
    API_ID=$(awslocal apigateway get-rest-apis --query "items[?name==\`${API_NAME}\`].id" --output text)
    PARENT_RESOURCE_ID=$(awslocal apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/`].id' --output text)
    
    awslocal apigateway create-resource \
        --rest-api-id ${API_ID} \
        --parent-id ${PARENT_RESOURCE_ID} \
        --path-part "{somethingId}"
    
    [ $? == 0 ] || fail 3 "Failed: AWS / apigateway / create-resource"
    
    RESOURCE_ID=$(awslocal apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/{somethingId}`].id' --output text)
    
    awslocal apigateway put-method \
        --rest-api-id ${API_ID} \
        --resource-id ${RESOURCE_ID} \
        --http-method GET \
        --request-parameters "method.request.path.somethingId=true" \
        --authorization-type "NONE" \
    
    [ $? == 0 ] || fail 4 "Failed: AWS / apigateway / put-method"
    
    awslocal apigateway put-integration \
        --rest-api-id ${API_ID} \
        --resource-id ${RESOURCE_ID} \
        --http-method GET \
        --type AWS_PROXY \
        --integration-http-method POST \
        --uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDA_ARN}/invocations \
        --passthrough-behavior WHEN_NO_MATCH \
    
    [ $? == 0 ] || fail 5 "Failed: AWS / apigateway / put-integration"
    
    awslocal apigateway create-deployment \
        --rest-api-id ${API_ID} \
        --stage-name ${STAGE} \
    
    [ $? == 0 ] || fail 6 "Failed: AWS / apigateway / create-deployment"
    
    ENDPOINT=http://localhost:4567/restapis/${API_ID}/${STAGE}/_user_request_/HowMuchIsTheFish
    
    echo "API available at: ${ENDPOINT}"
    
    echo "Testing GET:"
    curl -i ${ENDPOINT}
    
    echo "Testing POST:"
    curl -iX POST ${ENDPOINT}Heavily inspired by https://gist.github.com/crypticmind/c75db15fd774fe8f53282c3ccbe3d7ad except updated the lambda runtime to be `ruby`

Thanks for taking a look :wave:

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-185) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment] 2021-10-03 21:31
Thanks for reporting @theomarkkuspaul . Looks like this is the expected behavior - at least when looking at the AWS Lambda docs here which mentions only `ruby2.5`/`ruby2.7` as valid runtimes: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#w316aac39c35 

Also, it seems that in the sample snippet you've shared, it is actually using the `--runtime ruby2.5` string - does the issue still persist in this case? 

Closing this as obsolete / cannot reproduce, but please do let us know if you still believe this needs to be fixed, or if the behavior in fact diverges from AWS. Thanks for your help!

**Closed by whummer** 2021-10-03 21:31 UTC
