### ISSUE TITLE
access redshift using psycopg2 is not working

### ISSUE THREAD

**Issue by shrishinde** [localstack/localstack#352] opened 2017-09-27 07:02 UTC
I know psycopg2 is not in the supported client's list but I need to use psycopg2 as product code is written using this module.

Connection try is hanging when tried connecting through psycopg2 but works fine when boto3 is used.

```
import boto3
import psycopg2

# Working fine with boto3
client = boto3.client('redshift', endpoint_url='http://127.0.0.1:20233/')
print client.describe_clusters()

# waiting indefinitely on connect call
con = psycopg2.connect(dbname='test', host="127.0.0.1", port=20233, user='user', password='password')
cur = con.cursor()
print cur.execute("SELECT * FROM `table`;")
cur.fetchall()
cur.close()
con.close()
```

Any idea what is happening and how can I resolve this?

**Comment by whummer** [comment] 2017-09-30 18:23
This seems to be a duplicate of #63 . Please note that querying redshift tables is not currently supported, but there seem to be some promising frameworks out there that we could integrate into LocalStack, for example https://github.com/opt-tech/redshift-fake-driver . Would you be able to contribute a pull request to add this new functionality? That would be great - I'd be happy to provide help and assistance during the process. Thanks

**Comment by whummer** [comment] 2019-11-08 17:20
Closing in favor of #833

**Closed by whummer** 2019-11-08 17:20 UTC
Labels: duplicate, enhancement, feature-missing
