### ISSUE TITLE
bug: cannot create more than 50 instances of AWS::AppSync::Resolver

### ISSUE THREAD

**Issue by fancywriter** [localstack/localstack#8783] opened 2023-07-31 22:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have an application with a lot of AppSync endpoints. It's being deployed to AWS just fine, but when we try to deploy it to localstack to run some tests, we are getting strange error.

```localstack  | 2023-07-31T22:54:10.356 ERROR --- [functhread15] l.s.c.e.template_deployer  : Dependencies for "SampleResolver50" not yet satisfied, retrying in next loop: Unresolved dependencies: SampleDataSource50
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1310, in do_apply_changes_in_loop
localstack  |     should_deploy = self.prepare_should_deploy_change(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1406, in prepare_should_deploy_change
localstack  |     resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 318, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 630, in _resolve_refs_recursively
localstack  |     value[key] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 318, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 630, in _resolve_refs_recursively
localstack  |     value[key] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 318, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 443, in _resolve_refs_recursively
localstack  |     raise DependencyNotYetSatisfied(resource_ids=resource_logical_id, message="")
localstack  | localstack.services.cloudformation.service_models.DependencyNotYetSatisfied: Unresolved dependencies: SampleDataSource50
localstack  | 2023-07-31T22:54:10.361 ERROR --- [functhread15] l.s.c.e.template_deployer  : Dependencies for "SampleResolver50" not yet satisfied, retrying in next loop: Unresolved dependencies: SampleDataSource50
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1310, in do_apply_changes_in_loop
localstack  |     should_deploy = self.prepare_should_deploy_change(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1406, in prepare_should_deploy_change
localstack  |     resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 318, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 630, in _resolve_refs_recursively
localstack  |     value[key] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 318, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 630, in _resolve_refs_recursively
localstack  |     value[key] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 318, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 443, in _resolve_refs_recursively
localstack  |     raise DependencyNotYetSatisfied(resource_ids=resource_logical_id, message="")
localstack  | localstack.services.cloudformation.service_models.DependencyNotYetSatisfied: Unresolved dependencies: SampleDataSource50
localstack  | 2023-07-31T22:54:10.362 ERROR --- [functhread15] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "my-test-stack": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SampleResolver50', 'PhysicalResourceId': None, 'ResourceType': 'AWS::AppSync::Resolver', 'Scope': [], 'Details': []}}] Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1265, in _run
localstack  |     self.do_apply_changes_in_loop(changes, stack)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1373, in do_apply_changes_in_loop
localstack  |     raise Exception(
localstack  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SampleResolver50', 'PhysicalResourceId': None, 'ResourceType': 'AWS::AppSync::Resolver', 'Scope': [], 'Details': []}}]
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1265, in _run
localstack  |     self.do_apply_changes_in_loop(changes, stack)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1373, in do_apply_changes_in_loop
localstack  |     raise Exception(
localstack  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'SampleResolver50', 'PhysicalResourceId': None, 'ResourceType': 'AWS::AppSync::Resolver', 'Scope': [], 'Details': []}}]
```

What's important, it must be at least 50+ instances of resolvers depending on 50+ **different** data sources to reproduce. If I create just 50 resolvers pointing to the same data source (which is useless for production), it will be deployed without errors...

### Expected Behavior

Expect to see everything deployed without any issues.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro:2.2.0
    container_name: localstack
    ports:
      - "4566:4566"         
      - "4510-4559:4510-4559"  
      - "53:53"             
      - "53:53/udp"          
      - "443:443"              
      - '4571:4571'
    environment:
      - MAIN_CONTAINER_NAME=localstack_test
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CFN_VERBOSE_ERRORS=true
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-} 
      - PROVIDER_OVERRIDE_LAMBDA=asf 
    volumes:
      - '${TMPDIR:-./localstack}:/var/lib/localstack'
      - '${TMPDIR:-/tmp/}localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I have prepared script on Python (boto3) to reproduce it easily in few seconds:

```python
import json

import boto3


def sample_ds(i):
    return {
        "Type": "AWS::AppSync::DataSource",
        "Properties": {
            "ApiId": {"Fn::GetAtt": ["GraphQlApi", "ApiId"]},
            "Name": f"sample_ds_{i}",
            "Type": "AWS_LAMBDA"
        }
    }


def sample_resolver(i, ds):
    return {
        "Type": "AWS::AppSync::Resolver",
        "Properties": {
            "ApiId": {"Fn::GetAtt": ["GraphQlApi", "ApiId"]},
            "TypeName": "Query",
            "FieldName": f'sample_resolver_{i}',
            "DataSourceName": {"Fn::GetAtt": [ds, "Name"]}
        }
    }


if __name__ == '__main__':
    n = 51  # if I change to any value lower like 50 - all works good, but for >= 51 fails

    resources = {
        "GraphQlApi": {
            "Type": "AWS::AppSync::GraphQLApi",
            "Properties": {
                "Name": "gql-api",
                "AuthenticationType": "API_KEY"
            }
        }
    }

    for i in range(n):
        ds = f'SampleDataSource{i}'
        resources[ds] = sample_ds(i)
        resources[f'SampleResolver{i}'] = sample_resolver(i, ds)

    template = json.dumps({
        "AWSTemplateFormatVersion": "2010-09-09",
        "Description": "Test CloudFormation template",
        "Resources": resources
    })

    s3 = boto3.client('s3', endpoint_url='http://localhost:4566')
    cf = boto3.client('cloudformation', endpoint_url='http://localhost:4566')

    s3.create_bucket(Bucket='deployment-bucket', CreateBucketConfiguration={'LocationConstraint': 'eu-west-1'})
    s3.put_object(Bucket='deployment-bucket', Key='cf-template.json', Body=template)
    cf.create_stack(StackName='my-test-stack',TemplateURL='https://s3.amazonaws.com/deployment-bucket/cf-template.json')

```

### Environment

```markdown
- OS: GNU/Linux 
- LocalStack: 2.2.0
- Docker: 23.0.3
- Docker-compose-2.17.2
- Python-3.11.4 (for running script, not for localstack runtime)
- boto3-1.28.8
```

### Anything else?

Seems like number 50 might be fixed somewhere in configuration - any way we can make it more conservative (wait more seconds to dependencies to be ready?) to make it work for 100+ AppSync resolvers?

**Comment by simonrw** [comment] 2023-08-29 10:28
Hi @fancywriter, thanks for reporting this issue. We are currently making some improvements across the board to our CloudFormation resource providers. This means that a fix is on the way, but not right now. If this issue is urgent, please [raise a request with our support](https://docs.localstack.cloud/getting-started/help-and-support/#pro-support).

**Comment by fancywriter** [comment] 2023-09-01 14:19
@simonrw thanks for reply.
No rush on that, we have a workaround. Good to know that sooner or later it's gonna be fixed.

**Comment by simonrw** [comment] 2024-04-21 13:51
Hi @fancywriter, I noted that we were making some significant changes to CloudFormation, and I'm pleased to say I cannot reproduce this issue with the latest docker image. Please pull the latest image and confirm.

I will close this issue for now, but if you still experience this problem feel free to re-open and comment with additional details.

Thanks!

**Closed by simonrw** 2024-04-21 13:51 UTC
Labels: type: bug, aws:cloudformation, aws:appsync, status: backlog
