### ISSUE TITLE
Error when putting no data to s3

### ISSUE THREAD

**Issue by PaulPopat** [localstack/localstack#1187] opened 2019-03-12 15:48 UTC
Hello

I have been writing a CMS that interacts with s3. We are currently handling the case of a user trying to register a file that they haven't uploaded. This means that we could be copying a file from a temporary location in s3 to a new permanent location. We are trying to use a try catch (in dotnet core) around the copy command (using the IAmazonS3), which is looking for a NotFound exception. This works fine when getting the metadata for an object and then performing the operation but we are concerned about concurrency so wanted to do this during the actual copy, so as to avoid the user seeing server errors.

When we run our system tests for this, localstack appears to not be returning a response, which means that our servers are hanging. I have done a bit of debugging and got a stack trace for an error in localstack (see bellow) which seems to indicate a problem when trying put a file with no data, but please do let me know if I have read it wrong.

```
localstack_1  | 2019-03-12 15:07:16,986 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2019-03-12 15:07:16,989 INFO supervisord started with pid 1
localstack_1  | 2019-03-12 15:07:17,991 INFO spawned: 'dashboard' with pid 8
localstack_1  | 2019-03-12 15:07:17,992 INFO spawned: 'infra' with pid 9
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2019-03-12T15:07:18:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  | 2019-03-12T15:07:18:INFO:werkzeug:  * Restarting with stat
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | 2019-03-12T15:07:19:WARNING:werkzeug:  * Debugger is active!
localstack_1  | 2019-03-12 15:07:19,063 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2019-03-12 15:07:19,063 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2019-03-12T15:07:19:INFO:werkzeug:  * Debugger PIN: 287-679-467
localstack_1  | * Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:07:21] "GET / HTTP/1.1" 200 -
localstack_1  | Ready.
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:07:38] "DELETE /dev-cms HTTP/1.1" 404 -
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:07:38] "PUT /dev-cms HTTP/1.1" 200 -
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:09:18] "PUT /dev-cms/this/request/has/no/data HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 98, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack_1  | response = self.handle_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 568, in key_response
localstack_1  | response = self._key_response(request, full_url, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 621, in _key_response
localstack_1  | return self._key_response_put(request, body, bucket_name, query, key_name, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 717, in _key_response_put
localstack_1  | storage=storage_class, acl=acl, src_version_id=src_version_id)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/models.py", line 885, in copy_key
localstack_1  | key = key.copy(dest_key_name)
localstack_1  | AttributeError: 'NoneType' object has no attribute 'copy'
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:09:19] "PUT /dev-cms/this/request/has/no/data HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 98, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack_1  | response = self.handle_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 568, in key_response
localstack_1  | response = self._key_response(request, full_url, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 621, in _key_response
localstack_1  | return self._key_response_put(request, body, bucket_name, query, key_name, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 717, in _key_response_put
localstack_1  | storage=storage_class, acl=acl, src_version_id=src_version_id)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/models.py", line 885, in copy_key
localstack_1  | key = key.copy(dest_key_name)
localstack_1  | AttributeError: 'NoneType' object has no attribute 'copy'
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:09:20] "PUT /dev-cms/this/request/has/no/data HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 98, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack_1  | response = self.handle_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 568, in key_response
localstack_1  | response = self._key_response(request, full_url, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 621, in _key_response
localstack_1  | return self._key_response_put(request, body, bucket_name, query, key_name, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 717, in _key_response_put
localstack_1  | storage=storage_class, acl=acl, src_version_id=src_version_id)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/models.py", line 885, in copy_key
localstack_1  | key = key.copy(dest_key_name)
localstack_1  | AttributeError: 'NoneType' object has no attribute 'copy'
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:09:27] "PUT /dev-cms/this/request/has/no/data HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 98, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack_1  | response = self.handle_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 568, in key_response
localstack_1  | response = self._key_response(request, full_url, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 621, in _key_response
localstack_1  | return self._key_response_put(request, body, bucket_name, query, key_name, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 717, in _key_response_put
localstack_1  | storage=storage_class, acl=acl, src_version_id=src_version_id)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/models.py", line 885, in copy_key
localstack_1  | key = key.copy(dest_key_name)
localstack_1  | AttributeError: 'NoneType' object has no attribute 'copy'
localstack_1  | 127.0.0.1 - - [12/Mar/2019 15:09:52] "PUT /dev-cms/this/request/has/no/data HTTP/1.1" 500 -
localstack_1  | Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 98, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack_1  | response = self.handle_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 568, in key_response
localstack_1  | response = self._key_response(request, full_url, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 621, in _key_response
localstack_1  | return self._key_response_put(request, body, bucket_name, query, key_name, headers)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 717, in _key_response_put
localstack_1  | storage=storage_class, acl=acl, src_version_id=src_version_id)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/models.py", line 885, in copy_key
localstack_1  | key = key.copy(dest_key_name)
localstack_1  | AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by whummer** [comment] 2019-11-30 20:23
Thanks for reporting @PaulPopat . I'm unable to reproduce this issue - seems to have been fixed in the latest version?

```
$ touch empty_file
$ awslocal s3 mb s3://test
make_bucket: test
$ awslocal s3 cp empty_file s3://test/empty_file
upload: ./empty_file to s3://test/empty_file
```

Hope that helps. If the problem persists, please provide a small, self-contained example (ideally a sequence of `awslocal` commands) to help reproduce it. Thanks

**Closed by whummer** 2019-11-30 20:23 UTC
